### ISSUE TITLE
[ST] Add migration system tests with JBOD support in KRaft mode

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#10000]
With the support for JBOD disks in KRaft mode added by https://github.com/strimzi/strimzi-kafka-operator/pull/9936 and it's usage during migration as well (together with a fix by https://github.com/strimzi/strimzi-kafka-operator/pull/9993) we should add additional system tests for migration about migrate and rollback an Apache Kafka cluster using multiple JBOD disks.

**Comment by scholzj** [comment]
Triaged on the community call on 2.5.2024: Lukas is already working on this.
