### ISSUE TITLE
Performance Issue with SCRAM-SHA Credentials Cache at 4800+ `KafkaUsers`

### ISSUE THREAD

**Issue by see-quick** [strimzi/strimzi-kafka-operator#10021]
### Related problem

The SCRAM-SHA credentials cache in the User Operator fails to maintain readiness under high user load scenarios. This issue becomes apparent when the number of Kafka users managed by the User Operator approaches 4800. At this point, the system throws a `RuntimeException` indicating that the SCRAM-SHA Credentials Cache is not ready, which prevents the User Operator from processing further user reconciliations effectively. 

### Suggested solution

I would like to enhance the cache initialization and error-handling mechanisms to ensure that the cache can handle high loads without becoming unready. Possible improvements could include:
- Implementing an exponential back-off retry mechanism during cache loading to handle transient failures more gracefully? 
- Adjusting the refresh interval dynamically based on system load and error rates to ensure the cache remains up-to-date without overwhelming the system.

### Additional context

- The problem typically manifests at around 4800 users but may vary slightly based on cluster performance and specific configurations.
The current caching mechanism is critical for reducing Kafka broker load by minimizing unnecessary calls to the Kafka Admin API.
- This issue has been observed consistently in environments with high user churn and in stress-testing scenarios designed to simulate peak loads.
- Moreover the UO configuration changes does not have any impact on how many `KafkaUsers` can UO handle. 
```java
Use Case: capacityDefaultUseCase
+------------+--------------------------+---------------------+---------------------------------+-------------------------------+----------------------+------------------------------+---------------------------------+--------------------------------------+------------------------------------+-------------------------------------+----------------------------------+
| Experiment | IN: OPERATION_TIMEOUT_MS | IN: WORK_QUEUE_SIZE | IN: CONTROLLER_THREAD_POOL_SIZE | IN: CACHE_REFRESH_INTERVAL_MS | IN: BATCH_QUEUE_SIZE | IN: BATCH_MAXIMUM_BLOCK_SIZE | IN: BATCH_MAXIMUM_BLOCK_TIME_MS | IN: USER_OPERATIONS_THREAD_POOL_SIZE | OUT: Successful KafkaUsers Created | jvm_memory_used_megabytes_total.txt | system_load_average_per_core.txt |
| 1          | 300000                   | 10000               | 50                              | 15000                         | 1024                 | 100                          | 100                             | 50                                   | 4800                               | 716.524856                          | 0.23875                          |
| 2          | 300000                   | 10000               | 100                             | 20000                         | 2048                 | 200                          | 50                              | 100                                  | 4800                               | 877.894032                          | 0.2825                           |
| 3          | 300000                   | 10000               | 75                              | 15000                         | 1500                 | 150                          | 75                              | 75                                   | 4800                               | 548.884896                          | 0.2825                           |
| 4          | 300000                   | 10000               | 100                             | 30000                         | 4096                 | 300                          | 100                             | 100                                  | 4800                               | 638.626608                          | 0.243125                         |
| 5          | 300000                   | 10000               | 50                              | 10000                         | 512                  | 50                           | 25                              | 50                                   | 4800                               | 725.024336                          | 0.2375                           |
+------------+--------------------------+---------------------+---------------------------------+-------------------------------+----------------------+------------------------------+---------------------------------+--------------------------------------+------------------------------------+-------------------------------------+----------------------------------+
```

Logs and error messages related to the issue: [1]

[1] - https://gist.github.com/see-quick/d85dece01a711b5be9f2507a30e0124b

**Comment by scholzj** [comment]
Please share the full log and not just a snippet.

**Comment by see-quick** [comment]
The logs that I had is quite huge...It contained a lot of other test cases...so let me break it into one test case.

[user-operator-log-performance-issue.txt](https://github.com/strimzi/strimzi-kafka-operator/files/15094586/user-operator-log-performance-issue.txt)

**Comment by see-quick** [comment]
So based on the suggestion from @scholzj (i.e., try to increase the length of the username), we found out that it might be the problem of the LIMIT for the `KafkaAdmin API` request. We found out that `KafkaUsers`:

- with the length of 22 chars it can handle over 4800 users
- with the length of 44 chars it can handle over 4100 users
....
Interesting fact is that it's not linear (i.e., 44 chars does allow more than 2400 users to be created). So there might be some compression involved....

Here is another log from User Operator but with 44 chars usernames [1].

[1] - https://drive.google.com/file/d/1kAj27sWi79kGs96i3vCWegpfhrz_cBJV/view?usp=sharing

**Comment by see-quick** [comment]
I will not be able to attend today's triage but to summarize this problem occurs in **ZK-based clusters**. On KRaft clusters the limit is around 19 300 KafkaUsers [1] with identical environment and flavour machines.

[1] - https://github.com/strimzi/strimzi-kafka-operator/pull/10018

**Comment by scholzj** [comment]
Triaged on the community call on 2.5.2024: There might be some ZooKeeper tunning that might help. But given that ZooKeeper is being removed, it does not sem like it is worth a deeper investigation or changes in Kafka / ZooKeeper should there be any needed. This should be closed.
