### ISSUE TITLE
Running with Minishift anyuid addon

### ISSUE THREAD

**Issue by sjwoodman** [strimzi/strimzi-kafka-operator#1009]
Strimzi does not work with the Minishift `anyuid` addon. This is because the Kafka/ZooKeeper etc. processes will run as the user created in the dockerfiles. As this user is not part of the root group they cannot read from the PVCs. For example, the Zookeeper TLS sidecar pod fails with the following:

```
Error reading certificate file: /etc/tls-sidecar/zookeeper-nodes/my-cluster-zookeeper-0.crt
  | error queue: 140DC002: error:140DC002:SSL routines:SSL_CTX_use_certificate_chain_file:system lib
  | error queue: 20074002: error:20074002:BIO routines:FILE_CTRL:system lib
```

**Comment by scholzj** [comment]
This should be now fixed on master. Feel free to give it a try and let us know if it helped.

**Comment by matzew** [comment]
works w/ 0.8.2  (tested it w/ `anyuid`)
