### ISSUE TITLE
Add Cruise Control timer metrics to the Topic Operator

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#10124]
### Related problem

In #9216, we created additional metrics for requests to external services (Kubernetes and Kafka). These additional metrics are disabled by default, but can be enabled to track down performance issues, or while doing load tests.

In #9483, we introduced the topic replication factor change feature, which integrates the Topic Operator with Cruise Control REST API.

### Suggested solution

It would be good to also have timer metrics for the `topic_configuration` and `user_tasks` requests. These should be present only when the additional metrics and Cruise Control integration are enabled.

**Comment by ppatierno** [comment]
Triaged on 30/5/2024: it was fixed by #10160
