### ISSUE TITLE
[CRD-v1] Switch the User Operator reconciliationIntervalSeconds to int in v1

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#10164]
### Related problem

Right now, the spec field `reconciliationIntervalSeconds` is defined as int for the Topic Operator, and long for the User Operator. At runtime, this determines a different behavior when setting a value that overflows int. The User Operator will take and use it, while the Topic Operator will fail, which is better, as the user can spot the configuration error quickly.

### Suggested solution

The proposal is to switch the User Operator to use int as `reconciliationIntervalSeconds` in v1, so that the behavior of the entity operators is the same. This change has backward compatibility implications, so I'm proposing to do it when upgrading schemas to v1.

**Comment by ppatierno** [comment]
@fvaleri how does this one cope with https://github.com/strimzi/strimzi-kafka-operator/pull/10158 which moved in the opposite direction, or?

**Comment by fvaleri** [comment]
> @fvaleri how does this one cope with #10158 which moved in the opposite direction, or?

This is only to align the spec between TO and UO. The spec changes of that PR were reverted (int is fine as we use seconds as time unit), so I only changed the implementation where we map to milliseconds (was int, now it's long like the UO).

**Comment by ppatierno** [comment]
Triaged on 30/5/2024: agreed on the call that we should have alignment on using milliseconds for the reconciliation interval on both TO and UO. Going to close this one and @fvaleri opening a new one for it.
