### ISSUE TITLE
[CRD-v1] Remove field reconciliationIntervalSeconds

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#10176]
### Related problem

The `reconciliationIntervalSeconds` field in Topic and User Operators' spec is deprecated in favor of `reconciliationIntervalMs`.

### Suggested solution

Remove `reconciliationIntervalSeconds` from user and topic operator spec and model classes.

### Additional context

Deprecation PR: #10175.

**Comment by scholzj** [comment]
We do not need to track individual fields. We have to remove all deprecated fields. This should be closed.

**Comment by fvaleri** [comment]
Ok, makes sense. Sorry.
