### ISSUE TITLE
[Docs]: a list of runtime/provided 3rd party libraries in Kafka Connect

### ISSUE THREAD

**Issue by SamoylovMD** [strimzi/strimzi-kafka-operator#10189]
### Suggestion / Problem

We use Strimzi to manage Kafka Connect clusters with our custom sets of SMTs and source/sink plugins. These plugins are built as fat/shadow jar files and put to plugins folder to custom kafka connect image built as this:

```
FROM quay.io/strimzi/kafka:$strimziVersion-kafka-$kafkaVersion

COPY ./. /opt/kafka/plugins
```

However, I found out that our custom plugins sometimes conflict with runtime libraries included into base image. The examples can include logging libraries (`slf4j-api` and other slf4j libs). I want to sync the dependencies with strimzi runtime, but I'm struggling to find the exact versions of libraries included into an image, without obtaining the list from the image directly. Is there any documented list of runtime provided libraries included into every image, or is there any other way I could address this problem?

**Comment by scholzj** [comment]
No, we do not provide any list like that. Any extra libraries Strimzi adds to the images are based on these pom files: https://github.com/strimzi/strimzi-kafka-operator/tree/main/docker-images/artifacts/kafka-thirdparty-libs. So you can easily get the list from GitHub for your Strimzi / Kafka version. We also provide SBOM files as part of every Strimzi release where all included libraries should be listed as well IIRC.

**Comment by ppatierno** [comment]
Triaged on 13/6/2024: it seems there is a general agreement with what @scholzj said. We already have several ways to get this information, no need to add more documentation which would bring more work to have it up to date. @SamoylovMD I am going to close this one, feel free to re-open if you don't agree and want to discuss more.
