### ISSUE TITLE
[Bug]: Scaling-Down Stuck if Pods Restart during Scaling Down 

### ISSUE THREAD

**Issue by kos-team** [strimzi/strimzi-kafka-operator#10231]
### Bug Description

When scaling down the zookeeper cluster from 5 replicas to 3 replicas while the two replicas to be deleted are restarted due to some external faults or rebalancing, the scaling operation will be permanently stuck and the two nodes will stuck in CrashLoopBackOff. The two pods are first restarted before they get deleted. Per the operators' design, the two pods won't be deleted before they first successfully restart. However, the restart will never be successful due to missing certificates.

On restart, the two nodes will try to read the certificate from the mounted volume from the `opt/kafka/zookeeper-node-certs`. The certificates are from the volume mounted from a Kubernetes Secret object, which is directly written by the operator. Here, although the operator did not delete the two nodes, it already removed the certificates for the two nodes. So these two nodes always crash on startup. This causes the two nodes keep crashing and the scale down never happens.

### Steps to reproduce

1. Deploy the Kafka with 5 ZK replicas
2. Simulate the Pod crash by killing pod-3
3. Before the ZK pod gets healthy, issue the scale down by changing ZooKeeper replicas to 3
4. Observe that pod-3 never is able to start, crashing with error log
```
Detected Zookeeper ID 4
Preparing truststore
Adding opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore
Certificate was added to keystore
Preparing truststore is complete
Looking for the right CA
No CA found. Thus exiting.
```

### Expected behavior

The operator should be able to tolerate transient failures of application Pods, and correctly scale down the ZooKeeper cluster.

### Strimzi version

0.41.0

### Kubernetes version

1.27

### Installation method

YAML

### Infrastructure

Kind

**Comment by scholzj** [comment]
This can be reproduced as described in the item description. But I do not think it has a simple fix. And given it is an edge situation, that ZooKeeper scaling is not something that is done very often, and that ZooKeeper is on its way out from Kafka, we need to decide if this is worth the effort.

**Comment by scholzj** [comment]
Discussed on the community call on 10.7.2024: This issue can indeed happen. But given the probability of this issue occurring, the complexity to fix this and the fact that ZooKeeper will be removed soon, we decided to not address this.
