### ISSUE TITLE
Failed upgrade from Strimzi 0.5.0 to 0.8.0

### ISSUE THREAD

**Issue by thbeh** [strimzi/strimzi-kafka-operator#1024]
Upgraded both k8 (1.9.2) and strimzi-0.5.0 to k8 (1.11.2) and strimzi-0.8.0. Unsuccessful deployment with liveness and readiness probe failed. Is that an issue of RBAC? Any advice?

**Comment by scholzj** [comment]
So ... does that mean that your cluster operator is looping? Or that the Kafka cluster doesn't work? Could you share the logs from the failing component? 

Also, have you done upgrade in terms of upgrading the software from 0.5.0 to 0.8.0? Or clean install? There was some issue in 0.8.0 related to upgrading - that is why we released 0.8.1. But TBH we never tried upgrade from 0.5.0. Latest version we tried upgrading from was 0.6.0.

**Comment by thbeh** [comment]
It's looping and it's a clean install for both k8 (1.11.2) and cluster-operator (0.8.0). I have attached the logs for your attention.

[logs-from-strimzi-cluster-operator-in-strimzi-cluster-operator-548755778c-dzvx6.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2511848/logs-from-strimzi-cluster-operator-in-strimzi-cluster-operator-548755778c-dzvx6.txt)

**Comment by scholzj** [comment]
This seems to be the same problem as described in #544 - your API server certificate doesn't seem to contain the right hostnames (the default / usual API hostname is `kubernetes.default.svc`, but your certificate seems to have only `kubernetes.default`).

The best solution would be if you could fix your certificate. If that is not possible, you can try the approach described in #544 to work around it. However, you should expect that the TOpic Operator and User Operators will nto work for you as this workaround cannot be currently applied to them (see #993). That means that you will ba able to deploy Kafka, but not to manage Kafka topics and Users using Kubernetes resources.

**Comment by scholzj** [comment]
PS: I'm actually not aware of any change on our side between 0.5.0 and 0.8.0. So I think the certificate was correct in your 1.9.2 cluster.

**Comment by thbeh** [comment]
Thanks. I will have a look at the API server certificate.

**Comment by thbeh** [comment]
Solved. Closing.
