### ISSUE TITLE
Add finalizer on `KafkaRebalance` custom resource to avoid its deletion and losing feedback on Cruise Control ongoing operation

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#10245]
As per this discussion https://github.com/strimzi/proposals/pull/122#discussion_r1631460418 on the "autorebalancing on cluster scaling" proposal, the current Cruise Control integration suffers an issue related to the `KafkaRebalance` custom resource deletion while an operation in Cruise Control is going on.
The user can make a mistake or do the deletion on purpose but in that case, while the operation on Cruise Control continues (elaborating a proposal or running an actual rebalance), there is no more way to provide feedback to the user.
So the user doesn't know what's going on in Cruise Control unless they take a look at the corresponding log.
In order to avoid such a situation, the `KafkaRebalance` custom resource deletion should be possible only when the Cruise Control operation reaches a stable state reflected in the `KafkaRebalance` resource. By stable I mean, when a proposal is ready (aka `ProposalReady`) or when a rebalance is completed (aka `Ready`). Of course, the user is still able to stop the on going operation by using the usual `strimzi.io/rebalance: stop` annotation in all the other "temporary" states.
Avoiding the deletion could be simplified by the usage of a finalizer to be set and removed by the `KafkaRebalanceOperator` during the interaction and state changes on the `KafkaRebalance` custom resource.

**Comment by scholzj** [comment]
Should this be a general feature, I think it needs a triage and a separate proposal because it has major impact on users.

**Comment by ppatierno** [comment]
Yes I was already writing a proposal for it, opened the PR for tracking.

**Comment by ppatierno** [comment]
Going to close it because not relevant to the autorebalancing stuff on which we have to focus.
