### ISSUE TITLE
Getting user task status of getting proposal and current rebalancing should be "consistent"

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#10294]
When using the `KafkaRebalance` custom resource for rebalancing purposes, we are using two different approaches for getting the status of:

* getting a proposal (CC is computing an optimization proposal)
* actual rebalancing (CC is moving data across the cluster)

The main CC REST endpoint is `/rebalance` which is used for both, getting a proposal (by using the query parameter `dry_run=true`, with no user task id) and starting the rebalancing (by using the query parameter `dry_run=false`, with no user task id).
In both cases, an HTTP POST request is issued to that endpoint which is right.

When it comes to get the status, we are:

* still issuing an HTTP POST request on `/rebalance?dry_run=true` for the status of getting a proposal but this time passing a user task id.
* issuing an HTTP GET request on `/user_tasks` for the status of the rebalancing (of course, including the user task id).

The only reason I can think of why it was done differently is because of the following specific case.
When the model on CC is not ready yet, so you have the usual exception about "not enough data in the window" (i.e. when CC has been started from a few minutes and it doesn't have enough data to process proposal), what happens on CC is that your POST request for a proposal is created on CC, it gets a user task id assigned, the exception is thrown, and the task is immediately removed from the tasks list. It means, that after the POST request, there is no status to get because that user task doesn't exist anymore so we are safe by issuing a new POST request which actually means requesting for a new proposal (not getting the status of a previous request). NOTE: on the second POST we are issuing a user task id (from the first one) but it doesn't exist on the CC side anymore (so it sounds to be kind of useless).

So, I think we should investigate and understand what happens if we use the same rebalancing approach (POST on `/rebalance` and then GET on `/user_tasks`) even in the case of "not enough data in the window" exception. Even because a proposal could be not ready not just because of the "not enough data in window" exception but even for other reasons which don't throw and exception (in that case GETting the user tasks status would be the right way to go).

**Comment by scholzj** [comment]
Discussed on the community call on 10.7.2024: This should be discussed next time with the Cruise Control SMEs on the call.

**Comment by ppatierno** [comment]
Not able to join the today's call. This issue is about an investigation which would make sense to do and if possible we should use the same approach for both getting a proposal and running an actual rebalancing.

**Comment by scholzj** [comment]
Discussed on community call on 5.9.2024: We should try to refactor the code.
