### ISSUE TITLE
[Enhancement]: Support AWS_MSK_IAM auth mechanism for MirrorMaker

### ISSUE THREAD

**Issue by mytxyang** [strimzi/strimzi-kafka-operator#10301]
### Related problem

We want to use MirrorMaker to replication data between two AWS MSK cluster, but these MSK clusters only enable IAM auth method, current version cannot support AWS_MSK_IAM auth mechanism for MirrorMaker crds.

### Suggested solution

Add support for AWS_MSK_IAM auth mechanism on MirrorMaker controller.

**Comment by scholzj** [comment]
Duplicate of #5473

**Comment by scholzj** [comment]
Discussed on the community call on 10.7.2024: Duplicate of #5473. This should be closed.
