### ISSUE TITLE
[DOC]: The new quotas API does not allow to set check interval

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#10311]
### Related problem

The default check interval is 60 seconds, which may be too much for some use cases.
The only way to configure this is to use `.spec.kafka.config`, which is undocumented.

### Suggested solution

Add `checkIntervalSec` to the quotas API with related documentation.

**Comment by scholzj** [comment]
What does _too much_ mean? Too small? Too big?

**Comment by fvaleri** [comment]
> What does _too much_ mean? Too small? Too big?

Too big.

**Comment by scholzj** [comment]
I guess if you make it smaller you just overload the Admin API without gaining too much.

BTW: The proposal specifically expects that `Other options might be configured directly by the user in .spec.kafka.config section of the Kafka CR.`

**Comment by fvaleri** [comment]
> I guess if you make it smaller you just overload the Admin API without gaining too much.

I think it is useful to set a lower value, because a sudden and unexpected increase in the incoming bytes rate can fill up the disc in less than a minute, especially if you didn't leave room for this. 

The plugin project itself sets the check interval to 5 seconds as an example in the main readme. In general, I feel this is an important configuration to expose through the API.

> BTW: The proposal specifically expects that `Other options might be configured directly by the user in .spec.kafka.config section of the Kafka CR.`

Ok, I didn't remember that, but I don't think users read the proposal. Additionally, we have the following phrase in the changelog: the configuration of the plugin inside .spec.kafka.config is ignored and should be removed.

**Comment by scholzj** [comment]
> I think it is useful to set a lower value, because a sudden and unexpected increase in the incoming bytes rate can fill up the disc in less than a minute, especially if you didn't leave room for this.

I think you should plan with a sufficient buffer for this rather than play with the frequency of the check.

**Comment by fvaleri** [comment]
> I think you should plan with a sufficient buffer for this rather than play with the frequency of the check.

I agree, but we have things like test clusters, perf and load tests, so there could be valid use cases for this.

**Comment by scholzj** [comment]
Discussed on the community call on 10.7.2024: We should update the documentation to suggest that additional options can be configured in `.spec.kafka.config`.
