### ISSUE TITLE
[Enhancement]: Allow trusted certificates from external CA

### ISSUE THREAD

**Issue by mattaltberg** [strimzi/strimzi-kafka-operator#10325]
### Related problem

Right now, Kafka clusters will only trust incoming client certificates signed by the cluster's CA. I have a situation where the clients have certs signed by a secondary private CA, which I want to be able to trust. I cannot, however, use the private CA for regular cert generation, as I don't have access to its private key.

### Suggested solution

I want the cluster to trust incoming certificates that can be specified using a secret, specifying that CAs certificate.

### Alternatives

Using the cluster's CA to sign client certificates, but it's a no-go.

**Comment by scholzj** [comment]
Please check the docs. You can provide your own Clients CA and use it. If you do not plan to issue any user certificates, you can provide some dummy value instead of the private key if needed.

**Comment by mattaltberg** [comment]
I didn't find what I was looking for in the docs. All I found was that I would need the CA cert and its private key. I don't have access to the private key, but I was able to find that I could add the CA cert manually to `<cluser-name>-clients-ca-cert` so its added to the truststore. Where would I find the clients CA stuff in the docs?

**Comment by scholzj** [comment]
> I didn't find what I was looking for in the docs. All I found was that I would need the CA cert and its private key. I don't have access to the private key, but I was able to find that I could add the CA cert manually to `<cluser-name>-clients-ca-cert` so its added to the truststore. Where would I find the clients CA stuff in the docs?

Well, as I said, you can provide a dummy instead of the private key as long as you don't plan to issue any user certificates through the User Operator. The docs have a full chapter on custom CAs. But I'm afraid I do not have a link at hand right now.
