### ISSUE TITLE
Topic not available for console consumer when cluster scaled to one node

### ISSUE THREAD

**Issue by gunnarmorling** [strimzi/strimzi-kafka-operator#1034]
I've set up a cluster as per the example template, then scaled it down to one node. Also replication factors are set to 1:

```
Config:
      Default . Replication . Factor:                    1
      Offsets . Topic . Replication . Factor:            1
      Transaction . State . Log . Replication . Factor:  1
```

I then can't read the topic using the console consumer:

```
[2018-10-25 21:38:07,071] WARN [Consumer clientId=consumer-1, groupId=console-consumer-22653] Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```

The "node -1" looks suspicious.

Interestingly, I can read the topic programmatically using the Java API. Do I need to invoke the console consumer differently here? That's what I do:

```
oc exec -it my-cluster-kafka-0 -- /opt/kafka/bin/kafka-console-consumer.sh    --bootstrap-server my-cluster-kafka-bootstrap:9092    --from-beginning    --property print.key=true    --topic myorders
```

**Comment by gunnarmorling** [comment]
So as I learned from @jpechane, it works with `--bootstrap-server=localhost:9092`. I'm wondering why that is, @ppatierno, @scholzj?

**Comment by ppatierno** [comment]
@gunnarmorling is your cluster made by one Kafka broker? In that case it's a problem of the routing service in OpenShift. It happens that it's not able to redirect the traffic to itself.

**Comment by gunnarmorling** [comment]
> I suggest to use another pod for running the kafka-console-consumer

Which pod would that be, though? The Kafka nodes are the only ones coming with the console consumer, aren't they?

**Comment by ppatierno** [comment]
you could use the `kafka-base` image to build your own image to use as "testing" platform?

**Comment by gunnarmorling** [comment]
Hum, I guess in that case I could also just stay with three broker nodes...

**Comment by ppatierno** [comment]
Maybe you could try to use the zookeeper node? It has these tools as well. But what you are trying to do ... out of curiosity :-) Is it for a tutorial, demo, ... ?

**Comment by gunnarmorling** [comment]
Ah yes, indeed it works from the ZK node. Thanks!

> But what you are trying to do ... out of curiosity :-) Is it for a tutorial, demo, ... ?

Ha, glad you asked :)

We're going to do an updated version of the lab from RHT Summit at Voxxed Microservices next week (Wednesday). So in fact, if you have a chance, it'd be super-cool if you could run through the instructions here: https://github.com/debezium/microservices-lab/blob/master/voxxed-microservices-2018/lab.adoc. Any feedback would be much appreciated, esp. if you run into any issues or we're doing something stupid. Thanks!

**Comment by ppatierno** [comment]
Cool!!

PS: using the ZK node is just for a simple test, don't use the node to produce traffic from an application! :P

**Comment by gunnarmorling** [comment]
Sure, the console consumer is used just for peeking into a few topics.
