### ISSUE TITLE
ClusterRoleBindings for kafka-init to strimzi-kafka-broker role not containts ownerRef metadata

### ISSUE THREAD

**Issue by qveensi** [strimzi/strimzi-kafka-operator#10374]
### Bug Description

When i configure [Consuming messages from the closest replicas](https://strimzi.io/docs/operators/latest/configuring.html#consuming_messages_from_the_closest_replicas) the cluster creates a ClusterRoleBinding with no owner metadata. When using Gitops practices, argocd/fluxCD asks to remove this resource, as it considers it an orphan.

### Strimzi version

0.37.0

### Kubernetes version

 v1.29.6-gke.1254000

### Installation method

argoCD

### Infrastructure

Google Kubernetes Engine

### Configuration files and logs

![image](https://github.com/user-attachments/assets/2d345009-e9a6-4ad1-ab98-42daa499e979)

**Comment by scholzj** [comment]
That is not a bug. Cluster-wide resources cannot have owner references.

**Comment by qveensi** [comment]
> That is not a bug. Cluster-wide resources cannot have owner references. (Or to be more precise, it can have only cluster-scoped owner)

well, we will ignore it then. thank you, my jamb

**Comment by tkriviradev** [comment]
@qveensi Take a look my comment here https://github.com/strimzi/strimzi-kafka-operator/issues/7093#issuecomment-2640713035
