### ISSUE TITLE
Quotas plugin usage after upgrading from 0.41.0 to 0.42.0

### ISSUE THREAD

**Issue by alarex** [strimzi/strimzi-kafka-operator#10391]
After upgrading to 0.42.0 it seems that quota plugin not working or maybe i did something wrong?

Upgrade process:
1. Upgraded strimzi-operator via helm chart to 0.42.0
2. Manually updated crds from 0.42.0 release yaml, verified that quotas field is exists in crd
3. Deployed before upgrade Kafka cluster and newly created both ignored field so i don't see them in the spec of Kafka resource
```
spec:
  quotas:
    producerByteRate: 15728640  
```
4. Tried to reinstall strimzi operator completely

Still don't see quotas field in the Kafka resource spec.
Is it expected behavior or i missing something?

**Comment by im-konge** [comment]
Hi, could you please share whole Kafka CR? 
It seems (at least from the short snippet you pasted here) that you have it on wrong place, as the path is `spec.kafka.quotas` not `spec.quotas`.

**Comment by scholzj** [comment]
Can you provide the additional information or check the suggestions from Lukas please @alarex?

**Comment by scholzj** [comment]
Triaged on the Community call on 8.8.2024: We did not receive any response from the user. This should be closed.
