### ISSUE TITLE
[Bug]: Security Issue: Keystore and Trust store passwords are visible in ps output for Kafka Service in Strimzi Kafka Pod 

### ISSUE THREAD

**Issue by ekowsal** [strimzi/strimzi-kafka-operator#10399]
### Bug Description

Kafka Pods shows keystore and trust store passwords of kafka agent in ps output of kafka service.
 
Kafka server adds java agent which polls Kafka broker state and create broke state file.  It takes key/truststore password as argument which makes passwords are visible in ps output

KAFKA_OPTS="${KAFKA_OPTS} -javaagent:$(ls "$KAFKA_HOME"/libs/kafka-agent*.jar)=$KAFKA_READY:$ZK_CONNECTED:$KEY_STORE:$CERTS_STORE_PASSWORD:$TRUST_STORE:$CERTS_STORE_PASSWORD

Another security issue in kafka strimzi code is that CERTS_STORE_PASSWORD is exposed as environment variable. This env variable exposed and used for certificate creation of cruise control, mirror maker, kafka connect and many other places.

### Steps to reproduce

1. Go to Kafka pod 
2.  Do ps axww for kafka service
3.  You can see keystore/trustore password in the ouput of that

### Expected behavior

Password should not take as argument or exposed as environment variable. 

It should take password file as input and do the process internally. The keystore and truststore file and their password (ssl config parameter) is already written in /tmp/kafka_ssl_config.properties. It can pass the same ssl property file as input to agent or cert creation script and then it can read the key store and trust store details from that.

### Strimzi version

0.36.1

### Kubernetes version

Kubernetes 1.29.1

### Installation method

YAML

### Infrastructure

Bare Metal

### Additional context

It is very straight forward issue. Simple Kafka deployment will be enough to reproduce the issue.

**Comment by scholzj** [comment]
Duplicate of #9957. Please follow the explanation and details provided there.

**Comment by haijun2022** [comment]
Hi @scholzj, I am interested this issue, can I take a look at it?

**Comment by scholzj** [comment]
@haijun2022 As I suggested above, this seems like a duplicate. If you want to work on it, it should be the correct issue. You should probably also first clarify how would you address it.

**Comment by haijun2022** [comment]
Thanks @scholzj, yes I understand there are two issues created for same. I will research and share the solution for review.

**Comment by scholzj** [comment]
Triaged on the Community call on 8.8.2024: Duplicate of #9957.
