### ISSUE TITLE
Automatically refreshing the `KafkaRebalance` proposal should be properly plugged into the async-flow

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10416]
When the `KafkaRebalance` spec is updated, the `KafkaRebalanceAssemblyOperator` automatically adds a refresh annotation to it: https://github.com/strimzi/strimzi-kafka-operator/blob/66ef8d5772e66eb9c7ef40488c59ffdc1070e57a/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java#L1045-L1060

However, this code seems to be a bit lazily implemented and should be improved:
* As it is done asynchronously, it should be plugged into the asynchronous flow of the Vert.x futures
* It should be done only after the checks for the Kafka cluster, to make sure that:
    * The refresh annotation actually makes sense because the the Kafka cluster exists and is ready
    * Make sure the operator instance annotating it owns the rebalance resource

This should help to avoid race conditions.

**Comment by ppatierno** [comment]
Not able to join today's call but I think that this should be done.

**Comment by scholzj** [comment]
Triaged on the Community call on 8.8.2024: This should be fixed.
