### ISSUE TITLE
Fix update of status in `KafkaRebalanceAssemblyOperator` when refresh annotation is added

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10423]
In the `KafkaRebalanceAccessOperator`, there is a code for adding the refresh annotation when the spec changed:

```java
        if (kafkaRebalance.getStatus() != null
                && kafkaRebalance.getStatus().getObservedGeneration() != kafkaRebalance.getMetadata().getGeneration()) {

            KafkaRebalanceBuilder patchedKafkaRebalance = new KafkaRebalanceBuilder(kafkaRebalance);

            patchedKafkaRebalance
                    .editMetadata()
                         .addToAnnotations(Map.of(ANNO_STRIMZI_IO_REBALANCE, KafkaRebalanceAnnotation.refresh.toString()))
                    .endMetadata()
                    .editStatus()
                         .withObservedGeneration(kafkaRebalance.getMetadata().getGeneration())
                    .endStatus();

            kafkaRebalanceOperator.patchAsync(reconciliation, patchedKafkaRebalance.build()).onComplete(
                    r -> LOGGER.debugCr(reconciliation, "The KafkaRebalance resource is updated with refresh annotation"));
        }
```

It updates the `.status` section of the resource. But it call only `patch` afterwards and does not patch the status. That makes the status change completely ignored and useless. That is either a bug if the status update is really needed (but it does not seem so as nobody complained that it is not updated) and we should also call `patchStatus` to update the status as well. Or we should remove the status change in the first place to not mislead anyone that it is being updated.

Also the indentation of the in the builder is wrong as it uses 5 characters instead of 4.

**Comment by ppatierno** [comment]
@scholzj so aren't you going to open the PR with changes we agreed on #10415 ? Because now you labeld as needs-triage so it seems you asked for more discussion on the next community call.

**Comment by ppatierno** [comment]
Not able to join today's call, I think updating the status can be removed as you suggest but maybe we could close this one and taking it into account for #10416 ?

**Comment by scholzj** [comment]
Triaged on the Community call on 8.8.2024: This should be fixed.
