### ISSUE TITLE
[Enhancement]: ingress for kafka-connect

### ISSUE THREAD

**Issue by kamenskiyyyy** [strimzi/strimzi-kafka-operator#10427]
### Related problem

We use kafbat-ui to render kafka cluster in the browser. Kafka-cluster and kafbat-ui are located in different kubernetes clusters. Currently, there is no way for kafka-connect to add ingress using the operator, we do it manually...(

### Suggested solution

I suggest adding to the operator the ability to add external access for kafka-connect via Ingress/Load Balancer

**Comment by scholzj** [comment]
Triaged on the Community call on 8.8.2024: The effort to implement and maintain this seems to be quite high, especially assuming the different ways for exposing it other users might ask for. And exposing the API manually is very simple. Also, we currently lack any security on the Connect REST API which would be prerequisite.

This should be rejected for now. Feel free to raise it again when the security is supported for the Connect REST API, as that would address at least one of the major blockers.
