### ISSUE TITLE
Support building S2I builds based on artifact ids

### ISSUE THREAD

**Issue by gunnarmorling** [strimzi/strimzi-kafka-operator#1043]
Currently, in order to create custom images of Kafka Connect with additional connectors, a directory with JARs have to be provided. That can be cumbersome when dealing with connectors that require multiple (transitive) dependencies. E.g. updating all the dependencies after an update of the connector version requires some work. How about simplifying this by allowing to specify plug-ins for S2I in form of Maven coordinates?

E.g.

```
mkdir confluent-es-sink && cd confluent-es-sink && \
curl -sO http://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/5.0.0/kafka-connect-elasticsearch-5.0.0.jar && \
curl -sO http://central.maven.org/maven2/io/searchbox/jest/2.0.0/jest-2.0.0.jar && \
curl -sO http://central.maven.org/maven2/org/apache/httpcomponents/httpcore-nio/4.4.4/httpcore-nio-4.4.4.jar && \
curl -sO http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar && \
curl -sO http://central.maven.org/maven2/org/apache/httpcomponents/httpasyncclient/4.1.1/httpasyncclient-4.1.1.jar && \
curl -sO http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar && \
curl -sO http://central.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar && \
curl -sO http://central.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar && \
curl -sO http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar && \
curl -sO http://central.maven.org/maven2/io/searchbox/jest-common/2.0.0/jest-common-2.0.0.jar && \
curl -sO http://central.maven.org/maven2/com/google/code/gson/gson/2.4/gson-2.4.jar
```
would become `io.confluent:kafka-connect-elasticsearch:5.0.0` in some sort of configuration option passed to the S2I builder. That'd make the S2I build quite a bit easier to use.

WDYT, @ppatierno and @scholzj?

**Comment by scholzj** [comment]
I wonder what would be the right way to specify the plugins. The obvious choice would be some `pom.xml` file with dependencies which we just download I guess. Maybe we can use the Offliner tool for that (http://release-engineering.github.io/offliner/features/format-maven-pom.html).

However, I'm not sure this will suit everyone. There are many users who need to download form some Nexus proxies or private repositories and not from Maven Central. Or for example don't have internet access in their cluster. So I do not think it should replace the current functionality, but maybe serve as some alternate option.

**Comment by gunnarmorling** [comment]
> So I do not think it should replace the current functionality, but maybe serve as some alternate option.

Yes, I'm not suggesting to remove the existing approach of just providing a directory, but add another easier option based on Maven coordinates.

I don't even think a pom.xml would be needed, a list of comma-separated GAV coordinates such as `io.confluent:kafka-connect-elasticsearch:5.0.0` should suffice. It could be implemented using Offliner or quite easily using the Aether API (used by Maven itself internally, but can also be used to programmatically resolve artifacts). That is, if you can call Java code from within the S2I build, I've no idea how it is implemented :)

> Nexus proxies or private repositories

The proposed mechanism could and should support Maven's _settings.xml_ with additional repos.

**Comment by scholzj** [comment]
We are deprecating the Connect S2I. So we will not add this feature there. However, it is still planned for the KAfka Connect Build in #4179
