### ISSUE TITLE
[Bug]: The KafkaTopic.status.topicId is never updated

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#10467]
### Bug Description

The KafkaTopic.status.topicId keeps the old value when the topic is recreated in Kafka while the reconciliation is paused/disabled, or the operator is not running.

### Steps to reproduce

1. Create a new KT
2. Pause/unmanage the KT
3. Recreate the topic in Kafka
4. Unpause/manage the KT

### Expected behavior

We should set the topicId when the KT is managed and topicId is not set. We should remove the topicId when KT is paused or unmanaged.

### Strimzi version

main

### Kubernetes version

1.30

**Comment by scholzj** [comment]
Discussed on a community call on 22.8.2024: This should be fixed.
