### ISSUE TITLE
[BUG] The validation of the override node IDs in the `Capacity` class results in invalid warnings

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10465]
The way the capacity overrides are handled in the `Capacity` class in `processCapacityEntries` method can lead to invalid warnings such as:

```
2024-08-19 16:42:32 WARN  Capacity:401 - Reconciliation #0(test) kind(namespace/name): Ignoring broker capacity override for unknown node ID 0
2024-08-19 16:42:32 WARN  Capacity:401 - Reconciliation #0(test) kind(namespace/name): Ignoring broker capacity override for unknown node ID 0
```

These can happen in a single reconciliation even when the node `0` exists because they check each override multiple times with incomplete information. For example:
* Imagine cluster with 3 nodes with IDs 0, 1, and 2
* Imagine cluster with override for node 0
* The loop inside `processCapacityEntries` processes first the node `2` and checks the overrides
    * => node 0 was not processed yet and is not in the `capacityEntries` maps yet
    * Warning is raised
* Next, the node 1 is processed
    * => node 0 was not processed yet and is not in the `capacityEntries` maps yet
    * Warning is raised
* Finally the node 0 is handled:
    * => node is added to `capacityEntries` and override is used

This should be fixed for example by splitting the code into two loops.

**Comment by scholzj** [comment]
Discussed on a community call on 22.8.2024: This is a bug and should be fixed.

**Comment by Xander-run** [comment]
Hi @scholzj !

I'd like to work on this issue. Could you please assign it to me?

**Comment by scholzj** [comment]
@Xander-run Great. I assigned it to you. Please have a look at it and let us know if you have any questions or need some help.
