### ISSUE TITLE
[Bug]: Broken panels due to metric names change

### ISSUE THREAD

**Issue by dzasta997** [strimzi/strimzi-kafka-operator#10464]
### Bug Description

After updating operator to `0.42.0` two panels in `Strimzi Kafka Mirror Maker 2` - `Incoming Bytes per Second` and `Outgoing Bytes per Second` became empty.
Metrics `kafka_producer_outgoing_byte_total` and `kafka_consumer_incoming_byte_total` stopped producing values.
In the same time `kafka_producer_outgoing_byte` and `kafka_consumer_incoming_byte` appeared and based on their values I assume they replaced old metrics.

### Steps to reproduce

Update to operator `0.42.0`

### Expected behavior

If the metrics names were changed they should also be changed in [dashboards](https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/grafana-dashboards/strimzi-kafka-mirror-maker-2.json). But as I didn't find related changes I am not sure if it isn't a bug

### Strimzi version

0.42.0

### Kubernetes version

1.26

**Comment by scholzj** [comment]
Did you used the updated metrics configuration (the Config Map with the JMX exporter configuration YAML)?

**Comment by dzasta997** [comment]
After updating it everything works fine, thank you for support.

**Comment by scholzj** [comment]
Great, thanks for checking it.

(The changes were caused by some changes to the Prometheus JMX Exporter library. So we could have either just adopted them or be stuck forever with an old version :-(.)
