### ISSUE TITLE
Add the current Raft state to the KRaft Grafana dashboard

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10538]
In #10533 we added the metrics with the current Raft state for the different nodes to the exported metrics. This might be something to also add to the KRaft Grafana dashboard. The metric shows what role does the broker currently play in KRaft - e.g. leader, follower, observer etc. It might ve shown for example as a table

The example of this metric can be seen in the attached screenshot.
![Screenshot 2024-09-03 at 23 14 26](https://github.com/user-attachments/assets/10efe7a8-5f40-46ea-af8b-06a42ecf64d5)

**Comment by scholzj** [comment]
Discussed on community call on 5.9.2024: Seems useful.

**Comment by MichaelMorrisEst** [comment]
@scholzj I can work on this
