### ISSUE TITLE
[Docs]: Downloading the Strimzi Drain Cleaner deployment files

### ISSUE THREAD

**Issue by Blarc** [strimzi/strimzi-kafka-operator#10534]
### Suggestion / Problem

The documentation says "The Strimzi Drain Cleaner deployment files are available from the [GitHub releases page](https://github.com/strimzi/strimzi-kafka-operator/releases)", but Strimzi Drain Cleaner is not available as a release asset.

The yamls can be found either in strimzi-kafka-operator repository - [here](https://github.com/strimzi/strimzi-kafka-operator/tree/main/packaging/install/drain-cleaner) or in the [Strimzi Drain Cleaner repository](https://github.com/strimzi/drain-cleaner/tree/main).

This confused me a bit, because I wasn't sure which repository should I look at, even though they have the same files.

### Documentation Link

https://strimzi.io/docs/operators/latest/deploying#drain-cleaner-prereqs-str

**Comment by fvaleri** [comment]
@Blarc you are right, that's confusing. If you want to contribute a fix, [this readme](https://github.com/strimzi/strimzi-kafka-operator/tree/main/documentation) should help :)

**Comment by scholzj** [comment]
The Drain Cleaner installation files are part of the Operator installation package. So you can get them from the linked release page in the `strimzi-0.43.0.zip` or `strimzi-0.43.0.tar.gz` files. Those are the files that are referred to in the documentation. But of course, feel free to open a PR to clarify the docs if you think something is not clear there.

**Comment by scholzj** [comment]
Discussed on community call on 5.9.2024: It is not completely clear what the confusing part is and what would be the improvement. @Blarc please clarify it or open a PR that improves it.

**Comment by Blarc** [comment]
Hey @scholzj,

the documentation says:
"To deploy and use the Strimzi Drain Cleaner, you need to download the deployment files.
The Strimzi Drain Cleaner deployment files are available from the [GitHub releases page](https://github.com/strimzi/strimzi-kafka-operator/releases)."

This link takes you to the latest release, where deployment files are not mentioned at all. That is the part that confused me. 

The documentation could mention, that you need to download the [strimzi-0.43.0.zip](https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.43.0/strimzi-0.43.0.zip), uncompress the file and then the deployment files for Strimzi Drain Cleaner can be found at `install/drain-cleaner/kubernetes`.

Of course this is a small thing that is not so important, I just opened an issue because I figured out that if it confused me, it might confuse someone else as well.

I can open a PR when I'll have some the time.

**Comment by scholzj** [comment]
Ok, thanks.

> Of course this is a small thing that is not so important, I just opened an issue because I figured out that if it confused me, it might confuse someone else as well.

That is of course fine. It just needs to be clear about what the confusing part is as it might not be clear to everyone. Thanks for clarifying it.

**Comment by Blarc** [comment]
@im-konge Hey, sorry, @PaulRMellor can take a look.

**Comment by PaulRMellor** [comment]
@Blarc -- We have a Downloading deployment files section. I've expanded that to describe what in it and reference it from the procedure to deploy the Drain Cleaner. It should be clear now.

**Comment by Blarc** [comment]
Great @PaulRMellor ! Thanks a lot.
