### ISSUE TITLE
Move `TestUtils` methods used only in system tests to `systemtest` module

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10557]
The `TestUtils` class seems to have several methods used exclusively by the System Tests:
* `indent(...)`
* `changeRoleBindingSubject(...)`
* `parseImageMap(...)`

We should try to find them a new home directly in the `systemtest` module instead of having them in the `test` module as they do not seem to be generic methods but very specific methods needed by system tests only.

**Comment by see-quick** [comment]
Sure, I can take a look at this if nobody is interested in doing so. Thanks for raising this.

**Comment by im-konge** [comment]
Triaged on 19.9.2024: This makes sense. @see-quick will have a look at it.

**Comment by im-konge** [comment]
Done in #10610
