### ISSUE TITLE
[Enhancement]: Support to Jolokia

### ISSUE THREAD

**Issue by rlanhellas** [strimzi/strimzi-kafka-operator#10577]
### Related problem

Today, it isn't possible to collect JMX metrics using HTTP, just raw JMX protocol, which is a problem for most of the collectors like metricbeat which supports Jolokia but not JMX.  

### Suggested solution

Change the current Docker image adding Jolokia Agent so it might be used when needed. 

### Additional context

I can work on this but first I'd like to know if you guys are inclined to accept this feature or if it is in your roadmap. IMO it's a basic feature that we should support.

**Comment by scholzj** [comment]
I think Metricbeat can scrape Prometheus metrics. So it has no need for JMX or Jolokia.

**Comment by im-konge** [comment]
Triaged on 19.9.2024: There are users that use Metricbeat for scraping the Prometheus metrics. So that's not right justification to support Jolokia here. Adding support for more things like this (Jolokia) can add a big efforts to maintainability and testability. In case of need, we can discuss it further.

**Comment by rlanhellas** [comment]
> I think Metricbeat can scrape Prometheus metrics. So it has no need for JMX or Jolokia.

Got it , but imagine the following situation. I have a complete Metricbeat configuration with more than 500 lines using Jolokia to scrap metrics, so in order to port it to prometheus I need to rewrite every rule on my metricbeat. 

So Jolokia is a good feature for Strimzi IMO, and I'm able to open this PR if you allow me.

**Comment by scholzj** [comment]
I don't really understand what rules do you need to rewrite. But it is not about opening a one-off PR. Things need to be maintained and tested again and again possibly for years. So that is a lot of effort over the time.

**Comment by rlanhellas** [comment]
Really, I don't see why we can't have a metrics exporter config to Prometheus and another to Jolokia, actually we might have any kind of output here since the input is the same (JMX). So we just have to maintain the input, the output depends on the library we use as exporter. My point is ... We could have a way to import a plugin to export to different formats not just prometheus

**Comment by scholzj** [comment]
Imagine that every Strimzi user would come and say _"Although I could use the metrics you already have, I'm used to this other thing, so you should support it."_. How long do you think the project will survive if we add every single thing someone asks for? How long we would be able to keep it in a working condition, do new releases etc. Every new feature needs to have some reasonable justification to cover the effort that it will cost short and long term.

**Comment by rlanhellas** [comment]
> Imagine that every Strimzi user would come and say _"Although I could use the metrics you already have, I'm used to this other thing, so you should support it."_. How long do you think the project will survive if we add every single thing someone asks for? How long we would be able to keep it in a working condition, do new releases etc. Every new feature needs to have some reasonable justification to cover the effort that it will cost short and long term. Because only that way we can make sure it will keep working. It is in nobody's interest to add features today and remove them tomorrow because we do not have the resources to keep them working.

That's ok, anyway thanks for the feedback.

**Comment by ppatierno** [comment]
Triaged on 03.10.2024: @rlanhellas we are going to close this one because it would be difficult for us to provide the right support for every kind of tool that the community could ask for.
