### ISSUE TITLE
topic-operator fails to use truststore/keystore as specified with env vars

### ISSUE THREAD

**Issue by BradyWiseman** [strimzi/strimzi-kafka-operator#1058]
Running strimzi/topic-operator:0.8.2 standalone on Oracle Cloud Infrastructure/Oracle Kubernetes Engine.

We have added an initcontainer to the manifests provided with examples/install/topic-operator.  We successfully construct a truststore, a keystore, & passwords.  When these are passed in to STO as environment vars, topic-operator code ignores them and attempts to build keystore & truststore in /tmp/topic-operator, as indicated in the attached log file.

org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/topic-operator/replication.keystore.p12 of type JKS

We log in to the STO container and verify the following:
\# env |grep STRIMZI
STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS=20000
STRIMZI_CONFIGMAP_LABELS=strimzi.io/kind=topic
STRIMZI_TLS_ENABLED=true
STRIMZI_NAMESPACE=kweet-psr
STRIMZI_LOG_LEVEL=DEBUG
**STRIMZI_TRUSTSTORE_PASSWORD=GxeGs2Denj**
STRIMZI_VERSION=0.8.2
**STRIMZI_KEYSTORE_PASSWORD=GxeGs2Denj**
**STRIMZI_TRUSTSTORE_LOCATION=/jks/kafka.client.truststore.jks**
**STRIMZI_KEYSTORE_LOCATION=/jks/kafka.client.keystore.jks**
STRIMZI_ZOOKEEPER_CONNECT=10.0.6.38:2181
STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS=6
STRIMZI_KAFKA_BOOTSTRAP_SERVERS=10.0.6.39:9092
STRIMZI_FULL_RECONCILIATION_INTERVAL_MS=900000 

NOTE: The logfile indicates topic-operator is using different values for STRIMZI_TRUSTSTORE_LOCATION AND STRIMZI_KEYSTORE_LOCATION.

Check the jks files we constructed.
\# ls -l /jks
total 8
-rw-r--r--. 1 root root 2328 Nov  2 19:38 kafka.client.keystore.jks
-rw-r--r--. 1 root root 1073 Nov  2 19:38 kafka.client.truststore.jks
(Present and accounted for.)

Check the jks files the topic-operator tried to build.
\
[STO-tls-failure-2018-11-02--19-39-13.log](https://github.com/strimzi/strimzi-kafka-operator/files/2543952/STO-tls-failure-2018-11-02--19-39-13.log)
\# ls -l /tmp/topic-operator/
total 0
( None there.  )

Please advise.

**Comment by scholzj** [comment]
I think this is a bug in our documentation / bug in the Docker image for Topic Operator. The docs say you can rewrite it this way. But in reality the Docker image expects to have X509 keys mounted in specific locations and converts them into JKS store on its own. I will have a look at it.

Until I fix it, if you want to configure it with 0.8.2, here are the paths of the keys to get that working: https://github.com/strimzi/strimzi-kafka-operator/blob/0.8.2/topic-operator/scripts/tls_prepare_certificates.sh

**Comment by scholzj** [comment]
FYI: I opened a PR for this - #1059

**Comment by BradyWiseman** [comment]
Thanks for the weekend response!

Are you saying that if I drop my pkcs12 file at
/tmp/topic-operator/replication.truststore.p12, the topic operator will use
it & create keystore/truststore?

Best regards

Brady Wiseman in Bozeman Montana

**Comment by scholzj** [comment]
Actually, the P12 files is what the script creates. It expects x509 and PEM files on the input.

**Comment by BradyWiseman** [comment]
OK, thanks.

**Comment by ppatierno** [comment]
I have just reviewed the #1059 and it looks good to me. As soon as the Travis CI will be green we can merge it to the master.
