### ISSUE TITLE
Simplify manual certificate installation/renewal

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1064]
Currently manual installation of CA certificate & key is a bit complicated because:

1. You need to create two secrets
2. Both those secrets need to have the correct annotations.

Likewise CA cert renewal is also more complicated than it could be.

One way to alleviate this (when `Kafka.spec.clusterCa.generateCertificateAuthority=false`) would be for the user to supply a single secret with both cert and key, without needing any annotations on it. The CO would copy the cert into the correctly named and annotated secret. Likewise the key, I suppose, though I wonder if using the key from the user-supplied `Secret` would actually be simpler from an RBAC point of view.

Thoughts @strimzi/developers ?

**Comment by scholzj** [comment]
This sounds quite complicated to me. It will be hard to maintain it.

**Comment by scholzj** [comment]
Triaged on 22.02.2022: The https://github.com/strimzi/proposals/pull/46 will change this and it is taking this idea into account. This can be closed.
