### ISSUE TITLE
Rack awareness tests should not rely on the internal files

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10663]
The RackAwarenessST tests currently rely on the internal implementation details (lines 121-124 at the time of opening this issue):

```java
        String rackIdOut = cmdKubeClient(testStorage.getNamespaceName()).execInPod(podName, "/bin/bash", "-c", "cat /opt/kafka/init/rack.id").out().trim();
        String brokerRackOut = cmdKubeClient(testStorage.getNamespaceName()).execInPod(podName, "/bin/bash", "-c", "cat /tmp/strimzi.properties | grep broker.rack").out().trim();
        assertThat(rackIdOut.trim().contains(hostname), is(true));
        assertThat(brokerRackOut.contains("broker.rack=" + hostname), is(true));
```

This relies on the internal implementation of how the rack information is passed to the Kafka container, how it is loaded and where the configs are stored. This should instead do a black box testing and use the KAfka Admin API to query the nodes rack to make sure the Kafka nodes are properly configured.

**Comment by im-konge** [comment]
Thanks, this makes sense. I will have a look.

**Comment by ppatierno** [comment]
Triaged 03.10.2024: thanks to @im-konge for volunteering to look into this.
