### ISSUE TITLE
[Enhancement]: Remove mirror maker 2 extensions from images

### ISSUE THREAD

**Issue by robobario** [strimzi/strimzi-kafka-operator#10662]
### Related problem

The strimzi mirror maker 2 extensions were Deprecated in [0.28.0](https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.28.0) in 2022.

### Suggested solution

- mirror maker 2 extensions extensions are removed from the images
- release note added about the removal

**Comment by robobario** [comment]
What milestone/release would be suitable?

**Comment by scholzj** [comment]
https://github.com/strimzi/proposals/blob/main/034-deprecate-and-remove-mirror-maker-2-extensions.md says it should be removed in 0.32.0 🙄. So if you wanna remove it, I guess you can probably do it. You might also consider to wait for 0.46 release as that will have a lot of breaking changes (Zoo removal, MM1 removal etc.). Given this is a zero-effort dependency, it should be simple to wait for 2 more releases.

**Comment by robobario** [comment]
lumping it in with the other breaks in 0.46 sounds good

**Comment by ppatierno** [comment]
Triaged 03.10.2024: agreed on having the MM2 extensions removed in 0.46.0 release.
