### ISSUE TITLE
[Enhancement]: Support HostPath as a Volume for KafkaConnect

### ISSUE THREAD

**Issue by lujiajing1126** [strimzi/strimzi-kafka-operator#10688]
### Related problem

In the current `AdditionalVolume` implementation, only `Secret`, `ConfigMap`, `EmptyDir` and PVC are supported. In some cases, for example, `spiffe`  (https://spiffe.io/) needs UDS for communication between DaemonSet pod and application pod, e.g. KafkaConnect pod.

### Suggested solution

Add `HostPath` support to the AdditionalVolume and related utils.

**Comment by scholzj** [comment]
Can you elaborate more on the use case? How it will be used, what will it enable etc.? Also, do you understand that the hostpath will be the same in every single pod?

**Comment by scholzj** [comment]
Also, can't you already do it through PV and PVC? Create a hostPath PV, PVC to map to the PV and moount the PVC into the Pods? Or does this not work for some reason?

**Comment by scholzj** [comment]
The diagram shows Envoy running in the Pod and consuming it. So how will you get it there? We do not support that. Also, what about using the host path through the PV?

**Comment by im-konge** [comment]
Triaged on 31.10.2024: There is a suggestion from Jakub added 3 weeks back and we didn't get a better use-case until now. So I'm closing this now and in case that you will find issues with the suggestion, please re-open the issue. Thanks
