### ISSUE TITLE
[Bug]: CA cert annotations aren't updated during CaReconciler rolling update

### ISSUE THREAD

**Issue by katheris** [strimzi/strimzi-kafka-operator#10710]
### Bug Description

When the CA private key or public certificate is updated the CaReconciler class does a rolling update of the Kafka nodes to use the new key and/or certificate. However this class does not update the `strimzi.io/cluster-ca-cert-generation` and `strimzi.io/cluster-ca-generation` annotations, this is instead done by the Kafka Reconciler.

This means if something goes wrong while the CaReconciler is doing its rolling update and the reconciliation fails, the next reconciliation will roll all of the nodes again, even the ones that were already rolled.

### Steps to reproduce

1. Create a Kafka custom resource with 3 replicas
2. Annotate the cluster-ca-cert Secret with `strimzi.io/force-renew=true` to trigger a certificate renewal
3. Once the operator has rolled one of the pods, see that the annotation on that pod is not updated
4. Delete the cluster operator
5. When it starts back up it will roll all pods again, even the one it already rolled

### Expected behavior

Instead the CaReconciler should patch the StrimziPodSet so that as the rolling update is performed the pods come up with the new certificate generation annotation

### Strimzi version

main

### Kubernetes version

N/A

**Comment by ppatierno** [comment]
Triaged on 17/10/2024: PR is under review and almost ready to be merged.
