### ISSUE TITLE
[DOC]: Invalid cluster.id error when initializing a new KRaft cluster with existing volumes

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#10722]
### Bug Description

When Kraft disks are already formatted, we have to reuse the previous cluster.id in addition to the --ignore-formatted flag. This is required by the Kafka storage tool in order to check that cluster.id is the same across all broker disks.

When Kafka pods are restarted, the operator reuses the existing cluster.id from Kafka CR status and skips disk formatting. Instead, when initializing a new Kafka cluster, there is no status, so it always generates a new cluster.id and runs disk formatting. 

This is a problem when rebinding existing volumes from a previous Kafka cluster instance because they already have a cluster.id stored in meta.properties. In this case, Kafka pods start crash looping with the following error:

```sh
Exception in thread "main" java.lang.RuntimeException: Invalid cluster.id in: /var/lib/kafka/data/kafka-log0/meta.properties. Expected kQHv733NQIew9aw9uCXnDA, but read 2DLef4_8TqOVdBjzCORB1Q
```

### Steps to reproduce

See https://github.com/strimzi/strimzi-kafka-operator/pull/10637#discussion_r1780956446.

### Expected behavior

Assuming the binding is correct, the Kafka pods should be able to work with volumes from a previous Kafka cluster instance.

### Strimzi version

main

### Kubernetes version

1.30

**Comment by scholzj** [comment]
The expectation is that users set the cluster ID in the Kafka CR status as part of the recovery. There is no expectation to recover it from the disks. This might need to be documented, but it should not be fixed by reading any cluster IDs from the volumes.

**Comment by fvaleri** [comment]
> This might need to be documented, but it should not be fixed by reading any cluster IDs from the volumes.

Definitely, because the current documented procedure is broken: https://strimzi.io/docs/operators/latest/deploying#proc-cluster-recovery-volume-str.

**Comment by scholzj** [comment]
> Definitely, because the current documented procedure is broken: https://strimzi.io/docs/operators/latest/deploying#proc-cluster-recovery-volume-str.

It is not broken, just old. Let's keep the issue to track the docs improvement.

**Comment by ppatierno** [comment]
Triaged on 17/10/2024: we agreed on leaving this open to be fixed in the documentation. @fvaleri is going to run some tests and open a doc related PR.

**Comment by fvaleri** [comment]
@scholzj I'm trying the KRaft volume recovery procedure with the status update as you suggested. It ultimately works, but it's not so nice.

Let's say we have Kafka volumes binding and it's all correct. Then you have to deploy the cluster and let it use the existing bindings. You first create resources, and then patch with `--subresource status` to set the `.status.clusterId` with what's inside the volumes.

What happens next is that you still get the invalid cluster.id error.

```sh
$ kubectl logs my-cluster-broker-7 | grep "Invalid cluster.id"
Exception in thread "main" java.lang.RuntimeException: Invalid cluster.id in: /var/lib/kafka/data/kafka-log7/meta.properties. Expected 32RSAKsQSf6KYFCAiLTfSw, but read PytBkS1vSieIefyfMJwc-g
$ kubectl get k my-cluster -o yaml | yq .status.clusterId
PytBkS1vSieIefyfMJwc-g
```

In order to unblock this, I have to delete all pods and, after some time, the cluster is able to start correctly. Am i missing something? Is there a better way?

**Comment by fvaleri** [comment]
Adding [cluster-op.log](https://github.com/user-attachments/files/17411553/cluster-op.log) after cluster recreation and `.status.clusterId` patch.

**Comment by scholzj** [comment]
> Let's say we have Kafka volumes binding and it's all correct. Then you have to deploy the cluster and let it use the existing bindings. You first create resources, and then patch with --subresource status to set the .status.clusterId with what's inside the volumes.

I think the right approach is:
* Create the Kafka CR paused
* Update the status with `kubectl edit --subresource status`
* Unpause the resource

The main challenge is IMHO how to get the cluster Id if you don't have it (because you don't have the old resources, logs, etc.).

**Comment by fvaleri** [comment]
> Create the Kafka CR paused

Ok, let me try that.

> The main challenge is IMHO how to get the cluster Id if you don't have it

We can spin up a temporary pod and read it from `meta.properties` of one of the volumes as it must be the same for all.

**Comment by fvaleri** [comment]
Ok, that worked nicely, thank @scholzj. Going to write something down for the doc update, and then we can refine in the PR.

**Comment by TigranKhudav** [comment]
Hi @scholzj,

Why can’t we hardcode `cluster.id`? We are seeing many issues related to this, so it would be helpful to add it as a hardcoded attribute.

If you are okay with that, I can make the change and open a pull request.

**Comment by scholzj** [comment]
@TigranKhudav You can set the cluster ID in the status section of the Kafka CR as described above.
