### ISSUE TITLE
[Bug]: Empty required field in CRDs

### ISSUE THREAD

**Issue by wdonne** [strimzi/strimzi-kafka-operator#10732]
### Bug Description

The CRDs in version 0.43.0 of the Helm charts have a `required` field under the `volumes` field that has an empty array as its value. While this is allowed, when applied to the cluster those fields are not present in the live manifest. This keeps the CRD resources out of sync for ArgoCD.

### Steps to reproduce

1. Deploy the Helm chart 0.43.0 on a cluster through ArgoCD (version 2.12.4).
2. Sync the ArgoCD application.

### Expected behavior

The CRDs are synchronised.

### Strimzi version

0.43.0

### Kubernetes version

1.29

### Installation method

Helm chart

### Infrastructure

Amazon EKS

**Comment by scholzj** [comment]
Already solved in #10492, which also contains a workaround for Argo.
