### ISSUE TITLE
Documentation for the API module

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1074]
We need documentation on the `api` module, including typical use cases and some basic examples.

**Comment by scholzj** [comment]
Triaged on 26.5.2022: This is still something we would be interested in.

**Comment by ashutosh0022** [comment]
I am completely new to open-source and came to know, that documentation is the path to begin contributing. Can anyone help me?
I will do my best.

**Comment by scholzj** [comment]
@ashutosh0022 There is a guide for contributong to the documentation: https://strimzi.io/contributing/guide/ ... so that might be the best start and if you have any questions afterwards, let us know. @PaulRMellor is our documentation guru, so I'm sure he will be able to help with most of the things as well.

**Comment by devilkiller-ag** [comment]
Can I handle this issue?

**Comment by scholzj** [comment]
@PaulRMellor? ^^^

**Comment by devilkiller-ag** [comment]
Thank you @scholzj. I will start working on it after the comfirmation by @PaulRMellor

**Comment by 9avneet** [comment]
@PaulRMellor ,I want to solve  this issue,but I am new to this ,so if possible can you guide me a little bit,it will be very helpful.thanks

**Comment by PaulRMellor** [comment]
Thanks @9avneet -- To get started on this issue, I would suggest taking the following steps:

1. Familiarize yourself with the [Strimzi Documentation Contributor Guide](https://strimzi.io/contributing/guide/), which outlines the process for contributing to the documentation.
3. Set up Git on your local machine, if you haven't already. You can find instructions on how to do this in the Strimzi Documentation Contributor Guide.
5. Get an understanding of the [document structure](https://github.com/strimzi/strimzi-kafka-operator/tree/main/documentation) using asciidoc, which is the markup language we use for our documentation. You can find some helpful resources on Asciidoc in the [Asciidoc Writer's Guide](https://asciidoctor.org/docs/asciidoc-writers-guide/).
7. Look at the [examples](https://github.com/scholzj/strimzi-api-examples) @scholzj provided.
9. When you feel comfortable with the docs and how you might start documenting the examples, maybe start with a simple example to get started.

**Comment by 9avneet** [comment]
@PaulRMellor I am facing difficulties in starting with this,I tried to go through documentation,but as I told you in an new to open source so I am not become able to proceed with the same,if you can provide me an mentor or some initial guide will be enough ,so that I can continue with the same , thanks hope you understands.

**Comment by PaulRMellor** [comment]
It seems like this task might be more challenging than expected @9avneet . As you mentioned, you are new to open source so it might be useful for you to start with a simpler documentation task that could help you gain more experience in the project. If you read through the documentation, perhaps you could find some small update.  A less complex task would allow you to gain familiarity with Strimzi's documentation processes. Additionally, you could attend the a community meeting, where you can ask questions and receive guidance.

**Comment by SaxenaAnushka102** [comment]
Greetings @scholzj, @PaulRMellor! I'd love to work on this issue. I've previously done setup of Strimzi on a Linux VM & have a basic understanding of how the project enables Apache Kafka on Kubernetes for stream processing. Could you please share some resources that I can refer to start creating the documentation?

**Comment by scholzj** [comment]
@SaxenaAnushka102 I think looking at the steps described here might be the first step:

> 1. Familiarize yourself with the [Strimzi Documentation Contributor Guide](https://strimzi.io/contributing/guide/), which outlines the process for contributing to the documentation.
> 2. Set up Git on your local machine, if you haven't already. You can find instructions on how to do this in the Strimzi Documentation Contributor Guide.
> 3. Get an understanding of the [document structure](https://github.com/strimzi/strimzi-kafka-operator/tree/main/documentation) using asciidoc, which is the markup language we use for our documentation. You can find some helpful resources on Asciidoc in the [Asciidoc Writer's Guide](https://asciidoctor.org/docs/asciidoc-writers-guide/).
> 4. Look at the [examples](https://github.com/scholzj/strimzi-api-examples) @scholzj provided.
> 5. When you feel comfortable with the docs and how you might start documenting the examples, maybe start with a simple example to get started.

**Comment by SaxenaAnushka102** [comment]
Got it, I'll go through these resources & try some examples first! Thanks @scholzj

**Comment by scholzj** [comment]
Closing after discussion with @ppatierno and @PaulRMellor. It is not really clear what the ask is and this probably cannot be contributed by someone from the outside. And at the same time, we clearly do not consider it important enough to work on it ourself.
