### ISSUE TITLE
Support instantiation of Kafka Connect connectors via operator

### ISSUE THREAD

**Issue by gunnarmorling** [strimzi/strimzi-kafka-operator#1076]
Currently KC connectors such as Debezium must be registered via KC's REST API. An Operator could smoothen this experience:

* Could create/update/delete connectors following the resource definition
* Could automatically fetch the required connector dependencies at least for a set of known connectors
* Could inject secrets for connector credentials
* Could verify sanity of options (albeit that'd be connector specific): e.g. for Debezium's MySQL connector, there must not be two instances with the same server name and client id. An operator could verify that and fail the registration if needed. That'd need some means of exensibility, so that connector builders such as DBZ could register the required info.

**Comment by yarmiganosca** [comment]
$WORK is currently in the process of adopting Kafka Connect for CDC from all our service datastores, and we'd love an Operator to handle provisioning of Connectors. If anybody could point me in the right direction on testing (not just how to run them, which is in the Hacking doc, but what are good tests to use as a template for both unit and end-to-end tests for Operators), we might be able to contribute at least a bare-bones implementation that just does the create/update/delete piece.
