### ISSUE TITLE
[Enhancement]:  Repeat automatic adding not in autoRebalance in the same way, as in automatic remove

### ISSUE THREAD

**Issue by hennadii2012** [strimzi/strimzi-kafka-operator#10820]
### Related problem

If object auto-rebalancing-add-brokers failed, it doesn't do another try to add partitions on newly created nodes, so you should do it manually

### Suggested solution

Add retries to   auto-rebalancing-add-brokers in the same way, as it implemented in auto-rebalancing-remove-brokers, so process will work as it should

**Comment by scholzj** [comment]
I do not think this is really doable without a significant complexity because the added nodes is not a state that persists.

**Comment by hennadii2012** [comment]
Probably something like retry interval and mount of retries can be added in such case. This don't need a lot of changes and in general 1 or extra retries triggering correct rebalance. What do you think?

**Comment by scholzj** [comment]
> This don't need a lot of changes and in general 1 or extra retries triggering correct rebalance.

This is not true because you need to know that you have to retry in the first place and keeping such a state is complicated as I said before.

**Comment by ppatierno** [comment]
Reiterate what Jakub said, it's not as simple as it looks like for the state to keep. Even during the proposal discussion we made the decision of leaving the user the burden of retrying.

**Comment by im-konge** [comment]
Triaged on 14.11.2024: As it was mentioned in the proposal, the retrying should be done by the user and it's not that easy to implement it without adding complexity. So I'm closing this as not planned.
