### ISSUE TITLE
[Bug]: The pod strimzi cluster operator CPU usage increased a lot

### ISSUE THREAD

**Issue by TheFireCookie** [strimzi/strimzi-kafka-operator#10859]
### Bug Description

Previously we were using Strimzi 0.40.0 with Kafka 3.7.0 with those feature gates:
+UseKRaft,+KafkaNodePools,+UnidirectionalTopicOperator

We upgraded to 0.44.0 with Kafka 3.8.0 and since then the CPU consumption of the operator is x100 compared to previously.
Our before average CPU usage : 0.0051 of 1 VM CPU
Our new average CPU usage : 0.515 of 1 VM CPU

### Steps to reproduce

In our case, install a clean operator with very few configs

here are the previous and new configurations attached
[old-envs.txt](https://github.com/user-attachments/files/17843956/old-envs.txt)
[new-envs.txt](https://github.com/user-attachments/files/17843955/new-envs.txt)

### Expected behavior

No CPU increase.

### Strimzi version

0.44.0

### Kubernetes version

Kubernetes RKE 1.30.1

### Installation method

Helm charts

### Infrastructure

RKE on vSphere Cluster

### Configuration files and logs
[old-strimzi-cluster-operator-logs.log](https://github.com/user-attachments/files/17844024/old-strimzi-cluster-operator-logs.log)
[new-strimzi-cluster-operator-logs.log](https://github.com/user-attachments/files/17844026/new-strimzi-cluster-operator-logs.log)

### Additional context

As you can see in the new version the operator seems to be triggering reconciliation in loop that was not occurring before. But why?

2024-11-21 10:18:29 INFO  AbstractOperator:520 - Reconciliation #50248(watch) Kafka(ipd-via/evs-ipd-via-kafka): Kafka evs-ipd-via-kafka in namespace ipd-via was MODIFIED
2024-11-21 10:18:29 INFO  AbstractOperator:266 - Reconciliation #50247(watch) Kafka(ipd-via/evs-ipd-via-kafka): Kafka evs-ipd-via-kafka will be checked for creation or modification
2024-11-21 10:18:29 INFO  AbstractOperator:546 - Reconciliation #50246(watch) Kafka(ipd-via/evs-ipd-via-kafka): reconciled

**Comment by scholzj** [comment]
Did you updated the CRDs when upgrading Strimzi? You have constantly happening reconciliations likely because you did not update CRDs and are using old CRD schema. See for example #10576.

**Comment by TheFireCookie** [comment]
Indeed, that's the issue! We'll do that, thanks for the fast answer.
