### ISSUE TITLE
[Enhancement]: Allow using Kafka Native

### ISSUE THREAD

**Issue by makinjc** [strimzi/strimzi-kafka-operator#10858]
### Related problem

Kafka Native is a lighter image that is tiny and starts very fast that is suitable for dev and CI environments. It'd be great to have it.

### Suggested solution

Operator should allow using [apache/kafka-native](https://hub.docker.com/r/apache/kafka-native) 

### Alternatives

I just tried changing the image with but it failed with the following error:

```
 exec: "/opt/kafka/kafka_run.sh": stat /opt/kafka/kafka_run.sh: no such file or directory: unknown
```

**Comment by scholzj** [comment]
Strimzi does not use the Kafka container images and does not plan to do so. Strimzi requires the images to contain various tools for configuring Kafka, additional JARs and other binaries and needs the image to support the platforms that we support. So using someone else's image is not possible without heavily customizing it to make it Strimzi compatible. And in case of the native image you would likely need to recompile the whole native binary etc.

**Comment by ppatierno** [comment]
Triaged on 12/12/2024: as Jakub explained is not that simple just replacing/supporting the native images straight away. We should stick with the current ones. So we agreed to reject this "proposal".
