### ISSUE TITLE
[Enhancement]: Add external listener type that will put ips to kafka config

### ISSUE THREAD

**Issue by hennadii2012** [strimzi/strimzi-kafka-operator#10887]
### Related problem

We have possibility to access to pods directly from our network, so we don't need node port or other type of services for external access to the cluster. Is it possible to add listener, that will work as internal, but return IPs instead of pod names

### Suggested solution

I propose listener with type external_headless. It will add to config the same params for broker, as it do in node_port type, but will not create service for each broker

**Comment by scholzj** [comment]
Sounds like a duplicate to https://github.com/strimzi/strimzi-kafka-operator/issues/3984?

**Comment by scholzj** [comment]
I don't think so. Or at least I'm not aware of anyone looking into it right now, sorry. Also, as described in the issue - we actually used the Pod IPs long time ago but moved away from them as they have their own issues.

**Comment by hennadii2012** [comment]
Yes, I have read about the pod IPs. Thank you for quick response
