### ISSUE TITLE
[Bug]: Kafka in KRaft mode doesn't have security.inter.broker.protocol set to SSL

### ISSUE THREAD

**Issue by deanmax** [strimzi/strimzi-kafka-operator#10903]
### Bug Description

In the documentation, it stated that when using Kafka in KRaft mode, communication between brokers should be TLS enabled.
<img width="1137" alt="Screenshot 2024-12-03 at 21 40 38" src="https://github.com/user-attachments/assets/79b2cda9-a6cc-4012-9183-45c98ac04b6e">

However, my brokers still shows `security.inter.broker.protocol: PLAINTEXT`
<img width="651" alt="Screenshot 2024-12-03 at 21 53 48" src="https://github.com/user-attachments/assets/c973c185-011b-477d-a846-39563cfa6879">
<img width="649" alt="Screenshot 2024-12-03 at 21 54 28" src="https://github.com/user-attachments/assets/4d165624-b4be-4fd7-8d42-6b0cd49a6eef">

And this value doesn't seem to be configurable
<img width="1534" alt="Screenshot 2024-12-03 at 21 55 57" src="https://github.com/user-attachments/assets/4e7ef7f9-f209-487e-b370-fcda7e2c748d">

### Strimzi version

0.44.0

### Kubernetes version

1.29

**Comment by scholzj** [comment]
It has the [`listener.security.protocol.map`](https://kafka.apache.org/documentation/#brokerconfigs_listener.security.protocol.map) set and configures it there. So as far as I know, that overrides whatever the default value is in `security.inter.broker.protocol`.

**Comment by deanmax** [comment]
Thanks! I see SSL on port 9091 on my broker, indicating TLS for inter-broker comm
```
listener.security.protocol.map = CONTROLPLANE-9090:SSL,REPLICATION-9091:SSL,PLAIN-9092:PLAINTEXT,TLS-9093:SSL
```
Closing issue.
