### ISSUE TITLE
[Enhancement]: Enable advertised listener port to be configured for all brokers or be part of AdvertisedHostTemplate

### ISSUE THREAD

**Issue by jayctran** [strimzi/strimzi-kafka-operator#10996]
### Related problem

With the 0.44.0 release, AdvertisedHostTemplates are possible but when leveraging ingress, generally it's port 443 that is used.

In our scenario, ingress service is on 443 and we'd need to configure the advertised host to be port 443.

With the HostTemplate and AdvertisedHostTemplate, we're able to use {nodeId} to not specify individual brokers, however there is no equivalent AdvertisedPort that can be specified for the template, or a GlobalAdvertisedPort that we could configure to make all brokers point to 443 - instead it uses the configured listener port unless we specify all the brokers individually anyway.

### Suggested solution

Have a global advertisedPort configuration that will be applied to the listener for all brokers unless overridden by a specific broker configuration. Something like between the lines of hashes:

```
public static Integer brokerAdvertisedPort(GenericKafkaListener listener, int pod)    {  
############################################################################
        if (listener.getConfiguration() != null  
                && listener.getConfiguration().getAdvertisedPort() != null) {  
            return listener.getConfiguration().getAdvertisedPort();  
        }
############################################################################
        elif (listener.getConfiguration() != null  
                && listener.getConfiguration().getBrokers() != null) {  
            return listener.getConfiguration().getBrokers().stream()  
                    .filter(broker -> broker != null && broker.getBroker() != null && broker.getBroker() == pod &&  
 broker.getAdvertisedPort() != null)  
                    .map(GenericKafkaListenerConfigurationBroker::getAdvertisedPort)  
                    .findAny()  
                    .orElse(null);  
        } else {  
            return null;  
        }  
    }
```

### Alternatives

Maybe modify advertisedHostTemplate to include an option for the port though I think the initial suggestion is way easier to implement.

**Comment by scholzj** [comment]
When using Ingress, Strimzi automatically uses port 443.

**Comment by jayctran** [comment]
Oh, for the advertised port? I thought I saw issues with it when I didn't have the port specified. Thanks, I will test it out.

**Comment by scholzj** [comment]
I'm not sure which issues you saw. But the `type: ingress` listeners always use 443 because they use TLS passthrough.

**Comment by jayctran** [comment]
It may be a much older version of strimzi when I had some issues but I can test it again to confirm.

However, I ran into a different issue when trying to use hostTemplate:
(kafka/cbi-cluster; kafka.strimzi.io/v1beta2, Kind=Kafka): .spec.kafka.listeners[0].configuration.hostTemplate: field not declared in schema

**Comment by scholzj** [comment]
That sounds like you have either too old Strimzi version or not updated CRDs (remember, if you use Helm you have to upgrade CRDs manually).

**Comment by jayctran** [comment]
Ah thank you for that, that is the reason as I am indeed using helm - I did not know this so glad to learn about it now!

I also tested again with the hostTemplate without a specific advertised port and with ingress it is still working with port 443.

Thank you again for being so quick to respond and appreciate the suggestions.
