### ISSUE TITLE
Test failure causes test failure

### ISSUE THREAD

**Issue by stanlyDoge** [strimzi/strimzi-kafka-operator#1099]
In case any system test fails, it logs `io.strimzi.test.k8s.KubeClusterException: java.io.IOException: Cannot run program "oc": error=2, No such file or directory`

After some investigation, I think it is caused by `String events = kubeClient().exec("oc", "get", "events").out();` in `Strimziextension.java`.

**Comment by serrss** [comment]
Issue was fixed by PR #1101
