### ISSUE TITLE
Refactor `SimpleAclOperator` to make use of Admin Client API

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1106]
Refactor `SimpleAclOperator` to make use of [KIP-332: Update AclCommand to use AdminClient API](https://cwiki.apache.org/confluence/display/KAFKA/KIP-332%3A+Update+AclCommand+to+use+AdminClient+API) when dealing with a Kafka 2.1 cluster.

**Comment by ppatierno** [comment]
This is also related to taking into account that the upstream Apache Kafka KIP-500 which is about removing the ZooKeeper dependency in Kafka.
