### ISSUE TITLE
Missing sections about `ResourceTemplate` and `MetadataTemplate` properties

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1130]
It seems that in the generated documentation, we are missing the documentation about `ResourceTemplate` and `MetadataTemplate` properties. `ResourceTemplate` is present, but empty. `MetadataTemplate` is missing completely. This might be bug in the CRD generator.

**Comment by samuel-hawker** [comment]
https://strimzi.io/docs/operators/latest/using.html#type-MetadataTemplate-reference
https://strimzi.io/docs/operators/latest/using.html#type-ResourceTemplate-reference

I think we can close this now as it was fixed some time ago. Is there any additional info missing here?

**Comment by scholzj** [comment]
Yeah, you are right.
