### ISSUE TITLE
Enable managment via Operator Framework - Operator Lifecycle Manager (OLM)

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi-kafka-operator#1147]
The Operator Lifecycle Manager (OLM) component of the Operator Framework (https://github.com/operator-framework/operator-lifecycle-manager) provides a declarative way to install, manage, and upgrade operators and their dependencies in a cluster. Some users may want to use OLM to install and manage the Strimzi operator as opposed to a Helm Chart or yaml manifests.

Provide the resources needed to make Strimzi available in the OLM Catalog and document the process for registering such resources with OLM. Also verify that Strimzi can co-exist in an OLM Catalog alongside a downstream Strimzi distribution.

Git repository https://github.com/operator-framework/community-operators/tree/master/community-operators appears to now be available to host such a contribution.

**Comment by scholzj** [comment]
I will close this issue. Strimzi is now part of the OLM as well as of the [OperatorHub.io](https://www.operatorhub.io/).
