### ISSUE TITLE
GC logging enabling logic is counterintuitive

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1171]
I think that using the CRD field `gcLoggingDisabled` is counterintuitive. We should try to use the opposite logic so `gcLoggingEnabled` which is already used in other case (i.e. `isMetricsEnabled`).

**Comment by scholzj** [comment]
How will it deal with the previous decision to keep it enabled by default?

**Comment by ppatierno** [comment]
For sure I am going to ask a stupid question but isn't it just a matter of defaulting to enable even when the field is not in the CR?

**Comment by scholzj** [comment]
Maybe ... I'm not sure what is inside the property. It would not for for
metrics.

**Comment by ppatierno** [comment]
> It would not for for metrics.

what do you mean?
