### ISSUE TITLE
High idle CPU usage from user-operator

### ISSUE THREAD

**Issue by benhwebster** [strimzi/strimzi-kafka-operator#1179]
On Strimzi 0.8.2, the user operator is using a relatively high amount of CPU, in a cluster with 22 users, all using TLS auth, with an average of 5-6 acls per user, the user operator idles at .3 core usage with spikes to .4. in another cluster with 14 users it idles at .2 and spikes to .3

22 user cluster
![image](https://user-images.githubusercontent.com/14381460/50229212-c73a7780-0377-11e9-96a0-522a292bfe02.png)

14 user cluster
![image](https://user-images.githubusercontent.com/14381460/50229220-ce618580-0377-11e9-9650-f79d3c09d1b2.png)

**Comment by scholzj** [comment]
Triaged on 10.5.2022: Lot of things changed since this issue was opened. We shold track the User operator scalability issues in #5790 which reflects some of the more recent changes.
