### ISSUE TITLE
Wrong version in examples kafka-ephemeral.yaml

### ISSUE THREAD

**Issue by arashkaffamanesh** [strimzi/strimzi-kafka-operator#1210]
The spec.kafka.version should be 2.0.1 and not 2.1.0 in kafka-ephemeral.yaml:

https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/examples/kafka/kafka-ephemeral.yaml

**Comment by tombentley** [comment]
The current default version of Kafka on `master` is indeed 2.1.0. In 0.9.0 is was 2.0.1. There's in progress work on documentating the upgrade procedure.

**Comment by arashkaffamanesh** [comment]
ok, thanks.
It means there will be a strimzi 1.0.0 version which supports 2.1.0?

**Comment by ppatierno** [comment]
It will be Strimzi 0.10.0. In any case the next release :)

**Comment by arashkaffamanesh** [comment]
Oh wow, thanks so much!
