### ISSUE TITLE
KafkaConnectCrdIT.testKafkaConnect fails with K8S v1.12

### ISSUE THREAD

**Issue by chonton** [strimzi/strimzi-kafka-operator#1212]
Validation of volumes.secret from 041-Crd-kafkaconnect.yaml fails with message:
```
type in spec.externalConfiguration.volumes.secret is required
type in spec.externalConfiguration.volumes.configMap is required
```
This occurs with kubernetes server version v1.12.4.  Upstream defect is https://github.com/kubernetes/kubernetes/issues/68466.  The issue description indicates that the defect starts with k8s-1.11.0

**Comment by scholzj** [comment]
LOL ... we use the `items` field just because it is part of the Kubernetes resources it self :-(.

**Comment by mfranczy** [comment]
@chonton I observed that on k8s-1.10.4, it's possible that the bug exists in earlier versions as well, I didn't check.

Hope it's gonna be fixed soon.

**Comment by scholzj** [comment]
I opened a PR to comment out the `items` fields from the test YAMLs. That should make the tests pass until this is fixed. Thanks for raising this issue.
