### ISSUE TITLE
LEADER_NOT_AVAILABLE error when trying to connect external client to kafka brokers

### ISSUE THREAD

**Issue by kurktchiev** [strimzi/strimzi-kafka-operator#1222]
Hello, so I have a simple 3 node cluster:
```
NAME                                         READY     STATUS    RESTARTS   AGE       IP              NODE
kafka-client                                 1/1       Running   0          3h        172.16.221.78   solserv1
my-cluster-entity-operator-f77f478fd-nlkqq   3/3       Running   0          3h        172.16.221.77   solserv1
my-cluster-kafka-0                           2/2       Running   0          3h        172.16.221.76   solserv3
my-cluster-kafka-1                           2/2       Running   0          3h        172.16.221.74   solserv1
my-cluster-kafka-2                           2/2       Running   0          3h        172.16.221.75   solserv2
my-cluster-zookeeper-0                       2/2       Running   0          3h        172.16.221.72   solserv3
my-cluster-zookeeper-1                       2/2       Running   0          3h        172.16.221.67   solserv1
my-cluster-zookeeper-2                       2/2       Running   0          3h        172.16.221.71   solserv2
strimzi-cluster-operator-7ff846fc5d-fcbk8    1/1       Running   0          3h        172.16.221.65   solserv1
```
I am exec into my kafka client pod and trying to run a quick producer test as follows:
```
kafka-producer-perf-test --print-metrics --topic test-rep-one --num-records 60000000 --throughput -1 --record-size 100 --producer-props bootstrap.servers=my-cluster-kafka-0.my-cluster-kafka-brokers.strimzi.svc.sol1.diamanti.com:9092,my-cluster-kafka-1.my-cluster-kafka-brokers.strimzi.svc.sol1.diamanti.com:9092,my-cluster-kafka-2.my-cluster-kafka-brokers.strimzi.svc.sol1.diamanti.com:9092 buffer.memory=67108864 batch.size=8196
```
However, I get greeted with a smattering of:
```
[2019-01-11 23:36:34,677] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 112 : {test-rep-one=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-01-11 23:36:34,781] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 113 : {test-rep-one=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-01-11 23:36:34,888] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 114 : {test-rep-one=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-01-11 23:36:34,995] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 115 : {test-rep-one=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-01-11 23:36:35,099] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 116 : {test-rep-one=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-01-11 23:36:35,203] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 117 : {test-rep-one=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
[2019-01-11 23:36:35,311] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 118 : {test-rep-one=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
```
The above is repeated infinitum... I am not sure why thats happening. I created the topic like this:
1. Exec into zookeeper-1
2. run: `[kafka@my-cluster-zookeeper-0 kafka]$ bin/kafka-topics.sh --zookeeper localhost:21810 --create --topic test-rep-one --partitions 6 --replication-factor 1`

Any thoughts or ideas are appreciated. I did have to install the operator with the suggested work around in #993 but other than that this is pretty vanilla setup on a relatively ordinary k8s cluster (non minikube)

**Comment by kurktchiev** [comment]
I have tried my connection string a few different ways in case its something with the advertised listeners but no luck:
Directly to IP of each kafka broker:
```
kafka-producer-perf-test --print-metrics --topic test-rep-one --num-records 60000000 --throughput -1 --record-size 100 --producer-props bootstrap.servers=172.16.221.76:9092,172.16.221.74:9092,172.16.221.75:9092 buffer.memory=67108864 batch.size=8196
```

Connect to the headless service for the brokers and let it resolve the clients as needed/wanted:
```
kafka-producer-perf-test --print-metrics --topic test-rep-one --num-records 60000000 --throughput -1 --record-size 100 --producer-props bootstrap.servers=my-cluster-kafka-brokers.strimzi.svc.sol1.diamanti.com:9092 buffer.memory=67108864 batch.size=8196
```

**Comment by scholzj** [comment]
What do you get when you describe the topic using `kafka_topics.sh`? You will probably also need to share the broker logs and the to give us more insight and the custom resource you used to create the cluster.

There is a bootstrap service which should be ideally used for the connections, in your case it should be named something like `my-cluster-kafka-bootstrap.strimzi.svc.sol1.diamanti.com`. You should ideally use this one. But I do not think this will be the problem in your case.

**Comment by kurktchiev** [comment]
The cluster is the example kafka-persistent.yaml you guys supply so nothing special. Just trying to test out a simple deploy and connect external clients. I will have to get the describe topic info and any logs you want later today

**Comment by kurktchiev** [comment]
The broker logs dont show anything of interest, the following block just repeats itself nonstop:
```
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
2019-01-11T20:08:40.213+0000: 0.258: [GC pause (G1 Evacuation Pause) (young), 0.0041915 secs]
   [Parallel Time: 3.7 ms, GC Workers: 1]
      [GC Worker Start (ms):  257.8]
      [Ext Root Scanning (ms):  1.9]
      [Update RS (ms):  0.0]
         [Processed Buffers:  0]
      [Scan RS (ms):  0.0]
      [Code Root Scanning (ms):  0.0]
      [Object Copy (ms):  1.7]
      [Termination (ms):  0.0]
         [Termination Attempts:  1]
      [GC Worker Other (ms):  0.0]
      [GC Worker Total (ms):  3.7]
      [GC Worker End (ms):  261.4]
   [Code Root Fixup: 0.0 ms]
   [Code Root Purge: 0.0 ms]
   [Clear CT: 0.0 ms]
   [Other: 0.5 ms]
      [Choose CSet: 0.0 ms]
      [Ref Proc: 0.3 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.0 ms]
      [Humongous Register: 0.0 ms]
      [Humongous Reclaim: 0.0 ms]
      [Free CSet: 0.0 ms]
   [Eden: 4096.0K(4096.0K)->0.0B(4096.0K) Survivors: 0.0B->4096.0K Heap: 4096.0K(128.0M)->826.9K(128.0M)]
 [Times: user=0.00 sys=0.00, real=0.00 secs]
2019-01-11T20:08:40.293+0000: 0.338: [GC pause (G1 Evacuation Pause) (young), 0.0031843 secs]
```

**Comment by scholzj** [comment]
The topic looks good. It shows the leaders. The repeating thing form the log is just the Garbage Collector log from JVM. I wonder if the client actually connects to the brokers properly if there is no log message. Maybe you could increase the log level in the Kafka resource to see more.

**Comment by kurktchiev** [comment]
Why would it not connect at all? What is the container listening on? As far as I can tell from the service and container definitions it’s the same ports as those exposed.

**Comment by scholzj** [comment]
TBH, I don't know. But the topics seems to have the leaders assigned and there don't seem to be any issues in the Kafka logs. So it was one of the things which came to my mind.

**Comment by kurktchiev** [comment]
Any other ideas? It seems pretty important to be able to connect an external client to a cluster :D there any other place I can look for what is going on? I am trying to only do un-encrypted traffic at the moment so I am connecting to the unsecured ports

**Comment by scholzj** [comment]
Wait, I'm not sure what do you mean with external client - I though you were running your client inside a pod in the same cluster. If you want to run the client outside of your Kubernetes cluster, you would need to use one of the external listeners. Either using load balancers or node ports.

**Comment by kurktchiev** [comment]
Sorry, I meant “external” as in a non strimzi CRD connection. I am indeed running a pod inside the cluster that is failing to connect

**Comment by kurktchiev** [comment]
Also, is it possible to define my own external? As in pass in my own string rather than the predefined route/LB/NP? What if I wanted to pass in a config as such: EXTERNALS://${POD_IP} where POD_IP=refspec.pod_ip from kube?

**Comment by kurktchiev** [comment]
What if I have a platform where that is not a problem? Having the ability to customize the listeners would be useful. However, I still need to get at least in-cluster communication working before I keep talking about the external bits :)

**Comment by scholzj** [comment]
Do you have such platform? If yes, I would be interested to hear more about it to better understand it. I think our ideal plan is that things work out of the box. That you don't have to care about these things. 

Back to your original problems ... could you share the whole logs from the the brokers? It would be also great if you can try to increase the log level in the client, so that we can better see where it is connecting and what it is doing. Thanks.
