### ISSUE TITLE
SASL authentication with custom callback handler

### ISSUE THREAD

**Issue by dineshudayakumar** [strimzi/strimzi-kafka-operator#1234]
Documentation says that Kafka properties starting with "listener." or "sasl." are forbidden. And SASL/SCRAM-SHA has a recommendation to use custom call back handler in case zookeeper is not secure. So want to set the Kafka property sasl.server.callback.handler.class, listener.name.sasl..plaintext.plain.sasl.server.callback.handler.class to have our own call back handler which can go to our Auth Service to authenticate the clients. But from the docs it looks like that is not possible, can you confirm? (Whats needed is we want to use our A&A service for doing the authentication and the plan is Clients will get the token from the A&A service and pass to Kafka using SASL mechanism and the SASL custom call back handler will validate the token by connecting to A&A service

**Comment by scholzj** [comment]
Nice. Keycloak is what we might be targeting as well. Is your code somewhere open-sourced? It would be interested to at least compare it when we start working on our implementation.

**Comment by dineshudayakumar** [comment]
Sorry for the delay
No, it is not open-source
Also, we are just starting with the integration, we don't have much in place as well. Also we plan to integrate using the sasl.server.callback.handler to validate the token passed from the client

**Comment by scholzj** [comment]
@dineshudayakumar I know this is fairly old issue and not sure whether it is still valid. But we have now our own support for OAuth authentication which works with Keycloak. So, does that handle your use-case? If not, there are now proposals dealing with custom authentications:
* https://github.com/strimzi/proposals/pull/42
* https://github.com/strimzi/proposals/pull/41

So it might be worth checking them out and making sure they work for you.
