### ISSUE TITLE
tls-sidecar container creshes

### ISSUE THREAD

**Issue by guyklein24** [strimzi/strimzi-kafka-operator#1241]
I am trying to deploy Strimzi on Openshift private cloud.

First I deployed the cluster-operator and the templates exactly as described in the docs.

The cluster-operator was up and running.

Then, I deployed a Kafka ephemeral cluster from the console with the default parameters.
The operator created zookeeper StatfulSet but the pods stuck in Crash loop Back-off.
I noticed the the zookeeper container is running but the one who crashes is the tls-sidecar.
It looks like it not doing anything, it just runs the entrypoint and complete.

I am using the latest version of Strimzi and latest docker images with Openshift Container Platform 3.9

**Comment by scholzj** [comment]
What version of Strimzi are yo using? Can you provide the log from the TLS sidecar? Thanks

**Comment by guyklein24** [comment]
I am using the latest version which is 0.9.0.
The TLS sidecar has no logs it just keeps crashing.

**Comment by ppatierno** [comment]
@guyklein24 aren't you able to get the TLS sidecar log with `oc logs -p` in order to get the previous one before crashing?

**Comment by guyklein24** [comment]
Nope.

Actually I think it has something to do with the docker images versions.

The issue happened when I used the master branch files not 0.9.0*

I did that because when using the 0.9.0 release I had some troubles with RBAC permissions.

I will try to download again the 0.9.0 images and use Strimzi  0.9.0 files.

**Comment by ppatierno** [comment]
Do you get some errors in the Event section in the OpenShift web console?
Can you use the `oc describe` command to see if we can get more information?

**Comment by guyklein24** [comment]
The events only show:
Back-off restarting failed container

oc describe shows the same:
As I mentioned, the zookeeper container is running but tls-sidecar stuck in CrashLoopBackOff.

**Comment by ppatierno** [comment]
The zookeeper container is running but it's not working because it needs the tls-sidecar.
I am using the master right now and I don't have this kind of problem.
Can you check what secrets were recreated in the cluster, if there are the certificates related Secrets?

**Comment by guyklein24** [comment]
The following secrets has been created:
my-cluster-client-ca
my-cluster-client-ca-cert
my-cluster-cluster-ca
my-cluster-cluster-ca-cert
my-cluster-cluster-operator-certs
my-cluster-zookeeper-nodes

Looks like to container has mounted the secrets volumes successfully.

Can you please provide me a list with the docker images that I need to download for the master version?

**Comment by guyklein24** [comment]
I am running in a private network so I need to download the images.

**Comment by scholzj** [comment]
I think this is too old and not valid anymore since the TLS sidecars from Kafka and Zookeeper pods are gone now. I will close this issue.
