### ISSUE TITLE
Improve use of events in the Topic Operator

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1245]
The Topic Operator creates K8s `Event` objects when processing fails for various reasons. The Events created aren't always very helpful.

This could be improved in the following ways:

* We should set the first seen, last seen and the count. 
* Where possible we should set a subobject
* We should ensure the message is useful

We should also explore using alternatives to using `Events`: Using a `status` subresource might be a better way of dealing with errors related to an individual topic.

**Comment by scholzj** [comment]
Triaged on 22.02.2022: Do we want to keep the events or get rid of them instead? The status subresource mentioned here is already supported and used. We should revisit it next time with @tombentley

**Comment by scholzj** [comment]
Triaged on 3.3.2022: We should keep the existing events, btu it does not seem to make much sense to implement this improvement. Should be closed.
