### ISSUE TITLE
Make it easier for Strimzi and its different versions to co-exist in the same cluster

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1247]
There are several things which make running different versions of Strimzi and AMQ Streams in the same cluster complicated. They almost always relate to the cluster wide resources:

* Cluster Roles: We are relying on pre-defined cluster roles. But these change from release to release. This might cause problems when the versions of Strimzi are overwriting each others roles. Despite us originally trying to avoid it, it might be best to just grab the rights to creating cluster roles and create them per cluster / namespace. That would make sure that each CO deployment and each cluster might have their own Cluster Roles and not run into conflict.
* The CRDs are currently shared between Strimzi versions. They are also shared across all versions. This is another point where things can easily overwrite each other. Not sure there is an easy solution here. We should do more versioning of the CRDs. But even that would not get us out of the woods because we will not update the version with every single release. So I'm not sure whether it really matters so much.

**Comment by iptrha** [comment]
Can you please add a note to the existing documentation and suggest a workaround?

**Comment by Mikedu1988** [comment]
looking forward to it. in the same cluster, I'm running 0.5.x, and I had to delete all strimzi components to upgrade to 0.8.0, and now I want to upgrade to 0.10.0 again....

**Comment by scholzj** [comment]
I do not think you have to delete 0.8.0 because of 0.10.0. I think it
should be able to coexist. You should just install the new CRDs and RBAC -
they should work with 0.8.0 as well. If you have any problems, I would be
interested to hear more about the details.

**Comment by stanlyDoge** [comment]
Is this dup of https://github.com/strimzi/strimzi-kafka-operator/issues/804 ?

**Comment by keithfenechgig** [comment]
Hi I am encountering the same issue that @scholzj encountered. It seems that I cannot have 2 different versions of Kafka strmzi on the same kube cluster. Is there a plan to have CRD versioning for example to combat this issue please?

**Comment by scholzj** [comment]
This is not something CRD versioning solves (plus we use CRD versioning).This is something what can be properly solved only by having proper multi-tenancy in Kubernetes. Until that is there, you can do following:
* Install the latest CRDs only
* Install the latest ClusterRoles
* Rename the ClusterRoleBindings to not clash

You just need to be careful to for example not delete the CRDs when uninstalling one of the operators.

**Comment by keithfenechgig** [comment]
@scholzj But what if the CRD itself changes between versions and it remains with the same apiVersion like v1beta1 ? and as far as I know you can only have one version of a CRD or am I wrong?  

For example in the new version of the operator it uses a list for the listeners however in the previous version it was using key value pairs (i am referring to the kind Kafka resource). 

I can't understand how renaming the clusterRoleBindings will solve this problem.

Thanks for your help

**Comment by scholzj** [comment]
Any changes to the version of the CRD we do are always backwards compatible. The array style listeners in the new version of Strimzi was added, but the old format is still supported. So it is backwards compatible. Only in `v1beta2` we will remove the old listener configuration to not break the compatibility. AFAIK this is the same approach as Kubernetes take when adding new fields to the existing resources.

But as you said, as long as you can have only one version of the CRD, this is really just a hacky workaround and not a proper solution. Only some proper - or namespaced CRDs (which are AFAIK not planned to be supported) would offer a proper solution.

**Comment by keithfenechgig** [comment]
Further to the above so lets say I have 2 version (one in a namespace and one in another namespace) and I upgrade one to the latest version where the CRD now changes to v1beta2 and the other one in the other namespace will still be on an older version which is working with v1beta1. In this case would both work as well because in the CRD we have the version section as shown below please or it is not the case?

![image](https://user-images.githubusercontent.com/69241143/102327735-75d51b00-3f86-11eb-9026-1edceb401c77.png)

Thanks again

**Comment by scholzj** [comment]
TBH, I do not know. That is why I called it hacky workaround ... such things might stop working at some point. It is even more complicated, because there is move to CRV v1 which we need to do as well. But that is what I said before ... having more versions does not really help 🤷🏻‍♂️ .

**Comment by keithfenechgig** [comment]
ok thanks. 

one more question what do you mean by "Rename the ClusterRoleBindings to not clash" ?

When I try to install for example an older version in a  different namespace, it does not create any resources or ClusterRoleBindings etc so I dont have anything to rename and I see the following error in the OperatorLifecycleManagement pod:

`time="2020-12-16T13:10:39Z" level=info msg="error updating ClusterServiceVersion status: Operation cannot be fulfilled on clusterserviceversions.operators.coreos.com \"packageserver\": the object has been modified; please apply your changes to the latest version and try again" csv=packageserver id=U6xHi namespace=openshift-operator-lifecycle-manager phase=Succeeded
E1216 13:10:39.503651       1 queueinformer_operator.go:290] sync {"update" "openshift-operator-lifecycle-manager/packageserver"} failed: error updating ClusterServiceVersion status: Operation cannot be fulfilled on clusterserviceversions.operators.coreos.com "packageserver": the object has been modified; please apply your changes to the latest version and try again`

**Comment by scholzj** [comment]
Hmm, if you always install it with OLM you probably do not need to do this. If you install from YAMLs, it has some ClusterRoleBindings with fixed names which you need to change in order to exist multiple times and point to different service accounts in different namespaces

**Comment by keithfenechgig** [comment]
Ok understood. Having said that I think no ServiceAccount or CRB are being created because it stops with this error:
`error validating existing CRs agains new CRD's schema: kafkas.kafka.strimzi.io: error validating custom resource against new schema &apiextensions.CustomResourceValidation{OpenAPIV3Schema:(*apiextensions.JSONSchemaProps)(0xc004c24800)}: [].spec.kafka.listeners: Invalid value: "array": spec.kafka.listeners in body must be of type object: "array"`

It seems that they 0.19 and 0.20 are not backward compatible

**Comment by scholzj** [comment]
They are ... this error suggests that you have the 0.19 version of the CRDs - that of course doesn't allow the new format. But the new CRD allows the new format as well as the old format. 

TBH I'm not sure whether OLM has any special feature to keep the latest CRDs. Last time I tried it (but that was on OpenShift) it didn't let me install different versions in different namespaces. That is why I assumed one would be using the YAMLs where you control this pretty much manually by what you apply.

**Comment by scholzj** [comment]
This issue should be closed. There is not much we can do about Kubernetes not being multi-tenant and not supporting multiple CRDs of the same kind. For ClusterRoles / ClusterRoleBindings, #804 should be used as the main issue.
