### ISSUE TITLE
Avoid [source,shell] snippets in docs requiring scrolling

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1250]
We should try to avoid using `[source,shell]` examples in the documentation which result in the user having the horizontally scroll, for example:

https://strimzi.io/docs/master/#proc-adding-users-the-strimzi-admin-role-str

Imho it's better to use explicit line breaks escaped by `\`.

This could probably be added to the existing docs checks relatively easily by simply checking each `[source,shell]` for lines longer than some threshold.

**Comment by PaulRMellor** [comment]
@tombentley Helo Tom. I think we should be as copy-friendly as we can. Shall I keep this open?

**Comment by tombentley** [comment]
I guess I don't have a terribly strong opinion.
