### ISSUE TITLE
Missing enforcement on having required `size` on a `PersistentClaimStorage`

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1251]
As stated by the current documentation, the `size` on a `PersistentClaimStorage` is mandatory.

> Mandatory when type=persistent-claim.

Actually, this requirement is not enforced by api nor by a CO checks but deploying a Kafka cluster without that fields ends with the following event on creation (i.e. Zookeeper part).

> create Claim data-my-cluster-zookeeper-0 for Pod my-cluster-zookeeper-0 in StatefulSet my-cluster-zookeeper failed error: PersistentVolumeClaim "data-my-cluster-zookeeper-0" is invalid: spec.resources[storage]: Invalid value: "0": must be greater than zero

We should set the `size` field as required at API level.

**Comment by scholzj** [comment]
I know that there were issues when setting fields as mandatory when they are only present for one type. I think you might need to do this on the CO level.

**Comment by ppatierno** [comment]
Yeah I realized that due to the inheritance, PR is coming.
