### ISSUE TITLE
Zookeeper scaleup should be done in steps

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#126]
The current implementation of Zookeeper scale up goes directly to the final number of nodes. This can be a problem. For example when the scale up would be from 3 nodes to 7 nodes, the existing cluster would loose quorum. So the Zookeeper scale-up should be probably done in smaller steps. This should apply only to Zookeeper. Kafka should not need this for scaling up.

**Comment by stanlyDoge** [comment]
I think this can be closed. Right? @tombentley

**Comment by tombentley** [comment]
Yes
