### ISSUE TITLE
When Zookeeper leader is not found, the rolling update should probably still continue

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1262]
It seems that when we find no Zookeeper leader, the rolling update fails:

```
2019-01-27 22:51:04 INFO  AbstractAssemblyOperator:157 - Reconciliation #1(timer) Kafka(myproject/my-cluster): Assembly my-cluster should be created or updated
--
  | 2019-01-27 22:51:05 INFO  ZookeeperSetOperator:327 - my-cluster-zookeeper-0 is not a leader
  | 2019-01-27 22:51:05 INFO  ZookeeperSetOperator:327 - my-cluster-zookeeper-1 is not a leader
  | 2019-01-27 22:51:05 INFO  ZookeeperSetOperator:327 - my-cluster-zookeeper-2 is not a leader
  | 2019-01-27 22:51:05 ERROR AbstractAssemblyOperator:166 - Reconciliation #1(timer) Kafka(myproject/my-cluster): createOrUpdate failed
  | io.vertx.core.impl.NoStackTraceThrowable: Zookeeper leader could not be found
```

But it could very well be that Zookeeper leader does not exist for a reason and the rolling update needs to continue to fix it.

**Comment by tombentley** [comment]
That's true, but it could also happen during a leader election, for example. IOW there are circumstances where proceeding when there isn't a leader is at best counter productive, if not harmful. We could back off and retry and proceed only after some number of failed attempts to find the leader.

**Comment by scholzj** [comment]
I did not find a way how to easily reproduce it. But reading from the code (which was completely rewritten since this issue was raised), it does not seem to be the case anymore. I think this issue can be closed.

**Comment by scholzj** [comment]
Triaged on 21.7.2022: Should be closed, seems to be implemented already.
