### ISSUE TITLE
Ability to watch all namespaces and not just nominated ones.

### ISSUE THREAD

**Issue by GrahamDumpleton** [strimzi/strimzi-kafka-operator#1292]
Documentation suggests that the operator must be configured and told which specific namespaces it should monitor. This is by setting the ``STRIMZI_NAMESPACE`` variable:

* https://strimzi.io/docs/master/#deploying-cluster-operator-kubernetes-to-watch-multiple-namespacesdeploying-co

If this is true and that is the only way to have it monitor multiple namespaces, this makes setting up a training/demonstration environment which promotes the operator a problem, as you wouldn't know what the names of the projects will be in advance.

Is there any way to have the operator monitor all namespaces? Will setting that field empty result in that? Or could the field perhaps accept a wildcard so could say ``*`` or ``project-prefix-*`` and have it monitor multiple namespaces where the name isn't know in advance? Of note, the projects may only be created after the operator is deployed, so the operator can't only check for projects to monitor when first started.

The background behind this question is that want to use the operator as one of a set to promote operators for OpenShift, more specifically, use of the operators by developers. So we don't want people having to do operations setup, the operator should already be pre-created in the cluster. The training environment users use though means they get assigned projects to work in dynamically on demand with unknown names. So in this case it seems the operator cannot work. We don't want them to have to be installing the operator in every project, we just want them using it.

Any suggestions?

If forced to allocate projects from a pre-defined set of project names that are configured into ``STRIMZI_NAMESPACE``, will the operator handle a large number of projects being listed, and will it work even if the project with that name doesn't exist when the operator is started, but created later?

**Comment by scholzj** [comment]
Actually, this is a brand new feature which we have. You can specify `*` and the Cluster Operator will watch the whole cluster. It is currently available only in master - it will be released towards the end of month in 0.11.0. The documentation is still as a PR #1279 which is being reviewed, but it should give you an idea how to use it if you want to five it a try.

**Comment by GrahamDumpleton** [comment]
Excellent. Time frame for needing it is May (Summit), so that not yet released yet is okay. So long as use ``strimzi/cluster-operator:latest`` and ``*`` at this point I should be good. Thanks.

**Comment by GrahamDumpleton** [comment]
Do you have images automatically built off ``master`` anywhere that can be pulled down and used? I wrongly assumed ``latest`` would be that, but it isn't.

**Comment by scholzj** [comment]
The latest images are built from master on every push - did the feature not work for you with them?

**Comment by GrahamDumpleton** [comment]
Okay, I ran:

```
oc adm policy add-cluster-role-to-user strimzi-cluster-operator-namespaced --serviceaccount strimzi-cluster-operator -n my-project
oc adm policy add-cluster-role-to-user strimzi-entity-operator --serviceaccount strimzi-cluster-operator -n my-project
oc adm policy add-cluster-role-to-user strimzi-topic-operator --serviceaccount strimzi-cluster-operator -n my-project
```

this time and it may be working.

Still have the question about whether rolebindings need to be applied to all projects as well though.

**Comment by scholzj** [comment]
Right. If you want Strimzi to watch the whole cluster / all namespaces, you will need to give it access to all namespaces. The RoleBindings are basically not needed at all anymore. You have to replace them with the ClusterRoleBindings which give us access to the whole cluster. That is actually one fo the reasons why we originally didn't supported this, since it seems that the actual users do not want to give us these rights :-o.

**Comment by GrahamDumpleton** [comment]
Okay, that will make it easier for me.

FWIW. I haven't gone through yet to see if this is an issue, but if the ``oc adm policy`` commands are run before doing the deployment as docs now say, you get warnings:

```
$ oc adm policy add-cluster-role-to-user strimzi-cluster-operator-namespaced --service
account strimzi-cluster-operator
Warning: role 'strimzi-cluster-operator-namespaced' not found
Warning: ServiceAccount 'strimzi-cluster-operator' not found
cluster role "strimzi-cluster-operator-namespaced" added: "strimzi-cluster-operator"
```

Things should probably be okay as they will match up when created, but a warning in docs may be needed if I have done this right and you will get that with a fresh install.

**Comment by scholzj** [comment]
What version of OpenShfit / of the `oc` client are you using? I do not think the 3.9 was giving me this warnings. But AFAIK these are really just a warnings - if you later create the role / service account it should link up and work fine.

**Comment by GrahamDumpleton** [comment]
I am using 3.11. Just busy right now, but will check the install again shortly to make sure it all works.

**Comment by scholzj** [comment]
Right. I think I tested it on 3.11 as well ... but I used the 3.9 client which doesn't print these warnings.

**Comment by GrahamDumpleton** [comment]
I take it back, is not entirely working even when using the ``example`` yaml file. It worked first time as didn't realise did it as a cluster admin. As a non cluster admin there are RBAC issues.

```
$ oc apply -f strimzi-kafka-operator/examples/kafka/kafka-ephemeral.yaml
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "kafka.strimzi.io/v1alpha1, Resource=kafkas", GroupVersionKind: "kafka.strimzi.io/v1alpha1, Kind=Kafka"
Name: "my-cluster", Namespace: "try-kafka-am0k1"
Object: &{map["apiVersion":"kafka.strimzi.io/v1alpha1" "kind":"Kafka" "metadata":map["name":"my-cluster" "namespace":"try-kafka-am0k1" "
annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "spec":map["zookeeper":map["storage":map["type":"ephemeral"] "r
eplicas":'\x03'] "entityOperator":map["topicOperator":map[] "userOperator":map[]] "kafka":map["storage":map["type":"ephemeral"] "version
":"2.1.0" "config":map["offsets.topic.replication.factor":'\x03' "transaction.state.log.min.isr":'\x02' "transaction.state.log.replicati
on.factor":'\x03' "log.message.format.version":"2.1"] "listeners":map["plain":map[] "tls":map[]] "replicas":'\x03']]]}
from server for: "strimzi-kafka-operator/examples/kafka/kafka-ephemeral.yaml": kafkas.kafka.strimzi.io "my-cluster" is forbidden: User "
system:serviceaccount:kafka:try-kafka-am0k1" cannot get kafkas.kafka.strimzi.io in the namespace "try-kafka-am0k1": no RBAC policy match
ed
```

The odd wrinkle in this case is that the ``oc apply`` command is run from a container which is run as a service account which is given ``admin`` rights on the project. That is, it isn't an authenticated user. Deploying anything else from the service account is usually not an issue.

Can you confirm that a non cluster admin, potentially service account, should be able to deploy using the operator CRD? It seems the template failure through the web console was similar RBAC issue.

**Comment by GrahamDumpleton** [comment]
Okay, confirmed normal user can't do anything and need to delegate roles first per:

* https://strimzi.io/docs/master/#proc-adding-users-the-strimzi-admin-role-str

**Comment by alexandru-tetelea** [comment]
After one  hour of search found this

https://strimzi.io/docs/0.16.2/full.html#deploying-cluster-operator-to-watch-whole-cluster-str
```
Create ClusterRoleBindings that grant cluster-wide access to all namespaces to the Cluster Operator.

Use the kubectl create clusterrolebinding command:

kubectl create clusterrolebinding strimzi-cluster-operator-namespaced --clusterrole=strimzi-cluster-operator-namespaced --serviceaccount **my-namespace**:strimzi-cluster-operator
kubectl create clusterrolebinding strimzi-cluster-operator-entity-operator-delegation --clusterrole=strimzi-entity-operator --serviceaccount **my-namespace**:strimzi-cluster-operator
kubectl create clusterrolebinding strimzi-cluster-operator-topic-operator-delegation --clusterrole=strimzi-topic-operator --serviceaccount **my-namespace**:strimzi-cluster-operator

**Replace my-namespace with the namespace in which you want to install the Cluster Operator.**
```
