### ISSUE TITLE
0.10.0 doesnt run on openshift 3.7

### ISSUE THREAD

**Issue by cameronbraid** [strimzi/strimzi-kafka-operator#1297]
Just tried an upgrade from 0.9.0 to 0.10.0 on a openshift 3.7 cluster and it failed. 

Issue is there is no StatefulSets in apps/v1 ,  since openshift 3.7 uses apps/v1beta1

Is this something you can detect and use apps/v1beta1 ?

**Comment by scholzj** [comment]
This is probably related to the upgrade of the Kubernetes client. However, I'm afraid we never supported OpenShift 3.7 and there were a lot of limitations even with the past releases. Our target right now is to support OpenShift 3.9 and higher and Kubernetes 1.9 and higher.
