### ISSUE TITLE
Run all components under their own service account

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1299]
Currently, some of our components are running under the default service account. That can cause some limitations in how users can customize the deployments / service accounts. They would need to customize the default SA which will affect all applications. We should have a separate SA for each components even if it currently doesn't require any special RBAC rights. This should include for example Kafka Connect, Mirror Maker, Zookeeper etc.

This came up when discussing the HDFS sink connector in Kafka Connect. It seems this connector in some cases takes the Linux username and uses it for communication with HDFS. For this reason you might want to run the Kafka Connect container under some specific user account. But this might require setting the SCC context on the service account. And it would be nice if this SCC setting can be done only on the service account specific to this deployment and not on the default one.

**Comment by danxmoran** [comment]
@scholzj I'd be interested in working on (at least part of) this. Any pointers for how to get started on setting the SA for Zookeeper?

**Comment by danxmoran** [comment]
Ah wait, it looks like this was done in #1369. Should this ticket be closed?

**Comment by scholzj** [comment]
@danxmoran Yeah, sorry ... I think this was already done and should be closed. Looks like we forgot to close it.

**Comment by danxmoran** [comment]
No worries @scholzj! Less work for me 😎
