### ISSUE TITLE
Expose Kafka Connect REST API to the outside world

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#130]
It should be possible to expose Kafka Connect to the outside of OpenShift / Kubernetes world.

**Comment by scholzj** [comment]
Reviewed on 10th Sep 2020: This might still make sense after security is solved. We should keep it open for the time being.

**Comment by sokolbiba** [comment]
Is it possible to secure the Kafka Connect REST api implemented by strimzi KafkaConnect?

**Comment by scholzj** [comment]
> Is it possible to secure the Kafka Connect REST api implemented by strimzi KafkaConnect?

No, that is currently not supported.
