### ISSUE TITLE
Kafka cluster deployment fails when using persistent storage

### ISSUE THREAD

**Issue by aditisrinivas97** [strimzi/strimzi-kafka-operator#1307]
I tried to deploy a kafka cluster on GKE using the example files, [kafka-persistent.yaml](https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka/kafka-persistent.yaml) and [kafka-persistent-single.yaml](https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka/kafka-persistent-single.yaml). It fails with the following error,
```
2019-02-06 10:25:51,083 ERROR There was an error in one of the threads during logs loading: org.apache.kafka.common.KafkaException: Found directory /var/lib/kafka/data/lost+found, 'lost+found' is not in the form of topic-partition or topic-partition.uniqueId-delete (if marked for deletion).
Kafka's log directories (and children) should only contain Kafka topic data. (kafka.log.LogManager) [main]
2019-02-06 10:25:51,087 ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]
org.apache.kafka.common.KafkaException: Found directory /var/lib/kafka/data/lost+found, 'lost+found' is not in the form of topic-partition or topic-partition.uniqueId-delete (if marked for deletion).
Kafka's log directories (and children) should only contain Kafka topic data.
```
This can be fixed easily. Do take a look at it. Thanks.

**Comment by scholzj** [comment]
We for sure do not expect any files or directories which do not belong to Kafka on it. I'm not sure how exactly did this directory got there. But fro my understanding it might have been created by the OS after some damage happened to the file system. In such case it probably needs a manual intervention to make sure whether ti can be deleted or what to do with it.

**Comment by aditisrinivas97** [comment]
Oh, alright! Thanks for the quick reply! I'll look into it.

**Comment by scholzj** [comment]
Actually, it turns out that if you were using the latest version from master this was related to some changes we did when implementing the support for JBOD storage. I opened a PR #1321 which should address it.

**Comment by aditisrinivas97** [comment]
Thanks a lot for looking into this!
