### ISSUE TITLE
[Docs] Step numbers missing from 8.2.3. Upgrading brokers to a newer Kafka version

### ISSUE THREAD

**Issue by laidan6000** [strimzi/strimzi-kafka-operator#1308]
Several numbers are missing from the procedure in section 8.2.3, Upgrading brokers to a newer Kafka version -- see https://strimzi.io/docs/master/#proc-upgrading-brokers-newer-kafka-str

Instead of numbers, the `+` (AsciiDoctor linebreak) character is visible.

**Comment by tombentley** [comment]
I'm guessing this is becuase in `snip-kafka-versions.adoc` there are not `+` between the paragraphs, so after inclusion asciidoc doesn't see a continuation of the list. Maybe we should just have the table in that file.

**Comment by scholzj** [comment]
Since the PR has been merged, can we close this?

**Comment by laidan6000** [comment]
Yes, we can. I've checked the procedure on `master` and it looks good now.
