### ISSUE TITLE
Use paged list query when reconciling all topics

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1311]
Kubernetes supports _paged_ listing resources (e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#list-62). When reconciling all topics we need to fetch all the `KafkaTopics` and currently we do this in the naive way fetching the whole result set. With very large numbers of topics this could limit scalability of the operator. We should seek to identify the scale at which this could be a problem and if this is a practical problem we should use paged listing to avoid this.

**Comment by scholzj** [comment]
The Bidirectional Topic Operator (BTO) has been replaced by the new Unidirectional Topic Operator from Strimzi 0.39. There are no plans to fix any outstanding issues in the old BTO and this issue can be closed.
