### ISSUE TITLE
Entity operator fails to come back up when minishift is restarted

### ISSUE THREAD

**Issue by jroper** [strimzi/strimzi-kafka-operator#1347]
Running on Minishift v1.26.1+1e20f27, if I deploy a Kafka instance, then stop Minishift, then start Minishift again, the entity operator crashes and fails to come back up. In its logs, it just shows this error message:

```
Error from server (BadRequest): a container name must be specified for pod strimzi-entity-operator-6fc8d47cc9-h6dd4, choose one of: [topic-operator user-operator tls-sidecar]
```

**Comment by scholzj** [comment]
The Entity Operator consists of several containers. To get the actual logs, you need to specify the container name: `kubectl logs <pod-name> -v <container-name>`. E.g. `kubectl logs strimzi-entity-operator-6fc8d47cc9-h6dd4 -c topic-operator`. Could you check it out and try to provide the logs? 

What is the actual behaviour of the pod? Is it just looping? Also, is this reproducible? I.e. does that happen anytime you `minishift stop` and `minishift start`?

**Comment by jroper** [comment]
Thanks, that error message now makes perfect sense, seems obvious in hindsight :flushed:

I will get you the information requested as soon as I can.

**Comment by jroper** [comment]
It appears to be readily reproducible (I've noticed it happening a number of times before, and when I just tried deploying a new Kafka and then restarting then, it happened, I can't say that I've ever seen a time where restarting didn't trigger this). I've just started a 1 node Zookeeper 1 node Kafka cluster (because limited resources) which I've called `strimzi`, it worked fine (messages were successfully delivered) prior to restart, after restart I see this:

```
strimzi-cluster-operator-d77476b8f-gn6ts   1/1       Running            2          14m
strimzi-entity-operator-6fc8d47cc9-q2hm6   2/3       CrashLoopBackOff   7          12m
strimzi-kafka-0                            2/2       Running            4          13m
strimzi-zookeeper-0                        2/2       Running            2          13m
```

Oddly enough though, the problem seems to have resolved itself this time, I haven't seen that happen before, so maybe it was a different problem this time. I didn't capture the logs of it failing unfortunately, but this event did occur:

```
docker://user-operator:Container failed liveness probe.. Container will be killed and recreated.
```

I'm sure I'll see a scenario where things terminally fail again, when I do, I'll update this issue.

**Comment by scholzj** [comment]
TBH, I think it always needs some time to recover after being stopped and I'm not completely sure whether we will be able to do something with it. But if you manage to get the logs just share them here.

Out of curiosity - for your cluster - are you using persistent or ephemeral storage?
