### ISSUE TITLE
When shutting down a kafka cluster resource, zookeeper is deleted before kafka

### ISSUE THREAD

**Issue by chonton** [strimzi/strimzi-kafka-operator#1355]
When deleting a kafka cluster resource, zookeeper pods are shutdown first, then kafka pods.   I would expect the kafka pods to be deleted before the zookeeper pods.

**Comment by scholzj** [comment]
The deletion is done through the Kubernetes garbage collection. I do not think there is any particular order in which it deletes things and I do not think we can really influence it anyway. 

The question is whether you care about that when you are deleting the cluster.

**Comment by chonton** [comment]
I don't care.  I was just surprised and was wondering it this behavior was expected.
