### ISSUE TITLE
Error while exposing kafka with loadbalancer tls=false

### ISSUE THREAD

**Issue by Dec-** [strimzi/strimzi-kafka-operator#1357]
Kafka broker won't start when we set TLS to false.

Error stack trace:

```
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
--
  | at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:268)
  | at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
  | at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
  | at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:264)
  | at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:97)
  | at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1694)
  | at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:348)
  | at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
  | at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
  | at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
  | at kafka.Kafka$.main(Kafka.scala:75)
  | at kafka.Kafka.main(Kafka.scala)
```

**Comment by scholzj** [comment]
These things normally should not be related. Could you please share the following information:
* Strimzi and Kubernetes version
* Full log from the Kafka broker (including the configuration which is printed at the beginning)
* Your Kafka custom resource
* Your Cluster operator logs

**Comment by Dec-** [comment]
It works now, we increased liveness and readiness checks and it up and running :)

If we want to connect from the local PC to the kafka cluster is this the URL: "kafka-0.xxxx.xxx.xxx:{svc port}" ?

**Comment by scholzj** [comment]
When using loadbalancers, you will always need to find the address of the bootstrap loadbalancer and connect to it on port 9094. More details how to find the loadbalancer address are in the docs: https://strimzi.io/docs/latest/full.html#proc-accessing-kafka-using-loadbalancers-deployment-configuration-kafka

**Comment by Dec-** [comment]
Ok, but this address is not resolvable outside of the OpenShift cluster? Or im missing something :)

Thx

**Comment by scholzj** [comment]
That should give you the address of the loadbalancer which is normally outside of OpenShift. That should be accessible from outside of OpenShift
