### ISSUE TITLE
Topic Operator doesn't handle `KafkaTopic` without labels

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1360]
Currently, the Topic Operator is using a wrong/old default value for the `STRIMZI_RESOURCE_LABELS` env var if it's not set in the Deployment; it's `strimzi.io/kind=topic` while this label doesn't exist anymore after moving to CRDs.
The Topic Operator should handle ALL the `KafkaTopic` resources if no label is set.
Setting the default value is not the solution because when the `K8sTopicWatcher` class tests the `resourcePredicate` (which handles the labels), the related `test` method return just false when no labels are set on the `KafkaTopic` resource.
Having no labels should mean to handle all the `KafkaTopic` resources.

**Comment by samuel-hawker** [comment]
@stanlyDoge , did #1430 close out this issue, or is there some undesired behaviour around the labels not being present?

**Comment by scholzj** [comment]
Triaged on 2.8.2022: Fixed in #1430
