### ISSUE TITLE
ZooKeeperClientTimeoutException during KafkaServer startup

### ISSUE THREAD

**Issue by foxyriver** [strimzi/strimzi-kafka-operator#1392]
/kind bug

**What happened**:
**there is the kafka-operator operation process below**:
1、create kafka kind resource
2、the kafka-operator generate zookeeper statefulset, the zookeeper statefulset generate zookeeper pod
3、the kafka-operator generate kafka statefulset, the kafka statefulset generate kafka pod
when generating kafka pod, the kafka container exit because of ZooKeeperClientTimeoutException.

**the error logs**:
2019-03-01 07:20:25,915 INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@65fb9ffc (org.apache.zookeeper.ZooKeeper) [main]
2019-03-01 07:20:25,935 INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2019-03-01 07:20:25,940 INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient) [main]
2019-03-01 07:20:25,950 INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2019-03-01 07:20:31,944 INFO [ZooKeeperClient] Closing. (kafka.zookeeper.ZooKeeperClient) [main]
2019-03-01 07:20:31,950 WARN Client session timed out, have not heard from server in 6000ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn) [main-SendThread(localhost:2181)]
2019-03-01 07:20:32,056 INFO Session: 0x0 closed (org.apache.zookeeper.ZooKeeper) [main]
2019-03-01 07:20:32,057 INFO EventThread shut down for session: 0x0 (org.apache.zookeeper.ClientCnxn) [main-EventThread]
2019-03-01 07:20:32,064 INFO [ZooKeeperClient] Closed. (kafka.zookeeper.ZooKeeperClient) [main]
2019-03-01 07:20:32,081 ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
        at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:268)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
        at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:264)
        at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:97)
        at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1694)
        at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:348)
        at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:372)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:202)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
        at kafka.Kafka$.main(Kafka.scala:75)
        at kafka.Kafka.main(Kafka.scala)
2019-03-01 07:20:32,088 INFO shutting down (kafka.server.KafkaServer) [main]
2019-03-01 07:20:32,105 INFO shut down completed (kafka.server.KafkaServer) [main]
2019-03-01 07:20:32,106 ERROR Exiting Kafka. (kafka.server.KafkaServerStartable) [main]
2019-03-01 07:20:32,121 INFO shutting down (kafka.server.KafkaServer) [kafka-shutdown-hook]
 
**Anything else we need to know?**:
i have three kafka pod, only one kafka pod occur this error, even if i restart this pod, this error still happen. i restart the node in which the error kafka pod is, the error kafka pod recoverd( but does not work every time).

**Environment**:
kafka-operator 0.10.0-rc2

**Comment by scholzj** [comment]
The Kafka pod has two containers - the main Kafka container and a sidecar with Stunnel proxy which is responsible for encrypting and forwarding the connection to Zookeeper. It would be interesting to see what is in the log of the other container.

I see this happen fairly often during startup when the Kafka container image is pulled first and tries to start while the Stunnel container image is still being pulled and doesn't therefore run yet. But in that case that resolves it self after one or two restarts when the second container image is pulled and that container starts as well.

**Comment by foxyriver** [comment]
@scholzj 
there is the tls-sidecar container logs, hoping this helps
> 2019.03.01 08:17:47 LOG5[1:140034156660800]: stunnel 4.56 on x86_64-redhat-linux-gnu platform
2019.03.01 08:17:47 LOG5[1:140034156660800]: Compiled/running with OpenSSL 1.0.1e-fips 11 Feb 2013
2019.03.01 08:17:47 LOG5[1:140034156660800]: Threading:PTHREAD Sockets:POLL,IPv6 SSL:ENGINE,OCSP,FIPS Auth:LIBWRAP
2019.03.01 08:17:47 LOG5[1:140034156660800]: Reading configuration from file /tmp/stunnel.conf
2019.03.01 08:17:47 LOG5[1:140034156660800]: FIPS mode is enabled
2019.03.01 08:17:47 LOG4[1:140034156660800]: Insecure file permissions on /etc/tls-sidecar/kafka-brokers/my-cluster-kafka-1.key
2019.03.01 08:17:47 LOG5[1:140034156660800]: Configuration successful
2019.03.01 08:17:56 LOG5[1:140034156656384]: Service [zookeeper-2181] accepted connection from 127.0.0.1:59720
2019.03.01 08:17:56 LOG5[1:140034156656384]: connect_blocking: connected 10.254.176.107:2181
2019.03.01 08:17:56 LOG5[1:140034156656384]: Service [zookeeper-2181] connected remote server from 172.22.141.197:53040
2019.03.01 08:18:12 LOG5[1:140034156586752]: Service [zookeeper-2181] accepted connection from 127.0.0.1:59810
2019.03.01 08:18:12 LOG5[1:140034156586752]: connect_blocking: connected 10.254.176.107:2181
2019.03.01 08:18:12 LOG5[1:140034156586752]: Service [zookeeper-2181] connected remote server from 172.22.141.197:53130
2019.03.01 08:18:12 LOG4[1:140034156586752]: CERT: Verification error: certificate is not yet valid
2019.03.01 08:18:12 LOG4[1:140034156586752]: Certificate check failed: depth=1, /O=io.strimzi/CN=cluster-ca v0
2019.03.01 08:18:12 LOG3[1:140034156586752]: SSL_connect: 14090086: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
2019.03.01 08:18:12 LOG5[1:140034156586752]: Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
2019.03.01 08:18:14 LOG5[1:140034156586752]: Service [zookeeper-2181] accepted connection from 127.0.0.1:59826
2019.03.01 08:18:14 LOG5[1:140034156586752]: connect_blocking: connected 10.254.176.107:2181
2019.03.01 08:18:14 LOG5[1:140034156586752]: Service [zookeeper-2181] connected remote server from 172.22.141.197:53146
2019.03.01 08:18:41 LOG5[1:140034156517120]: Service [zookeeper-2181] accepted connection from 127.0.0.1:59966
2019.03.01 08:18:41 LOG5[1:140034156517120]: connect_blocking: connected 10.254.176.107:2181
2019.03.01 08:18:41 LOG5[1:140034156517120]: Service [zookeeper-2181] connected remote server from 172.22.141.197:53286
2019.03.01 08:19:23 LOG5[1:140034156406528]: Service [zookeeper-2181] accepted connection from 127.0.0.1:60170
2019.03.01 08:19:23 LOG5[1:140034156406528]: connect_blocking: connected 10.254.176.107:2181

**Comment by scholzj** [comment]
I see this in the log: `CERT: Verification error: certificate is not yet valid` 

Is it possible that the node where you saw this problem had a time which was out of sync with the other nodes of your cluster?

**Comment by eye0fra** [comment]
It seems an issue with certificates:

2019.03.01 08:18:12 LOG4[1:140034156586752]: Certificate check failed:
depth=1, /O=io.strimzi/CN=cluster-ca v0
2019.03.01 08:18:12 LOG3[1:140034156586752]: SSL_connect: 14090086:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify
failed
2019.03.01 08:18:12 LOG5[1:140034156586752]: Connection reset: 0 byte(s)
sent to SSL, 0 byte(s) sent to socket

*Mattia Mascia*

*mobile: +41 79 41 14 377*
*m@il: mattiam7@gmail.com <mattiam7@gmail.com>*

**Comment by foxyriver** [comment]
@scholzj @eye0fra the time difference between different nodes is 7 minutes, then i synchronize the time, the  certificate error is gone, but still has this error below

> Service [zookeeper-2181] accepted connection from 127.0.0.1:39856
2019.03.01 08:52:29 LOG5[1:140123399329536]: connect_blocking: connected 10.254.176.107:2181
2019.03.01 08:52:29 LOG5[1:140123399329536]: Service [zookeeper-2181] connected remote server from 172.22.141.198:40318
2019.03.01 08:52:29 LOG5[1:140123399329536]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2019.03.01 08:52:29 LOG5[1:140123399329536]: Certificate accepted: depth=0, /O=io.strimzi/CN=my-cluster-zookeeper
2019.03.01 08:52:29 LOG5[1:140123399329536]: SSL socket error: Connection reset by peer (104)
2019.03.01 08:52:29 LOG5[1:140123399329536]: Connection reset: 49 byte(s) sent to SSL, 0 byte(s) sent to socket
2019.03.01 08:52:30 LOG5[1:140123399329536]: Service [zookeeper-2181] accepted connection from 127.0.0.1:39872
2019.03.01 08:52:30 LOG5[1:140123399329536]: connect_blocking: connected 10.254.176.107:2181
2019.03.01 08:52:30 LOG5[1:140123399329536]: Service [zookeeper-2181] connected remote server from 172.22.141.198:40334

**Comment by scholzj** [comment]
Could it be that some other nodes have the time out of sync as well?

**Comment by foxyriver** [comment]
only two nodes of my kubernetes cluster.

**Comment by foxyriver** [comment]
@scholzj 
the zookeeper has this error, but the zookeeper pod is running.

> Line 451: 2019-03-01 09:11:23,899 WARN Exception causing close of session 0x0: ZooKeeperServer not running (org.apache.zookeeper.server.NIOServerCnxn) [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:21811]
	Line 454: 2019-03-01 09:11:27,331 WARN Exception causing close of session 0x0: ZooKeeperServer not running (org.apache.zookeeper.server.NIOServerCnxn) [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:21811]

**Comment by tombentley** [comment]
I don't think the error 

> 2019.03.01 08:52:29 LOG5[1:140123399329536]: SSL socket error: Connection reset by peer (104)

is anything to worry about. Isn't it just a side-effect of the health check?

**Comment by foxyriver** [comment]
@tombentley yes, now i don't think this error is the root reason too.

**Comment by foxyriver** [comment]
@scholzj @eye0fra @tombentley @valdar 
this issue is caused by ipvs mode hangs of kube-proxy, resulting network impassability.
https://github.com/kubernetes/kubernetes/issues/71071 
merge the following pr to test ZooKeeperClientTimeoutException issue, anything is ok now
https://github.com/kubernetes/kubernetes/pull/72426

**Comment by scholzj** [comment]
@foxyriver Thanks for the update. Does that mean that we can close this issue?

**Comment by foxyriver** [comment]
@scholzj  yes, the issue is done.

**Comment by surbhiagrawal22** [comment]
hey, i have started to use apache kafka and i am also facing same error .. can some one please help
![image](https://user-images.githubusercontent.com/60931664/86060626-678d5400-ba65-11ea-9511-122c413e6f1a.png)

**Comment by surbhiagrawal22** [comment]
I have un-installed and installed the kafka again.and using MAC PC.

**Comment by scholzj** [comment]
@surbhiagrawal22 That looks like a completely different error - why do you think it has anything to do with the error previously discussed in this issue?

In your case it looks like some storage mixup - using storage volumes used previously by some other cluster or completel data loss of the Zookeeper storage. Please share more information about your cluster (full logs as text, the KAfka custom resource, versions used, storage type used etc.) - that might tell us something more.
