### ISSUE TITLE
Support for confluent images

### ISSUE THREAD

**Issue by gkocur** [strimzi/strimzi-kafka-operator#1400]
Do you plan to create images based on confluent images?
My use case: I use kafka operator to create kafka cluster - it works great and we are very happy with it.
I also need a kafka connect cluster running debezium connector. I tried to extend provided images and to add debezium plugin to it and had a lot of strange problems (for example connector status was "running" but with 0 tasks). After hours of experiments I decided to give a chance halm chart provided by confluent (with confluent images) - everything works like a charm.
It would be great to have everything (kafka and kafka connect) managed by kafka operator.

**Comment by scholzj** [comment]
We have no plans to support Confluent images. 

I think there are several users using Debezium with our images and if you use OpenShift there is even a  guide on the [Debezium website](https://debezium.io/docs/openshift/). So I'm quite sure that Debezium works with our images. Maybe if you share more details about how you created the image and what problems you had we can help you to get it working.

**Comment by gkocur** [comment]
Thank you for your answer. 
I run this on kubernetes, so I create custom image based on strimzi image by adding directory containing debezium plugin (downloaded from maven) to /opt/kafka/plugins (exactly as in documentation).
The plugin is found and I can see it when I call /connector-plugins endpoint.
After adding the connector it returns 200, but there is 0 running tasks. Moreover - calling /connectors/connector-name/status returns 404.
To complicate things  - sometimes it works correctly, I didn't found why.

It's strange,  while - as you mentioned - the debezium documentation describes adding debezium to strimzi images.

Anyway - I'll close this issue since I don't think it's a problem with strimzi images but rather with debezium itself. I'll try debug this deeper and maybe open issue on debezium.

BTW - you are doing great job guys with this software!
