### ISSUE TITLE
Support volume for pod running logs

### ISSUE THREAD

**Issue by tanshanshan** [strimzi/strimzi-kafka-operator#1401]
We want to use volume for mounting  the container running log contents to the host, 
Can it support it  ?
currently we just use 

> kubectl logs podname containername

 to get them.

Thanks

**Comment by scholzj** [comment]
This is currently not possible and it is not planned right now. 

AFAIK the usual workflow is that the logs are written to the STDOUT of the container where they are collected and written to a file by the container engine (Docker) on the host. There they can be collected and sent somewhere to ElasticSearch etc.. So normally it is not needed to create any special volumes for writing logs to files.

**Comment by scholzj** [comment]
Triaged on 22.02.2022: Might be useful in some edge-cases.
