### ISSUE TITLE
Connection to kube leaked

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1409]
I have observed messages like this in the CO logs:

Mar 02, 2019 11:57:09 AM okhttp3.internal.platform.Platform log
WARNING: A connection to https://kubernetes.default.svc/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by scholzj** [comment]
AFAIK this will be Fabric8 bug.

**Comment by tombentley** [comment]
There was the Workaround RBAC stuff, but that's now been removed in 0.11.x, so I agree it looks like a Fabric8 problem. It could be https://github.com/fabric8io/kubernetes-client/issues/1013, for example.

**Comment by scholzj** [comment]
We couls also try to bump the version ... it seems 4.1.3 is out.

**Comment by stanlyDoge** [comment]
Bumped fabric8 to 4.1.3 in https://github.com/strimzi/strimzi-kafka-operator/pull/1424

**Comment by scholzj** [comment]
I do not think this is happening anymore. So we can probably close the issue?
