### ISSUE TITLE
Question: why do we need the ClusterIP service for client?

### ISSUE THREAD

**Issue by jeroenr** [strimzi/strimzi-kafka-operator#1419]
I'm confused on why we need this additional ClusterIP service for clients to connect to. They can just use the headless service, right?

Please enlighten me :)

**Comment by scholzj** [comment]
IIRC, the difference is in the way they resolve in DNS. The headless service resolves into the pod IP addresses. But the pod IP addresses might change during restarts. So for example after a rolling update, your client might need to re-resolve the DNS and that doesn't always work well. The ClusterIP on the other hand resolves to a single IP which is stable and routes the connections from there. So it doesn't have these problems. Hope this helps to explain it.

**Comment by jeroenr** [comment]
Makes sense, although the single cluster IP service will round robin return a random broker and clients at some point will need to know the address of the specific broker they need to contact, right? Also, recently [a bug related to resolving DNS in kafka client](https://issues.apache.org/jira/browse/KAFKA-7755) was fixed, so that would rule out the need for the ClusterIP service I guess? Or is there any other reason to keep it?

**Comment by scholzj** [comment]
Well, KAFKA-7755 was one bug in one of the many clients. So I do not think this justifies the removal of the ClusterIP service. DNS has simply its limitations with regards to how changes are propagated. Regardless of whether you use the ClusterIP or the Headless service, you always connect to a _random_ broker (Randomising the endpoints to which the DNS record resolves is AFAIK one of the common strategies). 

But Kafka doesn't care about it really - it will always open the first connection only to get the metadata and open a subsequent connections to the specific brokers it needs to connect to based on the advertised addresses from the metadata.

**Comment by jeroenr** [comment]
AFAIK the headless service would return a list of brokers and it's up to the client how to deal with that. With the ClusterIP you would indeed get a random broker. So if it's about randomnising endpoints I understand the use of the ClusterIP

**Comment by scholzj** [comment]
TBH, for me the randomising aspect is not important. I was just pointing out that it might be done when using both services. For me the main point is really that the DNS record is stable and doesn't need to be refreshed.
