### ISSUE TITLE
Define a policy for which Kafka versions to ship in Strimzi releases

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1426]
We should have a policy about which Kafka versions are included in the images for each Strimzi release. Users of Strimzi would probably like an upgrade story where:

1. They can upgrade Strimzi without having to upgrade their Kafka cluster version.
2. They can easily upgrade to the latest version of Strimzi from a non-previous version (i.e. If they're on version N and haven't upgraded to N+1 by the time we're released N+2, they can easily just upgrade N→N+2).

While that might be ideal for users we have to be realistic about what the Strimzi project can support. Kafka evolves pretty quickly, and supporting older versions for a long time means the operators can't take advantage of new features, or have to explicitly model the capabilities of different Kafka versions, complicating the operators. Supporting more Kafka versions also makes the builds slower.

I propose that at the time of a Strimzi release we aim to support the last two Kafka minor versions only (i.e. 2.x.y and 2.(x-1).z). This might not be ideal, but it is simple to understand and does limit the number of versions a particular version of Strimzi supports. It means Strimzi users don't have to use a bleeding edge Kafka. Since Strimzi is releasing more frequently than Kafka there should always be an upgrade path.

Thoughts?

**Comment by scholzj** [comment]
The initial policy is now described in `https://github.com/strimzi/strimzi-kafka-operator/blob/master/KAFKA_VERSION_SUPPORT.md`
