### ISSUE TITLE
Mount volume for connector plugins

### ISSUE THREAD

**Issue by mikecowgill** [strimzi/strimzi-kafka-operator#1439]
Currently, we are required to bake a new docker image for kafka connect that includes additional connector plugins in the image. It seems early versions of Strimzi allowed for mounting a volume, which could contain the connectors. Is this something that is no longer possible?

I see the ability to mount secrets and configmaps but are there plans to add persistent volumes? It seems it would be straightforward to enable.

**Comment by scholzj** [comment]
We experimented with is a bit some long time ago. But at the end we decided to not adopt it. The main reason was that in general the containers should be usually immutable and loading the plugins on the fly from a config map or a volume goes a bit against this principle. There are also some technical issues:
* Config maps have (or at least head) significant size limitations
* Volumes are hard to handle (you would need another container / way to actually copy the plugins to the volume)

On OpenShift, we support the Source 2 Image mechanism to easily add the plugins to a new image. Unfortunately, Kubernetes currently don't have anything equivalent. But it is usually quite easy to just build the new image in some CI and push it to Docker Hub for example.

**Comment by mikecowgill** [comment]
Understood about immutable containers. In general I agree that's the way to go. As you mention, s2i could be interesting but we are on kubernetes. 
In my use case though, keeping various connectors up-to-date and also trying to keep the image size down is cumbersome.
Also, I'm using NFS volumes which makes it a bit easier to prep the plugin folder.

Just a thought, but what about just adding the ability to mount persistent volumes, in general. Don't even really need to document that it could be used for connectors.

Using the strimzi operator is great (!) but sometimes it can be limiting if it removes natively accessible features of kubernetes.

**Comment by scholzj** [comment]
Well, we can keep this open for that as an enhancement request. But honestly I don't think we will get to it anytime soon.

**Comment by joshdreagan** [comment]
I'd second that this would be a useful feature. Not necessarily for mounting a lib directory, but just in general the ability to mount a PV to the Kafka Connect container. I have a customer that would like to move their Kafka cluster into OpenShift, but they currently use the Spool Dir Connector to poll for files in a local directory. So we really can't replicate that functionality unless we do something clunky like standing up an FTP server or something. Would be nice to be able to just mount a PV and continue with the app written as-is.

**Comment by scholzj** [comment]
Connectors can be now added automatically by specifying them in the KafkaConnect CR. We do not plan to allow mounting connectors from volumes. Using volumes for possible reading / writing data to/from them is covered in #3693.
