### ISSUE TITLE
Helm Chart doesn't work with all namespaces

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1454]
From Slack:
_Hello, I am using helm charts to install  the strimzi operator, in my values.yaml I am setting the watchNamespaces to "*" to watch all namespaces.. but I am getting this error during helm install
Error: YAML parse error on strimzi-kafka-operator/templates/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml: error converting YAML to JSON: yaml: line 4: did not find expected alphabetic or numeric character_

Additionally, the Cluster Role Bindings will not be installed properly for watching all namespaces.

**Comment by spencergilbert** [comment]
Any chance this is going get attention soon?

**Comment by scholzj** [comment]
This should be fixed now in #1912
