### ISSUE TITLE
Remove images(UO, TO) constants from the models

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-operator#1469]
The issue was raised because of having problems in ST during the calling method `AbstractST.replaceKafkaResource(String resourceName, Consumer<Kafka> editor)`. When ST calls this method, the method also updates UO and TO image values in Kafka cluster configuration. This is most likely to occur because of getting Kafka object in line https://github.com/strimzi/strimzi-kafka-operator/blob/429e7eb83b8d92435469a18e8793422db6d684e0/systemtest/src/main/java/io/strimzi/systemtest/AbstractST.java#L207 where we use models which have constants `DEFAULT_IMAGE` in models `EntityTopicOperatorSpec`, `EntityUserOperatorSpec` and because

**Comment by scholzj** [comment]
Thsi should have been fixed with #2004
