### ISSUE TITLE
single node is running the rest kafka broker nodes are in CrashLoopBackOff

### ISSUE THREAD

**Issue by ludurr** [strimzi/strimzi-kafka-operator#1471]
Hi,

 i have kafka cluster with 3 nodes, 1st running no issue, but the other ones failing in  CrashLoopBackOff. 

logs from kafka broker node :

Starting Stunnel with configuration:
pid = /usr/local/var/run/stunnel.pid
foreground = yes
debug = notice
[zookeeper-2181]
client = yes
CAfile = /tmp/cluster-ca.crt
cert = /etc/tls-sidecar/kafka-brokers/*****-kafka-kafka-1.crt
key = /etc/tls-sidecar/kafka-brokers/*****-kafka-kafka-1.key
accept = 127.0.0.1:2181
connect = hs360-kafka-zookeeper-client:2181
delay = yes
verify = 2

2019.03.25 14:25:18 LOG5[1:139750506162240]: stunnel 4.56 on x86_64-redhat-linux-gnu platform
2019.03.25 14:25:18 LOG5[1:139750506162240]: Compiled/running with OpenSSL 1.0.1e-fips 11 Feb 2013
2019.03.25 14:25:18 LOG5[1:139750506162240]: Threading:PTHREAD Sockets:POLL,IPv6 SSL:ENGINE,OCSP,FIPS Auth:LIBWRAP
2019.03.25 14:25:18 LOG5[1:139750506162240]: Reading configuration from file /tmp/stunnel.conf
2019.03.25 14:25:18 LOG5[1:139750506162240]: FIPS mode is enabled
2019.03.25 14:25:18 LOG4[1:139750506162240]: Insecure file permissions on /etc/tls-sidecar/kafka-brokers/*****-kafka-kafka-1.key
2019.03.25 14:25:18 LOG5[1:139750506162240]: Configuration successful

**Comment by ppatierno** [comment]
can you provide the YAML file describing the `Kafka` resource you are using for deploying the cluster please?

**Comment by ludurr** [comment]
Hi, 

thanks for a reply. Actually all threee node within cluster were running until i decided to add metrics{} for prometheus. I used kubectl apply -f > it has updated zookeeper node without any issue, but first kafka node and it has start failing.

Thank you for looking.  

here my kafka-persistant manifest yaml:

apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: ****-kafka
spec:
  kafka:
    version: 2.1.0
    replicas: 3
    #plain kafka brokers listen on port 9092
    listeners:
      plain: {}  
    #metrics: {}
      #authentication property is missing, no authentication will be enabled listeners 
      #authorization property is missing, no authorization will be enabled listeners 
      #networkpolicy peers select PODs which can be listeners/brokers
      # v pripade restrikce pristup jenom urcitych app k listeners     
      #   networkPolicyPeers:
      #       - podSelector:
      #           matchLabels:
      #             app: kafka-client

#      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.1"
    logging:
      type: inline
      loggers:
        logger.name: "INFO"
    storage:
      type: persistent-claim
      class: managed-premium

      size: 2Gi

      deleteClaim: true

    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 2500m
        memory: 4Gi
  zookeeper:
    replicas: 3
    #metrics: {}
    storage:

      type: persistent-claim
      class: managed-premium

      size: 2Gi
      deleteClaim: true
  entityOperator:

    topicOperator: 
      watchedNamespace: test
      reconciliationIntervalSeconds: 60
    userOperator: 
      watchedNamespace: test
      reconciliationIntervalSeconds: 60

**Comment by scholzj** [comment]
Which of the containers in the Kafka pod is looping? The Kafka one or the TLS sidecar? I think you will need to provide a complete log from the one which is looping. Based on the YAML - are you sure you have enough disk space?

**Comment by ludurr** [comment]
Hello,
its a tls-sidecar and complete log for crashing tls sidecar is above. 

What would you suggest in regards to disk space ?

Thank you.

**Comment by scholzj** [comment]
Ok. So it doesn't look like disk space. The log from the TLS sidecar looks OK. If it is crashing, you might need to increase the log level to get us more information (see the [docs how to do it](https://strimzi.io/docs/latest/full.html#ref-tls-sidecar-deployment-configuration-kafka))

**Comment by ludurr** [comment]
I have decided to remove whole cluster operator configuration out of kubernetes and redeploy it from scratch, but when i apply cluster operator CRD, rolebidnings, clusterrole etc...and try to create statefulset with zookeeper and kafka nothing happen.
And i noticed that some resource definitations from old deployment are still there.

kubectl get kafka
kafkaconnects.kafka.strimzi.io      kafkamirrormakers.kafka.strimzi.io  kafkas.kafka.strimzi.io             kafkatopics.kafka.strimzi.io        kafkausers.kafka.strimzi.io 

thanks

**Comment by ludurr** [comment]
Thanks for your time and help, but due to time pressure i decided to redeploy the cluster operator.
