### ISSUE TITLE
Support non-k8s resource naming for KafkaUser

### ISSUE THREAD

**Issue by royantman** [strimzi/strimzi-kafka-operator#1475]
Hi.

Since we use Istio in our deployment, we require that KafkaUser(s) will support naming that
does not honor k8s resource naming limitations.

For example, Istio give services a SPIFEE identity:
```
spiffe://cluster.local/ns/default/sa/curly
```
And generates an x509 cert with the subject `CN=spiffe://cluster.local/ns/default/sa/curly`
thus we need that to match the ACL rule being created.

If you could provide support for better controlling the naming as you did with `KafkaTopicSpec (topicName)`, that would solve our problems.

Cheers.

**Comment by scholzj** [comment]
I do not think we have currently any solution for this. We have tried to workaround the limitations for topics and I think it results in a really bad user experience and very complicated and error prone implementation.

Can you share a bit more about your use case between Strimzi and Istio? Is your plan to use the Istio keys and the Clients CA so that you can use the Istio service certificates for authentication and all you need is to manage the authorization through the KafkaUser resources?

**Comment by commanderdishwasher** [comment]
Correctomondo!

**Comment by scholzj** [comment]
Hmm, that is interesting use case. I wanted to have a better look at possible integration with Istio for the security stuff, but didn't got to it so far :-(. 

I would like to keep this open and make this more easier in the future. But to be honest with you, I do not think we will get to this anytime soon. So I'm afraid your safest bet would be to just disable the user operator and manage the authorization rules your self using the Kafka Admin API.

**Comment by commanderdishwasher** [comment]
Exactly our "Plan B".
We will use Strimzi user operator or superUser field (string ;) ) to grant privs to our user operator and manage it from there on.

**Comment by footplus** [comment]
Another use-case is managing simple ACLs when using OAuth2 authentication only.

**Comment by scholzj** [comment]
Triaged on 22.02.2022: Decoupling the resource name from the topic name is cause of a lot of issues and non-deterministic behaviors in the Topic Operator. We do not want to repeat this in the User operator. Any users who want to use different user names can disable the User Operator and manage the users directly on their own without any issues, so there is a workaround available.
