### ISSUE TITLE
Idea: create a golang-based CLI for easy installation and configuration steps

### ISSUE THREAD

**Issue by dmvolod** [strimzi/strimzi-kafka-operator#1520]
Hi Devs!
What do you think about to create a CLI written on golang for easy installation and configuration of different entities. For example, Camel K project (https://github.com/apache/camel-k) allows to do all steps with kamel CLI, like install, deinstall, run,  etc.

**Comment by scholzj** [comment]
I think this is a good idea and it is on my private TODO list already for some time. But I never had time to look into it. It would be great if someone could look into it and contribute it ;-).

The main question would be whether it still makes sense to write it as standalone tool or rather as kubectl plugin. AFAIK the plugin support in kubectl evolved a bit lately and might be usable for this.

**Comment by dmvolod** [comment]
Thanks for feedback, @scholzj 
It would be nice to have both standalone tool and kubectl plugin as well with similar core code. But could be start with standalone tool as it much simple and flexible to implement. I can try to start take care about this, but would you recommend to use separate repo for it or just folder inside this one. Look like it's better to have a separate one with name like strimzi-tools (both for standalone and kubectl plugin) or anything else.

**Comment by dmvolod** [comment]
Some research: if component will be in separate repo, the strimzi-kafka-operator/install/ folder need to be move there, otherwise need to be place tools folder inside this repo.

**Comment by scholzj** [comment]
I think separate repo would be better because it will use completely different language. I wonder if something like submodule or subtree might be better solution. I also think the tool should probably primarily target the released YAMLs and not the master YAMLs. You maybe it can just get them from the release page at build time or something similar.

**Comment by mabulgu** [comment]
Hey @dmvolod Must have missed this, and seems that its been a while:). I think I need to improve my repo search skills(: At the time of this conversation I assume been working on this: 

https://github.com/systemcraftsman/strimzi-kafka-cli 

Just putting here for the sake of the archive and maybe some feedback about it.

P.S. Its not golang based, its python based.

Cheers, Aykut

**Comment by scholzj** [comment]
Triaged on 7.6.2022: It looks like there is no time to work on this and not that much interest in the `strimzictl` command like tool. This should be closed and we can get back to it later if the interest grows and if someone has time to work on it.
