### ISSUE TITLE
Set less restrictive file permissions for Kafka image

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#1529]
More specifically, I think we should set aside a directory where the group user has write permissions. This would be helpful for users testing the builtin FileSink and FileSource Connectors, allowing them to run an example using either/both connector(s) within the same pod

**Comment by scholzj** [comment]
You can use `/tmp/`. I'm not sure we really need another directory given the `FileSink` and `FileSource` plugins are pretty much only to just try it out.

**Comment by kyguy** [comment]
Ah you are right, I didn't realize `/tmp/`was writeable but since it is I agree we don't need another directory. Closing issue!
