### ISSUE TITLE
Scaling the topic controller

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#153]
The topic controller uses zookeeper watches to know when config, replication factor and number of partitions changes. We need to understand how well this scales in zookeeper when there are many topics and/or partitions. If we find a practical limit which is less than a reasonable number of topics we need to investigate mitigations.

**Comment by scholzj** [comment]
Reviewed on 10th September 2020: Zookeeper will be removed and nobody so far complained about TO scalability. This should be closed. It might be later replaced by another more generic TO scalability issue.
