### ISSUE TITLE
Configure Ports for Kafka Bootstrap and Broker services

### ISSUE THREAD

**Issue by j-chao** [strimzi/strimzi-kafka-operator#1536]
Hi, 

Is there support for being able to change and configure the ports on which the kafka external bootstrap and brokers services are being exposed on? 

For example, I have a strimzi kafka cluster running in kubernetes, but would like to be able to change the loadbalancer port from the default 9094 to 80 or 443. 

Thank you!

**Comment by scholzj** [comment]
We do not support it currently. What would be the reason to expose it on ports 80 or 443 when its anyway not HTTP / HTTPS?

**Comment by j-chao** [comment]
I have a firewall that blocks all other ports that I'm trying to navigate unfortunately.

**Comment by scholzj** [comment]
And will it pass through your firewall on this port? Or is it doing some additional checks to ensure that the traffic is in fact HTTP / HTTPS?

In general, I think this should be feasible to implement.

**Comment by aymenfurter** [comment]
Hi,

We are facing the same issue and would appreciate any input how to workaround this limitation! :)

Cheers
Aymen

**Comment by scholzj** [comment]
Small update: From 0.20 we allow to use more different ports, but only from 9092 up. We do not support 443 or 80.

**Comment by xsreality** [comment]
Came across the same issue. At a client premises, all ports other than 443 are blocked. The workaround would be:
1. Use an ingress to use port 443 and avoid firewall (not ideal as clients are outside K8S cluster) or
2. Open the firewall

Is there any other option?

**Comment by scholzj** [comment]
I'm not aware of any other option.

**Comment by kfox1111** [comment]
Not sure if this should be on this ticket or another, but we'd like to actually go the other direction. we're using ingress, but would like the ingress's port to be 9093 but its hardcoded to assume 443 even though the ingress controllers port is configurable to be on 9093. Should I file another issue, or should we track it here?
