### ISSUE TITLE
Consistent colours for pods in Grafana

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1546]
**Describe the bug**

The provided grafana dashboards don't use a consistent colour across the charts for the same zookeeper node or kafka broker. This can make reading and correlating the charts more difficult than it needs to be. See https://github.com/grafana/grafana/issues/6662

**To Reproduce**
1. Just look at the default grafana dashboard provided for a ZK cluster with ≥ 2 nodes.

**Expected behavior**

You'll see zookeeper-_n_ has different colours in the different timeseries charts. So cyan might be zookeeper-0 in one chart but zookeeper-2 on another.

**Comment by scholzj** [comment]
Triaged on 2.8.2022: This is still an issue in the current dashboards.
