### ISSUE TITLE
Zookeeper latency metrics lack unit

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1548]
**Describe the bug**

The provided grafana dashboards include metrics (min, mean and max) about request latency, but the unit is unclear. It's described as "The amount of time...".

**To Reproduce**
1. Just look at the ZK Request Latency timeseries in the default grafana dashboards.

**Expected behavior**

The description (at least) and the _y_ axis of the charts (ideally) should include the unit (ms).

**Comment by ShubhamRwt** [comment]
Hello @tombentley. I was working on this task. Should I keep the label as null or change it to ms. I have changed the format to ms for getting the time in ms.

**Comment by tombentley** [comment]
I think both ideally.
