### ISSUE TITLE
Add support for "match expressions" selector when using Persistent volumes

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#156]
The current "persistent" storage configuration using PVCs supported by the cluster controller allows to specify a selector with only "match labels". We should add the support for "match expressions" as well.

**Comment by samuel-hawker** [comment]
Can I pick up this issue?

**Comment by ppatierno** [comment]
@samuel-hawker why not? :-)

**Comment by scholzj** [comment]
@samuel-hawker Are you still planning to look at this?

**Comment by samuel-hawker** [comment]
I had got started on this but never finished it, I **may** get around to finishing it in the next few weeks but I am more than open to someone else picking this up. They are also more than free to use the above referenced commits.

**Comment by scholzj** [comment]
Reviewed on 10th September 2020: Should remain open.

**Comment by echernous** [comment]
The support for match expressions is not required at this moment, replacing selector's class from Map to LabelSelector will introduce backwards incompatibility:
https://github.com/strimzi/strimzi-kafka-operator/pull/4839
