### ISSUE TITLE
[Doc] Examples YAML snippets use wrong resource

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1561]
**Suggestion / Problem**

The example snippets for Kafka Connect, Kafka Connect S2I and Kafka Mirror Maker logging configs use `Kafka` resources, not `KafkaMirrorMaker` resources. This is confusing.

**Documentation Link**

https://strimzi.io/docs/master/#assembly-logging-deployment-configuration-kafka-mirror-maker

**Comment by tombentley** [comment]
One way of handling this would be to have the example in a different snippet file for each resource kind (i.e. `snip-external-logging-Kafka.adoc`, `snip-external-logging-KafkaConnect.adoc`, `snip-external-logging-KafkaMirrorMaker.adoc` etc) and include it in the procedure like this:

```asciidoc
include::snip-external-logging-{kind}.adoc[]
```

And define the attribute `:kind: KafkaMirrorMaker` in the assembly for KMM, `:kind: KafkaConnect` in the assembly for KC etc.

**Comment by PaulRMellor** [comment]
Snippets have been created to reflect the variations in the logging spec. An attribute is used in an include to bring the correct snippet into the procedure that describes inline logging.

**Comment by scholzj** [comment]
Is this still relevant? The linked section does not seem to exist anymore.

**Comment by PaulRMellor** [comment]
Each `spec` reference has a logging description and example for the component.

[Kafka](https://strimzi.io/docs/operators/in-development/using.html#property-kafka-logging-reference)
[ZooKeeper](https://strimzi.io/docs/operators/in-development/using.html#property-zookeeper-logging-reference)
[Topic Operator](https://strimzi.io/docs/operators/in-development/using.html#property-topic-operator-logging-reference)
[User Operator](https://strimzi.io/docs/operators/in-development/using.html#property-user-operator-logging-reference)
[Kafka Connect ](https://strimzi.io/docs/operators/in-development/using.html#property-kafka-connect-logging-reference)
[MirrorMaker](https://strimzi.io/docs/operators/in-development/using.html#property-mm-loggers-reference)
[Kafka Bridge](https://strimzi.io/docs/operators/in-development/using.html#property-kafka-bridge-logging-reference)
[Cruise Control](https://strimzi.io/docs/operators/in-development/using.html#ref-cruise-control-configuration-str)
