### ISSUE TITLE
[Question] Procedure to migrate a kafka/zookeeper deployment to another set of nodes?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [strimzi/strimzi-kafka-operator#1586]
Due to kubernetes version upgrades on services like GKE, often we need to upgrade the underlying nodes that the kafka/zookeeper is running. Is there a recommended procedure to perform this kind of task?

The main idea is to just spin up a new set of nodes with the upgraded version, and migrate the kafka and zookepper pods to this new set of nodes and then destroy the old nodes. But, how exactly it should be done using the operator?

My main concern is this: after I drain a old node and the operator reschedule the pod to a new node, how can I be absolutely sure that it is safe to drain a second node from the cluster?

Thank you very much

**Comment by scholzj** [comment]
I have so far never though about this. Maybe you can use node affinity? Changing the node affinity will probably trigger rolling update which will stop the old pods and move them according to the new roles. So if you used some labels to distinguish the old and new nodes, it might work.
