### ISSUE TITLE
Clarification about Topic Oprators dockerfile

### ISSUE THREAD

**Issue by FridMehdi** [strimzi/strimzi-kafka-operator#1604]
Hello @tombentley i have a question, please I could not find DockerFiles For TopicOperator how it's managed ? All what I could do is docker pull strimzi/topic-operator, but is like using topic operator like a black box could i have some info if it possible i will be gratiful

**Comment by tombentley** [comment]
We used to have separate images, both for the various Kafka components (Kafka, Kafka connect, etc) and also for the operators. But we recently changed this, so we now have a single image for all the Kafka components and a single image for all the operators. This was done in https://github.com/strimzi/strimzi-kafka-operator/pull/1431. You can find the `Dockerfile` for this at `docker-images/operator/Dockerfile`. The `bin/topic_operator_run.sh` can be used to start the Topic Operator.
