### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by panichella** [strimzi/strimzi-kafka-operator#1618]
**Describe the bug**

Following the guideline at the link https://strimzi.io/docs/master/#assembly-getting-started-topic-operator-str i have tried to follow the various steps to make it working strimzi.

However, when deploying the topic operator I run "$ kubectl describe deployment strimzi-topic-operator" I get:

Name:               strimzi-topic-operator
Namespace:          myproject
CreationTimestamp:  Mon, 13 May 2019 12:15:52 +0200
Labels:             app=strimzi
Annotations:        deployment.kubernetes.io/revision: 1
                    kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"strimzi"},"name":"strimzi-topic-opera...
Selector:           name=strimzi-topic-operator
Replicas:           1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:           name=strimzi-topic-operator
  Service Account:  strimzi-topic-operator
  Containers:
   strimzi-topic-operator:
    Image:      strimzi/topic-operator:0.11.3
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     100m
      memory:  96Mi
    Requests:
      cpu:      100m
      memory:   96Mi
    Liveness:   http-get http://:8080/healthy delay=10s timeout=1s period=30s #success=1 #failure=3
    Readiness:  http-get http://:8080/ready delay=10s timeout=1s period=30s #success=1 #failure=3
    Environment:
      STRIMZI_RESOURCE_LABELS:                  strimzi.io/cluster=my-cluster
      STRIMZI_KAFKA_BOOTSTRAP_SERVERS:          my-cluster-kafka-bootstrap:9092, my-cluster-kafka-bootstrap:9093
      STRIMZI_ZOOKEEPER_CONNECT:                my-cluster-zookeeper-client:2181, my-cluster-zookeeper-0:2181, my-cluster-zookeeper-1:2181, my-cluster-zookeeper-2:2181
      STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS:     20000
      STRIMZI_FULL_RECONCILIATION_INTERVAL_MS:  900000
      STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS:      6
      STRIMZI_LOG_LEVEL:                        INFO
      STRIMZI_TLS_ENABLED:                      false
      STRIMZI_NAMESPACE:                        *
    Mounts:                                     <none>
  Volumes:                                      <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   strimzi-topic-operator-7f48d956cd (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  12m   deployment-controller  Scaled up replica set strimzi-topic-operator-7f48d956cd to 1

When I run "$ kubectl get pods" i get:
NAME                                          READY   STATUS              RESTARTS   AGE
my-cluster-entity-operator-6479f5b8f5-x7kgq   2/3     Running             0          2h
my-cluster-kafka-0                            1/2     Running             0          2h
my-cluster-kafka-1                            1/2     Running             0          2h
my-cluster-kafka-2                            1/2     Running             0          2h
my-cluster-zookeeper-0                        0/2     Running             0          2h
my-cluster-zookeeper-1                        0/2     Running             0          2h
my-cluster-zookeeper-2                        0/2     Running             0          2h
my-connect-cluster-connect-67d5df744c-dlsq2   1/1     Running             0          2h
strimzi-cluster-operator-97bcc7869-tkkqf      1/1     Running             0          3h
strimzi-topic-operator-7f48d956cd-lnwnv       0/1     ContainerCreating   0          11m

I also noticed that after trying to deploy the operator all the zookeeper pods changed the READ and STATUS:

$ kubectl get pods
NAME                                          READY   STATUS              RESTARTS   AGE
my-cluster-entity-operator-6479f5b8f5-x7kgq   2/3     Running             0          2h
my-cluster-kafka-0                            1/2     Running             0          2h
my-cluster-kafka-1                            1/2     Running             0          2h
my-cluster-kafka-2                            1/2     Running             0          2h
my-cluster-zookeeper-0                        0/2     Running             0          2h
my-cluster-zookeeper-1                        0/2     Running             0          2h
my-cluster-zookeeper-2                        0/2     Running             0          2h
my-connect-cluster-connect-67d5df744c-dlsq2   1/1     Running             0          2h
strimzi-cluster-operator-97bcc7869-tkkqf      1/1     Running             0          3h
strimzi-topic-operator-7f48d956cd-lnwnv       0/1     ContainerCreating   0          12m
[strimzi-0.11.3-tutorial.zip](https://github.com/strimzi/strimzi-kafka-operator/files/3172550/strimzi-0.11.3-tutorial.zip)

**To Reproduce**
I'm using minishift.
Here the zip with all my configurations:
[strimzi-0.11.3-tutorial.zip](https://github.com/strimzi/strimzi-kafka-operator/files/3172552/strimzi-0.11.3-tutorial.zip)

Specifically, I followed the guideline till the section 2.4.2., all seems to work fine executing the following commands:
$ sed -i '' 's/namespace: .*/namespace: myproject/' install/cluster-operator/*RoleBinding*.yaml
$ kubectl apply -f install/cluster-operator -n myproject

The executed all commands indicated in section "2.2.5. Deploying the Cluster Operator to watch all namespaces"

Then runned 
$ kubectl apply -f examples/kafka/kafka-persistent.yaml
$ kubectl apply -f examples/kafka-connect/kafka-connect.yaml

Then, when I have tried to "Deploying Kafka Mirror Maker to Kubernetes" and " Deploying the standalone Topic Operator" (following the recommendations here https://strimzi.io/docs/master/#deploying-the-topic-operator-standalone-deploying) i go the following errors:

$  kubectl apply -f examples/kafka-mirror-maker/kafka-mirror-maker.yaml
$ kubectl apply -f install/topic-operator

Attached the zip with the Yaml configurations adopted.

**Expected behavior**

$ kubectl get pods
NAME                                          READY   STATUS        RESTARTS   AGE
my-cluster-entity-operator-6479f5b8f5-x7kgq   3/3     Running       0          3h
my-cluster-kafka-0                            2/2     Running       0          3h
my-cluster-kafka-1                            2/2     Running       0          3h
my-cluster-kafka-2                            2/2     Running       0          3h
my-cluster-zookeeper-0                        2/2     Running       0          3h
my-cluster-zookeeper-1                        2/2     Running       0          3h
my-cluster-zookeeper-2                        2/2     Running       0          3h
my-connect-cluster-connect-67d5df744c-dlsq2   0/1     Running       0          2h
strimzi-cluster-operator-97bcc7869-tkkqf      1/1     Running       0          3h
strimzi-topic-operator-7f48d956cd-lnwnv       1/1     Terminating   0          58m

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.11.1]

strimzi-0.11.3

 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io]

YAML files

 - Kubernetes cluster: [e.g. Kubernetes 1.14, OpenShift 3.9]

$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-05-02T11:52:09Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

$ oc version
oc v3.10.0+dd10d17
kubernetes v1.10.0+b81c8f8
features: Basic-Auth

Server https://192.168.64.5:8443
kubernetes v1.11.0+d4cacc0

 - Infrastructure: [e.g. Amazon EKS, Minikube]

**Custom Resource YAMLs**
[strimzi-0.11.3-tutorial.zip](https://github.com/strimzi/strimzi-kafka-operator/files/3172552/strimzi-0.11.3-tutorial.zip)

**Logs**
Attach or copy and paste the relevant logs.

**Additional context**

**Comment by scholzj** [comment]
@panichella I'm not sure entirely understand the issue you have. If you want to use the Strimzi Topic Operator with a Strimzi Kafka cluster, you should follow this: https://strimzi.io/docs/latest/full.html#deploying-the-topic-operator-using-the-cluster-operator-str

I.e. you should have something like this in your YAML used to deploy the Kafka cluster:
```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  #...
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

If you are trying to deploy the Strimzi Topic Operator with Kafka cluster not deployed by Strimzi, you can use the standalone deployment: https://strimzi.io/docs/latest/full.html#deploying-the-topic-operator-standalone-deploying

But you should not do both.

**Comment by scholzj** [comment]
Anything else we can do to help you with this? Or should we close this issue?
