### ISSUE TITLE
Topic-controller should work with chrooted zookeeper

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#162]
The topic controller should be able to work with kafka whose connection to zookeeper has a chroot.

**Comment by scholzj** [comment]
I think this is addressed by #2599 which makes the path used by the TO configurable. Or @tombentley

**Comment by tombentley** [comment]
Yes, I think so.

**Comment by tombentley** [comment]
Oops PR not yet merged.

**Comment by scholzj** [comment]
PR is waiting for your review ;-)
