### ISSUE TITLE
[Bug] Security Scanner has detected 3 vulnerabilities in kafka-base image

### ISSUE THREAD

**Issue by zzhu2** [strimzi/strimzi-kafka-operator#1623]
**Describe the bug**
There are 3 SEVERITY vulnerabilities found in the kafka-base image

| package | current version  | fix | CVE  |   |
|---|---|---|---|---|
| python  | 2.7.5-76.el7  | 0:2.7.5-77.el7_6  | https://access.redhat.com/errata/RHSA-2019:0710  |   |
| libssh2  |  1.4.3-12.el7 |  0:1.4.3-12.el7_6.2 | https://access.redhat.com/errata/RHSA-2019:0679  |   |
| python-libs  | 2.7.5-76.el7  | 0:2.7.5-77.el7_6  | https://access.redhat.com/errata/RHSA-2019:0710  |   |

It can be fixed by adding `RUN yum update -y python libssh2` to the Dockerfile

**To Reproduce**
N/A

**Expected behavior**
N/A

**Environment (please complete the following information):**
 - Strimzi version: [0.11.3]

**Custom Resource YAMLs**
N/A

**Logs**
N/A

**Additional context**
N/A

**Comment by scholzj** [comment]
I have rebuild the images for 0.11.3. Could you please check that everything is OK now?

**Comment by zzhu2** [comment]
verified. close the bug.
