### ISSUE TITLE
[Question] Strimzi and Kubernetes Client API

### ISSUE THREAD

**Issue by AldusLorde** [strimzi/strimzi-kafka-operator#1642]
Hi, is it possible to use Strimzi with Skuber? I want to define custom objects based on Strimzi resources.

**Comment by ppatierno** [comment]
I didn't know about Skuber. So it seems to be a Kubernetes client library written in Scala.
If you are thinking about creating Strimzi custom resources (Kafka, KafkaConnect and so on) from your Scala application (using Skuber) it's feasible if it provides a way to create custom resources.
I think that thanks to "compatibility" between Java and Scala you could also use the Strimzi API Maven package (https://mvnrepository.com/artifact/io.strimzi/api) which provides model classes for the custom resources.

**Comment by AldusLorde** [comment]
Thank you. I'll try it

**Comment by scholzj** [comment]
There should be some JavaDoc inside the code. But I do not think there is any dedicated documentation for it. It is used in our system tests, so feel free to check them for examples.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
