### ISSUE TITLE
Add more fluent API to the Cluster Controller resources

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#165]
Instead of having all `void setXXX(..)` methods on all the cluster controller resources (`AbstractCluster`, `KafkaCluster` and so on) a more fluent API could be provided with `XXXCluster withYYY(..)` methods.

**Comment by scholzj** [comment]
@ppatierno @tombentley Do we still see this as useful? Or should we close this?

**Comment by tombentley** [comment]
I think we should close this.
