### ISSUE TITLE
[Bug] helm chart doesn't support watching any namespace

### ISSUE THREAD

**Issue by osela** [strimzi/strimzi-kafka-operator#1661]
The helm chart supports setting the `watchNamespaces` option to set which namespaces the operator should watch. The template code sets the value of the `STRIMZI_NAMESPACE` env variable to the value of `watchNamespaces` and also adds `.Release.Namespace`. There is no way to set the `STRIMZI_NAMESPACE` to `"*"` to make it watch any namespace.

**Comment by stanlyDoge** [comment]
Probably duplicite of https://github.com/strimzi/strimzi-kafka-operator/issues/1454
