### ISSUE TITLE
Doc Enhancement Request: Kafka Cluster Delete and Redeployment Steps

### ISSUE THREAD

**Issue by cmcconnell1** [strimzi/strimzi-kafka-operator#1666]
**Suggestion / Problem**
This is post discussion in the strimzi slack channel in which we were requesting assistance with redeploying a cluster post deleting the cluster manifest.   The problem was that we deleted the cluster and waited for the AWS EBS vol's to become available, then purged them.  I didn't know that the kubernetes pvc remained and effectively prevented fresh cluster redeployment.

Ideally a section for deploying applications/clusters would be very helpful.
Would be great to include details on how to wipe clean and requisite steps to redeploy retaining previous data.
Something like: delete cluster manifest, then delete pvc's

I.e.: 
```sh
k delete -f ./manifests/my-cluster-0.11.1.yaml -n kafka-dev
```
# delete existing pvc
```sh
k delete pvc data-kafka-dev-kafka-0 data-kafka-dev-kafka-1 data-kafka-dev-kafka-2 data-kafka-dev-zookeeper-0 data-kafka-dev-zookeeper-1 data-kafka-dev-zookeeper-2 -n kafka-dev
```

**Documentation Link**
https://github.com/strimzi/strimzi-kafka-operator/tree/master/documentation/book/application-cluster-administration or something similar?  Will create a P/R for this

**Comment by PaulRMellor** [comment]
This issue was discussed on a recent call. The decision was to not update the documentation at present as the use case wasn't compelling enough.
