### ISSUE TITLE
[Doc] Change appendices to refer to properties

### ISSUE THREAD

**Issue by PaulRMellor** [strimzi/strimzi-kafka-operator#1667]
**Suggestion / Problem**
The API reference appendices in the Strimzi documentation use 'Field' as a column name. To be consistent with documentation, this should be changed to 'Property'

**Documentation Link**
https://strimzi.io/docs/master/#api_reference-str

**Comment by scholzj** [comment]
I think this should be a simple change. But I'm not sure the documentation uses property. There is around 50 occurrences of _field_ through the text (outside of the reference appendix). So should you fix that as well, or just change the appendix?

**Comment by tombentley** [comment]
We should fix them all.
