### ISSUE TITLE
[Enhancement] support setting different ingress.class for Ingress

### ISSUE THREAD

**Issue by antimack** [strimzi/strimzi-kafka-operator#1716]
I didn't find how I can specify Ingress storage class when configuring external listener as Ingress.

It would be nice to have an ability to specify ingress.class in case if there are multiple Nginx Ingress controllers deployed in the same namespace so we can choose specific one.

Thanks!

**Comment by scholzj** [comment]
Thanks for opening this issue. I will have a look at it.

**Comment by antimack** [comment]
@scholzj thanks a lot!

**Comment by scholzj** [comment]
I had a bit more look into it. But the Ingress class is not a field and just an annotation. You should be able to use this feature to set the annotations: https://strimzi.io/docs/latest/full.html#customizing_dns_names_of_external_listeners

It was designed primarily for managing DNS, but it can set other annotations as well. So it should work for the `ingress.class` as well. Can you please give it a try?
