### ISSUE TITLE
Factor out common things between the controllers

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#172]
There are some common classes which both controllers could use. We should move these into a new maven module which both controllers depend on. 

Candidates from the topic controller include:

* `LabelPredicate`
* `MapName`
* `Controller.Event`
* `Config`

**Comment by scholzj** [comment]
What is MapName?

I think this whole things is heading towards a common K8s / OpenShift  API, or?

**Comment by tombentley** [comment]
@scholzj it's the name of a configmap, but if I were refactoring it for common usage I would rename it `ResourceName`, since really I think all k8s resource names have the same rules. To be honest it's not much more than a String+validation, but for the topic controller I wanted to use type safety to avoid conflating map and topic names.

**Comment by tombentley** [comment]
I have added `Config` to the list for consideration.

**Comment by scholzj** [comment]
@tombentley Do you think we can call this closed with the `operator-common` module?

**Comment by tombentley** [comment]
Yes
