### ISSUE TITLE
[Bug] Unable to access Kafka outside of K8s cluster

### ISSUE THREAD

**Issue by gowthamgutha** [strimzi/strimzi-kafka-operator#1721]
**Describe the bug**
---------------------
In case when the external-ip is not present for the nodes, the INTERNAL-IP is being taken which is preventing the kafka from being accessed outside of the cluster.

**Output of kubectl get nodes -o wide**
```
node-1    Ready    master,node   41d   v1.13.4   192.168.0.132   <none>        CentOS Linux 7 (Core)   3.10.0-957.10.1.el7.x86_64   docker://18.9.5
node-2    Ready    node          41d   v1.13.4   192.168.0.141   <none>        CentOS Linux 7 (Core)   3.10.0-957.10.1.el7.x86_64   docker://18.9.5
node-3    Ready    node          41d   v1.13.4   192.168.0.142   <none>        CentOS Linux 7 (Core)   3.10.0-957.10.1.el7.x86_64   docker://18.9.5
```
There are many network interfaces on each node and one of the network interface points the internal-ips shown above.

**Strimzi Properties**
```
kubectl exec my-cluster-kafka-0 -n kafka -it -- cat /tmp/strimzi.properties | grep advertised
Defaulting container name to kafka.
Use 'kubectl describe pod/my-cluster-kafka-0 -n kafka' to see all of the containers in this pod.
advertised.listeners=REPLICATION://my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local:9091,CLIENT://my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local:9092,CLIENTTLS://my-cluster-kafka-0.my-cluster-kafka-brokers.kafka.svc.cluster.local:9093,EXTERNAL://192.168.0.140:30918
```
--------
**To Reproduce**
------------------
1. Launch a sample kafka cluster as specified in the documentation.
2. Update the kafka-persistent.yaml file in the examples/ directory of this repo to enable external access as follows (under spec.kafka.listeners):

```
external:
       type: nodeport
       tls: false

```
3. Apply the updated yaml file using _kubectl apply -f -n <namespace>_
4. Get the NodePort and try to access it from oustide.
5. The metadata should return the Internal-IPs which are not accessible from outside of the cluster.

> P.S: Ensure, that the kubectl get nodes -o wide doesn't have any external IPs and that the Internal-IPs are not accessible from outside of the cluster.
----------
**Expected behavior**
-----------------------
If the External-IP is not configured, Strimzi must try to get the node IP using other way. May be for example like this..

```

try(final DatagramSocket socket = new DatagramSocket()){
  socket.connect(InetAddress.getByName("8.8.8.8"), 10002);
  ip = socket.getLocalAddress().getHostAddress();
}
```
[Reference for the above snippet](https://stackoverflow.com/questions/9481865/getting-the-ip-address-of-the-current-machine-using-java
)

and configure it instead of falling back to the Internal-IP.

---------------

**Environment:**
 - Strimzi version: 0.12.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.13.4
 - Infrastructure: Bare-metal

**Comment by scholzj** [comment]
The external IP address has to be set on the node for us to find it. I do not think we want to open any connection to the outside for security reasons, but also this would probably not work well in many different environments. If you cannot configure the nodes to contain the right address, you can use the override features to configure the advertised address manually: https://strimzi.io/docs/latest/full.html#customizing_advertised_addresses_on_external_listeners

**Comment by gowthamgutha** [comment]
I don't understand what is meant by 'not work well in many different environments', the above method should work despite of the ability of the host to connect to 8.8.8.8 (Google DNS) address (reference from the above link only).

**Comment by scholzj** [comment]
Triaged on 21st June: There is no plan to implement this. When the auto-detection based on the information provided by the Kubernetes platform fails, users can customize the advertised addresses.
