### ISSUE TITLE
[Bug] CO raise NPE if wrong Kafka version is used in CR

### ISSUE THREAD

**Issue by Frawless** [strimzi/strimzi-kafka-operator#1722]
**Describe the bug**
CO is raising NPE if wrong Kafka version is specified in CR. CR is created correctly after yaml files are applied, but pods are not created. CO log with version 0.12.0 is slightly different than log from  master CO, but both contains NPE (see logs bellow this for more info)

**To Reproduce**
1. `cd strimzi-kafka-operator`
2. `oc apply -f install/cluster-operator/`
3. `sed -i 's/version: .*/version: 2.2.9/g' examples/kafka/kafka-ephemeral.yaml`
4. `oc apply -f  examples/kafka/kafka-ephemeral.yaml`
5. `oc logs -f <strimzi_operator_pod>`

**Expected behavior**
CO should print WARN log about wrong kafka version used in CR.

**Environment (please complete the following information):**
 - Strimzi version: [master, 0.12.0]
 - Installation method: [YAML files]
 - Kubernetes cluster: [OpenShift 3.11]
 - Infrastructure: [Baremetal, Openstack]

**YAML files and logs**
* CO files (master from 2019-06-20) - https://github.com/strimzi/strimzi-kafka-operator/tree/0de80fdd3954c5ca847d6a942fa9630516821b0a/install/cluster-operator
* Kafka yaml file - https://gist.github.com/Frawless/1d97b2a98b0e63ec73937322da080101
* Kafka CR - https://gist.github.com/Frawless/cfbe2a3fcda1a7d95d49d4cb24e3b597
* CO log (master from 2019-06-20) - https://gist.github.com/Frawless/d7788abb1471cff0a70f8e187087f5e3
* CO 0.12.0 exception from log - https://gist.github.com/Frawless/b7f1051bdf8ec7492bad85953c6b4203

**Comment by tombentley** [comment]
Currently in the CO we warn, but do not kill the operator if the `KAFKA_IMAGES` env var does not include one of the versions in `kafka-versions`. It could still work so long as the user specifies a `Kafka.spec.kafka.image` when using that version, but TBH that seems like a pretty unusual corner case. Other errors report the versions in `kafka-versions`, so it's pretty confusing if some of those don't actually work.

So should we instead make it an error, and exit the CO if it's configured with `KAFKA_IMAGES` env var does not include one of the versions in `kafka-versions`?

Wdyt @ppatierno @scholzj ?

**Comment by scholzj** [comment]
@tombentley So, the `spec.kafka.version` not being in the ENV is not necessarily bug in the CO configuration. It would be most likely a bug in the custom resource. So killing the CO does not seem to be the right thing. Imagine . CO managing several cluster which is looping just because one guy did typo in the version. This is potentially a form of an DoS attack if you exit the CO since you might never reconcile the other valid clusters. So I would say ctach it and print and error but continue on without exiting.

**Comment by tombentley** [comment]
@scholzj Sorry, I didn't explain very well. One fix for one of the NPEs is to throw in the method we use when figuring out the versions for a CR. That method is also used when validating the CO config. Right now in that CO config validation we warn. If that method were to throw then the natural thing to do would be to let the exception propagate, causing the CO process to exit. IOW it's not a `spec.kafka.version` not being in the ENV which would cause the CO to exit, it's the ENV (more specifically one of the `*_IMAGES`) not having an image for one of the supposedly supported versions. I.e. it's misconfiguration of the CO itself.

**Comment by scholzj** [comment]
So how does the CO know that something is missing in the configuration? From the version list in resources? In that case it should be probably fine to just exit. That should raise awareness.

**Comment by stanlyDoge** [comment]
Now the log contains ```

2020-03-03 09:15:45 ERROR AbstractOperator:124 - Reconciliation #0(watch) Kafka(myproject/my-cluster): createOrUpdate failed
--
  | io.strimzi.operator.cluster.model.InvalidResourceException: Version 2.4.9 is not supported. Supported versions are: 2.3.1, 2.4.0.

```
So this can be closed, or?
