### ISSUE TITLE
CO Bootstrapping and improved config validation

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1724]
The very first thing that the CO does is validate and create the `ClusterOperatorConfiguration` from the container environment. It then does platform analysis to determine which features are available.

These things are actually inter-dependent. If we're on a platform with S2I support then we should validate configuration of S2I related things (like S2I images), if not we can safely ignore S2I configuration. The bootstrapping of the cluster should be multi-phase process.

Somewhat relatedly, the `KafkaVersions` goes to some lengths via `Lookup` to ensure that the production code can only get version info from the environment. Really it should be getting it from the Configuration. Fixing this would simplify the tests.

**Comment by scholzj** [comment]
Isn't this just unnecessarily complicating things? We have just one set of installation files, so adding some ifs and elses into the configuration validation just for S2I seems to be a bit overkill.

**Comment by tombentley** [comment]
If we're going to validate we should do it properly. Validating some env vars, but not other related ones is inconsistent.

**Comment by scholzj** [comment]
That is not what I'm suggesting. I'm saying that I would validate the S2I env var anytime regardless of the platform. I would expect it to add unnecessary complexity to the code to validate it only sometimes.

**Comment by scholzj** [comment]
Triaged on 3.3.2022: The S2I is gone now. This might apply to the Kaniko image. But there does not seem to be any real value which this would add.
