### ISSUE TITLE
[Question] Client connectivity problems after operator OOM/restart

### ISSUE THREAD

**Issue by Framstag** [strimzi/strimzi-kafka-operator#1732]
We are currently using Strimzi 0.11.4

We have problems with Services connecting to Strimzi/Kafka getting TimeoutException (on an rather load-less Kafka cluster) after a while that only get fixed after a Kafka restart. Problems ocur for all clients at the same time AFAIK, which could hint at a general, possibly network-releated cause.

We have seen that around the same time the cluster-operator was OOMKilled by the Openshift cluster - and got restarted.

We are currently unsure if our connectivity problem is a Strimzi problem, an Openshift problem or a Kafka problem. Especially the cluster-operator OOM around the same time could hint that Strimzi might be invloved, though in our understanding the cluster-operator installs/monitors/restarts parts of Kafka but is not actively involved in networking or changes of networking configuration, since this is part of the StatefulSet for Zookeeper and Kafka once it has been created.

So, could a hard kill of the cluster-operator have influence of the correct configuration and could lead to networking problems?

Are there are Strimzi aspects that could influence the connectivity of the actual kafka resources?  If yes, how could we check this/test this? Are there logs we could switch on/increase and check? 

Are there any important things to now if developing Kafka-clients in Strimzi/Openshift setup combination?

If not, we are of course helpful for hints regarding analysis of the problem (known effects in Openshift) , though we are aware that this is not the job of the Strimzi community.

Finally, a big "thanks" for this fine project :-)

**Comment by scholzj** [comment]
Are you using resource in the Kafka cluster configuration (https://strimzi.io/docs/latest/full.html#assembly-resource-limits-and-requests-deployment-configuration-kafka)? If not you should try to configure them as this is often causing similar issues. I would suggest as a minimum for Kafka 2Gi or RAM and 500m CPU for it to be stable for development etc.

The crashing cluster operator should not cause any actual problems to the Kafka cluster. But might be rather a symptom of something else going wrong. E.g. some memory handling issues in other applications etc.

**Comment by Framstag** [comment]
OK, I'll check that we explicitely add limits, where missing.
2Gi, 500m CPU is your recommendation for the "Kafka" POD (IMHo this is the cluster-operator). Right?

What about mqcluster-entity-operator?


Just to be sure. Setting explicit memory limits will avoid the cluster-operator (and entity-operator) crashing. Correct?

What about our problems that sending/receiving messages seems not be possible anymore after some (random) time? You stated that the cluster-operator crash should not be connected to that. OK (I assumed that). 

Can memory problems have influence on above connectivity problems? Has Strimzi any influence on that at all? Or do you point to potential Openshift or Kafka problems for that?

**Comment by Framstag** [comment]
We currently do not completely use ressource descriptions for creating topics, should/could that have any influence on connectivity of Kafka. The documentation suggests it should not (though there are definitely advantages to use eplicit topic resources).

**Comment by scholzj** [comment]
The Cluster Operator should have the requests/limits set out of the box unless you removed them. So it should be fine. I was talking about the requests/limits for the Kafka pods.

**Comment by Framstag** [comment]
OK, thanks for you help. We'll check this (since from project to project different: Should I close the question?).

**Comment by scholzj** [comment]
I think we can close this ... and you can re-open it / open a new one if you find out you need something more. Thanks.
