### ISSUE TITLE
[Doc] Metrics Docs include {GitHubVersion} which is not resolved

### ISSUE THREAD

**Issue by sjwoodman** [strimzi/strimzi-kafka-operator#1740]
**Suggestion / Problem**
The links to install the metrics on OpenShift include {GitHubVersion} but this is not resolved to a version. Should it be replaced with {ProductVersion}?

**Documentation Link**
https://github.com/strimzi/strimzi-kafka-operator/blob/master/documentation/book/appendix_metrics.adoc

**Comment by scholzj** [comment]
This seems to be solved now.
