### ISSUE TITLE
[Question] One time migration from topic driven to resource driven Topics

### ISSUE THREAD

**Issue by Framstag** [strimzi/strimzi-kafka-operator#1743]
Due to errors on our side we missed to cleanly define custom resources for our topics as recommended and created topics via auto create via clients.

We now want to change that.

However it looks like if we now supply a custom resource for the topics the topic-operator still favours the information from the topics, effectivly overwriting the information in the resource during runtime. Information is still driven by the topic information.

Question: Is there a way (one-time, clean migration path) to get the topic-operator to favour the resource definition and thus changing the topic if the resource definition changes? The documentation does not hold any information on this (it though states, that should not switch back and forth - which is definitely not our plan) or if and where topic-operator holds such state information (memory, etcd, zookeeper?).

**Comment by tombentley** [comment]
> However it looks like if we now supply a custom resource for the topics the topic-operator still favours the information from the topics, effectivly overwriting the information in the resource during runtime. Information is still driven by the topic information.

That sounds suspicious. Once created you should be able to change the topic from both ends. Can you describe in more detail what you're doing?

>  where topic-operator holds such state information (memory, etcd, zookeeper?).

FWIW the topic operator uses a three way diff to reconcile the differences between kubernetes and kafka (since there's no single source of truth). The 3rd copy of the state is held in zookeeper. But I think modifying this by hand should be a last resort.

**Comment by Framstag** [comment]
OK, based on your description we checked again. It *seems* like changes to the resources are not honoured because we chanmges attribute, for which Strimzi does not support changes yet.

So: No, no suspicion from your side necessary. Your information help us to understand better, what happened.

You can close the issue.
