### ISSUE TITLE
Making clear the meaning of strimzi.io/cluster label in a KafkaUser

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1744]
From the documentation, it seems not clear that, in order for the User Operator noticing a new `KafkaUser` resource from creating the related user, the label `strimzi.io/cluster` in the cluster has to be the name of the cluster for which the user should be created (related to the User Operator).
If it doesn't match, the UO doesn't "see" the `KafkaUser` resource and doesn't create a new user.

**Comment by ppatierno** [comment]
@tombentley damn! right, thanks for moving it.

**Comment by scholzj** [comment]
So I guess we should re-open it?

**Comment by tombentley** [comment]
@ppatierno I moved the existing one.

**Comment by ppatierno** [comment]
@tombentley and I closed the right one. I need to rest sometimes :-)

**Comment by PaulRMellor** [comment]
The _Configuring_ guide now includes a section called [Identifying a Kafka cluster for user handling](https://strimzi.io/docs/operators/in-development/configuring.html#con-securing-client-labels-str). 
This section clarifies the importance of the label
