### ISSUE TITLE
[Enhancement] Installation Deployments should use apps/v1

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1752]
As part of #1723 I changed the api version that we used for the Deployments created by the CO from `extensions/v1beta1` to `apps/v1`, but we should also fix the Deployments in the installation resources to match.

**Comment by WheresAlice** [comment]
This will be required to work with Kubernetes 1.16

On a Kubernetes 1.16 minikube cluster we are seeing the following when attempting to deploy the operator:

> error: unable to recognize "strimzi-cluster-operator-0.13.0.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

**Comment by ppatierno** [comment]
It's already fixed in the master and will be available in the coming 0.14.0 release.
See this PR https://github.com/strimzi/strimzi-kafka-operator/pull/1984

**Comment by scholzj** [comment]
I have actually already done it in #1984. It will be part of the 0.14.0 release. Feel free to try one of the RCs which we have already out.
