### ISSUE TITLE
[Enhancement] Use maven for adding jars to classpath

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1754]
As mentioned [here](https://github.com/strimzi/strimzi-kafka-operator/pull/1731#pullrequestreview-255832721), we should try to use a pom/bom to describe the dependencies which we want to pull into the Kafka image and added to the classpath. That would avoid needing to handle transitive dependencies (we'd only need to list the direct deps), and simplify upgrades. It would also make it easier for people wishing to build their own images.

**Comment by scholzj** [comment]
I take it you want to use it for things like the Json logging, JMX exporter
etc and not Kafka it self?

**Comment by tombentley** [comment]
That's right. Kafka itself is more than just the jars (e.g. scripts), so I think we should still pull that directly from apache.org

**Comment by scholzj** [comment]
@tombentley It is not implemented in #1731, but Travis doesn't like it. I'm not sure why and our logging is terrible.

**Comment by tombentley** [comment]
https://github.com/strimzi/strimzi-kafka-operator/commit/d29f744badb40fc8ecd88b6fa56c11591f21cbc2 shows how I envisaged this working. Basically we'd prepare the directory of dependencies before running the existing docker build. For one thing that means we don't need `mvn in the docker images, which I see as a plus.

**Comment by scholzj** [comment]
I think the solution with multi stage Docker build in the PR is IMHO better. But I guess there is some probability that this might be what does not work on Travis. (It worked fine locally)

**Comment by ppatierno** [comment]
Pay attention to using multi-stage Docker build. My experience is that the current Docker version I have on my Fedora doesn't support it (but I have to use this Docker version :-)). Maybe it could happen to someone else. It doesn't mean that we should not move to use multi-stage btw.

**Comment by scholzj** [comment]
@ppatierno Well, it sounds like a blocker if you cannot use it ... we need you to be able to build the images! You should probably mention it in #1731

**Comment by GrigorievNick** [comment]
I think we can close this?.
It's done during logging task.

**Comment by scholzj** [comment]
Yes, correct. Thanks for raising this up.
