### ISSUE TITLE
[Doc] Unclear what namespace should be changed for operator to watch multiple projects

### ISSUE THREAD

**Issue by alainpham** [strimzi/strimzi-kafka-operator#1756]
**Suggestion / Problem**

In the documentation for deploying on Openshift to watch multiple namespaces it is not clear whether the my-namespace/my-project inside the yaml files should be changed. I assume it must not be changed in the yaml file. The yaml file should contain the name of the namespace of the cluster operator and the namespace in the command is the watched namespace.

> For all namespaces or projects which should be watched by the Cluster Operator, install the RoleBindings. Replace the my-namespace or my-project with the OpenShift project or Kubernetes namespace used in the previous step.

Maybe it's better to distinguish it as follows in the doc :
Instread of naming the examples my-namespace or my-project. We should call the examples my-cluster-operator-namespace and my-watched-namespace to better clarify what means what.

**Documentation Link**
Provide a link to the documentation where the bug / suggestion should be applied

https://strimzi.io/docs/latest/#deploying-cluster-operator-kubernetes-to-watch-multiple-namespacesstr

**Comment by PaulRMellor** [comment]
The docs now use the _my-cluster-operator-namespace_ and _watched namespace_ conventions and make it clear what needs to be replaced. 

- [Deploying the Cluster Operator to watch a single namespace](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-cluster-operator-str)
- [Deploying the Cluster Operator to watch multiple namespaces](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-cluster-operator-to-watch-multiple-namespaces-str)
- [Deploying the Cluster Operator to watch all namespaces](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-cluster-operator-to-watch-whole-cluster-str)
