### ISSUE TITLE
[Enhancement] Add Strimzi releases 0.12.0 and 0.12.1 to OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi-kafka-operator#1757]
Add Strimzi releases 0.12.0 and 0.12.1 to OperatorHub.io.

**Comment by scholzj** [comment]
There seem to be some changes in the OperatorHub which we needed to deal with. There are now two PRs which should address this:
* https://github.com/operator-framework/community-operators/pull/483
* https://github.com/operator-framework/community-operators/pull/484

**Comment by scholzj** [comment]
This should be fixed now.
