### ISSUE TITLE
About mirror maker configuration parameters

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1762]
Related to #1734 (and PR #1760) ...

Today, we have `num.streams` under the `consumer` section which makes sense because it's just consumer related.
The `offset.commit.interval.ms` (addressed by above PR) is going to be into the `consumer` section as well, which makes sense again.

The `abort.on.send.failure` (Configure the mirror maker to exit on a failed send. (default: true)) could be added under the `producer` section. Btw, with the current default, it means that MM container exits but Kubernetes will restart it so the send could fail again and so on. Making it configurable could be useful. 
When false, the MM just logs the skipped message and move on.

Currently, we also have a `config` section under consumer and producer but we moved `bootstrapServers` and `groupId` outside of it. I am thinking that it wasn't a good choice because more often we are relying on using a generic config section for all the stuff related to Kafka native client (see how it works in the HTTP Kafka bridge for example).
Isn't it feasible to deprecate them and allowing the user to specify them under `consumer.config` and `producer.config` as `bootstrap.servers` and `group.id`?

**Comment by scholzj** [comment]
`consumer.config` and `producer.config` is a map. So you have no way to enforce any rules on it on the CRD level - e.g. to make the `bootstrapServers` and `groupId` options mandatory.

**Comment by ppatierno** [comment]
So agree, let's add `abort.on.send.failure` in the configuration via #1760 for now.
@stanlyDoge are you ok with that?

**Comment by stanlyDoge** [comment]
Absolutely. Just for clarification - it should be part of producer spec, right?

**Comment by ppatierno** [comment]
yes it's about producing

**Comment by scholzj** [comment]
@ppatierno @stanlyDoge Is this still valid? didn't we solved this?

**Comment by ppatierno** [comment]
@scholzj yes we solved this. Closing it.
