### ISSUE TITLE
Fire Kubernetes/OpenShift events on forbidden storage update

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#177]
Currently, the cluster controller just logs a warning when the use change the cluster ConfigMap with forbidden changes (i.e. changing `type`, `size` and so on).
It could be useful having the cluster controller firing a Kubernetes/OpenShift event as well which will be visible on the console.

**Comment by scholzj** [comment]
Reviewed on 10th September 2020: We use now CR status for this kind of things. This issue was opened before Custom Resources. Using Events for this does not seem to make sense anymore.
