### ISSUE TITLE
[Enhancement] Annotate installation ClusterRoles and Roles

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1771]
**Is your feature request related to a problem? Please describe.**
When people look at the installation resources which create ClusterRoles and Roles a typical reaction is "Whoa! That's a lot of access". This can put people off using Strimzi, especially if the person reading the resources is a cluster admin who doesn't even know what Strimzi is/does.

**Describe the solution you'd like**
The installation resources which create ClusterRoles and Roles should be annotated with comments explaining which component requires the access and why it is needed. In addition if it's possible to disable some of the requested access (at the cost of lost features) this should also be made clear in the comments. Rack awareness requiring node access is one example.

**Describe alternatives you've considered**
This could also be documented elsewhere, but it would be more difficult to maintain and the person reading the resources might not know about that documentation, so it would not solve the problem. If we really need this in the user documentation we could do that later by processing the installation YAMLs into a form better suited to inclusion in the docs.

**Comment by ppatierno** [comment]
@tombentley does #3029 address what you are describing here?

**Comment by tombentley** [comment]
It does!

**Comment by samuel-hawker** [comment]
Glad I closed this issue early ;)

Let me know if any of the descriptions are insufficient, happy to review and approve any changes you want to make.
