### ISSUE TITLE
[Enhancement] make jute.maxbuffer JVM option configurable

### ISSUE THREAD

**Issue by joekohlsdorf** [strimzi/strimzi-kafka-operator#1773]
**Is your feature request related to a problem? Please describe.**
I am currently testing a pretty big cluster with hundreds of topics, the maximum size of a znode in Zookeeper is 4MB and once I reached that limit (around 150k znodes) I started seeing the following errors in the log which ultimately ended in an unrecoverable situation:
`java.io.IOException: Packet len5095780 is out of range!`

The cluster operator restricts the JVM options which can be changed and `jute.maxbuffers` isn't one of them.

**Describe the solution you'd like**
I would like to be able to change the `jute.maxbuffers` JVM parameter for both Kafka and Zookeeper.

**Comment by scholzj** [comment]
@joekohlsdorf Thanks for raising the issue. I can have a look at it. What is the approach to reproduce this so that we can test it? Should I just add more and more topics until this happens?

**Comment by joekohlsdorf** [comment]
After further analysis I found that this was actually caused by some sort of endless loop in the topic operator which writes to `/config/changes` in Zookeeper. I haven't been able to reproduce this since.

In the worst case you still end up with an unrecoverable cluster because the Zookeeper command line utilities are unable to operate because they hit the same server-side limits.

**Comment by scholzj** [comment]
What version of Strimzi do you use? The loop should be IMHO already fixed in 0.12.x.

**Comment by joekohlsdorf** [comment]
This happened on an 0.11.1 cluster, I updated to 0.12.1 when this issue broke it.

**Comment by scholzj** [comment]
Ok, gret. Can we lose this issue in that case? Thanks

**Comment by joekohlsdorf** [comment]
Fine with me.
Note that you could still end up with an unrecoverable cluster if you manage to reach ~150k ZNodes.

**Comment by abhishekjiitr** [comment]
Faced a similar issue on 0.11.0, the znodes in _/config/changes_ was filled by topic operator. Had to delete the whole znode to fix this.

**Comment by Airfan** [comment]
We are having 330k znodes in a 0.39 cluster with error message:
2024-03-19 12:58:51,972 ERROR Unexpected throwable (org.apache.zookeeper.ClientCnxnSocketNetty) [nioEventLoopGroup-2-1]
java.io.IOException: Packet len 9162276 is out of range!

Are you sure that was fixed in 0.12? We are in unrecoverable state at the moment
