### ISSUE TITLE
How to scaling up Kafka Broker

### ISSUE THREAD

**Issue by nomis-rzp** [strimzi/strimzi-kafka-operator#1781]
What is the right way to scale up Kafka broker pods. I tried changing the replicas in the yaml file and applied it, but it terminated and recreated the existing kafka pods. Or should i edit the stateful set manually ? Please advise @scholzj

**Comment by ppatierno** [comment]
You are doing it in the right way so actually changing the replicas field in the Kafka resource. What version of Strimzi are you using. Can you share the Kafka resource YAML you are using?

**Comment by nomis-rzp** [comment]
Strimzi version 0.11.1

[kafka-persistent.txt](https://github.com/strimzi/strimzi-kafka-operator/files/3367202/kafka-persistent.txt)

**Comment by scholzj** [comment]
@nomis-rzp The right process is that you edit the `Kafka` custom resource and edit the field `spec.kafka.replicas`. Looking at your `kafka-persistent.txt` you shared - it seems to be invalid:

```
spec.kafka.template.pod.metadata.annotations in body must be of type object: "null"
spec.zookeeper.template.pod.metadata.annotations in body must be of type object: "null"
```

This will cause all changes to be not applied. So I wonder if this could have caused your changes tot he number of replicas to be discarded.

**Comment by nomis-rzp** [comment]
@scholzj I have proper annotation in my actual yaml file. I just removed it from the file i uploaded. 

>This will cause all changes to be not applied. So I wonder if this could have caused your changes tot he number of replicas to be discarded.

My changes are getting applied and the new replica pod will come up but it will terminate all the existing pods and bring them back up and then brings up the new replicas. My issue is that, why existing pods are getting terminated and recreated along with the new replica.

**Comment by scholzj** [comment]
Ahh, ok. I do not think this is necessarily an issue. This is currently expected when you use external listener such as node ports - its because of how the configuration is handled and generated.

**Comment by nomis-rzp** [comment]
@scholzj But that could potential cause issue/outage with the kafka cluster when the pods get terminated and created.. right ?

**Comment by scholzj** [comment]
Rolling updates are fairly common thing. If you use replication they should not impact the cluster availability. The clients should just reconnect to another replica. So while this could be improved in theory, it should not be a major issue.
