### ISSUE TITLE
[Enhancement] Upgrade tests should contain message exchange with store them in persistent volume

### ISSUE THREAD

**Issue by Frawless** [strimzi/strimzi-kafka-operator#1791]
Upgrade tests should contain the following additional steps:

1. Deploy Kafka cluster with persistent storage
2. Send messages to Kafka before upgrade (with old version of clients, messages will survive restarts cause persistent storage)
3. Do upgrade of CO and Kafka (this is covered)
4. Read messages from Kafka with new version of clients

**Comment by scholzj** [comment]
Triaged on 3.3.2022: This seems to be already done and can be closed.

@Frawless @im-konge @see-quick please re-open it if it is not the case.
