### ISSUE TITLE
AMQ stream and  strimzi 

### ISSUE THREAD

**Issue by FridMehdi** [strimzi/strimzi-kafka-operator#1794]
@strimzi what is the diffrence between amq stream and strimzi thanks

**Comment by scholzj** [comment]
Strimzi is an open source project which everyone can use and contribute to. It is free to everyone but there are also no support guarantees etc. It is just open source project and nothing more.

AMQ Streams is a product from Red Hat which is based on the Strimzi and Apache Kafka project. As a part of a paid subscription you get support etc.

Hope this helps.
