### ISSUE TITLE
Incorrect default directory for Kafka Connect binary build

### ISSUE THREAD

**Issue by jpechane** [strimzi/strimzi-kafka-operator#1804]
The build process by default places plugins into `s2i` subdir of `/tmp/kafka-plugins`.
https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/s2i-scripts/assemble#L22

But the start script sets plugin path to `/tmp/kafka-plugins`
https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/s2i-scripts/run#L13

This means that all plugins are in the same subdirectory and are loaded by the same classloader which breaks plugin isolation.
The plguin path should point to exactly the same directory where plugin directories are located without any additional subpath.

**Comment by scholzj** [comment]
I'm not sure I understand the problem. This works fine for many plugins.

**Comment by jpechane** [comment]
@scholzj Just imagine two plugins using the same dependency in different version. In current setting all plugins would share the same dependency. With the correct setup each plugin will have its own dependency.
It was discovered when two Debezium plugins of different version were deployed side-by-side (different databases).

**Comment by scholzj** [comment]
But I do not think we touch the directories. If you give us one big bundle of JARs in one directory they should end up in the same directory. If you give us a tree structure with directory per plugin we should keep this structure. 

Or maybe if you can give a more specific example of what are the cases when we mix the JARs I might be able to better understand the problem.

**Comment by jpechane** [comment]
Let's suppose we have two plugins, each ses different version of protobuf

In correct setup
`/tmp/tmp/kafka-plugins/plugin1/protbuf2.jar`
`/tmp/tmp/kafka-plugins/plugin1/plugin1.jar`
`/tmp/tmp/kafka-plugins/plugin2/protbuf3.jar`
`/tmp/tmp/kafka-plugins/plugin2/plugin2.jar`

There will be two classloaders, `plugin1.jar` will see `protobuf2.jar` and `plugin2.jar` will see `protobuf3.jar`

In wrong setup
`/tmp/kafka-plugins/s2i/plugin1/protbuf2.jar`
`/tmp/kafka-plugins/s2i/plugin1/plugin1.jar`
`/tmp/kafka-plugins/s2i/plugin2/plugin2.jar`
`/tmp/kafka-plugins/s2i/plugin2/protbuf3.jar`

There will be *one* classloader `s2i`. The clapass path will contain both `protbuf2.jar` and `protbuf3.ja
r` and if they are not compatible then at least one plugin will fail because it will see the wrong version of dependency. So both `plugin1.jar` and `plugin2.jar` will see the same protobuf jar but it is not predictable which one.

**Comment by scholzj** [comment]
Thanks for the clarification. I opened a PR for this.
