### ISSUE TITLE
Add DNS annotations to nodeport services[Enhancement] ...

### ISSUE THREAD

**Issue by gamer22026** [strimzi/strimzi-kafka-operator#1811]
Currently using external nodeport services, a manual DNS entry must be created to the external bootstrap service so that external clients have a common FQDN to connect to.

Allow nodeport services to support dnsAnnotations (both ingress and loadbalancer types already do). This would allow the external bootstrap service to have an auto-configured DNS entry either using the kops based dns-controller annotations (https://github.com/kubernetes/kops/tree/master/dns-controller) or ExternalDNS annotations.

**Comment by scholzj** [comment]
@gamer22026 Thanks for opening the issue. I opened a PR for this - so this should be done in the next release.
