### ISSUE TITLE
Storage Class configuration override support for custom PVCs

### ISSUE THREAD

**Issue by NathanielRose** [strimzi/strimzi-kafka-operator#1834]
When targetting a persistent volume claim custom storage class for a kafka broker, I would like to customize additional native kubernetes `volumeclaimtemplates` parameters such as `access modes` `iops` etc.

According to strimzi docs: The overrides property is currently used only to override storage class configurations. Overriding other storage configuration fields is not currently supported. Other fields from the storage configuration are currently not supported.

An improvement would be to add keymap configuration support to the override field.

**Comment by scholzj** [comment]
Triaged on 17.3.2022: No feedback. So we are going to close this. Can be re-opened later if needed.
