### ISSUE TITLE
Missing dashboard for ConnectS2I

### ISSUE THREAD

**Issue by stanlyDoge** [strimzi/strimzi-kafka-operator#1883]
**Describe the bug**
After working with Connect and Connect S2I together with Prometheus and Grafana, I found we are missing a dashboard json file for the Kafka Connect S2I. 
The `strimzi-kafka-connect.json` file uses queries like `...strimzi_io_kind="KafkaConnect"...` but when the Kafka Connect S2I is deployed, it returns a body with payload like this: `...strimzi_io_kind="KafkaConnectS2I"...`

There are few solutions
1. Add a file for the Kafka Connect S2I (the very same file as for Connect just with changed queries)
2. Use `strimzi_io_kind~="KafkaConnect.*" in the queries
3. Add the sed command for the replacing `kind` to the docs: `sed -i 's/strimzi_io_kind=\"KafkaConnect\"/strimzi_io_kind=\"KafkaConnectS2I\"/' metrics/examples/grafana/strimzi-kafka-connect.yaml`

I think option 1 is the most reasonable but I want to see another opinions. Thanks.

**Comment by scholzj** [comment]
I think we should go the option 2. But options 1 and 3 have some advantages (seding, maintaining two dashboards, etc.).

**Comment by ppatierno** [comment]
If 2 works, I would go with it avoiding to have two different Kafka Connect dashboards.
