### ISSUE TITLE
[Question] Upgrade disks for a single broker at a time

### ISSUE THREAD

**Issue by cameronbraid** [strimzi/strimzi-kafka-operator#1898]
Hi

I currently run strimzi 0.9.0 on openshift 3.9 using the local volume provisioner for volumes.

We have 3 kafka brokers spread across 3 bare metal nodes.

I am running out of space so are adding new disks to the machines.

I am taking the following approach to perform the upgrade, one node at a time :

- shutdown node
- install new drive
- startup node
- setup local volume provisioner on new disk
- create a new PV on the new disk (PV-new)
- take the kafka broker down on the node
- start a sleep pod on node with PV-old and PV-new mounted
- rsh into sleep pod and rsync data from PV-old to PV-new
- start the kafka broker on the node using PV-new

Some questions arise with this process

* how do I shutdown a specific broker pod ?  say kafka-kafka-1 .. if I delete it it gets recreated
* how do I configure the kafka broker on the node to use PV-new

Or is there a better approach ?

Cheers

Cameron

**Comment by scholzj** [comment]
I'm afraid there are no easy ways for this ... but maybe this helps a bit:

> how do I shutdown a specific broker pod ? say kafka-kafka-1 .. if I delete it it gets recreated

The pods are managed by the StatefulSet controller. So are not so easy to stop. On OpenShift, you can maybe use the `oc debug` feature. It will basically start the Kafka pod in a debug mode -> which is into shell with a terminal. You can basically request the debug pod, delete the old pod and once the debug pod starts it will block the regular pod from starting again. That is probably the easiest way which comes to my mind.

> how do I configure the kafka broker on the node to use PV-new

The brokers do not use the PVs directly. They use the PVCs which refer to PV. So I think that after you rsync the data you would need to modify the PVC to link with the `PV-new` and not the old PV. TBH I don't think you can modify it just by `oc edit`. So you might need to dump the YAML, delete the old PVC, and create the new PVC with the new PV linked. As long as you use the same PVC name, Strimzi should simply use the new PVC with the new disk.

**Comment by cameronbraid** [comment]
Debug pod - that's a great idea thanks.

Re PV-s - yeah, I understand how it uses PVC not PV.  

I'll try doing some PVC hacking in a separate project to see what works

Thanks
