### ISSUE TITLE
[Bug]  "prioroty" field in kafkatopics.kafka.strimzi.io CRD is not recognized by the API server

### ISSUE THREAD

**Issue by yuha0** [strimzi/strimzi-kafka-operator#1909]
**Describe the bug**
`kafkatopics.kafka.strimzi.io` has a `priority` field in `CustomResourceColumnDefinition`: https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/topic-operator/04-Crd-kafkatopic.yaml#L30
However, this field is not returned in a `GET` call by the API server:

```
$ kubectl get CustomResourceDefinition -oyaml kafkatopics.kafka.strimzi.io | grep JSONPath: -B2 -A 5
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.partitions
    description: The desired number of partitions in the topic
    name: Partitions
    type: integer
  - JSONPath: .spec.replicas
    description: The desired number of replicas of each partition
    name: Replication factor
    type: integer
  conversion:
    strategy: None
```

This means, if I execute `kubectl apply` multiple times, it will always show as configured instead of unchanged even if there's no change at all:

```
$ kubectl apply -f 04-Crd-kafkatopic.yaml
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io configured
$ kubectl apply -f 04-Crd-kafkatopic.yaml
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io configured
$ kubectl apply -f 04-Crd-kafkatopic.yaml
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io configured
...
```

**To Reproduce**
1. run `kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/install/topic-operator/04-Crd-kafkatopic.yaml`
2. run `kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/install/topic-operator/04-Crd-kafkatopic.yaml`
3. step 2 will return "configured" instead of "unchanged" because of the `priority` field

**Expected behavior**
I am not sure if this is something we can fix in the CRD, or an issue in Kubernetes API server, but I would want the API server to recognize everything we defined in the CRD definition, including the  `priority` field.

**Additional context**
This is annoying if you have a GitOps pipeline to control strimzi CRDs -- our GitOps controller thinks the CRD is out of sync because the yaml file has `priority` field but the returned object from `kubectl get` does not have it

**Comment by yuha0** [comment]
According to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go#L236

`priority` is labeled with `omitempty`. This means it will not be returned if the value equals to `0` (`0` means empty for an integer type).

Since 0 is already the default priority, I think it can be removed from the CRD definition.

**Comment by scholzj** [comment]
CC @tombentley

**Comment by tombentley** [comment]
TBH when I was implementing this I was just following the documentation [here](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/#priority), which doesn't describe what the defaults for any of those fields are. I guess you're right at it could be omitted when 0, but it's harmless to include 0, so I don't see it as a priority to remove it.

**Comment by tombentley** [comment]
@yuha0 sorry, I didn't see all the context provided above. I guess it is problematic for you. It should be trivial to fix, actually. On line 246 or the `CrdGenerator` you can just add the `priority` property conditionally. Would you be able to provide a PR?

**Comment by tombentley** [comment]
@yuha0 all the CRD YAMLs are generated by the CrdGenerator, so we need to make the fix there.
