### ISSUE TITLE
[DOC] Broken link in appendix

### ISSUE THREAD

**Issue by laidan6000** [strimzi/strimzi-kafka-operator#1911]
**Problem**
There is a broken link in _Appendix D: Installing an OpenShift Cluster_.
- appendix_deploying_openshift_cluster.adoc
- https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md

**Documentation Link**
https://strimzi.io/docs/master/#installing_openshift_cluster

**Comment by WheresAlice** [comment]
There's an [OpenShift issue](https://github.com/openshift/origin/issues/21553) for this page going missing, and it turns out there are multiple ways of launching an OpenShift cluster now, so it's not as straightforward as just fixing a broken link.

**Comment by scholzj** [comment]
I think this section is not in our docs anymore.
