### ISSUE TITLE
[Enhancement] Pass custom annotations to PVCs

### ISSUE THREAD

**Issue by spencergilbert** [strimzi/strimzi-kafka-operator#1914]
I see in #1039 the ability to pass annotations was introduced for most resources, is it possible to add a similar configuration for PVCs?

**Comment by scholzj** [comment]
That is not possible right now. But if you want we can change this to enhancement and add such option in one of the future releases.

Do you mind sharing the usecase for annotations on PVC? I'm always curious why such thing might be needed / useful.

**Comment by spencergilbert** [comment]
My particular use case is with using strimzi with ArgoCD, since the PVCs aren't part of the git repo (just the kafka crd is) it sees these as out of sync and wants to remove them. The expected workflow for argo is to annotate resources with a particular ignore flag

**Comment by scholzj** [comment]
Ok, that sounds useful. I will try to get this done. It should be quite easy, so I hope to get to it soon. But right now I do nto have any exact date.

**Comment by spencergilbert** [comment]
Thanks! Thankfully it doesn't seem like ArgoCD can _actually_ delete the resources thanks to the PVC protections :smile:

**Comment by spencergilbert** [comment]
Thanks @scholzj !
