### ISSUE TITLE
[Question] Just running Mirror Maker

### ISSUE THREAD

**Issue by ennala** [strimzi/strimzi-kafka-operator#1915]
Hi,

I need to write to kafka mirror which can be deployed to our k8s cluster and which replicates data between our 2 existing kafka clusters and found this great project. I have few questions which I need clarification.

1) We are just going to use only kafka mirror maker ... do we need to deploy the whole cluster operator to use this or is there a way we can deploy which only has mirror maker ?

2) Our clusters are set up using SSL encryption ( truststore, keystore jks files and password) .. I see that only TLS encryption is supported .. is there a way we can supply SLL encryption files.

Thanks.

**Comment by scholzj** [comment]
Thanks for the questions. Please see the answers below:

1) There is just one operator which operates everything. So you need to install it in the same way as if you would be when using Kafka brokers as well. Once the operator is running, you of course don't have to deploy any KAfka clusters. All you have to do is to create the `KafkaMirrorMaker` custom resource with your desired Mirror Maker configuration.

2) I think it might a bit depend on the actual TLS/SSL configuration. If you brokers use SSL in the sense that they have the `ssl.protocol` field set to for example `SSLv2`, it might be a problem. But in most cases these are just synonyms. So give it a try.

**Comment by ennala** [comment]
Thanks for answers ... highly appreciate it.

One last question.

I am trying to under the configuration part from the example below.
https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka-mirror-maker/kafka-mirror-maker-tls.yaml

In kafka mirror I specify the config some thing like below 
```
bootstrap.servers=test.host:9492
security.protocol=SSL
ssl.truststore.location=test-truststore.jks
ssl.truststore.password=testTrustPassword
ssl.keystore.location=test-keystore.jks
ssl.keystore.password=testKeyPassword
```

In the example I see the consumer is configured with trust certificate like this.

```
    tls:
      trustedCertificates:
        - secretName: my-source-cluster-cluster-ca-cert
          certificate: ca.crt
```
Do I need to get the truststore certificate from my jks and supply it as a secret (secretName) ? what is ca.crt btw ?

And how do I specify keystore details ?

**Comment by scholzj** [comment]
The way this works is that you should take the certificate from the truststore and store it in a Secret as a plain CRT file. Amnd when you reference the Secret and the certificate in the `tls` section, the Operatore'will do the rest for you - configure the `security.protocol`, the truststore locations etc.

If you want to use TLS client authentication (e.g. to specify the keystore and use it as well), you need to specify the publci and private key which should be used in the keystore in the `authentication section. See more in the documentation, where there is example for the TLS authentication: https://strimzi.io/docs/latest/full.html#tls_client_authentication_4

Again, you do not need to specify anything in the `config` section for it. All you need there is the bootstrap server and the group for the consumer.

**Comment by ennala** [comment]
Thanks.
