### ISSUE TITLE
[Question]There is a problem in Strimzi Quickstart

### ISSUE THREAD

**Issue by xiongmaodada** [strimzi/strimzi-kafka-operator#1916]
hi, @scholzj  when I walk through a quick and easy install for [k8s development environment](https://strimzi.io/quickstarts/minikube/),  in third step(Provision the Apache Kafka cluster): 
```
kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.13.0/examples/kafka/kafka-persistent-single.yaml -n kafka 
```
The following problem has occurred:
```
root@xxx-k8s-test-2:~# kubectl get  pvc -o wide  -n kafka
NAME                          STATUS    VOLUME                        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-my-cluster-zookeeper-0   Pending                                                                          44m
data01-kafka-0                Bound     local-pv-k8s2-data01-broker   1Gi        RWO            kafka-broker   54d
data01-kafka-1                Bound     local-pv-k8s3-data01-broker   1Gi        RWO            kafka-broker   54d
root@xxx-k8s-test-2:~# 
root@xxx-k8s-test-2:~# kubectl describe  pvc  data-my-cluster-zookeeper-0   -n kafka
Name:          data-my-cluster-zookeeper-0
Namespace:     kafka
StorageClass:  
Status:        Pending
Volume:        
Labels:        strimzi.io/cluster=my-cluster
               strimzi.io/kind=Kafka
               strimzi.io/name=my-cluster-zookeeper
Annotations:   strimzi.io/delete-claim: false
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Events:
  Type       Reason         Age                   From                         Message
  ----       ------         ----                  ----                         -------
  Normal     FailedBinding  4m4s (x175 over 44m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
Mounted By:  my-cluster-zookeeper-0
```
how to solve this problem?

**Comment by scholzj** [comment]
Are you running this on Minikube or somewhere else? And if it is Minikube, which version it is? It looks like you do not have any available persistent volumes, so Kubernetes cannot provision the cluster.

You can try to use the example with [ephemeral](https://strimzi.io/docs/latest/full.html#ref-ephemeral-storage-deployment-configuration-kafka) storage: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.13.0/examples/kafka/kafka-ephemeral.yaml ... but this has the disadvantage that of the pod restarts it will loose all data. So it is suitable only for some very basic playing and not really for anything serious.

**Comment by xiongmaodada** [comment]
thanks a lot !

I am not running this on Minikube  but  k8s that I set up. the reason for the problem is that  I do not have any available default storage class. After I set default storage class, it's ok!

if I don't set default storage class, it is ok that I use the example with ephemeral storage: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.13.0/examples/kafka/kafka-ephemeral.yaml.

**Comment by scholzj** [comment]
If you don't have default storage class but have some other storage class you want to use, you can just specify the class name in the Kafka custom resource (see [docs](https://strimzi.io/docs/latest/full.html#ref-persistent-storage-deployment-configuration-kafka) for more details). Otherwise yeah, you have to use the ephemeral example.

**Comment by xiongmaodada** [comment]
em, thank you very much

**Comment by chiheb08** [comment]
@xiongmaodada  can you give me some hints on how to solve it? I'm going through the same problem

**Comment by Starttoaster** [comment]
> @xiongmaodada can you give me some hints on how to solve it? I'm going through the same problem

Here's an example Node Pool CR that:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: my-node-pool
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        class: ceph-rbd
        size: 20Gi
        deleteClaim: false
```

You specify the storage class name in that `class` key.  I was kind of surprised this option didn't make it into one of the examples, because the API documentation is a little rougher to translate to yaml.
