### ISSUE TITLE
[Question] Topic-Operator tries to connect broker with old IP

### ISSUE THREAD

**Issue by Framstag** [strimzi/strimzi-kafka-operator#1919]
We had yesterday the effetc that the topic controller tried to connect one of our brokers but failed. In the context of the error message hostname and IP of the broker were dumped.

The IP of the broker was wrong. We assume - since the broker was restarted before - that the IP adress belong to an old instance of the broker.

Since Openshift only guarantees fixed hostnames but not fied IP adresses for stateful sets, we assume that the topic-operator was victim of another effect in the kafka cluster (we had in parallel the effect that one of the other brokers seem to have "left" the cluster).

To further analyse the problem and their cause on our side it would be interesting to know how the topic-controller tracks changing IP addresses of brokers on their restart and what must have been happend to this appraoch so that the controller was out of sync.

Can you help us?

**Comment by scholzj** [comment]
The Topic Operator doesn't use IP addresses of the brokers but the DNS names. The problem is that the DNS is subject to caching, which probably happened in your case. So I assume your problem could have been with the DNS cache?

**Comment by Framstag** [comment]
I assume that the Kubernetes/Openshift itself does not do significant DNS caching, changes of IP adresses due to container restart should propergate fast and we checked that the new IP was shown and propergated by the Openshift itself.

The problem IMHO (do you agree?) thus must be within the Java process itself? I see that one in principle has the option to influence the DNS caching of java (see https://stackoverflow.com/questions/1256556/how-to-make-java-honor-the-dns-caching-timeout and https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html) but we did not set one of these options manually, thus the default of 30 seconds should be active - or are you activating a security manager (we are using the default images)? Or are you caching on a higher level, too?

We are rather sure that the problem occured for more than 30 seconds (we discussed it for more than 30 seconds), though logs are already gone.

It would be nice if the base images already handled the problem actively (choose a reasonable setting for Kubernetes/Openshift) or is it up to us to do such configuration?

**Comment by scholzj** [comment]
Well, TBH this is a bit of mystery for me. AFAIK most of the solutions for disabling DNS caching in Java do not really work properly. Anyway, I changed this from question to bug and will try to find some more time to look into it.

**Comment by Framstag** [comment]
Yes, it stounds strage. We keep monitoring this effect from our side, too (since we still seem to have "effects" with kafka production stability). In case we see the problem again, which information would help you?

**Comment by scholzj** [comment]
Triaged on 2.8.2022: Should be closed. This seems to be old and outdated ->we now use DNS names to connect to Kafka / ZooKeeper.
