### ISSUE TITLE
A few doubts while deploying Prometheus

### ISSUE THREAD

**Issue by soheilade** [strimzi/strimzi-kafka-operator#1923]
Hi, I am following the [guide](https://strimzi.io/docs/latest/#proc-metrics-deploying-prometheus-str) to deploy prometheus for scraping kafka metrics 

I have two questions:

- I find step 2 very unclear to understand:
> 2. Edit the ServiceMonitor resource in strimzi-service-monitor.yaml to define Prometheus jobs that will scrape the metrics data.

What am I supposed to do? Can I use the default file as is or what are the names of the jobs?

- while running 
`oc apply -f strimzi-service-monitor.yaml`
I get this error
`error: unable to recognize "strimzi-service-monitor.yaml": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

Any idea how to resolve this?

Soheila

**Comment by scholzj** [comment]
@stanlyDoge @PaulRMellor @laidan6000 Could you please have a look at this?

**Comment by stanlyDoge** [comment]
Hi.

1. We provide example jobs which can be used. It is [description](https://github.com/prometheus/prometheus/blob/master/docs/getting_started.md#configuring-prometheus-to-monitor-itself) of jobs which are scraping metrics from the endpoints.

2. These CRDs are installed by CoreOS Prometheus Operator. Are sure you installed Prometheus Operator? Is it successfully started?

**Comment by soheilade** [comment]
Thanks @stanlyDoge , 

1.Could you please elaborate where in a serviceMonitor yaml, I can add the scrape_configs section? is it just enough to attach scrape_configs section at the end? 
Would this config work for scraping kafka?
```
scrape_configs:
 - job_name: 'kafka'
   scrape_interval: 10s
   static_configs:
    - targets:
      - localhost:7071
        labels:
          group: 'kafka'
```
2. I actually applied all the resources at this [stage ](https://strimzi.io/docs/latest/#proc-metrics-deploying-prometheus-operator-str).

**Comment by stanlyDoge** [comment]
1. You can take a look at [additional scrape configuration](https://github.com/coreos/prometheus-operator/blob/d37bc833ab4691fe67e17da69893f8a314728eed/Documentation/additional-scrape-config.md). It takes whatever you put there and uses that for Prometheus configuration. So you can just copy your job to [this file](https://github.com/strimzi/strimzi-kafka-operator/blob/master/metrics/examples/prometheus/additional-properties/prometheus-additional.yaml), recreate  the secret and you should be ready to go.

2. Can you doublecheck you are using the correct namespace?

**Comment by scholzj** [comment]
@soheilade Can this be closed? Or do you have something more to this?

**Comment by ningjunwei2** [comment]
这个问题怎么解决的，我也碰到了

**Comment by ningjunwei2** [comment]
how to solve this problem？
