### ISSUE TITLE
[Question] ... I would like to map my pre-created PVC.

### ISSUE THREAD

**Issue by shivabommakanti03** [strimzi/strimzi-kafka-operator#1931]
I already created PVC for my cluster and I would like to use that but when I add volumes tag to strimzi yaml file it throws error and if i remove my changes and re-run it it creates it's own PVC and I cannot assign it to my label name. Please help me with this.

I am using strimzi operator for the first time.

**Comment by scholzj** [comment]
The only way you can create your own PVCs is that you name them in the same way as the PVCs which would be created by the Strimzi operator. In that case they will be simply reused. This is because of how StatefulSets work. They do not let us define the PVC names but always generate them from the StatefulSet name.

**Comment by scholzj** [comment]
TBH, I'm not entirely sure what exactly and how did you changes the metadata. Did you changed the name of the Kafka CR from let's say `my-cluster` to something else? That should cause the names of the secrets and service account to change. But IMHO you cannot rename the CRD - you have to delete the old one and create the new one. So was the old one deleted?

**Comment by scholzj** [comment]
Have you tried this to configure the StorageClass? https://strimzi.io/docs/latest/full.html#ref-persistent-storage-deployment-configuration-kafka

It should look like this:

```yaml
# ...
storage:
  type: persistent-claim
  size: 1Gi
  class: my-storage-class
# ...
```

**Comment by scholzj** [comment]
So, can we close this?

**Comment by shivabommakanti03** [comment]
@scholzj Sorry to reopen this issue. I am facing another issue with PVC. I used class and it worked but seems like strimzi is creating additional PVCs which I am not sure why. Can you please help

**Comment by scholzj** [comment]
Could you share the list of your PVCs? And the KAfka CR you use to deploy the cluster?

**Comment by shivabommakanti03** [comment]
I was able to find that out. But, another issue came up. Kafka brokers cannot bound to storage class name. I am attaching my code here please check.

`apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-loc
spec:
  kafka:
    replicas: 3
    version: 2.3.0
    jvmOptions:
      -Xms: 128m
    listeners:
      tls: {}
      plain: {}
      external:
        selector:
          statefulset.kubernetes.io/pod-name: kafka-loc-0
          strimzi.io/cluster: kafka-loc
          strimzi.io/kind: Kafka
          strimzi.io/name: kafka-loc
        type: loadbalancer
        tls: false
    config:
      #auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-shared-5gi
      deleteClaim: false
  zookeeper:
    replicas: 3
    jvmOptions:
      -Xms: 128m
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-shared-5gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
`

**Comment by scholzj** [comment]
Thsi looks ok. Could you do `kubectl describe` on the PVCs it created?

**Comment by shivabommakanti03** [comment]
Here is the output

```(base) TXMACL05SB878F:skafka sb878f$ kubectl describe pvc data-kafka-loc-kafka-0
Name:          data-kafka-loc-kafka-0
Namespace:     com-att-fraudml-stream-dev
StorageClass:  local-shared-5gi
Status:        Pending
Volume:
Labels:        strimzi.io/cluster=kafka-loc
               strimzi.io/kind=Kafka
               strimzi.io/name=kafka-loc-kafka
Annotations:   strimzi.io/delete-claim: false
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  WaitForFirstConsumer  3m51s (x45 over 13m)  persistentvolume-controller  waiting for first consumer to be created before binding```

**Comment by scholzj** [comment]
Ok - and when you do the same (`kubectl describe`) for the Kafka StatefulSet / Pod 0?

**Comment by shivabommakanti03** [comment]
It worked after I remove this part from the code. I am not sure what's wrong in that part of the code.

``` external:
        selector:
          statefulset.kubernetes.io/pod-name: kafka-loc-0
          strimzi.io/cluster: kafka-loc
          strimzi.io/kind: Kafka
          strimzi.io/name: kafka-loc
        type: loadbalancer
        tls: false```

**Comment by scholzj** [comment]
Wait - from where did you removed it?

**Comment by shivabommakanti03** [comment]
If you look my previous code that I commented here (kafkapv). I delete this block from that.

**Comment by scholzj** [comment]
Ahh, ok. I didn't noticed that - I looked only on the storage. But yeah, this is not part of the CRD, so it should not be there. The service selector is configured automatically.

**Comment by shivabommakanti03** [comment]
This is what I am trying to achieve in in my case.

https://strimzi.io/docs/latest/full.html#con-accessing-kafka-bridge-from-outside-str

``` # ...
  selector:
    strimzi.io/cluster: kafka-bridge-name (1)
    strimzi.io/kind: KafkaBridge
  #...```

**Comment by scholzj** [comment]
You have to create your own service and use this selector inside it. Not in the Kafka CR. I.e. directly

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    # ...
  selector:
    strimzi.io/cluster: kafka-bridge-name
    strimzi.io/kind: KafkaBridge
  # ...
```

**Comment by shivabommakanti03** [comment]
I am sorry for all of this but I must of conveyed wrongly. So the above file which I shared is my kafka persistent volume file. Even in this case we don't need them?

**Comment by scholzj** [comment]
What exactly do you mean with the _kafka persistent volume file_? The Kafka Custom resource? That is needed to deploy Kafka cluster (+ Zookeeper). If you configure the load balancer there it will only for Kafka it self using Kafka protocol.

If you want to use the HTTP Bridge, you deploy it using the KafkaBridge resource. And if you want to expose that, you can write your own service. Unlike Kafka, the HTTP Bridge is a regular HTTP protocol which is easy to expose and does not need any special support from the operator.

**Comment by shivabommakanti03** [comment]
Sorry @scholzj for this late response. Thanks for all the help it worked well. I do have one last question. I am using the below part of the code in my kafka yaml to use external load balancer of K8s.

```listeners:
      tls: {}
      plain: {}
      external:
        selector:
          statefulset.kubernetes.io/pod-name: kafka-loc-0
          strimzi.io/cluster: kafka-loc
          strimzi.io/kind: Kafka
          strimzi.io/name: kafka-loc
        type: loadbalancer
        tls: false```

I tested the same part of the code and it automatically picked up external IP where as in my case (private cloud) it didn't pick any external IP. Do we have to mention IPs here?

**Comment by scholzj** [comment]
So, first of all, the whole `selector` section will be completely ignored by the operator. We always try to pickup the address of the loadbalancers which are created from the `Status` section of the `Service` resource. But this is a bit different cloud provider by cloud provider etc. If your service does not have the address there, we cannot really automatically detect it. In such case, you can enter it manually in the `Kafka` custom resource. Please have a look at the [docs](https://strimzi.io/docs/latest/full.html#con-kafka-broker-external-listeners-addresses-deployment-configuration-kafka) - in your case you will need to use the `type: loadbalancer` and specify the addresses for the different loadbalancers for each node.

**Comment by scholzj** [comment]
@shivabommakanti03 Can this be closed? Or do you have something more to this?

**Comment by shivabommakanti03** [comment]
Yes. This can be closed. Thanks for your help :)
