### ISSUE TITLE
[Bug] Mirror Maker takes to long for readinessProbe:

### ISSUE THREAD

**Issue by ennala** [strimzi/strimzi-kafka-operator#1933]
I am setting up mirror maker for our existing clusters. I though of using some recent fixes for mirror maker and deployed master branch.

Mirror makes takes too long around 5 mins to become ready. I could not find any specific error in the logs .. except below log.

```
2019-08-28 05:49:24,979 ERROR Could not delete readiness indicator file /tmp/mirror-maker-ready (io.strimzi.mirrormaker.agent.MirrorMakerAgent) [ReadinessPoller]
2019-08-28 05:49:29,979 ERROR Could not delete readiness indicator file /tmp/mirror-maker-ready (io.strimzi.mirrormaker.agent.MirrorMakerAgent) [ReadinessPoller]
2019-08-28 05:49:34,979 ERROR Could not delete readiness indicator file /tmp/mirror-maker-ready (io.strimzi.mirrormaker.agent.MirrorMakerAgent) [ReadinessPoller]
2019-08-28 05:49:39,980 ERROR Could not delete readiness indicator file /tmp/mirror-maker-ready (io.strimzi.mirrormaker.agent.MirrorMakerAgent) [ReadinessPoller]
2019-08-28 05:49:44,980 ERROR Could not delete readiness indicator file /tmp/mirror-maker-ready (io.strimzi.mirrormaker.agent.MirrorMakerAgent) [ReadinessPoller]
```

I did not had the problem when I deployed 0.13.0 release.

**Comment by scholzj** [comment]
Could you share the whole log file please?

**Comment by scholzj** [comment]
First of all, the new readiness and liveness probe is only in master. So I do not think you are using 0.13.0 but master.

From the log I see two issues:
1) The `Could not delete readiness indicator file` erorr is a simple bug. I opened #1942 to fix it.
2) However, your log makes me curious why do you have this error. It is printed when the Mirror Maker is not ready which should happen when it is not connecter to either the source or the target broker. Can you confirm that in this log your Producer / target cluster is not connected?

Also, when you say _I also used recently added probes which does not seem to work._ - what exactly do you mean? That the `readinessProbe` and `livenessProbe` are ignored?

PS: The name of the Mirror Maker logger is `mirrormaker.root.logger`. So you need to use something liek this:

```yaml
  logging:
    type: inline
    loggers:
      mirrormaker.root.logger: "DEBUG"
```

**Comment by ennala** [comment]
@scholzj  

Yes I installed master.

It did mirror all the messages in the test topic .. which indicates it was connected. I will cross it one more time today.

Yeah ... I meant to say  `readinessProbe` and `livenessProbe`.

Thanks I will update my logging config.

**Comment by scholzj** [comment]
> It did mirror all the messages in the test topic .. which indicates it was connected. I will cross it one more time today.

If you think it was connected and should have been ready ... could you try that with tracing for the readiness agent to help debug why was it not ready? Thanks.

```yaml
  logging:
    loggers:
      log4j.logger.io.strimzi.mirrormaker.agent: TRACE
      mirrormaker.root.logger: INFO
```

**Comment by ennala** [comment]
For some reason I am not able to reproduce this today after multiple attempts. Could be a problem with by brokers. Sorry for the trouble.
