### ISSUE TITLE
Show status output in `kubectl get k -w`

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1939]
I had a quick look at doing this just now, but it doesn't really work very well:

* https://github.com/kubernetes/kubernetes/issues/66538 means doesn't work with `-w`.
* even without -w https://github.com/kubernetes/kubernetes/issues/20352 means you can't have `Ready`/`NotReady` only `Ready`/_blank_. In principle this could be solved by having a single field within the status which we could query with the jsonpath, but it's not worth changing the status schema just for this feature.

So I don't think this is really worthwhile at the moment, but I'm opening this issue because I think this would be nice to add in the future once kubernetes supports it better.

**Comment by scholzj** [comment]
This should be done in #3968
