### ISSUE TITLE
Enable DCO on all Strimzi repos

### ISSUE THREAD

**Issue by caniszczyk** [strimzi/strimzi-kafka-operator#1941]
This is required by CNCF's IP Policy, I installed it here:

https://github.com/organizations/strimzi/settings/installations/1697310

**Comment by scholzj** [comment]
DCO is installed and seems to work fine on all repositories. I think this can be closed. We also added it to our [HACKING.md](https://github.com/strimzi/strimzi-kafka-operator/blob/master/HACKING.md#dco-signoff) guide. I think this can be now closed.
