### ISSUE TITLE
[Doc] Configuring Zookeeper connection timeout is allowed in Kafka broker configuration

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1954]
The Kafka broker configuration section mentions some parameters (starting with specific prefixes) that cannot be modified by the user in the CRD (`config` section) https://strimzi.io/docs/master/#ref-kafka-broker-configuration-deployment-configuration-kafka
It mentions all parameters starting with `zookeeper.connect` but doesn't mention that the specific `zookeeper.connection.timeout.ms` is an exception so the user can configure it.

**Comment by scholzj** [comment]
Done in #3367
