### ISSUE TITLE
[Enhancement] Use dynamic broker reconfiguration where possible

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1977]
**Is your feature request related to a problem? Please describe.**
Currently the CO will perform a rolling restart of the Kafka cluster every time the broker config in the CR is changed. This causes controller and leader elections which will impact clients for example causing latency spikes.

**Describe the solution you'd like**
Kafka has supported dynamic broker reconfiguration since version 1.1. The CO should use this API instead of using broker restart whenever the change in configs doesn't require a restart.

**Describe alternatives you've considered**
Do nothing, needlessly inflicting the consequences on to client apps.

**Comment by tomncooper** [comment]
Can this issue be closed now?

**Comment by tombentley** [comment]
No, this one is still very much alive.

**Comment by scholzj** [comment]
@tombentley Is it still true that it is alive? We seem to have the dynamic configuration now.

**Comment by tombentley** [comment]
Yes, let's close this. It would, of course, be good to support dynamic reconfig is various places where we don't currently support it, but it could in principal be used. I guess that includes certificate changes, and possibly some networking changes. But we should have specific issues for those.
