### ISSUE TITLE
[Bug] Remove the old certificates after a renewal of Cluster CA

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1979]
Currently, when the CA is renewed the old certificates remain in the secrets and in use until they expire. This potential security risk. We should clear the certificate once it is not needed (ie. once all components were moved to new certificates). 

This is not so easy with Clients CA where Strimzi does not control the clients connecting based on it. However, even in that case we should at least add a warning to the docs that users should remove the keys. This warning needs to be especially in the docs around the forced renewal which might be cause by the original certificates being compromised.

**Comment by PaulRMellor** [comment]
https://github.com/strimzi/strimzi-kafka-operator/pull/3486
