### ISSUE TITLE
Remove @OpenShiftOnly tests in SecurityST

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#1994]
The SecurityST uses OpenShift routes to enable external access (which is used in turn so we can check the continual availability for producers and consumers during the test). This means the test is OpenShift specific, though it needn't be (it's not testing OpenShift specific functionality). 

We should refactor the test to use some other external listener type to it can be run on Kube.

**Comment by scholzj** [comment]
@im-konge @tombentley Is this still valid? Or has it been solved?

**Comment by im-konge** [comment]
@scholzj this should be solved
