### ISSUE TITLE
[Bug] Changing replicas on kafkatopic does not provide a clear message in k8s events

### ISSUE THREAD

**Issue by komish** [strimzi/strimzi-kafka-operator#2025]
Pretty small issue here, just playing around with the interactions of the CRs. 

**Describe the bug**
From what I can see. changing the replication factor via changes to the `KafkaTopic` CR is unsupported. The topic-operator event log doesn't reflect this in an informative way, listing `java.lang.NullPointerException` as the message

**To Reproduce**

Kafka cluster deployed using the provided [yaml](https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka/kafka-ephemeral.yaml) in `examples/` from this repo.

```
$ oc create -f examples/kafka/kafka-ephemeral.yaml
	kafka.kafka.strimzi.io/my-cluster created
```

KafkaTopic initially deployed using the provided examples/` [yaml](https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/topic/kafka-topic.yaml). This creates `my-topic` with 1 replica and 1 partition.

```
$ oc create -f examples/kafka/kafka-ephemeral.yaml
	kafka.kafka.strimzi.io/my-cluster created
```

KafkaTopic modified to change replicas (from: 1, to: 3) which, from what I can tell, is an operation that _should_ fail currently if modified via the k8s object. 

```
$ oc apply -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
EOF
```

The kubernetes API accepts the request, and the entity-operator+topic-operator reports the failure as follows (line numbers for clarity):

```
     1	[2019-09-26 14:54:03,003] ERROR <opicOperator:612> [oop-thread-1] 8|kube =my-topic|4374026: Changes replication factor
     2	[2019-09-26 14:54:03,005] INFO  <nedKafkaImpl:89> [oop-thread-1] Changing replication factor of topic my-topic to 3
     3	[2019-09-26 14:54:03,026] INFO  <rocessHelper:43> [ker-thread-2] Started process java.lang.UNIXProcess@631b3317 with command line [/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64/jre/bin/java, -cp, lib/io.strimzi.topic-operator-0.13.0.jar:lib/io.netty.netty-codec-dns-4.1.34.Final.jar:lib/com.squareup.okhttp3.okhttp-3.12.0.jar:lib/com.101tec.zkclient-0.11.jar:lib/com.squareup.okio.okio-1.15.0.jar:lib/io.vertx.vertx-core-3.7.1.jar:lib/com.github.spotbugs.spotbugs-annotations-3.1.12.jar:lib/io.netty.netty-handler-proxy-4.1.34.Final.jar:lib/javax.validation.validation-api-2.0.1.Final.jar:lib/org.apache.zookeeper.zookeeper-3.4.14.jar:lib/com.fasterxml.jackson.core.jackson-core-2.9.9.jar:lib/io.netty.netty-transport-4.1.34.Final.jar:lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:lib/org.apache.kafka.kafka-clients-2.3.0.jar:lib/com.fasterxml.jackson.core.jackson-databind-2.9.9.1.jar:lib/org.apache.yetus.audience-annotations-0.5.0.jar:lib/io.fabric8.kubernetes-client-4.3.0.jar:lib/io.netty.netty-codec-socks-4.1.34.Final.jar:lib/io.fabric8.kubernetes-model-common-4.3.0.jar:lib/io.netty.netty-resolver-4.1.34.Final.jar:lib/io.netty.netty-codec-4.1.34.Final.jar:lib/org.apache.logging.log4j.log4j-slf4j-impl-2.11.1.jar:lib/com.github.mifmif.generex-1.0.2.jar:lib/io.strimzi.certificate-manager-0.13.0.jar:lib/com.fasterxml.jackson.dataformat.jackson-dataformat-yaml-2.9.9.jar:lib/org.apache.logging.log4j.log4j-api-2.11.1.jar:lib/com.google.code.findbugs.jsr305-3.0.2.jar:lib/org.slf4j.jul-to-slf4j-1.7.26.jar:lib/org.apache.logging.log4j.log4j-core-2.11.1.jar:lib/dk.brics.automaton.automaton-1.11-8.jar:lib/com.github.luben.zstd-jni-1.4.0-1.jar:lib/io.netty.netty-handler-4.1.34.Final.jar:lib/io.strimzi.api-0.13.0.jar:lib/io.fabric8.openshift-client-4.3.0.jar:lib/io.netty.netty-resolver-dns-4.1.34.Final.jar:lib/io.strimzi.operator-common-0.13.0.jar:lib/io.fabric8.zjsonpatch-0.3.0.jar:lib/org.lz4.lz4-java-1.6.0.jar:lib/io.netty.netty-buffer-4.1.34.Final.jar:lib/io.netty.netty-codec-http-4.1.34.Final.jar:lib/com.squareup.okhttp3.logging-interceptor-3.12.0.jar:lib/io.strimzi.crd-annotations-0.13.0.jar:lib/io.netty.netty-common-4.1.34.Final.jar:lib/io.fabric8.kubernetes-model-4.3.0.jar:lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.9.8.jar:lib/org.slf4j.slf4j-api-1.7.25.jar:lib/com.fasterxml.jackson.core.jackson-annotations-2.9.8.jar:lib/io.netty.netty-codec-http2-4.1.34.Final.jar:lib/org.yaml.snakeyaml-1.23.jar:lib/org.glassfish.javax.el-3.0.1-b11.jar, kafka.admin.ReassignPartitionsCommand, --zookeeper, localhost:2181, --topics-to-move-json-file, /tmp/io.strimzi.operator.common.process.ProcessHelper3957138059861484090-topics-to-move.json, --broker-list, 0,1,2, --generate]
     4	[2019-09-26 14:54:03,155] INFO  <rocessHelper:48> [ker-thread-2] Process java.lang.UNIXProcess@631b3317: exited with status 1
     5	[2019-09-26 14:54:03,162] ERROR <opicOperator:613> [oop-thread-1] Changing replication factor is not supported
     6	[2019-09-26 14:54:03,221] WARN  <opicOperator:106> [oop-thread-1] java.lang.NullPointerException
     7	[2019-09-26 14:54:03,226] INFO  <TopicWatcher:39> [oop-thread-1] 8|kube =my-topic|4374026: Success processing event MODIFIED on resource my-topic with labels {strimzi.io/cluster=my-cluster}
     8	2019-09-26T14:54:03.247+0000: 435.709: [Full GC (Metadata GC Threshold) 2019-09-26T14:54:03.247+0000: 435.709: [Tenured: 13222K->13601K(86016K), 0.0444552 secs] 19593K->13601K(124800K), [Metaspace: 34507K->34507K(1081344K)], 0.0445612 secs] [Times: user=0.04 sys=0.00, real=0.05 secs]
```

The reason `Changing replication factor is not supported` doesn't make it to the message in the event log:

```
LAST SEEN   TYPE      REASON                            OBJECT                                             MESSAGE
52m         Warning                                     kafkatopic/my-topic                                java.lang.NullPointerException
51m         Warning                                     kafkatopic/my-topic                                java.lang.NullPointerException
```

**Expected behavior**
The event log receives the message reported by the controller:

> Changing replication factor is not supported.

or something similar, potentially more verbose indicating that changing the replication factor _via the CR_ is not supported.

**Environment (please complete the following information):**

- Strimzi version: 0.13.0

```
$ oc get csv
NAME                               DISPLAY                         VERSION   REPLACES                           PHASE
strimzi-cluster-operator.v0.13.0   Strimzi Apache Kafka Operator   0.13.0    strimzi-cluster-operator.v0.12.2   Succeeded
```

- Installation method: OperatorHub
- Kubernetes cluster: OpenShift Container Platform 4.2

**YAML files and logs**

Should be provided inline above. Let me know if I can provide anything else.

**Additional context**
Looking at issues in repo, I see discussions about the replication factors in #191 and am understanding that how replication factor can mutate is being discussed (correct me if I'm wrong).

Initially it stemmed from an assumption that a cluster-scoped installation would not put an entity-operator outside of the "operator" namespace limiting user visibility as to _why_ the replication factor didn't change when declared. Since this was an incorrect assumption on my part, the user can simply look at the entity operator logs and see the issue which makes this a smaller "experience" problem.

This log adjustment is more of a quality-of-life improvement in the interim until #191 results in a change in how we interact with `KafkaTopic` replication factors.

**Comment by tombentley** [comment]
This should have been addressed in master and should be included in the forthcoming 0.14.0 release. Can you confirm that you saw this on 0.13.0 (or earlier)? If you want to try out the latest 0.14.0 RC you should find you get a meaningful error message.

**Comment by komish** [comment]
Confirmed, seeing this in 0.13.0. I'll try 0.14.0 shortly to confirm and close this out once I have.

**Comment by tombentley** [comment]
Great, thanks @komish

**Comment by komish** [comment]
Just more context, seeing similar with regards to partitions where increasing the number of partitions and then reducing that number (which we know is not a supported task) causes the KafkaTopic object to stay in the inconsistent state. 

It almost feels like it would be best validated before the change is accepted by the API server but I'm not sure what that would look like in implementation. Just adding some thoughts here as I poke at things.

Can move this to a separate bug (and close this one) if that helps contextually as the original intention of this bug (event object messages) is confirmed as good to go in the 0.14.x RC.

**Comment by tombentley** [comment]
@komish It's easier to just continue this issue than open a new one.

If you look at the `status` of the topic in these cases you should find the error message repeated there. Using `status` is the accepted way for an operator to feed back to the user about problems in honouring the configuration (the TO's support for events predates the support for status). If we just silently reverted the replicas we wouldn't be able to use `status` to inform the user why. And the user would likely know they'd not changed anything on the Kafka side, so this could be confusing. In general the principle is that the TO does not make changes itself (e.g. to try to fix things), it just tries to keep the `KafkaTopic` and topic in Kafka in sync with however they get changed, thus leaving the human operator in control (and not having to second guess what the TO is doing).

I think it's a better pattern for people to get into the habit of checking `status` when they make changes, because the operator can also use that in other error situations, so it's something they should do anyway to know for sure they their changes have been successful.

Finally, about your point about the API server: Since the TO uses CRDs the apiserver is not able to validate this itself (since it's really about how the CR has _changed_, rather than being a problem with a single CR "document"). In theory a validating webhook could be used for that, but those also have their drawbacks and it doesn't seem worthwhile just for this.

**Comment by komish** [comment]
Understood! Thanks for the explanation and discussion. Closing.
