### ISSUE TITLE
[Bug] Don't annotate services with prometheus.io annotations if metrics is disabled

### ISSUE THREAD

**Issue by joe-sch** [strimzi/strimzi-kafka-operator#2048]
**Describe the bug**
The annotations for prometheus on service objects, e.g. the kafka-bootstrap or zookeeper-client are set, even if monitoring is not configured (metrics nor kafka-exporter section is there). 
The problem is, that if there is a prometheus in this cluster, it tries to scrape metrics from these services, which will fail, and then prometheus marks these endpoints as down or unhealthy in its target overview.

**To Reproduce**
1. deploy ephemeral example
2. run command  `kubectl get svc my-cluster-kafka-bootstrap -o yaml`
3. See that there are annotations:
````
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9404"
    prometheus.io/scrape: "true"

````
But there is nothing on port 9404:
````

$ kubectl get svc my-cluster-kafka-bootstrap
NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
my-cluster-kafka-bootstrap   ClusterIP   10.104.125.241   <none>        9091/TCP,9092/TCP,9093/TCP   4m50s

````

**Expected behavior**
If metrics nor kafka_exporter is activated don't annotate services with prometheus.io annotation, or at least set  `prometheus.io/scrape: "false"`

**Environment (please complete the following information):**
 - Strimzi version: [e.g. 0.13.x and 0.14.0 ]
 - Installation method: [e.g. YAML files, Helm chart]
 - Kubernetes cluster: [Kubernetes 1.15]
 - Infrastructure: [Minikube, Kubernetes]

**Comment by scholzj** [comment]
Good point. Thanks for raising this.

**Comment by scholzj** [comment]
I opened a pull request to fix this. It should be in the 0.15.0 release.

**Comment by joe-sch** [comment]
Wow, that was fast! Thank you
