### ISSUE TITLE
[Question] Restricting rolebindings when deploying everything into the same ns

### ISSUE THREAD

**Issue by phhutter** [strimzi/strimzi-kafka-operator#2071]
Hi,

I would like to restrict the following permissions of the cluster operator.
https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/cluster-operator/020-ClusterRole-strimzi-cluster-operator-role.yaml

Just out of curiosity, do I need the following RBACs if everything (zookeeper,kafka etc) is located in the same namespace? - As far as i understand, 3 deploy methods exists (https://strimzi.io/docs/master/ 2.3.3 2.3.4 2.3.5). Does it make sense to create 3 different sets of configurations each of them with a minimal permission approach? 
```  
clusterrolebindings.rbac.authorization.k8s.io  []                 []              [get create delete patch update watch]
rolebindings.rbac.authorization.k8s.io          []                 []              [get create delete patch update]
networkpolicies.networking.k8s.io               []                 []              [get list watch create delete patch update]
networkpolicies.extensions                      []                 []              [get list watch create delete patch update]
```

does anyone know what this RBAC allows to do ?
```
routes.route.openshift.io/custom-host           []                 []              [get list create delete patch update]
```

I'm pretty sure there are other roles that aren't needed for a "Deploying the Cluster Operator to watch a single namespace". So far I have only compared the RBAC with the role "edit" and written down the "critical" permissions.

Another question; When we do need Networkpolicies but remove the privileges from the operator. - Is it possible to create the network policy in advance as a cluster admin or will the operator still trying to create the already existing policy and fails due to insufficient permissions? How does this actually work?

**Comment by scholzj** [comment]
> I'm pretty sure there are other roles that aren't needed for a "Deploying the Cluster Operator to watch a single namespace". So far I have only compared the RBAC with the role "edit" and written down the "critical" permissions.

The rights are needed for all the deployment modes. They are mostly unrelated to the amount of namespace which you are using. The difference there is the RoleBinding. For single namesapce mode it bings only to single namespace, for multiple namespaces you need to create one for each namesapce and for watching the whole cluster you need to create a ClusterRoleBinding.

Some of the rights might be needed only when you use some particular features, but that is unrelated to the installation modes.

> Another question; When we do need Networkpolicies but remove the privileges from the operator. - Is it possible to create the network policy in advance as a cluster admin or will the operator still trying to create the already existing policy and fails due to insufficient permissions? How does this actually work?

If you create the things before hand the operator will reuse them. But it will still be reconciling them (updating them) every loop to make sure they have the right configuration.So you can remove the create permission in such case, but not necessarily the other permissions.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.

**Comment by rk3rn3r** [comment]
@scholzj #3845 might help here, doesn't it?

**Comment by scholzj** [comment]
@rk3rn3r It does as long as you are fine with the disabled features not available in that mode: rack awareness, access using node ports or storage resizing. These features need cluster wide permissions due to Kubernetes RBAC design.

**Comment by ntrvic** [comment]
Following up here -- My Strimzi clusters have been integrated into our k8s RBAC system and have all the necessary permissions to perform actions like rack awareness, node ports, etc w/o Strimzi's need to create and manage other clusterRoleBindings. However I see no way around to the operator wanting to create or patch new CRBs. Is there anyway around this granted we really do not need Strimzi managing our CRBs for us?

**Comment by scholzj** [comment]
It needs to create the Cluster Role Bindings because some of these rights are granted to the operands which are deployed by the operator. They are not needed only by the operator. If you do not want it to manage the CRBs, you can avoid using the features which require them such as node-ports or rack-awareness.

**Comment by ntrvic** [comment]
Thanks for the quick response! :) I have been trying to grant the operator the rights to managing "specific CRBS" --

```
- apiGroups:
    - "rbac.authorization.k8s.io"
  resources:
    - clusterrolebindings
  # The strimzi operator needs patch and update rights to the clustrolebindings under the following names.
  resourceNames:
    - "strimzi-kafka-events-kafka-kafka-init"
  verbs:
    - "*"
 ```
But to no avail as I am still seeing -- 

```
io.vertx.core.impl.NoStackTraceThrowable: Failure executing: PATCH at: https://******/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/strimzi-kafka-events-kafka-kafka-init. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. clusterrolebindings.rbac.authorization.k8s.io "strimzi-kafka-events-kafka-kafka-init" is forbidden: User "system:serviceaccount:strimzi-operator:database-operator" cannot patch resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope.
````

`strimzi-kafka-events-kafka-kafka-init` was the CRB that strimzi-operator wanted to create, so I passed that step by creating is, but now it wants to PATCH the CRB b/c it doesn't like the the annotations provided during deploy. 

This might be more of a Kubernetes issue, but any insights would help here.

**Comment by scholzj** [comment]
IIRC you cannot use resource names for `create` operations. Not completely sure whether having it that way in one rule would cause the patch error as well. 

> edit: Just wanted to add that getting cluster-wide access like this is a pretty big ask for a larger org, so I've needed to find some workaround ( creating CRBs that strimzi needs, etc) to get past previous issues
edit2: We are becoming heavy users of Strimzi so we really do need the rack awareness feature :)

If there was some better way to do it, we would have done it. Why do you trust Strimzi to operate your Kafka cluster if you don't trust it to delegate the right to read the nodes of your Kubernetes cluster?

**Comment by ntrvic** [comment]
We have no problem granting the Strimzi service account access to read the nodes, and in fact we do give it those rights ( for that particular SA). However granting Strimzi's SA the right to create/path/update clusterRoleBindings seems like a bit of a security vulnerability. Strimzi aside, any SA that has that right could do something like "bind admin ClusterRole to any SA" essentially letting that user do anything they wanted with the cluster.

**Comment by scholzj** [comment]
> Strimzi aside, any SA that has that right could do something like "bind admin ClusterRole to any SA" essentially letting that user do anything they wanted with the cluster.

Ok, but that is not true. Just because you can create ClusterRoleBinding, it does not mean you can grant someone the cluster-admin role. Kubernetes has privilege escalation protection. You can create CRB only with the rights you have your self. So essentially, Strimzi can give only the rights it already has -> for example to get nodes or get storage classes. But it cannot give the rights it does not have such as deleting or creating nodes for example. https://kubernetes.io/docs/reference/access-authn-authz/rbac/#restrictions-on-role-binding-creation-or-update

**Comment by ntrvic** [comment]
@scholzj thank you for clarifying this bit 🙌 much appreciated.
