### ISSUE TITLE
Revert changes from #1212

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#2072]
The issue in kubernetes (https://github.com/kubernetes/kubernetes/issues/68466) which was addressed in https://github.com/strimzi/strimzi-kafka-operator/issues/1212 has been fixed, so once our CI is using a fixed version of kube we should be able to revert those changes.

**Comment by scholzj** [comment]
For the record: https://github.com/kubernetes/kubernetes/pull/76124#issuecomment-541004588

Also, thsi was fixed in 1.16 - so we should probably enable it only after we support onyl versions newer than 1.16. otherwise this migth be failing for users running the tests against older versions.

**Comment by scholzj** [comment]
Correction -> this is fixed only in 1.17 in kubernetes/kubernetes#85223 ... so we cannot fix it yet since we support 1.16 as well.

**Comment by scholzj** [comment]
Triaged on 3.3.2022: We still support Kube 1.16, so we should keep it for the future. We should have discussion about dropping some old Kube versions on the next community call.
