### ISSUE TITLE
[Task] Check api requirement for Serializable.

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#2075]
Per comment on https://github.com/strimzi/strimzi-kafka-operator/pull/2073#discussion_r333966441 we should check whether API classes inheriting `Serializable` is still necessary and remove it if not.

**Comment by scholzj** [comment]
Triaged on 3.3.2022: We should doublecheck this -> remove the Serializable check from the CRD generator and remove serializable from the API classes and see if everything works.

**Comment by antonio-pedro99** [comment]
@scholzj can I take a look at this one?

**Comment by antonio-pedro99** [comment]
@scholzj I am applying for the LFX mentorship (@ppatierno and @kyguy are the mentors) and I would like to get started on Strimzi to get exposed to it.

**Comment by scholzj** [comment]
@antonio-pedro99 Yeah, sure ... why not.

**Comment by antonio-pedro99** [comment]
@scholzj could you assign it to me?
