### ISSUE TITLE
Kafkaconenct plugins not working using confluent MQTT connectors build using openshift source2image 

### ISSUE THREAD

**Issue by ankit302** [strimzi/strimzi-kafka-operator#2078]
Running kafka in Distributed env using REST API - Kafka MQTT connector is not able to recognise the class that implements connectors,

Mqtt connector plugins are build and required jars are present in /tmp/kafka-plugins/s2i/kafkaconnect/ ** 

curl -s -X POST -H 'Content-Type: application/json' --data @MqttSourceConnector1.json http://localhost:8083/connectors

{"name":"mqtt-source","config":{"connector.class":"io.confluent.connect.mqtt.MqttSourceConnector","tasks.max":"1","mqtt.server.uri":"tcp://broker.hivemq.com:1883","mqtt.topics":"fgdciot/machine1","confluent.topic.bootstrap.servers":"localhost:9092","name":"mqtt-source"},"tasks":[],"type":null}

 

getting error on running:
{"error_code":500,"message":"Failed to find any class that implements Connector and which name matches io.confluent.connect.mqtt.MqttSourceConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSinkConnector, name='org.apache.kafka.connect.file.FileStreamSinkConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.file.FileStreamSourceConnector, name='org.apache.kafka.connect.file.FileStreamSourceConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockConnector, name='org.apache.kafka.connect.tools.MockConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=connector, typeName='connector', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='2.0.0.redhat-00003', encodedVersion=2.0.0.redhat-00003, type=source, typeName='source', location='classpath'}"}sh-4.2$ [dsadmin@cn-sdp-lab-ocp-bastion ~]

**Comment by scholzj** [comment]
The connector plugin is not listed in the available connectors. So KAfkaConnect didn't recognized it. Either it is missing - maybe just some JARs - or it is copied in a wrong folder.

**Comment by ankit302** [comment]
Connector plugins are present at location, which i build using openshift s2i option;

/tmp/kafka-plugins/s2i/confluentinc-kafka-connect-mqtt-1.2.3
sh-4.2$ ls -lrt
total 7080
-rw-r--r--. 1 jboss root   68545 Oct 11 11:10 protobuf-java-util-3.4.0.jar
-rw-r--r--. 1 jboss root 1383882 Oct 11 11:10 protobuf-java-3.4.0.jar
-rw-r--r--. 1 jboss root  217453 Oct 11 11:10 org.eclipse.paho.client.mqttv3-1.2.0.jar
-rw-r--r--. 1 jboss root    1169 Oct 11 11:10 manifest.json
-rw-r--r--. 1 jboss root   25849 Oct 11 11:10 kafka-connect-mqtt-1.2.3.jar
-rw-r--r--. 1 jboss root  257897 Oct 11 11:10 jose4j-0.6.1.jar
-rw-r--r--. 1 jboss root  125632 Oct 11 11:10 jaxb-api-2.3.0.jar
-rw-r--r--. 1 jboss root 2442625 Oct 11 11:10 guava-20.0.jar
-rw-r--r--. 1 jboss root  231952 Oct 11 11:10 gson-2.7.jar
-rw-r--r--. 1 jboss root 1493680 Oct 11 11:10 freemarker-2.3.25-incubating.jar
-rw-r--r--. 1 jboss root  132509 Oct 11 11:10 connect-utils-0.3.140.jar
-rw-r--r--. 1 jboss root   12041 Oct 11 11:10 connect-licensing-extensions-0.2.2.jar
-rw-r--r--. 1 jboss root  811691 Oct 11 11:10 confluent-serializers-new-5.0.0.jar
-rw-r--r--. 1 jboss root   19954 Oct 11 11:10 confluent-licensing-new-5.0.0.jar

I can see the required plugins, when i list the available plugins,

sh-4.2$ curl -s localhost:8083/connector-plugins
[{"class":"io.confluent.connect.mqtt.MqttSinkConnector","type":"sink","version":"0.0.0.0"},{"class":"io.confluent.connect.mqtt.MqttSourceConnector","type":"source","version":"0.0.0.0"},{"class":"org.apache.kafka.connect.file.FileStreamSinkConnector","type":"sink","version":"2.0.0.redhat-00003"},{"class":"org.apache.kafka.connect.file.FileStreamSourceConnector","type":"source","version":"2.0.0.redhat-00003"}]sh-4.2$


This could be due to version mismatch of Kafka -  i mean kafka from strimzi & connector plugins from kafka connect ?

**Comment by scholzj** [comment]
That is interesting. But I'm not sure I can help. I'm not sure what the requirements of the connector are. It is also quite strange that it reports the version as `0.0.0.0`. MAybe you can try to update to latets Strimzi which has newer Kafka version.

**Comment by ankit302** [comment]
this issue is resolved , actually newly modified container image ( image with custom libs build using Source to image -openshift functionality)  is not used by kafka connect container that's why plugins.path was still pointing to /opt/kafka-plugins instead of /tmp/kafka plugin.

Once kafka connect container is re-deployed with newly modified local registry image it worked like charm...
