### ISSUE TITLE
[Enhancement] NodeSelectors and affinity rules for kafka/zookeeper

### ISSUE THREAD

**Issue by zivi-dodis** [strimzi/strimzi-kafka-operator#2095]
**Is your feature request related to a problem? Please describe.**
We need the ability to schedule kafka/zookeeper on specific nodes.

**Describe the solution you'd like**
The ability to specify NodeSelectors for all resources created by the operator.

**Describe alternatives you've considered**
This could be solved using a [PodNodeSelector](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector) AdmissionController this feature is sadly not supported by many cloud providers. 

**Additional context**
* https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#podnodeselector
* https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

**Comment by scholzj** [comment]
Is there any use-case where you actually need node-selector? You can configure tollerations and affinity which should IMHO cover all needs (node affinity should be able to cover for node-selector). You can configure these on all resources (Kafka, Zoo, etc.) already today.

**Comment by zivi-dodis** [comment]
Right. Closing for being too dumb to RTFM... link for all people just passing by: https://strimzi.io/docs/latest/#assembly-node-scheduling-deployment-configuration-kafka-node-scheduling
