### ISSUE TITLE
[Enhancement] Support for specifying custom schedulers

### ISSUE THREAD

**Issue by ravitandonrt** [strimzi/strimzi-kafka-operator#2106]
**Is your feature request related to a problem? Please describe.**
I would like to specify a custom pod scheduler that takes in account the storage when doing pod placement. We are currently evaluating Portworx that provides a storage overlay in Kubernetes so that we could use the NVMe instance store (AWs EKS with i3en instances) to provision PVCs for Kafka. Their scheduler `stork` takes into account the location of the storage replicas in pod placement which improves latency and throughput.

Reference to stork: https://github.com/libopenstorage/stork

**Describe the solution you'd like**
Ability to specify `schedulerName` in the stateful set template for Kafka custom resource.

This is how the Portworx solution specifies their scheduler: https://docs.portworx.com/portworx-install-with-kubernetes/application-install-with-kubernetes/kafka-with-zookeeper/#install-kafka

**Describe alternatives you've considered**
By using the regular scheduler and Portworx with Strimzi we were not able to get a good throughput. I temporarily used the Yolean kubernetes-kafka distribution to get better numbers for Portworx.

**Additional context**
I noticed that `schedulerName` has been removed from the stateful set diff here: https://github.com/strimzi/strimzi-kafka-operator/blob/master/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/StatefulSetDiff.java#L43
I will make an attempt to change the code, but wanted to consult if there is a better direction to take here or if this has been intentionally left out at this time.

**Comment by scholzj** [comment]
TBH, I'm not sure how does this work and why would it help. But I guess adding it might be fairly simple. I will add it to my TODO list and try to look at it.

**Comment by ravitandonrt** [comment]
Thanks for the quick turnaround @scholzj , very happy and impressed. I was working on similar change but at cluster template level, pod template level change makes much more sense. I will give this is a swing later today and get back with results. Cheers!
