### ISSUE TITLE
[Enhancement] Ability to configure TLS certificates for Kafka Client

### ISSUE THREAD

**Issue by kameshsampath** [strimzi/strimzi-kafka-operator#2113]
Currently when using TLS with Kafka, I am not able to make Kafka use the valid SSL certificate. Say example if I configure my Kubernetes or OpenShift cluster to use letsencrypt, then I need to do something like what described in https://strimzi.io/2019/04/30/accessing-kafka-part-3.html for access over TLS.

cc: @scholzj

**Comment by nimmichele** [comment]
Using letsencrypt certificate I have to add this:

**Comment by scholzj** [comment]
Triaged on 3.3.2022: Done in the form of the listener certificate. We have a blog on the Strimzi website describing how to use it with Cert-Manager and Let's Encryrt.
