### ISSUE TITLE
Moving to nested structure for Strimzi operator in Operator Hub and OperatorHub.io

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#2125]
In order to have the next Strimzi release (0.15.0) on the OperatorHub.io website and as community operator in the Operator Hub in OCP 4.x, we need to move from a flat directory structure to the nested one (see https://github.com/operator-framework/community-operators/blob/master/docs/contributing.md#create-a-bundle) on the https://github.com/operator-framework/community-operators repo.
Referring to this issue https://github.com/operator-framework/community-operators/issues/804, the flat structure is now obsolete and new PRs won't be accepted using that way.

**Comment by scholzj** [comment]
Thsi has been already done in the community operators.
