### ISSUE TITLE
Part of Source code is missing: io.strimzi.api.kafka.model.status.ConditionBuilder

### ISSUE THREAD

**Issue by EresZX** [strimzi/strimzi-kafka-operator#2139]
strimzi-kafka-operator version 0.14.0
        When I read the source code, I find that in the package

        io.strimzi.operator.cluster.operator.assembly
 the class KafkaAssemblyOperator imports many classes from package  
        
        io.strimzi.api.kafka.model
but I can't find them in the package.
        These classes include:

        io.strimzi.api.kafka.model.DoneableKafka;
        io.strimzi.api.kafka.model.KafkaBuilder;
        io.strimzi.api.kafka.model.status.ConditionBuilder;
        io.strimzi.api.kafka.model.status.ListenerAddressBuilder;
        io.strimzi.api.kafka.model.status.ListenerStatusBuilder;
I don't understand why the missing of them does not affect the use and deployment of the operator.I want to modify the source code, this condition may result in the failure of the modified source code.

**Comment by scholzj** [comment]
This is a code which is generated at build time. You have to build the project to have it generated. The code is generated from the code inside the `api` module. In most cases, if you want to change something in these classes, you change it in the `api` module classes and regenerate the generated classes.

**Comment by EresZX** [comment]
Thank you very much!

**Comment by scholzj** [comment]
I will close this issue - feel free to re-open it or comment on it if you have any further questions. Thanks.
