### ISSUE TITLE
[Question] Warnings and Errors after upgrade to 0.14.0

### ISSUE THREAD

**Issue by jslusher** [strimzi/strimzi-kafka-operator#2147]
I upgraded my operator from 0.13.0 to 0.14.0 and I'm seeing the following logs repeated from the operator pod:

```
 ERROR ClusterOperator:88 - Watcher closed with exception in namespace kafka
io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 124242894 (131000860)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:254) [io.fabric8.kubernetes-client-4.3.0.jar:?]
	...
	...
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

```
WARN  AbstractAssemblyOperator:106 - Kafka resource platform in namespace kafka: Contains object at path spec.zookeeper.template.pod with an unknown property: spec
```

I have a running kafka cluster with a couple of connectors in a `kafka` namespace. I can't tell if the operator is still controlling it or if I need to rectify the errors above. Is there a way I can verify the operator is still controlling the cluster?

**Comment by scholzj** [comment]
As for the first error: I saw it few times, but not as a general issue. I think it might have been related to some bug / behavior in specific Kubernetes version. What environment are you runnign it in?

As for the second, that is just a warning. It says that in your Kafka resource, you have specified something on the path `path spec.zookeeper.template.pod.spec` what the operator doesn't support. It is just a warning for you to know that this field is ignored. On its own it is normally not a problem, but it always a bit depends what did you expected to configure. In theneral the `template` fields support only selected fields. Not any general specification.

**Comment by jslusher** [comment]
Here's my Kubernetes version info:
```
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jslusher** [comment]
The errors don't seem to be affecting the operator's ability to manage the brokers or connectors so I guess it's fine. I'll also note that I rebuilt one of these clusters from scratch and after I did that, the Exception went away, but the warning still logs with each reconciliation.
