### ISSUE TITLE
[Enhancement] Add the option of running Strimzi using the minimal RedHat Universal Base Image

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#2152]
The RedHat Universal Base image is a stripped down version of the RedHat Enterprise Linux operating system: https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

I propose we add support for running Strimzi using UBI as the base OS for all images. It would plug into the current functionality provided by Strimzi where you can build alternative images using the make envar `ALTERNATE_BASE=<image_subdirectory>` in this case it would be `ALTERNATE_BASE=ubi`.

I currently have a first pass at implementing this and will be hoping to contribute it shortly providing the community is happy with this. I have also tested that these new images pass RedHat Certification: https://connect.redhat.com/content/certify-your-container

**Comment by tallaxes** [comment]
@samuel-hawker, any insight on why this was closed? Supporting UBI for base does appear to make sense here ...

**Comment by samuel-hawker** [comment]
Hello! So essentially I had a small discussion with the maintainers at that time and it was decided that they didn't want to support and test both a centos base and a UBI base. There is functionality in Strimzi to be able to curate your own versions of the images discussed in this issue but currently there is no open source UBI version of these images.
