### ISSUE TITLE
strimzi-kafka pods failing on openshift and not able to attach existing persistent volume | Crash Loop Back-off

### ISSUE THREAD

**Issue by ritxos** [strimzi/strimzi-kafka-operator#2185]
**Images used -**
strimzi/operator                                  0.13.0
strimzi/kafka                                     0.13.0-kafka-2.3.0
strimzi/kafka-bridge                              0.13.0

**Below is the output from openshift cli-**
$ oc get pods
NAME                                       READY     STATUS             RESTARTS   AGE
cis-kafka-cluster-kafka-0                  1/2       CrashLoopBackOff   10         32m
cis-kafka-cluster-kafka-1                  2/2       Running            0          32m
cis-kafka-cluster-kafka-2                  1/2       CrashLoopBackOff   10         32m
cis-kafka-cluster-zookeeper-0              2/2       Running            0          33m
cis-kafka-cluster-zookeeper-1              2/2       Running            0          33m
cis-kafka-cluster-zookeeper-2              2/2       Running            0          33m
strimzi-cluster-operator-b9d48ddbf-qxtnc   1/1       Running            1          8d

**yaml specs-**

apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      external:
        type: nodeport
        tls: false
        overrides:
          bootstrap:
            nodePort: 22100
          brokers:
          - broker: 0
            nodePort: 22000
          - broker: 1
            nodePort: 22001
          - broker: 2
            nodePort: 22002
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: persistent-claim
      class: glusterfs-storage
      size: 1000Gi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 150Gi
      class: glusterfs-storage
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

**kAdditional Info**

(working fine for almost a month, tried recreating pods using same persistent storage so that there is no data loss, but experience same behaviour -- **surprisingly one of the kafka pods gets 2/2 checks passed and running well** without the logs shown on other two kafka pods
(zk cluster is normal)

**Logs-**

2019-11-13 12:56:19,389 INFO [ThrottledChannelReaper-Produce]: Starting (kafka.server.ClientQuotaManager$ThrottledChannelReaper) [ThrottledChannelReaper-Produce]
  | 2019-11-13 12:56:19,390 INFO [ThrottledChannelReaper-Request]: Starting (kafka.server.ClientQuotaManager$ThrottledChannelReaper) [ThrottledChannelReaper-Request]
  | 2019-11-13 12:56:19,425 INFO Log directory /var/lib/kafka/data/kafka-log0 not found, creating it. (kafka.log.LogManager) [main]
  | 2019-11-13 12:56:19,426 ERROR Failed to create or validate data directory /var/lib/kafka/data/kafka-log0 (kafka.server.LogDirFailureChannel) [main]
  | java.io.IOException: Failed to create data directory /var/lib/kafka/data/kafka-log0
  | at kafka.log.LogManager.$anonfun$createAndValidateLogDirs$1(LogManager.scala:158)
  | at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  | at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  | at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  | at kafka.log.LogManager.createAndValidateLogDirs(LogManager.scala:149)
  | at kafka.log.LogManager.<init>(LogManager.scala:80)
  | at kafka.log.LogManager$.apply(LogManager.scala:1022)
  | at kafka.server.KafkaServer.startup(KafkaServer.scala:242)
  | at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
  | at kafka.Kafka$.main(Kafka.scala:84)
  | at kafka.Kafka.main(Kafka.scala)
  | 2019-11-13 12:56:19,430 ERROR Shutdown broker because none of the specified log dirs from /var/lib/kafka/data/kafka-log0 can be created or validated (kafka.log.LogManager) [main]
  | Heap
  | garbage-first heap   total 131072K, used 26008K [0x0000000082000000, 0x0000000082400100, 0x0000000800000000)
  | region size 4096K, 5 young (20480K), 1 survivors (4096K)
  | Metaspace       used 22650K, capacity 23452K, committed 23552K, reserved 1069056K
  | class space    used 2960K, capacity 3062K, committed 3072K, reserved 1048576K

**Comment by scholzj** [comment]
This is indeed a bit weird. Strimzi is not mounting the volumes, the platform does that. But normally if it doesn't succeed the pod should not start. Can you check whether you can:
* Mount the volume in different pod and actually use it
* Exec into the pod to see what is or isn't in the mount directory where the volume should be?

**Comment by ritxos** [comment]
@scholzj Thanks for the response,
Volumes are mounted properly, In debug mode I've rshd into the pod and i could see the data along with permissions --due to the nature of error i was moving away form checking disk space but now i know that my volumes are full.

I'll expand volumes and try to avoid any data loss here and restarting pods just make everything good.(closing this case)

Thanks again for the directions.
