### ISSUE TITLE
[Bug] Flaky test: testTopicAddedWithEncodableName

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#2186]
[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 400.376 s <<< FAILURE! - in io.strimzi.operator.topic.TopicOperatorIT
[ERROR] testTopicAddedWithEncodableName{VertxTestContext}  Time elapsed: 76.289 s  <<< FAILURE!
java.lang.AssertionError: java.lang.Throwable: Test timeout

**Comment by scholzj** [comment]
Triaged on 7th July 2022: It looks like the test got tired of being flaky and fixed itself after 2 and half years.
