### ISSUE TITLE
[Bug] -Xmx for pods whould not be determined from memory limit but memeory request

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2203]
Following the discussion on [Slack](https://cloud-native.slack.com/archives/CMH3Q3SNP/p1574045255087900), we should use the memory request and not limit to determine the default -Xmx setting. The memeory limit might never be granted to the pod, so using it to determine -Xmx can lead to crashloops of KAfka when it cannot allocate the memeory at all.

This should be mentioned in release notes.

**Comment by stanlyDoge** [comment]
Why this should be a problem? 
```
The flag Xmx specifies the maximum memory allocation pool for a Java virtual machine (JVM), while Xms specifies the initial memory allocation pool.
```
If we use CR like 
```
resources:
      limits:
        memory: 4Gi
      requests:
        memory: 2Gi
```
it does make sense to have a Xms set to 2Gi and Xmx to 4Gi, does not it?

**Comment by scholzj** [comment]
The problem is that you want Kafka which will run as a stable application. But with -Xmx based on the limit it might never be abe to allocate this memory because it might not be available. It might be also killed because the limit memory needs to be collected back.
