### ISSUE TITLE
[Enhancement] Support storing logs on persistent volumes instead of always sending them only to STDOUT

### ISSUE THREAD

**Issue by JEFFLUFC** [strimzi/strimzi-kafka-operator#2216]
Description:
Whilst being very noisy, GC logs can be useful for example when identifying hangs in the JVM, or to indicate the reason as to why a Kafka log may hang (due to GC inferred via the log, with which you can cross reference timestamps). A JVM Option can be added to allow the logs to be output to a file rather than stdout, when GC logging is enabled. This allows the logs to be used when desired, whilst not cluttering stdout and being difficult to follow.

CC @dalelane

**Comment by scholzj** [comment]
Triaged on 17.3.2022: Needs more discussion => should this include all logs? Separate volume? (more complicated) Dump it to data volume? (easy but a bit messy)

**Comment by scholzj** [comment]
Triaged on 31.3.2022: We should close this and keep #3693 since that solves this problem in a most generic way.
