### ISSUE TITLE
[Doc][Bug] Dashboard for Zookeeper uses wrong expression for 'Memory Usage'

### ISSUE THREAD

**Issue by joe-sch** [strimzi/strimzi-kafka-operator#2224]
**Suggestion / Problem**
In the example dashboard for Zookeeper the expreession for the `Memory Usage` panel differs from the expression of the same panel for the kafka pods. 

for [zookeeper](https://github.com/strimzi/strimzi-kafka-operator/blob/master/metrics/examples/grafana/strimzi-zookeeper.json) the expression contains a `rate()` funtion it is:
````
"sum(rate(container_memory_usage_bytes{namespace="$kubernetes_namespace",container_name="zookeeper",kubernetes_pod_name=~"$strimzi_cluster_name-$zk_node"}[5m])) by (kubernetes_pod_name)"
````

for [kafka](https://github.com/strimzi/strimzi-kafka-operator/blob/master/metrics/examples/grafana/strimzi-kafka.json) it doesn't have the `rate()`funtion, it is:
````
sum(container_memory_usage_bytes{namespace="$kubernetes_namespace",kubernetes_pod_name=~"$strimzi_cluster_name-$kafka_broker",container_name="kafka"}) by (kubernetes_pod_name)
````

As a result of the `rate()` function the zookeeper dashboards says that a zookeeper pod uses only for example something between 2 and 6 megabytes, see https://strimzi.io/docs/master/images/grafana_zookeeper_dashboard.png

And i think that the `JVM Memory Used` Panels for both dashboards have the same Problem, it is not plausible that Zookeeper uses only 2M for the Heap, nor that Kafka 25M, see https://strimzi.io/docs/master/images/grafana_kafka_dashboard.png

**Comment by scholzj** [comment]
Thanks for raising this. I opened the PR #2237 to fix this.

**Comment by joe-sch** [comment]
Great, thank you
