### ISSUE TITLE
[Question] is it possible to change the advertised host without using an external listener?

### ISSUE THREAD

**Issue by carlobongiovanni** [strimzi/strimzi-kafka-operator#2247]
Hi, my use case is to enable mirroring between two GKE clusters located in two different regions, part of the same GCP project. To achieve that I don't want to use an external listener:

an external listener of type loadbalancer is not accepted by my company. an external listener of type nodeport brings other problems due to other networking policies we have in place.

I noticed that it's not possible to change the advertisedHost for internal listeners, but probably this could solve my issue. In my gcp setup I allow traffic to pods within different clusters, therefore I could even accept to use a static ip configuration in the internal listeners, but I haven't been able to find it in the docs. 

Has anyone addressed the same problem or would be able to give a suggestion on which direction to take? Thanks
C.

**Comment by scholzj** [comment]
I haven't heard about this kind of setup. We currently don't support redefining the advertised listener like this.

In the past I hacked around similar use cases by using a NodePort type external listener but not really exposing the nodes but overwritting the advertised information on them. Is that something what could work for you? I.e. you would have the NodePort services, but not necessarily use them.

**Comment by carlobongiovanni** [comment]
Yes, I did it as you suggested and it works. Thanks a lot!
