### ISSUE TITLE
[Question] Running on K8s cluster with /tmp non-writable policy.

### ISSUE THREAD

**Issue by weichuliu** [strimzi/strimzi-kafka-operator#2251]
Hi,

We are trying to run Strimzi (and Kafka cluster it creates) on our on-premise cluster.

However on the k8s cluster, the security policy is more strict and /tmp is set to non-writable, so Strimzi Operator failed to boot.

The problem could be solved by mounting a `tmpdir` fs to `/tmp`, but in order to do that we might need to fork the project and build our own image.

We want to seek for advice to see if we can mount /tmp without forking Strimzi.
Do we have a way of avoiding this problem by configuring some parameters of strimzi operator?
If it's not possible with current strimzi, is the change against strimzi itself for avoiding the problem acceptable by the community?

Thanks!

**Comment by weichuliu** [comment]
cc @mitake

**Comment by scholzj** [comment]
I haven't yet seen a cluster configured like that. I have also no idea how to set it up to give it a try. In the operator, you can probably just mount empty dir as `/tmp` - you can easily edit the deployment. But you cannot do this so easily with the Kafka pods and they use `/tmp` as well.

A lot of applications expects `/tmp` to be accessible. So how do you in general deal with them? Mount an emptyDir into `/tmp` to work around it? Or use some other solution? Maybe we can incorporate it into Strimzi.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.

**Comment by weichuliu** [comment]
Just want to thank you for your kind help.

We worked out this issue by mounting /tmp to the instance.
