### ISSUE TITLE
[Enhancement] Ability to Expose jmx_exporter port (9094) as pod port for each Kafka pod.

### ISSUE THREAD

**Issue by weichuliu** [strimzi/strimzi-kafka-operator#2252]
**Is your feature request related to a problem? Please describe.**
Strimzi metrics are design with Prometheus in mind, however we are not using Prometheus, but instead datadog.

Kafka exposes its metrics at port 9404, we want to write a small daemon to fetch metrics from each Kafka pod and export them to Datadog.

However the problem we encountered is that 9404 is only exposed to localhost and on `[name]-kafka-bootstrap`. The former is not accessible from other pods, and the later one can not tell which pod is the information from.

**Describe the solution you'd like**
we want to have a manifest configurable way expose 9404 per pod, so that I can `curl [name]-kafka-0:9404`

**Comment by scholzj** [comment]
I think you should follow the discussion in #2209 where we are currently discussing this. Any feedback would be welcome.

**Comment by weichuliu** [comment]
Actually, I am not sure if my understanding is right.

I deployed my cluster on Minikube with default metrics settings. From `[name]-kafka-0`, I can `curl localhost:9404` and see the metrics with no issues.

On the other hand, on `[name]-kafka-0`, I cannot `curl [name]-kafka-1:9404`.

I am not expert of `prometheus`, so I wonder how exactly does a `Prometheus` access to `9404` from another pod?

**Comment by scholzj** [comment]
If you want to use the DNS name to curl it, you would need to use the full DNS name. Which in this case might be something like `<name>-kafka-1.<name>-kafka-headless.svc`. Only the pod name will nto be resolved as DNS name.

**Comment by weichuliu** [comment]
@scholzj DNS seems not to be the cause here. On minikube the DNS works somehow. For example from kafka-1 I can talk to `kafka-2:9094`:

```
[kafka@bucketrider-kafka-1 kafka]$ /opt/kafka/bin/kafka-topics.sh --list --bootstrap-server bucketrider-kafka-2:9094
__consumer_offsets
test
```

From kafka-1 I cannot talk to `kafka-2:9404`(jmx export port) but I can talk to `kafka-1:9404` itself:

```
[kafka@bucketrider-kafka-1 kafka]$ curl bucketrider-kafka-1:9404 | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7098  100  7098    0     0   349k      0 --:--:-- --:--:-- --:--:--  364k
    129     681    7098
[kafka@bucketrider-kafka-1 kafka]$ curl bucketrider-kafka-2:9404 | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
```

**Comment by scholzj** [comment]
Prometheus is scraping these ports, so it is possible to access them from another pod. Not sure why does this not work - or to put it in other words, I would maybe not expect it to work without the full DNS, but if it works for the topics, it should here as well. Does it work locally then in Kafka pod 2?

**Comment by weichuliu** [comment]
@scholzj 

Thank you for your help.

FYI, we ended up adding a customized sidecar for scraping purpose in our forked version. From another pod we could not work out a stable solution that solves DNS/Port connection issue.

I wonder if upstream is interested in configurable sidecar feature?

**Comment by scholzj** [comment]
TBH, I do not like the sidecar approach that much, because it makes it very hard to help someone if every is using some sidecar. Plus the integration can often get complicated with things which the sidecar might want form the Pod such as volumes or ports. But feel free to list here how you addressed it - especially on the API level.

**Comment by scholzj** [comment]
Just FYI ... there i now JMX support: https://strimzi.io/docs/master/full.html#assembly-jmx-options-deployment-configuration-kafka and there is a PR #2339 which by my understanding should help with integrations like this. Would that help to resolve this issue?

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
