### ISSUE TITLE
[Bug] Cannot provision kafka-persistent on OpenShift 4.2

### ISSUE THREAD

**Issue by jpkrohling** [strimzi/strimzi-kafka-operator#2281]
**Describe the bug**
Provisioning a Kafka based on the `kafka-persistent.yaml` on OpenShift 4.2.2 results in the Zookeeper pods to crash due to permission problems.

**To Reproduce**
1. Provision an OpenShift 4.2.2 cluster with `openshift-install create cluster`
2. Install the AMQ Streams operator from the Operator Hub
3. `$ kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/examples/kafka/kafka-persistent.yaml`
4. `$ kubectl logs my-cluster-zookeeper-0 -c zookeeper`

**Expected behavior**
A Kafka cluster would be provisioned based on the example, like it happens with `minikube`.

**Environment (please complete the following information):**
```
$ oc get subscriptions -n openshift-operators
NAME                     PACKAGE                  SOURCE                CHANNEL
amq-streams              amq-streams              redhat-operators      stable
```

 - Installation method: OperatorHub.io
 - Kubernetes cluster: 
```
$ oc version
Client Version: openshift-clients-4.2.1-201910220950
Server Version: 4.2.2
Kubernetes Version: v1.14.6+868bc38
```
**YAML files and logs**
Custom Resource: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/examples/kafka/kafka-persistent.yaml
Logs from Zookeeper: https://paste.centos.org/view/c1a73425
State of the cluster:
```
$ oc get pods
NAME                                                     READY   STATUS             RESTARTS   AGE
my-cluster-zookeeper-0                                   1/2     CrashLoopBackOff   6          8m33s
my-cluster-zookeeper-1                                   1/2     CrashLoopBackOff   6          8m33s
my-cluster-zookeeper-2                                   1/2     CrashLoopBackOff   6          8m33s
```
YAML representation of the first pod: https://paste.centos.org/view/3f90a57c

**Additional context**
This is currently affecting the Kafka auto-provisioning feature from the Jaeger Operator (https://github.com/jaegertracing/jaeger-operator/issues/815)

**Comment by jpkrohling** [comment]
The error messages are similar to #1720, but the causes might be different.

**Comment by jpkrohling** [comment]
Looks like this happens only when deploying in the `default` namespace. The workaround is to deploy in another namespace.

@scholzj feel free to close this if you think there's no action to take in Strimzi's side.

**Comment by jpkrohling** [comment]
(or rather, to reopen if you think there *is* an action :) )

**Comment by scholzj** [comment]
For the record and following the Slack conversation ... The usual default for OCP is that it runs all pods under the SCC `restricted` policy. This policy injects its own security context (user ID, group ID, the persistent volume group ID). This seems to work fine on regular namespaces create by the user.

The `default` namespace in OCP4 seems to be using different SCC policy than regular user created namespaces.  In the default namespace, you can get it running by adding your own security context into the cluster. E.g.

```yaml
template: 
  pod: 
    securityContext: 
      fsGroup: 0 
      runAsGroup: 0 
      runAsUser: 1000001
```
