### ISSUE TITLE
[Question] Deploying operator on k3s

### ISSUE THREAD

**Issue by mariusstaicu** [strimzi/strimzi-kafka-operator#2286]
Hi, 

Regarding deploying on a k3s local cluster. I can deploy, no problems, operator shows up as a running deployment,
however, it doesn't show any log whatsoever and when I create a kafka resource, it doesn't create a stateful set.

I've seen the bug: https://github.com/strimzi/strimzi-kafka-operator/issues/1976 and I thought deployment on k3s is possible. Also, my k3s cluster shows for version a correctly formatted date string. 
```bash
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
Am I doing something wrong ? I must say that I use the same setup for a full blown GCP cluster and it works with no problems.

**Comment by scholzj** [comment]
I think the bug refered in #1976 (rancher/k3s#808) is fixed. So if you have newer version you do not need to manipulate the version info.

As for your problem:
* When you say doesn't create statefulset, does it mean that `kubectl get sts` doesn't list it?
* Could you post the whole log from the cluster operator? If possible, maybe with a log level set to DEBUG (the `STRIMZI_LOG_LEVEL` and var in the deployment)? Maybe something will tell us what the problem could be.

It worked fine with the workaround when I played with it. But the version might be now newer and micght have changed.

**Comment by mariusstaicu** [comment]
hy, thanks. It turned out that the k3s cluster had some kind of a problem. I reinstalled it and it all worked really well. Thanks.
