### ISSUE TITLE
[Question] installing my own certificate 

### ISSUE THREAD

**Issue by nimmichele** [strimzi/strimzi-kafka-operator#2295]
Hi all,
in my environment tls and sasl authentication works fine with auto generated cert and key. 
But when I tried to install my own cert following documentation, kafka-external fails saying it can not connect to zookeeper due to a certification problem.
Can you help me please pointing to the right docs/ideas? 
Thanks

**Comment by scholzj** [comment]
Are the certificates you provided configured with CA:True in the X509 extensions? That is a common problem which can cause this.

**Comment by nimmichele** [comment]
Hi scholzj,
tnx a lot for quick reply, I am trying to install certificate from Let's Encrypt and yes CA is false, infact:
penssl x509 -text -noout -in ca.crt | grep CA
                CA:FALSE
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/
but it is a chain certificate and it includes another certificate inside and it should be ok.

This is the log from <my-cluster>-kafka-0
Service [zookeeper-2181] accepted connection from 127.0.0.1:50588
connect_blocking: connected 10.3.252.8:2181
Service [zookeeper-2181] connected remote server from 10.0.1.39:42696
CERT: Verification error: unable to get local issuer certificate
Certificate check failed: depth=0, /O=io.strimzi/CN=kafka-external-zookeeper
SSL_connect: 14090086: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Connection reset: 0 byte(s) sent to SSL, 0 byte(s) sent to socket
it seems tls-sidecar is trying to verify zookeeper with a wrong certificate, but I only changed <my-cluster>-cluster-ca-cert and <my-cluster>-cluster-ca with:
  clusterCa:
    generateCertificateAuthority: false
and I suppose zookeeper should not be envolved in new certificate.
Any ideas how to solve the problem?

**Comment by scholzj** [comment]
Yeah, you cannot use Let's encrypt as CA. But the PR #2204 should allow you to use it as server wildrcard certificate - so this should be in the next release.

**Comment by nimmichele** [comment]
Perfect!
I didn't understand the difference between CA and Let's Encrypt wildcard certificate (so I thought Strimzi had already this feature) 
I saw PR #2204 has been already merged into master branch...
Thanks for explanation!
