### ISSUE TITLE
Move to final v1 version for CRDs apiextensions

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#2298]
When we'll drop support for older Kubernetes versions than the 1.16.0, we should move our CRDs API version from current `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` as defined by the `CRD_API_VERSION` constant in our CRDs api classes.

**Comment by scholzj** [comment]
This has been implemented.
