### ISSUE TITLE
Add UUID request in the KafkaClusterRebalance resource Status

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#2322]
In order to track the interaction between the CO and the Cruise Control REST API about ongoing rebalance operations, we need to store the so-called "User-Task-ID" in the `KafkaClusterRebalance` resource status. It's needed for interacting with CC REST API providing which request we want the running state and reflecting it in the resource status.

**Comment by stanlyDoge** [comment]
This can be closed, can't it?
