### ISSUE TITLE
[Question] Cruise Control ETA?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [strimzi/strimzi-kafka-operator#2326]
Hi, I see that Cruise Control is being implemented... Do you guys have a rough estimate on when it will be released? 1 week? 1 month?  6 months?

Thanks

**Comment by ppatierno** [comment]
Hi Daniel, we are already working on it, I guess that it should land in January timeframe.

**Comment by DanielFerreiraJorge** [comment]
Thank you very much!

**Comment by DanielFerreiraJorge** [comment]
Sorry to reopen the issue, but was cruise control implemented? I could not find any mention regarding it in the recent releases changelogs, nor in the user manual... thanks!

**Comment by scholzj** [comment]
The Cruise Control support has been shipped in Strimzi 0.18.0. Please check it out. https://strimzi.io/docs/operators/latest/full/using.html#cruise-control-concepts-str
