### ISSUE TITLE
[Bug] DNS caching in the Topic Operator

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#2332]
The TO uses the JVM default for caching DNS responses (when a security manager is not installed that default is to cache for an "implementation specific period of time", but it's not documented what that is). Sometimes that caching can prevent the TO from reconnecting to Zookeeper or a broker.

We should use the `networkaddress.cache.ttl` security property (not system property), to set that TTL to a known low value, or disable it entirely.

See https://docs.oracle.com/javase/8/docs/technotes/guides/net/properties.html

**Comment by scholzj** [comment]
From our images:

```
#
# The Java-level namelookup cache policy for successful lookups:
#
# any negative value: caching forever
# any positive value: the number of seconds to cache an address for
# zero: do not cache
#
# default value is forever (FOREVER). For security reasons, this
# caching is made forever when a security manager is set. When a security
# manager is not set, the default behavior in this implementation
# is to cache for 30 seconds.
#
# NOTE: setting this to anything other than the default value can have
#       serious security implications. Do not set it unless
#       you are sure you are not exposed to DNS spoofing attack.
#
#networkaddress.cache.ttl=-1
```

I do not think we are using security manager in TO, so it sould default to 30 seconds. If we wanna change this, how do we do it? Just sed the value in the original JVM file? Or do we want to use some more sophisticated method? E.g. using an override properties file?

**Comment by tombentley** [comment]
It's difficult to really justify going to extra effort, but I don't really like the idea of sedding the JVM security policy. It feels cleaner to use `Security.setProperty()`, even with a hard coded value.

**Comment by scholzj** [comment]
Ok, I will check if we can set the security properties with the default JVM settings. If we can, we can hardcode some defaults and have a env var to optionally reconfigure it or something like that maybe.
