### ISSUE TITLE
[Enhancement] Add support for kubernetes.io/tls certificates

### ISSUE THREAD

**Issue by joyrex2001** [strimzi/strimzi-kafka-operator#2340]
Currently certificates are stored, and consumed in Opaque secrets. Since there is a secret type [kubernetes.io/tls](https://github.com/kubernetes/api/blob/49be0e3344fe443eb3d23105225ed2f1ab1e6cab/core/v1/types.go#L5013) that is intended for storing tls certificates, it makes sense to support this as well. In our use case, our secret providing component exports certificates as `kubernetes.io/tls` secrets, and therefor we can not integrate this with strimzi.

**Comment by scholzj** [comment]
Maybe a stupid question, but can you explain the difference? I do not think this is part of any official interface or documentation.

**Comment by joyrex2001** [comment]
The type specifies there is a private key stored in `tls.key` and the certificate stored in `tls.crt`. So, if you have a secret with the type `openshift.io/tls`, you know that this secret will have these two keys available. Technically there is no difference, the added value is in the semantic contract (a standard).

**Comment by scholzj** [comment]
TBH, it is not a standard if the only real reference is somewhere in the source code. The problem is that we cannot change this without affecting everyone else who is using our secrets with our current names. And IMHO keeping duplicates would only keep confusion of what is what.

Also the problem is that this is a bit too simplistic. In some of the secrets we need to be able to transfer multiple certificates because of regeneration etc. So using only `tls.crt` and `tls.key` is not enough.

**Comment by joyrex2001** [comment]
I agree it's not a hard standard, and I also agree it's not realistic to move into that direction at this stage. But since this is the closest to an existing definition, it might make sense to consider supporting at least the filename convention used in there at some point.

Thanks for the discussion, much appreciated. I think it makes sense to close the issue.

**Comment by scholzj** [comment]
TBH I would have loved to follow this as closely as possible if I knew about this on the beginning. Now this is a much harder question because it is either breaking the compatibility or keeping duplicate secrets. Which secrets would you need it for in particular?

**Comment by joyrex2001** [comment]
We are bringing our own cluster-ca, so in our case `<cluster>-cluster-ca` and `<cluster>-cluster-ca-cert` are affected.

**Comment by ppatierno** [comment]
In the latest version, we are also putting PKCS12 store and password in our certificates related secret to simplify Java clients' usage so using tls.crt and tls.key is not enough.
