### ISSUE TITLE
Strimzi kafka fails random pods on cluster

### ISSUE THREAD

**Issue by patsadow2** [strimzi/strimzi-kafka-operator#2370]
Hello,

I am using kafka-ephemeral.yaml in memory with one node on kubernetes, and sometimes it break the whole cluster and every service start to fail even not connected with strimzi.

It's not aks it's 2 v-machines connected master-node with funnel 

From rancher i see there is only 20-30% of usage CPU/Memory

I cannot diagnose the problem, and i am not sure which logs should i observer when everything randomly fail ;/

Any idead what could be wrong ?

**Comment by scholzj** [comment]
Do you have some monitoring of available disk space? The ephemeral is not in-memory. It is using the `emptyDir` volumes which is basically an unbounded temporary directory somewhere in your filesystem. One of the possibilities is that these fill in your disk space and cause problems to other components.

**Comment by patsadow2** [comment]
Hmm, how many disk space need strimzi ? That could be a issue since i have only 30 GiB disk per VM

**Comment by scholzj** [comment]
Well, Strimzi operator it self doesn't anything. But Kafka does. Depending on the amount of topics, messages etc. it could be from GBs up to many TBs. Basically, each partition would create some index and log files. The indexes have fixed size even when empty, the log segments will grow with messages.

If oyu have latest Strimzi version and if your Kubernetes version suports it, you could also try to use the size limit for the epmtydir volumes: https://strimzi.io/docs/latest/full.html#type-EphemeralStorage-reference ... But I guess you should count with at leats 1GB per ZK node and at least 10GB per Kafka node.

**Comment by patsadow2** [comment]
I am wondering if the main problem is caused by that i use https://docs.microsoft.com//azure/aks/azure-nfs-volume and it write/read from disk a lot 
![image](https://user-images.githubusercontent.com/19226186/71997908-efc13800-323e-11ea-9b8c-8a96f2ad169c.png)

**Comment by scholzj** [comment]
Well, NFS is a bad choice for Kafka. So it wouldn't surprise me if Kafka doesn't work. Not sure how would it kill other componenets, but everything is possible I guess.

**Comment by patsadow2** [comment]
But i think kafka use his /temp since i use inmemory kafka from kafka-ephemeral.yaml

**Comment by patsadow2** [comment]
I am not sure maybe this is can be problem with VM's since after 30 min it became stable again


![image](https://user-images.githubusercontent.com/19226186/72000329-59434580-3243-11ea-9220-e3b583e4702f.png)

**Comment by scholzj** [comment]
I guess it definitely could be that it overloads the disk and that cause some problems to rest of the system. Since it is natwork attached disk it could be even some general IO or network connectivity to the master.

**Comment by patsadow2** [comment]
It's a little bit wierd i've added next node and i cannot make it fail now, so it's seems to be working for now we will see if that help, it's look like kafka need =< 3 nodes

**Comment by patsadow2** [comment]
Still failing ;/ i am out of ideas

**Comment by scholzj** [comment]
Honestly, it is hard to help without having some experience with the platform and infrastructure. MAybe you can try to add memory requests to the KAfka brokers if it helps. But I hope Rancher is better than that and wouldn't let it self be killed by that.

In general Kafka is definitely not something what runs for cheap. To get a good performance it needs some resources. And the NFS is bad choice in general. You should try it with some proper block storage, idealy separate from the system disk.

But as I said, it is hard to help more when its setup which I don't know.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
