### ISSUE TITLE
[Doc] KUBERNETES_SERVICE_DNS_DOMAIN should be documented

### ISSUE THREAD

**Issue by mickymiek** [strimzi/strimzi-kafka-operator#2372]
**Suggestion / Problem**

This issue: https://github.com/strimzi/strimzi-kafka-operator/issues/1486 still happens on clusters that have a different DNS domain name than the k8s's default one (`cluster.local`).

Setting `KUBERNETES_SERVICE_DNS_DOMAIN` in the cluster operator deployment when using another domain name should be documented somewhere.

**Comment by scholzj** [comment]
This should be now documented in https://strimzi.io/docs/operators/latest/full/using.html#ref-operator-cluster-str
