### ISSUE TITLE
Move helper methods for creating secrets and volumes etc. from AbstractModel to ModelUtils

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2373]
The `AbstractModel` class has several helper methods to create volumes, templates etc. (e.g. `createSecretVolume`, `createEmptyDirVolume` or `createPersistentVolumeClaimTemplate`). These are used more or less statically can be moved to the `ModelUtils` class.

**Comment by xsreality** [comment]
I would like to work on this to get familiar with the code base :)

**Comment by ppatierno** [comment]
@xsreality any help from the community is always appreciated. If you want I can assign this issue to you and feel free to ask for any kind of help.

**Comment by xsreality** [comment]
Sure go ahead. I will probably have a few questions, will ask here or on the Slack channel.

**Comment by ppatierno** [comment]
Questions more related to the issue maybe are better here, so that we can track them on this issue itself otherwise, feel free to use Slack.
