### ISSUE TITLE
[Enhancement] Add Strimzi release 0.15.0 to OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi-kafka-operator#2375]
Add Strimzi release 0.15.0 to OperatorHub.io.

**Comment by scholzj** [comment]
There is a PR for it: https://github.com/operator-framework/community-operators/pull/979 ... but it got stuck on some of the scorecard tests.

**Comment by ron1** [comment]
Do you think the upstream-community-operators scorecard tests will get stuck as well for a "kubernetes-operator" PR?

**Comment by scholzj** [comment]
I think the test is the same. I need to get back to it, but didn't had time yet :-(.

**Comment by ron1** [comment]
Please add to OperatorHub.io upstream-community-operators as well.

**Comment by scholzj** [comment]
Just done it: https://github.com/operator-framework/community-operators/pull/1245

I plan to move to 0.16.2 or 0.17.0 once we get it merged.
