### ISSUE TITLE
java.lang.IllegalArgumentException: Version `2.3` is not a valid version

### ISSUE THREAD

**Issue by krishnachaitanyareddy** [strimzi/strimzi-kafka-operator#2378]
One of the broker is not starting after updating to the 2.3 version. Below are the changes

inter.broker.protocol.version=2.3
log.message.format.version=2.3

**Log reference:**

`[2020-01-09 10:28:47,410] ERROR Fatal error during SupportedServerStartable startup. Prepare to shutdown (io.confluent.support.metrics.SupportedKafka)
java.lang.IllegalArgumentException: Version `2.3` is not a valid version
	at kafka.api.ApiVersion$.$anonfun$apply$1(ApiVersion.scala:91)
	at scala.collection.MapLike.getOrElse(MapLike.scala:128)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
	at scala.collection.AbstractMap.getOrElse(Map.scala:59)
	at kafka.api.ApiVersion$.apply(ApiVersion.scala:91)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1138)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1028)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1008)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1005)
	at kafka.server.KafkaConfig.fromProps(KafkaConfig.scala)
	at io.confluent.support.metrics.SupportedServerStartable.<init>(SupportedServerStartable.java:52)
	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:45)
`

**Broker server.property**

`auto.create.topics.enable=false

broker.id=16

cache.max.bytes.buffering=840000000

confluent.support.customer.id=anonymous

confluent.support.metrics.enable=false

cruise.control.metrics.reporter.bootstrap.servers=server10:9092

default.replication.factor=3

delete.topic.enable=true

group.initial.rebalance.delay.ms=3000

inter.broker.protocol.version=2.3

kafka.metrics.polling.interval.secs=5

listeners=PLAINTEXT://broker1:9092

log.dirs=/apps/kafka

log.message.format.version=2.3

log.retention.check.interval.ms=300000

log.retention.hours=168

log.segment.bytes=1073741824

metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter

min.insync.replicas=1

num.io.threads=8

num.network.threads=3

num.partitions=1

num.recovery.threads.per.data.dir=4

num.replica.fetchers=8

offsets.retention.minutes=10080

offsets.topic.replication.factor=3

reserved.broker.max.id=2147483647

socket.receive.buffer.bytes=1048576

socket.request.max.bytes=104857600

socket.send.buffer.bytes=1048576

unclean.leader.election.enable=false

zookeeper.connect=server1:2181,server2:2181,server3:2181

zookeeper.connection.timeout.ms=6000`

**Comment by scholzj** [comment]
I do not think that any classes from the package `io.confluent.support.metrics.SupportedKafka` are part of Strimzi. Is this something you added? It looks like it doesn't like the 2.3 version. But I have no clue what it is and what might be the problem.

**Comment by krishnachaitanyareddy** [comment]
@scholzj , i figured out the issue. kafka-ssl-principal-builder.jar was causing the problem. Once i move out the jar from "/usr/share/java/kafka/" broker started as expected.

**Comment by scholzj** [comment]
Ok, great. So I guess we can close this issue, right?
