### ISSUE TITLE
[Question] Kafka Connect does not automatically create topic.

### ISSUE THREAD

**Issue by yuwtennis** [strimzi/strimzi-kafka-operator#2400]
Hello .

I would like to ask question regarding to kafka connect. I currently use `strimzi 0.15.0`  .

I have kafka connect configured to use jdbc driver (`confluentinc-kafka-connect-jdbc-5.3.2`).
However, after jdbc task starts up ,  **topics are not created** on _broker_ side  .

```
2020-01-15 04:59:55,147 INFO Started JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask) [task-thread-dt003_term_location_info-0]
```

I usually see this log in kafka broker.

```
[2020-01-15 06:12:42,166] INFO [KafkaApi-0] Auto creation of topic db_dt003_term_location_info with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
```

Would there be any setting missing to create topics ?

I appreciate if I could get some advice.

Best Regards,
Yu Watanabe

**Comment by scholzj** [comment]
When deploying the Kafka cluster, you can disable / enable the automatic topic creation in the config section:
```yaml
auto.create.topics.enable: "false"
```

By default it should be enabled. In that case, when the producer connects to the broker to use topic which doesn't exist, it will get automatically created witht he default settings. That is what the log you pasted says. If you disable it by setting it to `false`, this topic would not be created automatically and someone has to create it explicitely.  So you should check whether you didn't disabled this. 

I do not think there is anything in Kafka Connect to enable / disable it. I do not know whether the JDBC connector it self has any options.

**Comment by yuwtennis** [comment]
Thank you for the advice . I will close this issue since it is solfved now.
