### ISSUE TITLE
[Doc] Issue with expansion of attributes with back ticks in them

### ISSUE THREAD

**Issue by sjwoodman** [strimzi/strimzi-kafka-operator#2404]
**Suggestion / Problem**
The K8sEmptyDir attribute has backticks in it to render as fixed with font. However, these are escaped somewhere in the generation process so the back ticks appear in the generated docs and the text is the incorrect font. For example, see ``emptydir`` here

https://strimzi.io/docs/master/#ref-ephemeral-storage-deployment-configuration-kafka

**Comment by laidan6000** [comment]
Fixed by PR #2542
