### ISSUE TITLE
[Enhancement] Allow TLS protocol selection for External connections

### ISSUE THREAD

**Issue by smartbit** [strimzi/strimzi-kafka-operator#2406]
I'd like to select the TLS protocols that the cluster supports for External connections. In the logs now we see
```
ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
```
For **External** connections I'd like to _disable_ `TLSv1.1, TLSv1` and allow `TLSv1.2` _only_.

Additional feature request: able to set the **ssl.cipher.suites**

**Comment by scholzj** [comment]
Thanks for opening the issue. This is definitely in our plans. Hopefully we get to it in one of the next releases.
