### ISSUE TITLE
[Enhancement] Support for `message.handler` and `message.handler.args` in Mirror Maker

### ISSUE THREAD

**Issue by mike-treadway** [strimzi/strimzi-kafka-operator#2407]
**Is your feature request related to a problem? Please describe.**
I have a situation where I'd like to use a message handler in Mirror Maker. I need a way to pass in the `--message.handler` and `--message.handler.args` arguments to Mirror Maker.

**Describe the solution you'd like**
I will need to create my own image from the strimzi image in order to add in my custom handler jars, but I'd rather not have to touch anything else other than add my jars. Currently I'll have to modify the `kafka_mirror_maker_run.sh` script to all me to pass in environment variables for these additional Mirror Maker parameters.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ppatierno** [comment]
Hi @mike-treadway thanks for raising this one, I left my comments on the related PR you opened.
