### ISSUE TITLE
[Bug] Replace "provided by Red Hat" in operatorhub.io

### ISSUE THREAD

**Issue by sjwoodman** [strimzi/strimzi-kafka-operator#2410]
The CSV that generates the OperatorHub.io interfaces includes Red Hat as the provider of the Strimzi Operator. This is incorrect and should be changed to something else. Candidates include "Strimzi Community" or "CNCF". There are examples of both of these in OperatorHub.io, but personally, I prefer the former.

**Comment by ppatierno** [comment]
Some others are using "by XXX Authors", btw I agree on "by Strimzi Community".
Now we have two options. Opening a PR for updating the current version or waiting to fix this when 0.16.0 will be out.
@tombentley @scholzj wdyt?
One more thing to notice is that OperatorHub.io is still on Strimzi 0.14.0!

**Comment by sjwoodman** [comment]
I would wait for 0.16.0. The 0.15.0 PR is stalled and given we are close to 0.16.0 then we should create a new one and try to push that through.
