### ISSUE TITLE
[Enhancement] Refactor KafkaAssemblyOperator Class to reduce line count/complexity

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#2413]
**Is your feature request related to a problem? Please describe.**

The KafkaAssemblyOperator class is approaching a non-commented source line length of 1500 lines [1] which when reached will violate our line limit checkstyle restriction.

**Describe the solution you'd like**

Refactor the KafkAssemblyOperator class to reduce the line count. We could start by separating out the ReconciliationState, then trying to reduce the number of fields, and then maybe even separating some of the functions into their own subclasses.

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/master/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaAssemblyOperator.java

**Comment by tomncooper** [comment]
There are quite a few fields from the KAO that the reconciliation state needs. Are we happy with a huge constructor for the RS? Would a builder pattern be better?

**Comment by tomncooper** [comment]
Or we could just keep hold of the ResourceOperatorSupplier instance given to the KAO constructor and just give that to the RS constructor for it to get what it needs each time?

**Comment by tomncooper** [comment]
Actually looking a this a bit more closely. The RS need access to so many of the fields in the KAO and its superclass that doing all the fields separately would be a big job.

**Comment by sknot-rh** [comment]
I did some refactoring [here](https://github.com/sknot-rh/strimzi/commits/refactor-kao). I am not convinced it is what we want, but it does split the huge class into several smaller ones. 
Is this the right path to go?

**Comment by scholzj** [comment]
This was done accross various PRs in Strimzi 0.29.0 release.
