### ISSUE TITLE
Getting error "HTTP Error bad Gateway" in grafana

### ISSUE THREAD

**Issue by mussa572** [strimzi/strimzi-kafka-operator#2421]
Hi 
I have added the Prometheus operator and trying to add it on the grafana pod  . However even after multiple attempts of rebuilding whole cluster ,I am getting the error HTTP Error bad Gateway . I have also attached the screenshot confirming all the services are up . I have logged on the kafka box and confirm the kafka exporter scaping the logs successfully . Also perform the telnet test to service 9090 which is also successful . 

Is there anything else I can check to confirm if i am missing anything . 

<img width="1069" alt="Screen Shot 2020-01-18 at 01 44 10" src="https://user-images.githubusercontent.com/59732783/72656719-39bfc180-3995-11ea-8f33-118f918ea50f.png">

Output of the `kubectl get all` . 

<img width="1071" alt="Screen Shot 2020-01-18 at 01 54 45" src="https://user-images.githubusercontent.com/59732783/72656913-953e7f00-3996-11ea-806b-75c345bfa859.png">

Regards

**Comment by mussa572** [comment]
Below is also the output from the service . just noticed that there is no end point associated with it . is this normal for this service to not have an endpoint ? 

> `kubectl describe service prometheus`

Name:              prometheus
Namespace:         default
Labels:            app=strimzi
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"strimzi"},"name":"prometheus","namespace":"default"},"sp...
Selector:          prometheus=prometheus
Type:              ClusterIP
IP:                10.8.15.103
Port:              prometheus  9090/TCP
TargetPort:        9090/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>

Regards

**Comment by ppatierno** [comment]
From your pods output I can see the Prometheus operator but not the Prometheus server.
The Prometheus operator is something that allows you to deploy the Prometheus server (as Strimzi is the operator that allows you to deploy the Apache Kafka cluster).
You are getting the BAD GATEWAY error because when Grafana tries to hit the Prometheus service, it's not able to redirect the call to the "TargetPort" because pods with the selector "prometheus=prometheus" doesn't exist.

**Comment by mussa572** [comment]
Thanks Paolo, by any chance do you know which file this tag is added to create the promethous server pod. I have used exactly the same file which are provided as part of strmizi example files (https://strimzi.io/docs/latest/#ref-metrics-config-files-str). Only thing I changed the namespace from "my-namespace" to "default" as I am running kafka on the default namespace . 

Regards

**Comment by ppatierno** [comment]
I am referring to the `prometheus.yaml` which describes the `Prometheus` resource kind which is handled by the Prometheus operator for deploying Prometheus.
The same YAML also contains the Service (which I see in your screenshot), ServiceAccount and role bindings.

**Comment by mussa572** [comment]
Thanks Paolo, I have only change `namespace`  to `default` on `prometheus.yaml` as per the instruction on link (https://strimzi.io/docs/latest/#proc-metrics-deploying-prometheus-operator-str) apart from that I have made no changes to the file which provided in the example files provided as part of the strimzi implementation . 


Also I am bit confused with following steps . My question is of why we have to make changes to below files if they have been provided as part of the example to monitor strimzi . In my scenario I only want to monitor kafka implemented by strimzi  

```
Edit the ServiceMonitor resource in strimzi-service-monitor.yaml to define Prometheus jobs that will scrape the metrics data. Any other advise will be appreciated .

To use another role:

Create a Secret resource:

oc create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml
Edit the additionalScrapeConfigs property in the prometheus.yaml file to include the name of the Secret and the YAML file (prometheus-additional.yaml) that contains the additional configuration.

Edit the prometheus-rules.yaml file that creates sample alert notification rules:
```

**Comment by ppatierno** [comment]
Due to how the Prometheus operator works not all jobs can be in the `ServiceMonitor` so the need for an additional scrape config which has to be in a Secret. Actually the doc is not clear I have to admit. Maybe @stanlyDoge can help on this.

Anyway if you followed all the steps, what you get if you run the command:

`kubectl get prometheus`

It should return the Prometheus instance that the Prometheus operator should see. If it's there so maybe we can take a look at the operator log to check why it's not getting the Prometheus resource. If it's not there, it means you didn't apply the `prometheus.yaml`  (or not in the right namespace).

**Comment by mussa572** [comment]
Hi Paolo,
Thanks for the advise , I managed to identify the issue , it was the secret file `additional-scrape-configs.yaml` i needed to apply this file on the secret . 

Now I can see the new Pod appearing , However it stays in Pending state all the time . 

I am running this cluster in google cloud , wondering if any one noticed issue running this operator running on google . I dont see any logs generated by the pending pods.  

<img width="680" alt="Screen Shot 2020-01-20 at 01 45 13" src="https://user-images.githubusercontent.com/59732783/72692950-a3bba080-3b26-11ea-92a6-f9b2de80e330.png">

**Comment by stanlyDoge** [comment]
Do their events say something suspicious?

**Comment by ppatierno** [comment]
can you do `kubectl describe pod prometheus-prometheus-0`, it should give you more information

**Comment by mussa572** [comment]
Thanks for all the advise , issue was solved .

**Comment by ppatierno** [comment]
@mussa572 it would be interesting to know what was the problem.

**Comment by mussa572** [comment]
@ppatierno  , Sure I can explain . So initially I was missing the following steps where you have to create a secret and then apply it on the kubernetes secret . As we discussed the documentation is not very clear on the monitoring section . 

#Then you will need to make a secret file out of this configuration. 

kubectl create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml --dry-run -oyaml > additional-scrape-configs.yaml

# Above command will create the new scret file "additional-scrape-configs.yaml".

ls prometheus-additional-properties/
additional-scrape-configs.yaml	prometheus-additional.yaml

# Apply the newly created secret file to the kubernetes secret using following command . 

kubectl create -f additional-scrape-configs.yaml

# Make sure the secret file is added to kubernetes secret by following command . 

kubectl get secret 



----------------------------------

Second issue where the pods were in pending state , that was due to the resource issue . So I did not have enough cpus on the nodes to add extra pods . Adding the node to the kubnernetes cluster solved the problem . 

Regards 

Mussa
