### ISSUE TITLE
helm install strimzi/strimzi-kafka-operator gives error 

### ISSUE THREAD

**Issue by rupeshjha** [strimzi/strimzi-kafka-operator#2435]
When i run command "helm install strimzi/strimzi-kafka-operator" it gives below error.

Error: pods is forbidden: User "system:serviceaccount:<namespace>:<serviceaccount>" cannot list resource "pods" in API group "" in the namespace "kube-system"

We haven't created any namespace kube-system

**Comment by scholzj** [comment]
`kube-system` exists in most clusters and contains the system compoenets. Could it be that it is the namespace whihc you have set as default and that is why Strimzi is being installed there? Also, do you get the error from Helm or from Strimzi?

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
