### ISSUE TITLE
Add Kafka minimalist SASL/PLAIN auth to OCP deployment w/annotated secret

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi-kafka-operator#244]
Add Kafka minimalist SASL/PLAIN auth to OCP deployment w/annotated secret. In many OpenShift environments, IPSEC encryption is already in place (see https://access.redhat.com/documentation/en-us/openshift_container_platform/3.7/html/cluster_administration/admin-guide-ipsec) which makes TLS encryption unnecessary. Secret and parameter definitions should be similar to the following:

objects:
    {
      "kind": "Secret",
      "apiVersion": "v1",
      "metadata": {
        "name": "kafka",
        "annotations": {
          "template.openshift.io/expose-username": "{.data['kafka-user']}",
          "template.openshift.io/expose-password": "{.data['kafka-password']}",
          "template.openshift.io/expose-admin_username": "{.data['admin-user']}"
          "template.openshift.io/expose-admin_password": "{.data['admin-password']}",
        }
      },
      "stringData" : {
        "kafka-user" : "${KAFKA_USER}",
        "kafka-password" : "${KAFKA_PASSWORD}",
        "kafka-admin-user" : "${KAFKA_ADMIN_USER}"
        "kafka-admin-password" : "${KAFKA_ADMIN_PASSWORD}",
      }
...
parameters:
    {
      "name": "KAFKA_USER",
      "displayName": "Kafka Producer/Consumer Username",
      "description": "Username for Kafka Producer/Consumer that will be used for accessing the broker.",
      "generate": "expression",
      "from": "user[A-Z0-9]{3}",
      "required": true
    },
...

**Comment by scholzj** [comment]
@ron1 I'm sorry, we didn't got to implement this. But we have now the [user operator](http://strimzi.io/docs/master/full.html#assembly-using-the-user-operator-str) which should cover the same areas although using the SASL SCRAM-SHA implementation instead of SASL PLAIN. Do you think this is still needed? Or can we close this as _resolved by the User Operator_?

**Comment by ron1** [comment]
I agree that SASL SCRAM-SHA support in the user operator satisfies the requirement. When is SASL SCRAM-SHA support expected to hit the master branch?

**Comment by scholzj** [comment]
We have the PRs already opened (#755 and #795 ). The last things to finish there it polish some tests and merge it. So I think it will get to master this week.
