### ISSUE TITLE
[Enhancement] Refactor JAAS config generation code into it's own class

### ISSUE THREAD

**Issue by ajborley** [strimzi/strimzi-kafka-operator#2443]
**Is your feature request related to a problem? Please describe.**
PR #2311 adds JAAS config generation code in the `KafkaMirrorMaker2AssemblyOperator` class for use by the MM2 connectors. There is also some JAAS config generation in the `KafkaBrokerConfigurationBuilder` class which was added as part of PR #2342. There is also some JAAS config generation in the scripts in `docker-images/kafka/scripts`.

**Describe the solution you'd like**
As noted by Tom (here: https://github.com/strimzi/strimzi-kafka-operator/pull/2311#discussion_r368507129), it would be good to refactor the JAAS config generation to it's own dedicated class to make testing, re-use, etc easier.

**Comment by scholzj** [comment]
Triaged on 17.3.2022: Still desired. Can be split into multiple PRs.

**Comment by ShazaAldawamneh** [comment]
hi Jakub, can you assign this to me as I'm working on it with Tom

**Comment by ShazaAldawamneh** [comment]
https://github.com/strimzi/strimzi-kafka-operator/pull/8901 PR merged
