### ISSUE TITLE
[Question] kafka-connecte data volume 

### ISSUE THREAD

**Issue by madbean** [strimzi/strimzi-kafka-operator#2445]
Hi,

I Want to use filestreaming connector to append data to a file.
This file is read by a R programme for learn about this data and Make some calcule.

The file connector sink generate the file inside one of the kafka connect pod.
How can i access this file from Another one pod please ?
I was thinking about mounting volume but i didn’t found this option, and HDFS look complicated for this simple case.

Thank for reading me and tour work
Jo

**Comment by scholzj** [comment]
You cannot really do this. The problem is that this does not go so well with for example scaling the Kafka Connect deployment etc. All I can probably offer you right now is to use the Strimzi image it self in your own pod and configure it for example as sidecar etc.

**Comment by madbean** [comment]
Thank you for your help
i solve this by stream to file form nodejs kafka-stream.
