### ISSUE TITLE
[Doc] Improve "Mounting Secrets as volumes" for Kafka Connect

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#2452]
**Suggestion / Problem**
I was trying to follow the documentation for using config providers in Kafka connect () and found it could be clearer:

1. It should call out how the name of the secret volume and the name of the key in the secret (but not the secret name) relate to the file name passed via `${file:...}`. This isn't really explained and it's left to the reader to infer what the pattern is.
1. Step 4 assumes user is accessing REST API directly. We should give an example with a `KafkaConnector`.

**Documentation Link**
https://strimzi.io/docs/master/#proc-kafka-connect-mounting-volumes-deployment-configuration-kafka-connect

**Comment by PaulRMellor** [comment]
@tombentley - I've created a PR (#3492). Step 4 had an example for KafkaConnector, but I've added some clarifications for the config.

**Comment by scholzj** [comment]
Fixed in #3492
