### ISSUE TITLE
SqlConnector Database HELL

### ISSUE THREAD

**Issue by patsadow2** [strimzi/strimzi-kafka-operator#2455]
Hello, 

I'm out of mind after 5hours of finding solution i have 2 databases on the same server with SQL Server Agent on and _CT working in both cases but when i switch from 1 database with was first database ever i've connect to another i don't see events in kafka ....

If i change testDB to otherDB it's cannot get events in kafka....
```

{
    "name": "inventory-connector-mssql",
    "config": {
        "connector.class" : "io.debezium.connector.sqlserver.SqlServerConnector",
        "tasks.max" : "1",
        "database.server.name" : "server1",
        "database.hostname" : "mssql-deployment",
        "database.port" : "1433",
        "database.user" : "sa",
        "database.password" : "Pasw0rd!",
        "database.dbname" : "testDB",
        "database.history.kafka.bootstrap.servers" : "my-cluster-kafka-bootstrap:9092",
        "database.history.kafka.topic": "schema-changes.inventory",	
		"transforms": "route",
		"transforms.route.type": "org.apache.kafka.connect.transforms.RegexRouter",
		"transforms.route.regex": "([^.]+)\\.([^.]+)\\.([^.]+)",
		"transforms.route.replacement": "$3"
    }
}




```

Should i add some unique key or something ? Or where can i check what could be wrong why i see events in kafka from one database and i don't see from another. It push new events everytime i insert it by SQL.

**Comment by scholzj** [comment]
TBH, that might be maybe a question for the Debezium mailing list. I do not see any reason why Strimzi would cause this. So it might be a bug or limitation in Debezium it self maybe?

**Comment by patsadow2** [comment]
I've reinstalled strimzi kafka and it's working when i choose as a first right database.
