### ISSUE TITLE
fbric8 version [Question] ...

### ISSUE THREAD

**Issue by FridMehdi** [strimzi/strimzi-kafka-operator#2462]
Hello;
currently you are using fabric8.kubernetes-client.version 4.6.2 which suport openshift 4.1
that mean the operator kafka strimzi is not fully compatible with openshift 4.2 or higher version
thanks
```
<fabric8.openshift-client.version>4.6.4</fabric8.openshift-client.version>
 <fabric8.kubernetes-model.version>4.6.4</fabric8.kubernetes-model.version>
```

**Comment by scholzj** [comment]
I do not think that is true. The fact that Fabric8 _supports OpenShift 4.1_ does not mean in any way that it does not work with OpenShift 4.2 or newer or that there are any problems. AFAIK Strimzi works fine with latest OpenShfit and latest Kubernetes as I'm using both regularly. If you have any issues, please provide us with the details and we will have a look at it.
