### ISSUE TITLE
[Bug] ...Producer is not able to connect to kafka brokers on AKS

### ISSUE THREAD

**Issue by anishprobable** [strimzi/strimzi-kafka-operator#2466]
Hi,

I tried to deploy Kafka on AKS via Strimzi Operator. I was following the post 
https://medium.com/@agrajm/running-kafka-on-azure-kubernetes-service-d8d6882ade8.

I was able to enter into Kafka pod and exec it. However when I ran below command

bin/kafka-console-producer.sh --broker-list my-tls-cluster-kafka-bootstrap.tls-kafka:9093 --topic test --producer.config /opt/kafka/config/ssl-config.properties

I got below error: I have masked some text below:

[2020-01-27 14:42:20,799] WARN Removing server #######-kafka-cluster-bootstrap.#######--kafka:9093 from bootstrap.servers as DNS resolution failed for #######--kafka-cluster-bootstrap.#######- (org.apache.kafka.clients.ClientUtils)
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:415)
at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:287)
at kafka.producer.NewShinyProducer.<init>(BaseProducer.scala:40)
at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:48)
at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)
at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:372)
... 4 more

I am running this on Azure CLI from Company Network. Being new to Kafka and Azure, can someone please help me out with the steps that I need to take to resolve this. I guess this is something related to networking/ports etc but I am really not sure what step I need to take.

**Comment by scholzj** [comment]
I think I will need a bit more information ...
* Is `tls-kafka` your namespace? Can you try to add `.svc` behind it? I think it should work also without it, but miht be worth a try.
* How many nodes does your Kafka cluster have? Is it more than just 1? There is this slightly weird thing when you cannot connect from the pod onto it self through a service. So IIRC this would not work if you exec into the KAfka pod and have only 1 Kafka pod.

**Comment by anishprobable** [comment]
Thanks !!  Got it resolved. My service name was incorrect. kubectl get svc -n <namespace> helped me out with correct service name. However I am not able to Produce/Consume. From 1 clinet I am able to produce but on another client I am not able to consume.

Client 1:
kubectl exec -it kafkaclient-0 sh -n tls-kafka
bin/kafka-console-producer.sh --broker-list my-tls-cluster-kafka-bootstrap.tls-kafka:9093 --topic test --producer.config /opt/kafka/config/ssl-config.properties

Client 2:
kubectl exec -it kafkaclient-1 sh -n tls-kafka
bin/kafka-console-producer.sh --broker-list my-tls-cluster-kafka-bootstrap.tls-kafka:9093 --topic test --producer.config /opt/kafka/config/ssl-config.properties

No error encountered when executing the bin/kafka-console-producer.sh and bin/kafka-console-producer.sh. However I am not able to see messages type from kafkaclient-0 to kafkaclient-1

**Comment by scholzj** [comment]
The producers sometimes need a lot of time before they throw errors with things such as TLS errors etc. Have you waited long enough to see that they actually sent your messages? They can spit the errors easily minute after you tried to send something.

**Comment by anishprobable** [comment]
"Long Enough" approximation ? The shells are not throwing any errors but yes I waited for 1 min or 2 max to see if the messages send from producer gets reflected on Consumer shell or not. Two separate CLI's for Producer and Consumer used.

**Comment by anishprobable** [comment]
Ok.. Got it resolved. There was no problem with the setup. It was due to zookeeper, I had set 2 replicas in yaml file and but it should be 3 to maintain the quoram so that was causing the broker to get confused. All is not up and running !!

Many Thanks for taking out the time to read issue and respond !!
