### ISSUE TITLE
[Question] Devops Azure Pipeline - Kubectl exec connectors

### ISSUE THREAD

**Issue by patsadow2** [strimzi/strimzi-kafka-operator#2469]
Hello,

How do you handle post connectors ? I 've problem with / and ' and other stuffs. I am also trying to handle it in that way, but still there are problems.

![image](https://user-images.githubusercontent.com/19226186/73263846-c3f7f900-41d1-11ea-98db-0dd4f458aef6.png)

![image](https://user-images.githubusercontent.com/19226186/73263876-d1ad7e80-41d1-11ea-8634-ac7ceecc89ff.png)

**Comment by scholzj** [comment]
I think this will not work because the `-d @...` points to your system at local host but the curl command will be executed inside the pod where it will not have the disk, or?

**Comment by patsadow2** [comment]
I am also trying with no effect:

-i my-cluster-kafka-0 -- curl -X POST -H Accept:application/json -H Content-Type:application/json http://my-connect-cluster-connect-api:8083/connectors -d https://raw.githubusercontent.com/repo/master/es-sink.json


Unrecognized token 'https': was expecting ('true', 'false' or 'null')\

**Comment by scholzj** [comment]
I never saw that curl can pull the content from somewhere else. Is that expected to work? I personally usually just use the JSON directly. E.g.:

```
--data '{ "name": "sink-test", "config": { "connector.class": "FileStreamSink", "tasks.max": "3", "topics": "kafka-test-apps", "file": "/tmp/test.sink.txt" } }'
```

If you are on Strimzi 0.16.0 or newer, you can also use the new connecotr operator and just use YAML and CRs for managing connectors.

**Comment by patsadow2** [comment]
It's working correctly from my PC but i am trying to use it from Azure Pipeline by kubectl option and there are problems with windows/linux trim "/", """

**Comment by patsadow2** [comment]
@scholzj Where can i find do this "If you are on Strimzi 0.16.0 or newer, you can also use the new connecotr operator and just use YAML and CRs for managing connectors." Can i give me some example?

**Comment by ppatierno** [comment]
@patsadow2 you can find some resources on the official doc:

https://strimzi.io/docs/latest/#proc-deploying-kafkaconnector-str
https://strimzi.io/docs/latest/#con-creating-managing-connectors-str

but even on this blog post providing a Debezium example:

https://strimzi.io/2020/01/27/deploying-debezium-with-kafkaconnector-resource.html

**Comment by patsadow2** [comment]
I've used it but it doesn;t work with yaml

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: inventory-connector-mssql
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.server.name: "server1"
    database.hostname: "mssql-deployment"
    database.port: "1433"
    database.user: "sa"
    database.password: "Pasw0rd!"
    database.dbname: "ihostedb"
    database.history.kafka.bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
    database.history.kafka.topic: "schema-changes.inventory"
    transforms: "route"
    transforms.route.type: "org.apache.kafka.connect.transforms.RegexRouter"
    transforms.route.regex: "([^.]+)\\.([^.]+)\\.([^.]+)"
    transforms.route.replacement: "$3"
    tombstones.on.delete: "true"

**Comment by patsadow2** [comment]
Working great

**Comment by patsadow2** [comment]
@ppatierno I've encounter some problem is there any setting to set KafkaConnector be applied after kafka is ready because somethimes when i restart cluster it doesnt apply connectors i am not sure why.

**Comment by scholzj** [comment]
@patsadow2 Does this still seem like a problem? Or can we close this?
