### ISSUE TITLE
Refactoring Future composition in the composite operations

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#249]
Most of the `CompositeOperation` (i.e. createKafka, createZk, ...) join a bunch of `Future`.
An idea from @tombentley was : 

> Rather than joining on a bunch of Futures here you could abstract waitUntilReady() into a utility method that took a ready Function as parameter. In the current case you could all that with a method reference to this::isReady(). Here you could instead pass a lambda that returns the isReady() results for each of the replicas &&-ed together. I'm not saying you should do this, but it would mean only one timer, and fewer Futures flying around, so could well be more efficient.

**Comment by scholzj** [comment]
Reviewed on 10th September 2020: There might be other issues to refactor but given the age of this issue, we should close this.
