### ISSUE TITLE
io.strimzi.operator.cluster.KafkaUpgradeException for supported version?

### ISSUE THREAD

**Issue by jslusher** [strimzi/strimzi-kafka-operator#2510]
```
k get deploy strimzi-cluster-operator -n strimzi-kafka-operator -o json | jq '.spec.template.spec.containers[].image'
"strimzi/operator:0.16.2"
```

I recently upgraded my strimzi-kafka-operator from 0.14.0 to 0.16.2. I also set the version in my Kafka CRD to 2.4.0. The operator is logging this exception:

```
io.strimzi.operator.cluster.KafkaUpgradeException: Unsupported Kafka.spec.kafka.version: 2.3.0. Supported versions are: [2.3.1, 2.4.0]
```

2.3.0 is my previous version, but I can see that the Kafka object is set to 2.4.0:

```
k get kafka platform -o json | jq '.spec.kafka.version'
"2.4.0"
```

Is there something I'm missing in this upgrade? Looking at the instructions and I don't think I left anything out.

**Comment by tomncooper** [comment]
The issue is that the 0.16 cluster operator only supports Kafka 2.3.1 and 2.4.0 so you cannot upgrade your Kafka 2.3.0 cluster using 0.16. 

You will need to use the 0.15 cluster operator to upgrade your Kafka cluster to 2.3.1, then upgrade the operator to 0.16 and upgrade Kafka 2.3.1 to 2.4.0

**Comment by jslusher** [comment]
Oh! I guess I misunderstood the documentation there. I didn't consider that it wouldn't upgrade from an unsupported version.
