### ISSUE TITLE
[Enhancement] The user operator to create secrets in other namespaces which contains both user and cluster CA certs

### ISSUE THREAD

**Issue by allanmoso** [strimzi/strimzi-kafka-operator#2513]
**Is your feature request related to a problem? Please describe.**
We are using TLS authentication for our Kafka clients. Because strimzi's user operator is only able to create user secrets (and CA secrets) in one namespace we are not able to mount those secrets on our Kafka client pods that reside in other namespaces without having to duplicate the secret to the other namespace by other means.

This issue is also the same for the cluster's CA cert which the client needs for its truststore.

**Describe the solution you'd like**
It would be great if the user-operator is able to watch all namespaces and create the secret in the namespace where the KafkaUser was reconciled from.  Because the kafka client also needs the cluster CA cert to connect to the cluster, it would also be nice if the user secret also contains that.  This would make it so that everything that a Kafka client application needs to connect to the Kafka cluster is available as a secret in the namespace where it would be deployed, if a KafkaUser object is created in that namespace.

**Describe alternatives you've considered**
- The simplest way would be to have the admins move the secret between namespaces. But this would put too much operational burden on the admins, especially because of auto-renewals. We did not go with this approach.
- We created a k8s controller that watches secrets with an annotation that defines a **source namespace**.  We would then create these empty placeholder secrets.  The k8s controller will then load the secret with data from the **source secret** based on the **source namespace** annotation and that matches its name of the placeholder secret.

**Additional context**
The current behavior of the user operator is inconvenient for us based on how we want to manage our k8s cluster.  We are pushing for self-service for our developers when it comes to deploying to the kubernetes cluster. However, developers are not able to interact with secrets directly, for security reasons. This prevents them from moving strimzi secrets between namespaces for their applications to use.

We are doing ["GitOps"](https://www.weave.works/technologies/gitops/) as a way to manage our cluster using [Weaveworks' Flux](https://github.com/fluxcd/flux)

We are also using [Stakater's Reloader](https://github.com/stakater/Reloader) tool that would allow us to restart pods when secrets or configmaps are changed, e.g., during CA auto-renewals.

**Comment by Fryuni** [comment]
This would definitely would help us a lot.  
We are in a similar scenario, for now we are putting all the applications that interact with Kafka in the same namespace as the cluster. That works, but it's not ideal by any means. Organizing those applications in namespaces would be much better for managing policies, permissions, quotas and priorities.

**Comment by dave93cab** [comment]
+1, would be very helpful

**Comment by MarkusTiede** [comment]
Thanks for sharing all of the information - @allanmoso: would you be interested in maybe sharing / open-sourcing your solution? [We're](https://github.com/baloise) atm building a very similar solution and are also thinking about doing that; really appreciate your comments / feedback!

**Comment by jutley** [comment]
You can allow Strimzi to manage users in other namespaces by specifying `STRIMZI_NAMESPACE="*"` and `STRIMZI_CA_NAMESPACE=<whereever strimzi is running>`. Unfortunately, this doesn't at all address the issue of the truststore not being available from other namespaces.

**Comment by alok87** [comment]
+1 
It is a very important thing from the renewal point of view. Strimzi takes care of renewing the certificates based on its renewal flags. So if at present we manually duplicate the secret, later it would again be a problem when we need to renew those certificates. 

If the strimzi operator takes care of keeping the secrets created in the right namespace it would be really helpful,

**Comment by dweber019** [comment]
We have written a Quarkus Operator to distribute secrets based on a label called `dist-namespace-1: <namespace>`. If a secret has this label it will distribute the secret and if the secret has in addition a label `strimzi.io/kind: KafkaUser` it will distribute the CA too.

Sorry but currently the source is not open source.
@MarkusTiede what do you think?

**Comment by MarkusTiede** [comment]
@dweber019 : Thanks for sharing the information! IMHO there is no reason why we shouldn't / couldn't share this as an open-source project at ours. Depending on the level of maturity I'd either place it within our top-level organization /baloise - or otherwise the /baloise-incubator. But iirc this is in productive use @ ours which is why I'd place it directly top-level.

**Comment by dweber019** [comment]
Nice will check how I can open source it ;)

**Comment by dweber019** [comment]
Here the link to our Quarkus app https://github.com/baloise/kube-secret-watcher as a first draft release.

**Comment by rossbachp** [comment]
A more general tool to copy secrets and cm can help:

https://github.com/kubeops-tools/kubed

**Comment by veerendra2** [comment]
+1 
Right our requirement is share secrets to different stages(namespace) in a cluster

**Comment by veerendra2** [comment]
I think, it is available from `0.24`
https://strimzi.io/blog/2021/07/22/using-kubernetes-config-provider-to-load-data-from-secrets-and-config-maps/

**Comment by veerendra2** [comment]
Ok, I found a way share secrets with help of this blog https://strimzi.io/blog/2021/07/22/using-kubernetes-config-provider-to-load-data-from-secrets-and-config-maps/
With RABC
### ROLE
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-client-role
  namespace: kafka
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["xxxx-dev-cluster-ca-cert", "galileo "]
    verbs: ["get"]
```
### RoleBinding
````
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-client-role-binding
  namespace: kafka
subjects:
- kind: ServiceAccount
  name: kafka-client
  namespace: veerendra-test
roleRef:
  kind: Role
  name: kafka-client-role
  apiGroup: rbac.authorization.k8s.io
````
### Create service account in namepsace "veerendra-test"
```
$ oc create sa kafka-client
```
### Get service account token and login with it
````
$ oc describe secret kafka-client-token-2hrw8
$ oc login https://openshift.dev.ocpXXXXXXX:443 --token=eyJhbGciOiJSU...
```
### Verify permission, should able get galileo secret
````
$ oc get pods
No resources found.
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:veerendra-test:kafka-client" cannot list pods in the namespace "xxx": no RBAC policy matched
$ oc describe secret galileo -n kafka
Name:         galileo
Namespace:    kafka
Labels:       app.kubernetes.io/instance=galileo
              app.kubernetes.io/managed-by=strimzi-user-operator
              app.kubernetes.io/name=strimzi-user-operator
              app.kubernetes.io/part-of=strimzi-galileo
              strimzi.io/cluster=sirius-dev
              strimzi.io/kind=KafkaUser
Annotations:  <none>

Type:  Opaque

Data
====
user.p12:       2364 bytes
user.password:  12 bytes
ca.crt:         1164 bytes
user.crt:       1009 bytes
user.key:       1704 bytes
```
* Finally inject the service account into app pod. The application has to use the service account get the secrets

**Comment by scholzj** [comment]
@veerendra2 This was one of the use-cases I thought about when designing the configuration provider. It might not be perfect since you need to do the RBAC setup etc., so it is maybe not as easy as using the local secret. But you should definitely give it a try.

**Comment by dweber019** [comment]
If anyone inserted we built an operator which can copy stuff by providing coordinates in a CRD yaml.
We needed this to copy secrets created by Strimzi and RHSSO (Keycloak) into other namespaces. Both of them have different implementations on handling/templating we made it declarative and resource based not operator capability based.

https://github.com/baloise/os3-copier

**Comment by shaakaud** [comment]
> This would definitely would help us a lot. We are in a similar scenario, for now we are putting all the applications that interact with Kafka in the same namespace as the cluster. That works, but it's not ideal by any means. Organizing those applications in namespaces would be much better for managing policies, permissions, quotas and priorities.

Did you find a better way to organize applications in a different namespace which can access the Cluster ?

**Comment by scholzj** [comment]
Triaged on 17.3.2022: This can be addressed by some of our existing utilities:
* The Kubernetes Config Provider (already released, works with Java clients)
* The Kafka Access operator (work in progress) which will allow to copy the cluster credentials into other namespaces.

**Comment by ltson4121994** [comment]
> Triaged on 17.3.2022: This can be addressed by some of our existing utilities:
> 
>     * The Kubernetes Config Provider (already released, works with Java clients)
> 
>     * The Kafka Access operator (work in progress) which will allow to copy the cluster credentials into other namespaces.

I have a use case where each kafka connect cluster represents a user and is deployed in different namespaces. I can see that there is an example on using secrets in different namespace with KafkaConnector, but is there any way we can reference that secret in KafkaConnect .spec.tls.trustedCertificates? RBAC would not work here I think because kafka connect cannot be deployed.
