### ISSUE TITLE
[Question] How to limit access to ingress external?

### ISSUE THREAD

**Issue by avif** [strimzi/strimzi-kafka-operator#2528]
I'm looking to whitelist ip addresses to the generated kafka ingress, tried:
```
dnsAnnotations:
   nginx.ingress.kubernetes.io/whitelist-source-range: xxx.xxx.xxx.xxx/32
   ingress.kubernetes.io/whitelist-source-range: xxx.xxx.xxx.xxx/32
```
But apparently that does not work with `nginx.ingress.kubernetes.io/ssl-passthrough: "true"`...

Is there a way to do this in the tls_sidecar? (or any other way)

**Comment by scholzj** [comment]
We really rely for the ingrss on this. You could try to use ntwork policies, but I'm not sure they would get the rigth IP address. Plus I think they let you only specify an IP address and not CIDR.  Simimlarly you can us ACLs per IP address. But again I'm not sure it allows CIDR instead of single IP.

**Comment by avif** [comment]
Thanks for the help, the solutions you provided did not solve my problem for the reasons you assumed.
I did manage to achieve this with an additional ingress controller for restricted access and using ingress class annotation on the kafka ingress configs.
Sure it does use additional LB's for the new ingress controller but it can serve all kafka deployments with the same ingress controller - so i'll call it a win :)

**Comment by scholzj** [comment]
Great, thanks for the update and glad you got it working. Can I close the issue? Or do you think you will have something more?

**Comment by avif** [comment]
Yes, you can close it - thanks!

**Comment by rajjaiswalsaumya** [comment]
Can you explain the steps ?
