### ISSUE TITLE
Splitting health check parameters for liveness and readiness probes

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#253]
Currently the `AbstractCluster` class provides health check fields which are in common between readiness and liveness probes. It could be useful (and needed for the current `TopicController` implementation) having two groups of parameters for setting path, timeout and so on for both liveness and readiness probes.
It comes from following discussion : 

https://github.com/strimzi/strimzi/pull/237#discussion_r170562102

**Comment by scholzj** [comment]
I believe we have now separate options in the CRDs for liveness probe and readiness probe. I think this could be closed. Feel free to reopen it if you think we are still missing something.
