### ISSUE TITLE
[Bug] Installation fails in Azure Kubernetes Service

### ISSUE THREAD

**Issue by octopyth** [strimzi/strimzi-kafka-operator#2535]
**Describe the bug**
Following the quickstart instructions, the installation fails. My guess is that the kafka brokers try to find zookeeper at localhost instead of actual zookeeper dns or IP. Not sure how to resolve, can you help?

**To Reproduce**
1. Create namespace kafka2
```kubectl create ns kafka2```
2. Create the custom resources in kafka2 namespace
```
curl -L https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.16.2/strimzi-cluster-operator-0.16.2.yaml \
   | sed 's/namespace: .*/namespace: kafka2/' \
   | kubectl apply -f - -n kafka2
```
3. Wait for the resources to get created (takes few seconds up to a minute)
4. Create the kafka cluster
```
kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.16.2/examples/kafka/kafka-persistent.yaml -n kafka2
```
5. Wait enough time to get all resources created
6. Observe CrashLoopBackOff for all kafka brokers
```
kubectl get all -n kafka2
```
![image](https://user-images.githubusercontent.com/640759/74232623-78f9dd80-4cc9-11ea-9b08-92789050b895.png)

7. Check kafka container logs
```
kubectl logs pod/my-cluster-kafka-0 -n kafka2 --container kafka
```
![image](https://user-images.githubusercontent.com/640759/74236944-a72feb00-4cd2-11ea-85e8-59fec2ca07e3.png)

**Expected behavior**
Hopefully the installation should go through.

**Environment (please complete the following information):**
 - Strimzi version: master, 0.16.2
 - Installation method: YAML 
 - Kubernetes cluster: AKS 1.16 
 - Infrastructure: Azure Kubernetes Service, 5 nodes type Standard_DS2_v2

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
My Kubernetes cluster consists of 5 nodes type Standard_DS2_v2
![image](https://user-images.githubusercontent.com/640759/74237429-d430cd80-4cd3-11ea-85cd-d2fe31c15abc.png)

**YAML files and logs**

https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.16.2/strimzi-cluster-operator-0.16.2.yaml

*I tried the report.sh script, which didn't work*
```
./report.sh: 7: ./report.sh: oc: not found
./report.sh: 21: ./report.sh: [[: not found
```

**Additional context**
I have previously installed other example yaml files namely kafka-persistent-single.yaml, so it is possible that I could have the cluster name already in use at the time of the installation start. This brings up the question how to easily perform cleanup of all the resources created with 
```
curl -L https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.16.2/strimzi-cluster-operator-0.16.2.yaml \
   | sed 's/namespace: .*/namespace: kafka2/' \
   | kubectl apply -f - -n kafka2
```
and
```
kubectl apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.16.2/examples/kafka/kafka-persistent.yaml -n kafka2
```
Ideally the cleanup instruction should make it to the quickstart guides, right after

**Comment by octopyth** [comment]
## Cleanup script
```
# delete namespace scoped resources
kubectl delete \
customresourcedefinition.apiextensions.k8s.io/kafkas.kafka.strimzi.io \
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-entity-operator-delegation \
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-topic-operator-delegation \
customresourcedefinition.apiextensions.k8s.io/kafkausers.kafka.strimzi.io \
clusterrole.rbac.authorization.k8s.io/strimzi-entity-operator \
clusterrole.rbac.authorization.k8s.io/strimzi-cluster-operator-global \
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator \
clusterrole.rbac.authorization.k8s.io/strimzi-cluster-operator-namespaced \
clusterrole.rbac.authorization.k8s.io/strimzi-topic-operator \
serviceaccount/strimzi-cluster-operator \
clusterrole.rbac.authorization.k8s.io/strimzi-kafka-broker \
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io \
customresourcedefinition.apiextensions.k8s.io/kafkabridges.kafka.strimzi.io \
deployment.apps/strimzi-cluster-operator \
customresourcedefinition.apiextensions.k8s.io/kafkaconnectors.kafka.strimzi.io \
customresourcedefinition.apiextensions.k8s.io/kafkaconnects2is.kafka.strimzi.io \
customresourcedefinition.apiextensions.k8s.io/kafkaconnects.kafka.strimzi.io \
customresourcedefinition.apiextensions.k8s.io/kafkamirrormakers.kafka.strimzi.io \
-n kafka

# delete cluster scoped resources
kubectl delete \
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator \
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-kafka-broker-delegation 

# delete namespace
kubectl delete ns kafka
```

**Comment by scholzj** [comment]
The Zookeeper connection string is for sure not a problem. It connects always to localhost bcausee the connction is routed through the TLS sidecars. So your problme will be somewhere else. Could you share logs from Zookeeper pods (both containers) and from the Kafka pods (both ontainers)?

**Comment by octopyth** [comment]
@scholzj Thanks Jakub, I cleaned up and this time all worked like a charm, could be a glitch with AKS.
```
kubectl get all -n kafka
```
![image](https://user-images.githubusercontent.com/640759/74367227-cbbebc80-4dd1-11ea-9fac-9107f0fd896d.png)

I am closing the issue, just noting about including the Cleanup procedure in the quick start manuals.
