### ISSUE TITLE
latest strimzi-cluster-operator is not creating NetworkPolicy for KafkaConnect?

### ISSUE THREAD

**Issue by jslusher** [strimzi/strimzi-kafka-operator#2538]
**Describe the bug**
I recently upgraded to strimzi-cluster-operator `0.16.2` and I have a KafkaConnect in a separate namespace. I see this in the logs:

```
2020-02-11 18:44:02 WARN  AbstractOperator:268 - Reconciliation #10(timer) KafkaConnect(kafka/platform): Failed to reconcile
```

If I add my own permissive NetworkPolicy to allow connections from my operator's namespace, the KafkaConnect gets reconciled.

```
2020-02-11 18:47:02 INFO  AbstractOperator:262 - Reconciliation #15(watch) KafkaConnect(kafka/platform): reconciled
```
**To Reproduce**
1. Create strimzi-cluster-operator in separate namespace
2. Create KafkaConnect resource in separate namespace
3. Examine NetworkPolicies for ingress from operator namespace
4. Look for reconciliation errors in operator logs

**Expected behavior**
I'm under the impression that the operator should create a NetworkPolicy that would allow the operator to communicate with the connect api.

**Environment (please complete the following information):**
 - Strimzi version: 0.16.2
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.16.6
 - Infrastructure: bare metal with kubeadm

**Comment by scholzj** [comment]
@jslusher Thanks for raising this. I opened a PR to have it hopefully fixedin 0.17.0.
