### ISSUE TITLE
[Enhancement] Add Strimzi release 0.16.2+ to OperatorHub.io (upstream-community-operators)

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi-kafka-operator#2569]
[Enhancement] Add Strimzi release 0.16.2+ to OperatorHub.io (upstream-community-operators)

**Comment by scholzj** [comment]
I oepned the first PR for community operators. Once it is ok and merged, I will open the second one for upstream-community-operators.

**Comment by scholzj** [comment]
Just opened the second PR: https://github.com/operator-framework/community-operators/pull/1269

**Comment by scholzj** [comment]
And the PR has been merged now. So I think we can close this issue.
