### ISSUE TITLE
kerberos authentication

### ISSUE THREAD

**Issue by saneerayapa** [strimzi/strimzi-kafka-operator#2570]
hi 
 is Strimz support kerberos authentication 

Thanks

**Comment by scholzj** [comment]
No, it doesn't support Kerberos. 

As far as I know (but I might be wrong), getting Kerberos to work in something like Kubernetes is very complicated and _insecure_ ()sharing tickts from the worker host etc. So we do not currently plan to add support for it.

**Comment by saneerayapa** [comment]
thanks @scholzj
