### ISSUE TITLE
podManagementPolicy as an option in Kafka CR

### ISSUE THREAD

**Issue by ladmitry** [strimzi/strimzi-kafka-operator#2575]
**Current issue:**

KAFKA OPERATOR VERSION: 0.13.0
Currently, stateful sets use the Parallel podManagementPolicy for both Kafka and Zookeeper.
That works perfect if we need to speed up the startup. However, in our case (HA cluster) we have strict affinity and anti-affinity rules in place. So during the first start Kafka and Zookeeper can be scheduled on the same node and the PVCs are requested according to that schedule. And only after that affinity and anti-affinity rules are applied and almost 100% times we get some pods in unschedulable state. The only available option is to fix that manually deleting the PVCs that were created within the same node to keep Kafka and Zookeeper spreaded across the cluster.

**Solution that will be very helpful here:**
Add an option to a Kafka CR so the StatefulSets can be created with different pod management policies:

**_podManagementPolicy: OrderedReady/Parallel_**

**Comment by scholzj** [comment]
To be honest, I think we can add this as a new field. But I'm not sure I understand the problem. I assume you have the affinity / anti-affinity set in the Kafka CR from the beginning? In that case, it should be taken into account already from the beginning ragardless of the policy with which the pods are started. So I wonder if this will help.

What version of Kubernetes are you using? I know that older versions had a problem that the volume scheduling ifnored the affinity rules. And as a result it happend that pods were scheduled in place where the storage was not available (for example in case of AWS where the volumes cannot move freely accross availability zones). That was sometimes happening for example around 1.11.

So, have you tried for example with some hacked build of Strimzi that it actually helps if you change the policy?

**Comment by ladmitry** [comment]
Thank you for the quick reply.
1) Yes, you are right, the issue is only related to old Kubernetes versions. In our case we use Openshift 3.11 (i.e. Kubernetes 1.11).
2) No, yet we haven't try to use any hacked build of Strimzi. But we have no issues with any other StatefulSets where OrderedReady policy is used.

**Comment by scholzj** [comment]
Oki, If you are sure it helps with your situation, I can have a look at it.

**Comment by ladmitry** [comment]
Thank you.

**Comment by scholzj** [comment]
Ok, I opened a PR for it. But it will probably get only into 0.18 - since we are already too far away with the RCs for 0.17.

**Comment by ladmitry** [comment]
Cool. Thanks.
