### ISSUE TITLE
How to connect kafka broker using other project openshift ( external)

### ISSUE THREAD

**Issue by saneerayapa** [strimzi/strimzi-kafka-operator#2576]
Hi 

I have a project running Kafka with the default configuration

1) how to configure this can be accessed via another openshift project such as microservices ( to send and consume messages)  - can you provide me yaml example 

Thanks
Saneera

**Comment by scholzj** [comment]
That depends heavily on how your OpenShift is configured. If you are using the multitenant network plugin, you will need to set the project with Kafka broker as global or join the projects. If you use flat network or netork policies, there should not be anything special you would need. In the client, just connect to the brokers using following URL: `<cluster-name>-kafka-bootstrap.<namespace>.svc` where `<cluster-nme>` is the name of your Kafka CR and `<namespace>` is the name of your project.

**Comment by saneerayapa** [comment]
Hi @scholzj 
Thanks for your reply, I have openshift running with
 os_sdn_network_plugin_name='redhat/openshift-ovs-networkpolicy'  configuration and  deployed kafka with external type  loadbalancer , I tried connect using external client and do telnet the external ip which I got oc get service my-cluster-kafka-external-bootstrap -o=jsonpath='{.status.loadBalancer.ingress[0].ip}{"\n"}') command,
but its not listing , what should be the issue

Thanks

Saneera

**Comment by scholzj** [comment]
You mean that the `oc get service my-cluster-kafka-external-bootstrap -o=jsonpath='{.status.loadBalancer.ingress[0].ip}{"\n"}')` command doesn't return anything? That yould happen probably if the loadbalancer is either not created or does not have an IP (but a DNS name instead). Can you just try to do `oc get service my-cluster-kafka-external-bootstrap -o yaml` and paste the output here? Thanks.

**Comment by saneerayapa** [comment]
ir returns ip 

 ```
kubectl get service my-cluster-kafka-external-bootstrap -o=jsonpath='{.status.loadBalancer.ingress[0].ip}{"\n"}'
172.29.77.233
```

**Comment by saneerayapa** [comment]
oc get service my-cluster-kafka-external-bootstrap -o yaml
error: the server doesn't have a resource type "service"

**Comment by saneerayapa** [comment]
oc get service my-cluster-kafka-external-bootstrap -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-25T23:00:46Z"
  labels:
    app: strimzi-persistent
    app.kubernetes.io/instance: my-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: strimzi
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka-external-bootstrap
  name: my-cluster-kafka-external-bootstrap
  namespace: kafka-loadbalancer-nosec
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: my-cluster
    uid: 93d12613-5822-11ea-9af0-02b950c9b09a
  resourceVersion: "927034"
  selfLink: /api/v1/namespaces/kafka-loadbalancer-nosec/services/my-cluster-kafka-external-bootstrap
  uid: a88c44b5-5822-11ea-9af0-02b950c9b09a
spec:
  clusterIP: 172.30.172.45
  externalIPs:
  - 172.29.77.233
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-external
    nodePort: 30083
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.29.77.233

**Comment by scholzj** [comment]
Ok, so that looks good. Now you can try to do `telnet 172.29.77.233 9094` if you want and see if it works or not.
