### ISSUE TITLE
kafka with OAUTH

### ISSUE THREAD

**Issue by saneerayapa** [strimzi/strimzi-kafka-operator#2596]
Hi  I have followed documentation install kafka with OAUTH configuration

https://strimzi.io/2019/10/25/kafka-authentication-using-oauth-2.0.html

but after executed oc apply -f keycloak.yaml -n keycloak
 kubectl logs $POD -n keycloak -f
**/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json (Permission denied)**

can you provide me the reason for this issue 

or is there anyway we can configure kafka with OAUTH config 

Thanks

Saneera

**Comment by scholzj** [comment]
@mstruk Any ideas?

**Comment by mstruk** [comment]
It looks like there is a problem deploying the latest Keycloak docker image.

Rather than jboss/keycloak which uses jboss/keycloak:latest image, try with jboss/keycloak:8.0.2

**Comment by saneerayapa** [comment]
Great it works fine thanks
