### ISSUE TITLE
[Enhancement] Supply CRDs via chart

### ISSUE THREAD

**Issue by xrow** [strimzi/strimzi-kafka-operator#2604]
**Is your feature request related to a problem? Please describe.**

Since helm 3 you can ship the crds via a helm in a seperate directory called "crds". 

**Describe the solution you'd like**
I would like strimzi to implement / use this feature.

**Describe alternatives you've considered**
do it by hand as mentioned in the docs

**Additional context**
https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/

**Comment by samuel-hawker** [comment]
I believe this has been addressed in: https://github.com/strimzi/strimzi-kafka-operator/issues/3203

Closing.
