### ISSUE TITLE
Strimzi download images 

### ISSUE THREAD

**Issue by saneerayapa** [strimzi/strimzi-kafka-operator#2614]
Hi 
I need to do the following tasks

-  Download Strimzi images and push into another repository 
- configure the new image path on the operator  to download images 

How do I achieve that 

Thanks
San

**Comment by stanlyDoge** [comment]
Hi,
to download an image you can do 
`docker pull strimzi/image:tag`
To push the image to another repository you can do
```
docker tag docker.io/strimzi/operator:tag docker.io/your-repository/operator:tag
docker push docker.io/your-repository/operator:tag
```
To change the image used by the operator you should take a look at file `strimzi-kafka-operator/install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml`

`spec.template.spec.containers.image` is the cluster operator image itself. To change other paths you can change them in `spec.template.spec.containers.env`, for example, `STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE`. Set the value to your image and re/apply this file to install the operator with images from your repository.

**Comment by saneerayapa** [comment]
@stanlyDoge 
Thanks, Stanly, I m going to use helm chart for openshift deployment, so I need to do the same thing for that also

**Comment by scholzj** [comment]
The Helm Chart has configuration options which allow you to configure the images as well. Please have a look at the Helm Chart README.md file: https://github.com/strimzi/strimzi-kafka-operator/tree/master/helm-charts/strimzi-kafka-operator
