### ISSUE TITLE
[Enhancement] .Support for multiple authentication mechanism for Kafka

### ISSUE THREAD

**Issue by arun-blacklane** [strimzi/strimzi-kafka-operator#2617]
**Is your feature request related to a problem? Please describe.**
We want to use OAuth as the main authentication mechanism for Kafka using Strimzi.
But there are some clients which does-not support OAuth by default(Some of them are third party consumers for which we don't have direct support to modify clients)

**Describe the solution you'd like**
In kafka there is an option to support multiple authentication mechanism for brokers.
`sasl.enabled.mechanisms` option in server.properties
[(https://cwiki.apache.org/confluence/display/KAFKA/KIP-43%3A+Kafka+SASL+enhancements#KIP-43:KafkaSASLenhancements-Supportformultiplemechanismsinabroker)]
Was looking at Strimzi documentation and seems like we don't have a way to support this.
Is this currently supported in strimzi?

**Describe alternatives you've considered**
For the existing clients that we have control over, we can make changes in client side to use OAuth authentication. 
But we are stuck on making it available with clients which doesn't support a specific authentication mechanism.(We want to have a restricted access to these clients based a different authentication mechanism)

**Comment by scholzj** [comment]
As answered in #2616, this is currently not supported. We plan to add support for more listeners - would being able to define one listener with SCRAM and one with OAUth work for you? Supporting multiple authentication types is a bit more complicated because you can in theory combine OAuth and SCRAM, but not OAuth and TLS. So it is more complicated to handle.

**Comment by arun-blacklane** [comment]
@scholzj 
Thanks for the response.
I think first option should work for us. We can have a dedicated listener for the clients that don't use OAuth.
Is there a timeline on when this is to be implemented with Strimzi?

**Comment by scholzj** [comment]
I would love to work on it in one of the next releases. So lets sea before the summer. But as everything - that is just tentative.

**Comment by oulydna** [comment]
Hey guys, do we have a more clear idea when this may be available?

**Comment by scholzj** [comment]
I think this is slowly moving forward. There is now an approved proposal for this change: https://github.com/strimzi/proposals/blob/master/005-improving-configurability-of-kafka-listeners.md ... I hope to get to the implementation during the summer.

**Comment by oulydna** [comment]
Awesome!

**Comment by scholzj** [comment]
Triaged on 17.3.2022: Multiple authentications can be used with multiple listeners. So this should be done.
