### ISSUE TITLE
[Bug] javaSystemProperties only supported in Kafka (but not in KafkaConnect, etc..)

### ISSUE THREAD

**Issue by dspereira-avlino** [strimzi/strimzi-kafka-operator#2618]
**Describe the bug**
We have a KafkaConnect resource which makes use of the `javaSystemProperties` property (and we are using 0.17.0-RC2). However the properties are not being passed to the JVM.

If we describe the KafkaConnect resource, we can see `STRIMZI_JAVA_SYSTEM_PROPERTIES` with the correct jvm values, but these are not passed to the JVM.

From this commit (https://github.com/strimzi/strimzi-kafka-operator/commit/aeec4459183f9e45863a05177cf09f74493eae2a), it appears that what's missing is changing the kafka_connect_run.sh (and the other scripts) to add that environment variable in the same way as what was done for `kafka_run.sh`.

**To Reproduce**
1. Create a KafkaConnect resource with `javaSystemProperties` set with at least one property
2. Go inside container and so something like `ps aux | cat` to see all the properties passed to the JVM
3. You will not see the option set in 1.

**Comment by scholzj** [comment]
CC @stanlyDoge

**Comment by scholzj** [comment]
Thanks for opening this issue @dspereira-avlino - it will be fixed in 0.17.0
