### ISSUE TITLE
Automatic restarts of Kafka Connectors by the operator

### ISSUE THREAD

**Issue by iXmonvi33** [strimzi/strimzi-kafka-operator#2621]
Hello,

I am using strimzi 0.16.2 and i see problem when mssql in K8S die and recreate, strimzi doesn't connect once again and it's failing (SQL connectors doesn't work)

Is there any settings to tell kafka to reconnect to database ?

**Comment by scholzj** [comment]
Strimzi doesn't connect to any database. So I assume you are talking about some connector in Kafka Connect? We are not providing any connectors, so I think you need to raise it with whoever is author of the connector to find out how it is or isn't re-connecting?

Or what would you expect Strimzi to do to get the connector to reconnect?

**Comment by patsadow2** [comment]
I think Strimzi should observer somehow Connectors and rerun it, when it's failed ?

**Comment by scholzj** [comment]
Right now you are expected to use the REST APi to restart the connector if needed. I guess restarting it automatically makes some sense. But it has its pros and cons. For example if the operator does it, it will be restarting it every _2 minutes_ regardess of of your MSSQL state. This might not be what everyone wants.

**Comment by patsadow2** [comment]
The main problem is that kafka-connector fail always after 5-10min and i have to redeploy kafka-connector for mssql manual ;/

**Comment by scholzj** [comment]
So why does it fail every 5-10 minutes?

**Comment by patsadow2** [comment]
I am not sure i was thought that it is some kind of connection problem but i dont know why it happens always after a few minutes, for a few minutes it is working perfectly ;/

**Comment by patsadow2** [comment]
It's from kafkaconnector

![image](https://user-images.githubusercontent.com/19226186/75621929-f616c500-5b9a-11ea-8d5e-769fcbd4a370.png)

**Comment by patsadow2** [comment]
Do you have any script that check kubectl describe kafkaconnector inventory-connector-mssql and then redepoly when fails ?

**Comment by scholzj** [comment]
If such error happens regularly without any reason such as MSSQL issues etc., I suggest you raise it with Debezium, maybe they will have an idea. But I think we should keep this open as an issue for automatically restarting the connectors / tasks. We would have anyway discussed that, so we can use it for tracking.

I do not have any cript which would restart the connector. I have alwaysdone it nly manually using curl as a one of thing.

**Comment by patsadow2** [comment]
Would be great because i cannot bypass it and i am not able to sit and check connection every 5 minutes ;d

**Comment by patsadow2** [comment]
@scholzj Is there any news about implementing it in strimzi ? Some autoreconnect flag ?

**Comment by scholzj** [comment]
I don't think there are any news about this. We didn't got to it yet. Sorry.

**Comment by davispw** [comment]
Can I request the title be updated?

Q: Is anyone using Kafka Connect or KafkaMirrorMaker2 without an automatic way to restart failed tasks?

Standing up a dev environment, it’s likely that KafkaConnect/KafkaMirrorMaker2 may randomly start before the target database/kafka starts, and the task will fail, and never restart.

In production, even the slightest hiccup can kill a task, after which it will never restart. 

Every other Kubernetes resource is designed for auto-reconciliation and failure handling,  usually by auto-restarting if unhealthy.

Cron Jobs seems like the hacky answer for now.

I’m interested in working on a patch for this.  Was there a reason a flag like autoRestart:true would not work?

**Comment by laidan6000** [comment]
Hi @davispw . I just want to make sure you're aware of this recently merged PR:

https://github.com/strimzi/strimzi-kafka-operator/pull/4114

**Comment by davispw** [comment]
@laidan6000 Indeed I wasn’t. Resolves this issue, then? :-)

**Comment by laidan6000** [comment]
@davispw - I hope so!

**Comment by scholzj** [comment]
For the record, the annotations are part of Strimzi 0.22 - so not yet released.

**Comment by estahn** [comment]
We're just looking at this. Will the second part contain an interval check to do this action automatically? I'm aware this is not what everyone wants, so a `restartUponFailure: true` option would be helpful.

https://rmoff.net/2019/06/06/automatically-restarting-failed-kafka-connect-tasks/

**Comment by scholzj** [comment]
Automatic restarting is something what was planned, but was not implemented yet.

**Comment by naormatania** [comment]
Just wanted to say this feature will be very helpful for my team.
We were running debezium connector on postgres. The connector failed and stopped because of a database update.
Since no one noticed the alert, the connector was down for several days which caused our database to reach its max capacity (due to WAL not being cleaned).
Automatic restarting would have solved this problem without forcing someone to be alerted on the issue.

**Comment by nikunjy** [comment]
are you open to PRs on this @scholzj

**Comment by scholzj** [comment]
@nikunjy Sure, of course. I don't think we discussed the API in detail before. I think it is important to make this opt-in feature to make sure nobody is negatively affected by this. So perhaps some annotation either on the `KafkaConnect` resource like for using the `KafkaConnector` resources which is there already or as an annotation on `KafkaConnector` resources directly (but that would make it useable only for users using the KafkaConnector resources I guess - which is fine by me, but might not work for everyone).

**Comment by scholzj** [comment]
Triaged on 17.3.2022: Covered by the Strimzi Proposal 007 -> needs to be implemented.

**Comment by scholzj** [comment]
Fixed in #7500
