### ISSUE TITLE
Kafka readiness probe fails on minikube/OSX

### ISSUE THREAD

**Issue by pixime** [strimzi/strimzi-kafka-operator#2623]
my-cluster-kafka-0 crashLoopBackOff on Minikube macOSX, any idea ?

Commands
-----
$ kubectl get pods -n=kafka                                   
NAME                                        READY   STATUS             RESTARTS   AGE
**my-cluster-kafka-0                          1/2     CrashLoopBackOff   15         132m**
my-cluster-zookeeper-0                      2/2     Running            0          132m
my-cluster-zookeeper-1                      2/2     Running            0          132m
my-cluster-zookeeper-2                      2/2     Running            0          132m
strimzi-cluster-operator-77555d4b69-tt268   1/1     Running            2          3h8m

$ kubectl describe  pods my-cluster-kafka-0  -n=kafka
...
Containers:
  kafka:
  ...
 **Readiness:      exec [test -f /var/opt/kafka/kafka-ready] delay=15s timeout=5s period=10s #success=1 #failure=3**
...
Events:
  Type     Reason     Age                   From               Message
  Normal   Scheduled  <unknown>             default-scheduler  Successfully assigned kafka/my-cluster-kafka-0 to minikube
  Normal   Pulled     132m                  kubelet, minikube  Container image "strimzi/kafka:0.16.2-kafka-2.4.0" already present on machine
  Normal   Created    132m                  kubelet, minikube  Created container tls-sidecar
  Normal   Started    132m                  kubelet, minikube  Started container tls-sidecar
  Normal   Started    131m (x4 over 132m)   kubelet, minikube  Started container kafka
  Normal   Created    130m (x5 over 132m)   kubelet, minikube  Created container kafka
  Normal   Pulled     35m (x10 over 132m)   kubelet, minikube  Container image "strimzi/kafka:0.16.2-kafka-2.4.0" already present on machine
  **Warning  BackOff    23s (x247 over 132m)  kubelet, minikube  Back-off restarting failed container**

Environment:
----
- minikube v1.7.3
- strimzi 0.16-2
- macOS Catalina 10.15.3

Installation:
----
following QuickStart instructions, https://strimzi.io/quickstarts/minikube/
- minikube memory 4096 (tested with 6128 as well)
- strimzi installation file strimzi-cluster-operator-0.16.2.yaml
- kafka yaml file : 0.16.2/examples/kafka/kafka-persistent-single.yaml

**Comment by scholzj** [comment]
Can you please share the logs from the `my-cluster-kafka-0` pod? Also, are you sure you are using the `0.16.2/examples/kafka/kafka-persistent-single.yaml` file? Because that should have only one Zookeeper node while your example shows 3 of them.

**Comment by pixime** [comment]
Here is the logs of my-cluster-kafka-0 pod.

You are right, I made a mistake, it is 0.16.2/examples/kafka/kafka-ephemeral-single.yaml. But I firstly use the "persistent" one (1 zookeeper replica) and it fails. Then I choose to switch to "ephemeral" (1 zookeeper replica) with the same results.

[kafka-0-tls-sidecar.log](https://github.com/strimzi/strimzi-kafka-operator/files/4272422/kafka-0-tls-sidecar.log)
[kafka-0-kafka.log](https://github.com/strimzi/strimzi-kafka-operator/files/4272423/kafka-0-kafka.log)

**Comment by scholzj** [comment]
That is weird. There is nothing what would suggest any problem. Did you gave the Minikube enough CPU?

**Comment by pixime** [comment]
Following your advice, this is what I did:

$ minikube config set cpus=4
$ minikube config set memory=4096
$ minikube delete

then
$ minikube start
(now with 4 cpus)
 
finally I have reinstalled the stack as explained in the QuickStart and now **it works fine**,

Thanks
PS: maybe emphasize use of more than 2 cpus (default minikube config)  in the QuickStart...

**Comment by scholzj** [comment]
Ok, great. Glad it works and thanks for the update. I will have a look at updating the website.

**Comment by scholzj** [comment]
BTW: Weird enough I tried it my self with exactly the same configuration (MacOS 10.15.3, Minikube 1.7.3, 2 cpu and 4GB RAM) and it worked fine for me ... IT world is weird:-( ... I guess not every CPU is the same size maybe?
