### ISSUE TITLE
TLS 1.3 for brokers

### ISSUE THREAD

**Issue by saneerayapa** [strimzi/strimzi-kafka-operator#2624]
Hi 

I need to deploy kafka broker with TLS 1.3 is there any possibility to do with operator side 

Thanks 

Sam

**Comment by scholzj** [comment]
TLS v1.3 will be available only in Kafka 2.5.0 AFAIK: https://issues.apache.org/jira/browse/KAFKA-7251

**Comment by saneera** [comment]
@scholzj thanks for your answer 
So TLS1.3 is supported by Apache Kafka form version 2.5 onwards. Is strimizi planning to provide Kafka 2.5 image in near future.

**Comment by scholzj** [comment]
Usually we support new Kafka versions in the next Strimzi release after their release. But what does that mean exactly depends ... first of all Kafka 2.5.0 is not released yet and depending how the testing of the RCs goes, it can be released tomorrow but also next month. Once it is released, we usually add it fairly quickly - but it also depends on how it falls into our release cycle when will be the next Strimzi release etc.  If it is release right after our release it might take longer than if it is released in the middle of our release cycle.
