### ISSUE TITLE
use existing zookeeper

### ISSUE THREAD

**Issue by samyan123** [strimzi/strimzi-kafka-operator#2630]
Hi 
In Strimzi can configure to use existing zookeeper instance or strimzi zookeeper can use for other application as well like hadoop 
thanks
Sam

**Comment by scholzj** [comment]
No, that is not possible. Strimzi deploys and uses its own Zookeeper. This is for secrity and stability reasons.

**Comment by saneera** [comment]
Thanks @scholzj 
Regarding Zookeeper "My bad, the question was bit unclear. The question I wanted to ask is, can we use Strimzi ZooKeeper to manage other server clusters e.g. Hadoop etc. If yes, is there any documentation / online material explaining what all other components currently supported, and related process to begin with."

"So just to confirm, can we use Strimzi ZooKeeper to manage other server clusters e.g. Hadoop etc. If yes, is there any documentation / online material explaining what all other components currently supported, and related process to begin with."

**Comment by scholzj** [comment]
Ok, sorry for not covering that. The Zookeeper we deploy is locked down with TLS client authentication, so other applications will be unable to connect. So you will be unable to use it for Hadoop or something else. Sorry.

**Comment by saneera** [comment]
Thanks @scholzj , much appreciated.
Sorry for the pest.. Just to get my understanding correct and how zookeeper interacts with broker etc. Does Zookeeper even authenticate broker using TLS Client authentication? And If yes, is the client certificate embedded within the broker/zookeeper image, and therefore no way we can extend Zookeeper for other components.

**Comment by scholzj** [comment]
The Zookeeper and whole its communication is wrapped into the sidecar containers which take care of encryption and authentication. If you really want, you can use something like this https://gist.github.com/scholzj/6cfcf9f63f73b54eaebf60738cfdbfae to expose it. But on your own risk and I do not recommend it.
