### ISSUE TITLE
[Question] Can I make only one service LoadBalancer's type?

### ISSUE THREAD

**Issue by tsyrfa** [strimzi/strimzi-kafka-operator#2632]
Hello!

I want to make external access to the Kafka cluster. Now I am using `.spec.kafka.listeners.external.type` with the value of` loadbalancer`, but in this case I need to pay for several load balancers. For example, if I created 3 copies of kafka, I got 4 loadbalancers
```
kafka-cluster-kafka-0 LoadBalancer 10.156.209.37 10.154.1.42 9094: 31204 / TCP 30d
kafka-cluster-kafka-1 LoadBalancer 10.156.130.61 10.154.1.20 9094: 30999 / TCP 30d
kafka-cluster-kafka-2 LoadBalancer 10.156.239.216 10.154.1.43 9094: 30854 / TCP 30d
kafka-cluster-kafka-external-bootstrap LoadBalancer 10.156.223.71 10.154.1.4 9094: 30781 / TCP 30d
```

But I only need one. Is there an option to create only `kafka-cluster-kafka-external-bootstrap` type` LoadBalancer` ?

**Comment by scholzj** [comment]
So if you create only one, how would you access brokers?

**Comment by tsyrfa** [comment]
sorry for long answer

I configuring kafka cluster for interaction with clickhouse cluster like conumer, Clickhouse not in k8s cluster. As I understand, I need use external-kafka-bootstrap service for connect by clickhouse

**Comment by scholzj** [comment]
The external bootstrap service is just for the initial connections. The clients open the connection through it and get the metadata. But then they need to connect to the different brokers individually. That is where the other loadbalancers are used for. I wrote a blog post series about how this works: https://strimzi.io/2019/04/17/accessing-kafka-part-1.html

So it is a bit more complicated and just having the bootstrap loadbalancer is not enough.

**Comment by tsyrfa** [comment]
I will read this blog and answer you. Maybe it that I searching few days ☺

**Comment by avif** [comment]
You could expose kafka with ingress, that will use only the ingress controller LB for all external traffic.

**Comment by tsyrfa** [comment]
Sorry for the long answer - I tested my application.
As I understood from the blog - I needed to give only one kafka broker for my application. For example, kafka-bootstrap and kafka cluster themselves choose which of kafka will respond. It is right?

**Comment by scholzj** [comment]
Yes - the client connects to basically any random member of the Kafka cluster, gets the metadata and than opens (possibly many) subsequent connectios to individual brokers based on where the partiotions/replicas it wants to talk to are.

**Comment by tsyrfa** [comment]
OK, Thanks!
I think I incorrect configure my application or kafka cluster - I gave `kafka-bootstrap` service like brocker's address and I saw that all traffic goes to only one kafka. Can you reccomend tool for debug it?

**Comment by scholzj** [comment]
It doesn't really matter that you give it just one address. It will find the rest from the brokers. You do not need to configure every single broker. I'm not aware of any debugging tools. Just use the Kafka Java client with enabled logging.

**Comment by scholzj** [comment]
@tsyrfa Is there still something we can help with? Or should we close the issue?

**Comment by tsyrfa** [comment]
Hello!

Thanks, all ok. We can close this issue

**Comment by scholzj** [comment]
Great, thanks.
