### ISSUE TITLE
[Doc] Metrics documentation seems outdated / inaccurate

### ISSUE THREAD

**Issue by jotak** [strimzi/strimzi-kafka-operator#2633]
Hello,

The documentation about metrics refers many times to some example files: https://strimzi.io/docs/master/#ref-metrics-config-files-str

It is unclear where these files can be found. The `examples/metrics` directory, which is what is documented, contains only a single file: https://github.com/strimzi/strimzi-kafka-operator/tree/master/examples/metrics

After exploring the repository, I believe the example directory is instead: `metrics/examples` ; it has more content although still doesn't match the directory structure from documentation: https://github.com/strimzi/strimzi-kafka-operator/tree/master/metrics/examples

Perhaps a direct link to the github repository in documentation could help.

**Comment by scholzj** [comment]
I think the confusion here is that during the release, these files end up in `examples/metrics`. So in the released docs the location is valid, but not in the master version. I think we should move it to make it work on both places. I will open a PR to move the location to the same place.
