### ISSUE TITLE
[Enhancement] Use context.succeeding/failing to remove boilerplate result checks in tests

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#2647]
**Is your feature request related to a problem? Please describe.**
As someone who makes changes to Strimzi I would like the tests  to be as  short and informative as possible.
By using context.succeeding or  context.failing we can make the intent of whether we want the test to fail or pass more clear, we can also remove the boilerplate of failing the test and printing the stack track by using these functions.

It also will unwrap the future as either an error for failing and the returned type on success meaning the readability of the return types is imroved

Before:
```
.setHandler(ar -> {
             if (ar.failed()) {
                testContext.failNow(new RuntimeException("Rolling failed", ar.cause()));
            }
           ....
        });
```

After:
```
           .setHandler(testContext.succeeding(v -> {
                ...
            }));
```

**Describe the solution you'd like**
I have a small draft of how I would like to improve the tests:
https://github.com/strimzi/strimzi-kafka-operator/compare/master...samuel-hawker:context-succeeding?expand=1

Whilst making changes I also used some more informative HamCrest matchers, so that on failure the error stack will be easier for debugging. (especially in cases where it returns true != false and the `reason` field was used to get around this.

**Comment by scholzj** [comment]
This looks good to me. @tombentley did you had a chance to look at this?

**Comment by tombentley** [comment]
This looks like a great idea. I guess there's a lot more tests which would benefit than the tests in the linked branch, right? If you're proposing to fix them all @samuel-hawker then I suggest you batch them across a number of PRs.

**Comment by samuel-hawker** [comment]
@tombentley thanks so much!

Yes, I just wanted to take a smallish sample of the tests, convert them to show the value in what I propose. The long term aim would be to convert them all.

I am happy to open what I have already done as a PR, or I can continue to work on this branch and open more PRs, whatever your most preferable size of review to be.

**Comment by tombentley** [comment]
@samuel-hawker I think a dozen source files at a time would be good (perhaps smaller for some of the bigger tests). 

@strimzi/contributors please can you take note of this issue so that any new tests you write use the new convention, to avoid Samuel having to mop up any new tests added while he's converting the old tests.

**Comment by samuel-hawker** [comment]
@scholzj should we close this now do you think? I am fairly happy we have most of instances of the old way of writing tests converted.

**Comment by scholzj** [comment]
I think that if you are happy with it we can definitely close it.
