### ISSUE TITLE
[Enhancement] Use reconcile() to delete resource in the operator-common ITs

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#2659]
**Is your feature request related to a problem? Please describe.**
Whilst looking through the Integration tests i noticed the below comment in several places:
```        
// The resource has to be deleted this was and not using reconcile due to https://github.com/fabric8io/kubernetes-client/pull/1325
// Fix this override when project is using fabric8 version > 4.1.1
```

Strimzi is now on fabric8 version `4.6.4` - these should be cleaned up to use reconcile and the comments deleted.

I propose this be done and would be happy to pick this up, unless there was any specific reason this has not been done yet and the comments have not been updated to reflect that?

**Comment by scholzj** [comment]
@tombentley Do you know anything about this?

**Comment by samuel-hawker** [comment]
Examples of this comment in the code can be found in these places: https://github.com/strimzi/strimzi-kafka-operator/search?q=https%3A%2F%2Fgithub.com%2Ffabric8io%2Fkubernetes-client%2Fpull%2F1325&type=

**Comment by tombentley** [comment]
@scholzj I don't recall it specifically, but I see no reason not to do it (and @stanlyDoge seems to have done so in https://github.com/strimzi/strimzi-kafka-operator/pull/2665)
