### ISSUE TITLE
How to connect Kafka with TLS through Java？？

### ISSUE THREAD

**Issue by ZPJeck** [strimzi/strimzi-kafka-operator#2690]
How to connect Kafka with TLS through Java？？

**Comment by scholzj** [comment]
Can you share more details? What is your configuration, what have you tried, what errors are you getting? All the available TLS options for the Java clients are described in the Kafka documentation: http://kafka.apache.org/documentation/

**Comment by ZPJeck** [comment]
My java program is a pod, then how can I use certificate connection? I will not use，Do you have any good cases?

**Comment by scholzj** [comment]
Ok, here is an example of how you can do it: https://github.com/strimzi/client-examples/blob/master/java/kafka/deployment-ssl-auth.yaml

All you really need is to mount the secrets with the certificates into the pod as files and than use them from your Java applications. If you use Strimzi 0.15 or newer, the Strimzi secrets will have PKCS12 files which can be read by Java directly. If you use some older version, you will have to use some startup script or init container to convert them from PEM format to PKCS12 or JKS.

In the Java application you just need to configure the client:

```java
props.put("security.protocol", "SSL");
props.put(SslConfigs.SSL_TRUSTSTORE_LOCATION_CONFIG, "/.../truststore.p12");
props.put(SslConfigs.SSL_TRUSTSTORE_PASSWORD_CONFIG, "123456");
props.put(SslConfigs.SSL_TRUSTSTORE_TYPE_CONFIG, "PKCS12");
props.put(SslConfigs.SSL_KEYSTORE_LOCATION_CONFIG, "/.../user.p12");
props.put(SslConfigs.SSL_KEYSTORE_PASSWORD_CONFIG, "123456");
props.put(SslConfigs.SSL_KEYSTORE_TYPE_CONFIG, "PKCS12");
```

The repo above has an example YAML file for deployment as well as the corresponding Java source codes, so feel free to look at it there.

**Comment by ZPJeck** [comment]
Thank you very much. I will try it

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
