### ISSUE TITLE
clarification about OAuth configuration

### ISSUE THREAD

**Issue by saneera** [strimzi/strimzi-kafka-operator#2696]
@scholzj 
Hi 

I found out the one GitHub repo Kafka-enablement-2020 in your repositories, I am trying to implement OAuth security on my OpenShift environment , so I followed your example provided in security section
one thing I m not sure about 05-kafka-oauth.yaml you mentioned in external section 

```
   tlsTrustedCertificates:
            - secretName: ingress-operator-crt
              certificate: ingress-operator.crt
```

is this a manually created how do I create them 

Thanks

**Comment by scholzj** [comment]
Yes, that is IIRC created manually. It contains the CA used by the OpenShift Router I guess collected as described here: https://github.com/strimzi/strimzi-kafka-operator/issues/2662#issuecomment-596834569

**Comment by saneera** [comment]
Thanks @scholzj

**Comment by saneera** [comment]
@scholzj 

Hi 
I have one use case implement active directory security on kafka cluster (openshift setup with active directory)
do you think it is feasible 
if it is what steps I need to take care of

Thanks
Saneera Yapa

**Comment by scholzj** [comment]
@mstruk would be the guy to ask. Not sure if anyone ever tried the Keycloak-AD federation with Kafka.

**Comment by mstruk** [comment]
@saneera I haven't seen it in practice yet, which also means I have no test for it, but it should work by using Keycloak's User federation with [Kerberos LDAP](https://www.keycloak.org/docs/latest/server_admin/#_kerberos), configuring Active Directory as Kerberos based user store, like @scholzj suggested.

Configuring Kerberos LDAP as user store does not affect flows between Kafka client and Keycloak or Kafka broker and Keycloak, and as far as I understand should be invisible to any OAuth implementation what user store you configure for User Federation in Keycloak.

Let us now if you have any issues trying to set it up.

**Comment by saneera** [comment]
@mstruk  thanks, very appreciate it, I need to know I need to configure active directory only without keycloak , is there any different way of doing that or same as you mentioned in above comments, 
 my environment is like openshift with active directory implementation so I need to implement security on Kafka using active directory as OAuth server not keycloak

**Comment by mstruk** [comment]
@saneera Kafka has support for [GSSAPI](https://kafka.apache.org/documentation/#security_sasl_kerberos) which allows you to connect your broker directly to LDAP / Active Directory store.  However, Strimzi Cluster Operator does not support configuring this mechanism through Kafka CR.

@scholzj Is there any kind of override mechanism one might use to inject config properties directly into strimzi.properties file?

**Comment by scholzj** [comment]
@mstruk You mean to get GSSAPI working? Kerberos does not work well in any kind of containerized environments because of how it needs to deal with the tickets etc. It is not supported and there is no plan to add it.

**Comment by mstruk** [comment]
@scholzj Yes, that's what I meant.

@saneera I guess your best bet is to use Keycloak with LDAP integration as I suggested.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
