### ISSUE TITLE
[Enhancement] consolidate *CrdOperatorIT.java tests to use an Abstract test Class

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#2699]
Whilst working on issue #2647 I noticed that all the classes with the name: `strimzi-kafka-operator/operator-common/src/test/java/io/strimzi/operator/common/operator/resource/*CrdOperatorIT.java` have the _exact_ same tests.

The classes effected by this:
```
./operator-common/src/test/java/io/strimzi/operator/common/operator/resource/KafkaBridgeCrdOperatorIT.java
./operator-common/src/test/java/io/strimzi/operator/common/operator/resource/KafkaConnectCrdOperatorIT.java
./operator-common/src/test/java/io/strimzi/operator/common/operator/resource/KafkaCrdOperatorIT.java
./operator-common/src/test/java/io/strimzi/operator/common/operator/resource/KafkaMirrorMaker2CrdOperatorIT.java
./operator-common/src/test/java/io/strimzi/operator/common/operator/resource/KafkaMirrorMakerCrdOperatorIT.java
./operator-common/src/test/java/io/strimzi/operator/common/operator/resource/KafkaUserCrdOperatorIT.java
```

I propose here https://github.com/strimzi/strimzi-kafka-operator/commit/283d50f0fa0646b17ef9507a25608a7895b15c01 that we make a single Abstract class called `AbstractCustomResourceOperatorIT` that has a number of abstract fields and methods that will greatly reduce code duplication and make additional CR additions easier to write tests for.

I am happy to open a standalone PR and convert all of the above mentioned Custom Resources

**Comment by samuel-hawker** [comment]
Some possible remarks I thought of, but wasn't sure whether to include in my above implementation was two additions abstract methods 
```
abstract String resourceName();
abstract String namespace();
```

So that we can supply constants so that each test runs its own namespace and own custom resource names, the latter being less important.

**Comment by scholzj** [comment]
As with everything CRD I would probably deffer to @tombentley ... but from how you describe it, it sounds like a reasonable idea to me.

**Comment by samuel-hawker** [comment]
^^ Made a draft https://github.com/strimzi/strimzi-kafka-operator/pull/2701/files happy to tweak it.
