### ISSUE TITLE
Unify documentation for k8s, OS, document templates separately

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#270]
Now that the YAML examples have been reorganized the documentation for installing and using the Operators is more or less the same on both kubernetes and openshift. The only real difference is that the openshift examples usually use the templates.

We could document the templates separately, and switch to using the "static" example configmaps for the bulk of the documentation, which would mean less cluster-specific subsections for k8s and OS. This would should make it simpler for readers too.

**Comment by scholzj** [comment]
Is this still something we want to do?

**Comment by tombentley** [comment]
Personally I still find it a drag writing docs and having to document both platforms in nearly identical ways. Getting the `+`s in all the right places just makes me sad. The what feedback we've had from people reading the docs is that it's confusing seeing instructions for both, when really a given reader is only interested in one of the other. So I'm still in favour of doing this, but I'd like to know what others think. @laidan6000 @ncbaratta @ppatierno @kyguy @stanlyDoge

**Comment by ncbaratta** [comment]
I'd love to separate these into two 2 documents.  That's what Enmasse did recently as well: https://github.com/EnMasseProject/enmasse/pull/1990

**Comment by scholzj** [comment]
The EnMasse PR is IMHO crazy ... it must add significant amount of overhead to maintain these as separate documents. Especially given there is no tooling for the modular docs and managing the modules. If we can generate it from single document, it might be more reasonable.

**Comment by tombentley** [comment]
I agree, on the face of it, it does seem a strange way to do it: Why do they use, for example, documentation/assemblies/assembly-infrastructure-configuration-oc.adoc and documentation/assemblies/assembly-infrastructure-configuration-kube.adoc to set platform specific parameters prior to including a common doc, rather than just configuring those parameters at the top level?
