### ISSUE TITLE
[Question] Behaviour of Kafka (Sink) Connector when source topic does not exist

### ISSUE THREAD

**Issue by anekdoti** [strimzi/strimzi-kafka-operator#2752]
Hello,

I would like to understand better how a KafkaConnector resource describing a SinkConnector is managed, when its source topic not yet exists. For example, it seems to be possible that this might happen when the source topic is defined by a Topic resource and a race condition occurs.
Are their attempts made to restart the connector in such cases, until the topic is present?

Thank you very much ahead for the clarification!

**Comment by scholzj** [comment]
I do not think we do any restarts at present. You have to do them over the REST API.

**Comment by scholzj** [comment]
I will close this since there was no update for more than 10 days. If you have something more feel free to open a new issue, reopen this one or get in touch with us on Slack or mailing list.
