### ISSUE TITLE
[Question] Prometheus metrics from zookeeper

### ISSUE THREAD

**Issue by tsyrfa** [strimzi/strimzi-kafka-operator#2764]
Hello!

I want to get indicators from kafka and the zoo to prometheus. As written in https://strimzi.io/docs/master/#assembly-metrics-setup-str, I added the `metrics' parameters for kafka and zookeeper in the cluster and created an exporter.
If I connect to the exporter, I see only Kafka indicators
[Metrics.log] (https://github.com/strimzi/strimzi-kafka-operator/files/4404998/metrics.log)
What could I do wrong?

**Comment by scholzj** [comment]
Each component exposes its own metrics on its own Prometheus endpoint. The Kafka Exporter is there to provide additional metrics - not to collect the metrics from Kafka and Zookeeper. It provides metrics which Kafka it self does not offer such as consumer lag, information about consumer offsets and partition offsets etc.

To get the metrics from Kafka and Zookeeper them self, you need to scrape them from KAfka and Zookeeper pods directly. They have the endpoint exposed on port 9404.

Hope this helps.

**Comment by tsyrfa** [comment]
Yes, it helps - I found zookeeper service with port 9404, and kafka service.
Thanks!

**Comment by scholzj** [comment]
Great. I will close this issue then. Feel free to open a new one or comment on this one if you have anything more.
