### ISSUE TITLE
[Bug] Endpoint /apis/kafka.strimzi.io/v1beta1/namespaces not found

### ISSUE THREAD

**Issue by uocxp** [strimzi/strimzi-kafka-operator#2765]
**Describe the bug**

Reconciliation is failing with this error
```log
KafkaAssemblyOperator:468 - Reconciliation #0(watch) Kafka(freshanalytics-kafka/my-cluster): Failed to update status

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.30.0.1/apis/kafka.strimzi.io/v1beta1/namespaces/freshanalytics-kafka/kafkas/my-cluster/status . Message: 404 page not found
```
when I curl the endpoint ` /apis/kafka.strimzi.io/v1beta1/` i get:
https://paste.ubuntu.com/p/YDVK6hKfYv/

**Question**
Is there actually any prerequisite concerning the Kubernetes version? Since i am not finding in the documentation any hint about the required Kubernetes version.

**To Reproduce**
```bash
oc apply -f https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.17.0/strimzi-cluster-operator-0.17.0.yaml
oc apply -f https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/master/examples/kafka/kafka-persistent.yaml
```

**Environment (please complete the following information):**
 - Strimzi version: 0.17.0
 - Installation method: YAML files
 - Kubernetes cluster:  OpenShift 3.9
 - Infrastructure: bare metal

**Comment by scholzj** [comment]
Strimzi 0.17.0 does not support OpenShift 3.9. It supports Kubernetes 1.11 and higher and OpenShift 3.11 and higher. I think that is why you get the error - with the PUT request, the operator is trying to update the status of the custom resource, but the status subresource is not supported by OpenShift 3.9. 

I think 0.11 was the last version which supported OpenShfit 3.9.
