### ISSUE TITLE
[Question] Is it possible to stop the Strimzi Topic operator from deleting kafka topics when reconciling?

### ISSUE THREAD

**Issue by MrFishFinger** [strimzi/strimzi-kafka-operator#2775]
The reason we ask, is because when we restore a kakfa backup, the strimzi operator deletes the topics contained in the restore, that do not match those stored as KafkaTopic CRD objects!

We are using this strategy to **backup** our cluster:
1. scale down all components of strimzi (zookeeper/broker/operator)
2. backup contents of zookeeper/broker PVCs at the filesystem level
3. scale back up strimzi (zookeeper/broker/operator)

Then to **restore** we follow this process:
1. scale down all components of strimzi (statefulsets/deployments)
2. wipe content of zookeeper/broker PVCs
3. restore backups into zookeeper/broker PVCs
4. scale up zookeeper and broker stateful sets
5. scale up operator deployments

If we stop at point 4 of the restore process, all is fine. All the topics that were stored in the backup are visible and accessible.
The issue comes when we scale up the operators.  At this point the Strimzi operator detects that the topics in the restored kakfa instance do not match the "KafkaTopic" kubernetes CRD objects, and proceeds to delete the topics from kafka via the reconciliation process.

Is there a way to stop this behaviour?  Is it possible to somehow force Strimzi to use the kafka instance as the "source of truth" for topics?

thanks!

example operator log:

```
[2020-03-31 15:18:34,062] INFO <opicOperator:473> [oop-thread-0] 2|initial kafka redacted-topic-name-test3_AAA: Reconciling topic redacted-topic-name-test3_AAA, k8sTopic:null, kafkaTopic:nonnull, privateTopic:nonnull
[2020-03-31 15:18:34,064] INFO <opicOperator:345> [oop-thread-0] 2|initial kafka redacted-topic-name-test3_AAA: Deleting topic 'redacted-topic-name-test3_AAA'
[2020-03-31 15:18:34,106] INFO <opicOperator:473> [oop-thread-0] 0|initial kafka redacted-topic-name-test4_CCC: Reconciling topic redacted-topic-name-test4_CCC, k8sTopic:null, kafkaTopic:nonnull, privateTopic:nonnull
[2020-03-31 15:18:34,107] INFO <opicOperator:345> [oop-thread-0] 0|initial kafka redacted-topic-name-test4_CCC: Deleting topic 'redacted-topic-name-test4_CCC'
```

**Comment by scholzj** [comment]
There is a section in the documentation dedicated to restoring a cluster from PVs only: https://strimzi.io/docs/latest/full.html#cluster-recovery_str ... please have a look if you haven't seen it yet. It should explain most of the details on how to do it to not have the topics deleted.

You can also configure your Kafka cluster to never delete topics, that would help as well.

**Comment by MrFishFinger** [comment]
hi @scholzj , thanks for the pointer to that documentation, that was very useful!

For our needs, I adapted our restore process to ensure that the existing KafkaObjects are deleted before restoring, as well as deleting the "/strimzi" path in zookeeper before the operators start up.

see below for our updated restore process:

1. scale down all components of strimzi (statefulsets/deployments)
2. wipe content of zookeeper/broker PVCs
3. delete all KafkaTopic objects from namespace (`oc --namespace=kafka-strimzi-dev delete KafkaTopic --all`)
4. restore backups into zookeeper/broker PVCs
5. scale up zookeeper and broker stateful sets
6. delete the "/strimzi" path with zookeeper-shell:
```
oc --namespace=kafka-strimzi-dev rsh kafka-strimzi-dev-kafka-0 bin/zookeeper-shell.sh 
localhost:2181

deleteall /strimzi
``` 
7. scale up operator deployments, and observe that the KafkaObjects are created from what it finds in the kafka instance
