### ISSUE TITLE
[Enhancement] Add the correct labels and annotations for better visualization

### ISSUE THREAD

**Issue by hguerrero** [strimzi/strimzi-kafka-operator#2788]
**Is your feature request related to a problem? Please describe.**
I would like to have labels created for the zookeeper, kafka and operator deployments as well as annotations so I can use visualization tools for better grouping. 

**Describe the solution you'd like**

I suggest adding the [Kubernetes Labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) like `app.kubernetes.io/part-of: wordpress`

Also can add the OpenShift specific:

https://docs.openshift.com/container-platform/4.2/applications/application_life_cycle_management/odc-viewing-application-composition-using-topology-view.html

`app.openshift.io/connects-to`

**Describe alternatives you've considered**

**Additional context**

Tools for visualization will use this labels and annotations for representation of components, like the OpenShift developer console (topology view).

**Comment by ppatierno** [comment]
So actually, the 0.17.0 release already has:

`app.kubernetes.io/instance`
`app.kubernetes.io/managed-by`
`app.kubernetes.io/name`

the `app.kubernetes.io/part-of` is in the master branch so it will be available in the next release.
Regarding the more specific `app.openshift.io/connects-to` it was mentioned here by @scholzj but it's not added but we agree that it could be a useful one.

**Comment by samuel-hawker** [comment]
Agreed with @ppatierno 
Though I might add `app.openshift.io/connects-to` is optional and would only need to be around if a user wanted to opt-in, and if this is the case, adding it to the `metadata.labels` of your `Kafka` custom resource should apply to all Strimzi resources the same label
https://github.com/strimzi/strimzi-kafka-operator/blob/1a2d6783dffe4db3931663cb4464e37a666f8a2f/operator-common/src/main/java/io/strimzi/operator/common/model/Labels.java#L411

**Comment by scholzj** [comment]
I think the question is if `app.openshift.io/connects-to` should be set automatically for Kafka -> Zoo and EO -> Kafka & Zoo.

**Comment by samuel-hawker** [comment]
Apologies that makes a lot more sense, agreed this looks like a great improvement.
The `app.kubernetes.io/name` labels are now `kafka` and `zookeeper` so it should just be a case of adding the above mentioned label. :)

**Comment by hguerrero** [comment]
What about `app.openshift.io/runtime`? I understand it will display the runtime logo in the future?

**Comment by scholzj** [comment]
> What about app.openshift.io/runtime? I understand it will display the runtime logo in the future?

So what runtime do we use in your opinion? I think it would be nice if you would be able to specify your own icon. But apart from that since we do not have any actual runtime to share I'm not sure it makes sense.

**Comment by ppatierno** [comment]
I agree about the icon and it seems that the `runtime` label is related to that. From the Hugo linked page, I read:

> Icon displayed in the node
Icons in the node are defined by looking for matching icons using the app.openshift.io/runtime label, followed by the app.kubernetes.io/name label. This matching is done using a predefined set of icons.

my question is, where is this predefined set of icons?

**Comment by hguerrero** [comment]
I'm using this [list](https://github.com/openshift/console/blob/master/frontend/public/components/catalog/catalog-item-icon.tsx) and it works for other runtimes. This team mentioned there will be one for Kafka in the near future.

**Comment by ppatierno** [comment]
But we want to distinguish between Strimzi and Kafka and ZKs.
I would have Strimzi icon for CO and EO, Kafka icons on Kafka pods and finally ZK icon on ZK nodes.

**Comment by scholzj** [comment]
Triaged on 26.5.2022: The Kubernetes labels are now added out of the box. Any additional labels can be added by the user. If some more labels should be set out of the box, a new clean issue should be opened.
