### ISSUE TITLE
Monitoring strimzi kafka cluster

### ISSUE THREAD

**Issue by daxtergithub** [strimzi/strimzi-kafka-operator#2804]
Hi 

We are running a small stress test for the kafka. We have 3 node broker cluster with 3 partitions and replica set to 3. Is there a way we can validate the Kafka statistics i.e.:
1)   No. of messages (Count) published to the broker
2)   A message published to broker
This is to ensure that all the messages published from the producer have been successfully received by Kafka broker without any data loss. 
Though we are logging the message and incrementing the counter in the producer applications upon receiving the ACK (1) from the broker.
However, to be doubly sure that the broker hasn’t lost any message, can we check it from the broker that all the message being published and the total count across all the partitions of the topic

Thanks

**Comment by scholzj** [comment]
TBH, I guess this is more Kafka than Strimzi question. I guess yuo could check the last offsets in the topic which should correspond to the messages roughly. But I think the only way to be really sure is to check with a consumer which verifies all the messages.

**Comment by daxtergithub** [comment]
@scholzj  Thank you for your response.

Actually we have been trying to use below command to get the latest offset of the topic but it keeps complaining “Topic Doesn’t Exist”. But we have been able to publish and subscribe the messages for the very same topic without any issues. We are using Strimzi images for kafka installation.

bin/kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list localhost:9092 --topic mytopic --time -2 

Also, we run the following command, it successfully returns back with the Topic details without any error.
bin/kafka-topics.sh --zookeeper localhost:2181 --describe --topic mytopic
Any pointers if we are missing anything here.

Thanks

**Comment by scholzj** [comment]
TBH, I never used `bin/kafka-run-class.sh kafka.tools.GetOffsetShell` and have no idea what it does. Sorry.

**Comment by scholzj** [comment]
@daxtergithub Can we close this? Or are there still any open points?

**Comment by veerendra2** [comment]
Are there any tools suggested for stress test? any guide from anyone?
