### ISSUE TITLE
Make it possible to dynamically change the log levels in CO

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2809]
We should make it possible to dynamically change the log levels in CO. Since it is using Log4j2, that might be easier than with Kafka components. 

Would having a config map with a log4j2.proeprties file and enabling auto-reloading the logging config map using https://logging.apache.org/log4j/1.2/faq.html#a3.6 be enough? Or do we need to for example have a REST endpoint which will call something like `((org.apache.logging.log4j.core.LoggerContext) LogManager.getContext(false)).reconfigure()`.

**Comment by stanlyDoge** [comment]
Implemented in the PR https://github.com/strimzi/strimzi-kafka-operator/pull/3328
