### ISSUE TITLE
[Enhancement] Is it possible to move KafkaConnect metrics to external ConfigMap?

### ISSUE THREAD

**Issue by mikekamornikov** [strimzi/strimzi-kafka-operator#2826]
Currently `metrics` definition is like a `2/3` of my `KafkaConnect` resource. From one point of view it's handy to have everything in one place. But at the same time I want to focus on things like `config`, `externalConfiguration` and `resources`. These things may differ if I have several `KafkaConnect` resources. And as a `kustomize` user I prefer to keep base stuff in one place and manipulate lightweight overlays.
Is there a way to extract `metrics`? Additionally is there a way to share base `config`?

**Comment by scholzj** [comment]
It is not possible today. You always have to add the metrics to the custom resource. But I can understand your point. Maybe we can change this to enhancement and make it possible in the future to just link to a config map with the metrics configuration if you want.

**Comment by mikekamornikov** [comment]
Yes, I look at it as a "nice to have". And it aligns with `spec.logging.type: external`.

**Comment by scholzj** [comment]
Ok, I changed the labels and the title. We will keep it in mind, bu TBH right now I do not have any date when we might get to it. Of course, PRs are always welcomed ;-).
