### ISSUE TITLE
kafka monitoring issues

### ISSUE THREAD

**Issue by daxtergithub** [strimzi/strimzi-kafka-operator#2829]
HI 

I have deployed Kafka in Openshiftt environment and enable monitoring  as example provided 

and run Prometheus and grafana dashboard in a different namespace, however, Prometheus not collecting any Kafka metrics it only has default metrics available

 what would be the issue 
is there any way I can make sure that Prometheus is picking up the metrics 
 
Thanks

**Comment by scholzj** [comment]
TBH, this is more Prometheus thing. Not sure anyone from the Strimzi team ever tried running it in different namespace. Checking this in the Prometheus docs might be the best way.

@stanlyDoge @ppatierno Or do you have any idea how to solve this?

**Comment by stanlyDoge** [comment]
If you want to have all the metrics related resources (Prometheus, Grafana) in the other namespace, you have to adjust roles to have needed permissions. Watch patch bellow which is doing this. 

```--- a/examples/metrics/prometheus-install/prometheus.yaml
+++ b/examples/metrics/prometheus-install/prometheus.yaml
@@ -43,7 +43,7 @@ roleRef:
 subjects:
   - kind: ServiceAccount
     name: prometheus-server
-    namespace: myproject
+    namespace: metrics-namespace
 
 ---
 apiVersion: monitoring.coreos.com/v1
@@ -71,7 +71,7 @@ spec:
       app: strimzi
   alerting:
     alertmanagers:
-    - namespace: myproject
+    - namespace: metrics-namespace
       name: alertmanager
       port: alertmanager
   additionalScrapeConfigs:
```
With this we are able to scrape metrics from another namespace

**Comment by daxtergithub** [comment]
Thanks for your reply

Yes I did run all the component  in same project namespace however still not working 

my environment is openshift 3.11 and it also configured openshift Prometheus and grafana on the openshift-monitoring namespace.
any Kafka metrics are not showing in Prometheus I check the logs no errors

is there any way I can check the kafka is publishing the metrics and Prometheus logs 

Thanks

**Comment by stanlyDoge** [comment]
If you changed Prometheus configuration you should be able to see a set of discovered targets under `Targets` tab in Prometheus UI. If nothing is there, something is set wrong.
Did you use Prometheus Operator or are you installing Prometheus manually?

**Comment by ppatierno** [comment]
You can also try to check if metrics are exposed from the Kafka pods.
Just do an `oc rsh` on one of the Kafka pod and run `curl http://localhost:9404/metrics` and check that the JMX exporter is exposing metrics starting with `kafka_`.

**Comment by stanlyDoge** [comment]
@daxtergithub Did you manage to get metrics from Kafka pods as Paolo suggested?

**Comment by scholzj** [comment]
@daxtergithub Are there still any open points on this? Or can we close it?
