### ISSUE TITLE
[Question]  Is there a way to use Entity Operator with external clusters?

### ISSUE THREAD

**Issue by schmichri** [strimzi/strimzi-kafka-operator#2834]
Hi there, 

is there a way to manage non-Strimzi-Operator Clusters with the Entity Operator (ACLs, Topics) and not installing the Kafka Operator?

At my current client we have a bunch of Clusters with "special" feature e.g. Kerberos and hard hostbindings. Nevertheless we require to manage the clusters  in a gitops manner and try to use the strimzi operator for that. Is this anyhow possible?

Looking forward to potential answers. 
Thanks 
Chris

**Comment by scholzj** [comment]
You can deploy the Topic Operator and User Operator in what we call _standalone_ mode:
* https://strimzi.io/docs/latest/full.html#deploying-the-topic-operator-standalone-deploying
* https://strimzi.io/docs/latest/full.html#proc-deploying-the-user-operator-standalone-deploying-uo

**Comment by schmichri** [comment]
Thats awesome. Thanks!
