### ISSUE TITLE
[Bug] ...kafka exporter  crashloopbackoff

### ISSUE THREAD

**Issue by superbeer** [strimzi/strimzi-kafka-operator#2842]
when have more traffic in kafka. kafka expoter crashloopbackoff.
it is error form describe pod.
Liveness probe failed
Readiness probe failed:
i am assign more CPU and  RAM . but not work. i'm test limit and no limit  already.
node is more cpu and ram .

**Comment by scholzj** [comment]
Can you share your configuration? How many resources you gave it? Can you also share the logs from the exporter - ideally on a debug level?

**Comment by superbeer** [comment]
kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*"
    # resources:
    #   requests:
    #     limits:
    #     cpu: 2000m
    #     memory: 1128Mi
    logging: info
    enableSaramaLogging: true
    readinessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 30
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 30
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka-exporter"

**Comment by jgray1206** [comment]
We have been having the same issue. No matter the time or resources we throw at the exporter, it always seems to stop working during periods of heavy load in Kafka.

**Comment by stanlyDoge** [comment]
There is an open PR which should improve Kafka Exporter's performance: https://github.com/danielqsj/kafka_exporter/pull/147

**Comment by SpeedEX** [comment]
> There is an open PR which should improve Kafka Exporter's performance: [danielqsj/kafka_exporter#147](https://github.com/danielqsj/kafka_exporter/pull/147)

I feel that it will not merge and release any time soon. Any alternative to use ? How about https://github.com/lightbend/kafka-lag-exporter ?

**Comment by scholzj** [comment]
The lag exporter is just as any other application at the end. So you should be able to connect it easily and give it a try.

**Comment by kpiyush17** [comment]
@scholzj 
Is there a way to remove liveliness and readiness probes for Kafka exporter?
My yaml config for the exporter:

```
kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
```
I am not specifying any liveliness or readiness here.

**Comment by scholzj** [comment]
The liveness and readiness probes have default values. You can configure them as described in the docs but not disable them: https://strimzi.io/docs/operators/latest/full/using.html#assembly-kafka-exporter-configuration-deployment-configuration-kafka

**Comment by kpiyush17** [comment]
@scholzj So, any solution for the above issue. I am getting a probe failed issue continuously.

**Comment by scholzj** [comment]
Well, if we had a solution it would not be an open issue. As I told you in the other isue you opened. This is not a problem with the probes. The KE does not work in some situations and the probes are correctly failing it.

**Comment by kpiyush17** [comment]
@scholzj Ok thanks for the help.

**Comment by scholzj** [comment]
Closing this as duplicate to #2480 which can be used to address the exporter issues.
