### ISSUE TITLE
Quickstart links for OKD and minikube lead to 404

### ISSUE THREAD

**Issue by josiemundi** [strimzi/strimzi-kafka-operator#2889]
**Suggestion / Problem**
The quickstart guide links for OKD and minikube lead to a 404 error in the readme of this repo. It seems like they should just link to https://strimzi.io/quickstarts/ and then the user selects which install they want. 

**Documentation Link**
https://github.com/strimzi/strimzi-kafka-operator/blob/master/README.md

**Comment by scholzj** [comment]
Thanks for reporting this. I will have a look.
