### ISSUE TITLE
Add support for Helm 3

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2895]
We should add support for Helm 3. Ideally while also keeping Helm 2 support, since not everyone moved to Helm 3 yet. There is WiP PR which was enver finished which can be maybe resued: #2384

**Comment by sgkiokas** [comment]
@scholzj, I had a look to the aforementioned PR and it doesn't seem far off. The most important thing missing (which would be ideal to template somehow) is a bump up of the `apiVersion` from `v1` to `v2`.

I'd suggest, in order to provide the `Helm3` support as soon as possible, to have initially 2 maintained charts in separate folders, as @dalelane  mentioned, and in a second round of refactoring attempt to merge in into one that can be used as the template that will eventually spits 2 charts.

I'll try to make a first draft in the following days if that's ok.

**Comment by scholzj** [comment]
Great, thanks a lot for looking into this! 👍

**Comment by sgkiokas** [comment]
@scholzj, may I please ask you to assign that issue to me? I won't push anything yet, but I got the Operator installed via `helm3`:

```
Stelioss-MacBook-Pro:strimzi-kafka-operator stelios$ helm3 list
NAME	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                       	APP VERSION
test	es       	1       	2020-05-02 19:43:24.072464 +0100 BST	deployed	strimzi-kafka-operator-0.1.0	0.1.0
Stelioss-MacBook-Pro:strimzi-kafka-operator stelios$ kubectl get pods
NAME                                        READY     STATUS    RESTARTS   AGE
strimzi-cluster-operator-55d76fb8f8-mpjx2   1/1       Running   0          77s
Stelioss-MacBook-Pro:strimzi-kafka-operator stelios$
```

I imagine the app/chart version will remain `0.1.0`, right?

**Comment by scholzj** [comment]
TBH, I have no idea abotu the real meaning of the chart version. I think it is 0.1.0 since beginning.

**Comment by sgkiokas** [comment]
@scholzj, apologies for the delay on that issue. I am planning to resume work this Friday (08/05).

**Comment by sebastianortizs4n** [comment]
> TBH, I have no idea abotu the real meaning of the chart version. I think it is 0.1.0 since beginning.

Hi, this is used to install specif versions of the helm chart. You have some tricky configuration, when pushig the the chart to the repo, because in the repo the version is updated.

![image](https://user-images.githubusercontent.com/56325428/84081762-3230a180-a9a4-11ea-9777-37690bc41077.png)

**Comment by sgkiokas** [comment]
@michael-barker if you move forward with your CRD folder update for Helm 3, I imagine you can use this issue as a reference as well.

**Comment by sgkiokas** [comment]
@scholzj, I think the work for that issue has been completed, so it can be closed.

**Comment by scholzj** [comment]
You are right. Thanks.
