### ISSUE TITLE
[Question] I see CrashLoopBackoff for the operator, how do I troubleshoot? 

### ISSUE THREAD

**Issue by zzztimbo** [strimzi/strimzi-kafka-operator#2907]
```
➜ k get po 
NAME                                        READY   STATUS             RESTARTS   AGE
strimzi-cluster-operator-5c876cc5cc-q8kml   0/1     CrashLoopBackOff   144        15h
```

**Comment by scholzj** [comment]
You need to check the log file from the pod (and share it). My guess would be incorrectly installed RBAC file - but it can be many different causes.

**Comment by zzztimbo** [comment]
@scholzj thank you for your recommendation, via email, to give the operator more memory. This seems to improve the situation. 

```
➜ k get po 
NAME                                        READY   STATUS    RESTARTS   AGE
strimzi-cluster-operator-5c4b766d66-scbf9   1/1     Running   85         46h
```

For those that are experiencing a similar situation, you can manage resource limits in a values.yaml when you install the operator. 

https://github.com/strimzi/strimzi-kafka-operator/blob/master/helm-charts/strimzi-kafka-operator/values.yaml#L110-L116
