### ISSUE TITLE
Synchronize the constant names in the configuration classes in model

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2927]
The `*Configuration` classes in the `cluster-operator` module, in package `io.strimzi.operator.cluster.model` seem to use the names `FORBIDDEN_OPTIONS` and `EXCEPTIONS` instead of the `FORBIDDEN_PREFIXES` and `FORBIDDEN_PREFIX_EXCEPTIONS` used in the `api` module. We should synchronize these names to the names used in `api` - i.e. rename them to `FORBIDDEN_PREFIXES` and `FORBIDDEN_PREFIX_EXCEPTIONS`. This refactoring should be done in all the `*Configuration` files where it applies.

**Comment by vdinovi** [comment]
Hi, I've been toying with strimzi and would really like to contribute. Mind if I take this one?

**Comment by scholzj** [comment]
@vdinovi Sure, go for it.I assigned it to you so that nobody else starts working on this.
