### ISSUE TITLE
[Question] Kafka topic creation with underscore

### ISSUE THREAD

**Issue by prabhu-r-ramasamy** [strimzi/strimzi-kafka-operator#2931]
I am trying to create Kafka topic with underscore with the below spec. I am getting the below error. Am i missing any parameter here?. 

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my_topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 1
  topicName: my_topic

Error Message: 
The KafkaTopic "my_topic" is invalid: metadata.name: Invalid value: "my_topic": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**Comment by scholzj** [comment]
Kubernetes resources - such as KafkaTopic - cannot contain `_` in the name. So you will need to name the resource differently. You can use the field `topicName` to work around it, but unless you really need the `_` in the name, you should just use some valid Kubernetes name for the topic and make your life easier. 

More can be found int he docs: https://strimzi.io/docs/latest/full.html#topic-operator-usage-recommendations-str

**Comment by prabhu-r-ramasamy** [comment]
Thanks a lot. I am able to create topic with underscore using topicName.

**Comment by oesebus** [comment]
Hi all , 
Even if i specify the topicName spec field , the ressource name is used by the command to set the name :

- task: Kubernetes@1
    displayName: Create topic ${{ parameters.topicName }}
    inputs:
      command: apply
      useConfigurationFile: true
      configurationType: inline
      inline: |
       apiVersion: kafka.strimzi.io/v1beta2
       kind: KafkaTopic
       metadata:
         name: faketopicname
         namespace: ${{ parameters.namespace }}
         labels:
           strimzi.io/cluster: ${{ parameters.clusterName }}
       spec:
         topicName: topic_A
         partitions: ${{ parameters.partitionCount }}
         replicas: ${{ parameters.replicaCount }}
         config:
          retention.ms: ${{ parameters.retentionMs }}
          segment.bytes: ${{ parameters.segmentBytes }}  
      outputFormat: ''

If i do not specifiy a ressource name , it violates K8S rules . 

Any idea guyz ?

Best regards
