### ISSUE TITLE
[Question] Strimzi Operators Grafana dashboard not working 

### ISSUE THREAD

**Issue by zzztimbo** [strimzi/strimzi-kafka-operator#2932]
I've installed my strimzi operator in ns: operators. 
I've installed my prometheus/grafana in a different namespace. 

Is this the reason why my grafana dashboard for the strimzi operator is blank? 
How do I fix this?

**Comment by tsyrfa** [comment]
Can you be shure that prometheus pulling metrics? I think, you can check that in "targets" appeared your ServiceMonitor's name. I add picture with "targets" in prometheus
Example of service monitor: https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/metrics/prometheus-install/strimzi-service-monitor.yaml


![image](https://user-images.githubusercontent.com/54310392/80789672-5921d980-8b95-11ea-8845-adc6f140b083.png)

**Comment by scholzj** [comment]
@zzztimbo The operators dashabord and the operators metrics are a new feature which will be released only in Strimzi 0.18. So unless you are using the master builds but some stable features, you will not have any of these features available yet.

**Comment by zzztimbo** [comment]
@scholzj I believe I installed the operator using release 0.17.0, but I've been using the metrics example in master. 

Should I reinstall the operator using master? or do you recommend waiting for the 0.18.0 release?

**Comment by scholzj** [comment]
No, you should wait for the 0.18 to be released. You should not use master just because of that. It is always better to use everyhting from the release - I'm not sure if there were some other changes even for the other dashabords.
