### ISSUE TITLE
[Question] Difference between rack.id and broker.rack

### ISSUE THREAD

**Issue by tsyrfa** [strimzi/strimzi-kafka-operator#2942]
Hello!

I put value to kafka-cluster in `spec.kafka.rack.topologyKey`
Now I see in kafka logs that I have a  `rack.id` but in `broker.rack` value is `null`.
And I don't found anythink about  `rack.id`  in kafka documentation
https://kafka.apache.org/documentation/

Is this same?

**Comment by scholzj** [comment]
Can you share the logs / configuration files? Also, what version of Strimzi are you using?

**Comment by scholzj** [comment]
I think this was a bug (basically a typo in the configuration file generator) in 0.16.0. It is now fixed in 0.17.0

**Comment by tsyrfa** [comment]
I using 0.16.0 version
This part of config of kafka (I changed some values, like replicas number or limits. We get values from varriables and it not readeble)
[kafka-config.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4574788/kafka-config.txt)
And kafka's logs
[kafka-0.log](https://github.com/strimzi/strimzi-kafka-operator/files/4574810/kafka-0.log)

**Comment by scholzj** [comment]
Ok - yeah ... as I said above, this looks like a bug in 0.16 which is fixed in 0.17. Sorry.

**Comment by tsyrfa** [comment]
OK!
Thanks!
I think, I will update it
