### ISSUE TITLE
[PROPOSAL] Move to Java 11 - Runtime

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2948]
Following the [Move to Java 11 proposal](https://github.com/strimzi/strimzi-kafka-operator/blob/master/design/java-11.md), we should do the following steps as part of Strimzi 0.19.0:
* Change the runtime in the container images to OpenJDK 11
* Update the CI to push documentation, JARs and container images from the Java 11 build
* Update all build documentation (HACKING.md, etc.) with regards to the changes described above

**Comment by tombentley** [comment]
Can we, as part of this, add the `--illegal-access=deny` to all executions of `java`? It's going to become the default in later JVMs anyway, so it would be good to know we're OK, or at least discover where the problems are well ahead of time.

**Comment by scholzj** [comment]
I have no idea what does that mean. Does it mean adding it to scirpts starting the operators for example?

**Comment by tombentley** [comment]
Yes, plus in the tests.
