### ISSUE TITLE
Make it possible to scale Kafka Mirror Maker 1 to zero replicas

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2965]
The PR #2897 made it possible to scale down KafkaConnect and KafkaConnectS2I to 0. We should make things consistent, so the same should be done to the Kafka Mirror Maker 1 as well. That should be a bit easier, since there is no connector operator involvement. So just make sure the readiness would pass and ensure the right options are set in the status.

**Comment by klalafaryan** [comment]
I would like to take this one on if no one else is working on it.

**Comment by scholzj** [comment]
I do not think anyone is working on this. So feel free to have a look.

**Comment by klalafaryan** [comment]
@scholzj  Should we close this issue since the PR (https://github.com/strimzi/strimzi-kafka-operator/pull/3412) has been merged ?

**Comment by scholzj** [comment]
Good point. Thanks.
