### ISSUE TITLE
Make it possible to scale Kafka Mirror Maker 2 to zero replicas

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2966]
The PR #2897 made it possible to scale down KafkaConnect and KafkaConnectS2I to 0. We should make things consistent, so the same should be done to the Kafka Mirror Maker 2 as well. That should be a bit easier, since there is no connector operator involvement. So just make sure the readiness would pass and ensure the right options are set in the status.

**Comment by klalafaryan** [comment]
@scholzj  I would like to start with this ticket. 
By the way, I have created an unit test, and seems like readiness is passing.

**Comment by scholzj** [comment]
Great ... I assigned it to you. thanks!
