### ISSUE TITLE
Make it possible to scale Kafka Bridge to zero replicas

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2967]
The PR #2897 made it possible to scale down KafkaConnect and KafkaConnectS2I to 0. We should make things consistent, so the same should be done to the Kafka Bridge as well. That should be a bit easier, since there is no connector operator involvement. So just make sure the readiness would pass and ensure the right options are set in the status.

**Comment by 524119574** [comment]
Hi, I'd like to take it on this issue.

**Comment by scholzj** [comment]
Sure, give it go. I assigned the issue to you so that nobody else takes it.

**Comment by 524119574** [comment]
Thanks!
