### ISSUE TITLE
[Question] how to increase logLevel: debug ?

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#2972]
I have issues installing Kafka via Strimzi.
how can I increase logLevel: debug ?

**Comment by scholzj** [comment]
That is very generic question. It is not clear what logging you need if you don't say what the problem is. All the logging is described in the docs: https://strimzi.io/docs/latest/full.html

**Comment by tirelibirefe** [comment]
I tried to deploy kafka as described in documentation as below;
kubectl apply -f kafka-persistent.yaml -n kafka
...Kafka couldn't have been deployed at first couple of attempts. Then It was able to deployed. I didn't understand the cause, so I am going to face with the same problem again probably in future. SO I need increase logging level in order to understand what's going on during deployment more detaily.

**Comment by scholzj** [comment]
You still didn't explained what exactly is failing. So I cannot give you anything more specific than the documentation which describes the logging configuration. If you want to know something more specific, you need to explain what and how was failing ... the Cluster Operator, Zookeeper, Kafka etc.

**Comment by stanlyDoge** [comment]
If you want to set kafka loggers levels, you can do it via Kafka CR. Please take a look at https://strimzi.io/docs/operators/master/using.html#con-kafka-logging-deployment-configuration-kafka

Basically you will just edit your configuration to something like this
```
spec:
  kafka:
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
        #any other logger from the list from the link above
```
Then just apply the new configuration and after the rolling update the logging configuration will be updated.

If you want to change other logging, please describe more details.

**Comment by scholzj** [comment]
@tirelibirefe Did this helped? Can we close this now?

**Comment by tirelibirefe** [comment]
yes,It helped me, thanks.
