### ISSUE TITLE
[Doc] All links using BookURLUsing attribute are broken

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#2982]
It seems that all the links on the website which use the `BookURLUsing` attribute are broken.
For example, following the link to the Kafka Mirror Maker configuration:

```
https://strimzi.io/docs/operators/master/%7BBookURLUsing%7D#assembly-deployment-configuration-kafka-mirror-maker-str
```
It seems that the attribute is not actually rendered as `./using.html`.
The `BookURLDeploying` attribute seems to be ok.

Is this something related just to the website rendering or an overall problem in the doc?

**Comment by scholzj** [comment]
Sharing where the link is would be probably more helpful than sharing the link it self.

**Comment by ppatierno** [comment]
The problem is everywhere, just search for BookURLUsing in the doc. Every link with it has the problem. The above was just an example to show how the link is not rendered well.

**Comment by scholzj** [comment]
I think the link in the actual docs is the interesting part. Not the source codes. I cannot find `BookURLUsing` in https://strimzi.io/docs/operators/master/deploying.html

**Comment by ppatierno** [comment]
In the source code for the doc, the BookURLUsing attribute is set as ./using.html but it's not rendered in this way but with the example above. The BookURLDeploying attribute is set to ./deployment.html and rendered in the right way.

**Comment by scholzj** [comment]
It could have safed me 15 minutes of searching if you actually included the place where the link which doesnt work is :-(

**Comment by ppatierno** [comment]
Does your IDE really need 15 minutes to search for a string? :) Maybe I misunderstood what you meant but reporting the broken links meant to search for them and copying a lot of them here.

**Comment by scholzj** [comment]
The broken link is not in the source code - the broken link is on the website. Got here https://strimzi.io/docs/operators/master/deploying.html and find me the broker links for the Using book.

**Comment by ppatierno** [comment]
I don't understand why searching for broken links in the HTML while I said that ALL the links with `BookURLUsing` in the source code (of course) were broken? But it's fine, the PR is there, I will take a look soon.

**Comment by scholzj** [comment]
No, they were not ALL broken. All links from the Deploying guide to the Using guide work completely and perfectly fine. Only when the sme module is included in the Using guide and links to Using guide the link is broken. That is why searching the source code is not useful without knowing where on the page the broken link is.
