### ISSUE TITLE
[Doc] Missing configuration for Kafka Mirror Maker 2

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#2987]
The "Using Strimzi with Mirror Maker 2.0" section

https://strimzi.io/docs/operators/master/using.html#assembly-mirrormaker-deployment-configuration-kafka-mirror-maker

seems to miss configurations like loggers, cpu and memory, and so on ... which are covered in the Kafka Mirror Maker section instead.
Some parts like cpu and memory could be considered in common with Mirror Maker (but it should be clarified in the doc) but the loggers are for example different: Mirror Maker 2 derives from Kafka Connect so, for example, the right loggers is not `mirrormaker.root.logger` (as for MM) but it's `connect.root.logger.level`.

**Comment by PaulRMellor** [comment]
This PR fixes #2987

https://github.com/strimzi/strimzi-kafka-operator/pull/3071

**Comment by ppatierno** [comment]
@PaulRMellor the "This PR fixes #2987" statement has to be written on the PR not on the issue :-)
Anyway I updated the PR for you.
