### ISSUE TITLE
[How to stop the Kafka/zookeeper]

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#2988]
Hello,

could you advice how we can stop the Kafka/zookeeper application?

i understand there is a method to Stop the Kafka broker through the command `./bin/kafka-server-stop.sh. `
we want to retain the cluster, but stop the application.
we cannot set the` replicas to 0`(not supported by strimzi)
is there are method we can leverage a functionality from Strimzi?

**Comment by scholzj** [comment]
I do not think there is currrently any way how to stop them. You could do the following:
* Scale down the operator to 0 to not interfere with any manual actions
* Delete the stateful sets for Kafka / Zookeeper

Once you want it back, you can just scale the operator back to 1 replica and it will recreate the stateful sets.

**Comment by pashafirdous** [comment]
Hi Jakub,

Thanks,
but we cannot scale the nodes to 0, it is not allowed.
we want to retain the service IP addresses
```
0uFfyor1CRCrAwmlXH9T6m5qDVern0MaOohkeQRiiQMVy7+8q\nlA==\n-----END CERTIFICATE-----\n"}, "type":"external"}}, "observedGeneration":1}}: validation failure list:
spec.kafka.replicas in body should be greater than or equal to 1
spec.zookeeper.replicas in body should be greater than or equal to 1
```

**Comment by scholzj** [comment]
> but we cannot scale the nodes to 0, it is not allowed.

I'm no suggesting to scale to 0 Zookeeper or Kafka. I suggested to scale to 0 the operator and afterwards delete the stateful sets.

> we want to retain the service IP addresses

I don't think the service IP addresses will change if you delete the stateful set. But lot of the communication goes through pod IP addresses and these will change for sure.

**Comment by pashafirdous** [comment]
Hello Jakub,

Thank you so much!
i followed your approach and it helped me.

closing the issue.
