### ISSUE TITLE
PodDisruptionBudget recreated on every cluster reconciliation

### ISSUE THREAD

**Issue by armisz** [strimzi/strimzi-kafka-operator#2993]
Hello,

Could you please advise if it is the expected behavior that the Cluster Operator recreates the _PodDisruptionBudget_ objects for Kafka and Zookeeper on every cluster reconciliation run? The payload of the object never changes, only metadata does.

This seems to be independent from whether I configure `spec.[kafka|zookeper].template.podDisruptionBudget` or not.  I have tested it with Strimzi 0.17.0, older releases may behave the same way.

Thanks
Michael

**Comment by scholzj** [comment]
Could you share some more details? What metadata do change?

**Comment by armisz** [comment]
I diffed the objects of two generations, only obvious ones for object creation change, like  creationTimestamp, resourceVersion and uid.

In the Kafka CR I only set `spec.kafka.template.podDisruptionBudget.maxUnavailable` to 1.

**Comment by scholzj** [comment]
Ok. I will have a look. Is this causing any actual issues?

**Comment by armisz** [comment]
No, it's not causing any issues. Only our object creation stats go through he roof.

**Comment by scholzj** [comment]
Ok, thanks for clarification ... I will keep it in mind. I will look at it. But migth get to it only after the upcomming 0.18.0 release.

**Comment by scholzj** [comment]
Changing this to bug to make it cleaer that this is not just a question.
