### ISSUE TITLE
[Error while producing messages with authorization enabled] 

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3011]
Hello Team,

I have enabled Kafka with a simple authorization
```
  apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: cluster1
  spec:
    clusterCa:
      generateCertificateAuthority: true
    clientsCa:
      generateCertificateAuthority: true
    kafka:
      version: 2.4.0
      replicas: 3
      listeners:
         plain: {}
         tls:
           authentication:
             type: tls
         external:
           type: loadbalancer
           tls:  true
      authorization:
        type: simple
      storage:
        type: persistent-claim
        size: 10Gi
        deleteClaim: false        
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
    zookeeper:
      replicas: 3
      storage:
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
```

when i produce messages either from external of services(bootstrap-external) or exec into the kafka pod.. i am not able to produce messages successfully.

```
[kafka@cluster1-kafka-1 bin]$ ./kafka-verifiable-producer.sh --topic mytopic --max-messages 20000 --broker-list localhost:9092
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
{"timestamp":1589393231850,"name":"startup_complete"}
[2020-05-13 18:07:12,163] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 1 : {mytopic=TOPIC_AUTHORIZATION_FAILED} (org.apache.kafka.clients.NetworkClient)
[2020-05-13 18:07:12,170] ERROR [Producer clientId=producer-1] Topic authorization failed for topics [mytopic] (org.apache.kafka.clients.Metadata)
{"timestamp":1589393232172,"name":"producer_send_error","topic":"mytopic","key":null,"value":"0","exception":"class org.apache.kafka.common.errors.TopicAuthorizationException","message":"Not authorized to access topics: [mytopic]"}
[2020-05-13 18:07:12,260] WARN [Producer clientId=producer-1] Error while fetching metadata with correlation id 3 : {mytopic=TOPIC_AUTHORIZATION_FAILED} (org.apache.kafka.clients.NetworkClient)
[2020-05-13 18:07:12,261] ERROR [Producer clientId=producer-1] Topic authorization failed for topics [mytopic] (org.apache.kafka.clients.Metadata)
{"timestamp":1589393232261,"name":"producer_send_error","topic":"mytopic","key":null,"value":"1","exception":"class org.apache.kafka.common.errors.TopicAuthorizationException","message":"Not authorized to access topics: [mytopic]"}

```

```
[kafka@cluster1-kafka-1 bin]$ ./kafka-verifiable-producer.sh --topic mytopic --max-messages 20000 --broker-list 172.30.193.14:9094
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
{"timestamp":1589392135534,"name":"startup_complete"}
^C{"timestamp":1589392172377,"name":"producer_send_error","topic":"mytopic","key":null,"value":"0","exception":"class org.apache.kafka.common.KafkaException","message":"Producer closed while send in progress"}
{"timestamp":1589392172377,"name":"shutdown_complete"}
{"timestamp":1589392172382,"name":"tool_data","sent":1,"acked":0,"target_throughput":-1,"avg_throughput":0.0}
```

i need to enable both TLS and Authorization with ACL's but i'm not able to produce in any scenarios.

need help.

**Comment by scholzj** [comment]
TLS alone is just encryption of data. It does not do authentication. So the connections over your external listener on 9094 and over the port 9092 will be seen just as ANONYMOUS by the broker. Only the TLS interface on 9093 has authentication.

To make this work properly, you need to enable authentication also on these two interfaces or give some rights to the ANONYMOUS users (for example if you want anyone who can connect to be able to produce messages etc.)

**Comment by vperi1730** [comment]
@scholzj  - I understood your point, I need your thoughts on the below scenario.

I am trying to reproduce the use case from the following article where there is a section  "Configure SSL on Kafka Broker" which talks about editing the config/server.properties which lies inside the Kafka broker pod. As we know the property files are read-only how do we ensure our Kafka broker still reads our keystore file to do the SSL authentication?

**https://jaceklaskowski.gitbooks.io/apache-kafka/kafka-demo-securing-communication-between-clients-and-brokers.html?q=**

**Comment by scholzj** [comment]
TBH, I'm not completely sure I understand what do you mean. With regular Kafka, you would go and edit the server.properties file manually. With Strimzi, you edit the Kafka custom resource and the operator will make sure it is applied to the broker. That does not always mean writting the file - there are also APIs to change some things without restart etc.

That article makes sense. But in case of Strimzi, a lot of that is done for you when you enable the TLS authentication on the listeners. So you do not need to do all the steps from there.

**Comment by pashafirdous** [comment]
closing as we were able to achieve authorization and authentication.

there was a bit of rethinking on the connectivity part.
 we had to work on the user/cluster certificates and find out logic as the connectivity part is not clear in the documentation.

but still thanks Jakub for giving the directions
