### ISSUE TITLE
The request included a message larger than the max message size the server will accept.

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3017]
Hello;
My broker config:

```
config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
      message.max.bytes: 536870912
      replica.fetch.max.bytes: 536870912
      replica.fetch.response.max.bytes: 536870912
```

My kafkaconnect config:

```
  config:
    group.id: dbz-mssql-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    producer.max.request.size: "536870912"
    consumer.max.request.size: "536870912"
```

My connector config:

```
  config:
    database.hostname: 192.168.215.6
    database.port: "1433"
    database.user: "FileLoader"
    database.password: "********"
    database.dbname: "AFileStorageDB"
    database.server.name: "filesql1"
    database.history.kafka.bootstrap.servers: "kafka-beytepe-kafka-bootstrap:9092"
    database.history.kafka.topic: "schema-changes.files"
    max.request.size: "536870912"
```

...but my Kafka stills throws exceptions:

```
...
2020-05-14 01:51:26,729 ERROR WorkerSourceTask{id=mssql-files-connector-0} failed to send record to filesql1.dbo.Files: (org.apache.kafka.connect.runtime.WorkerSourceTask) [kafka-producer-network-thread | connector-producer-mssql-files-connector-0]
org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.
2020-05-14 01:51:27,841 ERROR WorkerSourceTask{id=mssql-files-connector-0} failed to send record to filesql1.dbo.Files: (org.apache.kafka.connect.runtime.WorkerSourceTask) [kafka-producer-network-thread | connector-producer-mssql-files-connector-0]
...
Caused by: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.
...
```

Is there anything else which I should set to increase size?

**Comment by scholzj** [comment]
That is quite a huge message size - I wonder if you need to increase also some other configurations to get that through. There were two similar issues - #2716 and #2592 ... maybe they can also provide some help.

**Comment by tirelibirefe** [comment]
yes it is... 
probably I will need to increase much more in future.
There are files in MS SQL which sizes between 1K - 20GB each one. I need to transfer them somewhere else.  I don't know Kafka is the correct technology or not for this purpose.

**Comment by scholzj** [comment]
Kafka in general is not the best thing for large messages. Normally you should use something HATEOAS pattern. But I guess you don't have choice in this case.

**Comment by tirelibirefe** [comment]
I hadn't ever hard it before but I checked what HATEOAS is when you mentioned. It worth to evaluate. I'm at end of "Kafka on K8s" evaluation and I would like to complete this scenario.
I've initiative for production. Later I read more about HATEOAS  and may evaluate if it suits our needs. Thank you.

**Comment by scholzj** [comment]
@tirelibirefe Did you managed to resovle this? Or are there still some open points?

**Comment by tirelibirefe** [comment]
thank you very much @scholzj 
HATEOAS is an important tool should be taken into the consideration at similar projects.
Thank you.
