### ISSUE TITLE
[Enhancement] Custom Matcher for AssemblyOperator states

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#3018]
**Is your feature request related to a problem? Please describe.**
Brought up in an idea in this Pull request: https://github.com/strimzi/strimzi-kafka-operator/pull/3002#discussion_r424539022
I suggested that we make a generic custom matcher that all AssemblyOperator tests could use (e.g. KafkaAssemblyOperator, KafkaRebalanceAssemblyOperator, etc...)
This would cut down our code due to less duplication of logic and would also make each assertion more idiomatic hamcrest and the intent a little clearer.

**Describe the solution you'd like**
In example from the above linked PR.
This assertState method:
```
assertState(kr1, KafkaRebalanceAssemblyOperator.State.PendingProposal);
```
would be removed and replaced with 
```
assertThat(kr1, hasState(KafkaRebalanceAssemblyOperator.State.PendingProposal));
```

An example of a custom matcher can be found in the CustomMatchers class.

If we made one that was abstract we could simple implement the abstract matcher for this class and make the `AbstractOperatorState` be implemented by `KafkaRebalanceAssemblyOperator.State`for the above example

**Comment by klalafaryan** [comment]
If no one else is working on this, I would like to take it. 
As far as I can see `assertState` has been used only in `KafkaRebalanceAssemblyOperatorTest`. 
Seems like some classes have been changed, could you please give some hints ?

**Comment by samuel-hawker** [comment]
Sure, happy to help in any way I can.

`assertState` only exists in the above mentioned class, but the concept of checking states exists across a multitutude of classes. i.e.,
The logic here
<img width="652" alt="image" src="https://user-images.githubusercontent.com/34167246/87234038-0ea6af80-c3c5-11ea-94fc-b607c38947e5.png">
Of checking a specific state in the `status.conditions` field should be in other classes such as 
[here](https://github.com/strimzi/strimzi-kafka-operator/blob/2e950039d7559ddd7ce6d46aa586f0e66b50e702/cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceStateMachineTest.java#L85-L107) and looking through the [System Tests](https://github.com/strimzi/strimzi-kafka-operator/blob/9b93e9a54f1cda0453758e3bc986361ad4a22449/systemtest/src/test/java/io/strimzi/systemtest/operators/CustomResourceStatusST.java#L530-L539) you will see often we are checking the status of pods, custom resources and deployments, having an abstract CustomMatcher like [this](https://github.com/strimzi/strimzi-kafka-operator/blob/4b7bc42feebf777a92a8de1636a25bec6300d437/cluster-operator/src/test/java/io/strimzi/operator/cluster/CustomMatchers.java#L28-L48) would be useful for re-usability and just a generally more clear what you're checking as a lot of places a 'state check' is just a set of assertitions that require a deeper understanding of what constitutes that state than should be required.
By extending the abstract class you woould make a specific state checker for each implementing class with the knowledge of what to do to check a state for any given class.

**Comment by samuel-hawker** [comment]
Each implementing class would have its own version, i.e.
```
assertThat(kr1, hasState(KafkaRebalanceAssemblyOperator.State.PendingProposal));
```
`KafkaRebalanceStateTest.hasState` and for System Tests you might have something like `DeploymentMatchers.hasState` and `PodMatcher.hasState` all of these implementing the `CustomMatchers.hasState` (or similarly names classes.)
