### ISSUE TITLE
[Question] How to handle connector / tasks failures?

### ISSUE THREAD

**Issue by mikekamornikov** [strimzi/strimzi-kafka-operator#3032]
As I see `Strimzi` can pause/start `KafkaConnector` resources. While regarding real failures there is the following in the `0.17.0` docs:

> Using the APIs, you can:
> Restart failed tasks (not supported by KafkaConnector resource)

I wonder if it's something not implemented yet or a design decision. In any case could you suggest the best approach to keep connector alive and restart connector tasks?

As a use case imagine there is a 3rd-party sink connector reading from topic with 10 partitions to some external service. This connector is configured to have 5 tasks resulting to 2 random partitions per each task. Each tasks has its own connection to external service and may fail on reconnect (or any other reason). Connector is defined as `KafkaConnector` resource. If some task fails what should I expect from `KafkaConnector` resource?

**Comment by scholzj** [comment]
This is something not implemented yet. However, until we implement it, you can use the Connect REST API to restart the connector or tasks manually. Till than, the connector operator will only update the status of the Kafkaconnector resource to indicate it failed but will not attempt to restart anything.

FYI: I think there is some other issue tracking this missing feature.

**Comment by mikekamornikov** [comment]
@scholzj Isn't REST API protected by network policy? As I understand I have to created a pod, job or even a cron job with proper label, right?

**Comment by mikekamornikov** [comment]
I'll try to find related issue.

**Comment by scholzj** [comment]
It is ... although _protected_ is not the right word. The network policy is there to make sure we have the access to the REST API from the operator in case the network policies are configured to deny by default. You can just add your own network policies to give it a wider access if you want.

**Comment by mikekamornikov** [comment]
I've found some issues related to Connector Operator. But none of them actually tracks status updates.

**Comment by scholzj** [comment]
I think this one was for example looking at the connector restarts: https://github.com/strimzi/strimzi-kafka-operator/issues/2621

**Comment by mikekamornikov** [comment]
Thanks, I'm closing this one.
