### ISSUE TITLE
[Question] how to use secrets?

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3048]
Hello;
I came accross to one of @scholzj 's articles which is very helpful what I would like to do.

https://developers.redhat.com/blog/2020/02/14/using-secrets-in-apache-kafka-connect-configuration/

Regarding to the tutorial of Minio https://docs.min.io/docs/minio-server-configuration-guide.html  I would like to put env variables below into a secret.

MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
MINIO_DOMAIN=minio.dev-kik.io
minio server /data

I have cpl of questions:

1)
The last line is not a key value; is it possible to add it to Kubernetes?

2)
In @scholzj 's article there is a  config in connector config:
`"camel.source.url": "aws-s3://camel-connector-test?autocloseBody=false",`

is this URL target bucket url? If yes, should I put there my local Minio url like that "myminio.dev-kik.io" or ""myminio.dev-kik.io/mybucket"" ?

...or should I define my endpoint in Docker container and pass the env as above MINIO_DOMAIN=minio.dev-kik.io ? Which one is the correct way to define endpoint; Docker container env variable or connector configuration?

Thanks & Reagrds

**Comment by scholzj** [comment]
The demo in that blog post was using a Kafka Connector based on Apache Camel. The `camel.source.url` is a special URL of Apache Camel compoenents. I'm not sure how and if it supports S3 compatible servers on custom domains as i used it only with AWS. You would need to refer to Apache Camel (https://camel.apache.org/) for more info.

The way the secrets are assed around is generic through, so it should apply to any connector.

**Comment by tirelibirefe** [comment]
I removed Minio url from secret and defined minio url in connector config, it worked.

`store.url: http://minio.dev-kik.io`
