### ISSUE TITLE
[Question] Allow all kafkausers describe on topic *

### ISSUE THREAD

**Issue by MBarendregt** [strimzi/strimzi-kafka-operator#3056]
Hello, 

I was wondering if it would be possible to give all kafkausers the describe permission on topic * 
I know you can do something on the broker itself like: 

`bin/kafka-acls.sh --authorizer-properties zookeeper.connect=localhost:2181 --add --allow-principal User:*  --operation Describe --topic *`

but is there a way to configure this in the helm chart?  Thanks

**Comment by scholzj** [comment]
No, that is not possible. Kafka doesn't have any options to _pre-configure_ anything like that. So you need to configur eit after deploying the Kafka broker.

**Comment by MBarendregt** [comment]
Allright, thanks for the quick reply :)
