### ISSUE TITLE
[Enhancement] Cruise Control: Provide better log message when incorrect annotation is used

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#3057]
When you provide a wrong value for the `strimzi.io/rebalance` annotation on a `KafkaRebalance` you get this message logged:

2020-05-19 09:50:27 WARN  KafkaRebalanceAssemblyOperator:954 - Wrong annotation value strimzi.io/rebalance=approved on myproject/my-rebalance

The annotation gets removed from the CR and the `Status` condition remains `ProposalReady`. 

It would be better if the logged warning message included the valid values.

**Comment by scholzj** [comment]
As I said before ... this should be also raised in the conditions of the status. I do not think warning in CO logs is enough.

**Comment by tombentley** [comment]
I agree.

**Comment by ShubhamRwt** [comment]
Is this issue still valid @scholzj @tombentley ?

**Comment by scholzj** [comment]
The CC experts should probably know if this was fixed or not.

**Comment by ppatierno** [comment]
@ShubhamRwt have you tried if this still happens but I am not sure it was already fixed. It would be worth a try and then providing valid values for the annotation based on the state of the `KafkaRebalance` resource.

**Comment by ShubhamRwt** [comment]
Not yet @ppatierno , but yes it is on my agenda for today. I will try to replicate it, and see if it still exists.

**Comment by ShubhamRwt** [comment]
Looks like the issue still persists @scholzj @ppatierno

**Comment by ShubhamRwt** [comment]
@scholzj @ppatierno I was facing an issue while I was trying get the warning message in the condition. Actually what happens is when annotate our KR resource, even if its wrong what happens is that the annotations are removed and made `none`. The issue which I am facing is that I was making a check on the basis of annotation but, after a reconciliation the annotation is removed and when the status is built again then the warning doesn't show up since the resource is now updated and `none` annonation is there

**Comment by ShubhamRwt** [comment]
Should I do something like not changing the annotation to `none` if wrong annotation is passed

**Comment by ppatierno** [comment]
Just improving the warning message as Tom suggested would be pretty simple; what Jakub is asking for, which makes sense, is improving the condition in the `KafkaRebalance` status.
I think that if an annotation is wrong we should not remove it anymore but maybe updating the `KafkaRebalance` to `NotReady` with a warning message about the reason (that annotation is wrong). But, right now, the only way to move away from `NotReady` state is applying the "refresh" annotation which means for the user submit a new proposal request, while in the Tom example it was just waiting for approve but applying the wrong annotation.
Maybe we should stay in `PendingProposal` but adding a message in the condition about the error until user doesn't use the right annotation?
@tomncooper @kyguy any more thoughts on this?

**Comment by kyguy** [comment]
>  think that if an annotation is wrong we should not remove it 
+1

> Maybe we should stay in PendingProposal but adding a message in the condition about the error until user doesn't use the right annotation?

Did you mean stay in the `ProposalReady` state? If so I agree that we stay in the `ProposalReady` state and update the condition with an error message that an incorrect annotation was used

**Comment by ppatierno** [comment]
Yeah sorry ProposalReady :-)

**Comment by tomncooper** [comment]
Yeah I think this is a good suggestiong @ppatierno. We should not remove the annotation if it is a `.unknown` type. That way we can continue to post the warning condition via the `onProposalReady` method.

**Comment by scholzj** [comment]
Triaged on 26.5.2022: Seems to be done in #5948
