### ISSUE TITLE
defining ENV variables

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3067]
Hello;
I need to define several env variables for KafkaConnect.
...
CONNECT_KEY_CONVERTER="io.confluent.connect.avro.AvroConverter" \
CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL="http://url:8081" \
CONNECT_VALUE_CONVERTER="io.confluent.connect.avro.AvroConverter" \
CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL="http://url:8081" \
CONNECT_INTERNAL_KEY_CONVERTER="io.confluent.connect.avro.AvroConverter" \
CONNECT_INTERNAL_VALUE_CONVERTER="io.confluent.connect.avro.AvroConverter" \
...

should I define these variables in KafkaConnect docker image/container or in Strimzi KafkaConnect yaml file?

Thanks&Regards

**Comment by scholzj** [comment]
TBH, I'm not sure why do you need to define these. These fields are normally configured in the `KafkaConnect.spec.config` section of the custom resource. But assuming you really want them, you should be able to set them this way: https://strimzi.io/docs/operators/latest/full/using.html#con-customizing-containers-str
