### ISSUE TITLE
Topic controller's AdminClient config

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#307]
The topic controller should set `client.id` in its AdminClient config, so Kafka logging has a bit more contextual info for connections from the TC.

See https://kafka.apache.org/documentation/#adminclientconfigs

**Comment by scholzj** [comment]
Reviewed on 10th September 2020: This is still valid.

**Comment by ShubhamRwt** [comment]
I would like to work on this issue. Is it still valid?

**Comment by tombentley** [comment]
@ShubhamRwt it is still valid, so feel free to work on it.

**Comment by ShubhamRwt** [comment]
Hello @tombentley. I have added the enhancements and written the tests but I am stuck with how I can test it up.

**Comment by tombentley** [comment]
@ShubhamRwt yeah it's a difficult one to test right now, since `Admin` doesn't expose its config once created. I would be inclined to:

1. Refactor `Session` so that the constructor takes a `Function<Properties, Admin>` which would be used to create the client. `Main` would pass as `Admin::create`.
2. Write a `SessionTest` which created a `Session`, using your own impl of the function about which you could later assert on the entries in the `Properties`. Probably no need to actually call `Session.start()` if you factor out a method for creating the client. 

This would open the door to more tests for `Session` as we could then start using mocked `Admin`.
