### ISSUE TITLE
Using `tini` is missing for Cruise Control, Mirror Maker, Exporter and stunnel

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3073]
It seems that `tini` is used for starting Kafka, Kafka Connect (so Kafka Mirror Maker 2), Zookeeper, and the operators but not for Cruise Control, Kafka Exporter, Kafka Mirror Maker and all the stunnel containers.

@dalelane as far as I can see you worked on adding `tini`, apart from Cruise Control that was added in the latest release, any good reason for not using it for the others or you just forgot?
If no valid reasons for not using it, I would work on adding `tini` where it's missing.
Any thoughts?

**Comment by dalelane** [comment]
Good spot - I can't think of a good reason for it to not be there, but I'll have a quick look through the commit/issue history to see if I'm forgetting something.

**Comment by dalelane** [comment]
@ppatierno Can't find any discussion or conscious decision to exclude Connect, but looking at the discussion in https://github.com/strimzi/strimzi-kafka-operator/pull/2710/files#diff-8a63a5aa9b86387e2dd89abbaeb7bdcc I'd gotten the impression that tini is being used for Connect. Am I missing something?

**Comment by ppatierno** [comment]
@dalelane in my issue description, Connect was included :-)
The missing ones are Kafka Exporter, Kafka Mirror Maker, all stunnel containers and of course the latest Cruise Control.
So if no reasons I will add it to all the others. Thanks!

**Comment by dalelane** [comment]
Sorry, you're quite right. Yeah, I think adding it to the others would be a good idea, thanks

**Comment by ppatierno** [comment]
@dalelane one more question ...
for Kafka, for example, tini is used in this way

```shell
# starting Kafka server with final configuration
exec /usr/bin/tini -w -e 143 -- sh -c "${KAFKA_HOME}/bin/kafka-server-start.sh /tmp/strimzi.properties"
```

a new shell is started with `sh`.
While for the operators we have just

```shell
exec /usr/bin/tini -w -e 143 -- java $JAVA_OPTS -classpath $JAVA_CLASSPATH $JAVA_MAIN $@
```

any reasons for this difference?

**Comment by dalelane** [comment]
Not sure, to be honest. I need to do some googling to refresh my memory, because I think it does make a difference doesn't it? 

A bit of experimenting might shed some light, too. (e.g. trying with and without the `sh -c` and see the difference it makes to a `ps` list)

**Comment by ppatierno** [comment]
@dalelane I did a little bit of testing with and without `sh -c` and I didn't notice any kind of huge difference. 
The output for a `ps -aux` command on Kafka container (using `sh -c`) is a kind of:

```shell
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000140+     1  0.0  0.0   4356   356 ?        Ss   12:32   0:00 /usr/bin/tini -w -e 143 -- sh -c /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
1000140+    54 28.0  4.2 5670972 343684 ?      Sl   12:32   0:14 java -Xms128M -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.
1000140+   599  0.5  0.0  11824  1628 ?        Ss   12:33   0:00 /bin/sh
1000140+   606  0.0  0.0  51756  1652 ?        R+   12:33   0:00 ps -aux```

while without `sh -c`:

```shell
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
1000140+     1  0.0  0.0   4364   308 ?        Ss   12:21   0:00 /usr/bin/tini -w -e 143 -- java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.18.0.jar:lib/io.prom
1000140+     9  4.8  2.4 1750956 196460 ?      Sl   12:21   0:19 java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.18.0.jar:lib/io.prometheus.simpleclient_common-
1000140+    92  0.0  0.0  11824  1636 ?        Ss   12:27   0:00 /bin/sh
1000140+    99  0.0  0.0  51756  1656 ?        R+   12:27   0:00 ps -aux
```

They are quite the same, aren't they?
Did you dig into it?

**Comment by tombentley** [comment]
@ppatierno can you do the experiment again but including the `PPID` (`ps -ef`)?

**Comment by ppatierno** [comment]
@tombentley just done ... following the output for a Kafka container and the CO switching on/off `sh -c` for both.
Tbh I still don't see any difference in terms of parent process.

Kafka

```shell
UID        PID  PPID  C STIME TTY          TIME CMD
1000140+     1     0  0 12:32 ?        00:00:00 /usr/bin/tini -w -e 143 -- sh -c /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
1000140+    54     1  1 12:32 ?        00:00:43 java -Xms128M -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=true -Dc
1000140+   599     0  0 12:33 ?        00:00:00 /bin/sh
1000140+  5035   599  0 13:21 ?        00:00:00 ps -ef

UID        PID  PPID  C STIME TTY          TIME CMD
1000140+     1     0  0 13:27 ?        00:00:00 /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
1000140+    54     1 44 13:27 ?        00:00:06 java -Xms128M -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCInvokesConcurrent -XX:MaxInlineLevel=15 -Djava.awt.headless=true -Dc
1000140+   536     0  1 13:27 ?        00:00:00 /bin/sh
1000140+   542   536  0 13:27 ?        00:00:00 ps -ef
```

CO

```shell
UID        PID  PPID  C STIME TTY          TIME CMD
1000140+     1     0  0 13:29 ?        00:00:00 /usr/bin/tini -w -e 143 -- sh -c java  -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom  -classpath lib/io.strimzi.cluster-operator-0.19.0-SNAPSHOT.jar:lib/io.prom
1000140+     9     1 53 13:29 ?        00:00:10 java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.19.0-SNAPSHOT.jar:lib/io.prometheus.simpleclient_common-0.7.0.ja
1000140+    82     0  0 13:29 ?        00:00:00 /bin/sh
1000140+    89    82  0 13:30 ?        00:00:00 ps -ef

UID        PID  PPID  C STIME TTY          TIME CMD
1000140+     1     0  0 13:28 ?        00:00:00 /usr/bin/tini -w -e 143 -- java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.18.0.jar:lib/io.prometheus.simpleclie
1000140+     9     1 43 13:28 ?        00:00:09 java -Dvertx.cacheDirBase=/tmp -Djava.security.egd=file:/dev/./urandom -classpath lib/io.strimzi.cluster-operator-0.18.0.jar:lib/io.prometheus.simpleclient_common-0.7.0.jar:lib/io.
1000140+    68     0  0 13:28 ?        00:00:00 /bin/sh
1000140+    74    68  0 13:28 ?        00:00:00 ps -ef
```

**Comment by tombentley** [comment]
In all cases `java`s direct parent is `tini` and tini is pid 1, so I think we're good.

@Frawless can we add an assertion to STs that pid1 is `tini` for all containers, so we don't forget this in the future?

**Comment by ppatierno** [comment]
So I am going to add `tini` where it's missing but I still don't understand what's the reason for having or not having `sh -c` for running the `java` command.
I still don't see any difference.

**Comment by tombentley** [comment]
I guess there is effiectely no difference. When `tini` tries to fork to execute the script as a subprocess the kernel will see it's not a binary and look for the shebang, so it executes under `sh` in either case.

**Comment by ppatierno** [comment]
Yes exactly. So I am going to remove `sh -c` everywhere tbh.

**Comment by tombentley** [comment]
:+1:

**Comment by ppatierno** [comment]
@dalelane out of curiosity ... why did you decide to map exit code 0 to 143 (SIGTERM) (using `-e 143`) ?

**Comment by dalelane** [comment]
@ppatierno Have you seen Jeff's description in https://github.com/strimzi/strimzi-kafka-operator/pull/2219#discussion_r350740873 ?

**Comment by ppatierno** [comment]
@dalelane thanks! No I didn't remeber that!
At this point I would align to it for jmxtrans as well. It seems jmxtrans was already using `tini` but without mapping the exit code. See here:

https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/jmxtrans/docker-entrypoint.sh#L20

**Comment by Frawless** [comment]
@tombentley I think it should be possible, I will open jira for it
