### ISSUE TITLE
[Question] Topics deleted when Topic Operator namespace is recreated

### ISSUE THREAD

**Issue by chromy96** [strimzi/strimzi-kafka-operator#3080]
Hi,

We've been testing Topic Operator with an external Kafka and one thing we tried was to remove the namespace containing the Topic Operator, to see the consequences. As expected, topics were deleted, yet not when the namespace was removed, but when the Topic Operator was deployed again.

We tested it again, now with slightly different steps, which were:
- stop the operator
- remove it
- delete the namespace
- create a new namespace and deploy the operator

The results were the same. After starting, the operator deleted all the topics from the cluster.

I would expect the Operator to delete the topics when underlying CRDs are deleted, but I wasn't expecting this. Then we figured out that the operator also saves the state in Zookeeper. So apparently, since the CRDs are missing, and state exists in the Zookeeper, that gives the operator the signal to remove all the topics.

I know that deleting the namespace is not something one does on a regular basis, but if recreating a namespace is necessary (e.g. moving operator to another Kubernetes cluster to handle the same Kafka cluster), what would be the best approach to do it, so you don't lose all the data in the cluster?

- Is a manual cleanup of Zookeeper needed to prevent this from happening?
- Is there a way to tell the operator to start up not by using the state from the Zookeeper but by syncing with the cluster (as it does on the initial startup)?

**Comment by scholzj** [comment]
The Topic Operator has two sources of truth: The topics in Kafka and the KafkaTopic custom resources in Kubernetes. To reconcile between them, it is using 3rd source of truth which is currently in custom path in Zookeeper:
* If topic exists in Kafka but not in Kubernetes and in the TO store, it has been newly created and the operator will create it as Kubernetes CR and in the TO store. 
* If it exists as KafkaTopic CR and not in Kafka or in the TO store, it has been newly created in Kubernetes and the TO will add it to Kafka and to the TO store
* But if it for example exists in Kafka and in the TO store and not in Kubernetes, it was just delete and the TO will delete it.

And this is what most probably happened in your case: you deleted the namespace including the Kafka Topics. And when you reinstalled it, you did so without the KafkaTopics. The TO saw the topics in Kafka and in the TO store and assumed all the topics were delete. So to recover like this, you need to additionally delete the TO store in Zookeeper before reinstalling the TO.

It is not really written for the standalone TO - but basically this part of the docs should give you guidance how to do it: https://strimzi.io/docs/operators/latest/full/using.html#cluster-recovery_str

**Comment by chromy96** [comment]
Great, thanks for the input.
