### ISSUE TITLE
[Enhancement] Add helm annotation values for kafka operator 

### ISSUE THREAD

**Issue by gitOlf** [strimzi/strimzi-kafka-operator#3096]
Thank you for your great for work on this operator. It is great!

We are using your operator with istio. With the update on version 0.18.0 of the kafka operator we have to annotate the following pod annotation: 
` traffic.sidecar.istio.io/excludeOutboundPorts: "2181"`

If the do not add this annotation the kafka brokers aren't deployed anymore (but the zookeeper instances). Currently we are using a patch to provide the missing annotation. Can you had Kafka Operator Annotations to your helm chart?

I hope we do not missed something, we looked at: 
https://github.com/strimzi/strimzi-kafka-operator/blob/master/helm-charts/strimzi-kafka-operator/templates/050-Deployment-strimzi-cluster-operator.yaml

**Comment by scholzj** [comment]
Yeah, since 0.18, the operator is connecting to Zookeeper to handle the new way how Zookeeper scales and bootstraps in 3.5. This is similar to how it connects to Kafka brokers - so you should already for few releases have similar rule for connecting to Kafka on 9091. 

I do not think we want to hardcode these annotations into the Helm Chart as they might not work for everyone. But I guess if you want you can make that configrable through some parameter maybe?

**Comment by gitOlf** [comment]
Thank you for your quick response. Which ports does the operator require to connect to? Currently we only excluded 2181 not 9091 and if the port 9091 is also required doesn't that mean, we also have to exclude 9092 and 9093 (e.g. for having 3 kafka brokers) or it is enough to have a rule for port 2181. Ref https://github.com/istio/istio/issues/19280 
If I patch the deployment (pod annotation in the deployment) for the operator with an exclude for 2181 and istio-mtls enabled it deploys my kafka brokers, otherwise only the zookeeper instances are deployed, I think because the operator looks into the zookeeper storage to find out if the zookeeper instances are working and to check the kafka setup to deploy? Does it afterwards also want to connect to the kafka brokers to check them and if yes does it have negative side effects if it cant?

I think you misunderstand me, we do not want to hardcode annotations like 
`traffic.sidecar.istio.io/excludeOutboundPorts`. 

We only want to have the opportunity to add additional annotations in the values.yaml in the helm chart. You already provide this option in the kafka cluster resource https://github.com/strimzi/strimzi-kafka-operator/blob/master/helm-charts/strimzi-kafka-operator/templates/040-Crd-kafka.yaml but not in the operator (deployment) resource itself (and we already added additional excludeOutboundPorts annotations in the kafka resource (used since version 0.14.x))

**Comment by scholzj** [comment]
I'm not really an Istio user ... but the operator is connecting to:
* Zookeeper on 2181
* Kafka on 9091
* Kafka Connect on 8083 (if you use it)

So I guess ideally you should exclude all of these?

**Comment by gitOlf** [comment]
Thank you very much again for your quick response. Ok I will exclude them all, do the brokers also try to open connections to the operator or only the operator to the brokers? Istio has the option to have excludeOutboundPorts and InboundPorts

**Comment by scholzj** [comment]
From the other compoenents:
* The brokers talk with each other on port 9091 and with Zookeeper on 2021
* Zookeeper nodes talk with each other on port 2888 and 38888
* The Entity Operator and Cruise Cotnrol talk with Brokers on 9091 and Zookeeper on 2181
* Kafka Exporter talks to Kafka on 9091

Butnone of them connects to the operator - that is one direction only. Hope this helps.
