### ISSUE TITLE
[Question] How to copy Camel kafka connector binaries into Container  in minikube

### ISSUE THREAD

**Issue by saranyaeu2987** [strimzi/strimzi-kafka-operator#3100]
I am using https://developers.redhat.com/blog/2020/02/14/using-secrets-in-apache-kafka-connect-configuration/ to create a kafka S3 sink connector in my minikube.

In KafkaConnector yaml, there is a spec as follows 
```
...
spec:
  class: org.apache.camel.kafkaconnector.CamelSourceConnector
...
```

Question:
1. How Camel connector binaries are copied into container @scholzj ?

**Comment by scholzj** [comment]
In that blog post, I used some older manually build version of the connectors. But now the Camel Kafka connectors have some releases and you can pretty much download them from Maven: https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/ - just pick the connector, and the version and there should be an archive with the connecotr and all the JARs which you just add by following this: https://strimzi.io/docs/operators/latest/deploying.html#creating-new-image-from-base-str

**Comment by saranyaeu2987** [comment]
@scholzj 
Thanks for suggestions. 
I did the same way. but my kafka S3 sink connector is not pushing data into S3 as expected. I have added details in https://github.com/strimzi/strimzi-kafka-operator/issues/3110.

Got stuck for a long time.:( . Any suggestions on how to debug. or fix ?

**Comment by scholzj** [comment]
I don't know much about the connector - all I can help you with is to point you to the docs for changing the log levels which might help you to check the errors: https://strimzi.io/docs/operators/latest/full/using.html#con-kafka-connect-logging-deployment-configuration-kafka-connect
