### ISSUE TITLE
[Question] How to change the stdout log format to JSON in Strimzi kafka

### ISSUE THREAD

**Issue by rramanan15** [strimzi/strimzi-kafka-operator#3104]
Hi All,
I am new to Strimzi Kafka and we have a requirement to write the kafka stdout logs in JSON format. Which will be fed to log analyzer tool.

we have setup the Strimzi  kafka in K8.

Can you please tell me what properties and where it needs to be updated to change the stdout format to json.

Is there a possibility to write the logs into a file as well.

**Comment by scholzj** [comment]
I think you can try to follow this: https://gist.github.com/scholzj/2b92fb7389056b7fe1fa2ca8bb3fbdda

**Comment by rramanan15** [comment]
@scholzj Thanks much. We are able to configure it successfully.
