### ISSUE TITLE
[Question] How to manually start source connector for kafka connect ?

### ISSUE THREAD

**Issue by yuwtennis** [strimzi/strimzi-kafka-operator#3114]
Hello

This is not really specific to strimzi but appreciate if I could get advice.

## Strimzi version

| component | version |
| ------------ | -------- |
| strimzi-kafka-operator | 0.17.0 |
| kafka cluster & zookeeper | 2.4.0 |
| kafka connect | 2.4.0|

## What I am trying to accomplish

I am in middle of creating new kafka connect cluster.
I want to fast-forward connector-offset after creating jdbc source connector but before starting to ingest.

## Question

Any way to _manually_ start source connector ?

Thanks,
Yu

**Comment by scholzj** [comment]
TBH I'm not completely sure what you are asking for. You can manage the conectors using the REST API: http://kafka.apache.org/documentation/#connect_rest - so you can do everything described there including pausing/resuming connectors etc. You can also use the KafkaConnector resource: https://strimzi.io/docs/0.17.0/full.html#proc-deploying-kafkaconnector-str ... in 0.17.0 you can pause / unpause connectors through it as well.

But I do not have any experience with changing the offsets for the connecrors before it starts - so I do not have any advice for that.

**Comment by yuwtennis** [comment]
Thank you for the reply.

I found out that _connector offset topic_  is created at the start up of _Kafka Connect_ container .
So I was able to set offsets before actually creating connector.

Below link shows instruction about manipulating offsets.
https://www.confluent.jp/blog/kafka-connect-deep-dive-jdbc-source-connector/#starting-table-capture

**Comment by scholzj** [comment]
Thanks a lot for the update - that is useful to have here for the future if we need it again.
