### ISSUE TITLE
[Question] I'd like to replicate topics that have protobuf messages using schema registry with MM2

### ISSUE THREAD

**Issue by zzztimbo** [strimzi/strimzi-kafka-operator#3139]
Am I correct in my assumption that MM2 will just replicate the messages over from the source cluster to the destination cluster without any concern that the messages utilized a schema registry?

**Comment by scholzj** [comment]
I'm not aware of any dedicated support for Schema Registry in MM2.

**Comment by scholzj** [comment]
@zzztimbo Did that answered your question? Can this be closed? MM2 is using Kafka Connect as a base framework and at the end it has consumers and producers inside. So you can probably do with it anything you could with any other app of this kind. But to be honest I'm not experienced enough with Schema Registry to be able to help more.
