### ISSUE TITLE
[Question] ... Kafka exporter broker not connected

### ISSUE THREAD

**Issue by kpiyush17** [strimzi/strimzi-kafka-operator#3146]
Hi,

I am getting below errors from Kafka exporter logs:

```
time="2020-06-03T14:38:51Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
time="2020-06-03T14:38:51Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
time="2020-06-03T14:38:51Z" level=error msg="Cannot get consumer group: kafka: broker not connected" source="kafka_exporter.go:361"
time="2020-06-03T14:38:51Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
time="2020-06-03T14:38:51Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
time="2020-06-03T14:38:51Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
time="2020-06-03T14:38:51Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
time="2020-06-03T14:39:02Z" level=error msg="Cannot get consumer group: kafka: broker not connected" source="kafka_exporter.go:361"
time="2020-06-03T14:39:02Z" level=error msg="Cannot get offset of group test-group: kafka: broker not connected" source="kafka_exporter.go:384"
```
As far as I can understand it is not able to connect to Kafka. But our other applications like producer and consumer have no issue connecting to Kafka. We are sending the metrics to datadog. Despite the errors, we are seeing the metrics on datadog. 

Need help understanding the cause of this issue.
Thanks

**Comment by scholzj** [comment]
I guess you already found the other issue with the general problems with KAfka Exporter so we can maybe close this? I do not have any other solution.

**Comment by kpiyush17** [comment]
So, the other issue which I found is related to the probe fail. This issue I am getting even there is no probe issue.

**Comment by scholzj** [comment]
I do not think there is any probe issue. The Kafka Exporter has problems when not all Kafka brokers are running and maybe also when the load is too high. For example during the rolling updates. And because it doesn't work during these situations, the probes are correctly failing it.

**Comment by scholzj** [comment]
Closing this as duplicate to #2480 which can be used to address the exporter issues.
