### ISSUE TITLE
how strimzi kafka and zookeeper connectioin works 

### ISSUE THREAD

**Issue by saneera** [strimzi/strimzi-kafka-operator#3153]
Hi 
I just want to know how strimzi operator defined kafka and zookeper connection with each other as they are running on separate pods 

where can i see the kafka and zookeeper connection configs 

thanks

**Comment by scholzj** [comment]
It is just using the Kubernetes networking to connect them through services and DNS names. The configuration is usually generated at the pod startup - if you exec into the containers, you should be able to see some initial configuration files in `/tmp/`. But for example with Zookeeper, these could be later changed dynamically so they might not apply.

**Comment by saneera** [comment]
Thanks @scholzj any places can I see the dns names may be in logs

**Comment by saneera** [comment]
@scholzj  many thanks
