### ISSUE TITLE
Avoid static imports and add the related checkstyle

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3158]
I think that sometimes the code is not so readable using static imports.
An example is [here](https://github.com/strimzi/strimzi-kafka-operator/pull/3132#discussion_r435145568) using just `sigleton` which seems not to be clear coming from `Collections` but could be a private method in the class.
Of course, using an IDE you have all the facilities to get that but it's not the same while reviewing on GitHub.
As mentioned by @tombentley I would propose to avoid using static imports and adding the related checkstyle https://checkstyle.sourceforge.io/config_imports.html#AvoidStaticImport.
It's more a refactoring work.

Of course, it's possible that my opinion is not commonly shared with the other @strimzi/maintainers 
so if Tom is ok to stick with static imports, what the others think?

**Comment by tombentley** [comment]
There are some classes which I think deserve to be allowed, since they're used very commonly and seeing the qualifying class just adds visual noise. Off the top of my head those classes are:

* `Collections`,
* `Arrays`,
* `Assertions`
* Possibly `Collectors`

A lot of these are already statically imported (as least in most of the code I've touched). But I am in favour of avoiding static imports for, for example, our own `Utils`, `ModelUtils` classes.

**Comment by ppatierno** [comment]
Tbh I am for not allowing static imports for all the classes you mention (I always use the related methods explicitly). The problem happened to me with `singleton` for example. What you call "noise" is quite often useful to read the code better.
Maybe static imports could be allowed for static constants.
Of course, these are my 2 cents.
If others like static imports I will leave with them :-).

**Comment by samuel-hawker** [comment]
I quite like allowing static imports for HamCrest matchers as
```
assertThat(actual, is(expected))
```
is better than 
```
assertThat(actual, Matchers.is(expected))
```

Since matchers are always nested inside assertThats i see no ambiguity as to which class they came from.

**Comment by ppatierno** [comment]
Good point. I agree that with the matchers, the static import makes more sense and it is clear.

**Comment by tombentley** [comment]
@samuel-hawker But what about having to qualify the `assertThat` too? That would, imho, be horrible and add nothing to the readability of the tests.

More generally I would argue that it's just a matter of being familiar with the allowed-to-be-statically-imported classes. Once you know `Collections.singleton()` exists I think it would be pretty obvious that that was the function being called. After all most classes in Strimzi are unlikely to have a method called, simply, `singleton()`. 

Would we allow importing static classes, or would we require those to be class qualified too?

Paolo's argument can also be applied to top level class names: How do I know that any particular class name means what I think it means without being able to inspect the imports? In `Util.foo()` what `Util` is that?

If you try to eliminate all ambiguity from reading diffs then you're having to write code that's just horrible to both read and write in the IDE.

FWIW I'm increasingly finding `gh pr checkout 1234` and then reviewing in the IDE a better way to review more involved PRs, than simply reading diffs. Presumably there are code review tools built into things like VS Code. 

If there's any doubt, I'm willing to accommodate whatever consensus we find.

**Comment by samuel-hawker** [comment]
Sorry yes, I am so used to importing that I hadn't thought about that either. Correcting my comment

**Comment by samuel-hawker** [comment]
I think in general static imports should be allowed in test code. Maybe not so in non-test code? with certain ModelUtils exceptions.

**Comment by scholzj** [comment]
Triaged on 26.5.2022: @ppatierno got used to static imports and suggests to close it :-o.
