### ISSUE TITLE
Define package layering

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#3159]
Broadly speaking, the assembly operators depend on the resource operators and on the `*Cluster` classes. We should use checkstyle import controler to enforce this. In the process we're likely to find layering violations, but that's an opprtunity to understand _why_ those exist and to figure out how to fix it.

**Comment by scholzj** [comment]
Triaged on 31.3.2022: The point is valid. But we didn't get to this in 2 years. If someone wants to work on this, feel free but not much sense to keep the issue for it around.
