### ISSUE TITLE
Changing the log levels of Kafka and Zookeeper pods

### ISSUE THREAD

**Issue by serdarkalayci** [strimzi/strimzi-kafka-operator#3178]
Hello,
My Kafka pods are logging too much for my taste (sometimes more than 900 lines per second), and it has INFO, DEBUG and TRACE lines. I went through the docs but saw nothing to help me configure the level directly from the Kafka definition. Is there a way to lower the verbosity of the logs on the fly?

**Comment by scholzj** [comment]
You can configure the log levels as described here: https://strimzi.io/docs/operators/latest/full/using.html#con-kafka-logging-deployment-configuration-kafka

**Comment by serdarkalayci** [comment]
Thank you so much, I read thoroughly the document up to 3.1.10, and when 3.1.11 started talking about Entity Operator I gave up, my bad
