### ISSUE TITLE
[Question] MirrorMaker2 to use existing Connect cluster

### ISSUE THREAD

**Issue by abergmeier** [strimzi/strimzi-kafka-operator#3183]
With `KafkaConnector` I can reference a strimzi cluster via:

```
labels:
    strimzi.io/cluster: gravitas-cluster
```

It somehow seems like `KafkaMirrorMaker2` currently enforces an own cluster?

**Comment by ppatierno** [comment]
@abergmeier if Jakub answered your question, can we close this?

**Comment by abergmeier** [comment]
> @abergmeier if Jakub answered your question, can we close this?

Sure. Thanks.
