### ISSUE TITLE
[Question] What am I missing - MirrorMaker2 Multi cluster example

### ISSUE THREAD

**Issue by john-mcpeek** [strimzi/strimzi-kafka-operator#3188]
I've got 2 Openshift clusters. I'm trying to setup MirrorMaker2 between them. The AMQ Streams operator is in and working. Kafka cluster on both clusters. Topic foo on each cluster. I haven't seen an example that looks like it accesses a different cluster. There is talk about Kafka Connect, but nothing talks about setting Connect up. I'm looking for an example with real world values. I see the bootstrapServers, but none of the example I've seen actually explain how 'my-cluster-source-kafka-bootstrap:9092' could access another cluster. Do I need to setup a route to expose the bootstrap service? I'm just an looking for an explanation of where these values are supposed to come from and what else needs to be in place.

Please help me understand what I am missing.

**Comment by scholzj** [comment]
To mirror between Kafkas on different OCP clusters, you will need to expose the clusters first to the outside of openshift by enabling the external interface:
* https://strimzi.io/docs/operators/latest/full/using.html#assembly-kafka-broker-external-listeners-deployment-configuration-kafka
* https://strimzi.io/blog/2019/04/17/accessing-kafka-part-1/

In your case with OCP you can use for example routes. Once you do that, the `status` section of the Kafka CRs will contain the URL for connecting to the cluster using the external listener. So that is what you will use as the bootstrap address. Additionally, you will need to copy at least the secrets with the CA certificates between the clusters to configure TLS. The TLS configuration should be the same as in this example: https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/mirror-maker/kafka-mirror-maker-2-tls.yaml ... you will just need to copy the secret between the OCP clusters.

Hope this gets you started - give it a try and if you need something more, let me know ... ideally with the YAMLs for the two Kafka clusters and the Mirror Maker so that I can give you the exact changes if needed.

**Comment by john-mcpeek** [comment]
Ok, that got the connectors to a "RUNNING" state, but it doesn't look like the topics in the source cluster is working. Below is the yaml and also an error I am seeing in the log. I'm not sure what to do with "Timed out waiting for a node assignment." Thanks.


> apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  creationTimestamp: '2020-06-13T21:21:26Z'
  generation: 1
  name: my-mm2-cluster
  namespace: common
  resourceVersion: '27031652'
  selfLink: >-
    /apis/kafka.strimzi.io/v1alpha1/namespaces/common/kafkamirrormaker2s/my-mm2-cluster
  uid: cbc74a91-9d67-4da8-b1a9-6ce79fca916d
spec:
  clusters:
    - alias: my-cluster-source
      bootstrapServers: 'my-cluster-kafka-bootstrap-common.apps.server1.oscplatform.site:443'
    - alias: my-cluster-target
      bootstrapServers: 'my-cluster-kafka-bootstrap.common.svc:9092'
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  connectCluster: my-cluster-target
  mirrors:
    - checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      groupsPattern: .*
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      sourceCluster: my-cluster-source
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: 1
          replication.factor: 1
          sync.topic.acls.enabled: 'false'
      targetCluster: my-cluster-target
      topicsPattern: .*
  replicas: 1
  version: 2.4.0
status:
  conditions:
    - lastTransitionTime: '2020-06-15T13:40:20.612Z'
      status: 'True'
      type: Ready
  connectors:
    - connector:
        state: RUNNING
        worker_id: '10.22.0.188:8083'
      name: my-cluster-source->my-cluster-target.MirrorCheckpointConnector
      tasks: []
      type: source
    - connector:
        state: RUNNING
        worker_id: '10.22.0.188:8083'
      name: my-cluster-source->my-cluster-target.MirrorSourceConnector
      tasks: []
      type: source
    - connector:
        state: RUNNING
        worker_id: '10.22.0.188:8083'
      name: my-cluster-source->my-cluster-target.MirrorHeartbeatConnector
      tasks:
        - id: 0
          state: RUNNING
          worker_id: '10.22.0.188:8083'
      type: source
  observedGeneration: 1
  url: 'http://my-mm2-cluster-mirrormaker2-api.common.svc:8083'


--------------------------------------------------------------------------------------------

> 2020-06-15 13:47:43,306 ERROR Scheduler for MirrorSourceConnector caught exception in scheduled task: refreshing topics (org.apache.kafka.connect.mirror.Scheduler) [refreshing topics]
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at org.apache.kafka.connect.mirror.MirrorSourceConnector.listTopics(MirrorSourceConnector.java:278)
	at org.apache.kafka.connect.mirror.MirrorSourceConnector.findTopicPartitions(MirrorSourceConnector.java:167)
	at org.apache.kafka.connect.mirror.MirrorSourceConnector.refreshTopicPartitions(MirrorSourceConnector.java:177)
	at org.apache.kafka.connect.mirror.Scheduler.run(Scheduler.java:93)
	at org.apache.kafka.connect.mirror.Scheduler.executeThread(Scheduler.java:112)
	at org.apache.kafka.connect.mirror.Scheduler.lambda$scheduleRepeatingDelayed$1(Scheduler.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.

**Comment by scholzj** [comment]
I think you are definitely missing the TLS configuration for the remote cluster - the routes are always using TLS encryption because they use TLS Passthrough to get the non-HTTP Kafka traffic. So I think you need to first configure the TLS as explained above:

> Additionally, you will need to copy at least the secrets with the CA certificates between the clusters to configure TLS. The TLS configuration should be the same as in this example: https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/mirror-maker/kafka-mirror-maker-2-tls.yaml ... you will just need to copy the secret between the OCP clusters.

**Comment by john-mcpeek** [comment]
Oh, yeah. My bad. Thanks.

**Comment by john-mcpeek** [comment]
BOOM!

I had to change the port too, but looks like it is working great.

Thank you!

**Comment by scholzj** [comment]
Ok, great ... I guess in that case I can close this issue, right? Feel free to re-open it or open. new one if you need some more help.
