### ISSUE TITLE
Allow disabling operator to achieve a traditional, more customizable deployment

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi-kafka-operator#319]
At least until a feature-complete, production-ready, operator-based Strimzi release is available, allow disabling Strimzi Kafka operator to achieve a traditional, more customizable deployment. When this new OPERATOR_DISABLED ConfigMap property is set, the Kafka/Zookeeper deployment will be orchestrated by the user using Kubernetes/OpenShift primitives as was done in the Strimzi 0.1.0 release. This type of deployment allows for configuration of Kafka security and for configuration of less common Kafka properties such as "offsets.retention.minutes" and "advertised.listeners".

**Comment by scholzj** [comment]
I'm not sure I understand what disabling the operator means. You can disable the operator by not running the Cluster Controller. But then there is obviously nobody to deploy your cluster based on the ConfigMap.

I general we would prefer to focus on rolling out the features to actually make Strimzi useful (such as security and configuration) than spend the time on allowing some hacks but delaying the real support.

**Comment by scholzj** [comment]
#4399 will allow pausing the reconciliation in the operator. I do not think we plan to do anything else.
