### ISSUE TITLE
[Enhancement] Generate bunch of topics with predictable names with more random characters

### ISSUE THREAD

**Issue by Frawless** [strimzi/strimzi-kafka-operator#3194]
**Is your feature request related to a problem? Please describe.**
Currently, we generate topic names with stable prefix and random numbers. We should have a method, which will generate a list of names for topics, with more random characters. This approach will be useful in upgrade tests for example when we create a bunch of topics and check if the topics werent' changed by the upgrade process.  This idea started as a discussion at https://github.com/strimzi/strimzi-kafka-operator/pull/3177#pullrequestreview-429835266

**Describe the solution you'd like**
Create a method in some utils class, which will generate a list of topic names. As input, we need there count of topics and some kind of seed because we want to have the same names generated with each call with the same parameters.

**Describe alternatives you've considered**
If it will be too hard, we actually don't need to return same values with every call with same parameters, but we can store the generated list for further validation in the tests. For manual review, we can get topic names from the logs. Anyway, the names should be more random.

**Additional context**
Approach with a bunch of topics created for validation is currently used in `StrimziUpgradeST`.

**Comment by scholzj** [comment]
Triaged on 7.6.2022: Should be already done according to @Frawless
