### ISSUE TITLE
[Enhancement] Update Helm 3 chart to use `crds` directory

### ISSUE THREAD

**Issue by michael-barker** [strimzi/strimzi-kafka-operator#3203]
**Is your feature request related to a problem? Please describe.**
Is it is currently not possible to have Strimzi as a chart dependency where the parent chart is installing CRs using the Strimzi CRDs.

Helm charts can have dependencies on other Helm charts. When a dependent chart has CRDs that need to be installed and the parent chart is installing CRs using those CRDs, ordering becomes important. In Helm 3 this ordering is handled by placing the CRDs in a special `crds` directory. Helm will always install these CRDs first.

**Describe the solution you'd like**
By moving the CRDs to the `crds` directory, charts can include Strimzi as a dependency without ordering issues related to installing CRDs.

**Comment by michael-barker** [comment]
I'm currently working on a PR for this issue.

**Comment by samuel-hawker** [comment]
@michael-barker do you consider this issue complete now? Is there any outstanding work for this?

If not I would suggest we close this issue.

**Comment by michael-barker** [comment]
@samuel-hawker Yes, this is resolved. Thanks!

**Comment by samuel-hawker** [comment]
Thanks for the contribution! :)
