### ISSUE TITLE
Provide a Grafana dashboard for the HTTP bridge

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3217]
As we have metrics exposed through the bridge, After working on [#423](https://github.com/strimzi/strimzi-kafka-bridge/pull/423), [#426](https://github.com/strimzi/strimzi-kafka-bridge/pull/426) and [#431](https://github.com/strimzi/strimzi-kafka-bridge/pull/431), we need to add a Grafana dashboard to show these metrics.

**Comment by scholzj** [comment]
Closing since the dashboard for HTTP Bridge now exists.
