### ISSUE TITLE
[Question] Setting up SASL SCRAM-SHA-512 authentication

### ISSUE THREAD

**Issue by rramanan15** [strimzi/strimzi-kafka-operator#3226]
Am new to Kafka and we are setting up kafka cluster on Kubernetes. Is there any reference or detailed document available on how to set up SASL SCRAM-SHA-512 authentication and authorization.

Can we use JaaS for client authentication/authorization to write/read message from topics and how to configure it.

**Comment by scholzj** [comment]
So, have you read the the documentation about Authentication and Auhorization https://strimzi.io/docs/operators/latest/full/using.html#assembly-kafka-authentication-and-authorization-deployment-configuration-kafka and checked the security examples? https://github.com/strimzi/strimzi-kafka-operator/tree/master/examples/security

**Comment by rramanan15** [comment]
@scholzj 
Thanks. setup the authentication to SCRAM. We are able to run console producer & consumer by providing the credentials in properties file. But not able to create topic or list topic using kafka-topics.sh since we are not able to pass UID and password.
How to pass UID & password as arg to kafka-topics.sh.

**Comment by scholzj** [comment]
I think you will need to use this option: https://github.com/apache/kafka/blob/888f83c2c3d03084629256f9f993072a22da74c0/core/src/main/scala/kafka/admin/TopicCommand.scala#L598 (and if not this one, I'm sure there is some other option to pass the properties file with configs).

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks

**Comment by chary1112004** [comment]
Hi @scholzj ,

I have same case. I saw that you gave link to https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/security/scram-sha-512-auth/user.yaml

I wonder where we put password for user as I do not see the configuration for it?

When we setup kafka in aws, it associate with user account include **username, password**

Thanks!

**Comment by chary1112004** [comment]
> Hi @scholzj ,
> 
> I have same case. I saw that you gave link to https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/security/scram-sha-512-auth/user.yaml
> 
> I wonder where we put password for user as I do not see the configuration for it?
> 
> When we setup kafka in aws, it associate with user account include **username, password**
> 
> Thanks!

Hi @scholzj ,

I already saw it is auto generated secret same name with user.

Thanks

**Comment by scholzj** [comment]
That is correct. By default it is autogenerated. If you would want to set your own password for whatever reason, you can use this option: https://strimzi.io/docs/operators/latest/full/configuring.html#type-Password-reference in the `KafkaUser.spec.authentication` section.
