### ISSUE TITLE
[Question] Kafka connect REST API Authentication

### ISSUE THREAD

**Issue by nisheet195** [strimzi/strimzi-kafka-operator#3229]
Hi,

How can I enable Basic Authentication on the Rest API exposed by Kafka connect cluster??
I am using strimzi operator version 0.11.1
I looked through Kafka documentation and it suggests to enable it, we have to provide it in `rest.extension.classes` but according to strimzi documentation, I cannot override any configuration with prefix `rest.`

Thanks

**Comment by scholzj** [comment]
I don't think you can set it right now.

**Comment by nisheet195** [comment]
Thanks for the response.

Is there any other way to put any sort of authentication on the REST APIs??

**Comment by scholzj** [comment]
Not as far as I know ... NetworkPolicies might help a bit, but it is not a real authentication of course.

**Comment by nisheet195** [comment]
Is there any plan to implement such in near future??

**Comment by scholzj** [comment]
As far as I'm concerned, I think we should complete the connector operator to do the missing operations such as restarting connectors etc. And once that is done just give users the option to lock down the APi completely.

**Comment by scholzj** [comment]
The initial plan how to start working on it is described here: https://github.com/strimzi/proposals/blob/master/008-tls-encrypt-the-kafka-connect-rest-api.md ... we just need to start working on the implementation.

**Comment by hoptical** [comment]
Hi,

Is there any update on this? There seems to be no override on `rest.` configs yet, as mentioned [here](https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaConnectSpec-reference). 
So how can we secure the REST API of Kafka Connect?

**Comment by scholzj** [comment]
You cannot override this field because that would break the operator.

**Comment by hoptical** [comment]
Ok. Is there any other way to secure the REST API?
