### ISSUE TITLE
[Enhancement] KafkaUser - Pass annotations to secrets

### ISSUE THREAD

**Issue by dweber019** [strimzi/strimzi-kafka-operator#3237]
When I create a KafkaUser I like to define annotations on it, which will be passed/copied to the secrets created by the operator.

This would enable use cases like https://github.com/EmberStack/kubernetes-reflector or custom implementations on secrets.

Is there a way to do this?

**Comment by scholzj** [comment]
I don't think this is supported right now. But I can see why it would make sense. So we can change this to an enhancement if you want and maybe add some template setion to configure the metadata similar to the other resources we have.

**Comment by dweber019** [comment]
Okey I think this will be a good starting point https://github.com/strimzi/strimzi-kafka-operator/pull/1039
