### ISSUE TITLE
[Enhancement] stable/prometheus-operator instead of coreos / prometheus-operator

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3241]
**Is your feature request related to a problem? Please describe.**
coreos/prometheus-operator is very restrictive. 
coreos/prometheus-operator doesn't create clusterip service. It doesn't has practical ways to expose Prometheus ports outside of Kubernetes.

**Describe the solution you'd like**
Strimzi monitoring scenarios are based on coreos/prometheus-operator and that makes things harder. Strimzi forces us using coreos/prometheus-operator. If Strimzi monitoring scenarios were based on stable/prometheus operator, things would be much more easier on Prometheus side and we wouldn't have to struggle with coreos/prometheus-operator related problems.

Please look at following cases;
[https://stackoverflow.com/questions/58202565/prometheus-operator-expose-ingress-route](https://stackoverflow.com/questions/58202565/prometheus-operator-expose-ingress-route)
[https://stackoverflow.com/questions/60729947/helm-expose-prometheus-dashboard](https://stackoverflow.com/questions/60729947/helm-expose-prometheus-dashboard)
People aim to use stable/prometheus-operator instead of coreos-prometheus-operator.

**Describe alternatives you've considered**

Creating Prometheus via stable-prometheus-operator instead of coreos/prometheus-operator.

P.S pls correct, if I am wrong, the existing yaml files are valid also for stable/prometheus-operator.

**Comment by scholzj** [comment]
I think this is a misunderstanding. We do not force to use anything. The Prometheus and Grafana installation guide is just if you need one. But you can use whatever Prometheus and Grafana deployment you want. All you need to do is to configure it to find the pods and scrape the metrics, that is it. So it is fully up to you to decide what and how do you want to install them.

**Comment by tirelibirefe** [comment]
of course nobody put a gun to our head to force us coreos/prometheus-operator using; it's just an exaggerated analogy. Sorry if I was offending, that's not my purpose.

**Comment by scholzj** [comment]
You didn't write anything offending. I'm just trying to explain that there is no hard dependency between Strimzi and its operands and the CoreOS Prometheus operator. The operators and operands provide standard Prometheus endpoints which can be consumed by any Prometheus server or anything what is able to consume the Prometheus endpoints. In fact there are many users including me using different ways to install Prometheus. 

So I do not think we make anything harder for you. You can use whatever solution you find best to install Prometheus.

**Comment by tirelibirefe** [comment]
As running 2 different prometheus operators in the same K8s causes another problems, I removed coreos/prometheus-operator and installed stable/prometheus-operator.

then I applied my own ServiceMonitor yaml which is based on the example file provided by Strimzi.

```
cat <<EOF | kubectl apply -n kafka -f -
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-service-monitor
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
  namespaceSelector:
    matchNames:
      - kafka
  endpoints:
  #### job_name: kubernetes-cadvisor
  # configured in additional secret

  #### job_name: kube-state-metrics
  - port: tcp-prometheus
    honorLabels: true
    interval: 10s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoints_name]
      separator: ;
      regex: prometheus-kube-state-metrics
      replacement: $1
      action: keep
    - separator: ;
      regex: __meta_kubernetes_service_label_(.+)
      replacement: $1
      action: labelmap
    - sourceLabels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      targetLabel: namespace
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_namespace
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      separator: ;
      regex: (.*)
      targetLabel: node_ip
      replacement: $1
      action: replace

  #### job_name: node-exporter
  - port: tcp-prometheus
    honorLabels: true
    interval: 10s
    scrapeTimeout: 10s
    path: /metrics
    scheme: http
    relabelings:
    - sourceLabels: [__meta_kubernetes_endpoints_name]
      separator: ;
      regex: prometheus-node-exporter
      replacement: $1
      action: keep
    - separator: ;
      regex: __meta_kubernetes_service_label_(.+)
      replacement: $1
      action: labelmap
    - sourceLabels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      targetLabel: namespace
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_namespace]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_namespace
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_service_name]
      separator: ;
      regex: (.*)
      targetLabel: kubernetes_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      separator: ;
      regex: (.*)
      targetLabel: node_name
      replacement: $1
      action: replace
    - sourceLabels: [__meta_kubernetes_pod_host_ip]
      separator: ;
      regex: (.*)
      targetLabel: node_ip
      replacement: $1
      action: replace

  #### job_name: kubernetes-services
  # configured in additional secret

  #### job_name: kubernetes-pods
  # configured in additional secret

  #### job_name: kubernetes-nodes-kubelet
  # configured in additional secret
EOF

```
When I used coreos/prometheus-operator, it worked but when I use stable/prometheus-operator the servicemonitor couldn't have been created.

`The ServiceMonitor "kafka-service-monitor" is invalid: spec.endpoints.relabelings.replacement: Invalid value: "null": spec.endpoints.relabelings.replacement in body must be of type string: "null"`

So I need to your advises...

**Comment by scholzj** [comment]
These are just the configuration files for the Prometheus server which tell it what to scrape and where. If you use different Prometheus operator / server you might need to adjust them. I'm afraid we do not have the know-how to help with any kind of Prometheus deployment.

**Comment by tirelibirefe** [comment]
I've been working on Prometheus for a few days, I see that things are different than what I've perceived in first. So I'm closing issue.
