### ISSUE TITLE
[Doc] Broken links to Kubernetes API docs

### ISSUE THREAD

**Issue by sjwoodman** [strimzi/strimzi-kafka-operator#3246]
**Suggestion / Problem**
The "Using Strimzi" guide links to the Kubernetes API v1.11 for items such as NetworkPolicyPeer APIs. These links are broken. I don't know if the Kubernetes docs are temporarily broken or if 1.11 has been deliberately removed. 

**Documentation Link**

https://strimzi.io/docs/operators/latest/using.html

eg. Broken in Network Policies section with links pointing to https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#networkpolicypeer-v1-networking-k8s-io

**Comment by scholzj** [comment]
Are they broker even in master https://strimzi.io/docs/operators/master/full/using.html? I think I have been fixing some of them

**Comment by sjwoodman** [comment]
Ah, no. The are fixed on master. Thanks @scholzj I'll close this.
