### ISSUE TITLE
[Question] How to attach MirrorMaker to and existing group.id in source?

### ISSUE THREAD

**Issue by yupvr** [strimzi/strimzi-kafka-operator#3251]
To migrate from MM1 to MM2 I would like to start MM2 read from where MM1 stopped.
I tried to attach to the same consume group as MM1 read from.
Here is my configuration:
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: strimzi-aws-to-dc
spec:
  replicas: 1
  connectCluster: "dc"
  clusters:
  - alias: "dc"
    bootstrapServers: dc:9092
  - alias: "aws"
    bootstrapServers: aws:9092
    config:
      group.id: aws-to-dc-stg-group
  mirrors:
  - targetCluster: "dc"
    sourceCluster: "aws"
    sourceConnector:
      config:
        group.id: aws-to-dc-stg-group
    topicsPattern: "mm1-switch-mm2"
    groupsPattern: "aws-to-dc-stg-group"
```
When I run `kubectl describe deployments` I see that Kafka connect uses the default group:
```
...
    Environment:
      KAFKA_CONNECT_CONFIGURATION:      config.storage.topic=mirrormaker2-cluster-configs
                                        group.id=mirrormaker2-cluster
                                        status.storage.topic=mirrormaker2-cluster-status
                                        config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
                                        offset.storage.topic=mirrormaker2-cluster-offsets
                                        config.providers=file
                                        value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
                                        key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
...
```
In MM2 logs I also see that it does not use groupId what expected:
```
...
2020-06-26 15:16:55,940 INFO ConsumerConfig values:
...
	group.id = null
	group.instance.id = null
...
```
```
2020-06-26 15:16:56,076 INFO [Consumer clientId=consumer-4, groupId=null] Subscribed to partition(s): mm1-switch-mm2-0 (org.apache.kafka.clients.consumer.KafkaConsumer) [task-thread-aws->dc.MirrorSourceConnector-0]
2020-06-26 15:16:56,077 INFO Starting with 0 previously uncommitted partitions. (org.apache.kafka.connect.mirror.MirrorSourceTask) [task-thread-aws->dc.MirrorSourceConnector-0]
2020-06-26 15:16:56,078 INFO [Consumer clientId=consumer-4, groupId=null] Seeking to offset 10 for partition mm1-switch-mm2-0 (org.apache.kafka.clients.consumer.KafkaConsumer) [task-thread-aws->dc.MirrorSourceConnector-0]
2020-06-26 15:16:56,078 INFO task-thread-aws->dc.MirrorSourceConnector-0 replicating 1 topic-partitions aws->dc: [mm1-switch-mm2-0]. (org.apache.kafka.connect.mirror.MirrorSourceTask) [task-thread-aws->dc.MirrorSourceConnector-0]
2020-06-26 15:16:56,078 INFO WorkerSourceTask{id=aws->dc.MirrorSourceConnector-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask) [task-thread-aws->dc.MirrorSourceConnector-0]
2020-06-26 15:16:56,085 INFO [Consumer clientId=consumer-4, groupId=null] Cluster ID: olRs7ybdTU--T9NXZvIbSw (org.apache.kafka.clients.Metadata) [task-thread-aws->dc.MirrorSourceConnector-0]
```
Please advise how to attach to the consumer group.

**Comment by scholzj** [comment]
@ajborley Is this possible in any way? Or do we always set our own consumer group?

**Comment by ajborley** [comment]
Kafka's MM2 MirrorSourceConnector uses the KafkaConsumer.assign API to set it's initial offset (https://github.com/apache/kafka/blob/trunk/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/MirrorSourceTask.java#L93) and so does not commit offsets via the consumer. Instead, offsets are stored on the source cluster in the `mm2-offset-syncs.<target-cluster-alias>.internal` topic (a compacted topic that holds records containing the source offset and the target offset for a topic-partition). Hence, using a group id does not work for MM2.

It may be possible to seed the `mm2-offset-syncs.<target-cluster-alias>.internal` topic with a serialized OffsetSync record (https://github.com/apache/kafka/blob/trunk/connect/mirror/src/main/java/org/apache/kafka/connect/mirror/OffsetSync.java) so that the KafkaConsumer.assign call is given the right offset to begin at, but I have never tried this.

**Comment by yupvr** [comment]
@ajborley thank you for the detailed answer.

**Comment by yupvr** [comment]
@ajborley Again thank you for your previous answer.
I continued my experiments and saw that `mm2-offset-syncs.<target-cluster-alias>.internal` in source side messages only contain line wrapping symbol (empty line). On a destination side topic, `mirrormaker2-cluster-offsets` contains the next messages: 
```
{"offset":23}
{"offset":5}
{"offset":7}
{"offset":25}
```
The offsets look correct, but there is no indication which offset points to what topic (I replicate two different topics).
Also, I saw that offset point in `mirrormaker2-cluster-offsets` appear with ~30sec delay after replication happen. So I assume the MM2 do replication and then write offset, but not read offset and then do replication.

**Comment by yupvr** [comment]
Already found the answer. 
I missed is that Kafka is a key/value system. 
So the solution is quite simple:
1. Create `mirrormaker2-cluster-offsets` topic in destination side:
```$ ./kafka-topics.sh --bootstrap-server kafka-dc:9092 --create --replication-factor 1 --partitions 1 --topic mirrormaker2-cluster-offsets --config "cleanup.policy=compact"```
2. Populate topic with requared offset:
```$ ./kafka-console-producer.sh --bootstrap-server kafka-dc:9092 --topic mirrormaker2-cluster-offsets --property parse.key=true --property key.separator="|"```
`["aws->dc.MirrorSourceConnector",{"cluster":"aws","partition":0,"topic":"mm1-switch-mm2"}]|{"offset":21}`
3. Start MM2.

MM2 will start replication from the defined offset.

**Comment by scholzj** [comment]
Thanks for updating the case with the solution! That is always great to have it here for record. 👍
