### ISSUE TITLE
[Question] Kafka connect REST API /pause

### ISSUE THREAD

**Issue by VladimirYushkevich** [strimzi/strimzi-kafka-operator#3277]
Hello all!

I'm trying to use kafka connect REST API  to pause/resume MySQL `JdbcSourceConnector`. I see that after calling `/connectors/pause` in logs following entry: 
`2020-07-02 13:53:36,953 INFO Setting connector source-mysql-elli state to PAUSED (org.apache.kafka.connect.runtime.Worker) [DistributedHerder-connect-1-1]`
And `/status` endpoint produces a actual status after some time:
```
{
  "name": "source-mysql-elli",
  "connector": {
    "state": "PAUSED",
    "worker_id": "10.112.30.201:8083"
  },
  "tasks": [
    {
      "id": 0,
      "state": "PAUSED",
      "worker_id": "10.112.30.201:8083"
    }
  ],
  "type": "source"
```
But when I describe `kafkaconnectors.kafka.strimzi.io` CustomResource I see it is in `RUNNING` state.
Furthermore, after some time it's state changed without my control. I see in logs:
`2020-07-02 13:57:53,875 INFO Setting connector source-mysql-elli state to STARTED (org.apache.kafka.connect.runtime.Worker) [DistributedHerder-connect-1-1]`
That something what I don't understand. According to confluent documentation, connector's state should be persisted even between restarts. But looks like something is triggering `PAUSED` connector back to `RUNNING` state. Could someone help me to clarify is it a known issue or I'm doing something wrong?

Thanks.

**Comment by scholzj** [comment]
When using the KafkaConnector resource and the connector operator, you should not use some features of the REST API - and pausing is one of them. Thsi is because the connector operator has the KafkaConnetor resources as its single source of truth and will unpause the ocnnector. So to pause the connector, you should instead edit the KAfkaConnector resource and set `pause: true` (https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaConnectorSpec-reference).

**Comment by VladimirYushkevich** [comment]
Thanks for your response, @scholzj ! I see that the only way for me is to apply a new config with kubectl. Are there any plans to have pause/resume feature in `kafkaconnector.kafka.strimzi.io` custom resource? I think for now I use only delete and describe commands.

**Comment by scholzj** [comment]
If you mean something like `kubectl pause ...`, `kubectl` is IMHO not flexible enough for that. You would need to write your own plugin which could in theory do something like `kubectl strimzi pause connector ...`. But that is unrelated from the custom resource - that already has it as linked in my previous comment and you can just edit the custom resource to pause / resume the connectors.

**Comment by VladimirYushkevich** [comment]
Thanks, @scholzj
