### ISSUE TITLE
[Enhancement] Add missing KafkaAssignerEvenRackAwareGoal KafkaAssignerDiskUsageDistributionGoal goals to KafkaRebalance

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#3286]
**Is your feature request related to a problem? Please describe.**
Currently KafkaRebalance does not allow for the use of the following Goals:
```
KafkaAssignerEvenRackAwareGoal
KafkaAssignerDiskUsageDistributionGoal
```
Speaking to Kyle Liberti original contributor of the Cruise Control feature to Strimzi, he confirmed that this was an oversight.
Both of these goals require an extra parameter to be passed to Cruise Control when the request is sent:
https://github.com/linkedin/cruise-control/wiki/REST-APIs#trigger-a-workload-balance the `kafka_assigner` flag which defaults to false, and should be set to true if either of these goals are passed in.

**Describe the solution you'd like**
These Goals should be supported, with the correct `kafka_assigner` flag set to true passed to Cruise Control on Goals being present.

**Comment by ppatierno** [comment]
@samuel-hawker I am still finding difficulties to understand how these goals differ from `RackAwareGoal` and `DiskUsageDistributionGoal`; they really sound like to be the same.
What I notice is that the above`KafakAssignerXXXX` goals refer to a `kafka-assigner` tool [1] which sounds like something that was developed by Linkedin before Cruise Control; the doc says "These goals are used to make Cruise Control behaves like Kafka assigner tool". Do you know what that means? Did you ask more insights to the Cruise Control community?

[1] https://github.com/linkedin/kafka-tools/wiki/Kafka-Assigner

**Comment by ppatierno** [comment]
I discovered a couple of presentations [1] and [2] mentioning Kafka Assigner as a sort of predecessor of Cruise Control.
I have also started a discussion on the Cruise Control gitter channel to know more.

[1] https://www.usenix.org/sites/default/files/conference/protected-files/srecon18asia_slides_kumar.pdf
[2] https://www.slideshare.net/JiangjieQin/introduction-to-kafka-cruise-control-68180931

**Comment by samuel-hawker** [comment]
> "These goals are used to make Cruise Control behaves like Kafka assigner tool". Do you know what that means?

Unfortunately not, my only understanding is they have a different behaviour. It seems more likely to me now that actually those are deprecated in favour of `DiskUsageDistributionGoal` and `RackAwareGoal`.

I suggest we wait on a response from cruise control.
Currently if you supply the goals, the status has a condition containing:
```
Error processing POST request '/rebalance' due to:
        'java.lang.IllegalArgumentException: Goals
        [KafkaAssignerDiskUsageDistributionGoal] are not supported. 
```
I think this is probably sufficient, if a user tries to add it to the `cruiseControl.config.goals` then it won't work, but I doubt many users will ask for this...

Do you have a link to the slack question?

**Comment by ppatierno** [comment]
They have a Gitter room [1]
To be honest, I don't know how to link a direct question :-) ... but if you login into Gitter and that room, it's the last one with no answers for now.

[1] https://gitter.im/kafka-cruise-control/Lobby

**Comment by samuel-hawker** [comment]
Response:
```
Adem Efe Gencer
@efeg
00:05
Hi @ppatierno As you correctly pointed out, goals with KafkaAssigner prefix mimic the way LinkedIn's kafka-assigner distributes replicas over brokers. They were added to CC to ensure a smooth transition for kafka-assigner users (e.g. a couple of years ago, LinkedIn was one of them). So this enabled such users to gradually migrate to CC -- i.e. first to kafka-assigner mode, then to regular CC goals.
Hope it helps!
```

Due to this I am more than happy to close this issue. Apologies for the misunderstanding, it's good to get some clarity on this.
