### ISSUE TITLE
[Question] no metrics - Prometheus

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3288]
Hello;
I've installed Kafka, Prometheus and enabled metrics as described in documentation. All in the same namespace (namespace=kafka) except Grafana. Grafana is in another namespace (namespace=monitoring). I added Prometheus in namespace=kafka to Grafana in namespace=monitoring. I imported dashboards provided by Strimzi to Grafana. Things look like working properly, I mean I don't see any errors for now.

The problem is that Grafana (through Prometheus) cannot get any metrics, it returns always empty response. As Prometheus service is a headless service, I am not be able to connect to Prometheus and query metrics through Prometheus.

![image](https://user-images.githubusercontent.com/45227339/86627116-724d6900-bfd0-11ea-98e5-82e438cdc0c2.png)

I can provide kafka configuration files but at this point what do you advice me check or What must I check to go deeper to analyze the problem?

**Comment by scholzj** [comment]
I do not know your particular setup. But on my own cluster I have also Grafana and Prometheus in different namespaces and all I needed to do is to just configure the data sources URL as `prometheus.<namespace>.svc` - to use the namespace. Nothing else.

**Comment by scholzj** [comment]
I this still an issue or can we close this?

**Comment by tirelibirefe** [comment]
Yes we can close, thanks for your support
