### ISSUE TITLE
Strimzi includes terms which are considered problematic in the modern climate

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3289]
Terms such as whitelist and blacklist should be removed from Strimzis. Kafka has [KIP-629](https://cwiki.apache.org/confluence/display/KAFKA/KIP-629%3A+Use+racially+neutral+terms+in+our+codebase) for removing them so some of the work will be dependent on both Kafka and ZooKeeper releases.
Where possible we should remove them from APIs, examples and documentation but retain backward compatibility.
Some places to apply these changes are:

* The `KafkaMirrorMaker2` CRD contains `topicsBlacklistPattern` and `groupsBlacklistPattern` fields
* The `KafkaMirrorMaker` CRD contains `whitelist` field
* The OPA examples in system tests have "whitelist"

**Comment by samuel-hawker** [comment]
Do we want to follow their convention and switch to `include` and `exclude`? I've seen other alternatives of `allowlist` and `denylist` in other products.

**Comment by ppatierno** [comment]
For the Kafka related stuff, I would wait for KIP-629 and see how it goes. I think that having consistency is much better so if the KIP will be approved using "include" and "exclude" I would go with that.
For OPA stuff, it's about some examples so we should have more freedom.

**Comment by matthew-chirgwin** [comment]
Would this issue also cover branch names used across Strimzi repositories? This just came up in https://github.com/strimzi/strimzi-ui/pull/10 re the use of the term `master` as the primary/main branch.

**Comment by scholzj** [comment]
I'm not aware of us planning anything in that respect.

**Comment by matthew-chirgwin** [comment]
> I'm not aware of us planning anything in that respect.

Thank you for the response @scholzj !
