### ISSUE TITLE
[Enhancement] Should KafkaRebalance custom resource status `Ready` mark end of usable life? 

### ISSUE THREAD

**Issue by julianGoh17** [strimzi/strimzi-kafka-operator#3296]
From reading the documentation it was unclear that once a `KafkaRebalance` proposal is successful and the status turns `Ready` you are unable to get a new proposal from that `KafkaRebalance` custom resource. It was only through looking through the [code](https://github.com/strimzi/strimzi-kafka-operator/blob/2e950039d7559ddd7ce6d46aa586f0e66b50e702/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java#L368-L370) that we noticed that once the status is `Ready` that you won't be able to generate a new proposal from this custom resource.  

This seems to be intentional but we were wondering if this should be so? We were wondering if there was any compelling reason that you shouldn't be able to use the same custom resource for generating a new proposal? This would also make keeping a KafkaRebalance custom resource in your cluster make more sense as currently all it does is act as an old artefact of a previous rebalance.

**Comment by scholzj** [comment]
I think that is the case. But do not know the reasons.

@tomncooper @ppatierno @kyguy Can you have a look at this? You are the experts.

**Comment by tomncooper** [comment]
So `Ready` = finished was used as it is in line with Kubernetes convention (though I admit it is a bit confusing). 

Reusing a "finished" rebalance does make sense however. We do allow going from `Stopped` to `ProposalReady` via the `refresh` annotation, so we could look at doing something similar from `Ready`.

**Comment by scholzj** [comment]
Ok, changing this to enhancement then.

**Comment by ppatierno** [comment]
Maybe using `Complete` as Kubernetes Job could be better than "finished".

**Comment by samuel-hawker** [comment]
I agree with Paolo that `Complete` is a better 'terminal' state. 

I agree with Tom also that as an enhancement using a `refresh` (which would initialize a new session with Cruise Control for the KafkaRebalance) on a `Complete` KafkaRebalance should allow it to loop back into generating a proposal and eventually `ProposalReady`

**Comment by samuel-hawker** [comment]
I have marked this issue as `help-wanted` to allow new contributors the opportunity to enhance this behaviour.
