### ISSUE TITLE
Query on TLS Certificates/secrets

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3304]
Hi TEam,

Is there a way to share secrets across namespaces? or across Kafka operator clusters

The use case here is, if a Kafka cluster is deployed in one namespace, it's secrets are created in the same namespace. 
How can a microservice, hosted in a different namepsace mount those secrets.

As of now, we have used kubectl command to export the secret from kafka's namespace.

**Comment by scholzj** [comment]
There is nothing directly in Strimzi. I think there are some tools which can be used to copy/synchronise the secrets automatically.  but I personally have no experience with any of them.

**Comment by scholzj** [comment]
@pashafirdous Anything more we can help with? Or can we close this?

**Comment by pashafirdous** [comment]
closing.
