### ISSUE TITLE
Add the JAAS configuration string to the secret for SCRAM-SHA-512 users

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#3332]
One of the authentication types supported by the User Operator is SCRAM-SHA-512. In order to use it in Java, user will need to generate JAAS String for the Kafka client configuration (JAAS => Java Authentication and Authorization Services). Having this string generated by the operator and stored in the secret might save the effort for users.

Originally, this was proposed in #3037 . But that seems to be death. However, we think this feature is useful and it might be added in the future.

**Comment by allanmoso** [comment]
@scholzj  I could probably do this if you'd like.  It looks straight forward and does not change any of the API classes.

**Comment by scholzj** [comment]
Yeah, sure.
