### ISSUE TITLE
Add a possibility to specify secret prefix in the KafkaUser resource

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#3333]
By default, User Operator would create a secret with the same name as the KafkaUser resource. This is not always working - for example if you already ave other secret with the same name. One of the ways how this can be prevented is giving the users option to specify _secret prefix_, for example on the level of the whole UO. E.g. `STRIMZI_SECRET_PREFIX=kafka-` would cause all secret names to start with `kafka-`, e.g. `kafka-my-user`.

Additionally, this new option needs to be supported in the Kafka CR and documented.

This was originally raised in #2973. However this PR seems not to be active anymore, so we should have this feature tracked at least in this issue.

**Comment by allanmoso** [comment]
@scholzj  Is it OK if I work on this ticket?

**Comment by scholzj** [comment]
Yeah, sure. I will assign it to you.
