### ISSUE TITLE
Kafka latency spikes

### ISSUE THREAD

**Issue by AvihuHenya** [strimzi/strimzi-kafka-operator#3343]
Hi all,
I'm facing some issues regarding latency spikes in my Kafka cluster. 

Setup:
I am using OpenShift version 3.10
Strimzi version: 0.14.0
3 Kafka brokers
3 Zookeeper nodes
Memory: 8Gb
Disk: 7Gb each pod in Kafka Statefulset, 4GB each pod in Zookeeper Statefulset (Test enviroment), nfs volumes.
Using a topic with 3 partitions and replication factor of 3.

Phenomenon:
When I first try to test my cluster via the kafka-producer-perf-test.sh script, I have been getting latency spikes which are happening frequently each script execution.
I am exposing my Kafka cluster using OpenShift Route (External communication using TLS).
I am experiencing these spikes both from within and from outside of Openshift 
(Inside the cluster from within the pods themselves, and from outside using said Route).

Example from outside of Openshift:
_kafka-producer-perf-test.sh  --topic test-topic  --throughput 100  --num-records 10000 
--record-size 100000 --producer-props bootstrap.servers=<external-bootstrap>:9092 --producer.config producer.properties
500 records sent, 100.1 records/sec (9.55 MB/sec), 138.0 ms avg latency, 1131.0 ms max latency.
501 records sent, 100.1 records/sec (9.55 MB/sec), 5.5 ms avg latency, 11.0 ms max latency.
500 records sent, 100.1 records/sec (9.54 MB/sec), 5.4 ms avg latency, 14.0 ms max latency.
501 records sent, 99.9 records/sec (9.53 MB/sec), 5.1 ms avg latency, 14.0 ms max latency.
500 records sent, 100.0 records/sec (9.53 MB/sec), 6.3 ms avg latency, 135.0 ms max latency.
501 records sent, 100.1 records/sec (9.55 MB/sec), 5.0 ms avg latency, 9.0 ms max latency.
501 records sent, 100.0 records/sec (9.54 MB/sec), 8.6 ms avg latency, 206.0 ms max latency.
501 records sent, 100.1 records/sec (9.54 MB/sec), 4.9 ms avg latency, 11.0 ms max latency.
501 records sent, 100.1 records/sec (9.54 MB/sec), 4.8 ms avg latency, 12.0 ms max latency.
500 records sent, 99.9 records/sec (9.53 MB/sec), 4.7 ms avg latency, 10.0 ms max latency.
500 records sent, 100.0 records/sec (9.54 MB/sec), 7.1 ms avg latency, 149.0 ms max latency.
501 records sent, 99.9 records/sec (9.53 MB/sec), 4.8 ms avg latency, 11.0 ms max latency.
500 records sent, 100.0 records/sec (9.53 MB/sec), 4.8 ms avg latency, 18 ms max latency.
501 records sent, 100.1 records/sec (9.55 MB/sec), 4.8 ms avg latency, 19.0 ms max latency.
501 records sent, 100.0 records/sec (9.54 MB/sec), 4.8 ms avg latency, 12.0 ms max latency.
501 records sent, 100.1 records/sec (9.54 MB/sec), 4.7 ms avg latency, 14.0 ms max latency.
501 records sent, 100.1 records/sec (9.54 MB/sec), 5.3 ms avg latency, 45.0 ms max latency.
500 records sent, 99.9 records/sec (9.53 MB/sec), 5.0 ms avg latency, 13.0 ms max latency.
500 records sent, 100.0 records/sec (9.54 MB/sec), 5.3 ms avg latency, 14.0 ms max latency.
10000 records sent, 99.987002 records/sec (9.54 MB/sec), 12.04 ms avg latency, 1131.0 ms max latency, 5 ms 50th, 8 ms 95th, 394 ms 99th, 574 ms 99.9th_

I'll be glad if someone assist me with this phenomenon.
Thanks in advance,
Avihu.

**Comment by scholzj** [comment]
To be honest, I'm not sure how much we can help without having access to the same infrastructure, be able to monitor it etc. Especially given this is using very old version. If you use the Prometheus monitoring, you can probably check if these spikes correspond to some events going on in the system - either on a system level ... e.g. I/O or network. But also in the brokers - e.g. garbage collections. I do not think anything else comes to my mind.

It might be also worth checking what the latency distribution is. the average latency looks pretty stable. It is just the max latency which seems to have the spikes. So knowing what is for example the 90 or 95 percentile latency might be interesting.

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks

**Comment by AvihuHenya** [comment]
I have done what you recommend me about using Prometheus for checking system level latency, and found that there is load in my Openshift cluster that can effect my latency spikes. 
What i want to do next is to install the operator in  significantly less load OpenShift cluster, i will do that in the coming days, so i prefer to leave the issue open for possible another questions on that scope.

**Comment by scholzj** [comment]
Ok. I don't know where you run your OpenShift cluster. But you could also try things like dedicated hosts etc: https://strimzi.io/docs/operators/latest/full/using.html#assembly-scheduling-deployment-configuration-kafka

**Comment by scholzj** [comment]
Have you made any progress? Did it work any better on less loaded Kafka cluster?

**Comment by AvihuHenya** [comment]
Yes, I tried it.
The problem still exists there as well. I will try to test this in a few other ways I have thought of.
Thanks so much for the help anyway.

**Comment by AvihuHenya** [comment]
Hi again,
I am reopening this issue due to the persistence of this phenomenon.
We tried testing it again in several environments and Strimzi versions (same test configuration):
The spikes occur both on our closed Openshift environment (Version 4.5) using Strimzi v0.18 and Kafka v2.5, and on our online environment using the Redhat CRC project (basically Openshift v4 on your local setup) with Strimzi v0.18 and Kafka v2.5.
Any suggestions for solution?

**Comment by scholzj** [comment]
TBH, I'm not sure how much help could we offer. We do not have access to your environment to test things and see what is causing it.
