### ISSUE TITLE
[Enhancement] Allow KafkaUser CRD to use existing named secret

### ISSUE THREAD

**Issue by brokenjacobs** [strimzi/strimzi-kafka-operator#3354]
**Is your feature request related to a problem? Please describe.**
When using gitops, or similar approaches to deploy strimzi, users will desire to not store raw secrets in git. Many solutions to this exist, some which use their own CRD's such as bitnami's sealedsecrets operator. If the user desires to deploy a known password using an encrypted secret, a race condition occurs where the CRD controlling the secret must complete before the strimzi entityoperator processes the KafkaUser CRD, otherwise the secret will not be created and used. 

A race condition between two operators occurs and I can't control the secret used by the KafkaUser CRD.

**Describe the solution you'd like**
I would like the KafkaUser CRD to allow specifying a secret to be used to retrieve a SCRAM password from, and I would like the user to NOT be created until that secret exists. Similar to a pod referencing a secret. Something like a secret reference with a boolean to determine if the operator should create the secret or not. 

**Describe alternatives you've considered**
Alternatively I can change our secrets management approach to something like mozilla's sops and avoid this, but there is a large barrier to getting this done from a time perspective.

**Comment by scholzj** [comment]
@brokenjacobs From Strimzi 0.25, users can specify their own secret form which the password should be consumed: https://strimzi.io/docs/operators/latest/full/using.html#custom_password_configuration ... does that match this enhancement? I never used the sealed secrets, so not sure how they work and if they are compatible with this.

**Comment by brokenjacobs** [comment]
It does! Thanks! I should have closed this.
