### ISSUE TITLE
[Enhancement] Allow configurable NodePort value

### ISSUE THREAD

**Issue by talonx** [strimzi/strimzi-kafka-operator#3359]
**Is your feature request related to a problem? Please describe.**
For external listeners of type nodeport, there should be a way to configure the NodePort value. Currently, it is something random alllocated by Kubernetes like 32177. Having this configurable (Kubernetes allows it) in the Strimzi Kafka deployment would make it easy for external clients, and also ease not having to change firewall restrictions for them. This is currently a blocker for us on production.

**Describe the solution you'd like**
Add a field to configure the nodeport value.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by scholzj** [comment]
This is already possible. Please check the documentation:https://strimzi.io/docs/operators/latest/full/using.html#assembly-kafka-broker-external-listeners-nodeports-deployment-configuration-kafka / the example named _Example of an external listener configured with overrides for node ports_.

When using this, you are responsible for specifying node port numbers which are not used yet and can be allocated.

**Comment by talonx** [comment]
Thank you. I was looking at https://strimzi.io/docs/0.8.2/ - those are possibly older docs.

**Comment by scholzj** [comment]
Those are very old - we have now version 0.18.0. I'm not sure since when do we support this feature. But it is quite possible that it was not supported in 0.8.2.

**Comment by talonx** [comment]
Ah, I'm using 0.18.0 - not sure how I ended up in the older docs.
