### ISSUE TITLE
[Question] ... Kafka Connect broker may not be available

### ISSUE THREAD

**Issue by didentifier** [strimzi/strimzi-kafka-operator#3360]
( Openshift 4.4.12) After recreating my cluster I get weird connection issues. At first I got some errors on zookeepers about unknown_ca, I saw an open issue on that, I solved it after uninstalling the cluster and the operator and reinstalling. 

Now I keep getting Broker may not be available on kafka connect nodes I am really out of ideas on what is going on. 

`2020-07-22 07:33:18,553 INFO 10.129.4.1 - - [22/Jul/2020:07:33:18 +0000] "GET / HTTP/1.1" 200 91  1 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1865219266-23]
2020-07-22 07:33:19,682 WARN [Producer clientId=producer-2] Connection to node 0 (kafka-dev-kafka-0.kafka-dev-kafka-brokers.lagom.svc/10.128.4.27:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient) [kafka-producer-network-thread | producer-2]
2020-07-22 07:33:19,682 WARN [Producer clientId=producer-3] Connection to node 0 (kafka-dev-kafka-0.kafka-dev-kafka-brokers.lagom.svc/10.128.4.27:9093) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient) [kafka-producer-network-thread | producer-3]
`

I attached the logs of brokers, operators and kafka connect and brokers

[logs.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4958542/logs.zip)

**Comment by scholzj** [comment]
TBH, I'm not sure what could be the problem. From the log my guess would be some network issue.
* Can you share the full logs - i.e. from the beginning when the containers start?
* Can you share the custom resources for Kafka, Connect and any connector configurations which you already might have in Connect? (or did you not yet deployed any connectors?)
* Does the Kafka cluster work fine from other Kafka applications? Is the problem just Connect or all Kafka clients?

**Comment by didentifier** [comment]
It is probably a weird network issue but I don't really understand why, one of the replicas works as expected for now the other one I just restarted it to get the logs from the beginning and it cannot communicate with broker 2. It is pure luck if they work after I restart them. 

We use Lenses.io to create connectors which is able to communicate with the 3 brokers without issues. 

`apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  creationTimestamp: '2020-07-22T10:56:25Z'
  generation: 4
  name: kafka-dev
  namespace: lagom
  resourceVersion: '229413168'
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/lagom/kafkas/kafka-dev
  uid: f63bc53d-f6ba-41b5-bbac-3f7b0c4097a8
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  jmxTrans:
    kafkaQueries:
      - attributes:
          - Count
        outputs:
          - standardOut
        targetMBean: 'kafka.server:type=BrokerTopicMetrics,name=*'
    outputDefinitions:
      - name: standardOut
        outputType: com.googlecode.jmxtrans.model.output.StdOutWriter
      - flushDelayInSeconds: 5
        host: mylogstash.com
        name: logstash
        outputType: com.googlecode.jmxtrans.model.output.GraphiteOutputWriter
        port: 31028
  kafka:
    authorization:
      superUsers:
        - CN=lenses-user
      type: simple
    config:
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    jmxOptions:
      authentication:
        type: password
    listeners:
      external:
        authentication:
          type: tls
        type: route
      plain: {}
      tls:
        authentication:
          type: tls
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 8Gi
      requests:
        cpu: 200m
        memory: 8Gi
    storage:
      type: jbod
      volumes:
        - deleteClaim: true
          id: 0
          size: 1T
          type: persistent-claim
        - deleteClaim: true
          id: 1
          size: 1T
          type: persistent-claim
    tlsSidecar:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
  zookeeper:
    replicas: 3
    storage:
      size: 400Gi
      type: persistent-claim
status:
  conditions:
    - lastTransitionTime: '2020-07-22T14:16:43+0000'
      status: 'True'
      type: Ready
  listeners:
    - addresses:
        - host: kafka-dev-kafka-bootstrap.lagom.svc
          port: 9092
      bootstrapServers: 'kafka-dev-kafka-bootstrap.lagom.svc:9092'
      type: plain
    - addresses:
        - host: kafka-dev-kafka-bootstrap.lagom.svc
          port: 9093
      bootstrapServers: 'kafka-dev-kafka-bootstrap.lagom.svc:9093'
      certificates:
        - |
          -----BEGIN CERTIFICATE-----
          MIIDLTCCAhWgAwIBAgIJAMsRfO7ijEB3MA0GCSqGSIb3DQEBCwUAMC0xEzARBgNV
          BAoMCmlvLnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwHhcNMjAwNzIy
          MTA1NjI1WhcNMjEwNzIyMTA1NjI1WjAtMRMwEQYDVQQKDAppby5zdHJpbXppMRYw
          FAYDVQQDDA1jbHVzdGVyLWNhIHYwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
          CgKCAQEAsxlexF4m9iUQTYH/dzfSWHHD5tROOQPAaJG7h+ioNmhttBbt5rR0o9KL
          f4Yh2+Z3e86sE1I4YhJzgegV1M/T1XqQS+kcjs07dr/dgds3UrIImKLyJNkarxfQ
          hNgzM5hDAxcDmRL1cNO0e8yMdqgWm9/Z4U8zcmElmVDjvzpR8di9rL3ksYcchuyl
          DsLjFFBhStjytvIv+eulwk0ObfqHUmbKwxAG13Zt3qwJiUDrFZk6wr5O31pWPLr3
          IYIiLe030SR/D7r33OntusGkJ0sYDr0YvP45CDHKfSLzIlScBeNCNtrZEJ57a+ql
          PfRtP8Oe+9cAbukahbo9CMiGkLWvgwIDAQABo1AwTjAdBgNVHQ4EFgQUic0pYVxW
          DlITj9ttUtn1ISHcSMowHwYDVR0jBBgwFoAUic0pYVxWDlITj9ttUtn1ISHcSMow
          DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWipydPwxEIqxic8Caj8u
          CRhR8XZmCMHMdUCTdwXS/2ibLsxXBv/lWJPDGm0NteTsZ3Qz7qYYwKOiNby8puXV
          GQZvn+/qSiNiF+YvZE4SxUsG0PwsHORfyDkOtCmC1ASeCQq77CegI/Ki7W0WKdjz
          3k/LJ3t29qLjRCDLEGwNwkH2enUHLO2TQSIdjqbheNjAa3/7wJh+cg54eHH9t0gT
          jOrBU74Jr+ixVRL3XVGuSbPLLfHxAwPTYYBCuhQnuoyjuSup2SAUMP3twtFpcRri
          Mup8+m2WM3HRIPPYPDhIBTZEVH0yHH0akJPMx0YtKfkVNxXrGs4ctHykgzy2WX8I
          QA==
          -----END CERTIFICATE-----
      type: tls
    - addresses:
        - host: kafka-dev-kafka-bootstrap-lagom.apps.marlow.naboocore.com
          port: 443
      bootstrapServers: 'kafka-dev-kafka-bootstrap-lagom.apps.marlow.naboocore.com:443'
      certificates:
        - |
          -----BEGIN CERTIFICATE-----
          MIIDLTCCAhWgAwIBAgIJAMsRfO7ijEB3MA0GCSqGSIb3DQEBCwUAMC0xEzARBgNV
          BAoMCmlvLnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwHhcNMjAwNzIy
          MTA1NjI1WhcNMjEwNzIyMTA1NjI1WjAtMRMwEQYDVQQKDAppby5zdHJpbXppMRYw
          FAYDVQQDDA1jbHVzdGVyLWNhIHYwMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
          CgKCAQEAsxlexF4m9iUQTYH/dzfSWHHD5tROOQPAaJG7h+ioNmhttBbt5rR0o9KL
          f4Yh2+Z3e86sE1I4YhJzgegV1M/T1XqQS+kcjs07dr/dgds3UrIImKLyJNkarxfQ
          hNgzM5hDAxcDmRL1cNO0e8yMdqgWm9/Z4U8zcmElmVDjvzpR8di9rL3ksYcchuyl
          DsLjFFBhStjytvIv+eulwk0ObfqHUmbKwxAG13Zt3qwJiUDrFZk6wr5O31pWPLr3
          IYIiLe030SR/D7r33OntusGkJ0sYDr0YvP45CDHKfSLzIlScBeNCNtrZEJ57a+ql
          PfRtP8Oe+9cAbukahbo9CMiGkLWvgwIDAQABo1AwTjAdBgNVHQ4EFgQUic0pYVxW
          DlITj9ttUtn1ISHcSMowHwYDVR0jBBgwFoAUic0pYVxWDlITj9ttUtn1ISHcSMow
          DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAWipydPwxEIqxic8Caj8u
          CRhR8XZmCMHMdUCTdwXS/2ibLsxXBv/lWJPDGm0NteTsZ3Qz7qYYwKOiNby8puXV
          GQZvn+/qSiNiF+YvZE4SxUsG0PwsHORfyDkOtCmC1ASeCQq77CegI/Ki7W0WKdjz
          3k/LJ3t29qLjRCDLEGwNwkH2enUHLO2TQSIdjqbheNjAa3/7wJh+cg54eHH9t0gT
          jOrBU74Jr+ixVRL3XVGuSbPLLfHxAwPTYYBCuhQnuoyjuSup2SAUMP3twtFpcRri
          Mup8+m2WM3HRIPPYPDhIBTZEVH0yHH0akJPMx0YtKfkVNxXrGs4ctHykgzy2WX8I
          QA==
          -----END CERTIFICATE-----
      type: external
  observedGeneration: 4
`

`apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  creationTimestamp: '2020-07-22T11:09:51Z'
  generation: 3
  name: connect
  namespace: lagom
  resourceVersion: '229813344'
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/lagom/kafkaconnects/connect
  uid: ba157cb9-45f5-4dbc-8d25-9cbea035e117
spec:
  authentication:
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: lenses-user
    type: tls
  bootstrapServers: 'kafka-dev-kafka-bootstrap:9093'
  config:
    config.storage.topic: connect-cluster-configs
    group.id: connect-cluster
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: true
    offset.storage.topic: connect-cluster-offsets
    status.storage.topic: connect-cluster-status
    value.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter.schemas.enable: true
  image: 'image-registry.openshift-image-registry.svc:5000/lagom/deb_connectors:part1'
  replicas: 2
  tls:
    trustedCertificates:
      - certificate: ca.crt
        secretName: kafka-dev-cluster-ca-cert
  version: 2.5.0
status:
  conditions:
    - lastTransitionTime: '2020-07-22T21:06:45.028Z'
      status: 'True'
      type: Ready
  observedGeneration: 3
  url: 'http://connect-connect-api.lagom.svc:8083'
`

`apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  creationTimestamp: '2020-07-22T11:07:26Z'
  generation: 1
  labels:
    strimzi.io/cluster: kafka-dev
  name: lenses-user
  namespace: lagom
  resourceVersion: '229230024'
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/lagom/kafkausers/lenses-user
  uid: 0a332584-b24d-44dc-a4b8-19d879d9dd46
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - operation: Read
        resource:
          name: connect-cluster
          type: group
      - operation: Read
        resource:
          name: connect-cluster-configs
          type: topic
      - operation: Describe
        resource:
          name: connect-cluster-configs
          type: topic
      - operation: Write
        resource:
          name: connect-cluster-configs
          type: topic
      - operation: Create
        resource:
          name: connect-cluster-configs
          type: topic
      - operation: Read
        resource:
          name: connect-cluster-status
          type: topic
      - operation: Describe
        resource:
          name: connect-cluster-status
          type: topic
      - operation: Write
        resource:
          name: connect-cluster-status
          type: topic
      - operation: Create
        resource:
          name: connect-cluster-status
          type: topic
      - operation: Read
        resource:
          name: connect-cluster-offsets
          type: topic
      - operation: Write
        resource:
          name: connect-cluster-offsets
          type: topic
      - operation: Describe
        resource:
          name: connect-cluster-offsets
          type: topic
      - operation: Create
        resource:
          name: connect-cluster-offsets
          type: topic
      - operation: Read
        resource:
          name: connect-cluster
          type: group
      - operation: Read
        resource:
          name: my-topic
          type: topic
      - operation: Describe
        resource:
          name: my-topic
          type: topic
      - operation: Write
        resource:
          name: my-topic
          type: topic
      - operation: Create
        resource:
          name: my-topic
          type: topic
    type: simple
status:
  conditions:
    - lastTransitionTime: '2020-07-22T11:07:54.438Z'
      status: 'True'
      type: Ready
  observedGeneration: 1
  secret: lenses-user
  username: CN=lenses-user
`

[connect-connect-6885c475cd-g65gp-connect-connect(1).log](https://github.com/strimzi/strimzi-kafka-operator/files/4962621/connect-connect-6885c475cd-g65gp-connect-connect.1.log)

**Comment by didentifier** [comment]
It is probably a weird network issue but I don't really understand why, one of the replicas works as expected for now the other one I just restarted it to get the logs from the beginning and it cannot communicate with broker 2. It is pure luck if they work after I restart them.

We use Lenses.io to create connectors which is able to communicate with the 3 brokers without any issues.

I added everything in the zip
[crds-logs.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4962708/crds-logs.zip)

**Comment by scholzj** [comment]
> It is probably a weird network issue but I don't really understand why, one of the replicas works as expected for now the other one I just restarted it to get the logs from the beginning and it cannot communicate with broker 2. It is pure luck if they work after I restart them.

Have you checked if they run on the same worker node and one does work and another one doesn't? Or maybe it is one specific worker node of your cluster which does not work?

-----

Some things I noticed from the logs:

* You seem to use Kafka 2.5.0 for the broker and in he Connect custom resource you also tell the operator that you want to run 2.5.0. But in the log, it seems like the container image you provided is actually running Kafka 2.1.0:

   ```
   2020-07-22 21:03:14,072 INFO Kafka version : 2.1.0 (org.apache.kafka.common.utils.AppInfoParser) [DistributedHerder]
   2020-07-22 21:03:14,072 INFO Kafka commitId : 809be928f1ae004e (org.apache.kafka.common.utils.AppInfoParser) [DistributedHerder]
   ```

   This seems to be confirmed from the log listing the class path artifacts which are also all 2.1.0.

   To avoid any issues, you definitely need to rebuild the image with the Kafka 2.5.0 image from the corresponding  Strimzi version. Using old image can cause problems with both Kafka incompatibilities, but also with misconfiguration of the Connect since the operator always requires proper versions of the helper scripts it has inside the image. So you should look at it and rebuild it with the right base image.

   If you think you build it properly with the correct versions - could it be that the replicas which do not work have some stale version of the image while the running replicas have the proper one?

* It seems weird that none of your logs so far show problems with connecting to the node `-1`. That is used for the initial metadata request. They always seems to complain about one of the broker nodes. So I wonder if you have some problem with the routing to the headless service which is not used for the initial connection to `-1`.

   Maybe you can try to debug this and compere whether you can for example telnet to `kafka-dev-kafka-2.kafka-dev-kafka-brokers.lagom.svc:9093` versus to `kafka-dev-kafka-bootstrap.lagom.svc:9093`.

   You can also check whether the IP addresses in the logs listed behind the service name correspond to the IP address of the Kafka broker pods. If not it would suggest some DNS issue.

**Comment by didentifier** [comment]
Thank you for your help, I thought the latest image was 2.1 for kafka connect  because of this https://hub.docker.com/r/strimzi/kafka-connect I built the image with the correct image now.

As for the rest, I cannot telnet any of them and when I check the IPs they do not correspond to the pods:
"Connection to node 0 (kafka-dev-kafka-0.kafka-dev-kafka-brokers.lagom.svc/10.128.4.27:9093)"

oc get pods -o wide | grep kafka-dev
kafka-dev-entity-operator-66984d576f-l87ht           3/3     Running            0          20h     10.128.4.117   ip-10-0-168-72.eu-west-1.compute.internal    <none>           <none>
kafka-dev-kafka-0                                    2/2     Running            0          20h     10.131.6.88    ip-10-0-138-180.eu-west-1.compute.internal   <none>           <none>
kafka-dev-kafka-1                                    2/2     Running            0          20h     10.130.2.239   ip-10-0-132-230.eu-west-1.compute.internal   <none>           <none>
kafka-dev-kafka-2                                    2/2     Running            0          20h     10.128.6.62    ip-10-0-174-126.eu-west-1.compute.internal   <none>           <none>
kafka-dev-kafka-jmx-trans-754bc55f47-hb99d           1/1     Running            0          17h     10.129.5.45    ip-10-0-156-74.eu-west-1.compute.internal    <none>           <none>
kafka-dev-zookeeper-0                                1/1     Running            1          20h     10.130.2.238   ip-10-0-132-230.eu-west-1.compute.internal   <none>           <none>
kafka-dev-zookeeper-1                                1/1     Running            0          20h     10.129.5.40    ip-10-0-156-74.eu-west-1.compute.internal    <none>           <none>
kafka-dev-zookeeper-2                                1/1     Running            1          20h     10.128.4.116   ip-10-0-168-72.eu-west-1.compute.internal    <none>           <none>

So how would I proceed with troubleshooting the DNS issue? Where the DNS of Openshift really sits and what could I do to propagate the real dns/ ips? Could that be an issue with Openshift 4.4.12, I didn't face such issues before the upgrade

**Comment by scholzj** [comment]
Ok, if the IPs don't correspond to the pods, than it looks like some DNS issue when they are not resolving properly. But I'm afraid I know nothing about how DNS is handled in OpenShift, so I cannot help much to fix that. If some replicas work and some not, maybe the DNS issue is limited only to some worker nodes and just restarting them might help maybe?

**Comment by didentifier** [comment]
I upgraded the whole cluster to 4.4.13 and it fixed it self, I am not 100% sure but maybe just restarting the DNS pods would fix the issue. Either way thank you for your help!
