### ISSUE TITLE
Redesign Kafka rolling updates

### ISSUE THREAD

**Issue by sknot-rh** [strimzi/strimzi-kafka-operator#3362]
Fix https://github.com/strimzi/strimzi-kafka-operator/pull/3348 unveiled some deeper issues with reconciliation design. We should investigate and redesign it. Currently, Kafka rolling updates are happening in multiple places. It should happen only in one place.

**Comment by scholzj** [comment]
Do you think this is still relevant?

**Comment by sknot-rh** [comment]
IIRC this was raised because of handling certificates renewals (and thus RU). I have to admit I do not know in what state are renewals now :(

**Comment by scholzj** [comment]
Triaged on 31.3.2022: Not really sure what it means anymore. Should be closed
