### ISSUE TITLE
Warning events when a cluster configuration can drive to failure

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#337]
Because deploying a cluster with only one Zookeeper node and "ephemeral" storage drives to the failure described by #238, it could be useful to generate a "warning" event (at Kubernetes/OpenShift) level from the cluster controller when such a configuration is detected (or maybe some other similar configuration that could drive to other failures).

**Comment by Frawless** [comment]
I think this was already implemented and could be closed.

**Comment by Frawless** [comment]
Done by Standa in https://github.com/strimzi/strimzi-kafka-operator/pull/2563

```2020-03-20 18:59:58 WARN  AbstractModel:186 - A ZooKeeper cluster with a single replica and ephemeral storage will be in a defective state after any restart or rolling update. It is recommended that a minimum of three replicas are used```

**Comment by scholzj** [comment]
And #2663 I guess.
