### ISSUE TITLE
[Question] Does Strimzi has complete integration with AWS MSK?

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3370]
We want to start by not managing Apache Kafka clusters and offload the heavy lifting to AWS MSK. 
We see you have made really nice CRDs/Operators to work with Apache Kafka 👍 👍 , thanks.

We would want to use these CRDs/Operators with AWS MSK. Is it possible? Does it offer complete integration with AWS MSK?

**Comment by scholzj** [comment]
Not sure I completely understand the question, but I will try ... 

* When it comes to Kafka brokers, when using Amazon MSK, then Amazon is operating your Kafka and it cannot be done by Strimzi. When you deploy Kafka cluster using Strimzi, it will actually deploy it within your own Kubernetes cluster - e.g. within Amazon EKS - manage it and make sure it is running.

* When it comes to other components - such as Connect or Mirror Maker 1 and 2 or the HTTP Bridge - they can connect to any Kafka cluster as long as it supports one of the supported authentication methods. You just have to configure the bootstrap server, credentials etc. The Strimzi operatro will then deploy the Connect cluster for example to your EKS Kubernetes, but the connect will be connecting to your Amazon MSK Kafka, but I have no personal experience. I think there are users using for example Connect like this.

* Additionally, the Topic and User Operators can to some extend be used independently against Amazon MSK as well as long as it supports the right authentication etc. So you can use these and install them from the _standalone installs_. I think there are also users using these with Amazon MSK, but I have no personal experience. 

Was this what you were asking about?

**Comment by alok87** [comment]
this answer my question, this should work with MSK, but this more tested and used with the Kubernetes Strimzi operators managed Kafka.

Thanks.

**Comment by chary1112004** [comment]
Hi @alok87, did you have a chance to tested and used successfully with the Kubernetes Strimzi operators managed MSK?
