### ISSUE TITLE
[Enhancement] Publish release candidate versions on helm repo 

### ISSUE THREAD

**Issue by stoiev** [strimzi/strimzi-kafka-operator#3380]
Strimzi helm repo contains only stable release versions.
Installing release candidates versions of Strimzi directly from helm will be handy for early adopters.

Helm already segregates between stable and development versions based on SemVer postfix presence on install/search/upgrade commands. So publishing release candidate versions will be harmless to actual repo users.
```
$ helm install --help

This command installs a chart archive.
...
      --devel                        use development versions, too. Equivalent to version '>0.0.0-0'. If --version is set, this is ignored
...
```

I've notice that pre-release helm chart tgz already is published on GitHub, so it seems that is just a matter of re-indexing repo.

After this change, we could
```
$ helm search repo strimzi 
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                
strimzi/strimzi-kafka-operator  0.18.0          0.18.0          Strimzi: Apache Kafka running on Kubernetes
$ helm search repo strimzi --devel 
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                
strimzi/strimzi-kafka-operator  0.19.0-rc1      0.19.0-rc1      Strimzi: Apache Kafka running on Kubernetes
$ helm install strimzi/strimzi-kafka-operator --devel  # installs last release candidate operator version
```

Is this feature desirable/feasible/PRs acceptable?

PS: I've noticed that helm index on pre-release versions already are up to date, and adding [this](https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.19.0-rc1/helm-charts/) as a helm repo allows using pre-release versions. It's trickier than using an unified repo, but do the work.

**Comment by scholzj** [comment]
Hmm, nice. I didn't know about this feature. I opened strimzi/strimzi.github.io#174 to give it a try. The preview should be available here if you wanna give it a try and let me know if this works: https://deploy-preview-174--strimzi.netlify.app/charts/index.yaml

**Comment by ppatierno** [comment]
Not an Helm expert but I see that for showing the "development versions", the `--devel` option is used but in the index.yaml, the 0.19.0-rc1 is not "marked" differently from 0.18.0 version; I mean, there is no field saying it's a "development version" and it has to be shown only if `--devel` option is used.  Other than that, why 0.19.0-rc1 is in the index.yaml two times (I see apiVersion v1 and v2) while the previous versions just one (only v1)?

**Comment by scholzj** [comment]
The v1 and v2 are Helm 2 and Helm 3. My understanding is that Helm will parse the versions and decide what is devel and what is not. But I guess @stoiev can confirm it.

**Comment by ppatierno** [comment]
> The v1 and v2 are Helm 2 and Helm 3. My understanding is that Helm will parse the versions and decide what is devel and what is not.

But can't you have devel for both Helm 2 and Helm 3? Does it mean 4 possibilities, not just 2 based on apiVersion, or?
So I could have Helm 2 (v1) release and devel, and Helm 3 (v2) release and devel.
It's not still clear to me :-(

**Comment by stoiev** [comment]
> Hmm, nice. I didn't know about this feature. I opened [strimzi/strimzi.github.io#174](https://github.com/strimzi/strimzi.github.io/pull/174) to give it a try. The preview should be available here if you wanna give it a try and let me know if this works: https://deploy-preview-174--strimzi.netlify.app/charts/index.yaml

It will probably work just like adding https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.19.0-rc1/helm-charts/ as repo did (`index.yaml`'s from both paths are the same, rigth?)

> > The v1 and v2 are Helm 2 and Helm 3. My understanding is that Helm will parse the versions and decide what is devel and what is not.
> 
> But can't you have devel for both Helm 2 and Helm 3? Does it mean 4 possibilities, not just 2 based on apiVersion, or?
> So I could have Helm 2 (v1) release and devel, and Helm 3 (v2) release and devel.
> It's not still clear to me :-(

Unfortunately no..(maybe it's taking first entry).
```
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

$ helm repo add strimzi-0.19 https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.19.0-rc1/helm-charts
$ helm update
...

$ helm install --debug --namespace mm2-test test strimzi-0.19/strimzi-kafka-operator --devel
install.go:159: [debug] Original chart version: ""
install.go:161: [debug] setting version to >0.0.0-0
install.go:176: [debug] CHART PATH: /home/ivan/.cache/helm/repository/strimzi-kafka-operator-helm-2-chart-0.19.0-rc1.tgz
```

Does helm expect a single multi-version package? I'm not a helm expert either.

This issue, however, does not affect release candidates existence on repo.

**Comment by stoiev** [comment]
> Not an Helm expert but I see that for showing the "development versions", the `--devel` option is used but in the index.yaml, the 0.19.0-rc1 is not "marked" differently from 0.18.0 version; I mean, there is no field saying it's a "development version" and it has to be shown only if `--devel` option is used. Other than that, why 0.19.0-rc1 is in the index.yaml two times (I see apiVersion v1 and v2) while the previous versions just one (only v1)?

Helm take dev/no-dev versions from sufix existence. 0.19.0 is a release, 0.19.0-whatever is `devel`.

**Comment by ppatierno** [comment]
> Helm take dev/no-dev versions from sufix existence. 0.19.0 is a release, 0.19.0-whatever is devel.

Ok thanks, that makes sense then.

**Comment by scholzj** [comment]
Triaged on 31.3.2022: There is no actual code change to be done as part of this. It is just a manual process which would change. Currently, the Helm Charts for RCs are published to the GitHub releases and can be used from there.

**Comment by scholzj** [comment]
Just to update this: The release candidates are not pushed to our OCI Helm Chart repositor at Quay.io.
