### ISSUE TITLE
Kafka - Unable to extend Disk size with Namespaced Service account

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3385]
HI,

I am unable to extend disk size with namespaced service account.

i get below error
**Error message:**
`StatefulSet.apps "my-cluster-kafka" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
Tracking number: d7112112291804251`

`Failure executing:GET at: https://172.30.0.1/apis/storage.k8s.io/v1/storageclasses/standard. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. storageclasses.storage.k8s.io "standard" is forbidden: User "system:serviceaccount:pasha-1:kafka-operator" cannot get resource "storageclasses" in API group "storage.k8s.io" at the cluster scope.`

I have created cluster role as in [`name: strimzi-cluster-operator-global`](https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/cluster-operator/021-ClusterRole-strimzi-cluster-operator-role.yaml) and it is associated with the namespaced service account. [ All cluster roles installed at Cluster level, all roles created at namesapce level, cluster roles are associated at namesapce level with rolebinding]

Strimzi version : 0.17.0

As an alternative i created a test cluster role with only storage api(below) and created a rolebinding with SA created at namespace level ..still the same error.

```
- apiGroups:
      - storage.k8s.io

```

Looking for advice to find and address the issue.

**Comment by scholzj** [comment]
The support for resizing storage has to be marked in the StroageClass. So Strimzi needs to always first check the storage class to see whether it supports resizing or not. So we need to be able to read storage classes. This is also configured in the strimzi-cluster-operator-global role (https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/cluster-operator/021-ClusterRole-strimzi-cluster-operator-role.yaml). You need to either give it a rights to do so or not use disk resizing.

**Comment by pashafirdous** [comment]
HI Jakub,

I am not able to follow. it'll be greate if you can elaborate.

i am using the exact same config as strimzi-cluster-operator-global role (https://github.com/strimzi/strimzi-kafka-operator/blob/master/install/cluster-operator/021-ClusterRole-strimzi-cluster-operator-role.yaml)

what rights do i have to add more?

as i said in the question, i have already created a separate clusterrole with storage permission for all storage class and associatd with namesapced SA account..
still issue..
please advice.

**Comment by scholzj** [comment]
I do not think you are using the same setup. For example in our installation files, the service account name is `strimzi-cluster-operator`. You error suggests that your service account is `kafka-operator`. So it looks like you have customized the RBAC files. But without understanding your setup, I cannot really help much more since I do not know how it looks.

If you use your own RBAC files for the operator, you need to make sure to follow the ClusterRoles and ClusterRoleBindings as they are in our own files. Note: the `Cluster` part is important since you cannot grant access to cluster wide resources such as StorageClasses through Roles and RoleBindings-

**Comment by pashafirdous** [comment]
HI Jakub,

My bad for not clarfying.
we have renamed everything starting with  `strimzi-cluster-operator`  to `kafka-operator`
its just same RBAC files/SA implementation

**Comment by scholzj** [comment]
In that case I'm not sure why does the operator not have the rights to see the storage classes.

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks
