### ISSUE TITLE
Kafka topic - i cannot create 2 KT with same name

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3386]
Hi,

query with CRD Kafkatopic 

i cannot create 2 KT with same name on 2 different clusters within same namespace.

i am testing MM , with 2 Kafka clusters spun in a single namespace.
and the above query is a concern for us in an automated deployment using `kafkatopic`
i can still create it manually using kafka-topic.sh command, but not with above method.

looking for any clarifications.

regards,
Pasha

**Comment by scholzj** [comment]
This is how Kubernetes resources work and there is nothing we can do about it. With KafkaTopics you should be able to work around it by using a different name for the resource and specifying the name of the topic in the `.spec.topicName` field (https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaTopicSpec-reference). For other components, there is not solution then using different names. But in general I would recommend you to use different namespaces.

What is your use case for Mirror Maker with two clusters running in the same namespace? Normally one would use Mirror Maker on different Kubernetes clusters and not for clusters in the same namespace.

**Comment by pashafirdous** [comment]
Hi Jakub,

i have just tried one of the use case. MM was just not in plan.
we have more than 1 Kafka cluster in same namespace.
this is limited to teams using the resources

however if they want to have same topic name in both cluster, it fails.

is it possible to add more columns for the kt, like adding clustername before name?

NAME        PARTITIONS   REPLICATION FACTOR
my-topic            12              3

**Comment by scholzj** [comment]
Adding columns alone would not be so hard. But I think that the cluster name is only in the label which might make it hard. I will have a look.

**Comment by scholzj** [comment]
Actually, after some hacking it looks like ti can be done - I opened #3402 for it. We cannot add anything before name - we can just add columns behind it.

**Comment by scholzj** [comment]
I merged the #3402 - not sure what else can we do as part of this issue. Do you have something more? Or can we close it?

**Comment by pashafirdous** [comment]
thanks Jakub,

but, is there a way to enable it for already deployed 0.17.0 version ?

**Comment by scholzj** [comment]
You would need to copy the changes from the PR (https://github.com/strimzi/strimzi-kafka-operator/pull/3402/files#diff-0371597429948ea04ca8d9f5bb40a5b9) into your CRD and reapply it.
