### ISSUE TITLE
[Bug] Helm3 cli pulls v2 helm chart version in 0.19.0

### ISSUE THREAD

**Issue by stoiev** [strimzi/strimzi-kafka-operator#3401]
Strimzi helm repo contains two versions of helm chart release for 0.19.0, one for helm 2 and other for helm 3.
However, there is no way to get helm v3 client working with v3 chart .

This cause errors in installing/updating operator using helm3 clients when CRDs are previously installed

**To Reproduce**
```
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}

$ helm repo add strimzi https://strimzi.io/charts/ 
"strimzi" has been added to your repositories

$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "strimzi" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

$ helm install --debug  --dry-run test  strimzi/strimzi-kafka-operator
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: xxx.cache/helm/repository/strimzi-kafka-operator-helm-2-chart-0.19.0.tgz

Error: rendered manifests contain a resource that already exists...
```

**Expected behavior**
```
$ helm install --debug  --dry-run test  strimzi/strimzi-kafka-operator
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: xxx.cache/helm/repository/strimzi-kafka-operator-helm-3-chart-0.19.0.tgz
```
and no errors

**Comment by scholzj** [comment]
Helm 3 generates the index this way. So I'm not sure why is it picking the helm 2 chart from the index later.

**Comment by stoiev** [comment]
> Helm 3 generates the index this way. So I'm not sure why is it picking the helm 2 chart from the index later.

I could not find an issue/doc on Helm that states about it, but I found some ways to turn packages multi-version.

There was an [initiative](https://github.com/helm/charts/issues/19008) from main helm chart repository (stable/*) to archive this. It seems that `globbing` CRDs from helm3 `crds/` directory for helm2 while maintaining `"helm.sh/hook": crd-install` annotation do the work.

Just like was done in [Prometheus chart](https://github.com/helm/charts/pull/18721/files), for example.

**Comment by scholzj** [comment]
I don't think we are aspiring to have a chart working for both. We have two charts intentionally. The Helm 2 chart is expected to be deprecated soon.

**Comment by scholzj** [comment]
@sgkiokas Any idea how should we deal with the index? Should we have two separate repositories one for Helm 2 and one for Helm 3?

**Comment by sgkiokas** [comment]
@scholzj, apologies about the late reply. I don't know from the top of my head I'm afraid. I'll try to do some experimentation and googling to see what we can do for that matter.

**Comment by klalafaryan** [comment]
@sgkiokas We are having the same problem. We have deployed strimzi (0.18.0) using helm 2, and now we would like to bump up strimzi to 0.19.0 using helm 3 but seems like it is not possible.
Any update on this?
Many thanks!

**Comment by qbarrand** [comment]
Hello! We also hitting that one. Even a link to the `tgz` Helm 3 release would help...

**Comment by scholzj** [comment]
Link is easy ... it is in the GitHub release, at the bottom: https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.19.0

**Comment by klalafaryan** [comment]
@sgkiokas  Did you manage to have a look on this ? Thanks.

**Comment by scholzj** [comment]
@klalafaryan As we are slowly deprecating Helm v2 (which is being deprecated anyway), I will not add it to the index file anymore in 0.20.0 release and I expect it to be removed after the release.

**Comment by scholzj** [comment]
Helm 2 is now completely removed. So I think we can now close this.
