### ISSUE TITLE
[Kafka - Broker Config Info and Topic information] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3403]
Hi Team,

when I execute the Kafka-configs.sh with bootstrap and zookeeper related parameters I am not able to get any broker and topic-related information.  Is this something an issue that is either the same or similar.?

https://issues.apache.org/jira/browse/KAFKA-7720

I am following the Apache Kafka documentation. Need help here.

https://kafka.apache.org/documentation/

```
[kafka@my-cluster-src1-kafka-0 kafka]$ ./bin/kafka-configs.sh --zookeeper localhost:2181 --entity-type topics --entity-name july23-topic --describe
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
Configs for topic 'july23-topic' are
[kafka@my-cluster-src1-kafka-0 kafka]$ ./bin/kafka-configs.sh --bootstrap-server my-cluster-src1-kafka-bootstrap:9092 --entity-type brokers --entity-name 0 --describe
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
^C[kafka@my-cluster-src1-kafka-0 kafka]$ ./bin/kafka-configs.sh --describe --zookeeper localhost:2181 --entity-type brokers
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[kafka@my-cluster-src1-kafka-0 kafka]$ ./bin/kafka-configs.sh --describe --zookeeper localhost:2181 --entity-type topics
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[kafka@my-cluster-src1-kafka-0 kafka]$ ./bin/kafka-configs.sh --describe --zookeeper 127.0.0.1:2181 --entity-type topics
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N

```

**Comment by scholzj** [comment]
We are not using these command line tools in Strimzi. So I'm not sure what the problem would be. Also, you should not use this to change broker configuration as that will be overwritten by the operator and might break the whole cluster. (should be fine for topics)

**Comment by vperi1730** [comment]
I agree with you Scholzj, Question here is we would like to only know/view the existing broker configuration for which we are leveraging the config.sh provided by Kafka. Do you think of any other way to view this information?

**Comment by vperi1730** [comment]
Another question --> If you need any configuration change for the brokers or if you want to assign a topic to a particular broker, Is there a way to achieve this via Kafka CR?

**Comment by scholzj** [comment]
Maybe the kafka-configs.sh utility is showing only the config overrides from Zookeeper? And not the defaults / configs from a file? That would be why it is empty.

For the broker configs:
* The configuration is printed when the Kafka pod starts
* You can also list it inside the pod in `/tmp/strimzi.properties` (but editing this file will not do anything)
* Ultimately, all user configuration should be always in the Kafka CR in `.spec.kafka.config`

For the topics, you can check the KafkaTopic CRs if using the Topic Operator.

--- 

> Another question --> If you need any configuration change for the brokers or if you want to assign a topic to a particular broker, Is there a way to achieve this via Kafka CR?

For most use cases, you should not care about where a particular partition replica is. So it should be enough to just use Cruise Control and ran the rebalance from time to time. If you have some special usecase, you would need to use kafka-reassign-partitions.sh.

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks
