### ISSUE TITLE
[Question] Kafka topics CRD delete and get is not accurate

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3416]
**Describe the bug**
1. Kafka topics does not get deleted  even after repeated delete and wait
2. Kafka topic watch is showing changes when making changes to the mysql database, but the `kafka get topic` shows the topic does not exist.

**To Reproduce**
From the inventory example here: https://strimzi.io/blog/2020/01/27/deploying-debezium-with-kafkaconnector-resource/

**Expected behavior**
Delete should happen eventually but never happens, untill i restart the zookeeper and kakfa pods. (Not a persistent one at present, trying out strimzi)

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.18.0]
 - Kubernetes cluster: [Kubernetes 1.15]

```
$ k version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
 - Infrastructure: [e.g. Amazon EKS, Minikube]
AWS

### Delete not working
```
$ k get kt -n kafka
NAME                                                          PARTITIONS   REPLICATION FACTOR
connect-cluster-configs                                       1            1
connect-cluster-offsets                                       25           1
connect-cluster-status                                        5            1
consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a   50           1
dbserver1.inventory.customers                                 1            1
schema-changes.inventory                                      1            1
```
```
$ k delete kt -n kafka dbserver1.inventory.customers
kafkatopic.kafka.strimzi.io "dbserver1.inventory.customers" deleted
$ k get kt -n kafka | grep dbser
dbserver1.inventory.customers

after 15mins
$ k get kt -n kafka dbserver1.inventory.customers
NAME                            PARTITIONS   REPLICATION FACTOR
dbserver1.inventory.customers   1            1

$ k describe kt dbserver1.inventory.customers -n kafka
Name:         dbserver1.inventory.customers
Namespace:    kafka
Labels:       strimzi.io/cluster=k8s
Annotations:  <none>
API Version:  kafka.strimzi.io/v1beta1
Kind:         KafkaTopic
Metadata:
  Creation Timestamp:  2020-07-30T12:07:57Z
  Generation:          1
  Resource Version:    108757574
  Self Link:           /apis/kafka.strimzi.io/v1beta1/namespaces/kafka/kafkatopics/dbserver1.inventory.customers
  UID:                 cb586394-59dc-4098-ae0c-35912af9cfd1
Spec:
  Config:
  Partitions:  1
  Replicas:    1
  Topic Name:  dbserver1.inventory.customers
Status:
  Conditions:
    Last Transition Time:  2020-07-30T12:07:57.978Z
    Status:                True
    Type:                  Ready
  Observed Generation:     1
Events:                    <none>
```

### Get not showing the topic which is getting processed
It does not show other `dbserver1.*` topics even when the database changes are reaching the topics and consumer is picking them.

**Comment by scholzj** [comment]
Could it be that someone is just recreating the topic? If not, you would need to share the logs from the Topic Operator - ideally at least on debug level - for us to debug what is going on.

**Comment by alok87** [comment]
Sure would do that, there is one more issue in which the topics are not getting listed but the consumer is able to work on that topic.

**Comment by alok87** [comment]
I will reopen a fresh one with complete details if I find this happening again.

**Comment by alok87** [comment]
@scholzj yes you are right, some process is recreating it

```
[2020-07-30 16:45:58,826] INFO  <opicsWatcher:80> [calhost:2181] Deleted topics: [dbserver1.inventory.customers]
[2020-07-30 16:45:58,831] INFO  <opicOperator:535> [oop-thread-1] 1557|/brokers/topics -dbserver1.inventory.customers: Reconciling topic null, k8sTopic:null, kafkaTopic:null, privateTopic:null
[2020-07-30 16:45:58,925] INFO  <opicsWatcher:96> [calhost:2181] Created topics: [dbserver1.inventory.customers]
```

How to find which process is creating it?

**Comment by scholzj** [comment]
The logs are saying that it was recreated in Kafka - so it will be some Kafka client. Maybe you can find something in the Kafka logs. But I'm not sure anything from this is listed at the default settings level.

**Comment by alok87** [comment]
[This report.sh output](https://github.com/strimzi/strimzi-kafka-operator/issues/3419#issuecomment-666600202) can help in debugging this also.

**Comment by scholzj** [comment]
Well, it would collect the logs from brokers. But you need to know what to search for.

**Comment by scholzj** [comment]
Is there still something we can help with here? Or can we close the issue? Thanks
