### ISSUE TITLE
Getting socket connection closed in tls-sidecar container

### ISSUE THREAD

**Issue by shantpschauhan** [strimzi/strimzi-kafka-operator#3417]
We are using Strimzi 0.17.0 amd kafka version 2.4.0 
even without any traffic we are getting the below messages in logs. There are 2 different clusters. I am pasting logs for both.
cluster 1 logs, what we are getting in logs:
2020.07.30 09:18:52 LOG5[1:140376294754048]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.07.30 09:24:53 LOG5[1:140376294754048]: Service [listener-2181] accepted connection from 10.124.21.156:53080
2020.07.30 09:24:53 LOG5[1:140376294754048]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.07.30 09:24:53 LOG5[1:140376294754048]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.07.30 09:24:53 LOG5[1:140376294754048]: connect_blocking: connected 127.0.0.1:21810
2020.07.30 09:24:53 LOG5[1:140376294754048]: Service [listener-2181] connected remote server from 127.0.0.1:39612
2020.07.30 09:24:54 LOG5[1:140376294754048]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.07.30 09:30:51 LOG5[1:140376294754048]: Service [listener-2181] accepted connection from 10.124.21.156:36960
2020.07.30 09:30:51 LOG5[1:140376294754048]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.07.30 09:30:51 LOG5[1:140376294754048]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.07.30 09:30:51 LOG5[1:140376294754048]: connect_blocking: connected 127.0.0.1:21810
2020.07.30 09:30:51 LOG5[1:140376294754048]: Service [listener-2181] connected remote server from 127.0.0.1:41612
2020.07.30 09:30:52 LOG5[1:140376294754048]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.07.30 09:38:52 LOG5[1:140376294754048]: Service [listener-2181] accepted connection from 10.124.21.156:48332
2020.07.30 09:38:52 LOG5[1:140376294754048]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.07.30 09:38:52 LOG5[1:140376294754048]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.07.30 09:38:52 LOG5[1:140376294754048]: connect_blocking: connected 127.0.0.1:21810
2020.07.30 09:38:52 LOG5[1:140376294754048]: Service [listener-2181] connected remote server from 127.0.0.1:44270
2020.07.30 09:38:52 LOG5[1:140376294754048]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.07.30 09:46:52 LOG5[1:140376294754048]: Service [listener-2181] accepted connection from 10.124.21.156:54534
2020.07.30 09:46:52 LOG5[1:140376294754048]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.07.30 09:46:52 LOG5[1:140376294754048]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.07.30 09:46:52 LOG5[1:140376294754048]: connect_blocking: connected 127.0.0.1:21810
2020.07.30 09:46:52 LOG5[1:140376294754048]: Service [listener-2181] connected remote server from 127.0.0.1:47022
2020.07.30 09:46:52 LOG5[1:140376294754048]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.07.30 09:52:51 LOG5[1:140376294754048]: Service [listener-2181] accepted connection from 10.124.21.156:43430
2020.07.30 09:52:51 LOG5[1:140376294754048]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.07.30 09:52:51 LOG5[1:140376294754048]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.07.30 09:52:51 LOG5[1:140376294754048]: connect_blocking: connected 127.0.0.1:21810
2020.07.30 09:52:51 LOG5[1:140376294754048]: Service [listener-2181] connected remote server from 127.0.0.1:48992
2020.07.30 09:52:52 LOG5[1:140376294754048]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.07.30 09:58:51 LOG5[1:140376294754048]: Service [listener-2181] accepted connection from 10.124.21.156:47152
2020.07.30 09:58:51 LOG5[1:140376294754048]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.07.30 09:58:51 LOG5[1:140376294754048]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.07.30 09:58:51 LOG5[1:140376294754048]: connect_blocking: connected 127.0.0.1:21810
2020.07.30 09:58:51 LOG5[1:140376294754048]: Service [listener-2181] connected remote server from 127.0.0.1:51116
2020.07.30 09:58:52 LOG5[1:140376294754048]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket

other cluster in different environment  what we are getting in logs:
This logs captured from gcp console > container logs for tls-sidecar

{  "textPayload": "WARNING: The server has decided to close this client connection.\n",  "insertId": "aval8xerb1zm7ad5n",  "resource": {    "type": "k8s_container",    "labels": {      "container_name": "kafka",      "project_id": "saas-dev-us-cstack-gke1",      "location": "us-east4",      "cluster_name": "gke1",      "namespace_name": "sedsep-dev-saep-opstate-prod-five-ns",      "pod_name": "sedsep-dev-saep-opstate-prod-five-kafka-0"    }  },  "timestamp": "2020-07-27T08:45:20.660803019Z",  "severity": "ERROR",  "labels": {    "k8s-pod/statefulset_kubernetes_io/pod-name": "sedsep-dev-saep-opstate-prod-five-kafka-0",    "k8s-pod/app_kubernetes_io/managed-by": "strimzi-cluster-operator",    "k8s-pod/strimzi_io/kind": "Kafka",    "k8s-pod/strimzi_io/cluster": "sedsep-dev-saep-opstate-prod-five",    "k8s-pod/strimzi_io/name": "sedsep-dev-saep-opstate-prod-five-kafka",    "k8s-pod/app_kubernetes_io/name": "strimzi",    "k8s-pod/controller-revision-hash": "sedsep-dev-saep-opstate-prod-five-kafka-57d59c658c",    "k8s-pod/app_kubernetes_io/instance": "sedsep-dev-saep-opstate-prod-five"  },  "logName": "projects/saas-dev-us-cstack-gke1/logs/stderr",  "receiveTimestamp": "2020-07-27T08:45:27.549949575Z"}
{  "textPayload": "Jul 27, 2020 8:45:20 AM ServerCommunicatorAdmin reqIncoming\n",  "insertId": "aval8xerb1zm7ad5m",  "resource": {    "type": "k8s_container",    "labels": {      "namespace_name": "sedsep-dev-saep-opstate-prod-five-ns",      "cluster_name": "gke1",      "location": "us-east4",      "container_name": "kafka",      "project_id": "saas-dev-us-cstack-gke1",      "pod_name": "sedsep-dev-saep-opstate-prod-five-kafka-0"    }  },  "timestamp": "2020-07-27T08:45:20.660773954Z",  "severity": "ERROR",  "labels": {    "k8s-pod/strimzi_io/kind": "Kafka",    "k8s-pod/app_kubernetes_io/managed-by": "strimzi-cluster-operator",    "k8s-pod/strimzi_io/cluster": "sedsep-dev-saep-opstate-prod-five",    "k8s-pod/controller-revision-hash": "sedsep-dev-saep-opstate-prod-five-kafka-57d59c658c",    "k8s-pod/strimzi_io/name": "sedsep-dev-saep-opstate-prod-five-kafka",    "k8s-pod/app_kubernetes_io/name": "strimzi",    "k8s-pod/statefulset_kubernetes_io/pod-name": "sedsep-dev-saep-opstate-prod-five-kafka-0",    "k8s-pod/app_kubernetes_io/instance": "sedsep-dev-saep-opstate-prod-five"  },  "logName": "projects/saas-dev-us-cstack-gke1/logs/stderr",  "receiveTimestamp": "2020-07-27T08:45:27.549949575Z"}

Please let us understand for this behavior. There is not any traffic on both cluster.
Thanks.

**Comment by shantpschauhan** [comment]
[tls_sidecar-kafka-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021518/tls_sidecar-kafka-1.txt)
[tls_sidecar-kafka-2.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021519/tls_sidecar-kafka-2.txt)
[tls_sidecar-zookeeper-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021520/tls_sidecar-zookeeper-0.txt)
[tls_sidecar-zookeeper-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021522/tls_sidecar-zookeeper-1.txt)
[tls_sidecar-zookeeper-2.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021524/tls_sidecar-zookeeper-2.txt)
[kafka_cr_yaml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021526/kafka_cr_yaml.txt)
[strimzi_operator_logs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021527/strimzi_operator_logs.txt)
[strimzi_operator_yaml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021528/strimzi_operator_yaml.txt)
[tls_sidecar-kafka-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5021529/tls_sidecar-kafka-0.txt)

Attaching all the required logs. Please look into it once and let me know the root cause

**Comment by scholzj** [comment]
Well, you didn't shared any logs from Kafka and Zookeeper. The logs you shared look basically ok. So TBH I do not understand what exactly is the issue you have and what doesn't work. 

So I can really just give you some basic recommendations ... for example for Kafka, I think you can improve the resource configuration. The memory request is very small (I would give it at least 2Gi for some development or test cluster - and lot more for production) and the limit is mostly useless since Kafka isn't able to use it properly. You are also missing resource requests for Zookeeper where again especially the memory request is very important.

**Comment by shantpschauhan** [comment]
Hi Scholzj... Thanks.
I am attaching all the required logs here. 
There is not any traffic in this Kafka cluster but still we find these connection closed error messages.
Please check it once and provide insights for this behavior.
[kafka_cr_yaml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033720/kafka_cr_yaml.txt)
[kafka-kafka-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033721/kafka-kafka-0.txt)
[kafka-kafka-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033724/kafka-kafka-1.txt)
[kafka-kafka-2.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033725/kafka-kafka-2.txt)
[strimzi_kafka-operator_logs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033726/strimzi_kafka-operator_logs.txt)
[strimzi_operator_describe_yaml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033727/strimzi_operator_describe_yaml.txt)
[tls_sidecar-kafka-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033729/tls_sidecar-kafka-0.txt)
[tls_sidecar-kafka-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033730/tls_sidecar-kafka-1.txt)
[tls_sidecar-kafka-2.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033731/tls_sidecar-kafka-2.txt)
[tls_sidecar-zookeeper-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033732/tls_sidecar-zookeeper-0.txt)
[tls_sidecar-zookeeper-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033733/tls_sidecar-zookeeper-1.txt)
[zookeeper-zookeeper-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033734/zookeeper-zookeeper-0.txt)
[zookeeper-zookeeper-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033735/zookeeper-zookeeper-1.txt)
[zookeeper-zookeeper-2.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5033736/zookeeper-zookeeper-2.txt)

**Comment by scholzj** [comment]
So in which log do you see any error messages which make you concerned?

**Comment by shantpschauhan** [comment]
There are many connection reset and connection closed messages coming frequently in kafka logs and in zookeeper TLS side car logs. Concern is to understand this behavior that without any traffic why we are getting these messages .
Kafka Logs:
Aug 05, 2020 4:09:20 PM ServerCommunicatorAdmin reqIncoming
WARNING: The server has decided to close this client connection.
2020-08-05 16:11:22,771 INFO [GroupMetadataManager brokerId=2] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager) [group-metadata-manager-0]
Aug 05, 2020 4:15:20 PM ServerCommunicatorAdmin reqIncoming
WARNING: The server has decided to close this client connection.

Zookeeper tls side car logs:
2020.08.05 16:09:19 LOG5[1:139698888726272]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.08.05 16:11:18 LOG5[1:139698888726272]: Service [listener-2181] accepted connection from 240.0.100.193:37878
2020.08.05 16:11:18 LOG5[1:139698888726272]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.08.05 16:11:18 LOG5[1:139698888726272]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.08.05 16:11:18 LOG5[1:139698888726272]: connect_blocking: connected 127.0.0.1:21810
2020.08.05 16:11:18 LOG5[1:139698888726272]: Service [listener-2181] connected remote server from 127.0.0.1:38458
2020.08.05 16:11:19 LOG5[1:139698888726272]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.08.05 16:13:18 LOG5[1:139698888726272]: Service [listener-2181] accepted connection from 240.0.100.193:33072
2020.08.05 16:13:18 LOG5[1:139698888726272]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.08.05 16:13:18 LOG5[1:139698888726272]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.08.05 16:13:18 LOG5[1:139698888726272]: connect_blocking: connected 127.0.0.1:21810
2020.08.05 16:13:18 LOG5[1:139698888726272]: Service [listener-2181] connected remote server from 127.0.0.1:41872
2020.08.05 16:13:19 LOG5[1:139698888726272]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket
2020.08.05 16:15:18 LOG5[1:139698888726272]: Service [listener-2181] accepted connection from 240.0.100.193:53734
2020.08.05 16:15:18 LOG5[1:139698888726272]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2020.08.05 16:15:18 LOG5[1:139698888726272]: Certificate accepted: depth=0, /O=io.strimzi/CN=cluster-operator
2020.08.05 16:15:18 LOG5[1:139698888726272]: connect_blocking: connected 127.0.0.1:21810
2020.08.05 16:15:18 LOG5[1:139698888726272]: Service [listener-2181] connected remote server from 127.0.0.1:45280
2020.08.05 16:15:19 LOG5[1:139698888726272]: Connection closed: 347 byte(s) sent to SSL, 95 byte(s) sent to socket

**Comment by scholzj** [comment]
The Zookeeper TLS sidecars just show connections from the cluster operator from every reconciliation which happens every 2 minutes. That is correct and expected. So that should not be a problem.

Not sure what the `WARNING: The server has decided to close this client connection.` is. It seems definitely too infrequent to be related to the operator and the log does not seem to show what connection it is closing. So I don't know.

**Comment by shantpschauhan** [comment]
Thanks scholz...... please let me know if we can provide any other/additional logs for the kafka warning messages in kafka pod  logs.....to understand it. or if put debug mode to get more detailed logs to get some more insights and that can help to see if it is related

**Comment by scholzj** [comment]
You can increase the log level in the sidecars: https://strimzi.io/docs/0.17.0/full.html#ref-tls-sidecar-deployment-configuration-kafka ... but I have no idea whether that shows something more.
