### ISSUE TITLE
[Question] Kafka Connect Pod referring to an deleted config map files

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3419]
**Describe the bug**
Connector -> Connect -> Kafka
Bug being reported is the connect cluster pod looking at a deleted config map even when the specification of the connector pod does not have that config map specified.

```bash
$ k get kc
NAME                            DESIRED REPLICAS
mysql-1afe09f-20200730-143340   1

$ k logs -f mysql-1afe09f-20200730-143340-connect-7d4ccb59c9-7k5k7  --tail 1
2020-07-30 14:42:01,993 ERROR [Worker clientId=connect-1, groupId=connect-cluster] Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [DistributedHerder-connect-1-1]
org.apache.kafka.common.config.ConfigException: Could not read properties from file /opt/kafka/external-configuration/stream-inventory-a23f9/inventory.yaml
```

The connect pod is looking to find config map: `stream-inventory-a23f9`
This config map does not exist anymore. It was deleted and was part of previous deployments.

The connect pod YAML has specified a new **config map**:  `stream-inventory-09c4b` 
```
$ k get cm  | grep stream
stream-inventory-09c4b                         1      11m
```

```
$ k get deploy -o yaml mysql-1afe09f-20200730-143340-connect | grep -A2 configMap
      - configMap:
          defaultMode: 420
          name: mysql-1afe09f-20200730-143340-connect-config
--
      - configMap:
          defaultMode: 292
          name: stream-inventory-09c4b
```
The complete YAML can be found here: https://gist.github.com/alok87/fbc60e235ea590c5d8fedb391a5a42ad

Please suggest why is connector pod referring to the old delete YAML, this is happening even after recreating all the resources in the namespace. I am guessing it is retrieving the data from Kafka topic.

**Comment by scholzj** [comment]
I'm not sure I understand the problem. Please provide full logs and all custom resources (or use the report tool https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh to collect all required resources), specify the environment you are running on and version of Strimzi etc.

The configuration of the loaded config maps has nothing to do with KafkaConnector resources, just with KafkaConnect. If you want to change the config maps it is loading, you have to change that first and wait for the pods to be rolled.

**Comment by alok87** [comment]
I was doing a blue green deployment. 
Say Connect Pod A is there and Config map B is there

I was creating Connect Pod B and Config map B and deleting the A ones.

But the Connect Pod B was still referring to Config Map A.

**Comment by scholzj** [comment]
But with Strimzi you are not creating any pods. You are creating custom resources. The deployments and pods are managed by Strimzi. So maybe you can explain your issue step by step with example resources to better understand what were you doing and reproduce it?

**Comment by alok87** [comment]
I have the understanding of how the CRD is working. KC creates the pod, i am creating KC :)
 
Here are the steps to reproduce:

Step1: Create config_map_A, kc_A and kctra_A
Step2: Delete config_map_A, kc_A and kctr_A 
Step3: Create config_map_B, kc_B and kctr_B
Step4: Check the logs of the pod the kc_B will create: say kc_pod_B. 

Issue: You will find kc_pod_B logs full of errors trying to find config_map_A.

Does this help?

**Comment by scholzj** [comment]
No, it doesn't. You will have to provide the information I'm asking for if you want help. Please provide the resources which you are using in the different steps. Also for the deletions please make it clear in which order are you deleting them. If you refer to any log file, please provide the whole log file and not just the part which you think is important. A single line with exception isn't very helpful becuse it doesn't show any context.

**Comment by alok87** [comment]
Here is the report.sh output: https://drive.google.com/drive/folders/1JokyaLZSa0e986GNuIaonCWxkhcuiBMj?usp=sharing

Kafka cluster is running in kafka namespace.
KC, ConfigMaps, KCR are installed in pop namespace.

So 2 zips. Let me know when you download the files, i will delete them.

**Comment by scholzj** [comment]
I download the files so you can delete them.

But they still contain only single KafkaConnect CR and single KafkaConnector CR. So I do not know how does the other one look like. Neither you say in which order you deleted them. 

What I suspect, is that you delete them in wrong order. Kafka Connect is storing the configuration in Kafka it self. The topic names are configured in the KafkaConnect CR (https://strimzi.io/docs/operators/latest/full/using.html#con-kafka-connect-multiple-instances-deployment-configuration-kafka-connect). I guess right now you use the same (default) settings for both. And if you don't delete the connector first and wait until it is actually deleted, the new Kafka Connect instance will load it from the config topics on broker including the old configuration and fail. 

So IMHO you need to either first delete the connector make sure it is deleted and then delete the Connect. Or delete the topics after you delete the connect. Or deploy the connect with new set of topics for offsets, config etc. to not continue where the old left off.

**Comment by alok87** [comment]
Thanks, for the explanation. I will get back on this.

**Comment by alok87** [comment]
So this is what we are trying to achieve.
Say we have 3 databases: database_1, database_2, database_3
For each database we are trying to make the events stream to Kafka using strimzi operators to do the management.
```
database1 -> kctrA_1 -> kcA -> kafka
database2 -> kctrA_2 -> kcA -> kafka
database3 -> kctrA_3 -> kcA -> kafka
```

So there is a single kc process/pod managing the sync for all the three databases in a single namespace. Kafka is in another namespace.

So I am understanding it correctly, one of the suggestion is this, right?

- `kubectl delete kctr/kctrA_1 kctr/kctrA_2 kctr/kctrA_3 -n pop`.
- `kubectl delete kcA`.
-  create kcB with new change.
-  recreate kctrs again with the new change.
This will result in all of them starting with new change and the events will stream from last where it last processed. Correct?

My only concern with this approach say my database grows to a huge number then all of them would need to stop for a single database change to be deployed. I was doing this so that i do not need to run multiple KC processes.

But this should work right?

**Comment by scholzj** [comment]
If you want to have one KafkaConnect instance with multiple connectors you do not need to deploy it multiple times. You do it just once with all the configuration. And then you create all 3 connectors pointing to it. You do not need to recreate anything to do some changes. You either edit the original YAML file and do `kubectl apply -f ...` or use `kubectl edit ...`. But nowhere in this process you need to delete anything.

**Comment by alok87** [comment]
@scholzj what if want the deployment to be only create and delete operations and not have any updates. Since all our deployments are like that we want to keep it the same way.

Also since we have the whole tool in place to create config maps, version it etc..

**Comment by scholzj** [comment]
TBH, I do not think this is really how it should work ... this will cause lot of disruption to the system. All the operators are designed to work the way that you change the custom resources. Not delete and recreate them.

But apart from that it should be always first delete connector and then delete the KafkaConnect. Not sure what kind of behavior you expect here with regards to the offsets etc. - in theory you could delete also the Connect topics before the new deployment.

**Comment by alok87** [comment]
Thanks, what happens when the KCTR is deleted? are the plugins removed from connect pod and it is reloaded?

**Comment by scholzj** [comment]
First of all, the process is asynchronous. When you do `kubectl delete` you just remove it from the etcd database in Kubernetes. From there, the operator will learn about it and will call the REST API to delete the connector. And from there it is up to Connect. We do not delete the plugins - the plugins are just some JARs on the classpath. We delete only the connector instance.

**Comment by alok87** [comment]
Does not the KCTR delete wait for the JARs to be removed from the classpath, just like POD delete is not considered deleted untill all the containers are removed from the system?

**Comment by scholzj** [comment]
No, It is not. The JARs are present in the pod all the time from the start till the end. They anyway cannot be deleted by the operator - the container is immutable. To know the delete happened you would need to query the REST API of connect directly.

**Comment by alok87** [comment]
Thank you so much for the help.

**Comment by alok87** [comment]
I did the following, still the KC pod looked for the old config map. Going with update :( 
```
kubectl delete kctr/kctrA_1 kctr/kctrA_2 kctr/kctrA_3.
wait for delete to get complete.
kubectl delete kcA.
create kcB with new change.
wait for kcB status to be ready.
create kctrsB with the new change but this time linked with kcB.
```
