### ISSUE TITLE
[Enhancement] Propagate Availability Zone into KafkaConnect pod to use in the client.rack property

### ISSUE THREAD

**Issue by arnitolog** [strimzi/strimzi-kafka-operator#3426]
We have a distributed KafkaConnect setup with 2 workers in different AZs. We want to use “fetch from closest replica” feature. And in order to do that, we need to specify the `client.rack` property in the KafkaConnect consumer's configuration. But there is no way to pass AZ information to the configuration

**Describe the solution you'd like**
It will be good to have the same option for KafkaConnect as for Kafka Cluster:

```
spec:
    rack:
      topologyKey: failure-domain.beta.kubernetes.io/zone
```

**Comment by arnitolog** [comment]
Also, I think, it will be good to have such an option for all consumers managed by Strimzi Operator:
MirrorMaker1.0
MirrorMaker2.0
KafkaBridge

**Comment by scholzj** [comment]
Triaged on 31.3.2022: Should be split into new issues for Bridge and MM2. MM1 is deprecated and we should not invest into it anymore. Once the new issues are created, we can close this one.

**Comment by scholzj** [comment]
#6611 and #6610opened for Bridge and MM2. This issue was dedicated to Connect and can be closed as done.
