### ISSUE TITLE
[Enhancement] Support Kerberos based authentication type

### ISSUE THREAD

**Issue by donovanmuller** [strimzi/strimzi-kafka-operator#3437]
**Is your feature request related to a problem? Please describe.**
Support for configuring Kerberos authentication for Mirror Maker consuming/producing from external brokers with Kerberos based authentication. 

We use a security configuration similar to the following to use Kerberos based authentication to the brokers:

Example `strimzi-producer.properties`
```properties
bootstrap.servers=...
sasl.mechanism=GSSAPI
security.protocol=SASL_PLAINTEXT
sasl.kerberos.service.name=kafka
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required \
  useKeyTab=true \
  storeKey=true \
  keyTab="xxx.keytab" \
  principal="test@test.com";
```

the above configuration is not possible today, given that `sasl.` is a forbidden property. 
The above is in context of using Mirror Maker, when producing to external brokers.

**Describe the solution you'd like**
The ability to describe the configuration above would prevent us from having to build a custom image and using a stand alone deployment (not via `KafkaMirrorMaker` CR) of Mirror Maker to be able to configure the above.

**Describe alternatives you've considered**
We currently build a custom image the and run as a stand alone Deployment.

**Comment by scholzj** [comment]
I think this is more or less duplicate to #3088

**Comment by scholzj** [comment]
Closing as duplicate to #3088
