### ISSUE TITLE
[Enhancement] Add support for Kafka 2.6.0

### ISSUE THREAD

**Issue by sgkiokas** [strimzi/strimzi-kafka-operator#3470]
Kafka 2.6.0 is [out](https://downloads.apache.org/kafka/2.6.0/RELEASE_NOTES.html) so it will be nice to add support for it.

**Comment by scholzj** [comment]
I think there is (will be very soon) also 2.5.1. And we should remove 2.4.0 and 2.4.1. Since it is all work around the same files, it should be done together I guess.

**Comment by jpechane** [comment]
Hi,
a question: 2.6.0 is changing recommended Scala version to 2.13. Would you use it by default too or do you plan to saty with the one base upon Scala 2.12?

**Comment by scholzj** [comment]
I think we will stay with 2.12 for now. Might change later.
