### ISSUE TITLE
[Question] consumer_offsets topic consuming all PVC space

### ISSUE THREAD

**Issue by JollyZeus** [strimzi/strimzi-kafka-operator#3487]
i have a strimzi 0.17.0 / kafka 2.4.0 cluster, where the broker PVCs (size: 2GiB) run out of space after a few days of operation.
A workaround is to fully recreate the cluster and PVCs, but it fills up again after a few days

Interestingly, it seems like the `__consumer_offsets` topic seems to be the main culprit, while the "main" topics use basically nothing at all.
```
sh-4.2$ du -sh /var/lib/kafka/data-0/kafka-log0/*  | sort -hr      
72M     /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-9
71M     /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-22
70M     /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-30
69M     /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-5
36M     /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-33
26M     /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-16
25M     /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-41
6.0M    /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-2
5.9M    /var/lib/kafka/data-0/kafka-log0/__consumer_offsets-1
...
```

the settings around log cleaning / retention and offsets-retention are the default out-of-the-box settings that came with Strimzi:
```
	log.cleaner.delete.retention.ms = 86400000
	log.cleaner.enable = true
	log.cleanup.policy = [delete]
[...]
	log.retention.bytes = -1
	log.retention.check.interval.ms = 300000
	log.retention.hours = 168
	log.retention.minutes = null
	log.retention.ms = null
[...]
	offsets.retention.check.interval.ms = 600000
	offsets.retention.minutes = 10080
```

checking the topic configuration for `__consumer_offsets`, i see that cleanup.policy is set to compact, which is apparently correct according to [this](https://stackoverflow.com/questions/42546501/problems-with-the-retention-period-for-offset-topic-of-kafka#comment94751922_51953888)
```
./bin/kafka-configs.sh --zookeeper localhost:21810 --describe --entity-type topics --entity-name __consumer_offsets'
Configs for topic '__consumer_offsets' are segment.bytes=104857600,cleanup.policy=compact,compression.type=producer
```

does anyone have any idea why the consumer_offsets are growing so rapidly?

PS: thanks for creating the Strimzi project - i think its awesome!

**Comment by scholzj** [comment]
TBH, I do not think you can really run Kafka reliably with 2Gi of space. The settings are all just the defaults from Kafka. You can for sure try to play with the different settings, try to decrease the partitions count for consumer offsets, they to play with the retentions and segment sizes. In general, I think sizing for so small storage can be quite tricky as there are different indexes and something happen only on closed segments etc.

**Comment by JollyZeus** [comment]
hi @scholzj , thanks for your response. Ok, so it sounds like you are saying that the consumer_offsets topic is behaving normally, and that the cluster (at 2GiB per node) simply does not have enough disk space to handle normal operations.

So I have switched the PVCs to be resizable, to handle situations where it starts to run out of space.
I know that sizing a kafka cluster is a fine art, that depends on many variables, but do you perhaps know what a sane starting point would be, for a small kafka cluster?

Would 10GiB per broker / 10GiB per zookeeper node be sufficient?

**Comment by scholzj** [comment]
TBH, without really knowing the details of what you are doing, it is hard to say how much space is enough. I usually use 100GB as my starting point. But I guess in some cases 10Gi might be enough. Zookeeper normally does not need so much disk space as brokers, so it should be for sure enough there.

**Comment by JollyZeus** [comment]
ok, thanks for that feedback, and thanks again for strimzi! :)

**Comment by sugam72** [comment]
@JollyZeus I think you can set `log.retention.hours` to a smaller value to clear the PVC at regular internals.
