### ISSUE TITLE
Synchronous delete

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#349]
When we delete the Kafka or Zookeeper resources we just delete the resources. We don't wait for dependent resources (like pods and endpoints) to definitely be removed. We need to be sure those resources have definitely been removed before we consider the overall deletion complete.

**Comment by scholzj** [comment]
I think this has been done as part of the `selfClosingWatch` and it is not used when deleting resoruces. This can be closed.
