### ISSUE TITLE
[Enhancement] Add a pre-commit git hook to check commits are signed for DCO

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#3504]
**Is your feature request related to a problem? Please describe.**
Currently many PR travis runs fail due to lack of commit signing, I wonder if adding a pre-commit hook prompting a user to fix their dco prior to a push would save everyone time in the long run?

First time contributors are the most likely to hit into this problem, and it may sour their contribution experience. By making this easier we  stand to potentially gain more contributions.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tomncooper** [comment]
We already have one in the `tools/git-hooks` folder. Details of how to set it up are in the [developer guide](https://github.com/strimzi/strimzi-kafka-operator/blob/master/development-docs/DEV_GUIDE.md#dco-signoff).

**Comment by samuel-hawker** [comment]
Closing after discussion on Slack, even automated locally, contributions through the Web UI would still run into this issue.
