### ISSUE TITLE
[Enhancement] Scheme Registry CRD

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3509]
**Is your feature request related to a problem? Please describe.**
Need a crd to install schema registry, preferably https://github.com/confluentinc/schema-registry#installation

Let me know if it is in scope of strimzi to provide.

**Comment by scholzj** [comment]
This seems to be duplicate to #29. Please have a look there on the thoughts about Schema Registry and why we specifically can not support Confluent Schema Registry with its proprietary license. You can also have a look at this: https://github.com/lsst-sqre/strimzi-registry-operator ... maybe that would be useful for you

**Comment by joekohlsdorf** [comment]
> This seems to be duplicate to #29. Please have a look there on the thoughts about Schema Registry and why we specifically can not support Confluent Schema Registry with its proprietary license.

Schema Registry is licensed under Apache 2.0 🤔 
https://github.com/confluentinc/schema-registry/blob/master/LICENSE

**Comment by scholzj** [comment]
@joekohlsdorf The files says _The project is licensed under the Confluent Community License,_. Only the clients have Apache License 2.0.

**Comment by joekohlsdorf** [comment]
Ups, I better get my eyes checked...
