### ISSUE TITLE
[Question] How to add Kafka AVRO connector to strimzi image?

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3511]
```
FROM strimzi/kafka:0.18.0-kafka-2.5.0
USER root:root
RUN mkdir -p /opt/kafka/plugins/debezium
COPY ./debezium-connector-mysql/ /opt/kafka/plugins/debezium/
USER 1001
```

I created an image with mysql convertor following the strimzi documentation. I need to add AVRO connector class to this image. Can you please suggest how it can be done.

The above image does not have the class, getting errors like these
```
2020-08-14 12:20:21,481 ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed) [main]
org.apache.kafka.common.config.ConfigException: Invalid value 

io.confluent.connect.avro.AvroConverter for configuration key.converter: Class io.confluent.connect.avro.AvroConverter could not be found.
```
`

I could not find where to download that class. `io.confluent.connect.avro.AvroConverter`

Also clear out the confusion between the images provided by Debezium here and the one strimzi provides https://github.com/debezium/docker-images/tree/master/connect/1.2

**Comment by scholzj** [comment]
You have to add them in the same way as you add the connector. You can either add them to the plugins folder or directly to `/opt/kafka/libs`. But I do not know what is the right place to download the AVRO converter - maybe from Maven or somewhere from Confluent.

**Comment by alok87** [comment]
Thank you, i found this https://github.com/debezium/docker-images/blob/master/connect-base/1.2/Dockerfile#L39
