### ISSUE TITLE
Kafka Zookeeper - Monitoring disk metrics

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3514]
Hi,

Is there a method to monitor the Disk/storage for Kafka and zookeeper.

we have enabled CPU/Memory metrics in Prometheus but we cant find the disk metrics.

please advice.

regards,
Pasha

**Comment by scholzj** [comment]
It might depend on which metrics, but IIRC disk metrics are from Kubernetes. So you might need to configure cadvisor metrics or something like that to provide information about disks.

**Comment by pashafirdous** [comment]
Hi Jakub,

but is it possible to get the disk metrics from within the pods with the metrics we are already getting ?
we see CPU_total/Memory virtual metrics.

we want to observe the contianer disk pods.

do you have any reference for strimzi with cadvisor

**Comment by scholzj** [comment]
Kafka it self does not provide any metrics like available disk space. The CPU and Memory metrics you are getting should be already from Kubernetes cAdvisor and the likes of it.

Two things you can check:
* I think that @ppatierno did some fixes recently to some of the Prometheus queries. Maybe you can try to use the latest Prometheus and Grafana files from master. But Paolo is away for 2 weeks now and I'm not sure if he will get here to provide any more details whether hsi changes might be related or not.
* What kind of storage are you using? For example on my local development cluster, I have just some faked persistent disks made out of directories. These do not have any real metrics. The same would IMHO apply for example also on Minikube and the likes of it. So you need to check those metrics with real environment with real disks (in my case usually AWS)

**Comment by pashafirdous** [comment]
I have strimzi deployed on gke wirh standard disk.

**Comment by scholzj** [comment]
Oki, then the metrics should work. The Grafan dashboard we have seems to be using the metric `kubelet_volume_stats_available_bytes` ... so I guess you should check directly in Prometheus is you can find this metric (maybe just the labels are wrong) eventually whether you can find any `kubelet_...` metric there.

**Comment by ppatierno** [comment]
Can you access the Prometheus UI and see in the Targets tab if the kubelet target is up and running?

**Comment by ppatierno** [comment]
As Jakub said, you should check that the kubelet target is up and running, because it's providing the disk related metrics.

**Comment by scholzj** [comment]
@pashafirdous Anything more we can help here with?

**Comment by pashafirdous** [comment]
thanks closing issue.
