### ISSUE TITLE
[Enhancement] Update Jaeger Tracing Client to v1.3.2 to support the w3c trace context

### ISSUE THREAD

**Issue by chgl** [strimzi/strimzi-kafka-operator#3519]
**Is your feature request related to a problem? Please describe.**

Jaeger-core supports the recent [W3C Trace Context](https://www.w3.org/TR/trace-context/) propagation format since version [1.2.0](https://github.com/jaegertracing/jaeger-client-java/blob/master/CHANGELOG.md#120-2020-03-11). W3C is the default format for many OpenTelemetry client libraries (Python, .NET, JS), supporting it would make it easier to integrate Strimzi with them.

**Describe the solution you'd like**
Strimzi currently uses [v1.1.0 of jaeger-core](https://github.com/strimzi/strimzi-kafka-operator/blob/master/pom.xml#L111). It would be great if the version could be updated to the latest v1.3.2. 

**Describe alternatives you've considered**
Other propagation formats, b3 or the jaeger default, could be used instead.

**Additional context**

**Comment by scholzj** [comment]
Thanks for opening the issue. We will have a look.
