### ISSUE TITLE
Corner case in rollingUpdate

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#352]
The code in `StatefulSetOperator.rollingUpdate()` gets the number of replicas and tries to restart each pod. If the #replicas in the SS is modified directly while this happens the code will break! Since rolling update takes a long time the window for this race is large.

**Comment by scholzj** [comment]
Triaged on 26.5.2022: Will not be so easy with StrimziPodSets anymore which do not have the replicas field. This can be closed.
