### ISSUE TITLE
[Enhancement] Support configuring the TLS Secret on Ingress listener to enable cert-manager support for issuing certificates

### ISSUE THREAD

**Issue by donovanmuller** [strimzi/strimzi-kafka-operator#3521]
**Is your feature request related to a problem? Please describe.**
Currently when using the [Kubernetes Ingress](https://strimzi.io/docs/operators/latest/using.html#assembly-kafka-broker-external-listeners-ingressdeployment-configuration-kafka) external listener with Nginx Ingress controller, there is no way to specify a [TLS](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) `secretName`, which would allow `cert-manager`, for example, to issue certificates for the Ingress resources.

**Describe the solution you'd like**
When using the Kubernetes Ingress external listener with Nginx Ingress controller, I would like the ability to use `cert-manager` to issue certificates for the created [Ingress resources](https://cert-manager.io/docs/usage/ingress/#how-it-works). To do this I would require a way to configure two properties:

1. add annotations like `cert-manager.io/issuer` etc.
2. specify a `secretName`

The first property is configurable using `dnsAnnotations`, however, there doesn't seem to be an option to specify the `secretName` currently.

If the `secretName` could be specified, it would allow certificates to be issued by `cert-manager` for the created Ingress resources.

**Comment by scholzj** [comment]
First of all, please be aware that Strimzi requires TLS Passthrough. So the TLS certificate has to be done in the Kafka brokers and not in the Ingress it self. With that, it is not clear to me why you cannot use https://strimzi.io/docs/operators/latest/full/using.html#kafka-listener-certificates-str to configure the certificate which should be used.

**Comment by donovanmuller** [comment]
Thanks for the suggestion @scholzj, I completely missed that feature.

**Comment by jr200** [comment]
A recent blog suggests it should be possible to setup an ingress with an external listener and cert-manager plus lets-encrypt certificates. (I'm using jcmorais' haproxy ingress controller rather than nginx).

Blog: https://strimzi.io/blog/2021/05/07/deploying-kafka-with-lets-encrypt-certificates/

Following the above guide, it seems that the ingress object that gets created doesn't set the tls secretName, even though I have specified it in the `brokerCertChainAndKey`. The ssl-passthrough annotations are also set to true on the ingress object, which I didnt think should be the case. Any hints on how to debug this?

**Comment by scholzj** [comment]
@jr200 With TLS Passthrough any Ingresss secrets are completely irrelevant because the connection is passed directly into the broker. So you will not see any secrets specified on Ingress.

**Comment by jr200** [comment]
Yes, I agree. But I think your blog is saying you can do ssl-termination at the ingress (which is a way to access the kafka brokers from outside). In this case, I would have expected a tls secret to sit on the ingress object with my lets-encrypt issued certificate?

**Comment by scholzj** [comment]
No, it does not say anything like that. Kafka protocol is not HTTP based and (most) Ingress controllers would not understand it. That is why you always need to use TLS passthorugh.

**Comment by jr200** [comment]
Ah, yes thats right - because ssl-passthrough is just tcp-mode! Then in that case I definitely read too much into it. 
So the mechanism is to just have the bootstrap and broker-X servers use the lets-encrypt-issued certificates instead of those which would have been issued by kafka's CA?

**Comment by scholzj** [comment]
Yes, correct.

**Comment by scholzj** [comment]
As described in https://strimzi.io/blog/2021/05/07/deploying-kafka-with-lets-encrypt-certificates/, this should now be possible, although in slightly different way (the certificates need to be set in Kafka and not in Ingress due to the TLS passthrough). I think this can be closed.
