### ISSUE TITLE
[Kafka User Secrets Weird Behaviour Noticed] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3543]
Hi Team,

I have been working on creating various Kafka users across different namespaces, somehow today noticed a pattern that I found to be a little weird in terms of user secrets ca.crt field.  The following are the 2 use cases attempted.

1) When we create a Kafka user essentially there would be a K8 secret with the same name that contains ca.crt and other key & password contents. Also, the ca.crt for this kafka user is signed by the Cluster CA all the time, meaning ca.crt from your cluster-ca-cert matches with the ca.crt of the Kafka user. (No issues in this use case)

2) Now I have a new scenario where the following is the combination.

Namespaces : kafka-src and kafka-tgt
Cluster names are identical across both the namespaces(let's say cluster1)
Kafkauser is also identical across both the namespaces(let's say user1)

Weird behaviour is after creating the Kafka user in src namespace, we have created the same user in the TGT namespace as well and in both the cases the secrets which got created has the ca.crt signed by the Clients CA but not Cluster CA. 

3) Also realized that any number of users we create after the above operation is always signed by the Client CA only. 

I would like to understand this little in detail about the reason for this behaviour?

**Comment by scholzj** [comment]
The `ca.crt` in the KafkaUser secret is always the public key of the Clients CA. Never the Cluster CA. That is in order to have the full chain inside the secret if ever needed.

**Comment by vperi1730** [comment]
OK, Just to understand what does it mean if we notice the kafkauser signing authority is Cluster CA?

**Comment by scholzj** [comment]
Well, that would be probably a bug (but the User Operator does not read the Cluster CA IMHO, so not sure how it would happen). Only other ideas which come to my mind is standalone User Operator installation configured to use Cluster CA or custom CA with Cluster and Client CA being the same.

**Comment by vperi1730** [comment]
Ok, As such we didn't make use of any Custom CA, instead, we are testing this with the default strimzi configuration parameters only.  The following is the configuration we are using.

```
clusterCa:
      generateCertificateAuthority: true
    clientsCa:
      generateCertificateAuthority: true

entityOperator:
      topicOperator: {}
      userOperator: {}
```

**Comment by scholzj** [comment]
Yeah, I assumed you would have mentioned it since you would have to know about it. But especially if it is something what happened only for some KafkaUsers it would be a very weird bug.
