### ISSUE TITLE
[Enhancement] Validate doc references to YAML properties

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#3550]
While reviewing https://github.com/strimzi/strimzi-kafka-operator/pull/3447 I realised that we have an awful lot of references to YAML properties of the form `` `<CrKind>.<path>.<to>.<config>` `` and it's it's easy for these to be incorrect. Since we have reflective access to the Java model (which is how we generate the API reference) it would be relatively simple to validate these as part of the build:

1. Walk through the documentation directories reading `.adoc`
2. Search the adoc for things which look like the references above. 
3. For each such reference validate the path.

**Comment by PaulRMellor** [comment]
Hello @tombentley I see that some doc updates were made from your initial investigation. Let me know if further work is required on the docs.

**Comment by tombentley** [comment]
Thanks @PaulRMellor, let's close this one.

**Comment by PaulRMellor** [comment]
Thanks @tombentley
