### ISSUE TITLE
About the error /apis/kafka.strimzi.io/v1beta1/namespaces/../status not found

### ISSUE THREAD

**Issue by AvihuHenya** [strimzi/strimzi-kafka-operator#3559]
Environment (please complete the following information):
    Kubernetes: 1.10.0+b81c8f8 
    OpenShift: 3.10.83

I am trying to upgrade my strimzi version from v0.14.0 to v0.18.0. I just installed the new strimzi version in my OpenShift cluster, and got that the Reconciliation is failing with this error:
AbstractOperator:468 - Reconciliation #0(watch) Kafka(strimzi/my-cluster): Failed to update status

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://172.30.0.1/apis/kafka.strimzi.io/v1beta1/namespaces/strimzi/kafkas/my-cluster/status . The server could not find the requested resources

I knew this error from the time i was working with v0.14.0, but despite this error I was able to work and create all types of kafka resources (kafka, user, topic etc).
know, after I successfully created the operator deployment of v0.18.0, I tried to apply new yamls of kind kafka, but know although the operator recognize the requests for new resources creation (i saw it in the operator logs), it didn't create any new resource.

What i thought is that maybe between that two version a change has been made to the operator, so that it now creates resources only if it receives their status. do you know if my hypothesis is correct?

Since upgrading the OpenShift&Kubernetes versions of my cluster will be in a few months only i prefer to working in that direction.

Thanks in advance.

**Comment by scholzj** [comment]
Actually, support for Kubernetes 1.10 was dropped in 0.12. SoI would expect that even 0.14 does not work properly.
