### ISSUE TITLE
Is it possible to define namespace in connectCluster for MM2?

### ISSUE THREAD

**Issue by ElectricRabbit** [strimzi/strimzi-kafka-operator#3562]
We have few clusters each in its own namespace and I'm trying to mirror some topic from one cluster to another using MM2.

The problem is that we named all clusters with same name "franz" to be able simplified some automations and nugets to be universally applicable for each team in their team namespace. But now I've found out that in this situation when I define connectCluster parameter with name of clustrer which is not specific nothing happens with log message:

_WARN  AbstractOperator:247 - Reconciliation #851(timer) KafkaMirrorMaker2(finance/finance-to-logistics): Failed to acquire lock lock::finance::KafkaMirrorMaker2::finance-to-logistics within 10000ms._

connectCluster: "franz.namespace" doesn't work. Is there some possibility how to extend name with namespace when all kafka object have same name?

_ERROR AbstractOperator:175 - Reconciliation #960(watch) KafkaMirrorMaker2(finance/finance-to-logistics): createOrUpdate failed
io.strimzi.operator.cluster.model.InvalidResourceException: connectCluster with alias franz.logistics cannot be found in the list of clusters at spec.clusters
	at io.strimzi.operator.cluster.model.KafkaMirrorMaker2Cluster.lambda$fromCrd$1(KafkaMirrorMaker2Cluster.java:96) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?]
	at io.strimzi.operator.cluster.model.KafkaMirrorMaker2Cluster.fromCrd(KafkaMirrorMaker2Cluster.java:96) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.assembly.KafkaMirrorMaker2AssemblyOperator.createOrUpdate(KafkaMirrorMaker2AssemblyOperator.java:130) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.cluster.operator.assembly.KafkaMirrorMaker2AssemblyOperator.createOrUpdate(KafkaMirrorMaker2AssemblyOperator.java:71) ~[io.strimzi.cluster-operator-0.19.0.jar:0.19.0]
	at io.strimzi.operator.common.AbstractOperator.lambda$reconcile$3(AbstractOperator.java:174) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
	at io.strimzi.operator.common.AbstractOperator.lambda$withLock$6(AbstractOperator.java:230) ~[io.strimzi.operator-common-0.19.0.jar:0.19.0]
	at io.vertx.core.shareddata.impl.LocalAsyncLocks$LockWaiter.lambda$acquireLock$1(LocalAsyncLocks.java:65) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.9.1.jar:3.9.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.50.Final.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]_

Where can I find **list of clusters at spec.clusters** mentioned in error log?

**Comment by ajborley** [comment]
Hi - the `spec.connectCluster` field in your `KafkaMirrorMaker2` CR needs to match the `alias` field of one of the clusters in the list of clusters in `spec.clusters`. See the example CR in the docs here: https://strimzi.io/docs/operators/latest/using.html#proc-mirrormaker-replication-str

Note that the `alias` field in each `spec.clusters` item in your CR is just an alias, so can be any name you would like to use, but must be unique within the list of clusters.

**Comment by ElectricRabbit** [comment]
Oh, I thought aliases must match with Kafka clusters names. Now it is clear to me and it's working. 

Many thanks for the clarification @ajborley

**Comment by ppatierno** [comment]
Yeah, the doc should be clear enough about this https://strimzi.io/docs/operators/master/using.html#type-KafkaMirrorMaker2Spec-reference otherwise let us know how we can improve it.

**Comment by ElectricRabbit** [comment]
Maybe you can just add short note like "aliases doesn't have to match with Kafka cluster names"

I have one more question about spec.clusters target authentication and tls.

My definition is:

  _- alias: "logistics-franz" # target
    authentication:
      type: scram-sha-512
      username: target-cluster-user
      passwordSecret:
        secretName: target-cluster-user-secret
        password: password
    bootstrapServers: target-cluster:9093
    tls:
      trustedCertificates:
        - secretName: target-cluster-ca-cert
          certificate: ca.crt_

Now, my MM2 deployment has error:

_MountVolume.SetUp failed for volume target-cluster-user" : secret "target-cluster-user-secret" not found_

which is logical, because that is user for target cluster in other namespace. I assumed, that userOperator is able somehow use user from target cluster (in other namespace).

And another error about TLS configuration is, that "_target-cluster-ca-cert_" (which has same name as same name as  "_source-cluster-ca-cert_") already exists.

**Comment by scholzj** [comment]
> which is logical, because that is user for target cluster in other namespace. I assumed, that userOperator is able somehow use user from target cluster (in other namespace).
> And another error about TLS configuration is, that "target-cluster-ca-cert" (which has same name as same name as "source-cluster-ca-cert") already exists.

No, it doesn't have access to the other cluster. So you will need to copy these manually.

**Comment by ElectricRabbit** [comment]
I'm coming back to you again guys, I still couldn't get MM2 up and running.
This is my configuration now I tried with and without TLS config of target server:

`apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: finance-to-logistics
  namespace: finance
spec:
  version: 2.5.0
  replicas: 1
  connectCluster: "logistics" # target
  clusters:
  - alias: "finance" # source
    bootstrapServers: franz-kafka-bootstrap:9092
    authentication:
      type: scram-sha-512
      username: usr-accounting-admin
      passwordSecret:
        secretName: usr-accounting-admin
        password: password
    tls: {}
  - alias: "logistics" # target
    bootstrapServers: franz-kafka-bootstrap.logistics:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
    authentication:
      type: scram-sha-512
      username: usr-logistics-admin
      passwordSecret:
        secretName: usr-logistics-admin
        password: password
    tls:
      trustedCertificates:
        - secretName: logistics-franz-cluster-ca-cert
          certificate: ca.crt
  mirrors:
  - sourceCluster: "finance"
    targetCluster: "logistics"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: "accounting-availability-productcount"
    groupsPattern: ".*"
`
and still getting authentication errors from target cluster:
**2020-09-10 11:53:19,753 WARN [AdminClient clientId=adminclient-1] Connection to node -1 (franz-kafka-bootstrap.logistics/10.108.21.131:9092) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient) [kafka-admin-client-thread | adminclient-1]
**

but I still assume I don't need to use tls.trustedCertificates as in documentation is written that I can pick one of provided methods. (Authentication for the source cluster, using the TLS mechanism, as shown here, using OAuth bearer tokens, or a SASL-based SCRAM-SHA-512 or PLAIN mechanism.) I have **SCRAM-SHA-512** defined on both clusters.

I don't uderstand what is the purpose of target server user and which access it should has? Shoud it be pre-prepared user with topic write/create/describe/read for future mirrored topic in target cluster? is possible define some "Admin KafkaUser" with all right and topic resource.name "*" to use it for every mirrored topic in target cluster?

**Comment by scholzj** [comment]
You are connecting to port `9092` which with Strimzi suggests no TLS. But both aliases also enable TLS in MM2? That would also cause this kind of error. So maybe you should disable TLS (remove the whole `tls` section)?

**Comment by scholzj** [comment]
Yes. `tls: {}` still enables TLS just with the default system certificates. You should completely remove it.

**Comment by ElectricRabbit** [comment]
Thanks a lot, that really helped. Did I miss this information somewhere in documentation? It's little bit confusing as I'm used to helm charts where configuration like this means, that you can use it but it is not used with {}.

Now my next issue seems to be similar to this one [https://github.com/strimzi/strimzi-kafka-operator/issues/3207](url)

**Comment by scholzj** [comment]
I think the listener configuration is definitely described in the docs: https://strimzi.io/docs/operators/latest/full/using.html#assembly-configuring-kafka-broker-listeners-deployment-configuration-kafka ... but if there something is not clear, feel free to let us know. In any case, The listener configuration and the related docs move to a new format in Strimzi 0.20.0, which hopefully makes this a bit more clear.

> Now my next issue seems to be similar to this one https://github.com/strimzi/strimzi-kafka-operator/issues/3207 :/

TBH I'm not sure whihc part of that issue exactly you have in mind. Might be best to open a new issue if needed maybe.

**Comment by ElectricRabbit** [comment]
> I think the listener configuration is definitely described in the docs: https://strimzi.io/docs/operators/latest/full/using.html#assembly-configuring-kafka-broker-listeners-deployment-configuration-kafka ... but if there something is not clear, feel free to let us know. In any case, The listener configuration and the related docs move to a new format in Strimzi 0.20.0, which hopefully makes this a bit more clear.
> 
> > Now my next issue seems to be similar to this one #3207 :/
> 
> TBH I'm not sure whihc part of that issue exactly you have in mind. Might be best to open a new issue if needed maybe.

It seems I finally solved all my issues and MM2 is working now. Thanks a lot @scholzj for your answers. We can close this.

**Comment by scholzj** [comment]
Great. Glad it works now. Thanks.
