### ISSUE TITLE
[Question] Access Kafka Part2: NodePorts with Loadbalancer in between

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3590]
https://strimzi.io/blog/2019/04/23/accessing-kafka-part-2/

I followed this article to expose the Kafka service for a multi cluster K8s setup.
```kubectl
NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
k8s-kafka-0                    NodePort    100.66.195.56    <none>        9094:30711/TCP               6h43m
k8s-kafka-1                    NodePort    100.64.87.216    <none>        9094:31722/TCP               6h43m
k8s-kafka-2                    NodePort    100.65.56.158    <none>        9094:30733/TCP               6h43m
k8s-kafka-bootstrap            ClusterIP   100.69.176.253   <none>        9091/TCP                     6h43m
k8s-kafka-brokers              ClusterIP   None             <none>        9091/TCP                     6h43m
k8s-kafka-external-bootstrap   NodePort    100.71.19.191    <none>        9094:30744/TCP               6h43m
k8s-zookeeper-client           ClusterIP   100.66.197.91    <none>        2181/TCP                     6h44m
k8s-zookeeper-nodes            ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   6h44m
schema-registry501             NodePort    100.69.111.165   <none>        8081:31196/TCP               5h46m
```

I created a AWS Classic Loadbalancer with all the above node ports ^ as TCP forward.
In the client i need to specify the external bootstrap server, when the bootstrap server is the node-ip:30744 it works but when the bootstrap server is loadbalancer:30744 it does not.

## Works
client -> node-ip:node-port -> pod (broker1)

## Does not work
client -> ELB -> node-ip:node-port -> pod (broker1)

Please suggest why so?

**Comment by scholzj** [comment]
I'm sorry, but I do not follow what are you trying to do. If you wanna use load balancers, then you should follow the part 4: https://strimzi.io/blog/2019/05/13/accessing-kafka-part-4/

**Comment by alok87** [comment]
Yes i know about that. We do not use Loadbalancer type in Kubernetes but we use a manually created Loadbalancer with nodeports.

This is because we have a custom Kubernetes Loadbalancer controller.

So we use Loadbalancer and add node ports to it and then use elb: port address to route

**Comment by scholzj** [comment]
So I do not know what could the problem be if you use a custom stuff because I do not know how it works I'm afraid. In general, you would need to:
* Configure the advertised hostnames and ports for each broker in the Kafka CR to point to list the load balancer address / port
* Make sure the load balancer and nodes have the right security group to forward the traffic
* Configure the load balancer to route to the node ports

If you say it all works apart from the bootstrap service, then I would expect you badly configured the routing or security between load balancer and the bootstrap service. The bootstrap connection just gets to any broker, requests the metadata and opens new connections directly to the brokers. So there is actually not much to go wrong.
* Can you telnet to `loadbalancer:30744` and do you connect somewhere?
* What is the exact message from your client? (ideally use the Java clients from Kafka since I know the errors there)

**Comment by alok87** [comment]
ok,  just found out this.
the issue is not happening from the client i wrote, but is happening from [schema registry](https://github.com/confluentinc/schema-registry) pod **only**.

I have supplied BOOTSTRAP server as ELB:port does not work for it.
```
- name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: PLAINTEXT://ELB: 30744
```

Error
```
[main] ERROR io.confluent.admin.utils.ClusterStatus - Error while getting broker list.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:262)
	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:149)
	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
```

Why could it work for my client but not schema registry? 
I may open this in their repo also.

**Comment by scholzj** [comment]
I honestly don't know ... and I have no experience with the Confluent Schema Registry. I'm not sure what it is waiting for there.

**Comment by alok87** [comment]
Sure sir, thank you, this is not a strimzi problem now. thanks.
