### ISSUE TITLE
Question : How to increase the JVM size for strimzi operator running in strimzi operator pod.

### ISSUE THREAD

**Issue by shantpschauhan** [strimzi/strimzi-kafka-operator#3597]
Hi Team,
Can you please let me know the options/procedure to increase jvm size for strimzi  running on strimzi operator pod.

**Comment by scholzj** [comment]
Sorry, what exactly does JVM size mean? Things such as -Xmx etc.?

**Comment by shantpschauhan** [comment]
yes ... in strimzi operator pod kafka-operator container is running .... that runs strimzi java process  i need to know that how we can increase heap size for this JVM

**Comment by shantpschauhan** [comment]
Hello @scholzj 
Please help us to get answer for the question in above "how we can increase java heap memory for strimzi operator". 
Thanks in advance.

**Comment by scholzj** [comment]
You should just increase the resources to the operator. Java will then automatically configure things like -Xmx. If you really need to set your own, you should be able to set it in the `JAVA_OPTS` environment variable.

**Comment by shantpschauhan** [comment]
Thanks @scholzj ... This helps.

**Comment by scholzj** [comment]
Great. Can we close this?
