### ISSUE TITLE
Yet another question on exposing kafka to external clients

### ISSUE THREAD

**Issue by mugugnu** [strimzi/strimzi-kafka-operator#3611]
Hello,
i've been through the strimzi docs explaining the loadbalancer and ingress case, but still i'm a little confused, so apologies if i ask these questions.
Assuming i choose the loadbalancer option (seems to be better performing than ingress), strimzi will create an external bootstrap service with an external IP which the external client can use to make the first contact with kafka. However this IP is not reliable, as destroying the service and recreating will make the IP change. So how clients are supposed to get a "stable endpoint" to make the first contact with kafka ? (the same goes for the per-broker services that should be contacted once bootstrapping has completed)

If loadbalancer is not suitable for giving clients stable IPs to connect to, than i'd have to switch to the ingress option which at least is exposing a stable IP (and i can always create a dns alias for the bootstrap ip and for all the brokers).
Would this solution work ? I'm confused first of all because the ingress acts like a l7 http load balancer, but i expect kafka client to use the kafka protocol and not http (am i wrong here?) and most importantly: bootstrap and brokers would all get the same IP (the ingress IP) and would be distinguished only by the  DNS aliases. 
Any help would be appreciated.

Regards,
Mugugnu

**Comment by scholzj** [comment]
Why would the load balancer address not be reliable? It is true that if you delete and recreate it it usually changes the address. But why would you delete and recreate it? So I'm not sure I understand this concern. It is very common that load balancers are long lived. If for whatever reason yours isn't, you can also for example give it some additional DNS name and use that to configure your clients. And if you decide to delete and recreate the load balancer, you can just update the DNS name to the new load balancer and it is done. 

You can use Ingress as well. The way Strimzi uses Ingress is that uses the TLS passthrough feature. Where the Kafka traffic is basically hidden HTTPS - since the Ingress controller never decodes it it doesn't care that inside is not HTTP but TCP connection.

Last year I wrote a blog post series about exposing Kafka: https://strimzi.io/blog/2019/04/17/accessing-kafka-part-1/ ... if you haven't read that yet you can have a look at it. It goes a bit more into the detail how these options work.

**Comment by mugugnu** [comment]
I agree that deleting the service which creates the LB is not a common thing to do, but i think we should be able to rebuild the whole infrastructure anytime the way it was before and changing the IP which external parties use to connect to seems to me something which goes against this and would not be acceptable.

Regarding the ingress i understand i can use it for kafka as well, still i don't get if i can use it in my case. 

I'll try to explain my concern:  other k8s applications are already creating ingresses for allowing access from outside.
The load balancer will check the request URL and route to the appropriate pod inside kubernetes. 
To make this work, i've created a DNS alias for each of these services.
In this way i can connect my browser to http://dns-alias-web:80 and be routed the the GUI of the right application inside k8s or i can connect to http://dns-alias-xx:80 and be connected to the GUI of another application inside k8s and so on.

Would this still be working if i added dns aliases for kafka bootstrap and brokers (it would still be the same IP as above), and configure them here:

    listeners:
      # ...
      external:
        type: ingress
        configuration:
          bootstrap:
            host: <my dns alias for bootstrap>
          brokers:
          - broker: 0
            host: <my dns alias for broker0>
          - broker: 1
            host: <my dns alias for broker1>
          - broker: 2
            host:<my dns alias for broker2>

BTW: I read your blog about this topic, i find it's the most valuable around on the subject. I'm probably a little fresh to grasp it all, that's why i'm asking all these questions !

**Comment by scholzj** [comment]
The addresses in the Strimzi `listeners` configuration are used to configure the Ingress. Strimzi will not set and DNS records, you will have to do it your self. But apart form that it works as any other apps - the only difference is that with Kafka you will need many addresses (1 per broker + bootstrap). With most other applications like GUIs you just have one.

**Comment by mugugnu** [comment]
I understand that i have to set the dns entries by myself. 
Once i've done this, am i supposed to set them here ?
  # ...
  external:
    type: ingress
    configuration:
      bootstrap:
        host: <my dns alias for bootstrap>

**Comment by scholzj** [comment]
For Ingress yes, for LBs no. But that is basically independent. So you can set them there before you configure the DNS, it is just that without the DNS the clients will not connect.

**Comment by mugugnu** [comment]
I thought that for LB i'd use the advertisedhost:

    type: loadbalancer
    overrides:
      brokers:
      - broker: 0
        advertisedHost: <my dns alias>

Is it only meant to provide IPs ?

**Comment by scholzj** [comment]
With LBs you do not need to do anything for the brokers. Just for the bootstrap service. The brokers will be found through the metadata via the bootstrap service. So you should not really care if their IP address change.

**Comment by scholzj** [comment]
Imean, if you would want to use the DNS name for the brokers, you can set it in the advertisedHost ... but it doesn't have any value IMHO.

**Comment by mugugnu** [comment]
Uhmm..by "just for the bootstrap service" you mean i should put it in the DNS and use advertisedHost ? in the example it was shown for brokers, is it applicable to bootstrap as well (for LB case) ?

I think i got what you say about putting brokers in the dns being useless, let's see if i'm right: bootstrap will give the client the IP of the broker to connect to. That is the external IP of the per-broker service that strimzi creates when configuring LB, so the client is provided with a working IP (external to k8s) and no dns alias is needed. right ?

**Comment by scholzj** [comment]
> Uhmm..by "just for the bootstrap service" you mean i should put it in the DNS and use advertisedHost ? in the example it was shown for brokers, is it applicable to bootstrap as well (for LB case) ?

There is no advertised host for bootstrap. But if you use TLS you should add it as the bootstrap address which will add it to the certificates.

> I think i got what you say about putting brokers in the dns being useless, let's see if i'm right: bootstrap will give the client the IP of the broker to connect to. That is the external IP of the per-broker service that strimzi creates when configuring LB, so the client is provided with a working IP (external to k8s) and no dns alias is needed. right ?

Yes, that is what I meant.

**Comment by mugugnu** [comment]
ok thanks a lot for the explanation !!!
