### ISSUE TITLE
[Question] Deleting Kafka Cluster does not delete associated PV & PVC in Azure

### ISSUE THREAD

**Issue by agrajm** [strimzi/strimzi-kafka-operator#3617]
When I delete the Kafka Cluster, the PVC & PV remains unaffected and are not deleted automatically? Is this by design? If yes, what is the possibility of re-using them with a new Kafka cluster - I mean how can we attach an existing PVC/PV to a new Kafka cluster ?

**Comment by scholzj** [comment]
> When I delete the Kafka Cluster, the PVC & PV remains unaffected and are not deleted automatically? Is this by design?

This is standard Kubernetes behavior. When you delete StatefulSet, the PVCs and PVs remain in the system and you need to delete them manually. This is basically an additional protection layer -> if you delete the application by mistake you will still have the PVCs to recover from.

Strimzi allows you to set `deleteClaim` flag to true and take care of the deletion. But I would recommend it only for development. Definitely not for production.

> If yes, what is the possibility of re-using them with a new Kafka cluster - I mean how can we attach an existing PVC/PV to a new Kafka cluster ?

If you recreate a new cluster with the same name, it will automatically reuse the existing PVCs. If you want to use another name, you would need to create the PVCs with the matching names and bound the old PVs to them.

**Comment by agrajm** [comment]
Thank you, super helpful !

**Comment by IlyaNakhaichuk** [comment]
@scholzj hello 
After re-creating the cluster, with the existing pvc, my pods do not start. I did not change the name of the cluster, because the pvc contains the data necessary for the cluster.
Log:
```
strimzi-cluster-operator-6b7b6989db-74xcc         1/1     Running             0          24h
strimzi-zookeeper-0                     0/1     ContainerCreating   0          35s
strimzi-zookeeper-1                     0/1     ContainerCreating   0          35s
strimzi-zookeeper-2                     0/1     ContainerCreating   0          35s
```
describe pod(event):
```
Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Normal   Scheduled           28s                default-scheduler        Successfully assigned kafka/strimzi-zookeeper-0 to host-1
  Warning  FailedAttachVolume  0s (x17 over 28s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-fe44d160-1ff7-415a-ba7b-59ee87efe4b3" : volume attachment is being deleted
```

Any idea what I did wrong and what I need to change to get the cluster up and running?

**Comment by scholzj** [comment]
@IlyaNakhaichuk No idea -> it looks like your Kube cluster has trouble attaching the volumes. But I do not know why. MAybe the Kube logs can give you some hints, but I'm not really expert on this to give you some more precises pointers what to look for I'm afraid.

**Comment by dearboll23** [comment]
Hi [scholzj](https://github.com/scholzj), I set the deleteClaim flag as false, but when I deleted my kafka cluster via **argo-cd**, the PVCs also were deleted as below. Do you have any idea or a bug from argo-cd?
``` shell 
yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
NAME                                DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS   READY   WARNINGS
kafka.kafka.strimzi.io/liuyu-test   3                        3

NAME                                    READY   AGE
statefulset.apps/liuyu-test-zookeeper   0/3     2s

NAME                                                STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/data-liuyu-test-kafka-0       Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-1       Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-2       Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-zookeeper-0   Terminating   pvc-dc3ad1f0-4a50-4dbb-8c53-dbcef3001f14   1Gi        RWO            standard          8h
persistentvolumeclaim/data-liuyu-test-zookeeper-1   Terminating   pvc-0ec32628-daa1-4221-b7e5-7dfa365df982   1Gi        RWO            standard          8h
persistentvolumeclaim/data-liuyu-test-zookeeper-2   Terminating   pvc-0330b1b9-2922-4fd6-b7aa-73085538a1b7   1Gi        RWO            standard          8h
yu@CN-MB-yu kafka-sc %
yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
NAME                                            STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/data-liuyu-test-kafka-0   Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-1   Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-2   Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
NAME                                            STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/data-liuyu-test-kafka-0   Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-1   Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-2   Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
yu@CN-MB-yu kafka-sc %
yu@CN-MB-yu kafka-sc %
yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
NAME                                            STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/data-liuyu-test-kafka-0   Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-1   Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
persistentvolumeclaim/data-liuyu-test-kafka-2   Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
yu@CN-MB-yu kafka-sc %
yu@CN-MB-yu kafka-sc %
yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
No resources found in kafka namespace.
```

**Comment by dearboll23** [comment]
> Hi [scholzj](https://github.com/scholzj), I set the deleteClaim flag as false, but when I deleted my kafka cluster via **argo-cd**, the PVCs also were deleted as below. Do you have any idea or a bug from argo-cd?
> 
> ```shell
> yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
> NAME                                DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS   READY   WARNINGS
> kafka.kafka.strimzi.io/liuyu-test   3                        3
> 
> NAME                                    READY   AGE
> statefulset.apps/liuyu-test-zookeeper   0/3     2s
> 
> NAME                                                STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> persistentvolumeclaim/data-liuyu-test-kafka-0       Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-1       Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-2       Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-zookeeper-0   Terminating   pvc-dc3ad1f0-4a50-4dbb-8c53-dbcef3001f14   1Gi        RWO            standard          8h
> persistentvolumeclaim/data-liuyu-test-zookeeper-1   Terminating   pvc-0ec32628-daa1-4221-b7e5-7dfa365df982   1Gi        RWO            standard          8h
> persistentvolumeclaim/data-liuyu-test-zookeeper-2   Terminating   pvc-0330b1b9-2922-4fd6-b7aa-73085538a1b7   1Gi        RWO            standard          8h
> yu@CN-MB-yu kafka-sc %
> yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
> NAME                                            STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> persistentvolumeclaim/data-liuyu-test-kafka-0   Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-1   Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-2   Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
> yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
> NAME                                            STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> persistentvolumeclaim/data-liuyu-test-kafka-0   Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-1   Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-2   Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
> yu@CN-MB-yu kafka-sc %
> yu@CN-MB-yu kafka-sc %
> yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
> NAME                                            STATUS        VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
> persistentvolumeclaim/data-liuyu-test-kafka-0   Terminating   pvc-0f098317-863c-424f-836e-58a103cbb43b   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-1   Terminating   pvc-ac6f7c4c-aff2-4488-a020-aa0270c02b33   2Gi        RWO            pd-standard-xfs   5h20m
> persistentvolumeclaim/data-liuyu-test-kafka-2   Terminating   pvc-1a54ad1a-c450-4c62-891f-dfba4ba32c65   2Gi        RWO            pd-standard-xfs   5h20m
> yu@CN-MB-yu kafka-sc %
> yu@CN-MB-yu kafka-sc %
> yu@CN-MB-yu kafka-sc % kubectl get kafka,sts,pvc
> No resources found in kafka namespace.
> ```

I'm sorry I found that deletion were triggered by argocd.
