### ISSUE TITLE
[Doc] Strange note in JMXTrans section

### ISSUE THREAD

**Issue by tomncooper** [strimzi/strimzi-kafka-operator#3620]
There is a strange note in `documentation/modules/proc-jmxtrans-deployment.adoc` line 21:

```
NOTE: JmxTrans will not come up enable you specify that JmxOptions on the Kafka broker.
For more information see, xref:assembly-jmx-options-{context}[Kafka Jmx Options]
.Configuring JmxTrans output definitions
```

I am not sure what it should say, but it is probably not that?

**Comment by scholzj** [comment]
I guess it is trying to say that _you need to enable JMX in order to use JMX Trans_ maybe? 

@julianGoh17 You might know what this should mean ...

**Comment by laidan6000** [comment]
I'll pick this one up.
