### ISSUE TITLE
[Question] Zookeeper communication issue (strimzi-operator version >= 0.18.0)

### ISSUE THREAD

**Issue by vutkin** [strimzi/strimzi-kafka-operator#3626]
Hi all, on earlier version (strimzi<=0.16.0 for example) I can communicate with zookeeper using initContainer, check that it's up and running using next script:
```
result=1; until [ $result -eq 0 ]; do OK=$(echo ruok | nc -w 1 octopus-zookeeper-nodes 21810 ); if [ "$OK" == "imok" ]; then result=0; echo "zookeeper returned imok!"; else echo waiting for zookeeper to be ready; sleep 1; fi; done; echo "Success: zookeeper is up"
```
Now it not works with port 21810 and even with 2181,12181...

Is port 21810 is not usable now?
Could you please advise how can now we should communicate with zookeeper without authorization?

**Comment by vutkin** [comment]
Hi Jakub @scholzj could you please advise?

**Comment by scholzj** [comment]
2181X was related to how the TLS sidecars were used for securing Zookeeper. Since Zookeeper now supports things like encryption and authentication out of the box, we dropped the sidecars and the port numbers changed. The port 12181 should now work as replacement (in all pods the port number is the same).

**Comment by vutkin** [comment]
Hm....
Just an example of running same command inside zookeeper pod:
```
› k exec -t my-cluster-zookeeper-0 -- sh -c 'echo ruok | nc -w 1 localhost 12181'
imok%
```
-------------
Same for `ubuntu` container with netcat inside:
12181 port: failed
```
› k exec -t debug -- bash -c "echo ruok | nc -vw 1 octopus-zookeeper-nodes 12181"
nc: connect to octopus-zookeeper-nodes port 12181 (tcp) failed: Connection refused
nc: connect to octopus-zookeeper-nodes port 12181 (tcp) failed: Connection refused
nc: connect to octopus-zookeeper-nodes port 12181 (tcp) failed: Connection refused
command terminated with exit code 1
```
2181 port: there is no iamok
```
› k exec -t debug -- bash -c "echo ruok | nc -vw 1 octopus-zookeeper-nodes 2181"
Connection to octopus-zookeeper-nodes 2181 port [tcp/*] succeeded!
```
What I am doing wrong?

**Comment by scholzj** [comment]
The 12181 service is not exposed. So I would not really expect to be able to use it like this through the service. It should be accessible only inside the pod. But that should have been the same with the original 2181X. They were also internal only and did not existed on the services. 

The SCRAM-SHA authentication is Kafka only, so that should not have any impact.

**Comment by vutkin** [comment]
> The 12181 service is not exposed.
@scholzj Do you mean that zookeeper listen only localhost:12818?

**Comment by scholzj** [comment]
Yes, on 127.0.0.1 ... plus the port is not exposed on the pod level.

**Comment by scholzj** [comment]
TBH, I'm not sure what exactly is your use case. But Strimzi never really supported access to Zookeeper from outside. The best (unofficial) way how to get access to Zookeeper is this: https://github.com/scholzj/zoo-entrance ... maybe it helps.

**Comment by vutkin** [comment]
Thank you. I just want that my application be sure that kafka is up and running and it could start too.

**Comment by scholzj** [comment]
So do you want to find out the Kafka nodes from the Zookeeper states? Or do you first check the Zookeepers and then the Kafka pods?

**Comment by vutkin** [comment]
> Or do you first check the Zookeepers and then the Kafka pods?

Correct, I check if Zookeer is alive and then I am sure that kafka is up and running, so my application could start too.

**Comment by vutkin** [comment]
By the way some tools like CMAK (https://github.com/yahoo/CMAK) and confluent control center need to connect to zookeeper too.

**Comment by scholzj** [comment]
Well, that is one of the reasons the zoo-entrance mini-project exists. But Zookeeper will be gone from Kafka soon - so I think using any tool which requires Zookeeper is a liability these days.
