### ISSUE TITLE
Add a test for structual schema

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#3628]
We should add an integration or system test that uses a suitable version of kubernetes to test that our schemas are [structural schemas](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema).

**Comment by scholzj** [comment]
But we do not use structural schema ... you would first need to generate it.

**Comment by tombentley** [comment]
I was thinking more of editing the generated one prior to presenting it to kube.

**Comment by tombentley** [comment]
I mean it's mostly changing the api version of the CRD, right?

**Comment by scholzj** [comment]
No, the CRDv1 is very different. And our current schema is also not structural. So this would need changes to the code to first generate them. I pleased with it some time ago: https://github.com/strimzi/strimzi-kafka-operator/compare/master...scholzj:crdv1 ... so in theory we can try to merge it and use it for some testing etc. The way I did it it supports both versions in parallel IIRC.

**Comment by scholzj** [comment]
@tombentley I assume this is covered by https://github.com/strimzi/strimzi-kafka-operator/blob/master/api/src/test/java/io/strimzi/api/kafka/model/StructuralCrdIT.java?
