### ISSUE TITLE
Ingress and TLS

### ISSUE THREAD

**Issue by mugugnu** [strimzi/strimzi-kafka-operator#3629]
Hello,
i've read that strimzi ingress needs ssl and ssl passthrough on the ingress controller to route kafka non-http client requests to kafka broker inside kubernetes. At least this is what i've understood.

Now the question: if the above is correct, do kafka brokers need to have tls enabled as well to make this communication work, or the SSL can be terminated at the ingress level and proceed to kafka borkers which where tls has not been set ?

**Comment by scholzj** [comment]
When you use the `type: ingress` listener, it will always have TLS enabled. So that is required there. The TLS Passthrough is something what needs to be configured inside the Ingress controller.

**Comment by mugugnu** [comment]
Ingress will always have tls enabled regardless of this setting, right ?

spec:
  kafka:
    version: 2.5.0
    replicas: 5
    listeners:
      external:
        type: ingress
        **tls: false**

I was wondering if internal listeners could be set to plain and not tls in this case or to use ingress i'd have to set them to use tls too

**Comment by scholzj** [comment]
Yes. In 0.19.0, there is no `tls` field in the Ingress configuration: https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaListenerExternalIngress-reference ... It will be in the new listener configuration in 0.20.0, but you would need to have it set to `true` for Ingress.
