### ISSUE TITLE
TLS Option for zookeeper

### ISSUE THREAD

**Issue by WoodProgrammer** [strimzi/strimzi-kafka-operator#3635]
Hi everyone

I'm the newbie on strimzi. I deployed a basic cluster with CRD it works successfully (consuming, producing.).
But when I want to access zookeeper it returning this error shown below.

error.log
```
2020-09-13 00:26:19,877 WARN Exception caught (org.apache.zookeeper.server.NettyServerCnxnFactory) [nioEventLoopGroup-7-2]
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: fff4fffd06
```

Regarding that, zookeeper returning TLS error while my topic operator connecting. How can I disable tls option on zookeeper for my sandbox environment?

Thanks

**Comment by scholzj** [comment]
ZooKeeper is not accessible in Strimzi for security and stability reasons. If you really want to use it, you can at your own risk use this unofficial tool: https://github.com/scholzj/zoo-entrance ... but keep in mind that Zookeeper is being removed from Kafka and when it is we will also remove it from Strimzi.

**Comment by WoodProgrammer** [comment]
I just wondered, so how can I install topic operator without zookeeper now ?

**Comment by scholzj** [comment]
You have to deploy it as part of the Kafka custom resource: https://strimzi.io/docs/operators/latest/full/deploying.html#deploying-the-topic-operator-using-the-cluster-operator-str

**Comment by WoodProgrammer** [comment]
yes I have tried it it works well thank you
