### ISSUE TITLE
[Enhancement] Add an operator metrics to reflect the latest reconcile of a custom resource

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3642]
It would be useful to have a metric from the operators that provide information about the status of a specific reconciled resource.
For example, a metric that is 1 or 0 to define that a `Kafka` custom resource was reconciled successfully or not (os it's in the `Ready` status or `NotReady` due to an error).
This metric could bring labels as `kind`, `name`, and `namespace` to identify the reconciled custom resource uniquely.
For example:

`strimzi_reconcile_resource{kind="Kafka", name="my-cluster", namespace="my-kafka-namespace"}`

The same for all the kind of resources are handled today.

**Comment by scholzj** [comment]
* Would something like `strimzi_resource_state` be better name?
* Will the `namespace` label not clash with the namespace label attached by Prometheus when it collects it? Do we need to call it something like `resource-namespace`?

**Comment by ppatierno** [comment]
> Would something like strimzi_resource_state be better name?
I like it ... +1

> Will the namespace label not clash with the namespace label attached by Prometheus when it collects it? Do we need to call it something like resource-namespace?
I have just noticed that, right. Even if at some point the "namespace" label added by Prometheus could confuse (it's from where the metric comes so where the operator is living).

So the metric could be

`strimzi_resource_state{kind="Kafka", name="my-cluster", resource-namespace="my-kafka-namespace"}`
