### ISSUE TITLE
[Question] Create Kafka cluster complaining missing two cluster roles strimzi-entity-operator and strimzi-kafka-broker

### ISSUE THREAD

**Issue by sinbadonline** [strimzi/strimzi-kafka-operator#3643]
Using operator v0.18 create Kafka cluster may meet with a error saying missing two cluster role, strimzi-entity-operator and strimzi-kafka-broker. Two cluster role have corresponding yaml files in the install folder already. Is this a pre-requirement for Kafka user to install those two cluster role into K8S before using operator to create resource? Is there some special thought of not to create those two roles inside of operator logic? Thank you.

**Comment by scholzj** [comment]
It is expected that when you install the operator you install all the YAMLs from the `install/cluster-operator` folder. If not, you might face issue like this. Installing the cluster roles from YAML is easier than doing it in the operator and it lso means that we need one less RBAC right which is what some other users would probably complain about.

**Comment by sinbadonline** [comment]
Checking from cluster-operator's code, there are already some logic to create cluster role as below which seems conflict with your explaination, right? @scholzj 

```
 75 
 76         maybeCreateClusterRoles(vertx, config, client).onComplete(crs -> {                                                                                                                
 77             if (crs.succeeded())    {

```
```
165     /*test*/ static Future<Void> maybeCreateClusterRoles(Vertx vertx, ClusterOperatorConfig config, KubernetesClient client)  {                                                           
166         if (config.isCreateClusterRoles()) {
167             List<Future> futures = new ArrayList<>();
168             ClusterRoleOperator cro = new ClusterRoleOperator(vertx, client, config.getOperationTimeoutMs());
169 
170             Map<String, String> clusterRoles = new HashMap<String, String>() {
171                 {
172                     put("strimzi-cluster-operator-namespaced", "020-ClusterRole-strimzi-cluster-operator-role.yaml");
173                     put("strimzi-cluster-operator-global", "021-ClusterRole-strimzi-cluster-operator-role.yaml");
174                     put("strimzi-kafka-broker", "030-ClusterRole-strimzi-kafka-broker.yaml");
175                     put("strimzi-entity-operator", "031-ClusterRole-strimzi-entity-operator.yaml");
176                     put("strimzi-topic-operator", "032-ClusterRole-strimzi-topic-operator.yaml");
177                 }
178             };
```

**Comment by scholzj** [comment]
That was used in the past when installing Strimzi using OperatorHub.io which didn't supported any other way of creating Cluster Roles in the past. I don't think it in any way conflicts with what I said. I guess that if you want, you can use this as long as it is still there - but you would need to modify the base role to give the operator the rights to create cluster roles. And then set `STRIMZI_CREATE_CLUSTER_ROLES` env vard in the deployment to `TRUE`.

**Comment by sinbadonline** [comment]
Thanks, got it
