### ISSUE TITLE
[Enhancement] ClusterCaCert - Pass annotations to secrets

### ISSUE THREAD

**Issue by javiercri** [strimzi/strimzi-kafka-operator#3644]
It would be useful to define annotations on cluster ca certificate, which will be passed/copied to the secrets created by the operator.

**Comment by antimack** [comment]
+1 not sure about how it should be done but possibility to pass the annotations to the KafkaUser secrets would be awesome to have, on of the use cases can be of using operators to sync/copy secrets across namespaces

**Comment by scholzj** [comment]
@antimack Just FYI: There is already some work in progress on this by @javiercri in #3665

**Comment by scholzj** [comment]
This should be now possible through the Kafka template: https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaClusterTemplate-reference. I think this can be closed.
