### ISSUE TITLE
[Question] Multiple Kafka clusters with the same topic name and namespace

### ISSUE THREAD

**Issue by AnyISalIn** [strimzi/strimzi-kafka-operator#3655]
I have two Kafka clusters, Kafka-a, and Kafka-b. They are in a namespace, and the `auto.create.topics.enable` the option is turned on, and both use a topic (user) with the same name. When the user topic is automatically set by Kafka 
After creation, the topics operator will create a corresponding KafkaTopic resource in the k8s namespace to manage the corresponding topic, and then they will have the same name

Is there a way to add a prefix to the KafkaTopic created by the topicOperator in the k8s namespace, similar to

`kakfa-a-user`
`kakfa-b-user`

**Comment by scholzj** [comment]
I'm not sure what exactly would the Topic Operator do, but you for sure cannot configure the prefix. Best is to use different namespace for each cluster.

**Comment by AnyISalIn** [comment]
> I'm not sure what exactly would the Topic Operator do, but you for sure cannot configure the prefix. Best is to use different namespace for each cluster.

thank for your reply, It seems that the topic operators of the two clusters seem to conflict. We provide users with Kafka services. Each project is isolated based on namespace, so there will be a situation where a namespace corresponds to multiple Kafka clusters, or is there a way to turn off the automatic synchronization topic ?

**Comment by AnyISalIn** [comment]
Or is it possible to add a parameter so that the k8s-topic created by the topic operator contains the cluster name?

**Comment by scholzj** [comment]
From your description I'm not sure I understand why would each project require multiple Kafka clusters. I can see why it might be an inconvenience, but I do not think there is anything you can do about it right now.

You can also disable the topic operator by removing the `topicOperator: {}` section from the Kafka CR.

**Comment by AnyISalIn** [comment]
> From your description I'm not sure I understand why would each project require multiple Kafka clusters. I can see why it might be an inconvenience, but I do not think there is anything you can do about it right now.
> 
> You can also disable the topic operator by removing the `topicOperator: {}` section from the Kafka CR.
Just like openshift, we use the namespace of Kubernetes to distinguish projects. In most cases, there will not be multiple instances of Strimzi Kafka in a project.

**Comment by AnyISalIn** [comment]
Can you modify the logic of the `asKubeName` function to support cluster as the prefix. I found that the current logic in the case of multiple kafka clusters in a namespace, consumer-offsets will generate the same name `consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a`

**Comment by scholzj** [comment]
I do not know enough about the Topic Operator internals ... but there for sure would need to be also some other method to do the opposite - get the Kafka topic name from the resource name. You would also need to think about what to do when someone creates a topic which does not have your expected prefix. Should it be ignored? That would probably make things more complicated, but you need to make sure the translation in both ways is deterministic.

**Comment by AnyISalIn** [comment]
Sorry, I may not understand the current code implementation logic, but according to my understanding, the topic operator should be located at the same time through `spec.topicName` and `labels.strimzi.io/cluster`, while `metadata.name` is in 
Unique identifier in kubernetes

It seems that TopicOpeartor has two situations.

1. Declare Topic externally, create CustomResource through Kubectl and create corresponding Topic in Kafka through Topic Operator

2. Synchronize Topic in Kafka to Kubernetes cluster, asKubeName function handles the logic of conversion

What we are encountering now is the second situation. Theoretically speaking, the KafkaTopic in kubernetes can be located through topicName and cluster name. I understand that adding Prefix refers to the Kubernetes level, not the internal Kafka.

**Comment by scholzj** [comment]
I don't think relying on `spec.topicName` is enough. Because you would then have multiple resources managing the topic. Which will cause a mess. You need to be able to link these in both directions.

**Comment by scholzj** [comment]
BTW: `spec.topicName` is optional - so in many resources it will not be there.
