### ISSUE TITLE
[Bug] Invalid line numbers in Cluster Operator log output

### ISSUE THREAD

**Issue by mstruk** [strimzi/strimzi-kafka-operator#3658]
**Describe the bug**
Strimzi Cluster Operator log4j configuration is such that it prints logger name and line number together as LOGGER_NAME:LINE_NUM. This is incorrect in the case when logger name is not equals to class name where logger is used.

Consider the following logging line:
```
2020-09-16 13:44:19 DEBUG NetworkPolicyOperator:169 - NetworkPolicy my-cluster-network-policy-kafka in namespace myproject has been patched
``` 

Here the NetworkPolicyOperator class has no logic that logs anything, rather it inherits methods from AbstractResourceOperator. Looking for line number 169 in NetworkPolicyOperator won't yield any result. The line that called the logging statement is in this case in AbstractResourceOperator.

**To Reproduce**
1. Turn on DEBUG logging by using in `install/cluster-operator/060-Deploy-strimzi-cluster-operator.yaml`:
```
          env:
            ...
            - name: STRIMZI_LOG_LEVEL
              value: DEBUG
```
2. Deploy the cluster operator:
```
kubectl apply -f install/cluster-operator
```
3. Deploy some Kafka cluster, e.g.:
```
kubectl apply -f examples/kafka/kafka-ephemeral-single.yaml
```
4. Observe strimzi-kafka-operator log:
```
kubectl logs $(oc get pod | grep strimzi-cluster-operator | awk '{printf $1}') -f
```

**Expected behavior**
Either include the additional source field into debug output e.g.:
```
2020-09-16 13:44:19 DEBUG NetworkPolicyOperator (AbstractResourceOperator.java:169) - NetworkPolicy my-cluster-network-policy-kafka in namespace myproject has been patched
```

Or remove the line number altogether:
```
2020-09-16 13:44:19 DEBUG NetworkPolicyOperator - NetworkPolicy my-cluster-network-policy-kafka in namespace myproject has been patched
```

**Environment (please complete the following information):**
 - Strimzi version: master
 - Installation method: YAML files
 - Kubernetes cluster: minishift 3.11

**Comment by stanlyDoge** [comment]
I am not sure this is a bug. It is just `log4j2` configuration. If you with to have output like this
```
2020-09-17 08:22:11 DEBUG DeploymentOperator (AbstractResourceOperator:112) - Deployment myproject/my-cluster-kafka-jmx-trans does not exist, noop
```
use this pattern configuration 
```
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c{1} (%C{1}:%L) - %m%n
```

**Comment by scholzj** [comment]
@sknot-rh So, should we have some patter as you suggested as the default? The line numbers pointing to another class is indeed a bit weird and confusing sometimes.

**Comment by sknot-rh** [comment]
Yeah, I agree. However - with this pattern, we will have some duplicities if the logging is used in static methods or methods which are not overridden from the parent class. For example `2020-09-17 08:22:11 DEBUG AbstractResourceOperator (AbstractResourceOperator:120) -blah blah`

**Comment by tombentley** [comment]
Note that `%C` comes with this warning:

> Generating the class name of the caller ([location information](https://logging.apache.org/log4j/2.x/manual/layouts.html#LocationInformation)) is an expensive operation and may impact performance. Use with caution.

**Comment by scholzj** [comment]
Ok, so sounds like we want to fix it in the code rather than in the layout configuration. Thanks.
