### ISSUE TITLE
[Enhancement] Add reconcile resource resource state metric to the Topic Operator

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3661]
As already mentioned in #3642 which was fixed by #3652 for the Cluster and User operators, we should do the same for the Topic Operator and adding the following metric.

`strimzi_resource_state{kind="KafkaTopic", name="my-topic", resource-namespace="my-topic-namespace"}`

providing the information on the latest reconcile state of a `KafkaTopic` resource and if it was created and/or updated successfully at the end of reconciling or something failed (more info to check in the status of the custom resource). The possible values are just 1.0 and 0.0.

This issue should be fixed after #3659 because it seems that the current support for metrics in the Topic Operator is a little bit buggy.

**Comment by ShubhamRwt** [comment]
@ppatierno - Hello. Can I work on this issue since the metric problem in the topic operator is solved now , or are you planning to work on this ?

**Comment by ppatierno** [comment]
@ShubhamRwt go ahead! ;-)

**Comment by scholzj** [comment]
Triaged on 26.5.2022: Seems to be done in #4502.
