### ISSUE TITLE
[Enhancement] Add histogram latency buckets for reconciliations duration

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3663]
The operators expose a `strimzi_reconciliations_duration_XXXX` providing max, avg, and so on but having histogram with latency buckets would be better in order to avoid spurious timing providing a wrong average for example.
Think about more reconciles taking a few seconds but just one with a bigger value screweing up an average and the other way around. From histogram you can get percentiles that are really useful in these scenarios.

**Comment by ShubhamRwt** [comment]
@ppatierno Hello, Is this issue still open?

**Comment by ppatierno** [comment]
I would say yes, it could be useful imho.

**Comment by scholzj** [comment]
Done in #5349
