### ISSUE TITLE
[Bug] OpenSslCertManager.generateCert can delete CA certificate file

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#3681]
**Describe the bug**
`OpenSslCertManager.generateCert` tries to delete the CA serial file if it exists using this code:

```
        // We need to remove CA serial file
        Files.deleteIfExists(Paths.get(caCert.getPath().replace(".crt", ".srl")));
```

That doesn't work if the CA certificate file passed to the method isn't called `*.crt`. e.g. If it's called `ca.pem` then that code results in the CA certificate file being deleted.

**Comment by ShubhamRwt** [comment]
Hello @tombentley I was working on this issue. Can we make use of replaceAll() as we can use regex with it.  We can use this expression ``` replaceAll("[.].*", ".srl") ```  so that if the passed cert is in pem format then it will replace the pem file itself.

**Comment by tombentley** [comment]
@ShubhamRwt in a roundabout way, a fix for this has ended up in @alesj's PR here https://github.com/strimzi/strimzi-kafka-operator/pull/4116/files#diff-5676ef921102ade50d810e0352c98d9b2dd4da7cbecc825cdb87525437bac255L351. If @alesj is OK with it maybe take that fix, add a tests and open a PR based on that?

**Comment by alesj** [comment]
Yeah, fine by me.
I'll rebase if needed.
