### ISSUE TITLE
[Question] ...Disabling the readiness probe in kafka strimzi operator

### ISSUE THREAD

**Issue by chanduarava** [strimzi/strimzi-kafka-operator#3695]
HI Team,

There is a scenario where one broker went down for5 to 6 hours of a cluster, where Strimzi health check results in fail mode but here we want to disable readiness/liveness probe or increasing any property for time out to make Strimzi health check as pass.

Can you please suggest if there is a way with below scenarios to achieve above health check as pass if one broker went down

Can we disable readiness/liveness probe?
Can we put any delay of time for 5 hours?
In the script of Strimzi health check, can we increase period time/timeout to do health check?

Thanks,
Chandil

**Comment by scholzj** [comment]
You can configure the usual Kubernetes options for the healthcheck timeouts: https://strimzi.io/docs/operators/latest/full/using.html#assembly-healthchecks-deployment-configuration-kafka ... but I'm not sure they allow values like 5 hours. To be honest, I'm not really sure I understand the problem you had. Can you maybe describe it in more detail? Are you saying that the pod was starting for 6 hours? Or was the healthcheck killing it for 6 hours?

**Comment by chanduarava** [comment]
Giving more background on this,
Beacause of some update/patch at infra level, there is service disruption of few hours, the pod /container didn't come up for longer period of time. health check is failed for those pods and once they are running state, they were not able to join the cluster 

As per my understanding , if we increase failureThreshold to 100 and periodSeconds = 2 mins,it seems Strimzi waits for 200 mins (around 3 hours) and marks Strimzi healthcheck accordingly. So that health check will wait and update after require period of time.  Can we do this by increasing those numers(100 for failurethreshold and 2 for periodSeconds properties), will this cause any issues?

**Comment by scholzj** [comment]
So, what is wrong with the healthchecks failing and the pods looping if they don't work? 

In general, you should be able to set the healthcheck settings as you want and as Kubernetes allow you. But if you keep these settings also during regular operations they will of course cause the healthchecks to not fail when they should So that could cause issues.
