### ISSUE TITLE
Kafka external access using Nginx TCP

### ISSUE THREAD

**Issue by omerozery** [strimzi/strimzi-kafka-operator#3698]
Hi
Is it possible to add support for Kafka external access with Nginx standard TCP connection using its TCP configmap or otherwise with its GlobalConfiguration CRD. (depends on which distribution one uses, kubernetes/ingress-nginx or nginxinc/kubernetes-ingress) instead or in addition to the TLS passthrough.

Thanks.

**Comment by scholzj** [comment]
Our Ingress support AFAIK works only with TLS Passthrough. We test it with kubernetes/ingress-nginx and when I implemented it I think the TCP support was a bit weird or semi-functional. Maybe that changed since and we can revisit it.

**Comment by omerozery** [comment]
Great, Thanks!

**Comment by scholzj** [comment]
Triaged on 31.3.2022: Kubernetes is moving from Ingress to the Gateway API which should hopefully provide more standardization for things such as TCP connections. We should more focus on that rather on adding TCP support for current Ingress controllers.
