### ISSUE TITLE
[Unable to retrieve Kafka metrics into Prometheus by using Servicemonitor and Kafka Exporter] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3709]
Hi Team,

We are working on a use case of extracting the Kafka & Zookeeper related metrics into Prometheus endpoint with all the following configurations. Attached a single text file that has all these CR's.

1) Kafka.yaml
2) Servicemonitor.yaml
3) Prometheus-rules.yaml
4) Prometheus.yaml

After deploying all these into a single namespace, on the prometheus UI service discovery has happened with namespace and service monitor, however it shows 0/0 up, we noticed that somehow the target is not considered due to which no metrics data is shown. attaching the image.

Need help in this if possible and also let us know if there is any issue in any of the CR's which can be the root cause.

![Kafka-Prometheus](https://user-images.githubusercontent.com/63441996/94276545-07c01f80-ff66-11ea-8a9c-2127c0c5f38c.png)

[all_crs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5283272/all_crs.txt)

**Comment by scholzj** [comment]
@stanlyDoge @ppatierno Any chance you can have a look at this?

**Comment by vperi1730** [comment]
@stanlyDoge @ppatierno @scholzj  - Need your help here.

**Comment by vperi1730** [comment]
JFYI, We are using string version 0.17.0 and we are using corresponding yaml files for prometheus from your github.

**Comment by stanlyDoge** [comment]
Looking at this

**Comment by vperi1730** [comment]
Sure, Thank you. Will look forward to hearing back ASAP.

**Comment by ppatierno** [comment]
Can you provide the Prometheus configuration from the UI and the service discovery as well (still from the Prometheus UI)?

**Comment by vperi1730** [comment]
Sure, give me like 5mins. I will share the data.

**Comment by vperi1730** [comment]
Attaching both the files. 
[prometheus_config.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5297135/prometheus_config.txt)
![service_discovery](https://user-images.githubusercontent.com/63441996/94525627-f91d8500-0251-11eb-8cde-378e5278a4df.PNG)

**Comment by stanlyDoge** [comment]
Can you provide output of `kubectl get svc my-cluster-kafka-bootstrap -o yaml`, please?

**Comment by vperi1730** [comment]
Here it is...

 kubectl get svc prom-kafka-kafka-bootstrap  -n brcm-prometheus1 -o yaml

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9404"
    prometheus.io/scrape: "true"
    strimzi.io/discovery: |-
      [ {
        "port" : 9092,
        "tls" : false,
        "protocol" : "kafka",
        "auth" : "none"
      }, {
        "port" : 9093,
        "tls" : true,
        "protocol" : "kafka",
        "auth" : "tls"
      } ]
  creationTimestamp: "2020-09-23T13:15:22Z"
  labels:
    app.kubernetes.io/instance: prom-kafka
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: strimzi
    strimzi.io/cluster: prom-kafka
    strimzi.io/discovery: "true"
    strimzi.io/kind: Kafka
    strimzi.io/name: prom-kafka-kafka-bootstrap
  name: prom-kafka-kafka-bootstrap
  namespace: brcm-prometheus1
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: prom-kafka
    uid: a2551de6-0815-480a-a6fc-30b787f05f5c
  resourceVersion: "487243115"
  selfLink: /api/v1/namespaces/brcm-prometheus1/services/prom-kafka-kafka-bootstrap
  uid: b30cf5ae-04c1-4ecf-85ce-03f73356fa66
spec:
  clusterIP: 172.30.96.82
  ports:
  - name: tcp-replication
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: tcp-clients
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: tcp-clientstls
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: prometheus
    port: 9404
    protocol: TCP
    targetPort: 9404
  selector:
    strimzi.io/cluster: prom-kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: prom-kafka-kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

```

**Comment by stanlyDoge** [comment]
Mm, that LGTM. Can you provide `kubectl get clusterrolebinding prometheus-server -o yaml`, please?

**Comment by vperi1730** [comment]
# kubectl get clusterrolebinding  prometheus-server -o yaml

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: brcm-prometheus1

```

```
# kubectl get rolebinding prometheus-server  -n brcm-prometheus1 -o yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-server
  namespace: brcm-prometheus1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: brcm-prometheus1
```

Few points to consider.

1) As our requirement is to monitor the metrics at a namespace level, we have confiured the rolebinding instead of clusterrolebinding.

2) Both kafka and prometheus are in the same namespace(brcm-prometheus1).

**Comment by stanlyDoge** [comment]
I completely missed you are having an issue with Kafka exporter :facepalm: 
I've deployed a cluster from the examples folder and it works for me. The issue with Kafka exporter is, it starts working after some traffic in the cluster. Try to produce & consume ~100 messages and try to fetch the metrics again. Attaching a screen after some traffic in my cluster 
![Snímek z 2020-09-29 12-49-22](https://user-images.githubusercontent.com/19408098/94549349-5c0f1c00-0252-11eb-9778-8736e854569a.png)

**Comment by vperi1730** [comment]
OK, Could you please let us know if you see any issue in any of our custom resources attached above? 

We are trying to produce a good amount of messages to see if we can achieve our use case. Meanwhile, if you can check and let me know that would be great.

**Comment by stanlyDoge** [comment]
I did not found anything suspisious so far :disappointed:

**Comment by vperi1730** [comment]
Ok, if that is the case one question i have is, why under the service discovery the service monitor is displaying as 0/57 active. Ideally it has to show us the list or some relevant information coming from kafka nodes. Isn't it?

**Comment by stanlyDoge** [comment]
IIRC Servicemonitors are configured for [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) and [node-exporter](https://github.com/prometheus/node_exporter). So if you do not have deployed these, you won't get any data from SM. The `node` is from the k8s view. Kafka node is actually a `Pod`.

**Comment by vperi1730** [comment]
Thanks for the clarification. Few more questions to be answered...

1) If i don't need the node level and k8 cluster-level metrics, can we remove these from the SM?
2) If we want to have the metrics only for a specific namespace where the Kafka cluster is deployed. What configuration do we require inside the additional config scrape file (prometheus-additional.yaml is the filename for reference).

I would appreciate if you can revert back to us ASAP.

**Comment by stanlyDoge** [comment]
1. yes
2. If you set the rolebinding only for some of namespaces, the Prometheus server should not have a permission (RBAC) to read the metrics. If you want to set the ns also in the job configuration, I would try something like 
```
- job_name: kubernetes-pods
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names: 
      - brcm-prometheus1
```

**Comment by vperi1730** [comment]
Great, thanks for the answer. Another ask is...

1) As Prometheus will scrape the metrics from Kafka-exporter, so the pod access should be limited to the kafka exporter pod only instead of having access to all Kafka pods...

Is it true? - If YES can we limit to exporter pod in this case...

**Comment by stanlyDoge** [comment]
It is true in the case you really want only the metrics that Kafka Exporter is providing.
Because Kafka Exporter is managed by a `Deployment`, its pod has a dynamic name. I think it is rather impossible to limit RBAC just to pods with variable name (https://github.com/kubernetes/kubernetes/issues/56582).

**Comment by vperi1730** [comment]
Thanks for the answer and I agree that this is impossible to limit RBA just to a pod created by deployment. My requirement is if I need only the Kafka metrics from a particular namespace, how do we achieve this? (Let's say I have Prometheus in namespace A and Kafka running in B and C, Now I would like to fetch the Kafka metrics from namespace B but not from C, this is the use case we would like to achieve, how do we limit this).

The same has been asked above in Question no:3.  Need your thoughts here?

**Comment by stanlyDoge** [comment]
I would use the part of the configuration above (https://github.com/strimzi/strimzi-kafka-operator/issues/3709#issuecomment-700762814). @ppatierno do you have any thoughts?

**Comment by scholzj** [comment]
Is there still something we should do here? Or can we close this? @vperi1730 @sknot-rh @ppatierno

**Comment by ppatierno** [comment]
service monitor doesn't exist anymore, I would close it.

**Comment by sknot-rh** [comment]
Yeah, we use `PodMonitor`s currently (https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/metrics/prometheus-install/strimzi-pod-monitor.yaml).
