### ISSUE TITLE
ACL view of user command line

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-kafka-operator#3715]
Is there any way to view ACL view of any user in kafka using command line ?

**Comment by scholzj** [comment]
I think that will depend a lot on your configuration and versions of Strimzi and Kafka which you use. But I guess something like this could do it:

```
kubectl -n kafka run kafka-acls -ti --image=strimzi/kafka:0.19.0-kafka-2.5.0 --rm=true --restart=Never -- bin/kafka-acls.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --list
```

You might need to add some authentication or encryption depending on your actual settings.

---

Is you use the User operator and the KafkaUser resources, you can also get the information just from the Kubernetes API - `kubectl get kafkauser` and for example use JsonPath to extract some specific information.

**Comment by cloudcafetech** [comment]
kubectl get ku gives list of user but not acl view ?

yes, may be if I use -o yaml then may be will get acl details.

but looking as enhancement in cmd. 👍 

BTW, in ACL how can I use all operation ("Read", "Write", "Create", "Delete", "Alter", "Describe", "ClusterAction", "DescribeConfigs", "AlterConfigs") in single line.

can I use operation: "*" ?

**Comment by scholzj** [comment]
> kubectl get ku gives list of user but not acl view ?

`-o yaml` is one option. But you should look at this: https://kubernetes.io/docs/reference/kubectl/jsonpath/ ... the JSONPath will let you query the resource and extract just some parts of it. I do not have any example for users. But this is for example for extracting the bootstrap address for listener from the Kafka resource. So you could use something similar:

```
kubectl get kafka my-cluster -o=jsonpath='{.status.listeners[?(@.type=="external")].bootstrapServers}{"\n"}'
```

> BTW, in ACL how can I use all operation ("Read", "Write", "Create", "Delete", "Alter", "Describe", "ClusterAction", "DescribeConfigs", "AlterConfigs") in single line.
> can I use operation: "*" ?

I think you can use an operation `All` to assign all operations.

**Comment by cloudcafetech** [comment]
Tnx ,

I following https://github.com/strimzi/strimzi-kafka-operator/issues/2141#issuecomment-547778569

where u mentioned     
```
authorization:
      type: tls
```

but when I run under kafkauser with above parameter, its says supported value "simple"

little confusing ...

**Comment by cloudcafetech** [comment]
basically I want user (**super-user**) who can do every thing in my cluster and I want to use external (cert,truststore,keystore generation will take cake.)

Looking user manifest file with ACL for that user (**super-user**)

**Comment by scholzj** [comment]
That is just a typo ... there is no `type: tls` authorization. That is just authentication type. That comment is valid, but should be

```
authorization:
      type: simple
```

**Comment by cloudcafetech** [comment]
tnx

**Comment by Utkarsh-0211** [comment]
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - host: '*'
      operation: All
      resource:
        name: my-topic
        patternType: literal
        type: topic
      type: allow

I'm using this config for kafka-user.yaml.But while producing message it is giving me an error of "org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [my-topic]
"

**Comment by scholzj** [comment]
@Utkarsh-0211 How is it related to the issue here? Maybe you should open a new one and make sure the code is formatted properly.
