### ISSUE TITLE
Sink connectors stops consuming messages but still in Running state

### ISSUE THREAD

**Issue by eazhilan-nagarajan** [strimzi/strimzi-kafka-operator#3717]
Hi,

I'm not sure if this the right place to ask this question but I have got my questions answered here in the past. 

Let me explain the situation, we have built a custom JDBC sink connector which calls a Stored Procedure. It has all been working fine with few other pipelines but recently we started using it with a new pipeline which gets ~80 msgs/sec and a SMT which converts from JSON to XML (custom SMT with a little more happening) at the sink connector side. Most of the cases it works fine but intermittently the sink connector **STOPs**  pulling messages from the topic with the below error found in the logs.

`2020-09-26 04:57:31,265 INFO [Consumer clientId=connector-consumer-mySpSinkConnectorV0-0, groupId=connect-mySpSinkConnectorV0] Member connector-consumer-mySpSinkConnectorV0-0-c274ce98-7183-46ab-8b61-b615843692d7 sending LeaveGroup request to coordinator octo-cluster-1-kafka-0.octo-cluster-1-kafka-brokers.qa-octo.svc:9093 (id: 2147483647 rack: null) due to consumer poll timeout has expired. This means the time between subsequent calls to poll() was longer than the configured max.poll.interval.ms, which typically implies that the poll loop is spending too much time processing messages. You can address this either by increasing max.poll.interval.ms or by reducing the maximum size of batches returned in poll() with max.poll.records. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator) [kafka-coordinator-heartbeat-thread | connect-mySpSinkConnectorV0]`

We have played around with `max.poll.interval.ms` and `max.poll.records` properties and it has definitely improved a lot but didn't fix entirely.
The interesting thing is, though the connector stops consuming messages after the above error it still continues to be in **RUNNING** state (I mean both the connector and its tasks). Is this how connectors work or could you suggest a way to make the connector move to **FAILED** state so that we can be notified about the failure or in general a possible permanent fix?

Please also feel free to direct me to a different right place if here is not.

Thanks,
Eazhilan

**Comment by scholzj** [comment]
TBH, I think this is more question on someone who understand Kafka Connect or the particular connector you are using. One thing worth checking is if for example giving it more resources (cpu / memory) could help as the problem sounds a bit like it might be constraint.

**Comment by eazhilan-nagarajan** [comment]
Hmm that could be another way to look at this issue. Let me tweak the resources and give it a try.

Thanks for taking a look and suggestions.
