### ISSUE TITLE
Kafka Integration with Vault for secret/TLS management

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3719]
Hi ,

Could you please advice if there are any steps to enable Kafka secret management using Vault?

we want to have a centralized management for TLS/SSH certificate.

**Comment by scholzj** [comment]
I do not think there is anything beyond this older blog post: https://strimzi.io/blog/2018/11/16/using-vault-with-strimzi/ ... Vault integration is something what we are thinking about, but I would not expect it anytime soon.

**Comment by pashafirdous** [comment]
the blog is referencing ClusterCA process. what do you suggest for client CA?

**Comment by pashafirdous** [comment]
when i followed the blog, and configured PKI, i get the below error 
```
Compression not enabled
PRNG seeded successfully
Initializing service [my-cluster-zookeeper-1-2888]
Insecure file permissions on /etc/tls-sidecar/zookeeper-nodes/my-cluster-zookeeper-0.key
Certificate: /etc/tls-sidecar/zookeeper-nodes/my-cluster-zookeeper-0.crt
Error reading certificate file: /etc/tls-sidecar/zookeeper-nodes/my-cluster-zookeeper-0.crt
error queue: 140DC009: error:140DC009:SSL routines:SSL_CTX_use_certificate_chain_file:PEM lib
SSL_CTX_use_certificate_chain_file: 906D06C: error:0906D06C:PEM routines:PEM_read_bio:no start line
Service [my-cluster-zookeeper-1-2888]: Failed to initialize SSL context
str_stats: 54 block(s), 7205 data byte(s), 3132 control byte(s)
```

I do not have a public domain/certificate, but i want to test vault PKI for kafka using a certificate generated by Vault.

Advice please?

**Comment by scholzj** [comment]
The blog post is 2 years old. So maybe things changed since. I think the error suggests there is something wrong with the `my-cluster-zookeeper-0.crt` file. Wrong format or something like that.

**Comment by vperi1730** [comment]
@scholzj - You might be able to throw some light here. 

As the blog explains the process for the Cluster CA, inside the same we have a URL pointing to vault for generating our own CA which i was able to follow. 

https://learn.hashicorp.com/tutorials/vault/pki-engine#step-3-create-a-role.

However 1 area where i am blocked is, in the Cluster CA process with the following vault write we are able to generate the private key( intermediate.key.pem)  and CSR, this private key is accommodated inside the cluster-ca secret we generate.

```
vault write -format=json pki_int/intermediate/generate/exported \
        common_name="example.com Intermediate Authority" ttl="43800h" format="pem" > pki_intermediate

# Extract the private key & certificate signing request from the previous command's output:
$ jq -r '.data.private_key' < pki_intermediate > intermediate.key.pem
$ jq -r '.data.csr' < pki_intermediate > pki_intermediate.csr
``` 

On the other side when it comes to clients-ca, really not sure from where the private key/user key would come from. I am not if i have explained it properly.

**Comment by scholzj** [comment]
As I said before, I do not know much about the blog post. But I do not think there is any difference between the Clients CA and Cluster CA in how you create it. The are both just CAs. 

How do you want to generate the user certs? Your self in Vault? Or using Strimzi User Operator? If you want to use the User Operator, the private key for the clients CA will need to be in the clients-ca secret. If you don't want to use the User Operator, you can just stuff it with some dummy value and you only need to add the actual public key to the `clients-ca-cert`. That is the only difference.

With Cluster-CA, you always need to give Strimzi both public and private keys.

**Comment by vperi1730** [comment]
Presently it will be strimzi user operator.  I agree that the private key has to be in the clients-ca, can that be generated with openssl or is there any manual approach?

**Comment by scholzj** [comment]
If Vault doesn't generate it, then yes, for example OpenSSL or cfssl or any other SSL tool would be the options.

**Comment by aryklein** [comment]
Any news on Vault integration? I would like to use Vault to store user's password

**Comment by dweber019** [comment]
The feature at https://github.com/external-secrets/external-secrets/issues/976 could help with any secret created by Strimzi.
