### ISSUE TITLE
[Enabling authentication between Prometheus Service monitor and Kafka exporter] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3726]
Hi Team,

I am working on a use case of enabling the authentication between Prometheus Service Monitor and Kafka exporter. Just wanted to check do we have any sample example which has been tried and tested earlier.

It would be good if you can refer me to any GitHub repo which has a similar implementation .

**Comment by scholzj** [comment]
I do not think that is supported.

**Comment by ppatierno** [comment]
I guess that a quick look at the Kafka Exporter repo https://github.com/danielqsj/kafka_exporter is enough to see that there is no way to secure the HTTP endpoint used by Kafka Exporter for exporting metrics. It only has TLS configuration for connecting to the Kafka cluster from where getting metrics.

**Comment by vperi1730** [comment]
What I understand is Kafka exporter cannot have a username/password-based authentication which can be used in the Prometheus service monitor to connect with the Kafka exporter. Is this the point you are trying to make out?

**Comment by scholzj** [comment]
Yes, correct. There is no support for that.

**Comment by vperi1730** [comment]
Ok, thanks for the confirmation.Will close this thread for now.
