### ISSUE TITLE
Kafka Bridge (secured)

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-kafka-operator#3731]
Regarding Kafka Bridge as per document (https://strimzi.io/docs/operators/latest/using.html#con-securing-kafka-bridge-kafka-bridge-overview) it support only HTTP. This means that requests sent from external clients to the Kafka Bridge are:

- Not encrypted, and must use HTTP rather than HTTPS
- Sent without authentication

any blog or documentation to secure the Kafka Bridge using any ?

**Comment by ppatierno** [comment]
We decided to not having HTTPS and authentication out of the box but allowing people to use their own gateway in front of it, i.e. Nginx.
There is no blog post or documentation about that. I played a little bit with Nginx in the past and have something in this repo (https://github.com/ppatierno/nginx-strimzi-kafka-bridge). Maybe you can find something useful there.

**Comment by cloudcafetech** [comment]
I saw that repo in another issue, will try.

Thinking how we can automate (dynamically add)API token with user.
