### ISSUE TITLE
[Bug] The release zip file contains topic-operator and user-operator

### ISSUE THREAD

**Issue by haf** [strimzi/strimzi-kafka-operator#3745]
**Describe the bug**
It contains these folders, besides those being part of the entity operator deployment as separate container.

These folders should be removed from the release, if they are duplicated (which they are)

**To Reproduce**
1. Follow the guide and download the zip
2. Look inside the zip file, get confused. Try to deploy the operators stand-alone, fail due to TLS errors, get lots of errors in the ZooKeeper logs.

**Expected behavior**
A clear and concise description of what the installation process expects the operator to do.

**Comment by scholzj** [comment]
I think the ZIP is exactly as it should be. In my view, the documentation explaians quite well the relation of the different operators for example here: https://strimzi.io/docs/operators/latest/full/deploying.html#overview-components_str ... but it is sometimes hard for us from inside to judge how understandable the documentation is. So if you can points us exactly what confused you and what we should change or ideally open a PR which would make it clear for you it would be great and we can get this fixed.

**Comment by haf** [comment]
It's not the overview, since they are logical, not physical, so there's nothing wrong with them.

I just wanted yaml files for kubernetes; the guide says to download from github (here https://strimzi.io/docs/operators/latest/full/deploying.html#deploy-prereqs-str) and then states:

> You deploy Strimzi to a Kubernetes cluster using the kubectl command-line tool.

This is not enough; by default I believe I should install what I just downloaded.

**Comment by scholzj** [comment]
> This is not enough; by default I believe I should install what I just downloaded.

So what would you expect in the chapter 3.2 (https://strimzi.io/docs/operators/latest/full/deploying.html#downloads-str) instead of the _You deploy Strimzi to a Kubernetes cluster using the kubectl command-line tool._ to make it more clear for you?

> This is not enough; by default I believe I should install what I just downloaded.

How would kustomize handle this when you need to create cluster role bindings etc.?

**Comment by haf** [comment]
> Use `kubectl` to deploy Strimzi from the `cluster-operator` folder from downloaded zip file. `strimzi-admin`, `topic-operator` and `user-operator` are included in case you want stand-alone installations of these components.

**Comment by scholzj** [comment]
Thanks
