### ISSUE TITLE
Generic constaint schema annotation

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#3748]
We already have support in the `CrdGenerator` for a number of annotations (e.g. `@Minimum`) which allow us to constrain CR values via the schema generated for the CRD. There are places where this support is not powerful enough for the sorts of constraints which we need, and which are possible using the [wright 00 schema](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.7).

A couple of examples:

* It might be nice (one day, because it's not a backward compatible change) to constrain the zookeeper replicas to an odd number. 
* For the [listener ports](https://github.com/strimzi/strimzi-kafka-operator/pull/3738) we didn't do a perfect job of constraining the ports to not be in a reserved set of (non-contiguous) numbers.

We could solve these problems if we supported things like `not` and `oneOf` for combining these simple constraints. But Java annotations don't really work well with these kinds of composition patterns (in particular an annotation type declaration cannot have a recursive definition).

We could use an annotation which simply took the constraints which applied in a given version range as JSON. For example:

```java
// constrain some property to be an odd number
@Constraint(apiVersions="v1+", value="{'not': {'multipleOf': 2}}")

// constraint some property to a number from a set of non-contiguous ints
@Constraint(versions="v1+", value="'not': {'oneOf': [{'minimum': 9000, 'maximum': 9092}, {'minimum': 1111, 'maximum': 1111}]}")
```

This isn't completely ideal, because the `CrdGenerator` would just pass through well-formed JSON, which might not be valid for a CRD schema, or might not actually apply the validation expected. So using it would always require specific testing that the API server was able to enforce the given constraints.

**Comment by scholzj** [comment]
Triaged on 31.3.2022: @tombentley is this still something what makes sense? I know that we now have support for annotations to support some fields only in some API versions etc. So it is not clear whether it is already done or not and if not whether it is still needed.

Also, the Fabric8 now seems to have their own CRD generator. So I wonder if we should inevst into our own.

**Comment by tombentley** [comment]
Yeah, let's close this. I don't think this issue really describes something we're interested in at this point.
