### ISSUE TITLE
[Question] Configure dnsPolicy and HostNetwork for Kafka Brokers

### ISSUE THREAD

**Issue by venkatvghub** [strimzi/strimzi-kafka-operator#3753]
Hi,
My current setup exposes kafka over AWS's NLB. In essence, the NLB points to my external bootstrap service. However, the challenge i have is to enable `dnsPolicy: ClusterFirstWithHostNet` and `hostNetwork: true`. I do not see any reference in the CRD for enabling this. I was an early adoptor of strimzi and use 0.11.0 version(cannot upgrade due to client dependency on kafka versions).

With the above in mind, how do i go about handling this? In essence, how do i run the kafka broker statefulset with HostNetwork enabled?

The reason for the above ask is that client's are unable to connect to the brokers(in certain cases, unable to discover the brokers). Kubernetes networking complexities are other issues, but hostnetwork with clusterfirstwithhostnet are standard ways to solve these challenges for other similar systems. 

I do not see even in the newer versions of strimzi with this support. Kindly advice

**Comment by scholzj** [comment]
We do not support configuring `dnsPolicy` or `hostNetwork` and I'm afraid that even if we would add support for it, 0.11 is way too old for it. It is not completely clear to me why these would be needed. I wrote a blog post about using Kafka with NLBs and didn't needed anything like that (https://strimzi.io/blog/2020/01/02/using-strimzi-with-amazon-nlb-loadbalancers/).

**Comment by venkatvghub** [comment]
@scholzj thanks. Will explore and revert. Unfortunately, like i said, our adoption the current setup is quite large and we are slowly migrating. Our stack is on go(with sarama), which explicitly requires the protocol version for kafka. Also, are there cleaner ways to migrate to newer versions of kafka without breaking the data format? I know, this is beyond strimzi and a general kafka question. 

Solutions like mirror maker etc, change the topic names and isn't great. Other option is to do a two way write into both the clusters(new and old). This again, requires code changes to support multiple kafka versions. Downstream dependencies in terms of job processing etc, makes it complicated.

**Comment by scholzj** [comment]
Well, in theory new Kafka versions can still speak old protocols. You need to keep the old versions as the `log.message.format`. But I do not have any practical experience. Mirror Maker can be used for migration without changing the topic names. But if you need active-active clusters then you would for sure need different topic names.
