### ISSUE TITLE
Kafka topic data restore

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-kafka-operator#3755]
Just did follow the https://strimzi.io/docs/operators/latest/full/using.html#cluster-recovery_str for recovering kafka topic data.

Not able to view topic data ..

is there anyway I can view topic data inside Broker,Zookeeper or in PV ?

**Comment by scholzj** [comment]
You can see the data inside the pod on `/var/lib/kafka`. If you don't see them there, you should double check:
1) if the right volumes were mounted into the pods
2) If you followed the procedure around recovering the KafkaTopics properly

**Comment by cloudcafetech** [comment]
tnx
