### ISSUE TITLE
[Enhancement] Provide metrics to monitor certificates expiration

### ISSUE THREAD

**Issue by OuesFa** [strimzi/strimzi-kafka-operator#3761]
**Is your feature request related to a problem? Please describe.**
Lack of visibility regarding the validity period of certificates created by the cluster & user operators.

**Describe the solution you'd like**
Expose metrics to monitor the expiration of the certificates through visualisations and alerts.

**Comment by scholzj** [comment]
Triaged on 12.4.2022: This makes sense for the CAs:
* Metric can be provided as _days until expiration_
* Should be included in the Grafana dashboards and sample alerts

User certificates are not that easy because the User Operator doesn't know whether the certificate is actually used by the client or not. This would be better solved at the client side.

**Comment by OuesFa** [comment]
Thanks for the update.
How "difficult" you think this contribution would be, and how long it would take, compared to a contribution like this one for example https://github.com/strimzi/strimzi-kafka-operator/pull/5413
I can work on this if you think it is reasonable that someone who is not that familiar with the operator's code can do.

**Comment by steffen-karlsson** [comment]
@scholzj @maciej-tatarski and I would like to work on this, we have a solution in our company, not directly using Strimzi but build around and have some suggestions for dashboards as well.

**Comment by steffen-karlsson** [comment]
@maciej-tatarski will elaborate on the epoch :)

Regarding our existent solution, we don't plan to use that as part of this implementation, rather decom it when this is done.
What we have done, is to implement dashboards and alerts on certs based on a K8s CronJob to monitor our external secret store and emit metrics that way.

**Comment by maciej-tatarski** [comment]
I think epoch is better because in grafana you can easily visualize it as a date or days to expiry, because it fits default grafana time format.. Additionally it gives you more precise data, as it is in seconds.

**Comment by scholzj** [comment]
> I think epoch is better because in grafana you can easily visualize it as a date or days to expiry, because it fits default grafana time format.. Additionally it gives you more precise data, as it is in seconds.

Ok, I guess that makes sense. We would still need to figure out what would be the best way to expose these metrics. One of the main issues is how to cleanly remove them when the cluster is deleted.

**Comment by steffen-karlsson** [comment]
I see, there are no callbacks or anything on deletion in the `cluster-operator` currently that we can hook into?

**Comment by scholzj** [comment]
To be honest, I do not remember the details exactly. But in general, the deletion is done by Kubernetes and its garbage collection. It is not always simple to _remove_ the metrics for the deleted resources. But if you don't do it, they usually stay set until the operator restarts.

**Comment by steffen-karlsson** [comment]
Makes sense, @maciej-tatarski and I would gladly give it a go and see if we can come up with anything meaningful :)

**Comment by scholzj** [comment]
Ok, great. That sounds like a plan then.
