### ISSUE TITLE
Make it possible to set nodeSelectors on deployments created by the operator

### ISSUE THREAD

**Issue by andreas-ahman** [strimzi/strimzi-kafka-operator#3763]
It is possible to set the nodeSelectors on the operator itself but not on the deployments created by it.
This causes the deployments to be scheduled on the incorrect nodes.

It would be great to have a nodeSelectorsOverride where the nodeSelectors for the deployments can be specified.

**Comment by scholzj** [comment]
We support configuring your own affinity (including node-affinity): https://strimzi.io/docs/operators/latest/full/using.html#assembly-scheduling-deployment-configuration-kafka 

As far as I know, that give you superior options over node selectors and we currently do not plan to add any support for node selectors.

**Comment by andreas-ahman** [comment]
Thanks for the information!
