### ISSUE TITLE
[Doc] Forbidden configuration prefixes missing from Cruise Control configuration documentation

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#3769]
**Suggestion / Problem**

The forbidden prefixes in the Cruise Control configuration documentation [1] do not match the actual forbidden prefixes in the `CruiseControlSpec` [2]. For example the ```webserver.http``` forbidden prefix is missing from the forbidden prefix list [1]. Maybe this list should be removed and point to the generated CruiseControlSpec docs [2] for easier maintainence.

**Documentation Link**
[1] https://strimzi.io/docs/operators/latest/full/using.html#ref-cruise-control-configuration-str
[2] https://strimzi.io/docs/operators/latest/using.html#type-CruiseControlSpec-reference

**Comment by rushminatorr** [comment]
I can help with this one. :)

**Comment by scholzj** [comment]
@rushminatorr Help is always welcomed ... I think the wrong file is this one: https://github.com/strimzi/strimzi-kafka-operator/blob/master/documentation/modules/cruise-control/ref-cruise-control-configuration.adoc ... and the correct list of the forbidden prefixes is here: https://github.com/strimzi/strimzi-kafka-operator/blob/218fa73cd49f5804be7c1148b843c40e9fe07435/api/src/main/java/io/strimzi/api/kafka/model/CruiseControlSpec.java#L37 ... @kyguy should be able to help witht he content if needed.

**Comment by kyguy** [comment]
Resolved by https://github.com/strimzi/strimzi-kafka-operator/pull/3833
