### ISSUE TITLE
[Enhancement] Lock down Cruise Control API

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#3770]
**Is your feature request related to a problem? Please describe.**

The full Cruise Control API can be accessed directly by users by sending HTTP requests to the application on the Cruise Control pod. This allows users to preform potentially destructive operations on Kafka clusters without being properly vetted by the Cluster Operator. All non-read interactions with Cruise Control should happen through the supported `KafkaRebalance` custom resource and should not be allowed by any other method.

**Describe the solution you'd like**

Prevent users from accessing the Cruise Control API directly.

**Comment by OuesFa** [comment]
Hello @kyguy 👋 
I am using cruise-control-ui on top of the cruise-control-api created by Strimzi operator. (juste to have the status of the cluster)
Could the improvement you suggest break the UI deployment?

**Comment by kyguy** [comment]
After some investigation it looks like we can best accomplish this by using Cruise Control's built-in support for HTTP basic authentication and HTTPS [1]. With the basic authentication we can create two users, one with an `ADMIN` role reserved for the Cluster Operator and one with a `VIEWER` role reserved for developers. The username and password for the user with the `ADMIN` role can be secured with HTTPS requests. The username and password for the user with the `VIEWER` role can be shared in the documentation so that developers may access the read-only endpoints of the Cruise Control API.

With these changes we could also provide a cruise-control-entrance hack much like Jakub Scholz's zoo-entrance hack [2] which would create a Kubernetes service which reuses Strimzi certificates for making unencrypted requests to the Cruise Control API. This hack would allow third-party applications like the cruise-control-ui [3] read access to the Cruise Control API.

[1] https://github.com/linkedin/cruise-control/wiki/Security
[2] https://github.com/scholzj/zoo-entrance
[3] https://github.com/linkedin/cruise-control-ui
