### ISSUE TITLE
TLS & SCRAM both

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-kafka-operator#3777]
**Can I use TLS & SCRAM both authentication for single (external/tls) listener as well as user?** 

Because when we generating properties file for external connection only we will change the parameter. Just as below example.

-  SSL

```
security.protocol: SSL
ssl.truststore.password: $PASSWORD
ssl.truststore.location: /data/truststore.jks
ssl.keystore.location: /data/keystore.jks
ssl.keystore.password: $PASSWORD
ssl.key.password: $USERPASSWORD
```
- SCRAM

```
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
ssl.truststore.password: $PASSWORD
ssl.truststore.location: /data/truststore.jks
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="$KAFKAUSER" password="$USERPASSWORD";
```

**Comment by scholzj** [comment]
You can choose only one of them, they cannot be combined. But you can have different authentication on different listeners. So you can for example have one listener use SCRAM and other one use TLS authentication (especially after the 0.20.0 with the improved listener options you can have many different listeners).

**Comment by cloudcafetech** [comment]
One listener use SCRAM and other one use TLS authentication that I already tested in 0.19.

Last part 0.20.0 new version not clear. New listeners ?

**Comment by scholzj** [comment]
In 0.19.0 you can have only 3 listeenrs: One internal without TLS, One internal with TLS and one external. With 0.20.0 you will be able to have more of them. For example two internal with TLS and different authentication and two external etc.

**Comment by cloudcafetech** [comment]
Thanks 👍
