### ISSUE TITLE
Invalid value: "array": spec.kafka.listeners in body must be of type object: "array"[Bug] ...

### ISSUE THREAD

**Issue by a5a5a9** [strimzi/strimzi-kafka-operator#3781]
After applying 

kubectl apply -f kafka-ephemeral.yaml -n test
The Kafka "my-cluster" is invalid: spec.kafka.listeners: Invalid value: "array": spec.kafka.listeners in body must be of type object: "array"

**Comment by a5a5a9** [comment]
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

**Comment by scholzj** [comment]
If you are using some particular release use the example either from the GitHub tag or from the release downloads. Not from master where the examples are under development. E.g. for 0.19, use https://github.com/strimzi/strimzi-kafka-operator/tree/0.19.0 or https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.19.0
