### ISSUE TITLE
Need information on the framework used for kafka cluster operator.

### ISSUE THREAD

**Issue by kaushiksrinivas** [strimzi/strimzi-kafka-operator#3790]
Hi,
Would like to understand what framework is used for the kafka cluster operator.
I see most of the code source in java, is this not based on the golang kuberneters based operator frameworks like kubebuilder or operator-sdk ?

Need some documentation links on the framework used to build this operator.
Thanks,
Kaushik.

**Comment by ppatierno** [comment]
Hi,
we didn't use any specific framework for developing this Java-based operator.
It was developed from scratch.
The Vert.x project is used a lot just for having a reactive and asynchronous model.

**Comment by kaushiksrinivas** [comment]
Hi @ppatierno 
Just trying to understand the operator before using it.
We have a reference with opensource frameworks like operator-sdk to understand the reconciles of the operator.

In this operator, can you point us to any reference docs for architecture or design understanding on this custom framework ?
Thanks,
Kaushik.

**Comment by ppatierno** [comment]
Unluckily we don't have any design or architecture doc for the core. We started to have something like this later for new improvement proposals.

**Comment by kaushiksrinivas** [comment]
Hi,
Thanks for the info.
Is there any specific reason for not choosing any of the open source golang based frameworks to build this operator ?

**Comment by scholzj** [comment]
@kaushiksrinivas Operator is just a pattern. It can be implemented with any programming language. All you need is a Kubernetes client (in our case we use the Fabric8 Kubernetes client). It is not bound to any framework or Golang programming language. 

The frameworks like Operator SDK or Kubebuilder can make this easier. But they did not existed when Strimzi started. As for Golang versus Java, it is really about your programming language preferences and the quality of support for the operand the language offers. In case of Kafka, the Java APIs are part of the Apache Kafka project, are always up to data and always tested with the Kafka release for example. That cannot be always said for the Golang APIs.

**Comment by kaushiksrinivas** [comment]
Got it.
Thanks lot for the summary. Closing the ticket.
