### ISSUE TITLE
[Enhancement] Use latest JMX Exporter

### ISSUE THREAD

**Issue by chris-vest** [strimzi/strimzi-kafka-operator#3791]
**Is your feature request related to a problem? Please describe.**
JMX exporter version 0.12.0 is currently >1 year old. 

**Describe the solution you'd like**
It should be updated to 0.14.0.

**Describe alternatives you've considered**
Wait until 0.15.0?

**Additional context**
This is set here: https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/kafka-thirdparty-libs/2.6.x/pom.xml#L36
And here: https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/kafka-thirdparty-libs/2.5.x/pom.xml#L36

**Comment by scholzj** [comment]
Do you experience any specific issues with 0.12.0? I do not think it is problem to update it ... just trying to judge the priority of this.

**Comment by chris-vest** [comment]
@scholzj I'm working on a PR right now to update it. I'm seeing a very slow metrics endpoint on some Connect clusters, and I had a similar issue with some other applications (can't remember which unfortunately, but unrelated to Strimzi) - these issues were solved by upgrading the JMX exporter.

**Comment by stanlyDoge** [comment]
Fixed by https://github.com/strimzi/strimzi-kafka-operator/pull/3792
