### ISSUE TITLE
[Question] Setting consumer start offset as latest in Mirror Maker2?

### ISSUE THREAD

**Issue by yuwtennis** [strimzi/strimzi-kafka-operator#3798]
Hello .

I use `strimzi/kafka:0.17.0-kafka-2.4.0` for MM2 image.

However, Mirror Maker 2 always sets _earliest_  for consumer . This was confirmed as bug by community.

https://issues.apache.org/jira/browse/KAFKA-10160

I really need to set _latest_ for starting offset for consumer .
Is there anyone who had got over with this problem by any chance ? Perhaps by replacing jar file ?

Thanks,
Yu Watanabe

**Comment by yuwtennis** [comment]
I'd like to apply [this commit ](https://github.com/apache/kafka/commit/2eb10ecac214ccb28ca1b29a368d836e435f1637)  to [original source code](https://archive.apache.org/dist/kafka/2.4.0/kafka-2.4.0-src.tgz) .

Then replace 

```
-rw-r--r-- 1 root root    89247 Dec  9  2019 connect-mirror-2.4.0.jar
```

with new compiled jar source file,

```
-rw-r--r-- 1 y-watanabe y-watanabe 53498 Oct 14 09:23 connect-mirror-2.4.0-sources.jar
``` 

Would this be possible ?

**Comment by scholzj** [comment]
You can just build your own Docker image where you replace the JAR. Basically start from the Strimzi image and copy your new JAR over the old JAR. And then you can specify the new image either in the Cluster Operator configuration or in the KafkaConnect custom resource in `spec.image`.

**Comment by scholzj** [comment]
@yuwtennis Did this worked for you? Can we close this?

**Comment by yuwtennis** [comment]
@scholzj Yes. I will close this case. Thank you for the support.
