### ISSUE TITLE
Problem with deploying zookeeper cluster and kafka because of readiness and liveness probe since redeploying strimzi operator 0.19.0

### ISSUE THREAD

**Issue by slaurencelle** [strimzi/strimzi-kafka-operator#3806]
Hello i don't understand what is happening since i have to uninstall and reinstall my complete kafka and zookeeper cluster i am unable to have it running , the pods complaint about the readiness and liveness probe... nothing have change on my configuration file since i deploy it the first time.

here is the error i got : 
Readiness probe failed: Ncat: Connection refused.
Liveness probe failed: Ncat: Connection refused.
Back-off restarting failed container

i am runing iot on rhel 7.7 
strimzi 0.19.0
kafka and zookeeper 2.5
i have desactivated selinux and firewalld

tks in advance

Stephane

**Comment by scholzj** [comment]
I don't think anyone would be able to help you if you don't share any logs or anything.

**Comment by slaurencelle** [comment]
what are the logs you need to have ?

Stephane

**Comment by slaurencelle** [comment]
what is not working is that the pods for zookeeper are not able to run because of the probe problem.

Regards
Stephane

**Comment by scholzj** [comment]
That is not how it usually works. The probes are usually failing because of something and just like that on their own.

**Comment by slaurencelle** [comment]
here is the result from running the script

[report-14-10-2020_11-46-29.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5379391/report-14-10-2020_11-46-29.zip)

stephane

**Comment by scholzj** [comment]
@stanlyDoge @im-konge The report tool here again didn't captured anything apart from the CRs and operator log. But no operand logs etc. I think you probably broker something in the last fix there? Can you have a look?

**Comment by im-konge** [comment]
@scholzj I'll take a look ASAP

**Comment by scholzj** [comment]
@slaurencelle Until they figure out what is wrong with the report tool ... can you just manually collect the Zookepeer pod logs if Zookeeper pods are not running?

**Comment by slaurencelle** [comment]
yes will get you that after lunch

tks

Stephane

**Comment by slaurencelle** [comment]
Here is one of the zookeeper log pod

[eadae2a9fd38805691fc3ed5b49d66d56f3b9f2b0a67896250fd2f6ec7cf65ad-json.log](https://github.com/strimzi/strimzi-kafka-operator/files/5379988/eadae2a9fd38805691fc3ed5b49d66d56f3b9f2b0a67896250fd2f6ec7cf65ad-json.log)

Stephane

**Comment by scholzj** [comment]
Hmm, interesting. TBH, I haven't seen this error before. So I have no idea beyond what is in the exception - thet it _Failed to resolve address: kafkatdz-cluster-zookeeper-0.kafkatdz-cluster-zookeeper-nodes.kafkatdz.svc_ ... it seems to be unable to resolve all addresses of the Zookeeper nodes. And at the end it seems to just exit after 3 tries. So I guess this looks like some DNS issue in your cluster. Would be interesting if you can resolve these addresses from some other pods.

**Comment by stanlyDoge** [comment]
It seems you used wrong name of the (kafka) cluster. Are you sure you ran
`./tools/report.sh --namespace=kafkatdz --cluster=kafkatdz-cluster`?

**Comment by slaurencelle** [comment]
Hello,
Sorry my bad i put uppercase instead of lowercase for the cluster name :(

here is the result from the report with a lot more info :)

[report-15-10-2020_09-00-31.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5385021/report-15-10-2020_09-00-31.zip)

Tks

Stephane

**Comment by slaurencelle** [comment]
Hello,
I will try to check what is not working for the DNS part in the cluster , waiting if you can have more info in the report file i just share with you.

Regards,

Stephane

**Comment by slaurencelle** [comment]
Hello, it was the dns who was causing this king of behavior, i apply the inittial configmap to my coredns and normally it's suppose to reread it if i do a certain command but it did not, so i just restart the coredns pod and now everything is back to normal :)

Tks a lot guys.

I will close this case

Have a nice one

Stephane

**Comment by slaurencelle** [comment]
Hello, 
Still having problem with probe :(
keep crashing the pod

where can i change the liveness and readiness probe for zookeeper cluster or pod and kafka ?

maybe the default value is not working for me.

regards,
Stephane

**Comment by slaurencelle** [comment]
Ok i see in the log i am still seeing the dns resolution problem when i kill a pods and when it'S restart that's when i encounter the probe problem.

still searching what is causing that, if you got any idea, i am open to hear them :)

Stephane

**Comment by slaurencelle** [comment]
ok i was able to resolve all the problem with the DNS now everything is up and running but as soon that i enable firewalld and that the cluster entity operator restart, my pod are unable to cameback running because of the liveness and readiness probe.

Do i need to open specific port on firewalld for strimsi operator and all the stack ?

Stephane

**Comment by scholzj** [comment]
I never had to configure anything in firewalls.

**Comment by slaurencelle** [comment]
that's what i was expecting normally kubernetes should take care of it

i juste open a question on the kubenretes github. Will wait for them to get back to me and will be happy to shere it with you after :)

**Comment by JRial95** [comment]
I'm facing the same issue. I'm trying to deploy Kafka with the `kafka-ephemeral.yaml` config on a Jelastic Kubernetes cluster.

When I run a `kubectl describe` on zookeeper pods, I get:
```
Warning  Unhealthy ... Readiness probe failed: Ncat: Connection refused.
Warning  Unhealthy ... Liveness probe failed: Ncat: Connection refused.
```

On kafka pods (no message after `:`):
```
Warning  Unhealthy  ...  Readiness probe failed:
Warning  Unhealthy  ...  Liveness probe failed:
```

Has anyone ever managed to run Kafka on a Jelastic Kubernetes cluster?

@slaurencelle Was the kubernetes team able to help you? Did you solve your issue?

**Comment by slaurencelle** [comment]
Hello JRial95,
No did not had any feedback yet from kubernetes team, but solve it myself.
The problem was cause by the new iptables rules that i apply + firewalld that i activated.
after that i had apply a new configmap to my coredns pods which i restart but i did not restart my etcd pods and they were the one causing that the new dns change apply to the coredns configmap was not applying correctly.

hope this help

Regards,
Stephane

**Comment by JRial95** [comment]
Hello Stephane,

Thank you for your answer. I disabled the firewall of my cluster, but it still not working. However, I use the default coredns settings. Is it possible to post your configmap that makes your readiness/liveness probe working?

Thanks for your help!

**Comment by slaurencelle** [comment]
Here is the configmap that i apply at the end and i think i went back to the basic one after tryning multiple config :)

here what i got in it
Data
====
Corefile:
----
.:53 {
    log
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    ready :8181
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}

Is it what you have ?
also i activated firewalld because kubernetes use iptables and that on rhel 7 if i deactivated firewalld it also stop iptables :)
if you activate it here what i add for the rule on the master and worker nodes.

Master nodes:

public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources:
  services: dhcpv6-client ssh
  ports: 6443/tcp 2379-2380/tcp 10250/tcp 10251/tcp 10252/tcp 10255/tcp 10257/tcp 10259/tcp 8472/udp 30000-32767/tcp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

Workers nodes:
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens192
  sources:
  services: dhcpv6-client ssh
  ports: 10250/tcp 10255/tcp 30000-32767/tcp 6783/tcp 2181/tcp 9091/tcp 2888-3888/tcp 9092/tcp 9093/tcp 2888-3888/udp 8472/udp 6783-6784/udp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
if you need anything else :)

and i am using weave for the networking in the kubernetes cluster

Stephane

**Comment by scholzj** [comment]
Did you managed to solve this in some way?

**Comment by JRial95** [comment]
Sorry, I have tested plenty of configs to solve the problem, and I finally forgot to reply. @slaurencelle Yes, I have the same CoreDNS config. Unfortunately, it still doesn't work. It seems like it is related to the config or infrastructure that Jelastic relies on. I have changed the hosting company to solve the problem.

**Comment by jhcook-ag** [comment]
We recently ran into this issue ourselves, and completely removing the operator and namespace then redeploying corrected it. The only likely cause was deploying a cluster with too many objects causes too much activity and there was a docker cache issue. We were seeing other errors we couldn't figure out. 

https://github.com/kubernetes/kubernetes/issues/56682
