### ISSUE TITLE
[Enhancement] Enable CORS configuration for Cruise Control

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#3809]
**Is your feature request related to a problem? Please describe.**
At this moment, cross-origin resource sharing (CORS) configurations for Cruise Control are disabled. This means that the Cruise Control API cannot be accessed by any applications with different origins than the Strimzi components. On one hand this is good as it helps block applications from manipulating a Kafka cluster through Cruise Control without Strimzi Operator approval but on the other hand it prevents third-party applications from getting read-only cluster information from Cruise Control. 

Users should be able to have the option to enable CORS to get read-only information from Cruise Control. Exposing this read-only information poses no additional risk to a Kafka cluster but adds the benefit of letting users configure third-party applications like Linkedin's Cruise Control UI  [1] to monitor their Kafka cluster.

It's important to note that non-read interactions with Cruise Control must still happen through the supported KafkaRebalance custom resource and should not be allowed by any other method. Otherwise, users could preform potentially destructive operations on a Kafka cluster without being properly vetted by the Strimzi Operator. However, configuring a third-party monitoring application for getting read-only cluster status should be allowed.

Related to https://github.com/strimzi/strimzi-kafka-operator/issues/3117

**Describe the solution you'd like**

We should add the following configuration options to`FORBIDDEN_PREFIX_EXCEPTIONS` in the `CruiseControlSpec` [2]
```
webserver.http.cors.enabled
webserver.http.cors.origin
webserver.http.cors.exposeheaders
```
And then hard-code the CORS config for only allowing read-only access methods in the Cruise Control config generator script [3]
```
webserver.http.cors.allowmethods: 'OPTIONS,GET'
```

[1] https://github.com/linkedin/cruise-control-ui
[2] https://github.com/strimzi/strimzi-kafka-operator/blob/218fa73cd49f5804be7c1148b843c40e9fe07435/api/src/main/java/io/strimzi/api/kafka/model/CruiseControlSpec.java#L41
[3] https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/cruise-control-scripts/cruise_control_config_generator.sh#L36-L52

**Comment by EmilMichalczewski** [comment]
Hi, I'd like to take it on this issue
