### ISSUE TITLE
[Question] Readiness probe should take care of recovery due to connection failures

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3850]
```
2020-10-21 05:40:34,817 WARN [Worker clientId=connect-1, groupId=stream-producer-latest-kafka-mysql-connect] Connection to node 2 (ip-10-2-21-191/10.2.21.191:32000) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient) [kafka-coordinator-heartbeat-thread |stream-producer-latest-kafka-mysql-connect]
``` 

Today morning for some reason stream producer/kafka connect (`kubectl get kc`) stopped processing any new request for 60mins. The user reported us the problem then we went and deleted the KC pod and new pod came up and started processing and writing to Kafka.

Can the readiness probe take care of this?

**Comment by scholzj** [comment]
To be honest, from the message it is not exactly clear to see what happened in Connect or in the broker. So it is hard to say if there is something better we can do.

**Comment by alok87** [comment]
When the connection to the database breaks, the connect hangs saying you need to restart kafka connect pod for it to try again. If we can expose a readiness endpoint that gives !200 when the connectors are broken, it would help.

**Comment by scholzj** [comment]
Kafka Connect is a framework for running one or more connectors. So we cannot bind the readiness or liveness probe to a single connector state. That would just cause unnecessary disruptions to other connectors. There is a plan to have the connectors automatically restarted which might help with your case. But this is not implemented yet. So until then you will have to restart the connectors manually over the REST API.

**Comment by alok87** [comment]
Ok thanks any PR/issue i can subscribe.

**Comment by scholzj** [comment]
I'm afraid there is no PR to follow yet. But this is the approved proposal: https://github.com/strimzi/proposals/blob/master/007-restarting-kafka-connect-connectors-and-tasks.md
