### ISSUE TITLE
disable cruise control for single node deploy

### ISSUE THREAD

**Issue by azhang** [strimzi/strimzi-kafka-operator#3859]
How do I disable cruise control for a single broker deployment? I'd like to use the operator in my dev/staging environment but it seems like I just get

    Cruise Control cannot be deployed with a single-node Kafka cluster. It requires at least two Kafka nodes.

**Comment by ppatierno** [comment]
If you have Cruise Control deployed I guess you have the `cruiseControl` property specified in your `Kafka` custom resource.
Just remove that field to have the operator undeploy (or not deploying for a new Kafka cluster) Cruise Control.

**Comment by azhang** [comment]
Ahh, thanks!
