### ISSUE TITLE
Consider renaming the test-container artifact 

### ISSUE THREAD

**Issue by cescoffier** [strimzi/strimzi-kafka-operator#3874]
First, I would like to thank you for this test-container support. It allows me to test against Strimizi and saves a few minutes on my test suite (compared to the default Kafka).

Consider my request as a very low priority, just something I noticed this morning.

This morning, dependabot sent me a notification with _Bump test-container from 0.19.0 to 0.20.0_. At first, I was wondering about a pretty old left-over somewhere in an example project or something. Actually, it's the strimzi module that got updated. Renaming the artifact to _strimzi-test-container_ would improve readability. That might be nothing if you get a few notifications per day, just from dependabot, I got around 30 per day, even more (and don't ask about the junit 4 update from last week). Being able to process them quickly and prioritize them is becoming important. 

BTW, no worries, the tests passed with the new update.

**Comment by scholzj** [comment]
Sounds reasonable. I opened a PR for it -> but it would change only with Strimzi 0.21.0 since I assume this is not critical.

**Comment by cescoffier** [comment]
Thanks!
