### ISSUE TITLE
[Bug] Use of CRD_v1beta1 API for the Strimzi CRDs

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#3875]
**Describe the bug**
Strimzi is using the deprecated BETA1 version of the `apiextensions / CustomResourceDefinition` API. Applying 0.20 against a 1.19 based cluster gives me:

```
namespace/kafka created
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
...
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
...
```

**Expected behavior**
The use of `v1` version from the CRD API

**Environment (please complete the following information):**
 - Strimzi version: .20.
 - Installation method: YAML
 - Kubernetes cluster: OCP 4.6

**Comment by ppatierno** [comment]
There is a well-defined path to move to use v1 CRD API, you can read more here:

https://github.com/strimzi/proposals/pull/14
