### ISSUE TITLE
Unable to get/fetch secrets within validityDays

### ISSUE THREAD

**Issue by jbagdai** [strimzi/strimzi-kafka-operator#3878]
Per certificate renewal process mentioned on strimzi site https://strimzi.io/docs/0.8.1/  **7.4. Certificate renewal**
I am trying to fetch details for secrets which I was able to post deployment. Considering 1 day remaining for validity when I am trying to fetch the same for newly created secrets from Strimzi, it is not showing any secrets for cluster or clients.

Following flag is also set to true in order to be managed certificates operator itself.
generateCertificateAuthority: true

**Comment by scholzj** [comment]
Sorry, I'm not sure I understand the problem. Can you maybe add some examples steps of what does not work?

**Comment by jbagdai** [comment]
Closing the issue, had some environmental issues on my end.
Thank you @scholzj  for following up on this!
