### ISSUE TITLE
Unable to run bin/kafka-reassign-partitions.sh without zookeeper parameter

### ISSUE THREAD

**Issue by denistom** [strimzi/strimzi-kafka-operator#3879]
After upgrading to strimzi 0.20.0 and kafka brokers to 2.5.1, running command bin/kafka-reassign-partitions.sh reports that --zookeeper is required parameter and refuse to run the command.

Other command lines seem to work without --zookeeper parameter. 
Passing localhost:2181, zookeeper service name or IP causes command timeout.

1. Go to kafka broker.
2. Run bin/kafka-reassign-partitions.sh
 or  bin/kafka-reassign-partitions.sh --bootstrap-server localhost:9092 --topics-to-move-json-file /tmp/topics-to-move.json --broker-list "0,1,2" --generate
3. See error
...
--version                               Display Kafka version.
--zookeeper <String: urls>              REQUIRED: The connection string for
                                          the zookeeper connection in the form
                                          host:port. Multiple URLS can be
                                          given to allow fail-over.

According to new Kafka documentation, bin/kafka-reassign-partitions.sh should work without zookeeper parameter, just like the other command lines.

 - Strimzi version: 0.20.0
 - Kafka version: 2.5.1

**Comment by scholzj** [comment]
In Strimzi 0.20, if you want to run the command against Zookeeper, you have to run it inside the Zookeeper pod and connect to `localhost:12181`. 

I'm not sure which parts of `bin/kafka-reassign-partitions.sh` work over Kafka and which require Zookeeper in Kafka 2.5. That might be more question for Apache Kafka. When running your command in Kafka 2.5, I get the same error. 2.6 does not seem to throw it anymore.

**Comment by denistom** [comment]
Thank you for your reply!
