### ISSUE TITLE
[Question] TLS secrets deploying standalone topic and user operator with MSK

### ISSUE THREAD

**Issue by cristianburca** [strimzi/strimzi-kafka-operator#3886]
Hello.

I'm following the documentation provided to deploy standalone topic and user operators presented here: https://strimzi.io/docs/operators/master/deploying.html#deploy-standalone-operators_str

The goal is to configure them to TLS talk with AWS MSK using AWS ACM PCA.

The issue is I don't understand below environment variables for user operator using an AWS ACM private certificate authority. It would be possible to elaborate these, please?

`STRIMZI_CLUSTER_CA_CERT_SECRET_NAME` to point to a Kubernetes Secret containing the public key of the Certificate Authority used for signing Kafka brokers certificates for enabling TLS-based communication. The Secret must contain the public key of the Certificate Authority under the key ca.crt. This environment variable is optional and should be set only if the communication with the Kafka cluster is TLS based.

`STRIMZI_EO_KEY_SECRET_NAME` to point to a Kubernetes Secret containing the private key and related certificate for TLS client authentication against the Kafka cluster. The Secret must contain the keystore with the private key and certificate under the key entity-operator.p12, and the related password under the key entity-operator.password. This environment variable is optional and should be set only if TLS client authentication is needed when the communication with the Kafka cluster is TLS based.

**Comment by scholzj** [comment]
TBH, I have no clue what  AWS ACM PCA is. So I'm not sure how much help can I be. The `STRIMZI_CLUSTER_CA_CERT_SECRET_NAME` is the public certificate of the CA and is used to validate the server identity when TLS encryption is used. The `STRIMZI_EO_KEY_SECRET_NAME` is the private key used for authentication when TLS Client Authentication is enabled. If you do not use TLS client authentication, you can just leave it out.

**Comment by cristianburca** [comment]
Sorry for not being explicit. This is AWS PCA
https://docs.aws.amazon.com/acm-pca/latest/userguide/PcaWelcome.html

**Comment by scholzj** [comment]
Thanks for the link. But I'm not sure anyone will have time to read through the docs to understand how the service is expected to work. So you either need to find someone who uses it or to find out how AWS expects it to be used by applications which have know special support for the service.

**Comment by cristianburca** [comment]
Managed to solve the issue STRIMZI_CLUSTER_CA_CERT_SECRET_NAME is just the certificate of amazonrootca1 from a truststore (cacerts).

STRIMZI_EO_KEY_SECRET_NAME is basically the keystore.
