### ISSUE TITLE
[Question] ...JMX Exporter

### ISSUE THREAD

**Issue by yangvipguang** [strimzi/strimzi-kafka-operator#3891]
should  I  deploy JMX exporter separately？

**Comment by scholzj** [comment]
JMX Exporter is deployed automatically when you enable the Prometheus metrics: https://strimzi.io/docs/operators/latest/full/using.html#assembly-metrics-deployment-configuration-kafka

**Comment by yangvipguang** [comment]
@scholzj  I have enable the prometheus metrics and deploy the podmonitor 。The result is that a kafka exporter pod is running.I have several questions:
![image](https://user-images.githubusercontent.com/11416887/97837782-e3502380-1d19-11eb-8cfa-9d7e878971da.png)

1、does  the kafka exporter include all metrics（kafka and  jmx ...） 
2、When i port-forward the pod with 9404 port. I can open the url with metrics path. But I only can see  kafka_topic and  kafka_consumergroup  metrics  without any other metrics（jmx）
![image](https://user-images.githubusercontent.com/11416887/97837991-42ae3380-1d1a-11eb-8cd2-78b807742133.png)

**Comment by scholzj** [comment]
The Kafka Exporter has nothing to do with JMX Exporter. The JMX Exporter provides Prometheus metrics in Kafka and Zookeeper pods. Kafka Exporter provides some additional metrics not provided by Kafka. It depends what exactly are the metrics you want, but they provide different metrics and in most cases you want to use both.

**Comment by smartpcr** [comment]
every other time it returns "no data" when querying prometheus.

**Comment by scholzj** [comment]
@yangvipguang Did this explanation helped? Can we close this?

**Comment by yangvipguang** [comment]
@scholzj  yes very  thanks!
