### ISSUE TITLE
Why the default of 'isolation.level' in Kafka is 'read_uncommitted'

### ISSUE THREAD

**Issue by Usharaniaswa** [strimzi/strimzi-kafka-operator#3892]
Hi Team,

One of our Kafka connect pipeline ended up producing a huge duplicates. To resolve this we took couple of steps, adding on it we would like to change the 'isolation.level' = 'read_committed' from 'read_uncommitted'. Before making this change wanted to understand why did Kafka have 'read_uncommitted' as default behavior when it is actually safe to have 'read_committed' which helps us in avoiding the dirty read of messages.

Any thoughts on this will be appreciated. Thank you !!

**Comment by scholzj** [comment]
I think this is probably something for the Kafka community and not for Strimzi since the defaults are not Strimzi specific. I suggest asking on the Kafka User mailing list: http://kafka.apache.org/contact

**Comment by Usharaniaswa** [comment]
Thank you.
