### ISSUE TITLE
[Bug] Rolling update does not recover and roll all pods after timeout when certificates are updated

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#3913]
**Describe the bug**
The main problem is when we want to run `testClusterCaRemovedTriggersRollingUpdate` with CO's operationTimeout set to 30s. The test itself (the procedure itself too) is successful on OCP3.11, but fails on OCP4.x. So we were forced to changed the timeout of CO to 5mins.

If we delete cluster certs and waiting for ZK rolling update to be done, just one pod is rolled and any Kafka pod is rolled. It's "fixed" when we set the operationTimeout of CO to be more than minute.

Something similar is with `testTriggerRollingUpdateAfterOverrideBootstrap` in `RollingUpdateST`. 

**To Reproduce**
For example run the `testClusterCaRemovedTriggersRollingUpdate` test or try this:

(on OCP4.x)
1. Deploy Strimzi with operationTimeout to 30s
2. Deploy the Kafka cluster with internal/external listeners
3. Add the `kafka-test.XXXX.azure.XXXX.net` to "new bootstrap alternative name"
4. The Kafka pods will not roll in time and this issue happen

**Expected behavior**
Rolling update of ZK and Kafka is successful with `operationTimeout` set to 30s.

**Environment (please complete the following information):**
 - Strimzi version: all version & master
 - Installation method: yaml
 - Kubernetes cluster: Openshift 4.x

`oc get pod`
```
my-cluster-entity-operator-66c9c4c7cc-ksnxm   3/3       Running   0          10m
my-cluster-kafka-0                            2/2       Running   0          11m
my-cluster-kafka-1                            2/2       Running   0          11m
my-cluster-kafka-2                            2/2       Running   0          11m
my-cluster-kafka-clients-67f75b4c76-vc825     1/1       Running   0          10m
my-cluster-zookeeper-0                        1/1       Running   0          8m55s
my-cluster-zookeeper-1                        1/1       Running   0          12m
my-cluster-zookeeper-2                        1/1       Running   0          12m
strimzi-cluster-operator-7c57c55bbb-29d4l     1/1       Running   0          13m
```

**Comment by scholzj** [comment]
Triaged on 21.7.2022: Looks like a bug which should be fixed.

**Comment by devguyio** [comment]
Picking this up
