### ISSUE TITLE
Failed to calculate the number of expected pods: found no controller ref for pod messages

### ISSUE THREAD

**Issue by talonx** [strimzi/strimzi-kafka-operator#3928]
**Describe the bug**
"Failed to calculate the number of expected pods: found no controller ref for pod" messages fill the Kubernetes event logs after deploying a Kafka cluster using the operator.

**To Reproduce**
Deploy a 3 node Kafka cluster.

**Expected behavior**
Not expecting these messages.

**Environment (please complete the following information):**
 - Strimzi version: 0.18.0
 - Installation method: YAML
 - Kubernetes cluster: 1.16.13-gke.401 
 - Infrastructure: GKE

**Comment by scholzj** [comment]
Who is emitting such messages? Strimzi does not create the pods. The StatefulSet controller. So this is most probably coming from it?

**Comment by talonx** [comment]
> Who is emitting such messages? Strimzi does not create the pods. The StatefulSet controller. So this is most probably coming from it?

Yes, these are coming from the Kubernetes event logs. I suspect this indicates that there was something incorrect in the StatefulSet (or some other K8S config) set up by the operator but I am not sure what.

**Comment by scholzj** [comment]
But the events are always produced by something - so I think you will need to find out who produced this particular events and maybe in its logs there will be more details.

**Comment by scholzj** [comment]
Did you managed to find out what was producing the events? Was it the StatefulSet controller?
