### ISSUE TITLE
[Integrating Vault with Strimzi Kafka] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3931]
Hi Team,

I am working on a use case of integrating vault with Kafka for which the following blog really helped me. 

https://strimzi.io/blog/2018/11/16/using-vault-with-strimzi/

However, some of the questions I have are, Do we have any similar approach for Client CA as this blog deals with making the cluster configuration as below.

```
spec:
  clusterCA:
    generateCertificateAuthority: false
```

I have tried one of the ways below.

1) Created a Kafka user manually and extracted the user.key and user.crt into the Keystore through which I was able to Produce and Consume messages on a particular Kafka topic.

2) Now my ask do we have any approach to generate Client CA's the way we have created Cluster as explained in the blog and then disabling the property something like this while launching the Kafka cluster.

```
spec:
  clientCA:
    generateCertificateAuthority: false
```

Need help here.

**Comment by scholzj** [comment]
The Vault blog post was contributed by a user. I do not think we have any experience with Vault in the core Strimzi team. So this might be up to you. You can definitely use

```yaml
spec:
  clientCA:
    generateCertificateAuthority: false
```

For client CA in the same way as for the cluster CA. So that should be possible. The question is how you will generate the user certificates I guess - whether directly in Vault or using the User Operator.

**Comment by vperi1730** [comment]
Oh ok. Ya i found documentation in vault which covers the building your own CA. Sure, let me work on this and will come back.

**Comment by scholzj** [comment]
If you figure it out and would be interested in writing a follow up blog post to help others it would be of course great ;-)

**Comment by vperi1730** [comment]
Sure, I will revert back on this.

**Comment by vperi1730** [comment]
Another question i have is, Can we launch the Kafka cluster only with client-ca-cert in place without client-ca secret. 

I am making both the configuration params to false inside the spec.

**Comment by scholzj** [comment]
I think you need both. But if you disable the User Operator, I believe you can just set the key to same non-sense. It is only the User Operator actually using it.
