### ISSUE TITLE
Own Cluster and Client CA

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-kafka-operator#3935]
Need help on certificate.

Our corporate asking CSR file based on that they will generate CA.

I used below command to generate CSR and send that CSR to  coprporate.

```
openssl genrsa -out ca.key 4096

openssl req -new -sha256 \
-key ca.key \
-out ca.csr \
-subj "/C=IN/ST=WB/L=Kolkata/O=CloudCafe/CN=cluster.local"
```
But after receiving certificate we created secrets from that file and our ca.key and we use following configuration in kafka.yaml

```
  clusterCa:
    generateCertificateAuthority: false
```

But zookeeper not coming up (error: Looking for right CA), seems zookeeper not accepting that certificate.

Please help me to diagnosis the issue.

**Comment by scholzj** [comment]
First of all, without sharing any logs and any details, you will always get only a very generic answer. So, did you followed this guide [here](https://strimzi.io/docs/operators/latest/full/using.html#installing-your-own-ca-certificates-str)? Including all the steps including _All CAs in the chain should be configured as a CA in the X509v3 Basic Constraints._ which can cause problems like this?

**Comment by cloudcafetech** [comment]
Ya, got it. Complete Chain required.
