### ISSUE TITLE
[Enhancement] Support recreate deployment strategy for Kafka Connect cluster

### ISSUE THREAD

**Issue by ramanenka** [strimzi/strimzi-kafka-operator#3952]
**Is your feature request related to a problem? Please describe.**
Due to the nature of our source connector which can't be parallelized we use one-node Kafka Connect cluster deployed inside a pod that is given a lot of resources (CPU and Memory). Currently [hardcoded](https://github.com/strimzi/strimzi-kafka-operator/blob/a404c3d4961ea81c525bd7cc97433b7884b8d745/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectCluster.java#L470-L476) `RollingUpdate` deployment strategy causes doubled resource consumption during the cluster rollover due to both pods (new and old) be up. To accommodate to this short increase of resource consumption we have to upsize our k8s cluster which we wouldn't normally need if the operator supported the deployment recreate strategy.

**Describe the solution you'd like**
Change the deployment strategy of Kafka Connect deployments to `Recreate` or provide a way to customize the deployment strategy.

**Describe alternatives you've considered**
Manage Kafka Connect deployments ourselves without using the operator for that, but we'd like to use strimzi as much components as possible.

**Additional context**
* https://github.com/strimzi/strimzi-kafka-operator/pull/281

**Comment by scholzj** [comment]
Thanks for the enhancement. This sounds reasonable. I think we have to think about how to make it configurable in Connect and not for example in the operators which always need to use Recreate. But it is a good point.

**Comment by scholzj** [comment]
I opened the PR to add this feature.
