### ISSUE TITLE
[Bug] grafana dashboard displays none or part of panel data

### ISSUE THREAD

**Issue by smartpcr** [strimzi/strimzi-kafka-operator#3958]
**Describe the bug**
I was following [doc](https://strimzi.io/docs/operators/latest/deploying.html) and grafana is unable to consistently displaying all the data, the following are screen shots when I do page refresh:

![image](https://user-images.githubusercontent.com/9336638/99165616-86aa1c80-26ba-11eb-9c4a-f3e0dde82e35.png)
![image](https://user-images.githubusercontent.com/9336638/99165803-9590cf00-26ba-11eb-8600-295ea1eaf6e9.png)
![image](https://user-images.githubusercontent.com/9336638/99166083-af321680-26ba-11eb-8804-14737c20a9b9.png)

**To Reproduce**

1. deploy prometheus operator
``` bash
kubectl create namespace monitoring
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add stable https://charts.helm.sh/stable
helm repo update
helm install monitoring prometheus-community/kube-prometheus-stack -n monitoring
```

2. check grafana user/password, by default it's `admin` and `prom-operator`
``` bash
k get secret -n monitoring prometheus-grafana -o json | jq -r '.data."admin-user" | @base64d'
k get secret -n monitoring prometheus-grafana -o json | jq -r '.data."admin-password" | @base64d'
```

3. deploy strimzi kafka-operator
``` bash
helm repo add strimzi https://strimzi.io/charts/
helm repo update
kubectl create namespace kafka
helm install strimzi strimzi/strimzi-kafka-operator --namespace kafka
```

4. install kafka cluster, the yaml files are modified from strimzi [examples](https://github.com/strimzi/strimzi-kafka-operator/tree/master/examples)

``` bash
kubectl apply -f ./kafka/my-cluster.yaml -n kafka
```

5. deploy additional prometheus props as k8s secret, namespace was changed from `myproject` in example to `kafka`

``` bash
kubectl create secret generic additional-scrape-configs --from-file=./kafka/prometheus-additional.yaml -n monitoring
kubectl apply -f ./kafka/strimzi-pod-monitor.yaml -n monitoring
kubectl apply -f ./kafka/prometheus-rules.yaml -n monitoring
kubectl apply -f ./kafka/prometheus.yaml -n monitoring
```

6. create a new grafana deployment using `strimz` app selector
``` bash
kubectl apply -f ./kafka/grafana.yaml -n monitoring
kubectl apply -f ./kafka/grafana-ingress.yaml -n monitoring
```

7. navigate to `http://strimzi-grafana.k3d.local` (exposed via ingress rule) and set data source: type=`prometheus` and url=`http://prometheus-operated:9090`, then imported the following dashboards:
``` text
strimzi-kafka.json
strimzi-kafka-exporter.json
strimzi-operators.json
strimzi-zookeeper.json
```

**Expected behavior**
I should see consistent results for all panels in grafana dashboard.

**Environment (please complete the following information):**
 - Strimzi version: `0.20`
 - Installation method: `helm`
 - Kubernetes cluster: `1.19`
 - Infrastructure: `k3d version v3.2.0, k3s version v1.18.9-k3s1 (default)`

**YAML files**
- my-cluster.yaml
- prometheus-additional.yaml
- strimzi-pod-monitor.yaml
- prometheus-rules.yaml
- prometheus.yaml
- grafana.yaml
- grafana-ingress.yaml
- strimzi-kafka.json
- strimzi-kafka-exporter.json
- strimzi-operators.json
- strimzi-zookeeper.json

[strimzi-dashboard.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5541876/strimzi-dashboard.zip)

**Comment by scholzj** [comment]
What happens when you periodically query Prometheus without Grafana? Since Grafana gets the data from Prometheus, this sounds like Prometheus is not returning the data consistently.

CC: @sknot-rh and @ppatierno who understand best the monitoring stack.

**Comment by smartpcr** [comment]
every other time Prometheus returns "no data"

**Comment by scholzj** [comment]
What storage does your Prometheus use? Is it running stable? Or restarting?

**Comment by ppatierno** [comment]
> every other time Prometheus returns "no data"

what do you mean by this? can you query Prometheus directly (through the PromQL UI) for the missing metrics? Can you check that the Kafka target are scraped by Prometheus (in the "Targets" section in its UI)?

**Comment by jhartzell** [comment]
I have basically taken very similar steps and I am noticing a similar issues, there is no data provided by Prometheus.. Regardless of how many times I query prometheus there is never any data for the Strimzi Kafka Dashboard. I did notice that when deploying prometheus it always has a singular restart before successfully staying online.

I'd be happy to provide any information to help move this issue along!

**Comment by smartpcr** [comment]
made a mistake deployed two prometheus in two namespaces.
