### ISSUE TITLE
memory leak on cluster-operator

### ISSUE THREAD

**Issue by totee19** [strimzi/strimzi-kafka-operator#3962]
hello,

cluster-operator pod seem have a memory leak according my dynatrace probe.

`pod/strimzi-cluster-operator-597c48675d-49xjz                   1/1       Running   18         18d`

<img width="931" alt="Screenshot 2020-11-16 at 12 26 10" src="https://user-images.githubusercontent.com/70373967/99247298-10670080-2807-11eb-81fd-c02e52f0c62a.png">

Do you think if I increase JVM size I can fix this behaviors ?

**Comment by scholzj** [comment]
What version is that?

**Comment by scholzj** [comment]
Or maybe to put it differently. We fixed some stuff in the Connector Operator which is part of the Cluster Operator in 0.20.0. So if this is with older version, it might be worth checking with the newer version to see how much of that is related. If it is with 0.20.0, it might be something else ... in which case feel free to point us to the parts of code to fix or open a PR.

**Comment by totee19** [comment]
> What version is that?

It's strimzi 0.19.0

**Comment by scholzj** [comment]
Right. So I guess in theory this could be the issue we fixed in 0.20 (but of course might be also something else)

**Comment by totee19** [comment]
I will plan an update my strimzi to 0.20.0.
I will open a issue if I meet the same behavior.

Thank for your support

**Comment by totee19** [comment]
I can update strimzi 0.17.0 to 0.20.0 directly ?

**Comment by scholzj** [comment]
You can directly update between two versions which support the same Kafka version. So for example if Strimzi 0.17.0 supports Kafka 2.5.0, you should be able to upgrade directly. But for the record, we test only step by step upgrades in Strimzi.

**Comment by totee19** [comment]
I just checked in strimzi V0.17.0 use kafka 2.4.0 version, and from strimzi 0.19.0 remove support for 2.4.0 and 2.4.1 in kafka.
If I apply update to strimzi 0.20.0 directly 
Do I risk losing my user configurations(kafka-user, kafka-topic and secret certificat) and records or just records?
Or the best is apply incremental patch? knowing I can loss record on the topic

**Comment by scholzj** [comment]
I would recommend to go step by step. For example 0.17 -> 0.18 -> Upgrade Kafka to 2.5 -> 0.20 ... that way you do the clean Kafka upgrade.

**Comment by totee19** [comment]
I note in strimzi 0.20.0 "Note: This is the last version of Strimzi that will support Kubernetes 1.11 and higher. Future versions will support only Kubernetes 1.16 and higher."

I use openshift 3.11 does that mean the next strimzi 0.20.0 release will not support on my orchestration platform ?

**Comment by scholzj** [comment]
Yes. 0.20.0 should still work for you. But 0.21.0 might not anymore. I'm afraid that we need to make the cut in order to be able to support new versions of Kubernetes. In particular, for example Kubernetes 1.22 will not support CRD v1beta1 and we need to start preparing for it.

**Comment by totee19** [comment]
It's clear thank for your replies.
