### ISSUE TITLE
Review thread pooling configuration of dependencies

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#397]
We are using libs in the controllers which will have their own thread pools. Some of those are probably configuring themselves in a container un-aware way (i.e. parameterized by host #cpus, not container). We should review these libs to determine if they are doing this, and open futerh issues for configuring them in a container-aware way.

**Comment by scholzj** [comment]
Triaged on 26.5.2022: @tombentley Can you elaborate a bit more on this? Do you think this is still needed?

**Comment by scholzj** [comment]
Triaged on 26.5.2022: After discussion with Tom - we did not observe any issues related to this, so it can be closed.
