### ISSUE TITLE
Metrics ConfigMap contains JSON under YML property

### ISSUE THREAD

**Issue by sknot-rh** [strimzi/strimzi-kafka-operator#3986]
While working on https://github.com/strimzi/strimzi-kafka-operator/pull/3855 I have noticed we are using [metrics-config.yml](https://github.com/strimzi/strimzi-kafka-operator/blob/5f09629ec9c0b2d60075d999017376f546df4d53/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java#L113) as a property for the generated Logging and Metrics ConfigMap.
From the code we can see we are putting a JSON to the YML property: https://github.com/strimzi/strimzi-kafka-operator/blob/5f09629ec9c0b2d60075d999017376f546df4d53/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractModel.java#L530
We should be consistent with the data format.

**Comment by scholzj** [comment]
What is the solution for this @sknot-rh? Can we use YAML to pass to the JMX exporter? Or should we rename the key in the ConfigMap?

**Comment by sknot-rh** [comment]
Renaming the key should be enough.

**Comment by sknot-rh** [comment]
Fixed in https://github.com/strimzi/strimzi-kafka-operator/pull/5072
