### ISSUE TITLE
Intellij CRD definition

### ISSUE THREAD

**Issue by ghahramani** [strimzi/strimzi-kafka-operator#3990]
Hi,

It would be good to have the CRD definition for Intellij, it makes the writing of new yml files easier

Here shows how to add the new definition other than the default Kuberentes ones to Intellij

https://www.jetbrains.com/help/idea/kubernetes.html#crd

**Comment by scholzj** [comment]
You can just load the existing CRDs from the `install/cluster-operator` folder. So I do not think nothing prevents you from this.

**Comment by ghahramani** [comment]
I will try it but it would be good to have a direct URL to define in Intellij

**Comment by scholzj** [comment]
I used it only from file TBH. i never used the URL. But you should be able to load them then from GitHub, or? https://github.com/strimzi/strimzi-kafka-operator/tree/0.20.0/install/cluster-operator

**Comment by ghahramani** [comment]
Thank you @scholzj, the file reference worked but URL needed a bit trick, I needed to load the file from this url individually for each file under that folder:

```
https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/0.20.0/install/cluster-operator/{filename}.yml
```

By anyway, it is an acceptable workaround, thus I will close this issue.

**Comment by scholzj** [comment]
Do you know if IntelliJ can load multiple CRDs from a single YAML file using the URL? If yes, maybe we can generate for the next release a single file containing all of them.

**Comment by ghahramani** [comment]
Yeah, that was a good Idea, I just tried it and it works, I just combined all the files under the folder you mentioned above with `---` separator and then attached just that one file then Intellij recognized it

**Comment by scholzj** [comment]
Ok. Thanks for the update. I will have a look into it to have such file generated for the next release to make this easier.
