### ISSUE TITLE
Neither helm chart nor manual installation works 

### ISSUE THREAD

**Issue by ghahramani** [strimzi/strimzi-kafka-operator#3991]
Hi,

I am working with a protected Kubernetes environment in which privileged pods are forbidden, I have tried both helm chart installation and  `kubectl apply -f https://strimzi.io/install/latest?namespace=messaging`.

The error that I am getting is:

```
Error creating: pods "strimzi-cluster-operator-54ff55979f-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.initContainers[0].securityContext.runAsNonRoot: Invalid value: false: must be true spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_ADMIN": capability may not be added spec.initContainers[0].securityContext.capabilities.add: Invalid value: "NET_RAW": capability may not be added]
```

And there is no way to change securityContext in both ways.

**Comment by scholzj** [comment]
I'm not sure what the Helm does or doesn't allow to customize. The installation from the URL really just takes the released files and changes the namespace. But you could download the ZIP file with the YAMLs from the release page (https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.20.0) and customize the Cluster Operator pod. For the Kafka cluster, you can customize the security context in the `template` section for the different components: https://strimzi.io/docs/operators/latest/full/using.html#type-PodTemplate-reference

From your error, the cluster operator does not have any init container, so I'm not sure I completely understand the error message. (if you have anything like Istio injecting things into other pods, you would need to disable it for Strimzi related pods)

**Comment by ghahramani** [comment]
Yeah I have Istio, that's what I am saying, for a company, it would be difficult to keep and maintain all `yml` files, it always better to use helm or installer that they do the job, yml files usually are good for customized applications in my opinion. Why do I need to disable Istio for Strimzi pods?

**Comment by scholzj** [comment]
> Yeah I have Istio, that's what I am saying, for a company, it would be difficult to keep and maintain all yml files, it always better to use helm or installer that they do the job, yml files usually are good for customized applications in my opinion. 

Well, we always welcome contributions. So if you want, you can enhance the Helm Chart and open a PR.

> Why do I need to disable Istio for Strimzi pods?

Strimzi does not integrate with Istio. So it will not work if it is injecting sidecars everywhere and hijacking the connections.

**Comment by ghahramani** [comment]
> Well, we always welcome contributions. So if you want, you can enhance the Helm Chart and open a PR.
Yeah, you are right, I will work on that as soon as I have time.

> Strimzi does not integrate with Istio. So it will not work if it is injecting sidecars everywhere and hijacking the connections.
Hmm, how about the Kafka pods themselves that bring up via Strimzi?

**Comment by scholzj** [comment]
> Hmm, how about the Kafka pods themselves that bring up via Strimzi?

That is the same.

**Comment by ghahramani** [comment]
But if I install Kafka from bitnami helm chart, it works with Istio injection with no problem, the only thing that I need to set is the `serviceAccountName` that allows the `initContainer` does some stuff for Istio, nothing else.

So what Stirmzi exactly does when it wants to bring up the Kafka that makes it incompatible with Istio?

**Comment by scholzj** [comment]
That is well possible. I didn't said that Kafka cannot work with Istio. I said that Strimzi does not support it. 

Strimzi does its own security so if Istio messes up with it, it breaks it. I have no idea what the Bitnami Helm Chart does and what features it has. So I cannot compare it.
