### ISSUE TITLE
[Question] Are pods expected to restart on num replica change?

### ISSUE THREAD

**Issue by talonx** [strimzi/strimzi-kafka-operator#3998]
When I change the "replicas" for Kafka from say 4 to 3 and apply using kubectl (after ensuring remove_broker using Cruise Control has moved all partitions away from the 4th broker), it restarts all the pods in the cluster. There are no other changes in the cluster definition YAML. The operator logs say something along the lines of "restarting pod kafka-0 because it has old generation".

Is it expected that each time we add or remove a broker and make no other changes, all other brokers in the cluster should restart? If not, what could be happening here?

**Comment by scholzj** [comment]
Yes, that is currently expected. It is basically related to how stateful sets work and how each pod is sharing the same configuration which changes.

**Comment by talonx** [comment]
Thanks.
