### ISSUE TITLE
[Enhancement] Support of "readOnlyRootFilesystem=true" for ContainerTemplates

### ISSUE THREAD

**Issue by hubmat00** [strimzi/strimzi-kafka-operator#4011]
**Is your feature request related to a problem? Please describe.**
The CRD's of the Strimzi Operator allow the usage of custom securityContext for `ContainerTemplate` (https://strimzi.io/docs/operators/latest/full/using.html#type-ContainerTemplate-reference). The securityContext of `ContainerTemplate` is based on the official `SecurityContext` of Kubernetes (https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#securitycontext-v1-core). This means it is allowed to set the filesystem as read only with `readOnlyRootFilesystem=true`. However, the official docker containers of Strimzi do not support read only filesystems.

As we plan to provision PodSecurityPolicies for our Kubernetes-Clusters with (`users > 1000` and `readOnlyRootFilesystem: true`), we are currently not able to run the Strimzi Operator and `ContainerTemplates` with these configurations.

**Describe the solution you'd like**
The proper solution IMHO would be to map the necessary volumes when provision the cluster by the operator. For example `ZookeeperCluster`:
 * `ZookeeperCluster.getVolumes(...)` at https://github.com/strimzi/strimzi-kafka-operator/blob/0.20.0/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ZookeeperCluster.java#L583
 * `ZookeeperCluster.getVolumeMounts()` at https://github.com/strimzi/strimzi-kafka-operator/blob/0.20.0/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ZookeeperCluster.java#L614

Maybe there exists also a more generic solution for all `ContainerTemplates` within the operator.

**Describe alternatives you've considered**
One workaround would be the support of custom volumes mounts (i.e. /tmp). There exists already an enhancement issue to support mounting of such custom volumes to pods (https://github.com/strimzi/strimzi-kafka-operator/issues/3693). However, this would only be a workaround solution as developers need the necessary knowledge which folder must be writable and need to add all necessary volumes.

**Additional context**
For instance starting zookeeper with "readOnlyRootFilesystem=true" triggers the following startup issues:

```
Detected Zookeeper ID 1
mkdir: cannot create directory '/tmp/zookeeper': Read-only file system
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
Certificate was added to keystore
keytool error: java.io.FileNotFoundException: /tmp/zookeeper/cluster.truststore.p12 (No such file or directory)
Preparing truststore is complete
Looking for the right CA
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt
Preparing keystore for client and quorum listeners
Error opening output file /tmp/zookeeper/cluster.keystore.p12
/tmp/zookeeper/cluster.keystore.p12: No such file or directory
unable to write 'random state'
Preparing keystore for client and quorum listeners is complete
Starting Zookeeper with configuration:
tee: /tmp/zookeeper.properties: Read-only file system
./zookeeper_config_generator.sh: line 4: cannot create temp file for here-document: Read-only file system
server.1=i-kafka-zookeeper-0.i-kafka-zookeeper-nodes.i-kafka.svc:2888:3888:participant;127.0.0.1:12181
server.2=i-kafka-zookeeper-1.i-kafka-zookeeper-nodes.i-kafka.svc:2888:3888:participant;127.0.0.1:12181
server.3=i-kafka-zookeeper-2.i-kafka-zookeeper-nodes.i-kafka.svc:2888:3888:participant;127.0.0.1:12181
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
2020-11-27 15:30:49,336 INFO Reading configuration from: /tmp/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-11-27 15:30:49,342 ERROR Invalid config, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain) [main]
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /tmp/zookeeper.properties
    at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:156)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:113)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Caused by: java.lang.IllegalArgumentException: /tmp/zookeeper.properties file is missing
    at org.apache.zookeeper.server.util.VerifyingFileFactory.doFailForNonExistingPath(VerifyingFileFactory.java:51)
    at org.apache.zookeeper.server.util.VerifyingFileFactory.validate(VerifyingFileFactory.java:45)
    at org.apache.zookeeper.server.util.VerifyingFileFactory.create(VerifyingFileFactory.java:40)
    at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:141)
    ... 2 more
Invalid config, exiting abnormally
```

I guess similar problems occur with other `ContainerTemplates`: `CruiseControlTemplate`, `EntityOperatorTemplate`, `JmxTransTemplate`, `KafkaBridgeTemplate`, `KafkaClusterTemplate`, `KafkaConnectTemplate`, `KafkaExporterTemplate`, `KafkaMirrorMakerTemplate`, `ZookeeperClusterTemplate`

My CRD configuration for `Kafka`, more specifically the `ZookeeperClusterTemplate`, looks like the following:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: kafka-cluster

spec:
  ...
  zookeeper:
    replicas: 3
    template:
      pod:
        securityContext:
          runAsUser: 1001
      zookeeperContainer:
        securityContext:
          runAsUser: 1001
          readOnlyRootFilesystem: true
      tlsSidecarContainer:
      	...
  ...
```

Docker Image used by the operator: `strimzi/kafka:0.18.0-kafka-2.5.0`

**Comment by scholzj** [comment]
Thanks for raising this. I think this is a valid point, I will add it to my TODO list.
