### ISSUE TITLE
defaultImageRepository instead of imageRepositoryOverride in helm chart

### ISSUE THREAD

**Issue by wtayyeb** [strimzi/strimzi-kafka-operator#4014]
Dear strimzi team

In the operator helm chart, there is `imageRepositoryOverride` and `imageTagOverride` in values.yaml
and if one set them, he could not change `STRIMZI_KAFKA_xx_IMAGES` as they are Override like their name.

but let think this way, if one need to define private/cache registry for all images, and set `kafkaConnect` image to a custom repository, above variables will prevent him from that custom image. so he must set all .Values.xx.image.repository to private/cache registry and also set that custom image for kafkaconnect.

I have read and install several charts (>20) and there is a pattern letting you to define defaultRepository or defaultRegistry, to use them as default value not Override value, and the .Values.xx.image.repository is the final value and not the default value.

for example following line (from _kafka_image_map.tpl)
```
2.5.0={{ default .Values.kafka.image.repository .Values.imageRepositoryOverride }}/{{ .Values.kafka.image.name }}:{{ default .Values.kafka.image.tagPrefix .Values.imageTagOverride }}-kafka-2.5.0
```
will be something like this:
```
2.5.0={{ default .Values.defaultImageRepository .Values.kafka.image.repository }}/{{ .Values.kafka.image.name }}:{{ default .Values.defaultImageTag .Values.kafka.image.tagPrefix }}-kafka-2.5.0
```
and empty all values like .Values.xx.image.repository, .Values.xx.image.tag to let user set them.

**Comment by scholzj** [comment]
That sounds like it makes sense. Can you open a PR for it then?

**Comment by ShubhamRwt** [comment]
@wtayyeb Hello, do you plan to create a PR for this?
