### ISSUE TITLE
[Question] Can I deploy strimzi on a kubeadm cluster?

### ISSUE THREAD

**Issue by Bar0hayon** [strimzi/strimzi-kafka-operator#4024]
Hi :)
in the documentation you specified minikube as a prerequisite,
also in the quickstart guide you have posted steps for minikube/oc/kind clusters,
so my question is: if I have a kubeadm cluster configured can I use strimzi?

**Comment by scholzj** [comment]
Minikube, Kind etc. are just the tools you can use to get started locally. But Strimzi works with more or less any Kubernetes clusters ... that includes the different managed offerings from public clouds and all other deployments. So it includes Kube clusters deployed with `kubeadm` as well.

**Comment by Bar0hayon** [comment]
thnks on the fast response 👍
