### ISSUE TITLE
Is there a plan to move away from the current kafka exporter?

### ISSUE THREAD

**Issue by yzargari** [strimzi/strimzi-kafka-operator#4026]
Correct me if I'm wrong, but strimzi uses the kafka exporter from https://github.com/danielqsj/kafka_exporter - right?
It looks like this project is no longer maintained as last release was 2.5 years ago. Is there a plan to replace it with a better maintained project?

I'm now suffering from a bug in that exporter that causes negative lag values. This bug was reported 2 years ago [here](https://github.com/danielqsj/kafka_exporter/issues/76) and was even offered a PR for [here](https://github.com/danielqsj/kafka_exporter/pull/78), but it doesn't look like anyone is looking at it...

**Comment by scholzj** [comment]
I guess we are considering the options ... from moving to some other tool up to using our own build of the exporter. I guess we will get to it soon. There are some opened bug issues in Strimzi around some specific issues if you want to follow them.
