### ISSUE TITLE
[Enhancement] Make the Kafka cluster-id available in the Kafka CRD

### ISSUE THREAD

**Issue by lga-zurich** [strimzi/strimzi-kafka-operator#4028]
The Kafka [Cluster Id](https://cwiki.apache.org/confluence/display/KAFKA/KIP-78%3A+Cluster+Id) was meant as a handy means of identifying clusters inside a company, for example. Currently in Strimzi one can only find the Kafka cluster-id either by connecting to the Kafka cluster and using the KafkaAdmin interface or going all the way to Zookeeper. For inventory or monitoring tools that can list the Strimzi Kafka clusters in a Kubernetes cluster or namespace, it would be nice not to grant them more privileges to access the cluster id through the methods above.

The cluster-id could be made available as part of the status of the Kafka CRD, for example.

The advantage of the Kafka cluster-id, as opposed to, say, URLs or bootstrap servers, is that all observers can agree on the same id for a given Kafka cluster, independently of how they access it, for example from within or outside the Kubernetes cluster.

**Comment by lga-zurich** [comment]
[This is a sketch](https://github.com/lga-zurich/strimzi-kafka-operator/commit/4130be9d20765f9cd6a2c88392d79c7ea93a1436) of what would be required (apologies for the crude code, it is just to show how I understand this could be done).

**Comment by scholzj** [comment]
I think it looks good overall. I wonder if you should just use the bootstrap service instead of building the address from the pods. But I think that is a details.

**Comment by lga-zurich** [comment]
Resolved by #4123
