### ISSUE TITLE
Unable to scale add partitions to PVC in kafka brokers

### ISSUE THREAD

**Issue by saloni-2404** [strimzi/strimzi-kafka-operator#4029]
Hi,
Trying to add partition to PVC like below:
storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
          - id: 1
            type: persistent-claim
            size: 10Gi
            deleteClaim: false

Adding a id:2 but its not reflecting, it shows up in pending state and describe shows:

data-2-vkcluster1-kafka-0     Bound     pvc-f8d6ac0a-04a8-4dc3-b9b4-4cdba9665a21   10Gi       RWO            standard       9h
data-2-vkcluster1-kafka-1     Pending                                                                        standard       9h
data-2-vkcluster1-kafka-2     Pending                                                                        standard       9h

The describe still shows:
Events:
  Type    Reason                Age                       From                         Message
  ----    ------                ----                      ----                         -------
  Normal  WaitForFirstConsumer  2m34s (x1823 over 7h37m)  persistentvolume-controller  waiting for first consumer to be created before binding

Is there a solution for this?

**Comment by scholzj** [comment]
Sorry, but this is hard to answer without seeing the full logs and Kubernetes resources. Were the pods rolled to mount the volumes? What state are they and the StatefulSet in? Could it be related to #3136?

**Comment by saloni-2404** [comment]
The step 7 in issue #3136, adding jbod, that is what I am trying to achieve but it does not reflect when i check pvc. Pvc shows in pending state with describe as 
Normal WaitForFirstConsumer 2m34s (x1823 over 7h37m) persistentvolume-controller waiting for first consumer to be created before binding

**Comment by scholzj** [comment]
That why I asked about the pods!

**Comment by saloni-2404** [comment]
Kafka broker pods are in running state, 
Describing stateful set, 
Mounts:
      /opt/kafka/broker-certs from broker-certs (rw)
      /opt/kafka/client-ca-certs from client-ca-cert (rw)
      /opt/kafka/cluster-ca-certs from cluster-ca (rw)
      /opt/kafka/custom-config/ from kafka-metrics-and-logging (rw)
      /var/lib/kafka/data-0 from data-0 (rw)
      /var/lib/kafka/data-1 from data-1 (rw)
      /var/opt/kafka from ready-files (rw)

Volume Claims:
  Name:          data-0
  StorageClass:
  Labels:        <none>
  Annotations:   <none>
  Capacity:      10Gi
  Access Modes:  [ReadWriteOnce]
  Name:          data-1
  StorageClass:
  Labels:        <none>
  Annotations:   <none>
  Capacity:      10Gi
  Access Modes:  [ReadWriteOnce]

Even though kubectl get pvc shows:
data-2-vkcluster1-kafka-0     Bound     pvc-f8d6ac0a-04a8-4dc3-b9b4-4cdba9665a21   10Gi       RWO            standard       13h
data-2-vkcluster1-kafka-1     Pending                                                                        standard       13h
data-2-vkcluster1-kafka-2     Pending                                                                        standard       13h

**Comment by scholzj** [comment]
But were they rolled? Do the contain the new disks? What do the status for the STS ad Pods say? What is in the CO logs?

**Comment by saloni-2404** [comment]
Pods Status:        4 Running / 0 Waiting / 0 Succeeded / 0 Failed
Operator pod logs say:
2020-12-01 20:10:00 INFO  OperatorWatcher:40 - Reconciliation #566(watch) Kafka(kafka-pvc-partition-test/vkcluster1): Kafka vkcluster1 in namespace kafka-pvc-partition-test was MODIFIED
2020-12-01 20:10:00 INFO  AbstractOperator:122 - Reconciliation #566(watch) Kafka(kafka-pvc-partition-test/vkcluster1): Kafka vkcluster1 should be created or updated
2020-12-01 20:10:22 INFO  KafkaSetOperator:114 - Scaling down from 4 to 3
2020-12-01T20:10:24.190+0000: 49357.370: [GC (Allocation Failure) [PSYoungGen: 40757K->2324K(40960K)] 108098K->69681K(202752K), 0.0054924 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2020-12-01 20:11:48 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace kafka-pvc-partition-test...
2020-12-01 20:11:48 INFO  AbstractOperator:122 - Reconciliation #568(timer) Kafka(kafka-pvc-partition-test/cluster1): Kafka cluster1 should be created or updated
2020-12-01T20:11:49.287+0000: 49442.467: [GC (Allocation Failure) [PSYoungGen: 40724K->2213K(41472K)] 108081K->69586K(203264K), 0.0049084 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
2020-12-01 20:11:50 INFO  AbstractOperator:262 - Reconciliation #568(timer) Kafka(kafka-pvc-partition-test/cluster1): reconciled
2020-12-01 20:11:58 WARN  AbstractOperator:193 - Reconciliation #567(timer) Kafka(kafka-pvc-partition-test/vkcluster1): Failed to acquire lock lock::kafka-pvc-partition-test::Kafka::vkcluster1 within 10000ms.

**Comment by scholzj** [comment]
Please share the full log of the operator from beginning (ideally on the DEBUG level) and the YAMLs for the STSs, Pod, PVCs and the full Kafka CR. You should be able to use the Report tool (https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) to collect these.

**Comment by saloni-2404** [comment]
[strimzi-logs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625338/strimzi-logs.txt)

[operator yaml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625362/operator.yaml.txt)
[kafka yaml.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625363/kafka.yaml.txt)

**Comment by scholzj** [comment]
So, can you do following commands in the namespace where you run this and share the output?
* `kubectl get sts -o yaml`
* `kubectl get pod -o yaml` 
* `kubectl get pv -o yaml` 
* `kubectl get pvc -o yaml` 
* `kubectl get service -o yaml`

**Comment by saloni-2404** [comment]
The cluster we are referring to is: vkcluster1
[service.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625467/service.txt)
[pod.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625469/pod.txt)
[pv.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625470/pv.txt)
[pvc.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625471/pvc.txt)
[sts.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5625472/sts.txt)

**Comment by scholzj** [comment]
So the YAMLs make it a bit clear to me probably. It looks like at some point, you enabled in the Kafka cluster the `loadbalancer` type listener. And that does not seem to work because your cluster is not provisioning the loadbalancers:

```
2020-12-01 20:33:48 INFO  AbstractOperator:122 - Reconciliation #590(timer) Kafka(kafka-pvc-partition-test/vkcluster1): Kafka vkcluster1 should be created or updated
2020-12-01 20:38:50 ERROR Util:85 - Exceeded timeout of 300000ms while waiting for Service resource vkcluster1-kafka-external-bootstrap in namespace kafka-pvc-partition-test to be ready
2020-12-01 20:38:50 WARN  KafkaAssemblyOperator:1821 - Reconciliation #590(timer) Kafka(kafka-pvc-partition-test/vkcluster1): No loadbalancer address found in the Status section of Service vkcluster1-kafka-external-bootstrap resource. Loadbalancer was probably not provisioned.
2020-12-01 20:38:50 ERROR AbstractOperator:124 - Reconciliation #590(timer) Kafka(kafka-pvc-partition-test/vkcluster1): createOrUpdate failed
io.vertx.core.impl.NoStackTraceThrowable: No loadbalancer address found in the Status section of Service vkcluster1-kafka-external-bootstrap resource. Loadbalancer was probably not provisioned.
2020-12-01 20:38:50 WARN  AbstractOperator:268 - Reconciliation #590(timer) Kafka(kafka-pvc-partition-test/vkcluster1): Failed to reconcile
io.vertx.core.impl.NoStackTraceThrowable: No loadbalancer address found in the Status section of Service vkcluster1-kafka-external-bootstrap resource. Loadbalancer was probably not provisioned.
```

I assume only later you added the 3rd disk to the JBOD array. But because the load balancers do not work, the operator never got to apply the disk change. So as you can see in the STS YAML, it still has only 2 disks per broker.

You need to fix the problem with the load balancers (by either getting them created or by removing the listener to get them deleted) and then I would expect it gets through to apply the disk changes.

If you do `kubectl get kafka -o yaml`, you should see that the current state of the cluster in the Kafka CR is not as `Ready` but has the error instead.

**Comment by saloni-2404** [comment]
You are right, Jakub. That was due to load balancer not being provisioned, having removed that, no longer seeing the error.
Now trying to resize pvc, this time seeing pvcs in pending state, and one of the kafka brokers is no longer running:

From operator logs:
2020-12-02 05:01:59 ERROR Util:85 - Exceeded timeout of 300000ms while waiting for Pods resource cluster1-kafka-1 in namespace kafka-pvc-partition-test to be ready
2020-12-02 05:01:59 WARN  KafkaRoller:445 - Error waiting for pod kafka-pvc-partition-test/cluster1-kafka-1 to become ready: io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Pods resource cluster1-kafka-1 in namespace kafka-pvc-partition-test to be ready
2020-12-02 05:01:59 ERROR AbstractOperator:124 - Reconciliation #1104(watch) Kafka(kafka-pvc-partition-test/cluster1): createOrUpdate failed

From kafka yaml:
status:
  conditions:
  - lastTransitionTime: 2020-12-02T04:56:57+0000
    message: Error while waiting for non-restarted pod cluster1-kafka-1 to become
      ready
    reason: FatalProblem
    status: "True"
    type: NotReady

Attaching the logs/command outputs again:
[operator-logs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5627122/operator-logs.txt)
[pod-new.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5627123/pod-new.txt)
[pv-new.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5627124/pv-new.txt)
[pvc-new.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5627129/pvc-new.txt)
[service-new.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5627133/service-new.txt)
[sts-new.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5627134/sts-new.txt)

**Comment by scholzj** [comment]
Can you share the Kafka CR and describe what you changed to resize the volume?

**Comment by scholzj** [comment]
From the logs it looks like you tried to add the volume to the `cluster1` => but your storage provisioner did not created the volumes and that is why they are in Pending.

**Comment by saloni-2404** [comment]
Sure Jacob, 
the yaml is same as the one i provided, i changed 
storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
          - id: 1
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
          
To:

storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
          - id: 1
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
          - id: 2
            type: persistent-claim
            size: 10Gi
            deleteClaim: false

**Comment by scholzj** [comment]
You provided the Kafka CR for `vkcluster1`. But now you seem to have problem with `cluster1`. In any case, the changes you described above are not resizing volume but adding another volume once again. So it looks like what I said above. You should also check the Kubernetes events if they say any reasons.

**Comment by saloni-2404** [comment]
Yeah, it says something about
VolumeBindingMode:     WaitForFirstConsumer

**Comment by scholzj** [comment]
Then check the StatefulSet why is it not starting the pod.

**Comment by saloni-2404** [comment]
There is a warning:
Warning  FailedUpdate  36m (x5 over 5h56m)  statefulset-controller  update Pod cluster1-kafka-0 in StatefulSet cluster1-kafka failed error: Pod "cluster1-kafka-0" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)

**Comment by scholzj** [comment]
Right, so that is from #3136 ... the workaround is to delete the pods in order or just delete all of them at once and let the STS recreate them.

**Comment by saloni-2404** [comment]
That seemed to work, Jakub!
Deleted the pods together, then all came back up and pvc got bound.
Thank you.

**Comment by scholzj** [comment]
Yeah, so that confirms it was #3136

**Comment by saloni-2404** [comment]
Yes!

**Comment by saloni-2404** [comment]
Thanks again Jakub, closing the issue

**Comment by scholzj** [comment]
Great. Glad we got this sorted out ;-)
