### ISSUE TITLE
[Enhancement] Make it possible to configure KUBERNETES_SERVICE_DNS_DOMAIN and other env vars in Helm Charts

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4031]
As discussed in #3999, it would be good to be able to overwrite in Helm Charts `KUBERNETES_SERVICE_DNS_DOMAIN` (and possibly other environment variables). Currently, only some of them seem to be covered by variables and can be easily configured.

**Comment by ShubhamRwt** [comment]
The Kubernetes_Service_DNS_Domain and other env variables like `STRIMZI_CONNECT_BUILD_TIMEOUT_MS` , `STRIMZI_NETWORK_POLICY_GENERATION are now made configurable.Most of the required env vars in the Helm charts are now covered

**Comment by scholzj** [comment]
Reopening a the PR didn't actually added `KUBERNETES_SERVICE_DNS_DOMAIN`. @ShubhamRwt do you plan to continue with this?

**Comment by ShubhamRwt** [comment]
Yeah I will work on it
