### ISSUE TITLE
[Upgrading from Kafka 17 to 20 via any intermediate versions without impacting any of the running kafka applications] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#4036]
Hi Scholzj,

We have a situation within our cluster for which we need your inputs. 

1) Currently we have Operator version:17 deployed with Kafka:2.4.0, with this combination we have more than 25 namespaces under which the Kafka application(s) are running. 

2) Now the requirement is to have an upgrade to Operator:20 with Kafka:2.6.0, Challenge here is if we update the CRD's/ClusterRoleBindings within the existing cluster the previous applications running on 2.4.0 would be impacted as it is an unsupported version for Operator:20. 

So to achieve this smoothly, Do we have any intermediate version like 18/19 which still supports 2.4.0, and then without hampering the existing applications, it can be upgraded to 20?

Let me know your experienced thoughts.

**Comment by scholzj** [comment]
The list of supported versions is here: https://strimzi.io/downloads/ ... from it it looks like 0.19 still supports 2.4.0.

**Comment by vperi1730** [comment]
That's good news for me. Now moving from 19 to 20 without impacting the existing applications, Do we have any workaround/intermediate way?. Idea is to retain whatever existed so far.

**Comment by scholzj** [comment]
TBH, I'm not sure I fully understand the problem. Is it that you have25 Kafka clusters running 2.4.0 and you need to update just one of them to 2.6.0?

**Comment by vperi1730** [comment]
Yes - There are around 25 Kafka clusters running on 2.4.0, An upgrade to operator 20 would impact all these running clusters due to the version unsupported.  Isn't it?, Wanted to know if there can be any workaround. 

Hope my question is clear.

**Comment by scholzj** [comment]
There is no good solution because Kubernetes is not really multitenant => So you can have only one set of CRDs, cluster roles etc.

You can in theory install multiple operators => each watching different namespace (or set of namespaces). You would need to make sure to always use CRDs and latest ClusterRoles from the newest version you use. You would also need to do some renaming of the ClusterRoleBindings to not conflict.

It is not something tested and not something what is guaranteed to work with every version and it is probably a bit risky to maintain (e.g. deleting one of them including the CRDs wipes the other one as well etc.). But I think 0.19 and 0.20 could coexist like this. That is probably the only way to do this.

**Comment by vperi1730** [comment]
OK, thanks for the information.

Here is our simple use case.

1) We have a few Kafka clusters that are running on 0.17.0+2.4.0, Now we would like to migrate these clusters to 0.20.0+2.6.0.

Can you suggest to us the appropriate way to achieve this?

**Comment by scholzj** [comment]
I do not think that is easy. The best way is really to move to 0.19 and migrate all of them to 2.5 and then move to to 0.20 and migrate them to 2.6.

**Comment by vperi1730** [comment]
This makes sense, thanks Scholzj. I will try this use case in one of my clusters and will update you by EOD for further updates.

**Comment by vperi1730** [comment]
Just another ask as part of this migration activity, I would like to understand the following areas.

1) Will there be any interruption in the traffic flow of data from/to Kafka?
2) Will there be any challenge in the existing topics. it's partitions and data that is already existing???

The reason for these questions is while upgrade the Kafka cluster would restart due to either CRD changes/application version change.

Let me know your thoughts on this.

**Comment by scholzj** [comment]
In general not. There will be rolling updates of course, but they should not impact the availability of the clusters. But you should of course ideally try it first in some test environment since every environment and setup is slightly different.

**Comment by vperi1730** [comment]
I agree.
