### ISSUE TITLE
How can we restore a deleted PV in Kafka? I was supposed to delete the PV of an old version but I accidentally deleted the latest version's PV. One of the PVs of zookeeper got deleted, how can I get it back?

### ISSUE THREAD

**Issue by rajdeep44** [strimzi/strimzi-kafka-operator#4040]

**Comment by scholzj** [comment]
That depends on your infrastructure. But in most cases, when you delete a PV it is deleted and gone. If you delete the PVC, it should recreate and start with empty disk which should re-sync from the other nodes.

**Comment by rajdeep44** [comment]
They are back once I restarted the cluster.
