### ISSUE TITLE
Unable to add finalizer to loadbalancer service

### ISSUE THREAD

**Issue by saloni-2404** [strimzi/strimzi-kafka-operator#4046]
On deleting the loadbalancer, the forwarding rules do not get cleaned up.
So we tried to add the finalizer service.kubernetes.io/load-balancer-cleanup like this in kafka.yaml

kafka:
      version: 2.4.0
      replicas: 3
      template:
        bootstrapService:
          metadata:
            finalizers:
              - service.kubernetes.io/load-balancer-cleanup
        brokersService:
          metadata:
            finalizers:
              - service.kubernetes.io/load-balancer-cleanup 

Still not able to see it when we describe service

**Comment by scholzj** [comment]
The `template` section supports only selected fields which are supported by Strimzi and finalizers are not among them. You can check the docs to see what is supported: https://strimzi.io/docs/operators/latest/full/using.html#assembly-customizing-kubernetes-resources-str

**Comment by saloni-2404** [comment]
ok sure Jakub, that helps! thank you.
