### ISSUE TITLE
How to delete older consumer offset

### ISSUE THREAD

**Issue by saloni-2404** [strimzi/strimzi-kafka-operator#4049]
How to delete _consumer_offset if we deploy fresh instances of producer and consumer I can see after deploying fresh instance of producer and consumer we are still seeing messages present in partitions

**Comment by scholzj** [comment]
I'm not sure I fully understand the question. The offsets for individual groups fro `__consumer_offset` topic are normally not deleted but restarted using the `kafka-consumer-groups.sh` Kafka tool.

**Comment by saloni-2404** [comment]
I have deleted the whole kafka-cluster, redeployed again still I can see:
[kafka@kafka-cluster-kafka-0 kafka]$ bin/kafka-topics.sh --zookeeper localhost:2181 --list
__consumer_offsets
ultra-annotations

**Comment by saloni-2404** [comment]
Also Jakub,

Even the Kafka cluster is up and running, I can't see
a. tmp/zookeeper: zookeeper directory not created.
b. log.dirs=/tmp/kafka-logs: Kafka-logs directory not created.

When the above directories will be created?

**Comment by scholzj** [comment]
> Even the Kafka cluster is up and running, I can't see
a. tmp/zookeeper: zookeeper directory not created.
b. log.dirs=/tmp/kafka-logs: Kafka-logs directory not created.

These directories are not used. If you see them in the Kafka config file keep in mind that it is not used at all in Strimzi.

> I have deleted the whole kafka-cluster, redeployed again still I can see:

That depends on how you deleted the Kafka cluster. Did you deleted the KafkaTopic resources? Have you deleted all the PVs?

**Comment by saloni-2404** [comment]
thanks Jakub that helped..
