### ISSUE TITLE
[Question] ... 

### ISSUE THREAD

**Issue by coloal** [strimzi/strimzi-kafka-operator#4054]
I have deployed a Kafka cluster and a Kafka Connect cluster in kubernetes, using Strimzi and AKS. And I wanted to start reading from RSS resources to feed my Kafka cluster, so I created a connector instance of "org.kaliy.kafka.connect.rss.RssSourceConnector" which reads from a specific RSS feed, given an url, and writes to a specific topic. But my whole intention with this is to eventually have a Kafka Connect cluster able to manage a lot of external requests of new RSSs to read from; and here is where all my doubts come in:

Shoud I create an instance of Kaliy RSS connector for each RSS feed? Or would it be better to implement my own connector, so I create only one instance of it and each time I want to read a new RSS feed I would create a new Task in the connector?
Who should be resposible of assuring the Kafka Connect Cluster state is the desired one? I mean that if a Connector(in the case of 1 RSS feed : 1 Connector instance) stopped working, who should try to start it again? An external client via the Kafka Connect REST API? The strimzi operator itself via KafkaConnector custom resource?
Right now, I think my best option is to rely on Kafka Connect REST API making the external client responsible of managing the state of the set of connectors, but I don't know if these was designed to recieve a lot of requests as it would be the case. Maybe these could be scaled by provisioning several listeners in the Kafka Connect REST API configuration but I do not know. Thanks a lot!

**Comment by scholzj** [comment]
First of all, I know nothing about the connector you mentioned, I never used it and never heard about it (I never looked for RSS connectors, so I do not mean it in any bad way). So maybe asking the author(s) about how they recommend to use it might be a good start as they have a lot more experience with it.

Do I understand it right that you want to use it for regular RSS feeds from websites? I honestly wonder if using Kafka Connect would be the right approach for it. Regardless of whether you do it as separate connectors or separate tasks, I think that it would create a big overhead from running the connectors / tasks compared to how much the actual connector would do. I think implementing it as some regular application without Kafka Connect might be much more efficient.

**Comment by coloal** [comment]
My question is more about: if I want my KafkaConnect cluster to create a lot of Connectors based on the requests another service will make, should I implement it so these external service is responsible for the Connectors state(via the API REST) or should It be my Kafka cluster operator(in which case I will be creating a KafkaConnector resource for each request of a connector creation)?

**Comment by scholzj** [comment]
I do not think anyone tested the Connector operator for 1000s of connectors for example. So the REST API will be safer bet.
