### ISSUE TITLE
[Bug] The class method is not defined.

### ISSUE THREAD

**Issue by AllenZMC** [strimzi/strimzi-kafka-operator#4060]
**Describe the bug**
See the following code, ` .withMetricsConfig(spec.getMetricsConfig())` method cannot be called.

All places where this method is called are not defined.

```
return new KafkaConnectSpecBuilder()
                .withBootstrapServers(connectCluster.getBootstrapServers())
                .withTls(connectTls)
                .withAuthentication(connectCluster.getAuthentication())
                .withConfig(connectCluster.getConfig())
                .withLogging(spec.getLogging())
                .withReplicas(spec.getReplicas())
                .withVersion(spec.getVersion())
                .withImage(spec.getImage())
                .withResources(spec.getResources())
                .withLivenessProbe(spec.getLivenessProbe())
                .withReadinessProbe(spec.getReadinessProbe())
                .withJvmOptions(spec.getJvmOptions())
                .withMetrics(spec.getMetrics())
                .withMetricsConfig(spec.getMetricsConfig())
                .withTracing(spec.getTracing())
                .withAffinity(spec.getAffinity())
                .withTolerations(spec.getTolerations())
                .withTemplate(spec.getTemplate())
                .withExternalConfiguration(spec.getExternalConfiguration())
                .build();
```

**Comment by scholzj** [comment]
I think you will need to share more information ... what version are you using, what is the error etc. You would also need to share the whole code. We need to know what `spec` is and what does it contain etc.

**Comment by AllenZMC** [comment]
The version is master.   And the code in strimzi-kafka-operator/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaMirrorMaker2Cluster.java

`withMetricsConfig ()` method is not defined, Because I cannot search for the definition of this method in intellij idea.
Idea reported an unresolvable error, see `Cannot resolve method 'withMetricsConfig' in 'KafkaConnectSpecBuilder'` .

I'm not sure if it is a problem, but I searched this method in the whole project and found no definition.

**Comment by scholzj** [comment]
Ok, so you are trying to build / customize Strimzi? I guess it is missing the files generated at compile time from the different classes. So I think you should build the project and then the methods will be there.

**Comment by AllenZMC** [comment]
Sorry, I have built the project and I am also very strange.

**Comment by scholzj** [comment]
If you have build it, the this should be in the `generated-sources` in the `api` module. My Idea sees that out of the box. Maybe yours has some different configuration and does not see the files?

**Comment by scholzj** [comment]
@AllenZMC Did you managed to resolve this and load the generated classes?
