### ISSUE TITLE
maximum limit of messages can Kafka operator hold

### ISSUE THREAD

**Issue by saloni-2404** [strimzi/strimzi-kafka-operator#4061]
In Kafka-Operator we have created 12 partitions, so we want to know how many messages do a single partition can hold like max limit in size or in general what is the maximum limit of messages can Kafka operator hold.

**Comment by scholzj** [comment]
The operator does not hold any messages. It just operates Apache Kafka. Any topics or partitions exist in apache Kafka and store the data there. So this all depends on how you sized and configured your Apache Kafka brokers and the topics/partitions.

**Comment by saloni-2404** [comment]
Okay, and there is no limit on the number of brokers, partitions?

**Comment by scholzj** [comment]
Not any imposed by Strimzi. Strimzi just deploys Kafka -> we use the official released binaries of Apache Kafka and orchestrate it. There are certainly limits to what Kafka brokers can handle, but it will depend on your sizing, infrastructure etc.

**Comment by saloni-2404** [comment]
got it now Jakub, thanks a lot!
