### ISSUE TITLE
strimzi kafka benchmark test

### ISSUE THREAD

**Issue by lanzhiwang** [strimzi/strimzi-kafka-operator#4062]
I want to perform performance testing after installing strimzi kafka operator. I use the [openmessaging-benchmark](https://github.com/openmessaging/openmessaging-benchmark) tool. Currently the tool can get data normally. I want to compare your performance test data and methods. Have you ever done similar work? What if you did it, and what was the result?

**Comment by scholzj** [comment]
I don't think I ever used the OpenMessaging benchmark. So I do not have any results to share I'm afraid. But it seems to be getting more and more popular lately.
