### ISSUE TITLE
Deployment with custom listener certs

### ISSUE THREAD

**Issue by saloni-2404** [strimzi/strimzi-kafka-operator#4067]
We want to manage the external listener certs ourselves, and have the operator support mapping of encrypted files into secrets in the namespace of the cluster. In general we need multiple sets of these files to secrets mappings because of MirrorMaker also. 
Any suggestions on this?

**Comment by scholzj** [comment]
Sorry, I'm not sure I understand the question. Using your own listener certificates is documented here: https://strimzi.io/docs/operators/latest/full/using.html#kafka-listener-certificates-str

**Comment by saloni-2404** [comment]
Thanks for the link, have I understood the documentation correctly:
We need to deploy a cluster with default config and then to the running cluster's namespace, add the secret and refer to that in kafka cr and then update it?

**Comment by saloni-2404** [comment]
I also tried to apply the secret to another namespace and deploy over there, i was able to. Is it working as expected?

**Comment by saloni-2404** [comment]
I'm confused if its working because in the second scenario where i tried in a new namespace, and applied the secret before, then deployed i still see these secrets:
cluster2-clients-ca                                 Opaque                                1      16m
cluster2-clients-ca-cert                            Opaque                                3      16m
cluster2-cluster-ca                                 Opaque                                1      16m
cluster2-cluster-ca-cert                            Opaque                                3      16m
cluster2-cluster-operator-certs                     Opaque                                4      16m
cluster2-entity-operator-certs                      Opaque                                4      13m
cluster2-entity-operator-token-hjctn                kubernetes.io/service-account-token   3      14m
cluster2-kafka-brokers                              Opaque                                12     14m
cluster2-kafka-exporter-certs                       Opaque                                4      13m
cluster2-kafka-exporter-token-l6pv8                 kubernetes.io/service-account-token   3      13m
cluster2-kafka-token-pr496                          kubernetes.io/service-account-token   3      14m
cluster2-zookeeper-nodes                            Opaque                                12     15m
cluster2-zookeeper-token-cn25j                      kubernetes.io/service-account-token   3      16m
default-token-vtz6d                                 kubernetes.io/service-account-token   3      29m
kafka-operator-token-r2xsf                          kubernetes.io/service-account-token   3      29m
my-cert-secret                                      Opaque                                2      22m
sh.helm.release.v1.kafka-operator-0-1607509910.v1   helm.sh/release.v1                    1      28m

I created the secret my-cert-secret.
So how can i be sure which certs are being used?

**Comment by scholzj** [comment]
> We need to deploy a cluster with default config and then to the running cluster's namespace, add the secret and refer to that in kafka cr and then update it?

No, you do not need to deploy anything with default settings. You can just create the secret and refer it in the YAML which you create from the beginning. If you have the cluster running, you can of course edit the Kafka CR as well to add it. But you can set it up right from the beginning if your cluster is not deployed yet.

> So how can i be sure which certs are being used?

You check the status and the logs for errors and if there are not any, you are fine. You can also use `openssl s_client` to actually see what certificate is used on the broker.

> i still see these secrets

They do not disappear. they are still used for encrypting all the internal communication. You asked about how to configure the listener certificate => so you configured a listener certificate. It applies just for the listener where you configured it. If you want to use your certificates for everything, you can provide a custom CA: https://strimzi.io/docs/operators/latest/full/using.html#installing-your-own-ca-certificates-str ... but it needs to be a CA so it is a bit more complicated. The CA will be used to generate the server certificates, so the secrets will be still there. But signed by your CA.

**Comment by saloni-2404** [comment]
Hey Jakub,
I see some warnings in the operator logs, attaching the logs..
Is this because of the certs?
[custom-cert-operator-logs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/5665975/custom-cert-operator-logs.txt)

**Comment by scholzj** [comment]
No, I do not see any relevant warnings there.

**Comment by saloni-2404** [comment]
Okay, then we should be good.
Thank you so much for the help Jakub..

**Comment by saloni-2404** [comment]
Jakub, is there any way I can check this is working? By producing/consuming? We have replaced the listener certs, so how can we check

**Comment by saloni-2404** [comment]
eg while connecting we do:
kubectl get secrets -n kafka-cert-test-custom  -o jsonpath='{.data.ca\.crt}' | base64 -id > ca.crt

2: keytool \
  -import \
  -file ca.crt  \
  -keystore client.truststore.p12 \
  -alias ca \
  -storepass 1234567 \
  -noprompt
  
3: ls -l
   clients.truststore.p12

So that still uses the operator created ca certs. where do we actually check for use of listener certs?

**Comment by scholzj** [comment]
As I suggested above, you can just use `openssl s_client` to connect and list the certificates. There you should see your own certificate. And in general, if your Kafka clients connect with having a truststore containing just your own CA, that also means it worked fine,
