### ISSUE TITLE
Does kafka client need signed certificate to connect external listener? 

### ISSUE THREAD

**Issue by wuzm2k05** [strimzi/strimzi-kafka-operator#4091]
I use strimzi operator to install a kafka cluster with LB external type, since I want to connect kafka broker from outside of k8s.
I saw "listener.name.external-9094.ssl.client.auth=required" in broker's properties file, so I think kafka client need a certificate signed by client CA. However I didn't see that kind of information (client need certificate) in "using strimzi 0.19" document. 
So does kafka client need signed certificate to connect external listener?

**Comment by scholzj** [comment]
`listener.name.external-9094.ssl.client.auth=required` means TLS client authentication. When using Load Balancers, Both TLS client authentication as well as TLS ecnryption (and server authentication) are optional. If you configure the listener something like this:

```yaml
listeners:
  # ...
  external:
    type: loadbalancer
    tls: false
```

That way you can get it without any TLS.

If you just want to disable the TLS client authentication, you can remove this section:

```yaml
authentication:
  type: tls
```

You should probably also disable authorization if you have it enabled.

But assuming you want TLS which is normally recommended it works like this ...
* Strimzi is using its won _cluster_ CAs to signed the certificates for the brokers not just for the clients to connect but also to secure the internal communication.
* It has one additional _clients_ CA for issuing client certificates.

So by default, you would use these certificates. The server one (which foes into the truststore in your client) will be in a secret called `<cluster-name>-cluster-cert-ca`. The certificate for TLS client authentication can be created by creating a `KafkaUser` resource => that swill create a secret with the user key which should be used as keystore.

If you want, you can also provide your own CAs or you can provide your own server certificate which will be used just by the listener but will let Strimzi use its own CA for the internal communication.

**Comment by wuzm2k05** [comment]
thanks! I will try both( disable tls/authentication and certificates).
