### ISSUE TITLE
Drop strimzi Kafka unnecessary metric

### ISSUE THREAD

**Issue by cloudcafetech** [strimzi/strimzi-kafka-operator#4097]
In 24 hours strimzi consumed more than 5 GB storage data for Prometheus metric.

Please help me to drop strimzi Kafka unnecessary metric.

**Comment by scholzj** [comment]
You can disable the Kafka metrics in the Kafka custom resource by removing the `metrics` section.

**Comment by cloudcafetech** [comment]
Don't want to disable but keep those metric which is using only Grafana dashboard (already listed down those) and rest of metric wanted to drop/remove.

**Comment by scholzj** [comment]
You can then configure the JMX Exporter in the `metrics` section. TBH I do not know if you can disable some metrics that way or not.

**Comment by cloudcafetech** [comment]
Big challenge, let me check with Prometheus operator community.
