### ISSUE TITLE
Cruise control spawns two processes. 

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#4113]
If you apply a kafka cluster: `k -n namespace apply -f kafka-persistent.yaml`
In this case, cruise control doesn't come up because it continuously OOMs for some reason. 
Then you reapply or replace the cluster: `k -n namespace replace -f kafka-persistent.yaml`
I'm on strimzi 0.20 and EKS. 5 zookeepers  and 25 Brokers. 

I think this could be related to: https://github.com/strimzi/strimzi-kafka-operator/issues/4012#

You might end up with two cruise control processes. The second doesn't really run. How do I get ride of the second one for good house keeping? 

```
REDACT-strimzi-pro           kafka-cluster-cruise-control-5487d554fc-26xd4                     2/2     Running            1          120m
REDACT-strimzi-pro           kafka-cluster-cruise-control-5c75876696-dt2wm                     1/2     CrashLoopBackOff   24         91m
REDACT-strimzi-pro           kafka-cluster-entity-operator-7d77669c5f-v4pzr                    3/3     Running            0          3h3m
```

**Comment by scholzj** [comment]
That looks like some bug in Kubernetes. For the services running as deployments, Strimzi only creates the deployment. The rolling updates and management of replica sets are done by Kubernetes. 

But actually, in your case the crash-looping pod is the newer one and the running is the old one. If that is the case (i.e. the other way around then you describe it?), the old pod might not be removed until the new one is ready. So it might not be bug anywhere. You just need to find out why the new one is crash-looping maybe and fix it?

**Comment by jrivers96** [comment]
I gave it 2Gi memory limits and the crashing pod terminated, another pod started/ran properly, and the extra pod terminated.
