### ISSUE TITLE
Generate v1beta2 resources

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#4120]
As part of https://github.com/strimzi/proposals/blob/master/009-crd-v1-roadmap.md#development we need to change the build in master so that we're generating `v1beta2` resources.

**Comment by ShubhamRwt** [comment]
Hello @tombentley. In the upcoming release of Strimzi, are we thinking of converting the api.extentions/v1beta1 to api.extensions/v1beta2 in the CRDs present in install folders?

**Comment by tombentley** [comment]
Hi @ShubhamRwt, the overall plan is described in the linked proposal and the next release should be what's described in that document as "Strimzi X". There are several strands of work involved in that, but it will introduce `kafka.strimzi.io/v1beta2` of the `Kafka` (and other) resources. The switch in the CRD API will be to `api.extentions/v1` in "Strimzi Z".

This issue is basically about reconfiguring the "crd generator" to actually generate CRDs which declare `v1beta2` versions with schemas (in addition to the v1alpha1 and v1beta1 which are already generated), but those CRDs will still use apiVersion: apiextensions.k8s.io/v1beta1 in the next release.

**Comment by ShubhamRwt** [comment]
Okay got it. Thanks
