### ISSUE TITLE
[Bug] Inconsistent use of CPU metric in our Grafana Dashbaords

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4135]
Most of our Grafana Dashboards have a chart for _CPU Usage_. But it looks like for some reason, each of the dashabords is using a different metrics for it. For example:

* Kafka dashboard is using `container_cpu_usage_seconds_total` (https://github.com/strimzi/strimzi-kafka-operator/blob/d407e36726b9c68bdddbc5fc7f1ae342ac787a4e/examples/metrics/grafana-dashboards/strimzi-kafka.json#L855). The same metrci seems to be used also for Zoo for example:
```
sum(rate(container_cpu_usage_seconds_total{namespace=\"$kubernetes_namespace\",pod=~\"$strimzi_cluster_name-$kafka_broker\",container=\"kafka\"}[5m])) by (pod)
```

* Connect is using `process_cpu_seconds_total` (https://github.com/strimzi/strimzi-kafka-operator/blob/d407e36726b9c68bdddbc5fc7f1ae342ac787a4e/examples/metrics/grafana-dashboards/strimzi-kafka-connect.json#L433):
```
rate(process_cpu_seconds_total{strimzi_io_kind=~\"KafkaConnect.*\",strimzi_io_cluster=\"$strimzi_connect_cluster_name\"}[1m])
```

I think we should ideally use the same metric in all dashboards to make sure it gives a consistent view.

**Comment by scholzj** [comment]
@ppatierno @sknot-rh I think this is easy to fix ... but which of these metrics is the right one which should be used?

**Comment by ppatierno** [comment]
so the `process_cpu_seconds_total` is actually provided out of the box by the Prometheus exporter (in case of Kafka Connect I guess the JMX exporter agent using it). The `container_cpu_usage_seconds_total` is provided by cadvisor. Conceptually they are the same but I would use the cadvisor one. I will fix it.
