### ISSUE TITLE
Add support for topologySpreadConstraints

### ISSUE THREAD

**Issue by pietervincken** [strimzi/strimzi-kafka-operator#4136]
**Is your feature request related to a problem? Please describe.**
In order to properly schedule our brokers, we want to be able to use the [topologySpreadConstraints ](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)feature added to Kubernetes in 1.19 (stable). This would allow us to easily schedule all components to increase the availability. Currently, support is limited to pod(anti) affinity, which doesn't our use case of providing a best effort in splitting instances across the zones. We have 3 zones available, we scale beyond 3 broker instances, it won't scale as it cannot find a valid failure domain to schedule the broker into.

**Describe the solution you'd like**
To make the solution a little bit more generic, a podTemplate approach could be used. Currently, it seems that the pod template solution used in strimzi in a "explicit include" instead of a general "podTemplate" (https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates) setup found in other operators. (Elastic on Cloud has a nice approach)

**Describe alternatives you've considered**
We tried to use the pod anti-affinity, but adding zone support to that means that we're limited to the amount of zones we have. 

**Additional context**
N/A

**Comment by scholzj** [comment]
I have it already on my todo list. Just need to get to it and see how it works on older versions.
