### ISSUE TITLE
Unclear expression

### ISSUE THREAD

**Issue by AllenZMC** [strimzi/strimzi-kafka-operator#4160]
**Suggestion / Problem**

See the document description below:
`Optional configuration for a Kafka listener certificate managed by an external Certificate Authority. The brokerCertChainAndKey specifies a Secret that contains a server certificate and a private key. You can configure Kafka listener certificates for both tls and external listeners.`
I think this sentence `You can configure Kafka listener certificates for both tls and external listeners.`  is not clear, it should be changed to `You can configure Kafka listener certificates for TLS listeners`, because `tls` can be `internal` or `external`.

**Documentation Link**
https://strimzi.io/docs/operators/master/full/using.html#assembly-config-kafka-str

**Comment by scholzj** [comment]
Looks like this was not updated in 0.20 when we changed the format of the listener configuration. You can of course use it with any listener which is using TLS encryption. I opened a PR #4161 to fix it - feel free to have a look and comment. Thanks for reporting.
