### ISSUE TITLE
[Question] Cannot completion installation in K8s provisioned by Rancher rke

### ISSUE THREAD

**Issue by scheung38** [strimzi/strimzi-kafka-operator#4169]
![Screenshot 2021-01-03 at 03 09 24](https://user-images.githubusercontent.com/1273014/103470929-18f0a780-4d71-11eb-92da-e5d190affe7e.png)
I have 3 Droplets in Digital Ocean, each of
Ubuntu 20  2 GB Memory / 50 GB

*Describe the bug**

**To Reproduce**
1. rke up
2. kubectl apply -f strimzi/sample.yaml -n kafka 

➜  ~ kubectl get pods -n kafka -w     
 
![Screenshot 2021-01-03 at 03 12 09](https://user-images.githubusercontent.com/1273014/103470956-7c7ad500-4d71-11eb-8bcd-d1c21fc460b3.png)

**Expected behavior**
Completion 

**Environment (please complete the following information):**
 - Strimzi version: 
 - Client Version: v1.20.1
 - Server Version: v1.19.4
-
 
 - Infrastructure: Rancher rke up

 
![Screenshot 2021-01-03 at 03 15 17](https://user-images.githubusercontent.com/1273014/103470986-eb582e00-4d71-11eb-8762-80dc5e0c582d.png)

Is this related to sufficient node resources?

**Comment by scholzj** [comment]
It is a bit weird when you open both issue and talk about it on Slack. What is your preferred channel?

**Comment by scheung38** [comment]
Sorry here is fine. 

Just not seem to be starting?

![Screenshot 2021-01-06 at 02 19 59](https://user-images.githubusercontent.com/1273014/103721490-ae847500-4fc5-11eb-898e-188ff8833721.png)

**Comment by scholzj** [comment]
If the pod is pending, one of the usual reasons for it is missing storage. From your configuration, the storage needs to be created by the default storage class - do you know if you have one? It could be also no capacity in your cluster etc. Can you run the following commands and share the output? That should help us find out more.

* `kubectl get pv`
* `kubectl get pvc`
* `kubectl get storageclass`
* `kubectl describe pod my-cluster-zookeeper-0`
* `kubectl describe statefulset my-cluster-zookeeper`

On your screenshot, you seem to have quite a lot of pods which seem to be in the same state, but judging by the name they do not belong to Strimzi.

**Comment by scholzj** [comment]
PS: 2GB RAM / 1 cpu seems to be very small to hold the worker node including Kafka. But that should not cause the pods pending. So that might be an issue you run into later.
