### ISSUE TITLE
[Question] Stuck after issuing command: kubectl apply -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka

### ISSUE THREAD

**Issue by scheung38** [strimzi/strimzi-kafka-operator#4184]
**Describe the bug**

**To Reproduce**

kubectl apply -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka

**Expected behavior**
Completion to installation

![Screenshot 2021-01-06 at 02 23 04](https://user-images.githubusercontent.com/1273014/103721652-1cc93780-4fc6-11eb-847a-5b469d3dff69.png)

**Environment (please complete the following information):**
 - Strimzi version:  0.20.1
 - Installation method:  kubectl apply -f 
 - Kubernetes cluster: 
 - 
![Screenshot 2021-01-06 at 02 29 11](https://user-images.githubusercontent.com/1273014/103722022-f8218f80-4fc6-11eb-92fb-4872dfbf4a82.png)

 - Infrastructure: multipass ubuntu 20 LTS   -cpu 1 -mem 1G -disk 5G

**Comment by scholzj** [comment]
I think you can use the `-v` option to get more output from kubectl. But most probably it gets stuck with creating the last mentioned resource or the next one. So you would probably need to look into the logs of your Kube components if they say something: API server etc.

**Comment by scheung38** [comment]
Thank you Jakub. Roughly how to size the nodes for Kafka? As these were created from multipass 
-cpu 1 -mem 1G -disk 5G

**Comment by scheung38** [comment]
What is Strimzi recommendations for minimum node resource when using Kafka as deployment

**Comment by scholzj** [comment]
I have no idea what multipass is. The amount of resources needed for Kafka depends on your use cases and they can be often quite big. I personally during development and testing give ~2GB of RAM for each broker and 1GB for each Zookeeper node. You might be fine with less. But keep in mind that from the node size, big chunk will be taken by the OS, Kubelet, and other system services and only part will be left for Kafka to use.
