### ISSUE TITLE
SASL SSL not working: failed authentication due to: Unexpected handshake request with client mechanism SCRAM-SHA-512, enabled mechanisms are 

### ISSUE THREAD

**Issue by bhushan558** [strimzi/strimzi-kafka-operator#4190]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**

I configured TLS as per Strimzi documentation, it works fine. However, when I use SASL_TLS and perform a producer consumer test from local machine, it fails with error failed authentication due to: Unexpected handshake request with client mechanism SCRAM-SHA-512

{kubeconfig } ~> cat client-scram-auth.properties
bootstrap.servers=xx.xx.xx:9094
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
ssl.truststore.location=/home/unix/kafka-cert/ca-cert/kafka.client.truststore.jks
ssl.truststore.password=atdweefefaq
ssl.endpoint.identification.algorithm=
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=kafka-scram-client-credentials password=BwEo4ob2XksQ;

Note-password is already base64 decoded.

When I test only with SSL, it works, here is the client config:

{kubeconfig } ~> cat client-ssl.properties
bootstrap.servers=10.216.129.218:9094
security.protocol=SSL
ssl.truststore.location=/home/unix/kafka-cert/ca-cert/kafka.client.truststore.jks
ssl.truststore.password=xxxxxx
ssl.endpoint.identification.algorithm=

**To Reproduce**
1. Create client-scram-auth.properties file as above (Note the spec.tls and spec.authenctication already set in Kafka cluster statefulset
2. CI try to run producer consumer to see if the message are going though. I get the error as mentioned in title.
3. kafka-console-producer.sh --broker-list $LOADBALANCER_PUBLIC_IP:9094 --topic $TOPIC_NAME --producer.config client-scram-auth.properties
4. Errors as below:
>[2021-01-06 16:46:52,453] ERROR [Producer clientId=console-producer] Connection to node -1 (1.2.3.4:9094) failed authentication due to: Unexpected handshake request with client mechanism SCRAM-SHA-512, enabled mechanisms are [] (org.apache.kafka.clients.NetworkClient)
[2021-01-06 16:46:55,025] ERROR [Producer clientId=console-producer] Connection to node -1 (1.2.3.4:9094) failed authentication due to: Unexpected handshake request with client mechanism SCRAM-SHA-512, enabled mechanisms are [] (org.apache.kafka.clients.NetworkClient)
[2021-01-06 16:46:57,736] ERROR [Producer clientId=console-producer] Connection to node -1 (1.2.3.4:9094) failed authentication due to: Unexpected handshake request with client mechanism SCRAM-SHA-512, enabled mechanisms are [] (org.apache.kafka.clients.NetworkClient)

**Expected behavior**
It should allow me to post message on topic and consumer to consume it

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.11.1] 2.6.0
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io] Helm Chart
 - Kubernetes cluster: [e.g. Kubernetes 1.14, OpenShift 3.9] 1.14
 - Infrastructure: [e.g. Amazon EKS, Minikube] Kops

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
`apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
  namespace: kafka-strimzi
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512`
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

**Comment by scholzj** [comment]
Please read the instructions when opening the issues:
* Are you sure this is really a bug and not just some configuration issue for which a question in discussions or Slack would be more suitable?
* Can you provide the logs as asked in the instructions? You can use the report script to collect them all automatically. If you do not want to use it, please attach all Strimzi custom resources from your Kubernetes cluster so that they contain the status, version of the Strimzi operator you use, logs from the operators and Kafka brokers etc.

**Comment by Chatim94** [comment]
Hello,
I'm facing same issue with SASL/OAUTHBEARER mecanism.
@bhushan558  did you find solution ?
