### ISSUE TITLE
Support for Kafka 2.7.0

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#4231]
**Is your feature request related to a problem? Please describe.**
Need PEM format support for configuring TLS in kafka connect and connectors. 

**Describe the solution you'd like**
Kafka 2.7.0 adds the support for PEM http://kafka.apache.org/documentation.html#security_ssl

**Describe alternatives you've considered**
Alternative is to use JKS and PKCS12 which requires a lot of work and conversions to make Debezium connectors work with Kafka connect.

**Comment by scholzj** [comment]
Kafka 2.7.0 will be supported in 0.21.0. You can help by testing the 0.21.0-rc1: https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.21.0-rc1

**Comment by scholzj** [comment]
BTW: I will close this since it has been already implemented. If you have any follow up questions, we can continue in Discussions.

**Comment by alok87** [comment]
Thanks.

**Comment by alok87** [comment]
@scholzj I made kafka 2.6.0 from 0.20.1 strimzi, please suggest how to quickly move to 0.21.1.rc1 and use kafka 2.7

There should not be much changes.

**Comment by scholzj** [comment]
You should be able to just do the upgrade (with the caveat that this is just an RC - so be careful). You install the operator, let it roll the images and then you change the Kafka version in the custom resources.
