### ISSUE TITLE
Kafka brokers - CrashLoopBackOff - log.dirs empty

### ISSUE THREAD

**Issue by ananthk01** [strimzi/strimzi-kafka-operator#4243]
On my way to upgrading from strimzi 0.14 to 0.20, I am upgrading to 0.15, 0.17 and 0.19 before applying changes for 0.20. Stage 1, from 0.14 to 0.15, was smooth. Stage 2, from 0.15 to 0.17, is resulting in a CrashLoopBackOff for the kafka pods - the cluster operator and the zookeeper pods are started without issues. 

My end goal is to get to 0.20 now but I've seen that the recommendation is to not skip a version while upgrading. Does that hold good for this case? What is the recommendation on skipping this version upgrade from 0.15 to 0.17 and going straight from 0.15 -> 0.19 or even 0.15 -> 0.20 for that matter?

If it is recommended to go through 0.17 to get to 0.19, I have captured some information found below.

**Describe the bug**
The log.dir/dirs is not present and is causing the kafka pods to go in a CrashLoopBackOff state. It looks like the KAFKA_LOG_DIRS value is not set.

**Expected behavior**
Log path to be set and the kafka brokers to be started without issues.

**Environment (please complete the following information):**
 - Strimzi version: 0.15
 - Installation method: YAML
 - Kubernetes cluster: 
    `kubectl version`
    `kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}`
 - Infrastructure: Amazon EKS

**YAML files and logs**

We first apply the operator yaml (attached archive: operator.yaml) and wait for the rolling updates to finish - this is where the exception is seen. Then we apply the kafka yaml (attached archive: kafka.yaml).

[Archive.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5810422/Archive.zip)

Pod logs - exception - `kubectl logs -f kafka-kafka-1 kafka -n kafka`

```
KAFKA_BROKER_ID=1
KAFKA_LOG_DIRS=
Preparing truststore for replication listener
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/kafka/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for replication listener is complete
Looking for the right CA
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt
Preparing keystore for replication and clienttls listener
Preparing keystore for replication and clienttls listener is complete
Preparing truststore for clienttls listener
Adding /opt/kafka/client-ca-certs/ca.crt to truststore /tmp/kafka/clients.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for clienttls listener is complete
Starting Kafka with configuration:
broker.id=1
broker.rack=us-east-1a

# Listeners
listeners=REPLICATION://0.0.0.0:9091
advertised.listeners=REPLICATION://kafka-kafka-1.kafka-kafka-brokers.kafka.svc.cluster.local:9091
listener.security.protocol.map=REPLICATION:SSL
inter.broker.listener.name=REPLICATION
sasl.enabled.mechanisms=

# Zookeeper
zookeeper.connect=localhost:2181

# Logs
log.dirs=

# TLS / SSL
ssl.keystore.password=[hidden]
ssl.truststore.password=[hidden]
ssl.keystore.type=PKCS12
ssl.truststore.type=PKCS12
ssl.endpoint.identification.algorithm=HTTPS
ssl.secure.random.implementation=SHA1PRNG

listener.name.replication.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
listener.name.replication.ssl.truststore.location=/tmp/kafka/cluster.truststore.p12
listener.name.replication.ssl.client.auth=required





# Authorization configuration
authorizer.class.name=


# Provided configuration


OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
2021-01-13 17:44:33,953 INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$) [main]
2021-01-13 17:44:34,418 ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) [main]
java.lang.IllegalArgumentException: requirement failed: At least one log directory must be defined via log.dirs or log.dir.
	at scala.Predef$.require(Predef.scala:281)
	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1471)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1460)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
	at kafka.Kafka$.main(Kafka.scala:68)
	at kafka.Kafka.main(Kafka.scala)
```

**Comment by scholzj** [comment]
I'm not sure how did you do the upgrade. But your operator YAML in the attached ZIP is wrong. It seems to be mixing all kind of images from different releases. For example:

```
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.1.0=strimzi/kafka:0.14.0-kafka-2.1.0
            2.1.1=strimzi/kafka:0.14.0-kafka-2.1.1
            2.2.0=strimzi/kafka:0.14.0-kafka-2.2.0
            2.2.1=strimzi/kafka:0.14.0-kafka-2.2.1
            2.3.0=strimzi/kafka:0.14.0-kafka-2.3.0
            2.3.1=strimzi/kafka:0.15.0-kafka-2.3.1
            2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0
```

you have to use the installation file as it is => so for example for 0.17.0, it should have this:

```
        - name: STRIMZI_KAFKA_IMAGES
          value: |
            2.3.1=strimzi/kafka:0.17.0-kafka-2.3.1
            2.4.0=strimzi/kafka:0.17.0-kafka-2.4.0
```

This is what is causing your problems that you are mixing images from different versions together and the image from version X then for example expects to use a variable which does nto exist in version Y.

**Comment by ananthk01** [comment]
I see. Thanks for the quick response. I'll give this a go and provide an update.

**Comment by ananthk01** [comment]
@scholzj  Thank you very much. I was able to upgrade after that change!
