### ISSUE TITLE
Remove deprecated annotations

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4251]
As discussed and agreed on the Strimzi Community meeting on 14th January, the following annotations are deprecated and should be removed:
* `cluster.operator.strimzi.io/delete-claim`
* `operator.strimzi.io/generation`
* `operator.strimzi.io/delete-pod-and-pvc`
* `operator.strimzi.io/manual-rolling-update`

PR #4250 adds last warning in 0.22.0 release, 0.23 should be removed. This issue tracks the removal of the annotations.

**Comment by ShubhamRwt** [comment]
Hello @scholzj. Do we intend to remove the annotation for now because for 0.22.0 we are giving a last warning regarding the deprecated annotations?

**Comment by scholzj** [comment]
This should be removed only after 0.22 is released.

**Comment by ShubhamRwt** [comment]
Okay. Thank-you
