### ISSUE TITLE
Missing 0.20.1 images in Quay.io

### ISSUE THREAD

**Issue by LazyDBA247-Anyvision** [strimzi/strimzi-kafka-operator#4253]
Hi,
any reason for the missing operator / kafka  images **0.20.1**
https://quay.io/repository/strimzi/operator?tab=tags

https://quay.io/repository/strimzi/kafka?tab=tags

10x!

**Comment by scholzj** [comment]
They are not missing. They are in Docker Hub: https://hub.docker.com/u/strimzi. The move to Quay.io happened only after the 0.20.x release.
