### ISSUE TITLE
[DOC] Unable to create a KafkaConnector in a separate namespace from the KafkaConnect instance

### ISSUE THREAD

**Issue by fijshion** [strimzi/strimzi-kafka-operator#4264]
https://github.com/strimzi/strimzi-kafka-operator/blob/d484d4486ef8091f2c0b39f2a3d3ef036fd997b9/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java#L216

If I understand the above code, the strimzi.io/cluster (KafkaConnect instance) for a KafkaConnector resource must be in the same namespace. This doesn't seem to be documented anywhere. Other resources (e.g. KafkaTopic) can be created in a separate namespace from the Kafka instance. Is this the intended behavior? If so, can the operator be enhanced to support looking in separate namespaces, or is there some limitation I'm not aware of?

**Comment by scholzj** [comment]
This is intended behaviour. One of the problems is that we would need to somehow namespace the connectors etc. Another one would be that it complicates the RBAC setup. We would probably also need to change the label from just name of the cluster to also contain the namespace. I think that overall for the connectors, it is probably a significantly easier to implement it then for users or topics, but it is currently not in our plans. 

You could be right that it is not explicitly mentioned in the docs, that should be easier to fix.

With the topics it is possible to configure the _watched namespace_ in the Topic Operator. But it is still only one namespace and not the whole cluster.

**Comment by scholzj** [comment]
PS: If you want, we can track this as an enhancement for having the connectors in other namespaces and use other issue for the docs improvement. Just let me know _how much you want it_.

**Comment by fijshion** [comment]
Thanks for the quick replies! I'm cool with just documenting this limitation for now. This is only an issue in my test environment and I can work around it fairly easily.

**Comment by scholzj** [comment]
Ok, great. I changed it to documentation bug and we will get to it to make it more clear. Thanks.
