### ISSUE TITLE
Ability to add metadata to the operator pod.

### ISSUE THREAD

**Issue by raj-saxena** [strimzi/strimzi-kafka-operator#4278]
Right now, the [PodTemplate](https://strimzi.io/docs/operators/master/using.html#type-PodTemplate-reference) allows you to  add metadata (label/annotations) to different resources managed by the `operator`. 
However, the same doesn't seem to be possible for the `operator` itself deployed as [helm-chart](https://github.com/strimzi/strimzi-kafka-operator/tree/master/helm-charts/helm3/strimzi-kafka-operator#configuration). It does allow to add `tolerations` & `affinities`.

**Describe the solution you'd like**
Have an ability to add labels & annotations just like `tolerations` & `affinities`.

**Additional context**
We use Datadog as a logging platform and I actually needed this ability when during the investigation of https://github.com/strimzi/strimzi-kafka-operator/discussions/4276, I noticed that the `operator` exceptions logs are broken. This happens for Java logs and one way to solve the problem is to tell the log-extractor that a new line starts with a pattern by adding annotations. [Details](https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=kubernetes#multi-line-aggregation). While it would be nice to be able to configure `operator` to log as json, I believe, the ability to add metadata might help for broader use-cases.

**Comment by scholzj** [comment]
This is fine as an enhancement ... let's see if someone implements it. 

Just FYI: you can use the YAML files to install the operator which you can customize as much as you want including labels or annotations.

**Comment by scholzj** [comment]
I think we can close this - should be done in #4288
