### ISSUE TITLE
Add GC logging to Cluster Operator

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#430]
The cluster controller has currently no GC logging. We should add GC logging to have a better overview of what it does and how it handles memory.

**Comment by kyguy** [comment]
https://github.com/strimzi/java-docker-base/pull/2

**Comment by scholzj** [comment]
I think we will still need to rebuild the base image and push it to Docker Hub, so that it gets used.

@ppatierno You did that just last week while adding OpenSSL - can you do it here as well?
