### ISSUE TITLE
Installing Strimzi on Power architecture fails

### ISSUE THREAD

**Issue by VIjayHP** [strimzi/strimzi-kafka-operator#4324]
I have tried installing Strimzi on k8s cluster running on power architecture (ppc64le) using the command 
**kubectl apply -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka**
Error:
**kubectl logs strimzi-cluster-operator-68c6747bc6-72kmp -n kafka**
standard_init_linux.go:211: exec user process caused "exec format error"

Strimzi operator image (quay.io/strimzi/operator:0.21.1) is not a multi-arch image 
Any suggestions on this issue please?

**Comment by scholzj** [comment]
We do not support ppc64le architecture. If you want, you can try to build your own images for it:
* Add the links and checksums for ppc64 binaries to the Dockerfiles as done in #4256 for Arm64
* Follow this to build them using `docker buildx`: https://github.com/strimzi/strimzi-kafka-operator/blob/master/development-docs/DEV_GUIDE.md#building-container-images-for-other-platforms-with-docker-buildx

In general, we do not have any ppc64 environments for running the builds or testing, we cannot really support it. This is the same with regards to Arm64 mentioned above.
