### ISSUE TITLE
Add failure_reason label to the strimzi_resource_state metric

### ISSUE THREAD

**Issue by davidffrench** [strimzi/strimzi-kafka-operator#4327]
**Is your feature request related to a problem? Please describe.**
Currently, the strimzi_resource_state metric reports a boolean state to the readiness of a Kafka cluster. This means it is not currently possible to differentiate between a failed state and an in progress state.

**Describe the solution you'd like**
An easy solution to differentiate between a failed and in progress state is to add a label to the metric with a failure reason which gets added when the resource is in a failed state.

**Describe alternatives you've considered**
A separate metric or using a gauge metric with values for each different state. These are both unnecessary to solve the problem.

**Comment by sknot-rh** [comment]
Do I understand correctly you want the metric to look like this? 
```
strimzi_resource_state{container="strimzi-cluster-operator", endpoint="http", failure_reason="Version 2.8.0 is not supported. Supported versions are: 2.5.0, 2.5.1, 2.6.0, 2.7.0.", instance="10.129.2.121:8080", job="myproject/cluster-operator-metrics", kind="Kafka", name="my-cluster", namespace="myproject", pod="strimzi-cluster-operator-56b59d667d-vj7ln", resource_namespace="myproject"}
--
```

**Comment by davidffrench** [comment]
Thanks for the response @sknot-rh , Yes that looks good to me.

**Comment by sknot-rh** [comment]
Should we reopen this, as th Topic operator part is still opened in https://github.com/strimzi/strimzi-kafka-operator/pull/4502 ?
