### ISSUE TITLE
Quick question: What is the meaning of `<opicOperator:1379>`?

### ISSUE THREAD

**Issue by fzyzcjy** [strimzi/strimzi-kafka-operator#4345]
**Suggestion / Problem**
Hi thanks for the lib! I wonder what is the meaning of `<opicOperator:1379>` in the log of kafka operator?

example:

```
[2021-01-30 07:06:35,989] INFO  <opicOperator:1379> [oop-thread-7] Success reconciling KafkaTopic default/mytopic---ldkfjhgsdkljhgslkdfghsl
```

**Documentation Link**
not found

**Comment by scholzj** [comment]
It means the log messages was printed from the `TopicOperator` class, by a code on line 1379. Not sure why the `T` is missing.

**Comment by scholzj** [comment]
@tombentley @sknot-rh Any idea why the first letter is cut off in the Topic Operator logs?

**Comment by fzyzcjy** [comment]
Get it. Thanks!

**Comment by sknot-rh** [comment]
What version do you use? It should be patched in https://github.com/strimzi/strimzi-kafka-operator/pull/3985
It caused by using logging pattern which is cutting off the name of class/logger, e.g. `[%d] %-5p <%-12.12c{1}:%L> [%-12.12t] %m%n`.

**Comment by fzyzcjy** [comment]
Aha then it is because my version is too old. I will update it.
