### ISSUE TITLE
Support for scale down of Kafka cluster when Strimzi operator is set to watch all namespaces

### ISSUE THREAD

**Issue by super-falcon** [strimzi/strimzi-kafka-operator#4367]
**Is your feature request related to a problem? Please describe.**
We have an environment with a large cluster, where we have multiple namespaces (each running the Kafka cluster). Also, we have a situation where a new namespace (with Kafka cluster) could be created and terminated at any time.
In short, we want the Strimzi operator to be always running in order to service any new namespace creation (Kafka cluster).
So the Strimzi operator is set to watch the whole cluster as described in https://strimzi.io/docs/operators/latest/full/deploying.html#deploying-cluster-operator-to-watch-whole-cluster-str.

We want to be able to scale down the Kafka cluster on one of the namespaces (Kafka, Zookeeper stateful sets, and Entity-operator, Kafka-exporter deployments) down to 0 during the maintenance window. 

Right now if we scale the Kafka cluster down, the operator automatically resets it back to the desired replica level. 

The only way to scale down the Kafka cluster was to scale down the Strimzi operator as well.  This is not desirable, because, we have automated provisioning where the new namespace creation might happen at any time with the Kafka cluster within it.

**Describe the solution you'd like**
In a scenario where the Strimzi operator is configured to watch all namespaces, we want to be able to scale down the Kafka cluster in one of the namespace without having to scale down the Strimzi operator.

**Describe alternatives you've considered**
The alternative considered was to scale down the Strimzi operator,  when scaling down a Kafka cluster in a specific namespace. But this has other undesirable side effects.

**Additional context**
This is the discussion we had on the Strimzi slack channel on this topic.
https://cloud-native.slack.com/archives/CMH3Q3SNP/p1612290494237600

**Comment by scholzj** [comment]
This should be addressed in #4399 which lets you pause the reconciliation using an annotation (and scale down the Kafka STS down while it is paused).
