### ISSUE TITLE
support ingress without ssl

### ISSUE THREAD

**Issue by maknihamdi** [strimzi/strimzi-kafka-operator#4384]
**Is your feature request related to a problem? Please describe.**
We want to use ingress mode to expose our cluster to external clients. We already have a legacy platform with a legacy applications that dont supporting ssl. We want to migrate to strimzi without migrating our legacy applications immediatly. We already use ingress (nginx controller) using with tcpServiceConfigMap https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/. So we want to use ingress without ssl.

**Describe the solution you'd like**
The solution is to use TCP mode with ingress. Brokers share the same hostname, and every broker have a special port, using tcpServiceConfigMap we can specify service used for every broker replicas. Strimzi have only to configure listeners properly.

**Describe alternatives you've considered**
---

**Additional context**
kafka 2.4.0, strimzi 0.19.0

**Comment by scholzj** [comment]
In the past the _TCP_ support in Nginx was not working too well and it was quite hard to configure. The TLS Passthrough mechanism is easier to configure and use and applies better to other Ingress controllers. So I think that from the core Strimzi team there is no intention to implement this. 

The current implementation of the listeners is also fairly flexible. So you can probably implement it using an internal interface, overriding the advertised hostnames / ports and creating the appropriate Ingress resources manually.

Also, have you consider other options which do not require TLS such as node ports or load balancers?

**Comment by maknihamdi** [comment]
We already use TCP support with other component (jenkins, elk, sftp server,...), I agree it's a quite hard to configure, but we have only 2 objects to configure: one configmap and one service, we ended up mastering the matter more easily.

The advantage of using strimzi it's that all of broker configuration beans are managed by the operator, this is why we dont prefer using overriding internal listener solution. But, I will still consider this solution and test it, thank you!

Also we considered other options, the problem with load balancers solutions is that we have a limited ip range, in our development cluster we can have many cluster to expose, the limit can be exceeded quickly. With node port the problem is when a broker moves between nodes, his ip adresse changes, and client fails because broker is not reachable with old ip. 

This is why we decided to use ingress solution. Only one ip adresse (already reserved to the ingress LB), dynamic route to the broker. The problem is now with the obligation of using tls in the broker to be able to use the TLS Passthrough mechanism. It now only an ssl problem.

I developed the solution described in the issue and I tested it. I will push the source code and I will request a code review.

**Comment by scholzj** [comment]
Triaged on 12.4.2022: The Ingress API does not offer much compatibility for TCP routing. While the individual Ingress controllers often support it, it is usually done in a different way for each of them (even more different that the incompatibilities between the Ingress resource handling). More over, Ingress API is being replaced with the Gateway API which offers better support for this in the form of the TCPRoute which hopefully provides a better compatibility. This should be closed and any effort should focus on the Gateway APIs support instead.
