### ISSUE TITLE
strimzi_resource_state metric continues to include metrics for removed Kafka CRs

### ISSUE THREAD

**Issue by david-martin** [strimzi/strimzi-kafka-operator#4387]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
The `strimzi_resource_state` metric continues to give values for Kafka CRs that have been deleted.

**To Reproduce**
1. Create a new Kafka CR
2. Verify the strimzi_resource_state metric is included in the operator metrics endpoint for that Kafka CR
3. Delete the Kafka CR
4. The metric continues to be included in the metrics endpoint

**Expected behavior**
Once the Kafka CR is deleted, the metric should be removed.
This is the case for the related metric `strimzi_resources`

**Environment (please complete the following information):**
 - Strimzi version: strimzi-cluster-operator.v0.21.3
 - Installation method: OLM
 - Kubernetes cluster: OpenShift 4.6.15
 - Infrastructure: Amazon

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

I see the logic at https://github.com/strimzi/strimzi-kafka-operator/blob/master/operator-common/src/main/java/io/strimzi/operator/common/AbstractOperator.java#L506-L516 for removing the metric if the CR no longer exists.
However, I wonder if that is being hit?
When the CR is deleted, there is cleanup logic being executed OK. But when does this metric remove logic get a chance to run? There's a call to `get` the CR above it at https://github.com/strimzi/strimzi-kafka-operator/pull/3652/files#diff-0683e6f31cbb1557f1119868f5cb0a5f48c5f18d50e7751e9d63928989e84fdcR365, but will that line be hit when the CR no longer exists?

**Comment by sknot-rh** [comment]
Seems to be fixed in https://github.com/strimzi/strimzi-kafka-operator/pull/4354/files
