### ISSUE TITLE
No way to set the debug level up

### ISSUE THREAD

**Issue by datngoews** [strimzi/strimzi-kafka-operator#439]
Is there any way to set the `ZOOKEEPER_LOG_LEVEL` env?

https://github.com/strimzi/strimzi/blob/5d395aeb1ba55a4299fcdccf357cd6d0c418c167/docker-images/zookeeper/scripts/zookeeper_run.sh#L32

Same issue for the `KAFKA_LOG_LEVEL`

**Comment by scholzj** [comment]
Good point. We have it supported in the containers it self, but not exposed this as user configurable to the users. Thanks for raising this issue - we will add it to our backlog.

**Comment by prune998** [comment]
@scholzj or @ppatierno anything in the pipe on your side or is it worth I take a look right now ?

**Comment by ppatierno** [comment]
@prune998 it isn't high priority on our side so if you want, a PR will be really welcomed! :)

**Comment by prune998** [comment]
Well, the way I was thinking of this was : 
- change the startup script in the Docker image to template the log4j.properties file
- change the controler to set an ENV VAR with the needed log level, which is used by the startup script.

Any better thought ?

**Comment by scholzj** [comment]
Yeah, I think that would be a good start. I think in a long term there might be a need for more flexibility than just log level. But that can be done later.

**Comment by scholzj** [comment]
This has been now implemented through a different issue and can be closed.
