### ISSUE TITLE
Passing environmental variables to Connect

### ISSUE THREAD

**Issue by keslerm** [strimzi/strimzi-kafka-operator#443]
Maybe a very specific use case for this but something I'm running into.

We utilize the Connect S3 Sink and are required to provide some kind of credentials to the authenicator. In general this means passing AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environmental variables from a K8S secret into the pod, but there is no way to do this via a ConfigMap.

Curious if it's possible just to pass user provided ENV variables from the config map to the deployment that's created?

**Comment by ppatierno** [comment]
Currently there is no support for something like that. Off the top of my mind a solution could be ...
Because you are adding your connector, it means that you are building a new Docker image from the Strimzi Kafka Connect one as described in the doc. At that point you could define the env var at image level but I know that it's not ideal. @scholzj any more thoughts ?

**Comment by scholzj** [comment]
Well, this would work ... and it should be quite easy:

```Dockerfile
FROM strimzi/kafka-connect:latest
ENV AWS_ACCESS_KEY_ID=xxx
ENV AWS_SECRET_ACCESS_KEY=xxx
```

This is something what could work immediately. But it is obviously not exactly secure baking the credentials into the image. Ideally these should be baked into secrets. But we do not have a solution for this right now. I wonder if [this](https://cwiki.apache.org/confluence/display/KAFKA/KIP-297%3A+Externalizing+Secrets+for+Connect+Configurations) could be somehow used for this purpose once it gets implemented.

**Comment by scholzj** [comment]
I'm looking into this right now. I drafted a simple proposal how the secrets can be passed to the Connect pods as env vars. or files: https://gist.github.com/scholzj/2c27196987dfc160500c144dea76186f

Any feedback would be welcome.
