### ISSUE TITLE
TLS handshake failure

### ISSUE THREAD

**Issue by barryzhounb** [strimzi/strimzi-kafka-operator#4474]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**

**To Reproduce**
2. Create Custom Resource '....'

// generate truststore.jks with cluster-ca-cert
keytool -import -trustcacerts -alias root -file ca.crt -keystore truststore.jks -storepass password -noprompt

//generate user-keystore.jks with user.crt that is signed by client-ca
keytool -import -alias user -file user.crt -keystore user-keystore.jks -storepass 123456 -noprompt

Define a  config file kafka-sasl-ssl.conf as following

```
security.protocol=SSL
ssl.trustmanager.algorithm=PKIX
ssl.truststore.location=./truststore.jks
ssl.truststore.password=password
ssl.truststore.type=JKS
ssl.keystore.location=./user-keystore.jks
ssl.keystore.password=123456
ssl.keystore.type=JKS
```

3. Run command '....'

export KAFKA_OPTS="-Djavax.net.debug=ssl"

kafka-2.12-2.5.0/bin/kafka-console-producer.sh --bootstrap-server dlake-cluster-kafka-bootstrap-abc.apps.northers.os.fyre.ibm.com:443 --producer.config kafka-sasl-ssl.conf --topic dlake-topic

```
... no IV derived for this protocol
JsseJCE:  Using KeyGenerator IbmTls12Prf from provider TBD via init 
HandshakeMessage:  TLS Keygenerator IbmTlsPrf  from provider from init IBMJCE version 1.8
kafka-producer-network-thread | console-producer, WRITE: TLSv1.2 Change Cipher Spec, length = 1
JsseJCE:  Using cipher AES/CBC/NoPadding from provider TBD via init 
CipherBox:  Using cipher AES/CBC/NoPadding from provider from init IBMJCE version 1.8
JsseJCE:  Using MAC HmacSHA256 from provider TBD via init 
MAC:  Using MessageDigest HmacSHA256 from provider IBMJCE version 1.8
*** Finished
verify_data:  { 174, 132, 179, 89, 126, 243, 183, 123, 236, 20, 87, 120 }
***
kafka-producer-network-thread | console-producer, WRITE: TLSv1.2 Handshake, length = 80
kafka-producer-network-thread | console-producer, READ: TLSv1.2 Handshake, length = 2675
kafka-producer-network-thread | console-producer, fatal error: 80: problem unwrapping net record
javax.net.ssl.SSLProtocolException: Handshake message sequence violation, 2
%% Invalidated:  [Session-1, SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA256]
kafka-producer-network-thread | console-producer, SEND TLSv1.2 ALERT:  fatal, description = internal_error
kafka-producer-network-thread | console-producer, WRITE: TLSv1.2 Alert, length = 64
kafka-producer-network-thread | console-producer, called closeOutbound()
kafka-producer-network-thread | console-producer, closeOutboundInternal()
kafka-producer-network-thread | console-producer, called closeInbound()
kafka-producer-network-thread | console-producer, closeInboundInternal()
kafka-producer-network-thread | console-producer, called closeOutbound()
kafka-producer-network-thread | console-producer, closeOutboundInternal()
[2021-02-25 20:16:36,723] ERROR [Producer clientId=console-producer] Connection to node -1 (dlake-cluster-kafka-bootstrap-abc.apps.northers.os.fyre.ibm.com/9.30.116.162:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-02-25 20:16:36,724] WARN [Producer clientId=console-producer] Bootstrap broker dlake-cluster-kafka-bootstrap-abc.apps.northers.os.fyre.ibm.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
Using SSLEngineImpl.
```

Please see [More detail logs as error-logs](https://github.com/barryzhounb/issues/blob/master/kafka-producer-ssl-failure.log)

**Expected behavior**
I follow https://strimzi.io/docs/operators/master/deploying.html#setup-external-clients-str to setup TLS connection, unfortunately it failed.

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.11.1]
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io]
 - Kubernetes cluster: [e.g. Kubernetes 1.14, OpenShift 3.9]
 - Infrastructure: [e.g. Amazon EKS, Minikube]

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

**Comment by scholzj** [comment]
> Please use this to only for bug reports. For questions or when you need help, you can use the GitHub Discussions, our #strimzi Slack channel or out user mailing list.

Probably opening a discussion would be much better then opening a bug issue.

> //generate user-keystore.jks with user.crt that is signed by client-ca
keytool -import -alias user -file user.crt -keystore user-keystore.jks -storepass 123456 -noprompt

This does not create a keystore. This creates just a truststore because you add only the CRT file. You need to create an actual keystore which will contain the private key as well. Or you can use the PKCS12 one which is already included in the user secret. From the error, this is what probably caused your connection failure.

**Comment by barryzhounb** [comment]
Hi @scholzj, sorry for any inconvenience, I have changed it as question.

You mentioned: 
```
You need to create an actual keystore which will contain the private key as well.
```
Could you give me a help for how to create an actual keystore which will contain the private key with keytool command? Could you show an example here? Thanks your help in advanced.

**Comment by scholzj** [comment]
You can just google it. Foe example https://www.ibm.com/support/pages/how-generate-jks-keystore-existing-private-key
