### ISSUE TITLE
certificate disappeared from Kubernetes secrets 

### ISSUE THREAD

**Issue by mkarya0609** [strimzi/strimzi-kafka-operator#4479]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
we are set Kafka cluster using strimzi kafka. 

here is spec for consumer:
piVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  creationTimestamp: "2020-10-21T09:52:22Z"
  generation: 1
  labels:
    strimzi.io/cluster: dataflow-westus
  name: fc-telemetry-prod-write-user
  namespace: default
  resourceVersion: "61010505"
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/default/kafkausers/fc-telemetry-prod-write-user
  uid: 0508534d-6e4e-4a4d-94c9-cf5ddb5a3d43
spec:
  authentication:
    type: tls
  authorization:
    acls:
    - host: '*'
      operation: Write
      resource:
        name: fc-telemetry-prod
        patternType: literal
        type: topic
    type: simple
status:
  conditions:
  - lastTransitionTime: "2020-10-21T09:52:22.422Z"
    status: "True"
    type: Ready
  observedGeneration: 1
  secret: fc-telemetry-prod-write-user
  username: CN=fc-telemetry-prod-write-user

here is the certificate for fc-telemetry-prod-write-user
 Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxakNDQWI0Q0NRQ2xMek84Mm13QVZUQU5CZ2txaGtpRzl3MEJBUXNGQURBdE1STXdFUVlEVlFRS0RBcHAKYnk1emRISnBiWHBwTVJZd0ZBWURWUVFEREExamJHbGxiblJ6TFdOaElIWXdNQjRYRFRJeE1ESXhOakE1TlRjdwpORm9YRFRJeU1ESXhOakE1TlRjd05Gb3dMVEVUTUJFR0ExVUVDZ3dLYVc4dWMzUnlhVzE2YVRFV01CUUdBMVVFCkF3d05ZMnhwWlc1MGN5MWpZU0IyTURDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQU9COUhibHZXUjJTbTRUdVVrOFhMNE00Y29FVVpFWndoZmV3VFJObzNQbkgzYk1mdmJTVHV6K0dON0p2eFVyUgprZW1VTmtKQzJjQ0RvOHFmekR6a1hFdWtxMlFaeDZ0U212S1ZEbVN6TkhDaHVWVmxwTjBRd2ZVekhscDFoamtHCmg1ZGtVT0hqaCt3Qm4rQ0FtZ0FHbXdSeW5GSEtXdjU5TExGOU9rT0cwY2NlZlpBY2pJblU3OTdMTko3YVVtbEIKZSthTnVjU2tjRUxaZmFNaDJTMzBybUVwZVlWSDRlYlBzeHJLb2l0OVFhNXRHVG1xWUNod09GR3MyaTc4ZnJLNQpPcHgzTWxieHR2djNOYXlsdXFQUlhOa1Vib0kzMm9FejZJbFhieEVWbDRIZXMxSUxMUHlxVGtKaEVVRFVIak1WCkpPdnlOQlJaWitJYlpKOFZMWW15YUE4Q0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUXJtQzMxaFQKNVZVbGJKRCt5Uys1cU1XOEYwMDFkZmNKdkJMU1F3RGdiYkVGSHRibDFjQ3VINGFGczhUbWxJQ0dPRklpMWJhNQowdW5YRzU3amUrMFdqZ25nYXZ0anpHWGw3OE9jSmNYYmQzamVPeEFpdlQxOFR5azRoT2lJcXNXeTd0YkJEWHhQCmY2SzIxL0dkMVNqRk4yOVRFQXoxRlhlOWc0RlJwMHVuNHpLdjhHMVRvQ0tvYjM1RElKM3cxZVl2dm03T0lYbk4KaThYM3hRR1l5Wlc2Y0toZm8vV3UyaS85MFJTcXZuUTRtbTdlanBYclRIdHdKQm5sMllNczdGN2p4eVIwYlRqUgpZUjJ1aFBUZndSdURTd2ZWekJ2ckRtYUQ3UmtNdm5QQ1VkQkN5d05IOEdGbGhFVlo2eW5TZTJ2Y3BlOXd0MzBGCjZUMWRwV2dXVWp4Kyt3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  user.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQWJnQ0NRQ2pUMGx4NG8yM3pEQU5CZ2txaGtpRzl3MEJBUXNGQURBdE1STXdFUVlEVlFRS0RBcHAKYnk1emRISnBiWHBwTVJZd0ZBWURWUVFEREExamJHbGxiblJ6TFdOaElIWXdNQjRYRFRJeE1ESXhOakE1TlRnMApNbG9YRFRJeU1ESXhOakE1TlRnME1sb3dKekVsTUNNR0ExVUVBd3djWm1NdGRHVnNaVzFsZEhKNUxYQnliMlF0CmQzSnBkR1V0ZFhObGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxoQWJCN3UKVzB5MWtkU21Md2pxMHpTUTIxZjBOUEFieDY0UVJudlp0MmVsZjczUUxjcEYxOHdzOU4ySlJXclRyZEZIdG50bgpjZUhlZlNtbHJxSFQ4ejFMbGl3anRBRUdXTFBoL0lSNEhNenlndk1vWXc0YmpBVTFxY1BJWG1OTlVqSmlBVHVaCjV1L0VmZHp1eS82WGdOUmlOUktOdGlFSGZCdDFwZHBxM2hnVkpzTThhZHozazNGZzZVek5tZnpIV1F5ZmVSdWcKUER2aHBQTHFUMmRjc1l1bWF5NTdrS1hOM2pTNlRCYlZQN0E0TUdFRTlZQTd5clR1bzZyekZSaDFHdTF1c3czYgpBa3Blb0xlK3AybEcwWUNTM1c1cjRqVjd0ZGpjREw5L1o0V21WdE91VHEvWFRlWW5kZ29rRFAxYm5WM1B4KzdGCmVuOHlkZUJzOU9HOGpGTUNBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWFYckhlZjBVdnc0NGVBMUMKYmFLenZESTVZQnlhOWtYaGJqN1l4bXZGeEFOcERGTXNOWk9LQWovS2dJZkpZS3dwc29QS25jMTl1Wks1T09mdwp4dnJiLzNQNnJTZEJHMmk0eENpa0NkWlRHdExpZFJPMi9SSnNJWm1vU2VQMzIvVnljakNldWc2MFcvdmJGTjBLCkZtNXJKWjhhWUp5YXVMa2JSazRJRGk1TFpkTjNpcGhYYnhFeW8yTHc1M2s1U1AzUEdPTXF4Z2lDNzViNzB5cjUKOVZyRVB2andoMmNrNTdBSERuc2lPQk0vSFFJVDlZZ0hQeXU4Uzd1Wlk0cDJwR0E0Z2VOTExYODlpdy9TLzdrUwo2eWdBZXJJTHp2NUFNdXpYZW5EQ3VaSDI1eGZzTnpjQytSdlRNSng3NlNCSkJPTDV2TlBOMTNSQ04rM0VMdVZZCm9xRkdWZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  user.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzRRR3dlN2x0TXRaSFUKcGk4STZ0TTBrTnRYOURUd0c4ZXVFRVo3MmJkbnBYKzkwQzNLUmRmTUxQVGRpVVZxMDYzUlI3WjdaM0hoM24wcApwYTZoMC9NOVM1WXNJN1FCQmxpejRmeUVlQnpNOG9MektHTU9HNHdGTmFuRHlGNWpUVkl5WWdFN21lYnZ4SDNjCjdzditsNERVWWpVU2piWWhCM3diZGFYYWF0NFlGU2JEUEduYzk1TnhZT2xNelpuOHgxa01uM2tib0R3NzRhVHkKNms5blhMR0xwbXN1ZTVDbHpkNDB1a3dXMVQrd09EQmhCUFdBTzhxMDdxT3E4eFVZZFJydGJyTU4yd0pLWHFDMwp2cWRwUnRHQWt0MXVhK0kxZTdYWTNBeS9mMmVGcGxiVHJrNnYxMDNtSjNZS0pBejlXNTFkejhmdXhYcC9NblhnCmJQVGh2SXhUQWdNQkFBRUNnZ0VCQUszQnN6VUlPM2wvMFdMa3hYNTNWVzVCSFZrNHA2TzN6dnRMeGV5T1NQT3AKazJvQnBPMFlLSVlYNzJQc1RGYU9BV0ZYYTdPOHZoenZvTUZoeWVvNjR5eHUxOVFRWjNSLzg2N1A4ejlKdG45ZwpSRFhqWkdhdGU4Sjk5UGI1UW1vTFJQVFdqNnNSWEVQSTNaazRhWkJTZDkvU0xaS3RxWkJFYXJuS25QbjV4akNXClJvMWljUS9FdUJqZm1Pc0tUeDJxdThHdmkwSjJ1QUt2dkExVWxVNHV5ZXlGRXMzY1BpWVh0SHpZYkpOdmwvK2UKcmpMNm1waW1UNzFkWEMvK29rK0Zma0k2TDZ4MG1OL2pLK3B2bGRKQVhiK3U0OWM1VzBLcFZBdlVXcHgya09KYgpGYU16eG0wK2hTUmNMQkh4M051WVY4QVNxTEpMU3ovL1c1dkFVZE1QWUlFQ2dZRUE3WW1GNHExWklqbVFlTGN5Ck1OQ2h4MVFyUVRIbDhoMUdRZDdkRzUrZGpKSnRxQUkzaTRtbklzK2FVc2ZYVDF2d2JXckFabmdlUThTc0ZLOUIKb25jT2dQZWh4eU56ME5ybmFmbCtvaXprV1NzaGhJUGE1aUtsK2JvdHlRZVZ5cFp0U2JKNlIxSW5zRlA3RUhzTwpjQzY0emZnVDJvd0VFSTJnWkRTUTlrM0N5c01DZ1lFQXhwS2h6cXVDeGY0VEFTN3pxWTdKdVY0Q1o4bWtreFRaClpFQVNTMkVCUk5adW1LVmViaHlLa0NwZWc1dEJqcVVCN3pGcC96eVp3Wk5uMEk1RFZ5cmpGdnk5cDNHUlh2cncKYmdyTWREeTlkdHZrdjd0TzJYWStWbEZ4NlhNbCs2dGJ2dXE0V3N6OVF5RE9adHZyMEsxWVNhZVp1Z2s0SjJoTwpaNllrdlgvZmZ6RUNnWUVBcVdhVU51NU5UTjBrclJKcEZ1c1RGT1p2MnBUTlduZUtMVnZVNytoTElYOGorTmRyCjZYV0gzb21UazBtMXdZRGQzQXB2b0NRMTRUcVhSa0VlVzlEd1pRVTFPS0dON1ByUVlvRnQwQmFYMndlcFphbnIKS0lpNU9YbVBRWGpKV0tzaTBaWVpJbGZ5dWd1S1YxeUxGWEljbGJjLzRYSk5TOGpWQStHQktFYVlqcVVDZ1lBagpEQmhROE1hSkNYbnpPSVU3QlArbm51Y1B5SEFxb1lCcENFSHlXZkd1WTZacmZLeDVCTUtVQlZaZkpoVGhCMUNiCkZmNmVWT1RTWEtEekYxamRWcTEwRGpHdkR3VllYVFA0U0NHajFtQ2VUTnRIMTlobjIwM1BVRnFwbUhBNHhoclEKVEg4elQ0RFh5eitDdWdnWjhhNW1lWlZSVjNVNHgxa25SQlN4K1pMSjBRS0JnRlRmb3ZnNm5OUFF6OXRQaXZvVQpBdmE1QlNrMk9Kd1dLeEluMllKZVcrdDV0SDd3NWt1SzN5Q3VGcnB5SWRURlY5eEZlcDZXcGpPT3pvRzhJekNBCkZXTDVyNVRUcnc1YXJnZVF0Y090SG5wMzhiZ2lWS1RhNUlmaFJ0eWZyNk1IR2Rnc3ZDUFZNTzJXamNTb0x1UlkKaXM5VEx5NkJLblg1U2twdXNmSU5qUnRMCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  user.p12: MIIJogIBAzCCCWgGCSqGSIb3DQEHAaCCCVkEgglVMIIJUTCCA78GCSqGSIb3DQEHBqCCA7AwggOsAgEAMIIDpQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIw/2XMRxOEWcCAggAgIIDeA1WDBt05jFUjLRLU3vQpOjvCni8wj4fMWCI6BGhVOGFKFkKbmpmiKXeNozjUQ63rrSVLfeHH8InXkQG8rrq9ZG8iAU6/A2Bo3XC1UrPdkc9Vm5LoxUiMSB0sw/5my3pSVqENuPrW4y4Hj/nYI5SmLcxIqLLQpe7wL7q7ezpNeJ1nnTPpSkEoWDYdI6YvNRru/KkB8ZKH3X6U5s/iEK7JnijjpA/K9sk1JI2ieQwWRDfi7KcvUqsgTMWA3qPQnqAPZRXsqK+wZ8HRLbdtICIFpTigY11wWTTTjpF5Hqbe3fOSNwTqDiURhwQU1DmHLS7TZ8k0KYTWwwaTe/bTGW0u1wT/eMoNqQq+hngdwkj8NC4Un4K9DIw/R0xmlUt2LlL1YveeCl9Uy78rb3dwXFYlbvNZlm8C4zJbus1p5WwEgfEbGCfRFtxiPJHGffBLU6QbrDXmAOyCoxq7uaSDYtD8yle7d81yCDUWW8M7VgK3iLmQ8k5b4uNP4j3AGz+5GiCK15RLq07MtgAuQqBZfPQArJY4HqaBHgEUyVDEgFJgvtIoL+ByjXZh+ZeDAZ68q8+LHVB3oEClKV8WCJhMWhYjR0sSM4m19as001V03LGlqijLvZeJ5jXqhh0W8qU3ju1hQBum0knmHhw4g+4fF0Aru0DxAb+OOyZZ0RQiRFr6sqNxZK2d86h7exh9hrdefracQuuFqPRVY7Bf8ii4RtyKzQQtHgil+K615iPOgyl8ISoFYV/AiFeCwBQqWr8yNtsNoAbPX+FxGaw0LBecjadE2rWfJTghVSmVUVaI16ObjkvUtuRFu6Lk00bONe00DmCXVB+bY+vJVpT10YA91hRh9rzR8yaAhLZEMAATnj2X9HRWsCem42CkJrEg9cF/28smEuMMYeq/BoVGVUiRs69ppWBUZ0VzNvOgJJcBGdx7ni6VqdaBYBe3pvODc4XVRYOXxgZlkniW+Su+s7mnbAZJHrJ1ZUeftcgid+R5Vi79rNUF/dBJMW/2HslOxV09i+dZlR47jaYcA5thmNw01NdVyuyiyVXk+q8nh6Rn8A6AeOB5OpofiVyenyayUhSgPoc2CWq02qZl2Dql8cO5jLSw58BL1+OnB3WWBdcxPL6x9M77VzPhn2lg4bkpZxRGt+K/FWBNP8BxfBMsSSf9inQnGjYCvDABZXwl7Wzw6se5ZRUJUJPdw9wYxnNURDUElxJhsZI+sc1GUTSSQ0Nn716JVStYQli+pcw+UTLTnO9licrh0thbe43hNgRIcQvjv/xXXGbv+mljNNIwKmdVwASHMgONNmoFv0++H+LOkcNNS7whr1mhR7maS6Ex9iQHmmViW43DvHuiVITC+CeQXTQcTqeIlVOkNnHEqBYozTagk1kClivJ3PMSwuAqPqQ4WQxmKvHCKnVfqRWfwzssjVnqGTNCNf85Ys0TztVXS8dfm9WYu8+yy2ejl2AXo6xKXoCX3jLLSX4aweKgyYozRvFxykxoM3T5cq68Uymic3IcECQ2Mfbe9j6x5VX0i/Ul4SPOOOvlMyTeWvzJ89c06KRc7COrdFq2p2PFTHsO708LR5AsoxdyAabcgt/bGJe6nr84IYhzIi/qum6j+v7kTmPKBCc9NY1CyGiepBxYUdiyAFbnIXteHMT0GliDa3VvzyhozYAWQpss5yk3K8+bexlS963RnDiGAM2Lz5SJHNxmwBmQ9WH/1/bWaQi9BfVcceTtZJSD7gunJw6046oR0FSxx+4WMaeXRnxjmonpY+WZjPh6hW4CAqs9QyswXxDo8e7UBbr+glVUa6VsT7y+Uxrx2d7chzzqJmDEOpRDd+CJXuUr1itIaaF1YGcYKhqmt9+G/GEhvtaz23A4T/neVD0r5FfR1OsVe2XEBHWd6uTlmn2faAZh39Szbudla83yLU1m3SpMW4wIwYJKoZIhvcNAQkVMRYEFByduwIBM/scMOorv5vnWHr4QzhrMEcGCSqGSIb3DQEJFDE6HjgAZgBjAC0AdABlAGwAZQBtAGUAdAByAHkALQBwAHIAbwBkAC0AdwByAGkAdABlAC0AdQBzAGUAcjAxMCEwCQYFKw4DAhoFAAQU4xh8w3mC2ScXrrJe9mOFk/jIX1kECLHsh2QUNeIYAgIIAA==
  user.password: UE5kYXlwZFc2T3pj
kind: Secret
metadata:
  creationTimestamp: "2020-10-21T09:52:22Z"
  labels:
    app.kubernetes.io/instance: fc-telemetry-prod-write-user
    app.kubernetes.io/managed-by: strimzi-user-operator
    app.kubernetes.io/name: strimzi
    strimzi.io/cluster: dataflow-westus
    strimzi.io/kind: KafkaUser
  name: fc-telemetry-prod-write-user
  namespace: default
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: KafkaUser
    name: fc-telemetry-prod-write-user
    uid: 0508534d-6e4e-4a4d-94c9-cf5ddb5a3d43
  resourceVersion: "96932921"
  selfLink: /api/v1/namespaces/default/secrets/fc-telemetry-prod-write-user
  uid: a0a3ef17-fda9-4582-852a-0e356ce645b3

we have defined a certificate on one more secrets called dataflow-westus-clients-ca-cert. 

one day two certificates disappeared from the dataflow-westus-clients-ca-cert. this caused the Kafka outage for 4 hours till we added the certificate in the dataflow-westus-clients-ca-cert.

we are not sure how this certificate disappeared. 

i see below in Kafka log at this time.
![image](https://user-images.githubusercontent.com/47654276/109351860-f5913700-789f-11eb-8f32-673cbb16b338.png)

![image](https://user-images.githubusercontent.com/47654276/109351884-fd50db80-789f-11eb-8bf0-97d32848aedb.png)

**To Reproduce**
2. Create Custom Resource '....'
3. Run command '....'

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.11.1]
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io]
 - Kubernetes cluster: [e.g. Kubernetes 1.14, OpenShift 3.9]
 - Infrastructure: [e.g. Amazon EKS, Minikube]

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

**Comment by scholzj** [comment]
I'm sorry, but I'm not sure I really understand what your issue is. Can you please:
* Can you please format the issue properly to make it more readable?
* Attach all logs as a text file or copy paste them into the issue? The images are absolutely not readable.
* Delete the template which you did not used (although if you can include the things it is asking for such as the Strimzi version that might be helpful)
