### ISSUE TITLE
MM2 auto offset sync doesn't work with IdentityReplicationPolicy

### ISSUE THREAD

**Issue by feydan** [strimzi/strimzi-kafka-operator#4498]
**Describe the bug**
Kafka Mirrormaker2 auto offset sync doesn't sync consumer groups using `replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"`

**To Reproduce**
1. Create KafkaMirrorMaker2 custom resource with the following options for sourceConnector and checkpointConnector
```yaml
sourceConnector:
  config:
    replication.factor: 3
    replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
checkpointConnector:
  config:
    sync.group.offsets.enabled: true
```
2. Wait for topics to sync
3. Query consumer groups and confirm they are empty `bin/kafka-consumer-groups.sh --bootstrap-server <broker string> --list`.  Recreating mirrormaker2 with the same options, but without the replication policy does show groups when running this command.

**Expected behavior**
I expected auto offset sync to automatically sync consumer offsets when using IdentityReplicationPolicy.

**Environment (please complete the following information):**
 - Strimzi version: 0.21.1
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes v1.18.9
 - Infrastructure: Amazon EKS

**YAML files and logs**

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  annotations:
    meta.helm.sh/release-name: strimzi-kafka-custom-resources
    meta.helm.sh/release-namespace: REDACTED
  creationTimestamp: REDACTED
  generation: 10
  labels:
    app.kubernetes.io/instance: strimzi-kafka-custom-resources
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: strimzi-kafka-custom-resources
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: REDACTED
  name: kafka-mm2
  namespace: REDACTED
  resourceVersion: "81043440"
  selfLink: REDACTED
  uid: REDACTED
spec:
  clusters:
  - alias: REDACTED
    bootstrapServers: REDACTED
    tls:
      trustedCertificates: []
  - alias: REDACTED
    bootstrapServers: REDACTED
    tls:
      trustedCertificates: []
  connectCluster: REDACTED
  metricsConfig:
      type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        key: metrics-config.yml
        name: strimzi-kafka-custom-resources
  mirrors:
  - checkpointConnector:
      config:
        checkpoints.topic.segment.bytes: 1073742
        sync.group.offsets.enabled: true
      tasksMax: 3
    groupsPattern: .*
    heartbeatConnector: {}
    sourceCluster: REDACTED
    sourceConnector:
      config:
        replication.factor: 3
        replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
    targetCluster: REDACTED
    topicsPattern: ^(?!__consumer_offsets|connect|mirrormaker|mm).*
```

**Comment by scholzj** [comment]
It worked completely fine for me. But you have to also add the `replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"` into the `checkpointConnector` config. Without that it does not know the right topic name and cannot sync the offsets.

**Comment by feydan** [comment]
Thank you for the quick reply @scholzj !  I added the replication policy class for the checkpointConnector and it works now.
