### ISSUE TITLE
Allow adding finalizers to services type LoadBalancers

### ISSUE THREAD

**Issue by cleberwarmling** [strimzi/strimzi-kafka-operator#4500]
**Is your feature request related to a problem? Please describe.**
Related to: https://github.com/strimzi/strimzi-kafka-operator/issues/3974
For some reason, Strimzi's services type LoadBalancer does not receive the finalized responsible for guarantee the deletion of the Load Balancer on GCP. That means that even after deleting every Kubernetes object, Load Balancers are being kept on GCP. Google's supported answer me the following:

> After checking other active services with similar naming convention I found that they are managed by Strimzi operators. The reason why this is important is because Strimzi operator managed clusters do not utilize or permit the use of Kubernetes finalizers. In particular, the finalizer responsible for removing associated load balancers, "service.kubernetes.io/load-balancer-cleanup". This is a known issue with Strimzi managed clusters [1]. For more details on the various resources that Strimzi permits, please review the following documentation [2]. You'll notice that finalizers are not within this list of Kubernetes resources permitted within Strimzi operators. 
> 
> Unfortunately there is no work-around for this other than to either manually delete those Load Balancers, or to not use Strimzi as a means of managing your teams clusters so that the configuration yaml files can utilize finalizers as expected. As this is a 3rd party cluster management system, we cannot assist with ensuring Strimzi permits the use of finalizers as your team is expecting. 
> 
> I hope this addresses your teams concern with why these load balancers are not being deleted as expected when the services are deleted. Please let me know if you have any further questions about this. 
> 
> Regards, 
> 
> Spencer 
> 
> [1]: https://github.com/strimzi/strimzi-kafka-operator/issues/4046 
> [2]: https://strimzi.io/docs/operators/latest/full/using.html#assembly-customizing-kubernetes-resources-str 

**Describe the solution you'd like**
Either fixing the finalizer addition or adding `finalizer` to the `MetadataTemplate` [schema](https://strimzi.io/docs/operators/latest/full/using.html#type-MetadataTemplate-reference). With the second option, I can do it safely than patching the service after Strimzi deployed it.

**Comment by cleberwarmling** [comment]
@scholzj thanks in advance for the help!! Also, I'll try to fix/build locally to contribute but my Golang skills are not sharp as I wish.

**Comment by scholzj** [comment]
Well, PRs are welcomed, but don't worry abotu it if you don't know Java - I can get to it. However, we are just finalizing 0.22 release and I do not think it will get into it. So it will probably be only in 0.23.

**Comment by cleberwarmling** [comment]
Cool, thanks. FWIW I'm getting a workaround patching the services after they got running:

```
kubectl patch service  kafka-kafka-0 -p '{"metadata":{"finalizers":["service.kubernetes.io/load-balancer-cleanup"]}}' --type 'merge'
```

**Comment by scholzj** [comment]
This would be expected, yes. There is no way you can avoid it.

**Comment by scholzj** [comment]
FYI: I opened a PR for this.
