### ISSUE TITLE
Kafka CRD cannot be created "metadata.annotations: Too long: must have at most 262144 bytes"

### ISSUE THREAD

**Issue by kubealex** [strimzi/strimzi-kafka-operator#4512]
**Describe the bug**
Following the documentation, kubectl apply -f install/cluster-operator -n **namespace** ends up in error:

**To Reproduce**
kubectl apply -f install/cluster-operator -n kafka
serviceaccount/strimzi-cluster-operator created
clusterrole.rbac.authorization.k8s.io/strimzi-cluster-operator-namespaced created
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator created
clusterrole.rbac.authorization.k8s.io/strimzi-cluster-operator-global created
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator created
clusterrole.rbac.authorization.k8s.io/strimzi-kafka-broker created
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-kafka-broker-delegation created
clusterrole.rbac.authorization.k8s.io/strimzi-entity-operator created
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-entity-operator-delegation created
clusterrole.rbac.authorization.k8s.io/strimzi-topic-operator created
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-topic-operator-delegation created
clusterrole.rbac.authorization.k8s.io/strimzi-kafka-client created
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-kafka-client-delegation created
customresourcedefinition.apiextensions.k8s.io/kafkaconnects.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkaconnects2is.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkausers.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkamirrormakers.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkabridges.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkaconnectors.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkamirrormaker2s.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkarebalances.kafka.strimzi.io created
configmap/strimzi-cluster-operator created
deployment.apps/strimzi-cluster-operator created
**The CustomResourceDefinition "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes**

**Expected behavior**
Operator installs all resources without issues

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.11.1] 
0.21.1
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io] 
 yaml
 - Kubernetes cluster: [e.g. Kubernetes 1.14, OpenShift 3.9]
k8s 1.20.1
 - Infrastructure: [e.g. Amazon EKS, Minikube]
 Bare metal

Additional:

The culprit is this CRD:

[alessandro@localhost strimzi-kafka-operator]$ ls -latr install/cluster-operator/040-Crd-kafka.yaml
-rw-r--r--. 1 alessandro alessandro 1230854 Mar  4 17:25 install/cluster-operator/040-Crd-kafka.yaml

**Comment by scholzj** [comment]
You should use `kubectl create -f ...` /  `kubectl replace -f ...` instead of `kubectl apply -f ...`. If you found `kubectl apply` anywhere in the master documentation, please share the link as that would be a bug. But I think that it should be all fixed.

PS: Keep in mind that you are installing the work-in-progress master version of the software, not 0.21.1.

**Comment by jhcook-ag** [comment]
@scholzj https://www.youtube.com/watch?v=GSh9aHvdZco

`kubectl apply -f https://strimzi.io/install/latest?namespace=myproject`

8:54

**Comment by scholzj** [comment]
@jhcook-ag Please use `kubectl create -f` ... `kubectl apply` cannot handle larger files.
