### ISSUE TITLE
MirrorMaker2 idle consumer group sync example

### ISSUE THREAD

**Issue by stepan111** [strimzi/strimzi-kafka-operator#4514]
**Suggestion / Problem**
I am trying to replicate kafka cluster from one k8s cluster to another.
My scenario is :
1. Disable all Consumer's and Producers in Source cluster
2. Run MM2
3. Start Consumers and Producers in target cluster

 Unfortunately idle consumer group offset's don't synced by default.  To enable this feature I used steps from https://stackoverflow.com/questions/65925842/kafka-mirrormaker2-automated-consumer-offset-sync

```
checkpointConnector:
  config:
    checkpoints.topic.replication.factor: 1
    sync.group.offsets.enabled: "true"

```

**Documentation Link**
Provide a link to the documentation where the bug / suggestion should be applied

I would suggest to update any of : 

https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/mirror-maker/kafka-mirror-maker-2-custom-replication-policy.yaml
https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/mirror-maker/kafka-mirror-maker-2-tls.yaml
https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/mirror-maker/kafka-mirror-maker-2.yaml
Or Create a separate file in this folder.

**Comment by scholzj** [comment]
Have you seen this https://github.com/strimzi/strimzi-kafka-operator/pull/4473?

**Comment by stepan111** [comment]
No @scholzj , I haven't seen #4473 . 

Here are PR - https://github.com/strimzi/strimzi-kafka-operator/pull/4515

**Comment by scholzj** [comment]
Thanks for the PR. If you have any comments to #4515 feel free to comment directly on that as well.
