### ISSUE TITLE
[Feature] Provide ability to configure a custom Authorizer class

### ISSUE THREAD

**Issue by rareddy** [strimzi/strimzi-kafka-operator#4519]
Provide the ability to configure a custom Authorizer implementation other than Simple, OAuth and OPA.  Currently, there is no way to achieve configure a custom Authorizer. Providing the ability to user-defined Authorizer can extend this feature to other variety of Authorization implementations and will keep the feature extensible.

**Describe**
Define a new type called "custom" in the "authorization" section of the CRD, and also configure the class name for the same. If the defined class is found in the classpath then it will be used for configuring the Authorization module for Kafka.

In order to make the custom Authorizer class available in the Strimi image is not part of this request, it will be left as a user exercise to build a private image that has this class.

**Alternatives**
One could use the OPA endpoint to provide an alternative implementation, but that would need a separate process.

**Additional context**
This feature can be useful when defining simple ACLs that may apply to all the users of the cluster rather than per user based ACLs provided by Simple and OAuth methods

**Comment by scholzj** [comment]
Done in #4540

**Comment by rareddy** [comment]
My first Strimzi contribution!!! Thank you @scholzj
