### ISSUE TITLE
The CustomResourceDefinition "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#4589]
With the new 0.22.0 release I am getting this error:

```
The CustomResourceDefinition "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

When doing:

```
  ##strimzi_version=$(curl https://github.com/strimzi/strimzi-kafka-operator/releases/latest |  awk -F 'tag/' '{print $2}' | awk -F '"' '{print $1}' 2>/dev/null)
  oc create namespace kafka
  oc -n kafka apply --selector strimzi.io/crd-install=true -f "https://github.com/strimzi/strimzi-kafka-operator/releases/download/${strimzi_version}/strimzi-cluster-operator-${strimzi_version}.yaml"
  curl -L "https://github.com/strimzi/strimzi-kafka-operator/releases/download/${strimzi_version}/strimzi-cluster-operator-${strimzi_version}.yaml" \
  | sed 's/namespace: .*/namespace: kafka/' \
  | oc -n kafka apply -f -

```

Version 0.21.1 works

**Comment by slinkydeveloper** [comment]
To reproduce, just clone https://github.com/matzew/kn-box and run `./03-strimzi.sh`

**Comment by Frawless** [comment]
use `create/replace` instead of `apply`

**Comment by scholzj** [comment]
Yeah, this is not a bug in Strimzi. `kubectl apply` adds the original resource to annotations and annotations have limited size. So it cannot handle the Kafka CRD which is too big (because of the migration to v1beta2 which is needed because of the migration to CRD v1). You have to use `kubectl create` / kubectl replace`.

**Comment by nyarly** [comment]
`kubectl create` isn't a solution for us, because we're using a declarative approach to our configuration. Deploys are accomplished (essentially) with `kubectl apply -f cluster.yaml`; is there a workaround that would allow us to trim the Kafka CRD?

**Comment by scholzj** [comment]
@nyarly You can remove the validation schemas ... but then ... you will not have the validation schemas of course.

**Comment by nyarly** [comment]
This is a new deployment of Strimzi; can I somehow strip out the migration stuff?

**Comment by nyarly** [comment]
There's v1beta2, v1beta3, and v1alpha. If I just use v1beta3, will that work?

**Comment by scholzj** [comment]
There is no `v1beta3`. Also, I do nto really follow your question ... strip what migration stuff?

**Comment by nyarly** [comment]
Apologies: there are 3 versions of the schema. Can I just use the highest versioned one? I'm not even sure that'll get me under the byte-limit.

**Comment by scholzj** [comment]
Yes, you can delete just some schemas. Keeping only v1beta2 should get you
under the limit for apply. But it still means you will have two versions
without schema -> so no validation for then. But you can use it that way,
just need to be more careful when/if using the other APIs.

**Comment by nyarly** [comment]
Something to call out: I see the Kafka CRD in at 1231093 bytes - there's a hard limit on all Kubernetes resources of 1MB; based on  discussion here https://github.com/kubernetes/kubernetes/issues/82292, this CRD is a significant outlier. 

Anyway, if the Kafka CRD grows much more, it'll be undeployable, as far as I understand.

**Comment by scholzj** [comment]
I'm not sure what numbers are you basing your judgments on about what is or isn't an outlier. Also, if you properly read the upgrade documentation, you know that the older API versions will be dropped in the next release.

**Comment by nyarly** [comment]
That Kubernetes issue is discussing large CRDs in the context of SSA, and whether mitigations might be needed. One of the commenters is enumerating CRDs in the wild from what looks like a database, where the largest are ~219kB. The CRD I pulled from Strimzi's 0.22.1 release is ~1200kB.

**Comment by neuromantik33** [comment]
This is somewhat of a blocker for us argocd/kustomize users.. Any chance we can trim down the size of the `kafkas.kafka.strimzi.io` CRD?

**Comment by scholzj** [comment]
You can remove the validation schemas.

**Comment by storm1kk** [comment]
Hi guys! It is not possible to use strimzi helm chart as external dependency because of this error. Any chance to shrink description?

**Comment by mark-rushakoff** [comment]
I just ran into this when I was following the quickstart for kind at https://strimzi.io/quickstarts/.

```bash
#!/bin/bash

set -eu -o pipefail

kind create cluster --name strimzi-test

kubectl --context kind-strimzi-test create namespace kafka
kubectl --context kind-strimzi-test -n kafka apply -f 'https://strimzi.io/install/latest?namespace=kafka'
```

Output:

```
Creating cluster "strimzi-test" ...
 ✓ Ensuring node image (kindest/node:v1.20.2) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-strimzi-test"
You can now use your cluster with:

kubectl cluster-info --context kind-strimzi-test

Thanks for using kind! 😊
namespace/kafka created
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-entity-operator-delegation created
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator created
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-topic-operator-delegation created
customresourcedefinition.apiextensions.k8s.io/kafkausers.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkarebalances.kafka.strimzi.io created
deployment.apps/strimzi-cluster-operator created
customresourcedefinition.apiextensions.k8s.io/kafkamirrormaker2s.kafka.strimzi.io created
clusterrole.rbac.authorization.k8s.io/strimzi-entity-operator created
clusterrole.rbac.authorization.k8s.io/strimzi-cluster-operator-global created
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-kafka-broker-delegation created
rolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator created
clusterrole.rbac.authorization.k8s.io/strimzi-cluster-operator-namespaced created
clusterrole.rbac.authorization.k8s.io/strimzi-topic-operator created
clusterrolebinding.rbac.authorization.k8s.io/strimzi-cluster-operator-kafka-client-delegation created
clusterrole.rbac.authorization.k8s.io/strimzi-kafka-client created
serviceaccount/strimzi-cluster-operator created
clusterrole.rbac.authorization.k8s.io/strimzi-kafka-broker created
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkabridges.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkaconnectors.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkaconnects2is.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkaconnects.kafka.strimzi.io created
customresourcedefinition.apiextensions.k8s.io/kafkamirrormakers.kafka.strimzi.io created
configmap/strimzi-cluster-operator created
The CustomResourceDefinition "kafkas.kafka.strimzi.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

But it succeeds if I switch from `kubectl apply` to `kubectl create`.

I searched the recent pull requests for `kind` but it doesn't look like anyone has opened a PR to update the directions there.

**Comment by mark-rushakoff** [comment]
@scholzj you're right -- my mistake. I must have transcribed that line rather than copying and pasting. Force of habit to `kubectl apply -f` so I completely overlooked `create`. Sorry for causing confusion.

**Comment by scholzj** [comment]
Yeah, I have the same problem. `kubectl apply` will work again in 0.23 after we removed the older APIs.
