### ISSUE TITLE
Remove the legacy listener handling from the Cluster Operator

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4630]
In `v1beta2` we now support only the new Array based listeners. The `KafkaCluster` class still handles both object and array listeners in `fromCrd`. We should remove the support for the object listener from it.

_(The fields should still remain present in the `api` module for the time being)_

**Comment by rareddy** [comment]
@scholzj taking a look at this you guys already abstracted away the Object-based listener in the `ArrayOrObjectKafkaListeners` class in the API module, which you are saying do not modify, not sure what is left over to do in this?

**Comment by scholzj** [comment]
There is a little bit of it in the `fromCrd()` method in `KafkaCluster`. Maybe you can check that the array based listener config is present and use it directly + possibly some tests in `KafkaClusterTest` maybe? But maybe it is not worth touching until it we remove it from the API ... up to you.

**Comment by echernous** [comment]
Hi @rareddy , wanted to check if you are working on this issue or maybe I can pick it up? Thank you!

**Comment by rareddy** [comment]
all yours @echernous I did not get time to look into this again.

**Comment by echernous** [comment]
The PR got merged, closing
