### ISSUE TITLE
KafkaAvailability's logging should include the Reconciliation

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#4647]
`KafkaAvailability` is used during rolling restarts to determine whether a broker can be rolled without impacting producers with `acks=all`. When the CO is watching multiple `Kafka` CRs there can be multiple rolling restarts happening simultaneously. To make the logging unambiguous, `KafkaAvailability` should use a `Reconciliation`  instance as a prefix to all its logging statements, as `KafkaRoller` does for (almost) all of its logging.

If we can fix the one `KafkaRoller` logging stmt which lacks the Reconciliation too, that would be great.

**Comment by SmileyJames** [comment]
Wondering if this can be closed? Looks like a [PR](https://github.com/strimzi/strimzi-kafka-operator/pull/4709) was merged to resolve this issue.

**Comment by scholzj** [comment]
Thanks @SmileyJames ... I will close it, it should be indeed fixed.
