### ISSUE TITLE
Observability of rolling restarts via Events

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#4648]
Currently it's not very easy to see whether a particular pod was restarted by the operator and why such a CO-initiated restart was necessary. I think the only place this is really observable is in the CO logs. It would be good if this information was a little more accessible (searching the logs is tedious, especially when they're verbose, or the information might not be available depending on how the logging is configured).

Generating a Kubernetes `Event` against each pod that's rolled might be a better way of surfacing this. I think that's better than putting a condition in the CR status because it remains even after the next reconciliation. WDYT @strimzi/maintainers?

**Comment by scholzj** [comment]
Done in #6663
