### ISSUE TITLE
Filtering logging per Kafka CR

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#4653]
It would be really useful to be able to selectively filter logging so that we can get more info about a particular cluster (or more generally a particular CR), and carry on logging the rest normally. I think this can be done using log4j2 [`Markers`](https://logging.apache.org/log4j/2.x/manual/markers.html). Specifically I think each namespace would correspond to a `Marker`, and each CR in that namespace a child Marker (or maybe a single `ns/name` marker), and we could store a `Marker` in a `Reconciliation`, which we pass around widely already for logging purposes. Log4j2 can [filter using markers](https://logging.apache.org/log4j/2.x/manual/filters.html#MarkerFilter). 

Note: we can't use the `DynamicThresholdFilter` filtering which uses a `ThreadContext`-bound map because Vertx means that we jump around between threads all the time.

One way to do this would be to write our own Logger wrapper which looked like this:

```java
class LoggerWrapper {
    private final Logger log4j2Logger;
    public LoggerWrapper(Logger log4j2Logger) {
        this.logger = log4j2Logger
    }

    public void debug(Reconciliation r, String msg, Object arg) {
        this.logger.debug(r.marker, "{}: " + msg, r, arg);
    }

    public void debug(Reconciliation r, String msg, Object arg1, Object arg2) {
        this.logger.debug(r.marker, "{}: " + msg, r, arg1, arg2);
    }
}
```

Dealing with the varargs versions would be slightly painful, but it would generally simplify the logging stmt callsites and also prevent people from omitting the `Reconciliation` in classes where this was used, resulting in more consistency.

**Comment by srisatya1197** [comment]
Is anyone working on this issue?

**Comment by scholzj** [comment]
@tombentley I do not think anyone is working on this, or?
