### ISSUE TITLE
Prometheus metric to detect if the Operator is failing to reconcile

### ISSUE THREAD

**Issue by obrienrobert** [strimzi/strimzi-kafka-operator#4674]
**Is your feature request related to a problem? Please describe.**
A metric exists to detect if Strimzi resources are failing to reconcile (`strimzi_reconciliations_failed_total`), but no metric exists to detect if the Operator itself is failing to reconcile. The reason this is being requested is due to the same issue as reported in [4471](https://github.com/strimzi/strimzi-kafka-operator/issues/4471).

**Describe the solution you'd like**
A new metric within the Strimzi Operator of type counter that increases every time the Operator fails to reconcile, something like:
`strimzi_operator_reconciliations_failed_total`, for example. This would allow Prometheus alerts to be created which trigger when the operator fails to reconcile.

**Additional context**

**Comment by scholzj** [comment]
What does _Operator itself is failing to reconcile_ mean? The operator does not reconcile itself. So I do not think it can give you any metrics about this.

**Comment by scholzj** [comment]
The operator is running in loops and doing reconciliations => that is what it is reporting in its metrics. The only thing which can happen when it stops working is that the probes fail. But it can hardly send you alert when it is not working or stuck. But there are several metrics about the reconciliations => so I think you should be able to use these to detect that no reconciliations are happening anymore and raise an alert.

**Comment by obrienrobert** [comment]
@scholzj thank you for the info. I can take a look at the existing metrics and see If I can create an alert based on these. The `strimzi_reconciliations_periodical_total` metric looks like it might be helpful here.

**Comment by scholzj** [comment]
Triaged on 12.4.2022: Can be closed. the total reconciliation metric should cover this scenario.
