### ISSUE TITLE
Add support for topic creation, deletion and partition creation quotas

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4678]
Since Kafka 2.7, quotas for creation / deletion of topics and creation of partitions can be configured. This was implemented in [KIP-599](https://cwiki.apache.org/confluence/display/KAFKA/KIP-599%3A+Throttle+Create+Topic%2C+Create+Partition+and+Delete+Topic+Operations). It should be configured using the `controller_mutation_rate` quota. It might be interesting to add this quota to the User Operator and support it in the `KafkaUser` resource.

**Comment by srisatya1197** [comment]
Is anyone working on this issue?

**Comment by scholzj** [comment]
Not as far as I know, feel free to go for it

**Comment by ShubhamRwt** [comment]
@srisatya1197 Hii, I was hoping to work on this, are you working on this issue or not?

**Comment by srisatya1197** [comment]
@ShubhamRwt yeah you can work on it.

**Comment by ShubhamRwt** [comment]
Okay, Thankyou

**Comment by scholzj** [comment]
Done in #5059
