### ISSUE TITLE
Kafka connect cluster build failing

### ISSUE THREAD

**Issue by tope94** [strimzi/strimzi-kafka-operator#4691]
Trying to deploy the kafka connect cluster but it keeps failing/showing pending when i check the pods. is there anything im doing wrong. Thanks 
![EROOR](https://user-images.githubusercontent.com/67329652/113209896-9e390a80-9241-11eb-8e88-ca23365962a8.PNG)
![connect](https://user-images.githubusercontent.com/67329652/113210134-e8ba8700-9241-11eb-82ab-f41df1de9a20.PNG)

**Comment by scholzj** [comment]
I guess you would need to check the logs from the operator pod and from the build pod which is in error. I do not see any credentials for the registry to upload the image. Do you have them out of the box on the worker node or use KIAM or something like that? The credentials from the `externalConfiguration` section will not be applied to the build.

**Comment by tope94** [comment]
This is from the operator pod and build log. 
![pod](https://user-images.githubusercontent.com/67329652/113224431-7190ed00-9259-11eb-90f0-f15b89755d6b.PNG)


![log](https://user-images.githubusercontent.com/67329652/113224559-bc126980-9259-11eb-8fc4-c69e5998170f.PNG)

The registry is public so i didn't create a secret for that. i'm using ecr. Also my plugins are in aws s3 buckets because i can't find url links for them, (kafka-connector-jdbc, kafka-connector-elasticsearch) they are stored in S3 so i'm using S3 links and the externalCOnfiguration section has the access keys and secret keys to be able to access the information.
Is this process going to work?

**Comment by scholzj** [comment]
Well, the error from the build pod quite clearly shows that it is unauthorized to push to the registry. So maybe it is public for reading but not for pushing. So you will need to provide docker credentials for it.

**Comment by tope94** [comment]
I got it working, but the pod is now in a crashloopbackoff and can't figure out why
![podconnect](https://user-images.githubusercontent.com/67329652/113234786-ec650280-926f-11eb-9e66-64e2ca0d47cb.PNG)

**Comment by scholzj** [comment]
Looks like the image is somehow wrong? If you can share the full logs from the operator (as a text) and full versions of your CRs (as a text) maybe they show something more. This could be caused for example by using a badly configured base image etc. Also, if you can share it as a text and your repository is public for pulling as you said, I would be able to have a look at the image it build and maybe see if there is something wrong with it.

**Comment by tope94** [comment]
[operator-logs.TXT](https://github.com/strimzi/strimzi-kafka-operator/files/6243570/operator-logs.TXT)
[kafkaconnect.TXT](https://github.com/strimzi/strimzi-kafka-operator/files/6243592/kafkaconnect.TXT)

I changed the repository to private which enabled it work and not deny the access. I followed the documentation for building connector plugins with kafka-connect
[kafkaconnect-build.TXT](https://github.com/strimzi/strimzi-kafka-operator/files/6243645/kafkaconnect-build.TXT)

**Comment by scholzj** [comment]
Unfortunately, the operator log is not complete. So I do not see from it how the operator is configured and what will it use as base image. And the build pod is just a YAML, so it doesn§t show the Dockerfile either. Can you either get the full log or share the Dockerfile at least? It should be in ConfigMap named `my-connect-cluster-connect-dockerfile`.

**Comment by tope94** [comment]
[dockerfile.TXT](https://github.com/strimzi/strimzi-kafka-operator/files/6244161/dockerfile.TXT)
 This is the dockerfile in the configMap. The operator log is endless

**Comment by scholzj** [comment]
So, the file looks ok. The part which I can reproduce seems to work fine (i.e. without the connectors with unaccessible URLs). So I'm afraid all seems fine on my end and there is not much more I can do.

**Comment by tope94** [comment]
any ideas why the pods keep crashing since there was no problems with the built image? the connector are elasticsearch and jdbc plugins from my bucket

**Comment by scholzj** [comment]
Well, it is not crashing for me - so I do not know. It looks like the image is somehow wrong or is missing the expected interface (scripts).

**Comment by tope94** [comment]
It is running now, took out the external configurations with env and it fixed it.

**Comment by scholzj** [comment]
That is weird. No idea why would that cause issues 🤔

**Comment by tope94** [comment]
Yes very weird but thanks for your help
