### ISSUE TITLE
Helm chart v0.22.1 failed to upgrade Strimzi operator to support v1beta2 API

### ISSUE THREAD

**Issue by tringuyen-yw** [strimzi/strimzi-kafka-operator#4698]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
Upgraded Strimzi operator from `0.21.1` to `0.22.1`
Then follow the instrucstion in
[7.2.2. Converting custom resources configuration files using the API conversion tool](https://strimzi.io/docs/operators/in-development/deploying.html#proc-upgrade-cli-tool-files-str) to convert CRD from `v1beta1` to `v1beta2`

**To Reproduce**

Current Strimzi operator is at version `0.21.1`. Upgrade to latest version by

```
helm repo update
helm upgrade nystrimzi strimzi/strimzi-kafka-operator --namespace myns
```
Then use `bin/api-conversion.sh` downloaded from [release, api-conversion-0.22.1.zip](https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.22.1/api-conversion-0.22.1.zip)

- `bin/api-conversion.sh convert-file` : works OK
- `bin/api-conversion.sh convert-resource --all-namespaces`: works OK

In spite of the seemingly successful output , such as "Kafka resource named myexistingcluster1 in namespace kafka has been converted". The existing resources seems NOT to be converted. They still show `apiVersion: kafka.strimzi.io/v1beta1`
```
kubectl get kafka/myexistingcluster1 -n kafka -o yaml
```

The step "Upgrading CRDs to v1beta2" failed"

```
bin/api-conversion.sh crd-upgrade -d

Changing stored version in all Strimzi CRDs to v1beta2:
Updating KafkaConnector CRD

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PATCH at: https://MYCLUSTER.azmk8s.io/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/kafkausers.kafka.strimzi.io.
 Message: CustomResourceDefinition.apiextensions.k8s.io "kafkausers.kafka.strimzi.io" is invalid: spec.versions: Invalid
 value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1beta1", Se
rved:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceVali
dation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.Cu
stomResourceColumnDefinition(nil)}, apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:
false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subre
sources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnD
efinition(nil)}}: must have exactly one version marked as storage version. Received status: Status(apiVersion=v1, code=4
22, details=StatusDetails(causes=[StatusCause(field=spec.versions, message=Invalid value: []apiextensions.CustomResource
DefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name:"v1beta1", Served:true, Storage:false, Deprecated:f
alse, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextens
ions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}, ap
iextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:true, Storage:false, Deprecated:false, DeprecationWa
rning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidation)(nil), Subresources:(*apiextensions.CustomResource
Subresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomResourceColumnDefinition(nil)}}: must have exactly on
e version marked as storage version, reason=FieldValueInvalid, additionalProperties={})], group=apiextensions.k8s.io, ki
nd=CustomResourceDefinition, name=kafkausers.kafka.strimzi.io, retryAfterSeconds=null, uid=null, additionalProperties={}
), kind=Status, message=CustomResourceDefinition.apiextensions.k8s.io "kafkausers.kafka.strimzi.io" is invalid: spec.ver
sions: Invalid value: []apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{Name
:"v1beta1", Served:true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.Cust
omResourceValidation)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]ap
iextensions.CustomResourceColumnDefinition(nil)}, apiextensions.CustomResourceDefinitionVersion{Name:"v1alpha1", Served:
true, Storage:false, Deprecated:false, DeprecationWarning:(*string)(nil), Schema:(*apiextensions.CustomResourceValidatio
n)(nil), Subresources:(*apiextensions.CustomResourceSubresources)(nil), AdditionalPrinterColumns:[]apiextensions.CustomR
esourceColumnDefinition(nil)}}: must have exactly one version marked as storage version, metadata=ListMeta(_continue=nul
l, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failur
e, additionalProperties={}).
```

Keep repeating `bin/api-conversion.sh crd-upgrade -d` seems to see progress, each time the output involves another CRD
```
Changing stored version in all Strimzi CRDs to v1beta2:                                                                 
Updating v1beta1 version of Kind KafkaUser to be served but not stored                                                  
Updating v1alpha1 version of Kind KafkaUser to be served but not stored                                                 
Updating KafkaUser CRD                                                                                                  
... skip exception msg ...

Changing stored version in all Strimzi CRDs to v1beta2:
Updating v1alpha1 version of Kind KafkaBridge to be served but not stored
Updating KafkaBridge CRD
... skip exception msg ...

Changing stored version in all Strimzi CRDs to v1beta2:
Updating v1alpha1 version of Kind KafkaConnector to be served but not stored
Updating KafkaConnector CRD
... skip exception msg ...

Changing stored version in all Strimzi CRDs to v1beta2:
Updating v1beta1 version of Kind KafkaTopic to be served but not stored
Updating v1alpha1 version of Kind KafkaTopic to be served but not stored
Updating KafkaTopic CRD
... skip exception msg ...

Changing stored version in all Strimzi CRDs to v1beta2:
Updating v1alpha1 version of Kind KafkaRebalance to be served but not stored
Updating KafkaRebalance CRD
... skip exception msg ...

Changing stored version in all Strimzi CRDs to v1beta2:                                                                 
Updating v1beta1 version of Kind Kafka to be served but not stored                                                      
Updating v1alpha1 version of Kind Kafka to be served but not stored                                                     
Updating Kafka CRD                                                                                                      
... skip exception msg ...
```

But the exceptions seems to be persisitent as the same failed output keeps repeating. Attempt to create a Kafka cluster with `apiVersion: kafka.strimzi.io/v1beta2` failed with error:

```
kubectl apply -f deploy/mykafka.yaml
error: unable to recognize "deploy/mykafka.yaml": no matches for kind "Kafka" in version "kafka.strimzi.io/v1beta2"
```

**Expected behavior**

`bin/api-conversion.sh crd-upgrade -d`  should succeed in one go. And allow to create resource with `kafka.strimzi.io/v1beta2` API version

**Environment (please complete the following information):**
 - Strimzi version: 0.2.1 upgraded to 0.22.1
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes version 1.19.7
 - Infrastructure: Azure AKS

**YAML files and logs**

The `deploy/mykafka.yaml` which had failed to be created 

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kkbugreport
  namespace: tridebug
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        #authentication:
        #  type: tls
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        #authentication:
        #  type: tls
        configuration:

    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
    storage:
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
  zookeeper:
    replicas: 1
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    resources: {}
    storage:
      deleteClaim: false
      size: 1Gi
      type: persistent-claim

  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Additional context**

**Comment by scholzj** [comment]
It looks like you do not have the CRDs from 0.22 installed. Can you check them if they contain the `v1beta2` version?

**Comment by tringuyen-yw** [comment]
How can I check and if there is none, how can I install?

**Comment by scholzj** [comment]
You can run something like this:

```
kubectl get crd kafkas.kafka.strimzi.io -o jsonpath="{.spec.versions[*].name}"
```

And it should print something like this when the CRDs from 0.22 are installed:

```
v1beta2 v1beta1 v1alpha1
```

I'm not a Helm user. So I do not know why they would not upgrade. I use the YAML files (you can get the ZIP on the release page and just use `kubectl replace -f` - you should be able to use it to update the CRDs manually). But if you don't have the `v1beta2` that would explain why the conversion tool doesn't work.

**Comment by tringuyen-yw** [comment]
Confirmed the manual upgrade to `0.22.1` works. This must have been a flaw in the helm chart v0.22.1 which didn't update the physical strimzi operators. This issue is probably relevant I am going to edit the title to mention that is rather a helm chart bug.

Here is the manual procedure in case this helps someone having the same troubles to upgrade the Strimzi api to the new version `v1beta2`:

```
cd ~/Downloads
wget https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.22.1/strimzi-0.22.1.tar.gz
tar xzvf strimzi-0.22.1.tar.gz
cd ./strimzi-0.22.1/install

kubectl replace -f ./cluster-operator/
kubectl replace -f ./strimzi-admin/
kubectl replace -f ./topic-operator/
kubectl replace -f ./user-operator/

# is there `v1beta2` support?
kubectl get crd kafkas.kafka.strimzi.io -o jsonpath="{.spec.versions[*].name}{'\n'}"
v1beta2 v1beta1 v1alpha1

wget https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.22.1/api-conversion-0.22.1.tar.gz
tar xzvf api-conversion-0.22.1.tar.gz
cd ./api-conversion-0.22.1

# convert existing Strimzi managed resources to `v1beta2`
bin/api-conversion.sh convert-resource --all-namespaces

# Upgrading CRDs to v1beta2
bin/api-conversion.sh crd-upgrade --debug
```

**Comment by raj-saxena** [comment]
👆🏼 Small addition to above: before the `replace` step, change namespace of the `RoleBinding`s and `ClusterRoleBinding`s to the appropriate value from the default `myproject`

**Comment by scholzj** [comment]
@hari819 What Helm Chart are you installing? There is no kind `kafka-strimzi`. So I'm not sure what does this error really mean.

**Comment by hari819** [comment]
@scholzj  , yes  , i have corrected it to "kafka" , works fine. ,

thanks,

**Comment by rsoni43** [comment]
@scholzj I am facing the similar issue, i was running strimizi with 0.18.0 and kafka 2.5.0, and directly bumped the 0.18.0 to 0.22.0/0.22.1. Now,
I cannot see kafka in my kafka namespace and deployment of strimzi-operation is into crashloop back.

Secondly i cannot see any CRD's when i use

```
kubectl get crd kafkas.kafka.strimzi.io -o jsonpath="{.spec.versions[*].name}"
```

Error that i see in the operation log :

```
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator 2021-05-22 20:05:02 INFO  Main:60 - ClusterOperator 0.22.1 is starting
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator 2021-05-22 20:05:03 ERROR PlatformFeaturesAvailability:152 - Detection of Kubernetes version failed.
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:54) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:489) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:150) ~[io.strimzi.operator-common-0.22.1.jar:0.22.1]

strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at java.lang.Thread.run(Thread.java:834) [?:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator Caused by: java.net.SocketException: Broken pipe (Write failed)
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110) ~[?:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at java.net.SocketOutputStream.write(SocketOutputStream.java:150) ~[?:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:319) ~[?:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1202) ~[?:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at okio.Okio$1.write(Okio.java:79) ~[com.squareup.okio.okio-1.15.0.jar:?]

strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator 2021-05-22 20:05:03 ERROR Main:89 - Failed to gather environment facts
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.dsl.internal.ClusterOperationsImpl.fetchVersion(ClusterOperationsImpl.java:54) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.fabric8.kubernetes.client.DefaultKubernetesClient.getVersion(DefaultKubernetesClient.java:489) ~[io.fabric8.kubernetes-client-5.0.2.jar:?]
strimzi-cluster-operator-7bc76f4cb7-cc277 strimzi-cluster-operator      at io.strimzi.operator.PlatformFeaturesAvailability.lambda$getVersionInfoFromKubernetes$5(PlatformFeaturesAvailability.java:150) ~[io.strimzi.operator-common-0.22.1.jar:0.22.1]

```

Anything that you think that i might be missing ?

**Comment by scholzj** [comment]
@rsoni43 I do not why the CRDs did not installed for you. Are you using Helm 3? TBH, I'm not using Helm and do not understand it. The connection error was reported by some user yesterday on Slack. broken-pipe suggests some connectivity issue to the Kube API server. But I have never seen this, so not sure what would be the cause

**Comment by rsoni43** [comment]
Thank you @scholzj for your prompt response, no i have been using terraform to manage this.
I have also tried to do a curl to k8s api server from the same namespace just to check that api is accessible and it was working fine.

**Comment by uqix** [comment]
It seems that old apiVersion with new options works, e.g. 

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
..
spec:
  build:
    output:
      type: docker
      additionalKanikoOptions: [--insecure]
```

**Comment by scholzj** [comment]
It does work with the new options, that is expected. But the old APIs are removed in 0.23 => 0.23 and newer supports only `v1beta2`.

**Comment by uqix** [comment]
@scholzj so we can use old apiVersion with new options before this issue resolved

**Comment by scholzj** [comment]
@uqix Sorry, what issue exactly do you have in mind?

**Comment by uqix** [comment]
@scholzj 
After upgrading Strimzi helm chart from 0.21.1 to 0.22.1, no v1beta2 API available
> Helm chart v0.22.1 failed to upgrade Strimzi operator to support v1beta2 API

**Comment by scholzj** [comment]
Ahh, ok ... well, as far as I understood, Helm 3 does not upgrade the CRDs anymore. So you basically need to do it manually. For more info see https://strimzi.io/docs/operators/latest/full/deploying.html#upgrading_the_cluster_operator_using_helm_chart or https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

**Comment by tusharbhasme** [comment]
@tringuyen-yw we are at the same crossroads right now while trying to upgrade our Strimzi cluster from 0.19.1 to latest 0.27.0.
We have been using helm to manage two charts:
1. strimzi-operator
2. kafka

where strimzi-operator manager the operator and all CRDs while the kafka chart manages the kafka resources like kafka and zookeeper pods etc.
While upgrading to version 0.22.0 as per you solution, we manually replaced the CRDs using `kubectl replace`. After this, we modified the kafka resource yamls as per v1beta2 schema and tried to apply by upgrading the kafka helm chart, but helm does not recognize the resources it created in past anymore and threw error:
```
helm upgrade kafka ./kafka                 
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: kafka, name: kafka, existing_kind: kafka.strimzi.io/v1beta2, Kind=Kafka, new_kind: kafka.strimzi.io/v1beta2, Kind=Kafka
```
The kafka resource still has the label `app.kubernetes.io/managed-by=Helm`.

Did you face a similar issue or was ur setup different?

**Comment by tusharbhasme** [comment]
> @tringuyen-yw we are at the same crossroads right now while trying to upgrade our Strimzi cluster from 0.19.1 to latest 0.27.0. We have been using helm to manage two charts:
> 
> 1. strimzi-operator
> 2. kafka
> 
> where strimzi-operator manager the operator and all CRDs while the kafka chart manages the kafka resources like kafka and zookeeper pods etc. While upgrading to version 0.22.0 as per you solution, we manually replaced the CRDs using `kubectl replace`. After this, we modified the kafka resource yamls as per v1beta2 schema and tried to apply by upgrading the kafka helm chart, but helm does not recognize the resources it created in past anymore and threw error:
> 
> ```
> helm upgrade kafka ./kafka                 
> Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: kafka, name: kafka, existing_kind: kafka.strimzi.io/v1beta2, Kind=Kafka, new_kind: kafka.strimzi.io/v1beta2, Kind=Kafka
> ```
> 
> The kafka resource still has the label `app.kubernetes.io/managed-by=Helm`.
> 
> Did you face a similar issue or was ur setup different?

OK, so we got through after running the `resource-update` and `crd-update` scripts **before** running `help upgrade`.

**Comment by lsolisc** [comment]
you can solve it by modifying the crd, in my case the version of kubernetes modified the original resource preventing the change of version, I made the adjustments manually to the CRD and replace the existing one, I leave you the version of my resource.

`kubectl replace -f `

[kafkas.kafka.strimzi.io-0.22.0.yml.zip](https://github.com/strimzi/strimzi-kafka-operator/files/9619199/kafkas.kafka.strimzi.io-0.22.0.yml.zip)

**Comment by oanasc** [comment]
There is indeed a problem with the CRD's in versions 0.22.0 and 0.22.1 in the helm directory, they are incorrect they don't support v1beta2.
Do not use this:
https://github.com/strimzi/strimzi-kafka-operator/tree/0.22.0/helm-charts/helm3/strimzi-kafka-operator/crds
https://github.com/strimzi/strimzi-kafka-operator/tree/0.22.1/helm-charts/helm3/strimzi-kafka-operator/crds
The CRD's in the release assets are good. Use these:
* https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.22.0
* https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.22.1
