### ISSUE TITLE
Running strimzi without cluster role, cluster level permisisons

### ISSUE THREAD

**Issue by qldosdme0** [strimzi/strimzi-kafka-operator#4721]
Hey,

Installed Strimzi on kubernetes and found it requires cluster operator. Unfortunately, this has raised concerns + almost voiding the usage of it. The reason being there are other projects running on the cluster in other namespaces, don't want to open up / grant cluster permission to strimzi (in a nice way).

Is there a way to run strimzi without it requiring cluster level resources / cluster role binding?

I noticed company likes Redhat use strimzi - surely there must be a way? Can we change it to role binding - will it work?

**Comment by scholzj** [comment]
Duplicate to https://github.com/strimzi/strimzi-kafka-operator/discussions/4720
