### ISSUE TITLE
ssl handshake issue with 9093 port number in strimzi-kafka while producing messages

### ISSUE THREAD

**Issue by Cshanmukh80** [strimzi/strimzi-kafka-operator#4756]
**kafka.yaml**

[kafka.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6311585/kafka.zip)

**client-ssl.properties**

echo 'security.protocol=SSL
ssl.truststore.location=/tmp/kafka/kafka.truststore.jks
ssl.truststore.password=kafka123
ssl.enabled.protocols=TLSv1.2
ssl.endpoint.identification.algorithm=' > client-ssl.properties

**i am getting below error**

![Screenshot from 2021-04-14 11-57-07](https://user-images.githubusercontent.com/80450247/114730222-4d0b3980-9d5e-11eb-9bc6-224f04a9688f.png)

can you please give suggestion for this issue

**Comment by scholzj** [comment]
How does this differ from https://github.com/strimzi/strimzi-kafka-operator/discussions/4752? Why are you opening this as an enhancement? This is clearly not an enhancement and most probably not even a bug. Please continue in the discussion thread.
