### ISSUE TITLE
Enable external loadbalancer port type for Kafka-bridge

### ISSUE THREAD

**Issue by vijayrajah** [strimzi/strimzi-kafka-operator#4759]
**Is your feature request related to a problem? Please describe.**
Yes. when we deploy and kafka-bridge the HTTP port always gets deployed as cluster IP

**Describe the solution you'd like**
We should be able to have the option of deploying it as Loadbalancer IP

**Describe alternatives you've considered**
as current work around, I have created a service with the same selectors.
It would be nice to have this natively supported.

**Additional context**
This was discussed [here](https://github.com/strimzi/strimzi-kafka-operator/discussions/4757)

**Comment by scholzj** [comment]
I do not think we plan to support this right now. The HTTP interface is not secured in any way right now and it is expected to put behind some API gateway, authentication proxy etc. to be secured. Exposing the unsecured HTTP endpoint to the outside of the cluster makes only little sense. So if we would want to implement this, I think the security needs to come first.

**Comment by scholzj** [comment]
Triaged on 12.4.2022: Should be closed. There are currently no plans to add support for this. The first thing which would probably need to be solved is securing the Bridge HTTP API properly before we go and expose it.
