### ISSUE TITLE
Unable to renew Custom Cluster CA Certificates

### ISSUE THREAD

**Issue by tmitchell10** [strimzi/strimzi-kafka-operator#4769]
**Describe the bug**
I am attempting to renew the CA certificates in my Strimzi cluster and when I follow the instructions and replace the Cluster CA certificates, no pods roll, but the zookeeper pods issue error messages in the logs:

2021-04-16 15:07:59,715 WARN Exception caught (org.apache.zookeeper.server.NettyServerCnxnFactory) [nioEventLoopGroup-7-1]
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:336)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:185)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1380)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1275)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1322)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	... 17 more
	
**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy a cluster using custom certificates
2. Follow the Strimzi documentation to renew Custom CA certificates.
3. When the secrets are updated with the new CA Certificates and CA Keys, no pods roll, but the zookeeper logs start to show certificate error messages.

**Expected behavior**
I would expect to see the zookeeper, kafka and potentially the entity operator pods to roll in order to pick up the new CA certs.

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1
 - Installation method: YAML
 - Kubernetes cluster: 4.7
 - Infrastructure: 

**YAML files and logs**

**Additional context**

**Comment by scholzj** [comment]
I think @tombentley is working on some improvements and fixes to this. Is there actually any documentation for renewing custom certs? I do not remember any. I think until Tom fixes it you might need to roll some pods manually.

**Comment by tmitchell10** [comment]
This is the documentation link that I was following: https://strimzi.io/docs/operators/latest/using.html#renewing-your-own-ca-certificates-str

**Comment by beavenj** [comment]
Hi, I have been working with Tim on this one.. I also see the same problem which I think is the result of the certificates for the individual kafka and zookeeper nodes not being updated in the `<cluster>-kafka-brokers` and `<cluster>-zookeeper-nodes` secrets. Even if the nodes are manually rolled, when they start they select the CA certificate that matches their individual node certificate - which is the old one with the date in it after following the instructions above. The new certificate is never selected.

I have been looking at the code and the automation present in this area seems to be geared to handling the update of  generated certs that are due to expire rather than allowing the same for manually provided certificates. I'm still looking into it but before I go too much further I was wondering if there are plans for changes or fixes in this area as Jakub suggests.. @tombentley Can you advise here?

**Comment by chrispatmore** [comment]
Hi @scholzj I have an install which is using provided CA certificates, and during testing I have also seen that the replacement functionality documented here (https://strimzi.io/docs/operators/latest/using.html#renewing-your-own-ca-certificates-str) does not appear to be working. 

I see that you mention `I think until Tom fixes it you might need to roll some pods manually.` I am interested to know what pods / steps would need to be taken to get the certificates to replace successfully, so that they can be used as a potential workaround in the event that the provided CAs need to be replaced.

I am also interested to know if there is any expected timescale for when we might see these improvements from @tombentley

**Comment by scholzj** [comment]
> I am interested to know what pods / steps would need to be taken to get the certificates to replace successfully, so that they can be used as a potential workaround in the event that the provided CAs need to be replaced.

I would guess all of them ... ZooKeeper, Kafka, Entity Operator etc.

**Comment by chrispatmore** [comment]
We have done some experiments and come up with a script
```bash
#!/bin/bash
namespace=$NS
releaseName=$RELEASE
operatorLabel=strimzi.io
operatorNamespace=$OPERATOR_NS

echo "--- Delete all Kafka tls certificate secrets for recreation"
oc delete secret -n $namespace ${releaseName}-zookeeper-nodes
oc delete secret -n $namespace ${releaseName}-kafka-brokers
oc delete secret -n $namespace ${releaseName}-entity-operator-certs
echo "--- Delete Kafka operator pod to speed up reconcile"
oc delete pod -n ${operatorNamespace} -l app.kubernetes.io/name=ibm-events-operator,${operatorLabel}/kind=cluster-operator
echo "--- Wait for Kafka operator to recreate ZK certs"
oc get secret -n $namespace ${releaseName}-zookeeper-nodes
while [ ${?} == 1 ]; do 
    oc get secret -n $namespace ${releaseName}-zookeeper-nodes
    sleep 10s
done
echo "--- Bounce all ZK pods one at a time"
zkPodCount=$(oc get Kafka -n $namespace ${releaseName} -o jsonpath='{.spec.zookeeper.replicas}')
for podOrdinal in $(seq 0 $((zkPodCount=zkPodCount-1)))
do
  oc delete pod -n $namespace -l statefulset.kubernetes.io/pod-name=${releaseName}-zookeeper-${podOrdinal},${operatorLabel}/cluster=${releaseName}
  podReady=$(oc get pod -n $namespace -l statefulset.kubernetes.io/pod-name=${releaseName}-zookeeper-${podOrdinal},${operatorLabel}/cluster=${releaseName} -o jsonpath='{.items[0].status.containerStatuses[0].ready}')
  while [ "${podReady}" != "true" ]; do
    echo "Waiting for zookeeper pod ${releaseName}-zookeeper-${podOrdinal} to be ready"
    podReady=$(oc get pod -n $namespace -l statefulset.kubernetes.io/pod-name=${releaseName}-zookeeper-${podOrdinal},${operatorLabel}/cluster=${releaseName} -o jsonpath='{.items[0].status.containerStatuses[0].ready}')
    sleep 10s
  done
done
echo "--- Wait for Kafka operator to recreate broker certs"
while [ ${?} == 1 ]; do 
    oc get secret -n $namespace ${releaseName}-kafka-brokers
    sleep 10s
done
echo "--- Delete one broker pod, rest will get restarted one at a time automatically"
oc delete pod -n $namespace -l statefulset.kubernetes.io/pod-name=${releaseName}-kafka-0,${operatorLabel}/cluster=${releaseName}
echo "--- Wait for operator to recreate entity operator certs"
while [ ${?} == 1 ]; do 
    oc get secret -n $namespace ${releaseName}-entity-operator-certs
    sleep 10s
done
echo "--- Delete entity operator pod"
oc delete pod -n $namespace -l app.kubernetes.io/name=entity-operator,${operatorLabel}/cluster=${releaseName}
```

This *almost* brings everything back up to correct working order.
We can start sending data to Kafka again and ZK seems happy so that is good.
However the entity operator is stuck in crash loop backoff. Logs incoming

**Comment by chrispatmore** [comment]
Logs from entity operator pod
[tls-sidecar.log](https://github.com/strimzi/strimzi-kafka-operator/files/6618094/tls-sidecar.log)
[topic-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/6618095/topic-operator.log)
[user-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/6618096/user-operator.log)

**Comment by scholzj** [comment]
The Topic and User Operators fail because the TLS sidecar is not running. And I guess the sidecar fails because of this:

```
[!] error queue: crypto/x509/by_file.c:205: error:0B084009:x509 certificate routines:X509_load_cert_crl_file:PEM lib
[!] SSL_CTX_load_verify_locations: crypto/pem/pem_lib.c:842: error:0908F066:PEM routines:get_header_and_data:bad end line
[!] Service [zookeeper-2181]: Failed to initialize TLS context
```

It looks like it loaded the private key successfully before this. So this might be some issue with the Cluster CA public key which the `stunnel` application for some reason doesn't like?

**Comment by chrispatmore** [comment]
This seems odd because the CA is generated in the exact same way it was before regeneration, and all other components are happy with it. The only difference I can think of is that there is now a copy of the old CA also in the secret

**Comment by chrispatmore** [comment]
In a different file, as described by following the process in the documentation linked above

**Comment by chrispatmore** [comment]
I am wondering if it is this line
https://github.com/strimzi/strimzi-kafka-operator/blob/1fde1fbdfb20104bcf2519a8822a0b92b15c80b7/docker-images/kafka/stunnel-scripts/entity_operator_stunnel_config_generator.sh#L8
in the entity_operator_stunnel_config_generator which copies all the files into one file.

As each file does not have a trailing newline, this will cause problems when they are brought together.
We removed the trailing newline before adding to the CASecret as when it was there Zookeeper wouldn't start

**Comment by scholzj** [comment]
That could be the issue, yes. Let me give it some try.

**Comment by scholzj** [comment]
@chrispatmore You are right. This can cause the issue. I think you can workaround it by having a newline at the end of the CRT file => I would not expect that to break anything else - I guess that is how the CAs certs generated by Strimzi look like. I will also have a look and try to fix it in the code.

**Comment by chrispatmore** [comment]
We have been seeing having a newline causing an issue. When we have a newline at the end of our file ZK doesn't seem to start

**Comment by scholzj** [comment]
Well, but that seems to be how Strimzi does it and it works fine - we did not saw any issues. I assume this is not about a full empty line at the end of the file but about the `\n` at the end of the last line. My guess is that when you list the certificate, you get something like this:

```
kubectl get secret my-cluster-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d | sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'
-----BEGIN·CERTIFICATE-----¶
MIIFLTCCAxWgAwIBAgIUM+ogH+P+J95vIpCGrF6fgKpHsEAwDQYJKoZIhvcNAQEN¶
BQAwLTETMBEGA1UECgwKaW8uc3RyaW16aTEWMBQGA1UEAwwNY2x1c3Rlci1jYSB2¶
MDAeFw0yMTA2MDQxMjE1MzhaFw0yNDAyMjkxMjE1MzhaMC0xEzARBgNVBAoMCmlv¶
LnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwggIiMA0GCSqGSIb3DQEB¶
AQUAA4ICDwAwggIKAoICAQCyceRpfswmgpw4sbDoTGdv4ascGdAPca7yMk/WLz7l¶
kPXAwUW1bt4YFZ+9MsB1wo0U2wXzsdPR7yEvBwRHmiiZhmCQhGXWmsCK53rBerIo¶
YTqo92UTpABS9M58Dl66sQe1YBLWz/RvUtFuSXZ2TRyhfX3z/kFMpJX1KCqKx6cv¶
nbHWzha/VVfHPVe0l00HAs+tOU8k8HuCg+KXBjtLCzaWALXP1x00vfI56nAIj9VG¶
l7HLb6PLLqB1gI9IrzK4Q47XNILbvrGqSQlLyMZJWEFuor4M/scL/1v+0XnRi/rm¶
REwtCN3376rNztd/usXiC39UhAi3kI0oAVJjKfXB4XG/Q7lNa2yg9B67e5CJs0+/¶
AnoW0EdoBaI0MBAqbNow/dDF1rbPBrzHBq35e+m3BXK1H2hRrAVJGAl9pTB1EWMh¶
JyDNc9tUuASr9clw0zKkSeoMYjddTmEg5VKbaCb8gGIKpvfPzqGC8va+rL6Xb4sY¶
swGh6R/dxk7pRQPmnxAmFUmrzRRLB96WUupAPxU6D3wPJIEQ4JoVDVRgPlYFRAqB¶
nEdbhxj8kABhu3SNHYaO+Q7J/FBPWqR0EvspVOkyf9qKL2Kh2yprfJZfwC7n5gFV¶
lM4TFt728Pyo0sPv7NWiBuh1ZMZLK5j45etj2Us+sn/TEpRtTE3c9oiAoXwKJ44x¶
9QIDAQABo0UwQzAdBgNVHQ4EFgQU+scYptg58LG5ZO5m2YBU6/xlHc0wEgYDVR0T¶
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIB¶
AGw5eq2zfuyNe0yFF08BGWWDJ8wMSnUxgwDmlTtJn3djcQ7IRvY02GXL/HpEu0CM¶
RoWX/ysm3FnFZ4G6vF7PF7NpnOOchPFFoV0DrI7Ixrezp+vho+oD2PLFknmU8HUl¶
bzEuLZupkqa7yFVMg1ZSn+lYAERkN9PUHfvn4OQujNDoyPiCclyrhJM+TdlfYlZi¶
FkOZp2qwCH2gIIKYTzaSyZMwsmZ9UeGPRacnahS8awvQq/v0KAQ95gAlJvCJv9jG¶
sfoLCq2NXI9blXsbHpZo4cARIzd/NvWn7mnwAkSkXZ9hFi8A5P3G2cjhvBkkXjcC¶
NTh7w1XCW8YukY8U1UyGIyrnYIVQ2iJFyS4jxR5jlPPxfhJuWOzpZ1SmzXiPU8zU¶
+7gX1eMkuqFqGysBVBrPNyzGCrkdjPN6rOYZr7/ePfBzjS0+Ks1ZmK8eFUkPdciM¶
HFK4a587C30bLsynWyxOU97UAHi5a/hBjBToG9oeT8UTa1n720/iT1dkdp7q4uT7¶
klkMCgIlPjDhFfgt/k9NCjNp365GwNs18U9wZorCfsnJ/ZORjrArozKCVfCI/8jq¶
Pi4Lncp3bGcufYi6rgdTDPIjM7HoJmUM3LSC17lyBI4NalNPtQ2EtWl7vfH5P9n9¶
ZvOAOsgVKgccR2Ws3EFSjNwMXMHr1GpEUzRUM0BgvGat¶
-----END·CERTIFICATE-----
```

Where-as with the Strimzi generated certs you get this (notice the difference in the `-----END CERTIFICATE-----` line):

```
kubectl get secret my-cluster-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d | sed 's/ /·/g;s/\t/￫/g;s/\r/§/g;s/$/¶/g'
-----BEGIN·CERTIFICATE-----¶
MIIFLTCCAxWgAwIBAgIUM+ogH+P+J95vIpCGrF6fgKpHsEAwDQYJKoZIhvcNAQEN¶
BQAwLTETMBEGA1UECgwKaW8uc3RyaW16aTEWMBQGA1UEAwwNY2x1c3Rlci1jYSB2¶
MDAeFw0yMTA2MDQxMjE1MzhaFw0yNDAyMjkxMjE1MzhaMC0xEzARBgNVBAoMCmlv¶
LnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwggIiMA0GCSqGSIb3DQEB¶
AQUAA4ICDwAwggIKAoICAQCyceRpfswmgpw4sbDoTGdv4ascGdAPca7yMk/WLz7l¶
kPXAwUW1bt4YFZ+9MsB1wo0U2wXzsdPR7yEvBwRHmiiZhmCQhGXWmsCK53rBerIo¶
YTqo92UTpABS9M58Dl66sQe1YBLWz/RvUtFuSXZ2TRyhfX3z/kFMpJX1KCqKx6cv¶
nbHWzha/VVfHPVe0l00HAs+tOU8k8HuCg+KXBjtLCzaWALXP1x00vfI56nAIj9VG¶
l7HLb6PLLqB1gI9IrzK4Q47XNILbvrGqSQlLyMZJWEFuor4M/scL/1v+0XnRi/rm¶
REwtCN3376rNztd/usXiC39UhAi3kI0oAVJjKfXB4XG/Q7lNa2yg9B67e5CJs0+/¶
AnoW0EdoBaI0MBAqbNow/dDF1rbPBrzHBq35e+m3BXK1H2hRrAVJGAl9pTB1EWMh¶
JyDNc9tUuASr9clw0zKkSeoMYjddTmEg5VKbaCb8gGIKpvfPzqGC8va+rL6Xb4sY¶
swGh6R/dxk7pRQPmnxAmFUmrzRRLB96WUupAPxU6D3wPJIEQ4JoVDVRgPlYFRAqB¶
nEdbhxj8kABhu3SNHYaO+Q7J/FBPWqR0EvspVOkyf9qKL2Kh2yprfJZfwC7n5gFV¶
lM4TFt728Pyo0sPv7NWiBuh1ZMZLK5j45etj2Us+sn/TEpRtTE3c9oiAoXwKJ44x¶
9QIDAQABo0UwQzAdBgNVHQ4EFgQU+scYptg58LG5ZO5m2YBU6/xlHc0wEgYDVR0T¶
AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIB¶
AGw5eq2zfuyNe0yFF08BGWWDJ8wMSnUxgwDmlTtJn3djcQ7IRvY02GXL/HpEu0CM¶
RoWX/ysm3FnFZ4G6vF7PF7NpnOOchPFFoV0DrI7Ixrezp+vho+oD2PLFknmU8HUl¶
bzEuLZupkqa7yFVMg1ZSn+lYAERkN9PUHfvn4OQujNDoyPiCclyrhJM+TdlfYlZi¶
FkOZp2qwCH2gIIKYTzaSyZMwsmZ9UeGPRacnahS8awvQq/v0KAQ95gAlJvCJv9jG¶
sfoLCq2NXI9blXsbHpZo4cARIzd/NvWn7mnwAkSkXZ9hFi8A5P3G2cjhvBkkXjcC¶
NTh7w1XCW8YukY8U1UyGIyrnYIVQ2iJFyS4jxR5jlPPxfhJuWOzpZ1SmzXiPU8zU¶
+7gX1eMkuqFqGysBVBrPNyzGCrkdjPN6rOYZr7/ePfBzjS0+Ks1ZmK8eFUkPdciM¶
HFK4a587C30bLsynWyxOU97UAHi5a/hBjBToG9oeT8UTa1n720/iT1dkdp7q4uT7¶
klkMCgIlPjDhFfgt/k9NCjNp365GwNs18U9wZorCfsnJ/ZORjrArozKCVfCI/8jq¶
Pi4Lncp3bGcufYi6rgdTDPIjM7HoJmUM3LSC17lyBI4NalNPtQ2EtWl7vfH5P9n9¶
ZvOAOsgVKgccR2Ws3EFSjNwMXMHr1GpEUzRUM0BgvGat¶
-----END·CERTIFICATE-----¶
```

**Comment by chrispatmore** [comment]
Okay will do further investigation into the above.
One thing I have also just noticed is that once the CA changes, even if there is an old version of the CA in the secret. The operator pod attempts to talk to ZK using the new CA, even though the ZK certs have not yet changed. This causes the operator to fail, and a huge amount of certificate errors in the ZK pod logs.

**Comment by chrispatmore** [comment]
Running your above command we get
```
-----BEGIN·CERTIFICATE-----¶
MIIDODCCAiCgAwIBAgIQN/2mpErfFhfqaYk2KMgZJDANBgkqhkiG9w0BAQsFADAk¶
MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxCzAJBgNVBAMTAm15MB4XDTIxMDYwOTEx¶
MDkwNFoXDTIxMDkwNzExMDkwNFowPjEVMBMGA1UEChMMY2VydC1tYW5hZ2VyMSUw¶
IwYDVQQDExxJQk0gQXV0b21hdGlvbiBGb3VuZGF0aW9uIENBMIIBIjANBgkqhkiG¶
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyxRqf0/2Is8O1xDcmVQ9V9zmf/1cxsWdDPXl¶
rSEOHDmRtoHWDbIcTr34WO8FNke3DKAKozF47Av+5hLe+m4xajkDbubh4pIi8Da0¶
I89Zo9hjbtVPtHHIduoxW5zSAwLpFmbDCdBArtCxAwlDiKZ8AznaFnjP6WvVFaQX¶
CLuHbfdnxUNM2Iuz1kezVapU8ltDs9cCcRIkXG7KxgqqtbmuyL7gz73uWt6xICLt¶
8kzq+TQJDQKRyaez1LV14ZnC6YSIWvEZS6+4LAC6qb/MZMRASPpnEmovHqcLfiBs¶
AYT3V4YXTwH6M4y8tnWrDXzaDdr27XMNN5NrjY6IvkUNEKeIywIDAQABo0wwSjAO¶
BgNVHQ8BAf8EBAMCAoQwDwYDVR0TAQH/BAUwAwEB/zAnBgNVHREEIDAeghxJQk0g¶
QXV0b21hdGlvbiBGb3VuZGF0aW9uIENBMA0GCSqGSIb3DQEBCwUAA4IBAQCowus2¶
p29eR3qhaZFPusZg9UAUqBXBo+46oMyBLBbGQl6q0HTVedCjB4RA8lPBBiB4sAnp¶
FRsFMpZtlqLh907KURkMKBWyarQ5P5AWcoS5TJFcrNSjOuIqFTwcKB1cCXngWnsG¶
4mFrCsuXfIduktTWpcyv8LrGxrfMj5G0OWSE23tPE00s6phi43+blB9JPM/+i90S¶
0Ix8j/aEzJ4mTDNeUkCam/t1OP0kDn6xpbd7XaTnjytl3588Sqg0YR90hhILABca¶
A2d7t/l2Epa0fbx57gFEom9lBtymkPKX3ilOjLHkWUFlsw1FWptSeppFmekgjwAP¶
W4xklXbJefHDnXO1¶
-----END·CERTIFICATE-----¶
-----BEGIN·CERTIFICATE-----¶
MIIDBDCCAeygAwIBAgIQP+u8KSRKeHyDijHEwpLrlzANBgkqhkiG9w0BAQsFADAk¶
MRUwEwYDVQQKEwxjZXJ0LW1hbmFnZXIxCzAJBgNVBAMTAnNzMB4XDTIxMDYwOTEx¶
MDg0NloXDTIxMDkwNzExMDg0NlowJDEVMBMGA1UEChMMY2VydC1tYW5hZ2VyMQsw¶
CQYDVQQDEwJteTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKqVxM4U¶
eeJ94KHpOr+7j0Jlj6a+v4W5kSGS1odRNMOV5g9CRs/6u9Yuj/znugEA5dJtoJIH¶
zGUpNL3ZMYuqLqfj5tBehKMnFkmrODoxCKwYneFukTLdSinC813zphuuiyYFEV3f¶
8V3SHPcTYt4gf15nPO6O6qPRwa36b7g+L8xoUKJLxhmRv2K6Tkak/HodnCerqfjR¶
qf6unLzlVjtFTN5qmA3uTKFZPTw1AFL2gtUcduVmn/3s05ihRpyDJlgQT+z9/5ao¶
jhPfu+2qNUiHrN3cAC8jZFfQSUG3K2I881q/c88u4iONTIhpKIoT8tQGRg7gXRoB¶
2S7Sd3LN+LRTn9MCAwEAAaMyMDAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQF¶
MAMBAf8wDQYDVR0RBAYwBIICbXkwDQYJKoZIhvcNAQELBQADggEBAB2q43eMjSbA¶
lGVFRiiEBEdQz/oRI8G3e5gnkDo7H8mELQ0NrAxw1TZHEB3aZq6GyXUix0oR2wzE¶
owFJVt2xhYbzFMqP/nuoEjklLKRn610LSPl37hC2JP7/q41hn1alrzelWbStBcZ/¶
g1mRsrK4DWD4dK4jUCOIhb1bsMN/Gw2LO//SLJveKVofT7QhL3VfODrz+asWT+CS¶
5+k+FPLM/4f6pygqUaLQfasxciljhvJWv3lhXGPdpYkWJH+6YjnSgapyPn/UBHEU¶
UAhrVJgb6jUKbGdHf8Ogiuvkq2rlc1ktwNm06vIX84Kfs0PT6xEnL6NG8ysk0lSV¶
SkhtrVIH+HY=¶
-----END·CERTIFICATE-----¶
-----BEGIN·CERTIFICATE-----¶
MIIDBTCCAe2gAwIBAgIRAIIL/Foy2dIfRYiulv71JHQwDQYJKoZIhvcNAQELBQAw¶
JDEVMBMGA1UEChMMY2VydC1tYW5hZ2VyMQswCQYDVQQDEwJzczAeFw0yMTA2MDkx¶
MTA4MzFaFw0yMTA5MDcxMTA4MzFaMCQxFTATBgNVBAoTDGNlcnQtbWFuYWdlcjEL¶
MAkGA1UEAxMCc3MwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDWgy2G¶
JzzzcV/ci+42BV4VBIar3B0Q9V49UHvJ2XUGk2Q3kEJ9dMP0Win1da5v3Zrx064U¶
irTu3ayoOVFKjYueTbPPjz/brF8laJ0m2OsfXJXGQRyPTzhhJ3MtZ/3CVIE7stl3¶
6Qca3+zW2dh5nTbMA0Vkn1BfOhsH1NUJV2cn9VGcT/laL41XlQHsQP0aLQWD8eBO¶
VchioNpjyZ49xovzqImOxo1ALMh2zvtuibL8O8Pv4mQWWIw54NITgfSo4rHeEdMD¶
4t9uNLpA4Z/SaL4F9A51R8bMUTe5I1q8FRbSGbk5McyverNEAbS8hvAHngPaGQAp¶
M94k4HR8uxAwhCsZAgMBAAGjMjAwMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8E¶
BTADAQH/MA0GA1UdEQQGMASCAnNzMA0GCSqGSIb3DQEBCwUAA4IBAQDAKDV99psR¶
U21Htw5S7yqvOkTLsV+AvAbcUtaT11WmRnE1w8mx0R9v2VtvyNd1wsxDo9Gfv31s¶
5wn++eQ9lzGr2TgRmPVAHZFGsHy/dgjoAd4e93Yed/7W8+qTpKAAo6lLg27L8W9Y¶
oeLWP7lJC8vofp5Pxd6Zy53/idkm5P/x50aY32s0Cgpp9bYFwe13Yjv0BSiwpz7f¶
BTwxrrnA9dYIyEHDw/wKkLxZsNXzInpuBFhA/FBasL2xko9A1Lk1TItvQcdMaxt8¶
8JHJxQDiKA35TsZm/4giC01W4TDd1ke4eQXxut/Tq9M5PfkcgYcJnNTHGbo4TELA¶
PM41ZlldvpYo¶
-----END·CERTIFICATE-----¶
```

**Comment by chrispatmore** [comment]
Problem with newlines was an issue on our end, have solved and now entity operator pod seems to be fine again 👍

**Comment by scholzj** [comment]
I opened #5103 to fix the way how the certificates are merged. That should make sure that in the future it would not care about the new-line at the end.

**Comment by chrispatmore** [comment]
That's good however I have stumbled upon another potential problem with the entity operators connection to ZK.
It seems to depend on the order on which the different CA chains were appended to the single CA cert file in the tls sidecar

**Comment by chrispatmore** [comment]
That's good thanks, however there seems to be another issue. Which is that using a single file for multiple certificate chains doesn't seem to work.

If I put the single correct CA in a pem file and openssl to ZK it works
If I put an old CA in the same pem file after the correct one the openssl to ZK still works
If I put the old CA in the same pem file before the correct one the openssl to ZK fails.

This means that whether or not it can connect is dependent on the order in which 
` cat /etc/tls-sidecar/cluster-ca-certs/*.crt > "$CA_CERTS"`
appends the certs

**Comment by scholzj** [comment]
I'm not sure I understand why would the ordering matter. But there is currently no infrastructure to make it ordered differently from what is there.

**Comment by chrispatmore** [comment]
I am also not sure why it would matter but that is the behaviour we are seeing. Gonna try grab some logs for the sidecar

**Comment by scholzj** [comment]
It is also not clear to me why would this work for the Strimzi generated certs but not for your custom certs.

**Comment by scholzj** [comment]
(Hopefully the stunnel will be gone soon ... it seems to be quite sensitive on all kind of things which other applications don't care about)

**Comment by chrispatmore** [comment]
Agreed, Could it be because they have the same issuer etc. I feel like I remember seeing something in your code that slightly altered the subjects in the certs when they were regenerated
(this could be some other code I am remembering)

**Comment by scholzj** [comment]
We have the version sequence in the subject, that is true. Although I do not think this was introduced because of this problem, it could be why it works.

**Comment by chrispatmore** [comment]
Logs from sidecar when we have above issue.
Was working with just old CA certificate. And if we delete the old one leaving behind just the new one, it also works
[tls-sidecar.log](https://github.com/strimzi/strimzi-kafka-operator/files/6625532/tls-sidecar.log)

**Comment by chrispatmore** [comment]
Done some testing on this, and it does indeed appear to be the case that if you have two CAs in the same file with the same subject, the first one is always used. If they have different subjects it's fine

**Comment by chrispatmore** [comment]
After some more investigation, this seems to be because of the way our CA certificates are being generated. To be specific they are missing the `Subject Key Identifier` extension. Once this is added, having the two CAs with the same Subject works

**Comment by scholzj** [comment]
Interesting. Had no idea there is something like that. Well, thanks for figuring it out, this might be handy in the future as well.

**Comment by scholzj** [comment]
Triaged on 7th July 2022: Should be closed, seems to be explained.
