### ISSUE TITLE
Strimzi Cluster Operator with external Zookeeper

### ISSUE THREAD

**Issue by vinayakj-kaidee** [strimzi/strimzi-kafka-operator#4776]
**Is your feature request related to a problem? Please describe.**
We already have a zookeeper cluster running.
Is there anyway, we can point the strimzi cluster operator to deploy without zookeeper and use the already deployed one for kafka?

**Describe the solution you'd like**
Strimzi Cluster Operator should be able to deploy kafka with an external zookeper cluster setup instead of deploying zookeeper again.

**Describe alternatives you've considered**
The current solution that we see is to deploy kafka cluster without strimzi and then use the standalone topic operator and entity operator

**Comment by scholzj** [comment]
No, that is not possible today and  TBH I do not think we plan to support this. The focus will be on removing Zookeeper instead of adding new features to how it is used.

**Comment by levin81** [comment]
@scholzj jumping on this issue instead of opening a new one - but will a zookeeper-less configuration be available in strimzi 0.23? I saw that support for kafka 2.8 was merged, and was curious. Thanks

**Comment by scholzj** [comment]
No, it will for sure not be available in 0.23. AFAIU the Zookeeper-less support in 2.8 is for testing only. Also, we need to make sure we can properly upgrade the existing clusters etc., so we might not be able to support Zookeeper less mode until it is fully supported in Kafka itself.

**Comment by vinayakj-kaidee** [comment]
Hi 
Thanks for the clarification
I will close this issue as we are sure that the future goal for strimzi is to remove support for zookeeper once Kafka removes it.
