### ISSUE TITLE
Helm chart v0.22.1 creates 'v1alpha1' and 'v1beta1' CRDs with OpenAPIV3 structural schema violations

### ISSUE THREAD

**Issue by vitalyfilatov** [strimzi/strimzi-kafka-operator#4786]
**Describe the bug**
Helm chart v0.22.1 creates 'v1alpha1' and 'v1beta1' CRDs with OpenAPIV3 structural schema violations.
`kubectl describe crd kafkas.kafka.strimzi.io` says in paricular:
```
    Last Transition Time:  2021-04-21T06:53:06Z
    Message:               [spec.version[v1beta1].schema.openAPIV3Schema.properties[spec].properties[kafka].properties[listeners].oneOf[0].items.prop
erties[authentication].description: Forbidden: must be empty to be structural, ...
    Reason:                Violations
    Status:                True
    Type:                  NonStructuralSchema
```

**To Reproduce**
1. Install Kafka Operator Helm chart 0.22.1 via FluxCD + Helm Operator. Under the hood, Helm operator invokes 'helm' to install k8s resources.
2. All goes smoothly, no errors from Helm.
3. In Helm operator log I see that CRD was created:
```
ts=2021-04-21T06:53:04.229841638Z caller=helm.go:69 component=helm version=v3 info="creating 1 resource(s)" targetNamespace=kafka-system release=kafka-operator
ts=2021-04-21T06:53:05.146108355Z caller=helm.go:69 component=helm version=v3 info="creating 1 resource(s)" targetNamespace=kafka-system release=kafka-operator
```
3. However, when I run `kubectl describe crd kafkas.kafka.strimzi.io` I see in the very bottom of the output very-very long error message which refers to _v1alpha1_ and _v1beta1_ versions of _kafkas.kafka.strimzi.io_ CRD:
```
Conditions:
    Last Transition Time:  2021-04-21T06:53:06Z
    Message:               [spec.version[v1beta1].schema.openAPIV3Schema.properties[spec].properties[kafka].properties[listeners].oneOf[0].items.properties[authentication].description: Forbidden: must be empty to be structural, spec.version[v1beta1].schema.openAPIV3Schema.properties[spec].properties[kafka].properties[listeners].oneOf[0].items.properties[authentication].properties[accessTokenIsJwt].description: Forbidden: must be empty to be structural, ...
    Reason:                Violations
    Status:                True
    Type:                  NonStructuralSchema
```
4. See error messages above. I provided only a couple of complains in the output above, actually 'kubectl describe' contains a lot more complains. You can find full output of `kubectl describe` in the attached ZIP archive - [kafkas-crd.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6349664/kafkas-crd.zip).
5. So far, the CDR itself works and I can deploy Kafka cluster of _v1beta2_ version w/o any issue. However I want to get rid of the error messages above and make sure that this broken CRD won't prevent me from upgrading to future versions of Kafka operator.

**Expected behavior**
The `kafkas.kafka.strimzi.io` CRD is deployed without schema violation.

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes v1.16.15
 - Infrastructure: on-premise cluster
 - Helm version: 3.1.2

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

**Comment by scholzj** [comment]
Yes, the `v1alpha1` and `v1beta1` schemas are not structural. But that is not a bug - `apiextensions/v1beta1` do not require structural schemas and is not broken. Strimzi 0.23 will move to `apiextensions/v1` and will support only `v1beta2` which is structural as required by `apiextensions/v1`.

**Comment by vitalyfilatov** [comment]
@scholzj, thank you for yor reply.

So, v1alpha1 and v1beta1 versions will be removed as a part of upgrade to Strimzi 0.23, right? If yes, fee free to close this question.

**Comment by scholzj** [comment]
Yes, correct - they will be removed and the Strimzi 0.23 release will use the `apiextensions/v1` to make sure it works on Kube 1.22.
