### ISSUE TITLE
How to change the log level?

### ISSUE THREAD

**Issue by sneko** [strimzi/strimzi-kafka-operator#480]
Hi everyone 😀 

I was wondering if there is a way with the Strimzi operator to define the log level of each Kafka component (kafka cluster, zookeeper, connect)?

For example Zookeeper write several logs per second and that's not really helpful since they are just TRACE/DEBUG logs.

Thank you 👍

**Comment by sneko** [comment]
While looking for a solution I found it's possible to pass configuration to Zookeeper to:
https://github.com/strimzi/strimzi/search?utf8=%E2%9C%93&q=zookeeper-config&type=

I found that the log level could potentially be set like described in these links:
- https://github.com/strimzi/strimzi/blob/master/docker-images/zookeeper/config/log4j.properties
- https://github.com/apache/zookeeper/blob/master/conf/log4j.properties
- https://github.com/apache/kafka/blob/trunk/config/connect-log4j.properties
- https://github.com/apache/kafka/blob/trunk/config/log4j.properties

So finally I have this settings for my cluster:
```
  kafka-config: |-
    {
      "offsets.topic.replication.factor": 3,
      "transaction.state.log.replication.factor": 3,
      "transaction.state.log.min.isr": 2,
      "zookeeper.root.logger": "INFO, CONSOLE",
      "kafka.root.logger.level": "INFO",
      "log4j.rootLogger": "INFO"
    }

  zookeeper-config: |-
    {
      "zookeeper.root.logger": "INFO, CONSOLE",
      "zookeeper.console.threshold": "INFO",
      "zookeeper.log.threshold": "INFO",
      "log4j.appender.CONSOLE.Threshold": "INFO",
      "log4j.appender.ROLLINGFILE.Threshold": "INFO",
      "log4j.appender.TRACEFILE.Threshold": "INFO",
      "log4j.rootLogger": "INFO, CONSOLE"
    }
```

After applying changes, my cluster is updated one node by one node... but there is still these DEBUG logs... that's terrible x)

I don't understand anymore where I missed something... I will be grateful if you could help me with that 😃

**Comment by scholzj** [comment]
We have this on our TODO list, but didn't got to it yet. Setting the options in kafka-config and zookeeper-config will not work - these are just for Kafka and Zookeeper configuration, not the variables used in the log properties file.

In the meantime we can probably look into why does Zookeeper have `DEBUG` as default. I would expect more something like `INFO`.

@tombentley Do you remember why do we have `DEBUG` there? You did the logging file changes.

**Comment by tombentley** [comment]
Iirc, I just took the upstream logging config and modified it as minimal as
possible to parameterise the root logger level. I.e. the upstream had
showier logging at debug level.

Ultimately I think we should have the ability to configure an entire
logging config, not just change levels of a hard coded config.

**Comment by sneko** [comment]
@scholzj @tombentley Since several days I was trying to solve an issue: why some nodes of my cluster randomly go down... 😀 

I figured out that all these DEBUG(+INFO) logs were requiring a lot of resources to my logs collector (Fluentd) and my ElasticSearch storage (moreover there are 3 instances of Zookeeper).

The more appropriate solution for now is filtering Zookeeper logs by default by Fluentd instances but that's not the cleanest one since they still need to filter a huge amount of "useless" logs.

Do you have an approximative "release date" for the feature of customizing log level?

In the meantime, thank you for the operator it's worth it :)

**Comment by scholzj** [comment]
we are working on this. I expect that the log configuration for Kafka, Zookeeper etc. should land in master next week. Thanks for your patience.

**Comment by stanlyDoge** [comment]
Hi. There is PR for this feature.
https://github.com/strimzi/strimzi-kafka-operator/pull/512

**Comment by sneko** [comment]
@stanlyDoge thank you very much for working on this issue! I really appreciate and I will test this merge as soon as possible 😃

**Comment by sneko** [comment]
@stanlyDoge just a question, do you know when the 0.5.0 will be released please? (approximately)
