### ISSUE TITLE
io.vertx.core.VertxException: Connection was closed

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4813]
It looks like when the HTTP Client is used, following messages start appearing in the logs:

```
2021-04-24 23:02:43 ERROR HttpClientRequestImpl: - io.vertx.core.VertxException: Connection was closed
```

This is possibly related to the Vert.x 4 update?

**Comment by tomncooper** [comment]
Have you got the stacktrace? Just wondering what class this came from. The Vertx 4 upgrade did change some of the logic in the CC and Connect API clients.

**Comment by scholzj** [comment]
I do not think the exception bubbles up to our level. So all we see if the message above in the log which does not even show a line 🤷‍♂️
