### ISSUE TITLE
Make Kafka Connect Build work behind proxies

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4814]
As discussed in #4808, Kafka Connect build currently does not seem to work behind HTTP proxies. We should make it possible.

**Comment by Xan2063** [comment]
Usually we add some env vars to the container when dealing with the proxy
`FROM quai.io/strimzi/kafka:0.22.1-kafka-2.7.0
ENV https_proxy=proxy:8080
ENV http_proxy=proxy:8080
ENV no_proxy=localhost,127.0.0.1,companysite.com`

I think this solution [here](https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg)   is also possible and even better from security perspective as the values are not persisted in the image.

Not sure, how easy the setup is to build strimzi, but if you need something, just ping me.
Thanks
