### ISSUE TITLE
Unable to create type 'loadbalancer' in Azure with a private IP.

### ISSUE THREAD

**Issue by justin-silveri** [strimzi/strimzi-kafka-operator#4859]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
I'm trying to create a load balancer listener in Azure AKS for the kafka nodes with a private IP address following the documentation. Every time I try, the load balancer fails to create since it tries to attach to the public IP, which the cluster identity does not have permissions on (by design). I tried the template snippit below, first without the 'template:' section per the docs when running strimzi > 0.20, then tried adding it just to see if it would help, but it still tried to bind to the public IP.

**To Reproduce**
1. Deploy the template below (kubectl apply -f template.yml)

**Expected behavior**
Create a load balancer for the kafka nodes using a private IP, not public.

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1
 - Installation method: helm
 - Kubernetes cluster: Kubernetes 1.20.5
 - Infrastructure: Azure AKS

**YAML files and logs**

```apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: <my cluster name>
  namespace: <my namespace>
spec:
  kafka:
    replicas: 3
    version: 2.7.0
    listeners:
      - name: private
        port: 9092
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          brokers:
          - broker: 0
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          - broker: 1
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          - broker: 2
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    template:
      externalBootstrapService:
        metadata:
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

**Additional context**
none

**Comment by scholzj** [comment]
So, can you do `kubectl get service -o yaml`? That should show us if the annotations are attached or not. The Kafka CR looks good to me, so I would expect them to be there. But if they are missing, it will be something Strimzi related. If the annotations are there it is only on AKS to create the right type of load balancer.

**Comment by justin-silveri** [comment]
Yes, the annotations are there in the applied yaml file. I have created other private load balancers on this AKS cluster with the same annotation and they create with a private IP from the subnet with no issues.

**Comment by justin-silveri** [comment]
I found the way to add a private IP, so the deployed yml matches what worked for the nginx service, yet it's still trying to bind a public IP

```
kind: Service
apiVersion: v1
metadata:
  name: kafka-cluster-kafka-private-0
  namespace: --------
  uid: -------------------
  resourceVersion: '-------'
  creationTimestamp: '2021-04-30T00:46:52Z'
  labels:
    app.kubernetes.io/instance: kafka-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: strimzi-kafka-cluster
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-kafka
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
spec:
  ports:
    - name: tcp-private
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 31200
  selector:
    statefulset.kubernetes.io/pod-name: kafka-cluster-kafka-0
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-kafka
  clusterIP: 172.xx.xx.xx
  clusterIPs:
    - 172.xx.xx.xx
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 10.xx.xx.xx
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
```

**Comment by scholzj** [comment]
Yeah, you can configure the IP addresses in the Kafka CR: https://strimzi.io/docs/operators/latest/full/using.html#property-listener-config-lb-ip-reference

But I'm afraid we just create the service and the rest is on Kubernetes. We do not call any other APIs to create the load balancer. Did you tried to check the Kubernetes logs? Does that explain what it does and why? I do not know that well how Azure works, so I'm not sure what might be the things to cause this.

**Comment by justin-silveri** [comment]
Update:
It turns out this was a permissions issue on the Azure AKS side. It required adding the AKS ServicePrinciple as 'Contributor' to the AKS managed Resource Group, and 'Network Contributor' to the user managed AKS Resource Group. Why it's trying to touch the public loadbalancer/pip when creating an internal only service makes no sense at all to me, but it's working now.

**Comment by scholzj** [comment]
Thanks for the update. It might help someone else in the future. I guess we can close this issue now?

**Comment by justin-silveri** [comment]
Yes, the issue can be closed. Posted the update for exactly that reason, in case anyone else has the same issue in Azure with AKS.
