### ISSUE TITLE
getting 404 not found in kibana

### ISSUE THREAD

**Issue by Cshanmukh80** [strimzi/strimzi-kafka-operator#4891]
kibana.yml: |
    server.host: kibana
    logging.dest: stdout
    elasticsearch.hosts: [ "http://obf-elastic-master:9200" ]
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.username: "elastic"
    elasticsearch.password: "elastic"
    server.basePath: "/kibana"
    server.rewriteBasePath: "true"

[kibana.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6419772/kibana.zip)

here my elasticsearch is working fine but kibana is showing 404 not found issue
can you helm me out for this issue with kibana

**Comment by scholzj** [comment]
Sorry, but what has Kibana to do with Strimzi?
