### ISSUE TITLE
Improve reconciliation work scheduling

### ISSUE THREAD

**Issue by rareddy** [strimzi/strimzi-kafka-operator#4902]
When dealing with a large number of Kafkas  (about 100) in a single Openshift cluster controlled Strimzi Operator, I see the reconciliation times are all over the place taking anywhere from 30 seconds to 90 secs (based on sampling, may be higher). Also, see spikes in CPU usage every 2 minutes with continuous throttling of it.

some sample log lines extracted during reconcile
```
2021-04-28 18:34:23 INFO  AbstractOperator:254 - Reconciliation #2446(timer) Kafka(sample-1): Kafka sample-1 will be checked for creation or modification
2021-04-28 18:35:07 INFO  AbstractOperator:493 - Reconciliation #2446(timer) Kafka(sample-2): reconciled

2021-04-28 18:26:23 INFO  AbstractOperator:254 - Reconciliation #2046(timer) Kafka(sample-2): Kafka sample-2 will be checked for creation or modification
2021-04-28 18:27:36 INFO  AbstractOperator:493 - Reconciliation #2046(timer) Kafka(sample-2): reconciled

2021-04-28 19:32:23 INFO  AbstractOperator:254 - Reconciliation #5550(timer) Kafka(sample-3): Kafka sample-3 will be checked for creation or modification
2021-04-28 19:33:20 INFO  AbstractOperator:493 - Reconciliation #5550(timer) Kafka(sample-3): reconciled
```
Looking at Strmzi code for the reconciler is using `vertx.setPeriod` which executes a timer in a *fixed* interval of 2 mins, so every 2 mins all the clusters reconciles get executed contributing to the cpu load.

I am wondering if this call can be switched to `vertx.setTimer` which also executes using timer thread but this will only queue the next call after the previous one finished with idle time duration of 2 mins in between. I am hoping this would spread the CPU utilization a little better than the spikes we are seeing but will reduce the number of reconciling cycles if times are high.

There may be another issue here why the reconciles are taking this long, which I will further investigate and log another issue, but this one is strictly for the reconcile spread.

**Comment by tombentley** [comment]
It seems very likely that the spikes are due to the fact that all the timers get started at the same time and fire on the same interval. There are a number of options:

1. Switch to setTimer, which should cause the reconciliations of CRs to spread out over time, though they would be grouped together initially. 
2. We could spread the initial reconciles over the reconciliation interval (this would work with `setPeriodic` or `setTimer`).

There are other options too, but those are probably the simplest.

**Comment by rareddy** [comment]
option (1) might be ok as clusters are created over the period of time, with (2) with `setPeriodic` there is a small chance of overlapping reconciles. (2) with `setTimer` seems to cover both. The one change we will see with `setTimer` the reconciles may be further apart if the reconcile times are high but seems to be an acceptable risk.

**Comment by scholzj** [comment]
This does not work IMHO. The timer based reconciliation does not keep per-resource timers but a per-operator timer. So it goes, finds out all CRs and reconciles them. So any change between `setTimer` and `setPeriod` doesn't make sense. You can go and change how often the reconciliation is happening if it seems to be too often for you.

**Comment by rareddy** [comment]
Would you consider changing this to be per-resource timer? I have changed the default 2 mins to 4 mins did not seem to affect much other than cpu spikes at 4 min intervals.

**Comment by scholzj** [comment]
I'm not sure that makes sense. One of the points of it is to capture any possibly missed or failed reconciliations. And that is why it is a bit questionable to design it in a way where it relies on some reconciliation having properly configured some per-resource timer.

**Comment by sknot-rh** [comment]
> This does not work IMHO. The timer based reconciliation does not keep per-resource timers but a per-operator timer. So it goes, finds out all CRs and reconciles them. So any change between `setTimer` and `setPeriod` doesn't make sense. You can go and change how often the reconciliation is happening if it seems to be too often for you.

Cannot we use recursite calling timer? Something like 
```
        public void setRecursiveTimer() {
            vertx.setTimer(delay, id -> {
                doTheTask();
                setRecursiveTimer();
            }) ;
        }
        ```
        It would spread the beggings of the reconciliations and thus the peaks should be avoided.

**Comment by rareddy** [comment]
I verified that `setTimer` just hangs the whole process of reconciliation, which is not good as @scholzj suspected.

Since most of the blocking operations during reconciliation are done using the pool `kubernetes-ops-pool` defined at [1], 

1. do you think removing the fixed pool size of 10 threads and let this be the default size (20 threads) with a configurable size will be better? currently this is not configurable.
2. Since most of the calls using this thread pool are queued, I am suspecting increasing the thread sizes might help. However, I could not verify the vertx thread pool queue depths [2] during the testing to verify. Is there way to do this?
3. There are some instances the pool's executor used directly without queuing for immediate execution (`sorting = false` in `executeBlocking` call). I did not see any RejectedExcution in logs, but feel this could be a possibility with an increased load where all the 10 threads are engaed. 

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/ClusterOperator.java#L101
[2] https://vertx.io/docs/vertx-micrometer-metrics/java/#_vert_x_pool_metrics

**Comment by scholzj** [comment]
Not sure why the default would need to change from 10 to 20 ... but making it configurable makes sense.

**Comment by rareddy** [comment]
The issue is when you define a fixed number then it can not be configured through vertx. When you leave out the size then it is defaulted to 20 and also configurable. but one can add a Strimzi level configuration otherwise.

**Comment by scholzj** [comment]
You probably need to explain it a bit more ... so how is it configured when it would not be set by Strimzi code?

**Comment by rareddy** [comment]
There seems a roundabout way to provide a JSON file for config for Vertx during the start of Vertx. So, yeah the configuration at Strimzi level makes sense to me.

**Comment by rareddy** [comment]
@scholzj there are two different pools in use (apart from vertx worker/event pools) `kubernetes-ops-pool` which is configured at `10` threads and `kubernetes-ops-tool` that defaults to `20` threads currently. What do you recommend in terms of configuration, a single environment variable to control both the thread pools or different ones for each? I am unaware of the pattern of usage between both to make a decision.

**Comment by scholzj** [comment]
In general, everything should run through the `kubernetes-ops-pool` ... the execute blocking running on the default pool are basically a bug.

**Comment by rareddy** [comment]
ok, I will submit a patch to will fix that too.

**Comment by rareddy** [comment]
Added this PR as part of improving reconciliation effort https://github.com/strimzi/strimzi-kafka-operator/pull/4963

**Comment by rareddy** [comment]
@scholzj I see that `KafkaRoller` when it is running it creates a new thread not use any thread pool-based threads, is that intentional?

**Comment by scholzj** [comment]
I think that is intentional ... @tombentley can probably explain why he did it that way. (my threading skills stop at calling _executeBlocking_ :-))

**Comment by tombentley** [comment]
@rareddy the original version of `KafkaRoller` was typical async vertx code, but as the algorithm became more complex it became really hard to reason about and ensure that all error scenarios were covered. I decided in the end that it was better to just make it single threaded. While the code is still a more complex than I'd like, but it's relatively easier to _read_.

**Comment by rareddy** [comment]
@tombentley single-threaded is fine but was thinking if it can use one of the threads from pool `kubernetes-ops-pool` to keep the threads contained. obviously, there won't be any efficiency in processing, which might save tiny resources and runaway thread count in case of large roller tasks.

**Comment by tombentley** [comment]
Rolling can take a long time (minutes, or longer), and use blocking APIs. IIRC it's recommended that threads from the worker pool aren't supposed to take more than about 8s for their processing, and if you need longer you should manage your own threads.
