### ISSUE TITLE
Deletion of Kafka CR requires propagationPolicy of background

### ISSUE THREAD

**Issue by rareddy** [strimzi/strimzi-kafka-operator#5042]
When a user deletes an existing Kafka CR that is created with Strimzi using http client with propagationPolicy set to "orphan" then deletion of the Kafka CR is done however the corresponding resources (pods, deployments, statefulsets) are not always deleted and they are orphaned.

The reason for it is when in `ownerReferences` of the resources the value of `blockOwnerDeletion` either set to false or ignored, then when the delete operation comes with `propagationPolicy` like `orphan` then Kafka resource is deleted however all the resources not clean up properly. See https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy

The origination issue was from java-operator framework https://github.com/fabric8io/kubernetes-client/issues/3179

1. create a cluster
2. issue a delete with http client where propagationPolicy set to 'orphan' 

**Environment (please complete the following information):**
 - Strimzi version: 0.23.0
 - Installation method: OperatorHub.io
 - Kubernetes cluster: OpenShift 4.7
 - Infrastructure: Amazon EKS

Possible Resolutions:

1) Maybe a warning in the documentation that for delete `propagationPolicy` set to `background`
2) alternatively, all the resources can be changed to have `blockOwnerDeletion` set to `true`

**Comment by scholzj** [comment]
I do not follow this issue. If you set propagation policy to orphan, you are requesting to not delete the dependent resources. So that is not a bug but a feature.

**Comment by rareddy** [comment]
My suggestion is to at least add some notes to the document so that it is the case.

**Comment by ppatierno** [comment]
I think that with "orphan", what we see is the right behaviour. 
My point is why not using blockOwnerDeletion=true so that with deletion policy "foreground", the Kafka CR is deleted only when all dependants (statefulsets, configmaps, secrets and so on) are deleted. It would provide a right feedback that when the Kafka CR is gone, the entire parts of the Kafka cluster are gone.

**Comment by scholzj** [comment]
So, is there anything more to do here? Or can this be closed? I do not see anything we can do about this if you delete with orphan policy from your own application.

**Comment by rareddy** [comment]
this can be closed.
