### ISSUE TITLE
[CRD Generator] Validate that type fields have NON_NULL include policy

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#5064]
When using the `type` as discriminators for different sub-classes, it is important to make sure the `NON_NULL` include policy (`@JsonInclude(JsonInclude.Include.NON_NULL)`). Using other policies such as for example `NON_DEFAULT` will cause the `type` field to be omitted and generate invalid resource. That can cause issues such as the one described in #5054. Ideally, we should introduce. validation check for this in the CrdGenertor classes to make sure all classes are properly set.

**Comment by ShubhamRwt** [comment]
@scholzj Hello, Is this issue still open or is it resolved?

**Comment by tombentley** [comment]
@ShubhamRwt I suspect so, though the need for it isn't so pressing now that we're done the CRD conversion.

**Comment by ShubhamRwt** [comment]
Okay got it, Thanks @tombentley
