### ISSUE TITLE
Implement KafkaUser with TLS-noop so it won't generate certificate

### ISSUE THREAD

**Issue by FrankWang1108** [strimzi/strimzi-kafka-operator#5077]
**Is your feature request related to a problem? Please describe.**
It is related to a problem where I want to use KafkaUser for ACL and quota control, but I don't want to use the cert generated by Strimzi. I need to provide my own certs for the user.

**Describe the solution you'd like**
A solution where we can still generate kafkaUser with ACL and quota, but it doesn't generate certs. So that we can provide our own certs.

**Describe alternatives you've considered**
I'v considered to just ignore the User operator generated certs and use my own cert with corresponding CN

**Additional context**

**Comment by scholzj** [comment]
@FrankWang1108 Just FYI, I opened #5249 for this.
