### ISSUE TITLE
Adding custom resource selector tag on Strimzi operator metrics

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#5088]
With the introduction of the `STRIMZI_CUSTOM_RESOURCE_SELECTOR` env var for selecting which Kafka customer resources the operator should reconcile via labels, it would be useful to have that information in the metrics exposed by the Strimzi operator.
For example, currently we have something like:

```shell
strimzi_reconciliations_total{kind="Kafka",} 13.0
```
but could be useful to have distinction across custom resource selector labels, so something like:

```shell
strimzi_reconciliations_total{kind="Kafka", selector="io.ppatierno/my-label-to-select=my-value"} 13.0
strimzi_reconciliations_total{kind="Kafka", selector="io.ppatierno/my-label-to-select-2=my-value-2"} 5.0
```

The same could be applied to all other Strimzi operator metrics already grouped by "kind" tag.

**Comment by ShubhamRwt** [comment]
@ppatierno Hello, Is this issue free to work upon?

**Comment by ppatierno** [comment]
@ShubhamRwt sure, feel free to work on it if you like ;-)
