### ISSUE TITLE
Network connection issue when using watchAnyNamespace or watchNamespaces helm keys

### ISSUE THREAD

**Issue by benmathews** [strimzi/strimzi-kafka-operator#5124]
[report-14-06-2021_16-33-38.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6651598/report-14-06-2021_16-33-38.zip)
Installing the strimzi operator and a Kafka object in different namespaces doesn't work

**To Reproduce**
On a v1.17.11 kubernetes cluster install the v0.23.0 strimzi-kafka-operator and the (sample kafka cluster)[https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/kafka/kafka-ephemeral-single.yaml] into different namespaces. On the operator install, set the `watchAnyNamespace` key equal to true.

```
$ helm list -n strimzi
NAME                  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                        	APP VERSION
strimzi-kafka-operator	strimzi  	19      	2021-06-14 16:13:54.341355898 -0600 MDT	deployed	strimzi-kafka-operator-0.23.0	0.23.0     
$ kubectl get kafka -n benkafka
NAME      DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS   READY   WARNINGS
otherns   1                        3                             
```
Observe that the Kafka cluster is never set up correctly. 

```
$ k get pod -n benkafka
NAME                  READY   STATUS    RESTARTS   AGE
otherns-zookeeper-0   1/1     Running   0          32m
otherns-zookeeper-1   1/1     Running   0          32m
otherns-zookeeper-2   1/1     Running   0          32m
```

Observe that the strimzi-cluster-operator log eventually has a time out

```
2021-06-14 22:22:36 ERROR AbstractOperator:276 - Reconciliation #3(watch) Kafka(benkafka/otherns): createOrUpdate failed
io.strimzi.operator.cluster.operator.resource.ZookeeperScalingException: Failed to connect to Zookeeper otherns-zookeeper-0.otherns-zookeeper-nodes.benkafka.svc:2181,otherns-zookeeper-1.otherns-zookeeper-nodes.benkafka.svc:2181,otherns-zookeeper-2.otherns-zookeeper-nodes.benkafka.svc:2181. Connection was not ready in 300000 ms.
	at io.strimzi.operator.cluster.operator.resource.ZookeeperScaler.lambda$connect$6(ZookeeperScaler.java:155) ~[io.strimzi.cluster-operator-0.23.0.jar:0.23.0]
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [io.netty.netty-transport-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.60.Final.jar:4.1.60.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for ZooKeeperAdmin connection to otherns-zookeeper-0.otherns-zookeeper-nodes.benkafka.svc:2181,otherns-zookeeper-1.otherns-zookeeper-nodes.benkafka.svc:2181,otherns-zookeeper-2.otherns-zookeeper-nodes.benkafka.svc:2181 to be connected
	at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:137) ~[io.strimzi.operator-common-0.23.0.jar:0.23.0]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	at io.vertx.core.impl.future.FutureBase.lambda$emitFailure$1(FutureBase.java:71) ~[io.vertx.vertx-core-4.0.3.jar:4.0.3]
	... 7 more
```

I suspect this has something to do with the kubernetes version. I was unable to replicate this in a k3s install running v1.21.1+k3s1.

**Environment (please complete the following information):**
 - Strimzi version: [e.g. main, 0.23.0]
 - Installation method: Helm Chart
 - Kubernetes cluster: Kubernetes v1.17.11
 - Infrastructure: On prem / Self hosted

**YAML files and logs**

**Comment by scholzj** [comment]
So, does it work on the 1.17 cluster if you deploy the Kafka cluster in the same namespace as the operator? Or why do you think it is related to the namespace where the Kafka cluster is running?

**Comment by benmathews** [comment]
@scholzj yes, deploying into the same namespace works fine.

**Comment by scholzj** [comment]
Ok, I will see if I can reproduce it tomorrow. But I think we test this on Kube 1.16. So I think it is not likely it would work on 1.16 and 1.21 while 1.17 would not work. I wonder if it can be some environment issue instead. Could it be that something blocks the access between namespaces or something similar in the 1.17 cluster?

**Comment by benmathews** [comment]
I've found what may be the issue or at least lead us that way. The Kafka clusters created in the same namespaces have a Kafka and Zookeeper NetworkPolicy. Those in other namespacesr do not.

**Comment by scholzj** [comment]
That is weird. Could it be that some other tooling is deleting them in the other namespaces?

**Comment by benmathews** [comment]
I'm sorry, the zookeeper one is being created. The one in the remote namespace has the addition of an empty namespaceselector which seems correct.

**Comment by benmathews** [comment]
It is also possible that there is something that a large cluster causes. This cluster hosts our development environments and has 114 namespaces and 6300 pods. Most of them don't do much, but that is a possible source of slowness somewhere?

**Comment by scholzj** [comment]
> I'm sorry, the zookeeper one is being created. The one in the remote namespace has the addition of an empty namespaceselector which seems correct.

The Kafka one would be created only after the point where it fails for you. So it would be IMHO expected that that one is missing at that point.

> It is also possible that there is something that a large cluster causes. This cluster hosts our development environments and has 114 namespaces and 6300 pods. Most of them don't do much, but that is a possible source of slowness somewhere?

The point where it fails from the log is basically when the operator tries to connect to Zoo to verify its state. So that is pure TCP connection stuff. If that would be related to the cluster size, it would be more in the networking parts of the cluster not in Strimzi directly.

With a big cluster like this with many users ... could there be some limitation blocking the network access as in "fake multi-tenancy" or something like that? For example OpenShift had in the past (optionally) this _multi-tenant_ networking which blocked the network access between namespaces unless they were joined by some special commands etc.

**Comment by scholzj** [comment]
Hmm, my Minikube doesn't seem to be able to start 1.17.11 :-(. I will try to find some other way to test it with that version.

**Comment by benmathews** [comment]
I don't know of any limitations on network access. I turned the operator logging to debug and am attaching that.
[operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/6657369/operator.log)

**Comment by scholzj** [comment]
> I turned the operator logging to debug and am attaching that.

I'm a bit confused. The log shows how it communicates with Kafka and how the ZooKeeper cluster is ok. Does it mix the logs from several operators? The ZooKeeper error itself is quite clear and there is not much more to find out from the Operator log ... it just cannot connect to the ZooKeeper, which means some kind of connectivity/networking issue. But the log seems weird mixing different information which does not make much sense. Is it somehow altered?

> I don't know of any limitations on network access.

I guess you can try it the other way around and try if you can `curl` the Cluster operator endpoint from the ZooKeeper pods or use some other applications to test the networking. You can also try to setup _allow all_ network policy for the ZooKeeper to see if there is some issue with the network polciies.

**Comment by benmathews** [comment]
Vacation and some other priorities have kept me from this. 

I confirmed that the network policy is causing me the problem.

### Procedure

We are running kube 1.17 so ephemeral debug containers aren't available

I edited the strimzi-cluster-operator deployment and added a debug container.

```
- command:
  - sh
  - -c
  - while true; do sleep 10000000000; done
  image: ubuntu
  name: debug
```

Then I use that container to test the connection to zookeeper

```
k exec -c debug -it strimzi-cluster-operator-b4d64988-967nd -- bash
	
// In container
apt-get update && apt-get install -y netcat
	
// Validate connection or lack thereof
# echo stat | nc -v platform-zookeeper-client 2181
Connection to platform-zookeeper-client 2181 port [tcp/*] succeeded!
# echo stat | nc -v platform-zookeeper-client.strimzi 2181
Connection to platform-zookeeper-client.strimzi 2181 port [tcp/*] succeeded!
# echo stat | nc -v otherns-zookeeper-client.benkafka 2181
^C
```

### NetworkPolicy ApiVersion

Our cluster is running v1.17

```
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"ea5f00d93211b7c80247bf607cfa422ad6fb5347", GitTreeState:"clean", BuildDate:"2020-08-13T15:11:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

According to the [deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-16), extensions/v1beta1 isn't served anymore as of v1.16. However, my cluster still has it available and it is the default.

Both apiversions are available if I ask for them explicitly.

```
k get networkpolicy.networking
k get networkpolicy.extension
```

I feel like something with the ApiVersions is probably the problem. I'm not sure what the next step would be to investigate and diagnose. Any ideas?

**Comment by scholzj** [comment]
Wait, so the `netcat` seemed to have connected I guess if it said `succeeded` ... so why do you think there is some issue with network policies?

**Comment by benmathews** [comment]
The first two kafka clusters are in the same namespace. I included them to demonstrate that the command works within the same namespace. I'll add a comment to that effect.

**Comment by scholzj** [comment]
Ahh, ok. I missed that. Ok, but the network policies on their own apply equally to the same namespace as to other namespaces. So I still think this has to be something in your networking which blocks the access. Not the network policies directly. Maybe the networking plugin doesn't support the `namespace: {}` part as older Kube versions way before 1.16 did? Or something like that.

**Comment by benmathews** [comment]
We are running a 1.0.4 version of Calico. The Calico release notes are not adequate to see if this was an issue. But given that it works fine with newer versions, I think it a safe assumption that it is. We will either upgrade or find a way to work around the issue.

Thank you for working through this with me.
