### ISSUE TITLE
Using ArgumentCaptur consistently between tests

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#515]
The `KafkaAssemblyOperatorTest` has different tests which use `createCluster` and `deleteCluster` where the ArgumentCaptur is done in different ways (i.e. getting the Resource and then a map for getting the name instead of getting the name directly).
For example in the `createCluster` : 

`ArgumentCaptor<StatefulSet> ssCaptor = ArgumentCaptor.forClass(StatefulSet.class);`

instead of the following as in the `deleteCluster` : 

`ArgumentCaptor<String> ssCaptor = ArgumentCaptor.forClass(String.class);`

**Comment by echernous** [comment]
Hi @ppatierno, please could you confirm if it's okay to close this issue? I found the following changes when the deleteCluster method was removed - https://github.com/strimzi/strimzi-kafka-operator/commit/fcd57a6ce198222ce001cc2029b0510b3d69286f#diff-bb74695866dbe69d0a4e1152add9d11ba16a0fc11a03d4ebe3b4a032d7db89b8 , thank you! 
Cheers, Kate

**Comment by ppatierno** [comment]
yeah I would say yes. Thanks!
