### ISSUE TITLE
Migration to GenericKafkaListener failed if strimzi-operator was upgraded from 0.19.0=>0.20.1 (crd folder move)

### ISSUE THREAD

**Issue by vutkin** [strimzi/strimzi-kafka-operator#5188]
**Describe the bug**
Migration to GenericKafkaListener failed if strimzi-operator was upgraded from 0.19.0=>0.20.1=>0.21.1

```
Error: UPGRADE FAILED: release kafka-test failed, and has been rolled back due to atomic being set: cannot patch "test" with kind Kafka: Kafka.kafka.strimzi.io "test" is invalid: spec.kafka.listeners: Invalid value: "array": spec.kafka.listeners in body must be of type object: "array"

script returned exit code 1
```

**To Reproduce**
1. install strimzi 0.19.0
2. upgrade to 0.20.1, than 0.21.1 using hotfix script from https://github.com/strimzi/strimzi-kafka-operator/issues/3877#issuecomment-832750622
3. try to switch to GenericKafkaListener listeners format
```
Error: UPGRADE FAILED: release kafka-test failed, and has been rolled back due to atomic being set: cannot patch "test" with kind Kafka: Kafka.kafka.strimzi.io "test" is invalid: spec.kafka.listeners: Invalid value: "array": spec.kafka.listeners in body must be of type object: "array"
```

**Expected behavior**
Kafka should switched to GenericKafkaListener listeners format (array)

**Environment (please complete the following information):**
 - Strimzi version: [0.21.1]
 - Installation method: [Helm chart]
 - Kubernetes cluster: [1.20]
 - Infrastructure: [AKS]

**Additional context**
I see your comment https://github.com/strimzi/strimzi-kafka-operator/issues/3727#issuecomment-704386494. But unfortunately I have no idea how to apply crd from 0.21.1 release now. Have no idea why helm did't do this.
By the way fresh install from 0.21.1 release works as expected.

**Comment by scholzj** [comment]
I do not think this is really a bug. From the error, you just have old CRDs and you need to update them first before using the new listener format. 

I'm not Helm expert. My understanding is that Helm 3 doesn't upgrade CRDs anymore and you need to download the CRDs from our release page and do `kubectl apply` / `kubectl replace` on them.

**Comment by vutkin** [comment]
I've applied them manually via next snippet but got same error:
```
VERSION=0.21.1
RELEASE_FOLDER="$VERSION"

helm repo add strimzi http://strimzi.io/charts/
helm repo update
[ -d "$RELEASE_FOLDER" ] && rm -rf "$RELEASE_FOLDER"
helm pull strimzi/strimzi-kafka-operator --version "$VERSION" -d ./\
  --untar \
  --untardir "$RELEASE_FOLDER"

kubectl diff \
  -f "$VERSION/strimzi-kafka-operator/crds" \

read -p "Are you sure? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  kubectl apply \
    -f "$VERSION/strimzi-kafka-operator/crds"
fi
```

**Comment by scholzj** [comment]
You would need to check if they really updated (diff them I guess) or check if there is something wrong with your custom resource. It works fine in general. So not sure what else could I do remotely.

**Comment by vutkin** [comment]
apply didn't do job, replace with --validate=false flag did

**Comment by scholzj** [comment]
> apply didn't do job, replace with --validate=false flag did

That is weird. Probably `kubectl` confused something when trying to create the patch.

**Comment by scholzj** [comment]
@vutkin Did you managed to resolve this? Can it be closed?

**Comment by vutkin** [comment]
Yep, thanks, could be closed.--Sent from Yandex.Mail for mobile01.11.2021, 01:04, "Jakub Scholz" ***@***.***>:
@vutkin Did you managed to resolve this? Can it be closed?

**Comment by scholzj** [comment]
Thanks.
