### ISSUE TITLE
Unstable test for reconciliation

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-operator#520]
Test `
io.strimzi.operator.cluster.operator.assembly.KafkaConnectAssemblyOperatorTest.testReconcile` is unstable on CI side. Also, if execute this test on local environment 10 times, 2-3 times will be failed.

Cause of failure:
`java.lang.AssertionError: Not equals : [bar, foo] != [foo]`

Log:
[log_reconciliation.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2132206/log_reconciliation.txt)

**Comment by scholzj** [comment]
@serrss Is this still an issue?

**Comment by serrss** [comment]
@scholzj I see a lot of changes in test `KafkaConnectAssemblyOperatorTest.testReconcile` since `Jun 25, 2018` and if look at Travis builds we don't have this problem last time so the issue can be closed
