### ISSUE TITLE
Testing for concurrency problems using MockKube

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#525]
We have unit tests which use `MockKube` which are also testing functionality that relies on vertx. By configuring MockKube to add delays (`Thread.sleep()`) we should be able to detect things like blocking on the event loop thread much more easily, and thoroughly that we can via system testing.

**Comment by scholzj** [comment]
Triaged on 22.02.2022: Not. bad idea, but it seems there is no time / real interest to do this.
