### ISSUE TITLE
Istio + Kiali + Envoy + Jaeger integration for distributed kafka tracing

### ISSUE THREAD

**Issue by denissabramovs** [strimzi/strimzi-kafka-operator#5255]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
We are searching for solution to forward distributed tracing header back and forth in kafka.
We could do it in app, but would be very nice to have it outside of app/business logic, just by intercepting all kafka traffic and be able to extract some of the metadata from kafka messages, to direct that information to Jaeger.
This way we can see whole picture in Kiali.

**Describe alternatives you've considered**
Currently, the only one is to implement all of the above in the actual app code, by encapsulating all required headers in kafka message metadata.

**Comment by scholzj** [comment]
TBH, I'm not sure what you are asking for:
* Strimzi does currently not support Istio. As discussed many times in the past, Istio is relatively niche request which would require a lot of effort to implement and maintain for which we do not have resources.
* Unless something changed recently, Envoy does not support Kafka well enough to inject/extract any tracing information. So you would still need to instrument tracing in your applications.
* Strimzi supports OpenTracing / Jaeger using Interceptors in the components where interceptors are supported (Connect, Mirror Maker, etc.). This does not include the Brokers which currently do not support any kind on interception (not just in Strimzi, but Apache Kafka in general).

**Comment by scholzj** [comment]
Triaged on 28.4.2022: It is not clear what exactly is this asking for. Is it Istio support? Or tracing support? Given it is not clear, we should close this.
