### ISSUE TITLE
Allow injection of finalizers on LoadBalancer services

### ISSUE THREAD

**Issue by mike-jm** [strimzi/strimzi-kafka-operator#5260]
**Is your feature request related to a problem? Please describe.**
For every service of type LoadBalancer in Kubernetes our platform assigns an OpenStack load balancer.
A finalizer in then added to the Kubernetes service resource. Strimzi's reconciliation removes this finalizer.
Without the finalizer the OpenStack load balancer is not unassigned when the LoadBalancer service is deleted.

**Describe the solution you'd like**
Allow injection of finalizers. Seems to be the right thing to do for an operator. Similar to injection of sidecar containers.

**Describe alternatives you've considered**
We have a workaround where we use Strimzi's NodePort services to define the advertised hosts and ports.
We then create the LoadBalancer services without the help of Strimzi. This has the added benefit of being able to expose all brokers with only one IP address on different ports. But this would be another feature request someday.

**Additional context**
Here is the debug log of the reconciliation. I hope it helps.
```
2021-07-05 11:30:24 DEBUG ResourceDiff:39 - Reconciliation #2(timer) Kafka(i3-kafka-master/my-cluster): Current Service my-cluster-kafka-0 path /metadata/finalizers has value ["caas.daimler.com/fwaas"]
2021-07-05 11:30:24 DEBUG ResourceDiff:40 - Reconciliation #2(timer) Kafka(i3-kafka-master/my-cluster): Desired Service my-cluster-kafka-0 path /metadata/finalizers has value
2021-07-05 11:30:25 DEBUG AbstractResourceOperator:233 - Reconciliation #2(timer) Kafka(i3-kafka-master/my-cluster): Service my-cluster-kafka-0 in namespace i3-kafka-master has been patched

```

**Comment by scholzj** [comment]
You can configure finalizers in the listener configuration: https://strimzi.io/docs/operators/latest/full/using.html#type-GenericKafkaListenerConfiguration-schema-reference

> Allow injection of finalizers. Seems to be the right thing to do for an operator. Similar to injection of sidecar containers.

Why does that seem to be the right thing to do for an operator?

**Comment by mike-jm** [comment]
I had to brush up my knowledge on finalizers. So I asked 'What are Kubernetes finalizers for?' in O'Reilly learning and came up with the following answer from Kubernetes Operators by Jason Dobies and Joshua Wood:

> A finalizer is simply a series of strings on a resource. If one or more finalizers are present on a resource, the metadata.deletionTimestamp field of the object is populated, signifying the end user’s desire to delete the resource. However, Kubernetes will only perform the actual deletion once all of the finalizers are removed.

> Using this construct, you can block the garbage collection of a resource until the Operator has a chance to perform its own cleanup step. Once the Operator has finished with the necessary cleanup, it removes the finalizer, unblocking Kubernetes from performing its normal deletion steps.
 
Hence operators or controllers other than Strimzi could add their finalizers to the resources created by Strimzi if they need to do some work before the resources are deleted.

**Comment by scholzj** [comment]
I'm not sure it explains why is it _right thing to do_. It just describes some of the reasons why finalizers **might** be useful and why someone might want to use them. 

Anyway, I hope the link above helped you set your finalizers on loadbalancers. So can we close this?

**Comment by mike-jm** [comment]
The finalizer feature Strimzi implements does not work for us. 
IMHO Setting finalizer's with Strimzi that way is not very useful. Do people actually use that part of Strimzi? 

For now I we will go with the workaround as it also allows us to expose the Kafka cluster on a single IP address.
So I am closing this one.

**Comment by scholzj** [comment]
> The finalizer feature Strimzi implements does not work for us.
IMHO Setting finalizer's with Strimzi that way is not very useful. Do people actually use that part of Strimzi?

Maybe you can provide more details about why it does not work for you?
