### ISSUE TITLE
Can the zookeeper properties mount  out to the k8s configMap ?

### ISSUE THREAD

**Issue by ZhuoSiChen** [strimzi/strimzi-kafka-operator#5288]
**Is your feature request related to a problem? Please describe.**
Because some of client want to connect  the zookeeper ?

**Describe the solution you'd like**
 mount  out  the zookeeper propertiesto to the k8s configMap ,let other app counld connect the zookeeper.

**Comment by scholzj** [comment]
This was discussed many times in the past. We do not provide direct access to ZooKeeper. This is for security reasons and because ZooKeeper is going to be removed soon anyway. You can use this unofficial project at your own risk: https://github.com/scholzj/zoo-entrance

**Comment by ZhuoSiChen** [comment]
What I want to deploy is yahoo/CMAK ? 
But  CMAK can't connect to the zookeeper。
How can I finish this think ?

**Comment by scholzj** [comment]
Well, as I said above, you can use the zoo-entrance at your own risk.
