### ISSUE TITLE
strimzi_resource_state not updated to 0 when operator doesn't see a Kafka resource anymore due to changed selector label

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#5293]
The `strimzi_resource_state` metric is used to report when a specific (named) custom resource (i.e. `Kafka` kind) is ready or not.
It seems there is a bug when using more than one Strimzi operator handing over a `Kafka` custom resource from one to the other changing the so called selector label.
For example, let's consider having Strimzi 0.22.0 and 0.23.0 operator instances running together and watching all namespaces in a Kubernetes cluster but using the `STRIMZI_CUSTOM_RESOURCE_SELECTOR` env var in order to specify a label for selecting the Kafka custom resource to take care of.

1. Let's deploy a Kafka CR labeled for 0.22.0 so that it will reconcile it updating the `strimzi_resource_state` metric to 1 when it's ready.
2. Let's change the label on the Kafka CR to 0.23.0; the Strimzi 0.23.0 operator will take care of it while 0.22.0 won't see it anymore but the `strimzi_resource_state` metric will still stay 1 in the Strimzi 0.22.0 (of course it will be 1 in the Strimzi 0.23.0 as it should be). 

In this scenario, some aggregated metrics on complex dashboards could be doubled.
Taking a look at code it seems that the readiness of a Kafka resource on the `strimzi_resource_state` metric is set to 0 (not ready) only when there are some exception but not when the Kafka resource is not handled by the operator anymore which actually means a DELETED event.

**Comment by sknot-rh** [comment]
I tried to reproduce this. In the single namespace I created two deployments of the Strimzi. One had configured
```
            - name: STRIMZI_CUSTOM_RESOURCE_SELECTOR
              value: "strimzi.io/cluster=my-cluster-1"
```
the second one had configured
```
            - name: STRIMZI_CUSTOM_RESOURCE_SELECTOR
              value: "strimzi.io/cluster=my-cluster-2"
```
Then I created a Kafka resource with label 
```  labels:
    strimzi.io/cluster: my-cluster-1
```
As expected, the metric in the first operator was set to 
`strimzi_resources{kind="Kafka",selector="strimzi.io/cluster=my-cluster-1",} 1.0`
and in the second one to
`strimzi_resources{kind="Kafka",selector="strimzi.io/cluster=my-cluster-2",} 0.0`
Then, I changed Kafka resource label to 
```
  labels:
    strimzi.io/cluster: my-cluster-2
```
After $reconciliation_period the metrics are set to 
`strimzi_resources{kind="Kafka",selector="strimzi.io/cluster=my-cluster-1",} 0.0`
and
`strimzi_resources{kind="Kafka",selector="strimzi.io/cluster=my-cluster-2",} 1.0`.
Tested with latest image. So it seems to be fixed. @ppatierno WDYT?

**Comment by ppatierno** [comment]
@sknot-rh it seems you used on both deployments the same Strimzi version. Can you test it using 0.22.0 and 0.23.0 deployments please?

**Comment by sknot-rh** [comment]
Ahh, for some reason I was looking at the `strimzi_resources` metric instead of `strimzi_resource_state` one :man_facepalming:
