### ISSUE TITLE
Make `STRIMZI_NETWORK_POLICY_GENERATION` configurable in Helm Chart

### ISSUE THREAD

**Issue by valencetech** [strimzi/strimzi-kafka-operator#5295]
**Is your feature request related to a problem? Please describe.**
I would like the option to disable network policies i.e. and replace it with something a cilium network policy.
Currently, the flag STRIMZI_NETWORK_POLICY_GENERATION is missing from the operator deployment.

**Describe the solution you'd like**
Add an additional environment variables section to be used for the operator deployment template.
This would allow for adding extra Strimzi environment variables inside the values.yaml file.

**Describe alternatives you've considered**
Checking out the chart manually and editing.

**Additional context**

**Comment by scholzj** [comment]
> Currently, the flag STRIMZI_NETWORK_POLICY_GENERATION is missing from the operator deployment.

WDYM with this? First of all, this is something what is not released yet. Second, if you need it, you can just add it to the deployment.

**Comment by valencetech** [comment]
Hi @scholzj 
I am referring to this [section](https://github.com/strimzi/strimzi-kafka-operator/blob/41df8b275689960609689c57830f03fd2c4a0fc1/helm-charts/helm3/strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml#L61).
If I need to add extra environment variables defined [here](https://strimzi.io/docs/operators/in-development/using.html#ref-operator-cluster-str), I can't do that using the values.yaml file in the helm chart.

**Comment by scholzj** [comment]
Ok, so what you really want is to just add an option to specify this parameter in the Helm Chart, right?

**Comment by valencetech** [comment]
That's correct.

**Comment by scholzj** [comment]
Ok, I updated the title to make it clear what it is asking for.
