### ISSUE TITLE
how to config statefulset updateStrategy from 'OnDelete' to 'RollingUpdate' for kafka cr

### ISSUE THREAD

**Issue by volume-ji** [strimzi/strimzi-kafka-operator#5317]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
updateStrategy of statefulset generated by kafka cr is OnDelete, how to modify updateStrategy if i want to use RollingUpdate。

1. when i create kafka resource, kafka-operator create sts resource. sts .updateStrategy is "OnDelete"
2. if i want to change this updateStrategy, I must use "kubectl annotate statefulset cluster-name-kafka strimzi.io/manual-rolling-update=true" refer to https://strimzi.io/docs/operators/latest/using.html#proc-manual-rolling-update-statefulset-str
3. how to config updateStrategy directly using kafka.yaml.

thanks for any reply

**Comment by scholzj** [comment]
You cannot change it. The rolling update of the stateful sets (ZooKeeper / Kafka) is always done by the operator following special rules (Leader, controller last, watching data for being in-sync etc.).

**Comment by volume-ji** [comment]
but there is a bug about OnDelete updateStrategy, refer to 
Issue: https://github.com/kubernetes/kubernetes/issues/73492
open PR: https://github.com/kubernetes/kubernetes/pull/83649

**Comment by scholzj** [comment]
And how does that bug impact Strimzi? In any case, as I said, the operator does its own rolling update which is important to maintain the availability and stability of the cluster. Rolling update done by Kubernetes would not be able to do that. So there are no plans to change anything.

**Comment by volume-ji** [comment]
ok, thanks a lot
