### ISSUE TITLE
Pods occasionally fail to start

### ISSUE THREAD

**Issue by shawkins** [strimzi/strimzi-kafka-operator#5362]
**Describe the bug**
During the install of a new instance occasionally the zookeeper or kafka pods won't start.

**To Reproduce**
In a fresh namespace deploy a kafka resource similar to #5325 

**Expected behavior**
The pods will start.

**Environment (please complete the following information):**
 - Strimzi version: 0.23.0-1
 - Installation method: fabric8 client
 - Kubernetes cluster: OpenShift 4.7
 - Infrastructure: AWS

**YAML files and logs**
From a failed install showing:
```
[shawkins@localhost perf]$ kubectl --kubeconfig kafka-config get pods -n kafka
NAME                                          READY   STATUS             RESTARTS   AGE
instance-thru-admin-server-5f8c6cff7d-szg9j   1/1     Running            0          7m43s
instance-thru-canary-94d85c744-ll5z8          1/1     Running            0          7m43s
instance-thru-kafka-0                         0/1     CrashLoopBackOff   6          6m49s
instance-thru-kafka-1                         0/1     CrashLoopBackOff   6          6m49s
instance-thru-kafka-2                         0/1     CrashLoopBackOff   6          6m49s
instance-thru-zookeeper-0                     1/1     Running            0          7m39s
instance-thru-zookeeper-1                     1/1     Running            0          7m39s
instance-thru-zookeeper-2                     1/1     Running            0          7m39s
```

The entirety of the broker log is:
```
++ hostname
++ awk -F- '{print $NF}'
+ STRIMZI_BROKER_ID=0
+ export STRIMZI_BROKER_ID
STRIMZI_BROKER_ID=0
+ echo STRIMZI_BROKER_ID=0
+ export GC_LOG_ENABLED=false
+ GC_LOG_ENABLED=false
+ '[' -z '' ']'
+ export KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties
+ KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties
+ rm -f /var/opt/kafka/kafka-ready /var/opt/kafka/zk-connected
++ ls /opt/kafka/libs/kafka-agent.jar
+ KAFKA_OPTS=' -javaagent:/opt/kafka/libs/kafka-agent.jar=/var/opt/kafka/kafka-ready:/var/opt/kafka/zk-connected'
+ export KAFKA_OPTS
+ . ./set_kafka_jmx_options.sh '' '' ''
++ set -e
++ JMX_ENABLED=
++ JMX_USERNAME=
++ JMX_PASSWORD=
++ '[' '' = true ']'
+ '[' -n '' ']'
+ '[' true = true ']'
++ ls /opt/kafka/libs/jmx_prometheus_javaagent-0.14.0.redhat-00002.jar
+ KAFKA_OPTS=' -javaagent:/opt/kafka/libs/kafka-agent.jar=/var/opt/kafka/kafka-ready:/var/opt/kafka/zk-connected -javaagent:/opt/kafka/libs/jmx_prometheus_javaagent-0.14.0.redhat-00002.jar=9404:/opt/kafka/custom-config/metrics-config.yml'
+ export KAFKA_OPTS
+ export LOG_DIR=/opt/kafka
+ LOG_DIR=/opt/kafka
++ tr -dc _A-Z-a-z-0-9
++ head -c32
+ CERTS_STORE_PASSWORD=pp2JVWoZ_zk-zE0vW2pbm8XTJvXpVSf5
+ export CERTS_STORE_PASSWORD
+ mkdir -p /tmp/kafka
+ ./kafka_tls_prepare_certificates.sh
Preparing truststore for replication listener
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/kafka/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for replication listener is complete
Looking for the right CA
No CA found. Thus exiting.
```

This didn't seem to happen with 0.23.0-0.

**Comment by scholzj** [comment]
I guess there is something wrong with your cluster CA or with your server certificates.

**Comment by shawkins** [comment]
> I guess there is something wrong with your cluster CA or with your server certificates.

It's likely a kubernetes / timing issue. On exactly the same cluster, with exactly the same resource, I can retry after re-creating the namespace and it will succeed sometimes as well.  When this occurs it does mean that the kafka cluster is not ready within a reasonable amount of time - this test logic gives up after 10 minutes.  

I never see this situation with 0.23.0-0 for whatever reason.

**Comment by scholzj** [comment]
> It's likely a kubernetes / timing issue. On exactly the same cluster, with exactly the same resource, I can retry after re-creating the namespace and it will succeed sometimes as well. When this occurs it does mean that the kafka cluster is not ready within a reasonable amount of time - this test logic gives up after 10 minutes.

Well, the certificates matched when ZooKeeper was starting. So 'm not sure it is _Kubernetes_ or _timing_ issue - it suggests it was correct before. I guess you need to check the secrets and the certificates when it happens to see what is wrong with them.

> I never see this situation with 0.23.0-0 for whatever reason.

There is no 0.23.0-0 version. The only version which exists is 0.23.0.

**Comment by shawkins** [comment]
> I guess you need to check the secrets and the certificates when it happens to see what is wrong with them.

What are the relevant ones?

> There is no 0.23.0-0 version. The only version which exists is 0.23.0.

Sorry these are product bundle version.  This can be moved to a JIRA if that seems better.

**Comment by scholzj** [comment]
> What are the relevant ones?

Well, the CA secrets and the broker secret ... I think they are named `...-cluster-ca`, `...-cluster-ca-cert`, `...-brokers`.

**Comment by shawkins** [comment]
If I delete the brokers secret and wait for another reconciliation this issue resolves.  I think this happening because an update is being made to the strimzi operator deployment close to the time of the kafka deployment.  It must result in two instances of the strimzi operator running at the same time.  This behavior is only happening in a test framework, so this can be closed.
