### ISSUE TITLE
Support Helm Chart bundling to deploy operator

### ISSUE THREAD

**Issue by seglo** [strimzi/strimzi-kafka-operator#539]
Helm Charts are a useful way of bundling and versioning configuration resources in Kubernetes.  The only reference I could find to helm support is found in issue #42 which mentions:

> Helm is nice, but I'm not sure we really want to invest into that right now.

If this is not already on your immediate backlog I would like to propose adding a Helm Chart target to your build & release process that can generate a standalone tarball artifact.  

In addition once chart bundling is complete we could open a PR to the [Kubeapps Chart Repo](https://hub.kubeapps.com/charts) for consideration.

Would you be open to this contribution?

**Comment by ppatierno** [comment]
Hi Sean,
your contribution about adding Helm Charts is really welcome!
As you noticed from #42, it's on our backlog but not as high priority but having a contribution could be awesome.
So ... +1 from me (and I guess from all other contributors) ... and thanks! ;)

**Comment by seglo** [comment]
Great!  I'll follow up when I have something to review.

**Comment by scholzj** [comment]
@seglo I assigned this issue to you so that nobody else starts working on it.
