### ISSUE TITLE
Docs: Strimzi Quick Start guide (0.24.0) incorrect Kafka CRD example

### ISSUE THREAD

**Issue by akantak** [strimzi/strimzi-kafka-operator#5400]
Kafka CRD's example deployment described in https://strimzi.io/docs/operators/latest/quickstart.html (which is based on
https://github.com/strimzi/strimzi.github.io/blob/main/docs/operators/0.24.0/quickstart-book.html#L432)
is incorrect. It causes `InvalidResourceException` in Kafka CRD with message: `Kafka configuration option 'offsets.topic.replication.factor' should be set to 1 because 'spec.kafka.replicas' is 1`.

To make it work with a defined config, it is required to have 3 replicas.

**Comment by scholzj** [comment]
That is a great point. Thanks, I will have a look.

**Comment by scholzj** [comment]
This will be fixed in 0.25.0.
