### ISSUE TITLE
Make Scram-Sha password length configurable

### ISSUE THREAD

**Issue by pantaoran** [strimzi/strimzi-kafka-operator#5402]
**Is your feature request related to a problem? Please describe.**
I want to enable SASL authentication with Scram-Sha-512 for a group of Kafka users on my cluster. Corporate security tells me that they will only allow it if the used passwords are at least 30 characters long, but the passwords generated by Strimzi are only 12 characters long.

**Describe the solution you'd like**
Ideally I would like the generated password length to be configurable, so that I can set this length according to my needs. I don't really care if such config would be on a per user basis or a per cluster basis.

**Describe alternatives you've considered**
Another option would be to just set the hardcoded length to a bigger number for increased security. May I suggest 30 characters? 😇 

**Additional context**
None

**Comment by tombentley** [comment]
_If_ we were going to make it configurable then we should also consider making the alphabet from which the characters are drawn configurable too, since I'm sure there'll be some corporate security department somewhere that has opinions about that too.

**Comment by scholzj** [comment]
I think that makes sense @tombentley
