### ISSUE TITLE
Regenerate certificates when the internal CA one is deleted by accident

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#542]
If the "internal-ca" certificate is delete by accident, the CO regenerates it during the coming reconciliation.
It means that the current Kafka brokers and Zookeeper nodes certificates are signed with a not existing internal CA certificate so they cannot be valid anymore.
When the CO regenerates the internal CA certificate, it needs to start the generations of new certificates (signed with the new internal CA certificate) for Kafka brokers and Zookeeper nodes.

**Comment by scholzj** [comment]
Internal-ca is not used anymore. But the issue might be still valid for cluster-ca and clients-ca.
