### ISSUE TITLE
Update liveness/readiness probes in standalone deployment.yaml

### ISSUE THREAD

**Issue by oleksandr-balyshyn** [strimzi/strimzi-kafka-operator#5464]
https://github.com/strimzi/strimzi-kafka-operator/blob/c678c9dd3a5db63be7c50407dafa144c8c1696d9/install/topic-operator/05-Deployment-strimzi-topic-operator.yaml#L44-L55

Update port of application server in liveness/readiness probes according to a default value of STRIMZI_APPLICATION_SERVER variable

**Comment by scholzj** [comment]
I do not think `STRIMZI_APPLICATION_SERVER` has anything to do with the health checks.

**Comment by oleksandr-balyshyn** [comment]
Thanks for the blazingly fast response!

Following a official guide and `05-Deployment-strimzi-topic-operator.yaml` default values I get a error
```Readiness probe failed: Get "http://172.17.0.3:8080/ready": dial tcp 172.17.0.3:8080: connect: connection refused```
```Liveness probe failed: Get "http://172.17.0.3:8080/healthy": dial tcp 172.17.0.3:8080: connect: connection refused```

The default value for `STRIMZI_APPLICATION_SERVE` is `localhost:9000`, so I assume that there is a single vertx-based HTTP  server instance that exposes `/healthy` and `/ready` endpoints.

**Comment by oleksandr-balyshyn** [comment]
https://github.com/strimzi/strimzi-kafka-operator/blob/c678c9dd3a5db63be7c50407dafa144c8c1696d9/topic-operator/src/main/java/io/strimzi/operator/topic/Session.java#L366-L381

**Comment by scholzj** [comment]
Yeah, there is a separate HTTP server which does the healthchecks. From the code, `STRIMZI_APPLICATION_SERVER` configures some GRPC connectivity which AFAIK is not used at all in the Topic Operator (@alesj Do we need these options in the code? I can see how it is confusing if we have them but do not use them for anything. Can we maybe remove it?).

Without the full logs I'm not sure why would it be failing. Did you configured resources? Could it be that it does not have enough resources?

**Comment by alesj** [comment]
Hmmm, Kafka Streams needs some “application” info.
But afaik, it’s app id, whereas server was used in that gRPC stuff.
Hence it can be removed.
