### ISSUE TITLE
watchAnyNamespace flag leads to crash on operator startup.

### ISSUE THREAD

**Issue by mjrepo2** [strimzi/strimzi-kafka-operator#5476]
**Describe the bug**
watchAnyNamespace flag leads to crash on operator startup

**To Reproduce**
Use helm chart for strimzi version 0.25.0, set watchAnyNamespace: true, install strimzi.
No other changes have been made to the default helm chart

**Expected behavior**
The operator to start, and then watch all namespaces for strimzi resources

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0
 - Installation method: helm chart
 - Kubernetes cluster: Kubernetes 1.20
 - Infrastructure: Baremetal, Ubuntu

**YAML files and logs**
```
2021-08-25 09:55:56 INFO  ClusterOperator:78 - Creating ClusterOperator for namespace *
2021-08-25 09:55:56 INFO  ClusterOperator:94 - Starting ClusterOperator for namespace *
2021-08-25 09:55:56 WARN  WatcherWebSocketListener:73 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

2021-08-25 09:55:56 WARN  WatcherWebSocketListener:73 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

2021-08-25 09:55:56 WARN  WatcherWebSocketListener:73 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

2021-08-25 09:55:56 WARN  WatcherWebSocketListener:73 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

2021-08-25 09:55:56 WARN  WatcherWebSocketListener:73 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

2021-08-25 09:55:56 WARN  WatcherWebSocketListener:73 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

2021-08-25 09:55:56 WARN  WatcherWebSocketListener:73 - Exec Failure: HTTP 404, Status: 404 - 404 page not found

2021-08-25 09:55:56 ERROR Main:153 - Cluster Operator verticle in namespace * failed to start
io.fabric8.kubernetes.client.KubernetesClientException: 404 page not found
```

Hopefully I am missing something simple here, if any more information is needed please advise.

**Comment by scholzj** [comment]
HTTP 404 normally means that the CRDs are not installed. Can you double check that?

**Comment by mjrepo2** [comment]
Thanks for the quick reply - hopefully I am providing the right information:

```
kafkabridges.kafka.strimzi.io            2021-08-10T13:48:45Z
kafkaconnectors.kafka.strimzi.io         2021-08-10T13:48:45Z
kafkaconnects.kafka.strimzi.io           2021-08-10T13:48:44Z
kafkaconnects2is.kafka.strimzi.io        2021-08-10T13:48:44Z
kafkamirrormaker2s.kafka.strimzi.io      2021-08-10T13:48:45Z
kafkamirrormakers.kafka.strimzi.io       2021-08-10T13:48:45Z
kafkarebalances.kafka.strimzi.io         2021-08-10T13:48:45Z
kafkas.kafka.strimzi.io                  2021-08-10T13:48:44Z
kafkatopics.kafka.strimzi.io             2021-08-10T13:48:45Z
kafkausers.kafka.strimzi.io              2021-08-10T13:48:45Z
```
```

Labels:       app=strimzi
              component=kafkatopics.kafka.strimzi.io-crd
              strimzi.io/crd-install=true
Annotations:  <none>
API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-08-10T13:48:45Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1beta1

```

These are the crds that I have, but it seems the apiVersion is on a few v1, and others v1beta1

Like I said I have used the example strimzi helm chart and only changed the watchAnyNamespace flag.
Did I make a mistake somewhere or is this abnormal behaviour?

**Comment by scholzj** [comment]
Can you run something like this and share the output?

```
kubectl get crd kafkas.kafka.strimzi.io -o jsonpath='{.spec.versions[].name}'
```

**Comment by mjrepo2** [comment]
Yes, and sorry for wrongly labeling the post!

`kubectl get crd kafkas.kafka.strimzi.io -o jsonpath='{.spec.versions[].name}'
v1beta1`

**Comment by scholzj** [comment]
Right ... so for 0.25, you need to have the `v1beta2` version. So that explains the HTTP 404 error in the operator.

I don't really use/know Helm, so not sure why it did what it did. Was it upgrade or first install? It looks to me like you had some old Strimzi CRDs already installed on your cluster when you installed 0.25. If you are sure that no other strimzi installation is running in your cluster, the easiest way should be to delete the Strimzi CRDs and install those bundled with the 0.25.0 Helm Chart (you can also find the YAMLs [here](https://github.com/strimzi/strimzi-kafka-operator/tree/0.25.0/install/cluster-operator) - just use the 04X-*.yaml files).

PS: Don't worry about the labels ... ti is not always obvious what is bug and what not.

**Comment by mjrepo2** [comment]
It was a fresh install, I helm deleted strimzi and removed the namespace, and reinstalled - I did however have strimzi running in the cluster already before.
I have just removed everything again and it seems the CRDs are still there, so this may indeed be the issues.
I will remove the CRDs manually and reinstall fresh and report back my findings.

Thank you for your time.

**Comment by mjrepo2** [comment]
Removing the old CRDs has seemed to solve the issue, again thanks for your time and help!

**Comment by scholzj** [comment]
Yeah, I know some tools do not delete the CRDs when uninstalling the operator. I know OperatorHub.io does this, Helm might as well. So that might have caused this.
