### ISSUE TITLE
Allow for custom oauth settings

### ISSUE THREAD

**Issue by Sam-Kramer** [strimzi/strimzi-kafka-operator#5483]
**Is your feature request related to a problem? Please describe.**
Our Kafka setup integrates with our environments, which has a bespoke security setup. It uses OAuth2, but we need to be able specify our own callbacks and principals.

**Describe the solution you'd like**
Allow the ability to specify in the oauth2 listener config:
- listener.name.sasl_ssl.oauthbearer.sasl.server.callback.handler.class
- listener.name.sasl_ssl.oauthbearer.sasl.login.callback.handler.class
- listener.name.sasl_ssl.oauthbearer.principal.builder.class
- principal.builder.class
- listener.name.sasl_ssl.oauthbearer.connections.max.reauth.ms

**Describe alternatives you've considered** 
Another idea here, which is probably more ideal, is to simply allow for custom authentication section, and is up to the user to specify their listener config. I don't see this as being too egregious, as there already is a section for custom authorization. 

**Additional context**
Happy to contribute!

**Comment by Sam-Kramer** [comment]
```I also wonder whether principal.builder.class is something what can be configurable without breaking other things as/if it is not configurable per listener (mainly taking about the internal listeners here - for the user configured ones it would be up to you make sure it works I guess).```

How are you handling this today with Strimzi's OAuth @scholzj ? I see that if Strimzi OAuth is declared, we override the `principal.builder.class` to use https://github.com/strimzi/strimzi-kafka-oauth/blob/main/oauth-server/src/main/java/io/strimzi/kafka/oauth/server/OAuthKafkaPrincipalBuilder.java.

I assume operator and the other listeners still use cert-based authn/z, and the OAuthKafkaPrincipalBuilder supports both?

**Comment by Sam-Kramer** [comment]
Read the code a bit more of `OAuthKafkaPrincipalBuilder`, and that's exactly what's happening.

**Comment by scholzj** [comment]
Well, the difference is that that is our own principal builder which is written and tested to handle this. That might not apply for any custom builder a user provides.

**Comment by Sam-Kramer** [comment]
Submitted a proposal: https://github.com/strimzi/proposals/pull/41

**Comment by Sam-Kramer** [comment]
Fixed in https://github.com/strimzi/strimzi-kafka-operator/pull/6162https://github.com/strimzi/strimzi-kafka-operator/pull/6162
