### ISSUE TITLE
Both version "stable" and the version of the stable release should be choices in install.

### ISSUE THREAD

**Issue by javajon** [strimzi/strimzi-kafka-operator#5499]
**Is your feature request related to a problem? Please describe.**

At the [installation instructions](https://artifacthub.io/packages/aolm/community-operators/strimzi-kafka-operator) under the install button, there is a dropdown for the list of available releases. The current latest version is 0.25.0. This version is not in the list. The "stable" selection is there and is equivalent to version 0.25.0, however, the drop-down should also list 0.25.0 (or whever is the current "latest") as a choice, "Stable" should be treated as an alias of 0.25.0, not as the actual version identifiers.

The reason is I'm writing some instructions for people to follow in a tutorial. I need them to choose a specific version that the tutorial is tested against. I cannot tell them to install stable, as future stable releases may introduce breaking changes to the tutorial.  This is to maintain idempotency. As it stands now, in my instructions, I'm forced to tell them to install 0.24.0, since it's a predictable, idempotent choice over time.

**Describe the solution you'd like**
List both 0.25.0 and latest in the dropdown list for available versions.  Also, the list is in the reverse order, as the most recent versions should appear first, at the top.

**Describe alternatives you've considered**
In my instructions for now I have to instruct the reader to install 0.24.0, and if I later retest to a newer version, it will always be one less than latest.

**Additional context**
I'm authoring Katacoda scenarios for O'Reilly and highlighting Strimzi in one of them. To be published next week.

**Comment by scholzj** [comment]
TBH, I think this is some ArtifactHub issue. If you look at OperatorHub.io which is where they copy the data from, you can see 0.25.0 there: https://operatorhub.io/operator/strimzi-kafka-operator ... so maybe the best way is to use OperatorHub.io as the original source which is probably more reliable.

I also raised this on Slack (https://cloud-native.slack.com/archives/C0103CTR3RB/p1630447939020400) to see how they expect it to be updated or whether this is just some bug.

**Comment by javajon** [comment]
Yes, you are correct. ArtifactHub has a few issues with version listings. The OperatorHub is listing all available versions in a more sensible form. I see the same problem with the YAKS Operator. For now, I'll direct reads to OperatorHub since it's clearer.  Good suggestion.

Thank you for sending this upstream on slack. I added my 2 cents to that thread as well.

**Comment by scholzj** [comment]
I think this was resolved in ArtifactHub and can be closed.
