### ISSUE TITLE
Renaming services for Kafka and Zookeeper

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#55]
Both Kafka and Zookeeper have two separate services. The *headless* service which make sure that DNS records will be created for individual pods and access to them. In ZK this is needed to bootstrap the cluster. In Kafka this is needed to access the partition leaders directly etc.

Second service is a *ClusterIP* and does load balancing between available servers. For ZK this is used for client access and for Kafka this is used as the *bootstrap sever* address. IMHO these services are currently a bit unfortunately named. The *headless* services are always named `...-headless`. That means that the DNS hostnames to access the pods look always a bit strange, such as `kafka-0.kafka-headless.myproject...` or `zookeeper-0.zookeeper-headless.myproject...`. The names also don't make it clear which service should be used for what.'as well as to simplify the DNS names.

I would suggest to rename the services in following way to make it a bit more clear what should they be used for:
* `kafka` -> `kafka-bootstrap`
* `kafka-headless` -> `kafka`
* `zookeeper` -> `zookeeper-client`
* `zookeeper-headless` -> `zookeeper`

WDYT?

**Comment by tombentley** [comment]
I agree the current names are unclear, and so we should change them.

I have a couple of thoughts about the suggested names:
* Calling the zookeeper headless service `zookeeper` doesn't really convey that it's an internal ZK concern. But since the only clients should be other strimzi components, I guess that doesn't really matter much. 
* I also wonder if `kafka-brokers` for the headless service is a little more descriptive, emphasizing that it's a collection of individual brokers (I'm not 100% convinced though).

**Comment by scholzj** [comment]
Did we moved anywhere since last time? Is this the final version how it should be renamed?

* `kafka` -> `kafka-bootstrap`
* `kafka-headless` -> `kafka-brokers`
* `zookeeper` -> `zookeeper-client`
* `zookeeper-headless` -> `zookeeper-nodes`

Or do we want to close this? The later we do this, the more disruption it will cause.

**Comment by tombentley** [comment]
I'm +1 on renaming these to the names you suggest @scholzj and I agree we basically have to do this _now_, or never.

**Comment by ppatierno** [comment]
So referring to the methods we have for generating Secrets we agree to use "brokers" for Kafka and "nodes" for Zookeeper :-)

**Comment by scholzj** [comment]
@ppatierno I'm just trying to move this forward by accepting your suggestions ... my original suggestion was different. ;-)
