### ISSUE TITLE
kafka connector crashing with metric-config.json format

### ISSUE THREAD

**Issue by kajanth** [strimzi/strimzi-kafka-operator#5512]
**Describe the bug**
When upgrading from kafka connector v0.22.0 to v0.25.0 the connector is crashing due to 

Caused by: java.io.FileNotFoundException: /opt/kafka/custom-config/metrics-config.json (No such file or directory)

**To Reproduce**
1. upgrade from kafka connector v0.22.0 to v0.25.0 with metrics enabled.
2. kafka connect will crash
3. See error

**Expected behavior**
there should not be any changes to the way the metrics-config is perceived by the controller.

**Environment):**
 - Strimzi version: [0.25.0]
 - Installation method: HelmRelease
 - Kubernetes cluster: Kubernetes 1.17.17
 - Infrastructure: Yandex

**YAML files and logs**
File attached with the yaml manifest.

Error Log:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.io.FileNotFoundException: /opt/kafka/custom-config/metrics-config.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileReader.<init>(FileReader.java:75)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:78)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
[Archive.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7099100/Archive.zip)

# Additional configuration

**Comment by sknot-rh** [comment]
@ShubhamRwt could this be related to https://github.com/strimzi/strimzi-kafka-operator/pull/5072 ?

**Comment by ShubhamRwt** [comment]
> @ShubhamRwt could this be related to #5072 ?

@sknot-rh. Had the same thoughts but I was hoping for some more logs

**Comment by ShubhamRwt** [comment]
I will take a look into it

**Comment by scholzj** [comment]
Well, #5072 was the reason why I asked if the image was rebuilt with the right version. But nothing was provided so far 🤷‍♂️

**Comment by kajanth-tceu** [comment]
@scholzj  we had to disable the monitoring to make an urgent upgrade will get you the information by end of play today.

**Comment by kajanth** [comment]
@scholzj we had to disable the monitoring to make an urgent upgrade will get you the information by end of play today.

**Comment by scholzj** [comment]
You should just remove the metrics related section from the custom resource. I guess it would be in `KafkaConnect` in your case.

**Comment by scholzj** [comment]
@kajanth Did you managed to resolve this?

**Comment by CodeGlitcher** [comment]
Same issue when upgrading from 0.24.0.
The operator changes the configmap and rename metric.yml to metric.json. And then restart kafka en zookeeper.
But the 2.8.0 version of kafka and zookeeper stil expect to find metric.yml. 

I am able to start after upgrading to kafka 3.0.0. But this does not make it a nice experience.
It it possible for both metric.yml and metric.json to exists in the configmap until the old kafka & zookeeper versions are no longer supported?

**Comment by scholzj** [comment]
Do you use the right images corresponding to the operator version? For example, for Strimzi 0.26, you have to use the the Kafka 2.8 images from 0.26 and not from 0.24 or 0.23.

**Comment by CodeGlitcher** [comment]
yes, the deploy of the cluster operator has:
            - name: STRIMZI_KAFKA_IMAGES
              value: >
                2.8.0=cr.salvador-dali.local:5000/strimzi/kafka:0.26.0-kafka-2.8.0
                2.8.1=cr.salvador-dali.local:5000/strimzi/kafka:0.26.0-kafka-2.8.1
                3.0.0=cr.salvador-dali.local:5000/strimzi/kafka:0.26.0-kafka-3.0.0
But it still restarts zookeper once still on the  strimzi/kafka:0.24.0-kafka-2.8.0 image.
And because the first pod enter then a crashloop the deployment does not continue.

**Comment by scholzj** [comment]
I'm not sure I follow => When you use Strimzi 0.26 operator, why do some of your pods use `strimzi/kafka:0.24.0-kafka-2.8.0` image?

**Comment by CodeGlitcher** [comment]
Good question, but i dont know.
It restarts once still with the strimzi/kafka:0.24.0-kafka-2.8.0 image.
If that is successfull it then changes to image to 0.26.0.
If I have some time i will try to make some sort of recording of event to see if i can get some more details.

**Comment by scholzj** [comment]
No, the operator upgrade does only one ZooKeeper restart and that is just to change the image. I guess it would be in theory possible that while one pod is restarting to the new image, a container in another pod restarts for another reason and sees the new ConfigMap content => such race condition can probably happen. In that case, I guess it might just help to delete the pod and it will recreate it with the new image.

**Comment by CodeGlitcher** [comment]
I have repushed the strimzi images to our private repo and now it does startup as expected.
I Think i messedup soms images and did not tag them on the right version.
