### ISSUE TITLE
MirrorMaker2 stopped syncing offsets

### ISSUE THREAD

**Issue by m3nthal** [strimzi/strimzi-kafka-operator#5533]
MirrorMaker2 stopped syncing offsets after one of the source nodes was unavailable for 30 minutes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create 3 node broker A, and 3 node broker B
2. Create topic X on broker A and start consumer M from topic X on broker A
3. Setup MM2 to replicate to from A to B with `sync.group.offsets.enabled: true`
4. Verify offsets for consumer M on topic X are synced to broker B
5. Stop one node on broker A for 30 minutes
6. Offsets for consumer M on topic X will stop syncing = lag will start growing on broker B

**Expected behavior**
Offsets should continue to sync.

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1-kafka-2.7.0
 - Installation method: Terraform
 - Kubernetes cluster: Kubernetes 1.18
 - Infrastructure: GKE

**YAML files and logs**

Error in MM2 logs when one node on the source broker:

```
2021-09-03 12:47:37,118 ERROR Error querying offsets for consumer group app-a on cluster kafka-src. (org.apache.kafka.connect.mirror.MirrorCheckpointTask) [task-thread-kafka-src->kafka-em-gldn.MirrorCheckpointConnector-2]
2021-09-03 13:11:34,504 ERROR Error querying for consumer group app-a on cluster kafka-dst. (org.apache.kafka.connect.mirror.MirrorCheckpointTask) [Scheduler for MirrorCheckpointTask-refreshing idle consumers group offsets at target cluster]
```

**Additional context**

What was tried so far:

- restarting the task (no effect)
- restarting the MirrorMaker2 (no effect)
- resetting offsets on the destination broker B (the offsets were not syncing, lag was just growing)
- removing group id from the destination broker B (the group ID was not re-created on the destination)
- removing the topic (topic was then re-created and not consumer group nor offsets started to sync)
- disabling offset sync and enabling it again (no effect)

Seems like the broken consumer groups are still present in internal topics and prevent those to be re-create/re-synced.
Is there any way to re-sync particular topics or groupId without re-creating the broker?

**Comment by scholzj** [comment]
From the description it sounds like maybe some MM2 bug? Might be worth trying the latest Kafka version to see if it is fixed there. Have you tried to check:
* If the checkpoints are being created and the missing part is just pushing the data to the `__consumer_offsets` topics on the cluster B?
* If you can get / use the consumer offsets on the cluster A?
* If all offsets are affected or just some consumer groups / partitions which had leaders on the node from cluster A which you stopped?

**Comment by m3nthal** [comment]
Thank you for your answer.

> From the description it sounds like maybe some MM2 bug? Might be worth trying the latest Kafka version to see if it is fixed there. Have you tried to check:
> 
> * If the checkpoints are being created and the missing part is just pushing the data to the `__consumer_offsets` topics on the cluster B?

According to `.checkpoints.internal` on the destination broker last checkpoint for that particular topic/groupId was after the node on broker A recovered.
So `__consumer_offsets` on the destination broker was not updated since that checkpoint.

> * If you can get / use the consumer offsets on the cluster A?

I could get the offsets from cluster A, but they are irrelevant for cluster B, since they started at different times.

> * If all offsets are affected or just some consumer groups / partitions which had leaders on the node from cluster A which you stopped?

Offsets for all 4 topics that were consumed by a single consumer group stopped syncing.

Still, is there any way to force re-sync?

**Comment by scholzj** [comment]
> Still, is there any way to force re-sync?

I'm not aware of any. But I'm not really a MM2 expert.
