### ISSUE TITLE
More KafkaConnect Examples

### ISSUE THREAD

**Issue by kferrone** [strimzi/strimzi-kafka-operator#5574]
**Suggestion / Problem**
There is only a single KafkaConnect example in this repo. There is only one tutorial I found explaining the KafkaConnect. I am having a lot of trouble getting one to work. Would be nice if there was a few more examples which could be actually useful and usable. 

For example, I am trying to make a KafkaConnect using the camel-http-kafka-connector from here: https://camel.apache.org/camel-kafka-connector/latest/reference/connectors/camel-http-kafka-sink-connector.html

I at least got to the point the image is built and pushed and all the plugins register and then connect registers to the kafka cluster. However the container just randomly shuts down with no errors and a bunch of warnings saying things shutdown safely??? This creates a crash loop. 

**Documentation Link**
- [Lonely KafkaConnect Example](https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/connect/kafka-connect.yaml)
- [The one tutorial](https://strimzi.io/blog/2021/03/29/connector-build/)

**Comment by scholzj** [comment]
So, did you looked into the actual documentation?

**Comment by kferrone** [comment]
Yes, documentation is not an example, it's documentation.

**Comment by sknot-rh** [comment]
There is also a [Camel + Strimzi blogpost](https://strimzi.io/blog/2020/05/07/camel-kafka-connectors/).
In the docs, you can find the [section](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-kafka-connect-str) devoted to KafkaConnect. There are some (partial) examples.
Is there anything specific you need help with?

**Comment by kferrone** [comment]
Was mostly curious about a GRPC sink/source and also how to pass headers to http sink. 
I eventually figured out camel has this header: `CamelHeader.Authorization=...` and it can be added to a producerConfig. 
Now I'm wondering how to pass the same header when using the bridge? 

I'm slowly figuring things out. Ultimately I'll be fine. Still wish there were a few more examples than just the one, or at least add some depth to it. 

A simple example of consuming an s3 event would be extremely useful right out of the box. 

More examples would simply help newcomers to Strimzi pick up and get going faster.
