### ISSUE TITLE
Bug: Network Policy Generation can not be set in Helm Chart

### ISSUE THREAD

**Issue by kofl91** [strimzi/strimzi-kafka-operator#5589]
When trying to set the value fo Network Policy Generation, Kubernetes will reject the manifest as "false" is not a valid value when unquoted. 

In the Source Code you can see a missing "| quote" for the generateNetworkPolicy flag.

https://github.com/strimzi/strimzi-kafka-operator/blob/38a86e475d095e5a96b3ae9047e20e304430c80f/helm-charts/helm3/strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml#L120

**Comment by scholzj** [comment]
Looks like it. Can you open a PR for it?

**Comment by sknot-rh** [comment]
Isn't that done in https://github.com/strimzi/strimzi-kafka-operator/pull/5443/files#diff-5b37abf4318a667353eaf3475ba378b99ce129a524881e263022bcf02bf03c43R120 ?

**Comment by scholzj** [comment]
Looks like it. So it should be fixed in the next release I guess.

**Comment by scholzj** [comment]
Closing as fixed in #5443
