### ISSUE TITLE
Tool to get log dumps

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#5594]
`report.sh` uses `kubectl` (or `oc` if `kubctl` is not installed) to get broker and zookeeper logs for attaching to bug reports. 
When investigating problems around transactions or consumer groups it can be very helpful to get dumps of the `__transaction_state` and `__consumer_offsets` topics, as well as the relevant application partitions. I think it would be way, way too much to always include these for every partition in the cluster, but it would be good if there was a tool (possiblly `report.sh` or possibly something else) which supported a way of selecting partitions whose logs should be dumped (possibly between given times, to reduce the amount of data returned). For example, something like `report.sh --namespace=mynamespace --cluster=mycluster --transactionalId=mytransactionalid --after <date> --before <date> --partition=mypartition-1`. This would figure out the `__transaction_state` partition and dump the logs from brokers replicating that, as well as for `mypartition-1`. Similarly `--groupId` for consumer groups. There could be multiple occurrances of `--partition`.

**Comment by tombentley** [comment]
To avoid having a single issue about two separate ideas I've opened #5603 for the first point. I'll amend the description and summary so this issue is specifically about the second idea.

**Comment by fvaleri** [comment]
I also think that a separate tool would be better. This tool could also provide some statistics on these files and identify pending and empty transactions. All of this would help the analysis phase in case of issues. Finally, we would also need to specify that payloads are not included in these dumps, but only metadata.

**Comment by tombentley** [comment]
@fvaleri I think there are two things which could be improved: 

1. The extraction of log dumps (this issue)
2. The later analysis of those dumps, which often also requires correlation with broker logs. 

I think 2 is probably a different tool.
