### ISSUE TITLE
Incorrect pattern in the kafka-metrics config map

### ISSUE THREAD

**Issue by ivailopankow** [strimzi/strimzi-kafka-operator#5604]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
The order of arguments in the [kafka_server_$1_connections_tls_info](https://github.com/strimzi/strimzi-kafka-operator/blob/0.25.0/examples/metrics/kafka-metrics.yaml#L93) pattern is incorrect. Based on the pattern the arguments should be `cipher, protocol, listener, networkProcessor` rather than `listener, networkProcessor, protocol, cipher`

The current setup produces the following element in Prometheus

```bash
kafka_server_socket_server_metrics_connections_tls_info{cipher="3",listener="TLS_AES_128_GCM_SHA256",networkProcessor="TLSv1.3",protocol="REPLICATION-9091",strimzi_io_cluster="message-broker",strimzi_io_kind="Kafka",strimzi_io_name="message-broker-kafka"}
```

**To Reproduce**
1. Apply the [kafka-metrics.yaml comfiguration](https://github.com/strimzi/strimzi-kafka-operator/blob/0.25.0/examples/metrics/kafka-metrics.yaml)
2. Log to the corresponding Prometheus server
3. Search for `kafka_server_socket_server_metrics_connections_tls_info`
4. Observe the output

**Expected behavior**
The values of the labels should be correct

**Environment (please complete the following information):**
 - Strimzi version: `main`
 - Installation method: `YAML files` and `Helm Chart`
 - Kubernetes cluster: Kubernetes v1.19.12
 - Infrastructure: on premise 

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/main/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

**Comment by scholzj** [comment]
Thanks for reporting this. I opened a #5605  to fix it.
