### ISSUE TITLE
Add topic configuration settings to KafkaTopic CR status

### ISSUE THREAD

**Issue by katheris** [strimzi/strimzi-kafka-operator#5758]
**Is your feature request related to a problem? Please describe.**
As a user when I create a KafkaTopic it would be useful to see what configuration has been applied to the topic as some of these values may be set based on either Kafka or Strimzi defaults. This issue is being created based on a discussion in the community call on 21st October 2021.

**Describe the solution you'd like**
Add configuration details such as replication factor and minimum insync replicas into the KafkaTopic CR status field.

**Describe alternatives you've considered**
As an alternative developers could specify these values themselves in the CR so that they don't use any defaults

**Additional context**

**Comment by scholzj** [comment]
@katheris Did you had a chance to look into it? Is this still something we want / need?

**Comment by katheris** [comment]
Hey @scholzj, I've tested this and without the topic operator enabled I can create a `KafkaTopic` with no `partitions` or `replicas`, then once the topic operator comes up it puts in the values. So I think Tom is right that we don't need this because the user can just look at the `KafkaTopic` spec to determine the partitions and replicas
