### ISSUE TITLE
Add Cruise Control "monitoring" documentation section

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#5775]
**Is your feature request related to a problem? Please describe.**

We have had a couple users ask about monitoring Cruise Control in real time, more specifically about setting up alerts and reactions for a cluster's balancedness score. Luckily, Cruise Control provides metrics to monitor things like this [1] but it may be helpful to provide guidance on how to best do this, especially while we don't support Cruise Control's self healing functionality. 

**Describe the solution you'd like**
We could add a Cruise Control "monitoring" section explaining that Cruise Control metrics [1] are available for scraping as well as document things like:

- How the metric balancedness score differs from the balancedness score in the `KafkaRebalance` resource (e.g. the former is calculated using `anomaly.detection.goals` while the latter is calculated using `default,goals`)
- How a `KafkaRebalance` can be continually refreshed to reflect the latest state of the cluster and the performance impact of refreshing the `KafkaRebalance` resource.

Assuming there is no extra performance cost, it may even be good if we automatically set the value of `anomaly.detection.goals` to the value of `default.goals` if it is not provided by the user. That way, the value of the balancedness_score metric will match the balance score of the KR resource by default.

**Describe alternatives you've considered**
Leaving the documentation as is.

**Additional context**
[1] https://github.com/linkedin/cruise-control/wiki/Sensors

**Comment by PaulRMellor** [comment]
Monitoring section
