### ISSUE TITLE
User and Topic operators should have separate users

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#5791]
The User and Topic operator share today a single user as _Entity Operator_. This makes it hard to distinguish them in some metrics and monitoring for example such as the case with #5790. We should have a separate user for each of them.

**Comment by yyang48** [comment]
Is this _user_ from the **SASL_USERNAME** property? Where is this name set up in the `Entity Operator`?

**Comment by scholzj** [comment]
No, when deployed as part of the Kafka cluster, the User and Topic operators use TLS client authentication. So it is about using separate certificates for each of them.

**Comment by yyang48** [comment]
I see. Thanks for clarify!

**Comment by yyang48** [comment]
I checked this part, it seems like the "*-entity-operator-certs" is _currently_ used by three containers: topic operator, user operator and tls sidecar. Does it make sense to create two more new certificates: "*-entity-**user**-operator-certs" and "-entity-**topic**-operator-certs"? In this way, each container has its own certificates:

1. topic operator use the new "-entity-topic-operator-certs".
2. user operator use the new "-entity-user-operator-certs".
3. TLS sidecar from the entity-operator deployment use the existing "-entity-operator-certs"

WDYT?

**Comment by scholzj** [comment]
The TLS sidecar is now used only by the Topic Operator. So maybe it can just use the `-entity-topic-operator-certs` certs? But if it is somehow significantly easier to use `-entity-operator-certs` it might be fine as well.

**Comment by yyang48** [comment]
@scholzj should we close this issue now, because the PR is merged?

**Comment by scholzj** [comment]
@yyang48 Good point. Thanks for noticing.
