### ISSUE TITLE
Helm Installation failed（strimzi-kafka-operator: v0.26.0  ）

### ISSUE THREAD

**Issue by skycyan** [strimzi/strimzi-kafka-operator#5901]
strimzi-kafka-operator: v0.26.0
helm ： v3.7.1

### watchNamespaces ：This setting reports an error. Is the format wrong?
```
# vim values.yaml
watchNamespaces: kafka,kafka-cluster
watchAnyNamespace: false

# helm install strimzi-kafka-operator --namespace=strimzi -f values.yaml  /strimzi-kafka-operator
Error: INSTALLATION FAILED: template: strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml:69:25: executing "strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml" at <append $ns .Release.Namespace>: error calling append: Cannot push on type string
```

**Comment by scholzj** [comment]
Have you tried to use some kind of array?

**Comment by skycyan** [comment]
> Have you tried to use some kind of array?


## watchNamespaces: Comma separated list of additional namespaces for the strimzi-operator to watch.

## Tested the following example.
```
# vim values.yaml
watchNamespaces: kafka,kafka-cluster
watchAnyNamespace: false

or

watchNamespaces: 
   - kafka
   - kafka-cluster
watchAnyNamespace: false
```

**Comment by scholzj** [comment]
So, did it helped?

**Comment by skycyan** [comment]
> 那么，它有帮助吗？



> So, did it helped?

Sorry, there is no clear description.
The above example does not help and does not solve the problem.

**Comment by ShubhamRwt** [comment]
Hello @skycyan , If you want to pass the `watchNamespace` value, you can do it like this also -- `helm install strimzi --set 'watchNamespaces={myproject,myproject1}' packaging/helm-charts/helm3/strimzi-kafka-operator`. Apart from this if you want to pass it `values.yaml` as you are doing above I guess this is the right way :-
```
watchNamespaces:
  - myproject1
  - myproject3```

**Comment by ShubhamRwt** [comment]
Can you tell me what error are you getting with the second way ?

**Comment by skycyan** [comment]
> Can you tell me what error are you getting with the second way ?

Hello, return the following error.
```
watchNamespaces: 
   - kafka
   - kafka-cluster
   
# helm install strimzi-kafka-operator --namespace=strimzi -f values.yaml  /strimzi-kafka-operator
Error: INSTALLATION FAILED: template: strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml:69:25: executing "strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml" at <append $ns .Release.Namespace>: error calling append: Cannot push on type string
```

**Comment by ShubhamRwt** [comment]
Hello @skycyan, The second way I sent above works fine when I use it. Can you try passing the namespace using this command -->helm install strimzi --set 'watchNamespaces={myproject,myproject1}' packaging/helm-charts/helm3/strimzi-kafka-operator

**Comment by vyom-soft** [comment]
> > Can you tell me what error are you getting with the second way ?
> 
> Hello, return the following error.
> 
> ```
> watchNamespaces: 
>    - kafka
>    - kafka-cluster
>    
> # helm install strimzi-kafka-operator --namespace=strimzi -f values.yaml  /strimzi-kafka-operator
> Error: INSTALLATION FAILED: template: strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml:69:25: executing "strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml" at <append $ns .Release.Namespace>: error calling append: Cannot push on type string
> ```

I also see that it does not work. It only picks the first entry & rest of the entry are ignored. I used the latest helm chart 0.35
