### ISSUE TITLE
Using many spec.build.plugins.artifacts for KafkaConnect CRD causes image pull failure

### ISSUE THREAD

**Issue by brsolomon-deloitte** [strimzi/strimzi-kafka-operator#5915]
When including many (100+) `spec.build.plugins.artifacts` for a `kind: KafkaConnect` manifest, the build occurs and is successfully pushed to the Docker registry.

```
Taking snapshot of full filesystem...
USER 1001
cmd: USER
Pushing image to xxx.dkr.ecr.xxx.amazonaws.com/kafka-connect-distributed:latest
Pushed image to 1 destinations
```

However, the subsequent pull fails:

> Failed to pull image "xxx.dkr.ecr.xxx.amazonaws.com/kafka-connect-distributed@sha256:xxx": rpc error: code = Unknown desc = failed to register layer: max depth exceeded

A Googling around shows that this may be due to too many layers in the image.

This would make sense since it looks like each element of `artifacts` translates into a separate RUN instruction in the Docker image. For example,

```
RUN 'mkdir' '-p' '/opt/kafka/plugins/kafka-connect-s3/645caf7f'       && 'curl' '-L' '--output' '/opt/kafka/plugins/kafka-connect-s3/645caf7f/645caf7f.jar' 'https://repo1.maven.org/maven2/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar'
```

occurs like this for each JAR.

I can verify this on the fly by reducing the number of array members specified in `artifacts` - in this case the image pulls successfully, though now the connect cluster can't start right because it doesn't have the JARs it needs.

Some questions / suggestions on this:

- Thoughts on `failed to register layer: max depth exceeded`; any other interpretation of this besides too many layers?
- Open to modifying the build container so that there is no longer a 1:1 translation of JAR artifact to RUN command? Generally more layers = bad from an efficiency perspective also.

**Comment by brsolomon-deloitte** [comment]
Update: looks like this is done by Kaniko, so I realize it may not be fully under Strimzi operator's direct control anyway.

**Comment by scholzj** [comment]
I would be good to see your KafkaConnect custom resource to reproduce it as well as full logs to see what is actually failing. I guess you can try to use the ``-single-snapshot` Kaniko option if you are on Kubernetes (https://github.com/GoogleContainerTools/kaniko#--single-snapshot) to squash the layers.

But in general, there is also the question whether including so many JARs make sense. Why do you configure something like `https://repo1.maven.org/maven2/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar' as a separate artifact? Are you including all dependencies of a connector one by one? Why don't you just use the Maven or ZIP/TGZ artifacts?

**Comment by brsolomon-deloitte** [comment]
> But in general, there is also the question whether including so many JARs make sense. Why do you configure something like `https://repo1.maven.org/maven2/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar' as a separate artifact? Are you including all dependencies of a connector one by one? Why don't you just use the Maven or ZIP/TGZ artifacts?

Great question :) Because I'm using https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html#install-the-amazon-s3-sink-connector which provides neither a ZIP or TGZ. So to my dismay I cooked up a shell script that builds out the list of individual jar dependencies.

Also,

> Why don't you just use the Maven or ZIP/TGZ artifacts?

Strimzi only accepts type=TGZ, not ZIP, correct?

**Comment by brsolomon-deloitte** [comment]
Update: `--single-snapshot` did the trick for squashing the image layers.

Appreciate any comments you have on the above @scholzj but I will close this one. Thanks for being so responsive!

**Comment by scholzj** [comment]
> Update: looks like this is done by Kaniko, so I realize it may not be fully under Strimzi operator's direct control anyway.

Well, we generate the Docker file, so yes, each RUN command is a layer which can be in general changed. But then, I think that if we create single command downloading 100 JARs it might reach other limits. So I hope the `--single-snapshot` can help you, it is the easiest way I guess.

> Great question :) Because I'm using https://docs.confluent.io/kafka-connect-s3-sink/current/overview.html#install-the-amazon-s3-sink-connector which provides neither a ZIP or TGZ, only a single non-uber JAR. (There is a ZIP URL that is obfuscated by some JS code and sits behind cloudfront.) So to my dismay I cooked up a shell script that builds out the list of individual jar dependencies.

Yeah, they make it quite hard to get the connectors. I think I managed to dig out the download URL for ZIP file out of their website. But they clearly don't want people to do that :-).

> Strimzi only accepts type=TGZ, not ZIP, correct?

We have some more types now. JAR, ZIP, TGZ and Maven artifacts. With Maven you basically just specify the coordinates for Maven. You might be able to use that if the Confluent connector is in Maven. But I never tried it with Confluent connectors.

**Comment by scholzj** [comment]
> Update: --single-snapshot did the trick for squashing the image layers.

Glad this helped.

**Comment by brsolomon-deloitte** [comment]
> We have some more types now. JAR, ZIP, TGZ and Maven artifacts. With Maven you basically just specify the coordinates for Maven. You might be able to use that if the Confluent connector is in Maven. But I never tried it with Confluent connectors.

Ah, okay. I did dig out the cloudfront direct-download URL too but unsure if it will be stable / subject to change.

I do see `zip` now at `k explain kafkaconnect.spec.build.plugins.artifacts.type`. (Hadn't seen it on https://strimzi.io/docs/operators/latest/using.html#plugins so assumed it was not available.)

Thanks again.

**Comment by scholzj** [comment]
> I do see zip now at k explain kafkaconnect.spec.build.plugins.artifacts.type. (Hadn't seen it on https://strimzi.io/docs/operators/latest/using.html#plugins so assumed it was not available.)

Hmm, not sure why is it missing. I will have a look.

**Comment by scholzj** [comment]
I opened #5917 to add the ZIP artifacts there as well.
