### ISSUE TITLE
Kafka connect task failure metrics appearing 0 only

### ISSUE THREAD

**Issue by Abdul1929** [strimzi/strimzi-kafka-operator#5925]
Hi Team,

I am using kafka connect from strimzi opertaor and the opertaor version is 0.26.0 and kafka version is 2.8.0. I have enable the prometheus exporter and I can able to fetch the metrics but the problem is when I was checking the no of task failure the metrics is not accurate.
I have manually break the task from the connector but I am getting 
kafka_connect_connect_worker_metrics_task_startup_failure_percentage as zero only.
![image](https://user-images.githubusercontent.com/72790395/143013346-952f8730-7801-43a7-a0c9-2484bb2cc56c.png)

**Comment by scholzj** [comment]
Have you check what does this metric actually mean? It does not sound like counter of failed tasks but like of percentage of task startups which failed. That sounds like a different thing to me. Also, keep in mind that strimzi just exposed the metrics provided by Kafka. So if there is something wrong in the Grafana dashboard which Strimzi provides, we can try to fix it. But the metrics are what they are based on Kafka provides.
