### ISSUE TITLE
Support specifying container images from private registries

### ISSUE THREAD

**Issue by Manicben** [strimzi/strimzi-kafka-operator#5953]
**Is your feature request related to a problem? Please describe.**
We would like to use a Kafka operator to manage our clusters in internal and production environments. However, we have a strict requirement that container images can only be pulled from our own private registries.

Strimzi does not provide a way to specify our own images/registries for Kafka, Zookeeper, etc. We understand that we would have to mirror Strimzi's images from quay.io to our registries, or build the images ourselves, due to the custom scripts.

**Describe the solution you'd like**
Instead of specifying a Kafka version number, we'd like to expose the `image` field on the Kafka CR so we can point all images used by STSs/Deployments created by the cluster operator to our own container registry.

**Describe alternatives you've considered**
A hacky way to get around this is to create DNS records that point the quay.io images to our registry. However, this is not ideal for us.

We are willing to submit a PR for this, but we wanted to know beforehand whether this feature would be desirable to the community and is acceptable to the maintainers.

**Comment by scholzj** [comment]
This is supported today.

There are two ways how you can use your own images:
1) By configuring them at the operator level for all your operands
2) By configuring it at the custom resource level for each of your operands individually

Re 1: The Cluster Operator deployment has environment variables configuring the images which will be used. In addition you can also use the `STRIMZI_IMAGE_PULL_SECRETS` environment variable in the Cluster Operator to list any pull secrets if they are needed. For more details, check the docs:https://strimzi.io/docs/operators/latest/full/using.html#ref-operator-cluster-str + for the operator itself, you can just edit its deployment as you need.

Re 2) Every CR has an `image` field in its spec. In the Kafka CR, this is usually `.spec.kafka.image`, `.spec.zookeeper.image` etc., in the other CRs it is just `.spec.image`. You can use this field to configure your image. You can also configure the pull secrets in the custom resource in the PodTemplate configuration: https://strimzi.io/docs/operators/latest/full/using.html#type-PodTemplate-reference

**Comment by Manicben** [comment]
Thank you very much, I simply must've missed this when evaluating Strimzi and made assumptions based on the default behaviour. It is very clearly documented here https://strimzi.io/docs/operators/latest/using.html#con-common-configuration-images-reference and this would perfectly suit our use-case. Thanks again!
