### ISSUE TITLE
The `strimzi_resources{kind="Kafka"}` metric is not removed when the Kafka related namespace is deleted

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#6058]
Assuming to have a cluster operator deployment (version 0.26.0) watching ALL namespaces on a Kubernetes/OpenShift cluster, it seems that the `strimzi_resources{kind="Kafka"}` metric is not deleted when when the namespace where the `Kafka` CR lives is deleted (so the user deleted the resource and then the namespace).

It seems to be related to how these metrics are exported on each periodic reconcile here:

https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/main/java/io/strimzi/operator/common/Operator.java#L74

If across two reconcile cycles, a namespace with a `Kafka` CR is deleted so the corresponding Kafka instance, the namespace is not anymore in the `desiredNames` list and the corresponding metric is not removed; it will hang forever as a "zombie".

**Comment by scholzj** [comment]
> If across two reconcile cycles, a namespace with a Kafka CR is deleted so the corresponding Kafka instance, the namespace is not anymore in the desiredNames list and the corresponding metric is not removed; it will hang forever as a "zombie".

I do not think you need to delete the namespace. It should be enough if there is no other Kafka cluster in that namespace. Then the desiredNames will not have the namespace even if it still exists.

**Comment by ppatierno** [comment]
The use case I had was about deleting the namespace directly hence the `Kafka` CR was deleted, but I do agree that it doesn't matter.
