### ISSUE TITLE
Add support for `PodDisruptionBudgets` of version `v1`

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#6066]
Strimzi is currently using `PodDisruptionBudget` `v1beta1`. In Kube 1.25, the `v1beta1` version will be [removed](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125). We should add support for `v1` in Strimzi operator. Since the `v1` is introduced only in Kube 1.21, and Strimzi supports Kube 1.16+, we need for some time to support both `v1` and `v1beta1` versions. So the code needs to use the Kubernetes version detection and based on it use the correct PodDisruptionBudget API. (This is already done for `Ingress` API, so you can check that for inspiration)

**Comment by fjbecerra** [comment]
hey!, I'd like to work on this, assign it to me please!

**Comment by scholzj** [comment]
@fjbecerra Assigned.
