### ISSUE TITLE
Increase Replica count to 2 for kafka exporter

### ISSUE THREAD

**Issue by zarafree** [strimzi/strimzi-kafka-operator#6076]
** Problem**
I want to increase replica count for Kafka Exporter. I am not able to find any options/configurations to increase count replica for kafka exporter.
We are using 0.21 strimzi kafka in our environment in kubernetes environment.

**Comment by sknot-rh** [comment]
We do not support the increasing number of replicas for KE. As a workaround, you can copy generated Deployment and edit the number of replicas there.
Note - changing Deployment managed by strimzi will always roll back your changes. You will need you own copy of the deployment.
