### ISSUE TITLE
UserOperator: Keep the keystore password on certificate renewal

### ISSUE THREAD

**Issue by cpflaume** [strimzi/strimzi-kafka-operator#6173]
Hello, 
when using a KafkaUser with authentication.type: tls the UserOperator will provision a secret containing 
  ```ca.crt: PUBLIC-KEY-OF-THE-CLIENT-CA
  user.crt: USER-CERTIFICATE-CONTAINING-PUBLIC-KEY-OF-USER
  user.key: PRIVATE-KEY-OF-USER
  user.p12: P12-ARCHIVE-FILE-STORING-CERTIFICATES-AND-KEYS
  user.password: PASSWORD-PROTECTING-P12-ARCHIVE
```
I observed that when the UserOperator renews the user certificate, it also generate a new keystore with a new password. 
This can cause some issues with application mounting the keystore but having the password set via a different mechanism. E.g. in Nifi one can setup an SSLContext but the password cannot be read from an environment variable but has to be set via the UI. 

All this would not be a problem, if the password would stay the same on certificate renewal.
This would make it more easy for other applications to consume the secret without doing a full restart or in some cases necessary manual configuration. 

Would it be an option to keep the passwords the same? Or allow supplying a keystore/truststore password as part of the configuration? 

Edit: Same applies to the truststore password

**Comment by scholzj** [comment]
Triaged on 10.5.2022: There is no plan to implement this. Thsi might be seen as a security issue by others. Also, most Kafka clients can use the PEM files as well instead of the PKCS12 file which do not have any password. So this does not seem to be needed.
