### ISSUE TITLE
Single flag for enabling JSON logging

### ISSUE THREAD

**Issue by Oliver-Sellwood** [strimzi/strimzi-kafka-operator#6253]
**Is your feature request related to a problem? Please describe.**

JSON logging is a fairly common use case to enable more structured and useful logging. While this is true, setting up log4j is a complicated process and needs knowledge of application internals to do correctly.

**Describe the solution you'd like**

A simple flag that can enable or disable JSON logging for the entire operator stack.

**Describe alternatives you've considered**

I have followed the example provided here https://github.com/strimzi/strimzi-kafka-operator/issues/3104

But it's a complicated process (I was only able to sucessfully get ZooKeeper and Kafka to log to json), each service must be individually configured and some services I can't find any information to enable json logging eg. cruise control

**Comment by scholzj** [comment]
I think the problem is that everyone imagines _slightly different JSON logging_ with slightly different structures and different libraries. So there is no JSON logging which fits all. So I do not think we want to have any flag which configures it because there is no single way how to configure it.
