### ISSUE TITLE
MM2: Allow configuring topic pattern on connector level

### ISSUE THREAD

**Issue by dadufour** [strimzi/strimzi-kafka-operator#6273]
**Describe the bug**
When 2 MM2 are set to replicate topics from A to B and from B to A, offsets may not be synced from destination topics back to source topics.
In strimzi KafkaMirrorMaker2 CR, we define only 1 topic filtering through the _topicsPattern_ field. It is specified at _mirror_ item level and is not specific to a connector. Then what strimzi does is to propagate this property to **both** _sourceConnector_ and _checkpointConnector_.
The problem is that there are cases where we may need to have them set with different values.
Let's assume that you have a topic "my-topic" that exists on both clusters A and B and you want to set up a bi directional replication with offset sync and you use "my-topic" as value for _topicsPattern_.
The _checkpointConnectors_ will correctly sync offsets of consumers that consume on the source topic.
The problem is that it will NOT sync offsets of consumers that consume on the desctination topic because the name of this topic is different (it has a prefix, so should be someting like "A.my-topic") and it does not match the pattern "my-topic".

**To Reproduce**
1. Apply CRs ([MM2-bi-dir.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7957933/MM2-bi-dir.zip) )
2. Start producing on first cluster:
`echo "West 1" | kubectl exec -n kafka-test -i my-cluster-a-kafka-0 -- /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic test-switch`
3. Start consuming on first cluster:
`kubectl exec -n kafka-test -ti my-cluster-a-kafka-0 -- /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --whitelist ".*switch" --group my-group --from-beginning`
4. Stop consuming
5. Produce a message in first cluster:
`echo "West 2" | kubectl exec -n kafka-test -i my-cluster-a-kafka-0 -- /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic test-switch`
6. Produce a message in second cluster:
`echo "East 1" | kubectl exec -n kafka-test -i my-cluster-b-kafka-0 -- /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server localhost:9092 --topic test-switch`
7. Consume in second cluster:
`kubectl exec -n kafka-test -ti my-cluster-b-kafka-0 -- /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --whitelist ".*switch" --group my-group`
=> we get only 1 message (this is because offset for the destination topic in A was not sync in B and consumer started from the last offset)
8. Consume in first cluster:
`kubectl exec -n kafka-test -ti my-cluster-a-kafka-0 -- /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --whitelist ".*switch" --group my-group`
=> we get the same message as in second cluster (this is because offset for the destination topic in B was not sync in A and consumer reconsumed what was already consumed in the other cluster)

**Expected behavior**
In 7. we should get 2 messages (no message lost)
In 8. we should get 0 message (no double consume)
I want to be able to specify different topic patterns for Source and Checkpoint connectors to be able to sync data and offsets correctly for bi directional flow.

**Environment (please complete the following information):**
 - Strimzi version: 0.27.1
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.21.1
 - Infrastructure: Minikube

**YAML files and logs**
[MM2-bi-dir.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7957933/MM2-bi-dir.zip)

**Additional context**
A workaround is to always use a topic pattern starting with '.*'

**Comment by scholzj** [comment]
Sorry, I'm not completely sure I follow what is the bug on this and why is it a bug in Strimzi. Can you please explain what is Strimzi doing wrong? It really just configures Mirror Maker and nothing more.

**Comment by dadufour** [comment]
The issue is actually the way it configures Mirror Maker 2. Strimzi imposes to have the same topic filtering for both of the connectors. When we configure Mirror Maker 2 "manually" (using the REST API), we are free to set different filtering, hence to achieve what we want, which may be required in some scenario.
Note that for source connector, the topic filtering applies to source topics only.
For checkpoint connector, the topic filtering usually applies to source topics as well but you may need to apply to destination topics as well. So on semantics point of view, they are 2 different notions and strimzi should not merge them into a single one IMO.

**Comment by scholzj** [comment]
Wait, so, you are saying that the fields such as `topicsPattern`, `topicsExcludePattern`, `groupsPattern` etc. should not be on the level they are at but inside the connector definitions?

**Comment by dadufour** [comment]
Yes, at least for topicsPattern: I believe we should have it at connector level, inside the the SourceConnector and CheckpointConnector. Not sure why groupsPattern is not inside the CheckpointConnector as I don't think it is used outside.

**Comment by scholzj** [comment]
Ok, thanks. Now I understand it a bit better. 

I'm not sure I would call it a bug -> it is probably more enhancement for me. I guess we need to figure out the API (how should it look like, what to do with the existing fields etc.). But apart from that it might be fairly straight forward to implement.

**Comment by dadufour** [comment]
I agree that it's between the bug and the enhancement. And most of the difficulty is probably to define the new API and how to migrate.

**Comment by scholzj** [comment]
Triaged on 10.5.2022 ... 

@dadufour If we properly understood the use-case, this does not seem to be possible given how Mirror Maker 2 works:

* The group pattern is used for the checkpoint connector. The topic pattern is used for the source connector. So if the configuration is moved to the connector level, there will not be topic pattern configured in the checkpoint connector.
* In order to sync the offsets, the checkpoint connector needs to know 1) how are the offsets translated and 2) how is the topic name translated. The information for translating the offsets is provided by the source connector when it is mirroring the records. So when you are not mirroring the topics, the cannot mirror the offsets for them.

So at the end I don't think it matters where is the topic pattern configured.

CC @mimaison

**Comment by dadufour** [comment]
`So if the configuration is moved to the connector level, there will not be topic pattern configured in the checkpoint connector.`
The problem is that we don't necessarily want the EXACT same pattern for the source connector and the checkpoint connector.
Let's assume you want to do bi-directional replication between clusters A and B of a topic named "foo" (and you use the default policy so that the remote topic is name A.foo or B.foo). Let's say you want to synchronize the offsets for this topic.
If you put in your custom resources for MM2:
 - topicPattern = "foo": the data will be replicated but offsets will only be synced from the source topic to the destination and not in the opposite direction because A.foo (or B.foo) does NOT match the topicPattern
  - topicPattern = "*.foo": OK, this time the offsets are correctly synced in both directions but if you have a topic called "bar.foo", it will be replicated even if you don't want to (because it will match the pattern).
  
`In order to sync the offsets, the checkpoint connector needs to know 1) how are the offsets translated and 2) how is the topic name translated.`  
Do you mean that MM2 is supposed to recognize the remote topics by itself, from the topicPattern and the policy that is used to name the remote topic from the source name? I don't think so because there is no reference between a checkpoint connector to the related source connector, they are independant and that's why in MM2, the topicPattern is at connector level.

**Comment by scholzj** [comment]
I think I understand what would you want to have and I agree that it would be perfect if it worked that way. But what I'm saying is that I don't think MM2 supports it (in any form, not just in the way Strimzi deploys MM2).

My understanding of the way the offset mirroring works is following:
* The source connector mirrors topic `foo` in source cluster `A` to topic `A.foo` in target cluster `B`.
* While it mirrors the records, it knows that the record on offset 113 in `foo` was stored as offset `98` in `A.foo`
* It stores this information periodically and passes it to the checkpoint connector
* The checkpoint connector follows the offsets commits. And when it sees a commit for topic `foo`, offset `113`, it will mirror it to the target cluster as committed offset `98` for topic `A.foo`.
* But for the topics which are not mirrored through the source connector, it does not know how the offsets allign so it AFAIK cannot mirror the offsets. It would somehow need to gain the understanding of the topic mapping (i.e. that topic `A.foo` is a copy of `foo`) and it would need to have access to the translation table from the other cluster to know that the offset `98` in the cluster B for topic `A.foo` will translate to offset `113` of topic `foo` in the original cluster.

> * topicPattern = "foo": the data will be replicated but offsets will only be synced from the source topic to the destination and not in the opposite direction because A.foo (or B.foo) does NOT match the topicPattern

Correct. This is my expectation how will it work with these settings as well.

> * topicPattern = "*.foo": OK, this time the offsets are correctly synced in both directions but if you have a topic called "bar.foo", it will be replicated even if you don't want to (because it will match the pattern).

I do not think this is how it will work. If you get it to mirror the already mirrored topic, it will be mirrored as a brand new topic. E.g. if you have clusters `A` and `B` and topic `foo` on both of them, the topic `foo` will be mirrored from `A` to `B` into a new topic named `A.foo`. And if you get MM2 to mirror it again, it will be mirrored as `B.A.foo` And the offsets will be mirrored for `baz.bar.foo` as well and not for `foo`. So this will not work to sync the offsets.

> Do you mean that MM2 is supposed to recognize the remote topics by itself, from the topicPattern and the policy that is used to name the remote topic from the source name? I don't think so because there is no reference between a checkpoint connector to the related source connector, they are independant and that's why in MM2, the topicPattern is at connector level.

TBH, I do not know how it does it on the technical level, but IIRC it does. When you use the default topic pattern which just matches all topics, it will not mirror the already mirrored topics.

----

On the triage call we discussed it with @mimaison who knows MM2 very well. If you wantm we can get back to it in one of the community calls for example to discuss more details.

**Comment by dadufour** [comment]
The topic is a bit complex ;). I don't pretend to be an MM2 expert but what I can say is that I am able to make things work when I configure the connectors by myself (without strimzi).
I agree with you up to `I do not think this is how it will work.`
Let me just review the example we used. The setup is as follows (bi-directional):

- source connector `A->B`:
     topicPattern: foo

- checkpoint connector `A->B`:
     topicPattern: foo
     groupPattern: bar

- source connector `B->A`:
     topicPattern: foo

- checkpoint connector `B->A`:
     topicPattern: foo
     groupPattern: bar

What is important to notice is that the checkpoint connector `A->B` not only needs to sync offsets for consumers consuming on foo in A **but needs to sync offsets for consumers consuming on B.foo in A as well**. Keep in mind that in this setup, consumers are configured to consume from `*.foo` so that they don't care about where are the producers (in A or in B).  If you don't have this, you fall into the problem I am raising, i.e. **the switch of a consumer from A to B will not work as expected**. And if you want to make it, the topicPattern of checkpoint connector `A->B` can not be simply 'foo' (but rather *.foo).

There is one fondamental difference between the source connector and the checkpoint connector: the source connector copies data from source topics **only** to remote topics. The checkpoint connector sync offsets from source **AND** remote topics to remote and source topics. That's why the topicPattern is semantically different in both connectors.

I did the setup manually and it works as expected so that is why I don't really agree with you when you say `But what I'm saying is that I don't think MM2 supports it`

I am able to make it work manually because I can set different pattern in the source and checkpoint connector, which is not possible using strimzi.
Maybe there is another way to achieve what I want with strimzi but I don't see how (except using '*.foo' as topicPattern but this may replicate unwanted topics by the source connector)

**Comment by scholzj** [comment]
So how does it know what is the corresponding offset for the topics it does not sync?

**Comment by scholzj** [comment]
PS: Can you share the configurations with which you got it working? Maybe they will make it more clear.

**Comment by dadufour** [comment]
I don't remember the technical details (I can try to retrieve some notes when I studied this) but if I remember well, this is done through some internal topics. But I can tell you it does.

**Comment by dadufour** [comment]
This is what I used (connector configs to be submitted to the REST API)
```
{
    "name": "mirror-us-west-to-us-east",
    "config": {
      "connector.class": "org.apache.kafka.connect.mirror.MirrorSourceConnector",
      "tasks.max": "2",
      "source.cluster.alias": "us-west",
      "target.cluster.alias": "us-east",
      "source.cluster.bootstrap.servers": "my-kafka-west:9092",
      "target.cluster.bootstrap.servers": "my-kafka-east:9092",
      "topics": "test.*",
      "sync.topic.acls.enabled": "false",
      "sync.topic.configs.enabled": "true",
      "refresh.topics.enabled": "true",
      "refresh.topics.interval.seconds": "10"
    }
}
{
    "name": "mirror-us-west-from-us-east",
    "config": {
      "connector.class": "org.apache.kafka.connect.mirror.MirrorSourceConnector",
      "tasks.max": "2",
      "source.cluster.alias": "us-east",
      "target.cluster.alias": "us-west",
      "source.cluster.bootstrap.servers": "my-kafka-east:9092",
      "target.cluster.bootstrap.servers": "my-kafka-west:9092",
      "topics": "test.*",
      "sync.topic.acls.enabled": "false",
      "sync.topic.configs.enabled": "true",
      "refresh.topics.enabled": "true",
      "refresh.topics.interval.seconds": "10"
    }
}
{
    "name": "checkpoint-us-west-to-us-east",
    "config": {
      "connector.class": "org.apache.kafka.connect.mirror.MirrorCheckpointConnector",
      "source.cluster.alias": "us-west",
      "target.cluster.alias": "us-east",
      "source.cluster.bootstrap.servers": "my-kafka-west:9092",
      "target.cluster.bootstrap.servers": "my-kafka-east:9092",
      "groups": "my-group.*",
      "topics": ".*test.*",
      "refresh.groups.enabled": "true",
      "emit.checkpoints.enabled": "true",
      "emit.checkpoints.interval.seconds": "10",
      "sync.group.offsets.enabled": "true",
      "sync.group.offsets.interval.seconds": "10",
      "refresh.groups.interval.seconds": "10"
    }
}
{
    "name": "checkpoint-us-west-from-us-east",
    "config": {
      "connector.class": "org.apache.kafka.connect.mirror.MirrorCheckpointConnector",
      "source.cluster.alias": "us-east",
      "target.cluster.alias": "us-west",
      "source.cluster.bootstrap.servers": "my-kafka-east:9092",
      "target.cluster.bootstrap.servers": "my-kafka-west:9092",
      "groups": "my-group.*",
      "topics": ".*test.*",
      "refresh.groups.enabled": "true",
      "emit.checkpoints.enabled": "true",
      "emit.checkpoints.interval.seconds": "10",
      "sync.group.offsets.enabled": "true",
      "sync.group.offsets.interval.seconds": "10",
      "refresh.groups.interval.seconds": "10"
    }
}
```

**Comment by mimaison** [comment]
Hi @dadufour,

Thanks for the details explanations. 

The checkpoint connector is useful when a topic is mirrored by the source connector. The remote topic will have different offsets than the original topic, and the role of checkpoint connector is to translate offsets so a consumer can switch from the original topic in the first cluster to the remote topic in the second cluster seamlessly.

In order to work, the checkpoint connector depends on the source connector mirroring topics that consumers have committed offsets for. The source connector builds a mapping (stored in the offset-syncs topic) that the checkpoint connector needs to function.

In your scenario, a consumer reads from `A.topic` on cluster B. `A.topic` is a remote topic, it comes from cluster A, so even in a 2 way mirroring setup, the source connector will not mirror this topic back to cluster A. So in this case, there's no point for the checkpoint connector to attempt committing offsets for groups that made commits for `A.topic` (on cluster B) to cluster A. Actually the checkpoint connector is not even able to translate offsets for `A.topic` because there is no mapping for `A.topic` in the offset-syncs topic. Currently when this happens, the checkpoint connector simply commits the non-translated offsets but these offsets don't correspond to anything meaningful in the second cluster. It may seem to "work" in a simple test environment because offsets between both cluster match but as soon as offsets start diverging, and this happens all the time, the offsets have no value in the second cluster.

There's actually work in progress in the Apache Kafka community (https://github.com/apache/kafka/pull/11748) to stop the checkpoint connector emitting offsets when there's no mapping available. These offsets will always have no meaning and they can actually be confusing and cause issues in many cases.

There is one use case for using a different `topics` settings for both the source and checkpoint connector. It is when you set the `topics` setting on the checkpoint connector to a subset of the value of the source connector. For example consumer groups contain offsets for topics that are not mirrored and hence you want the checkpoint connector to ignore them. Once https://github.com/apache/kafka/pull/11748 is merged this will happen automatically.

I hope this clarifies the confusion around this issue. Let us know if you have any further questions.

**Comment by dadufour** [comment]
Ok, the discussion here actually joins the point raised by urbandan https://github.com/apache/kafka/pull/11748#discussion_r815676139

So finally, I close this issue as what I want is actually currently not supported by MM2 and the behavior that seemed to work was actually the result of a side effect coming from a "weird feature" inside the checkpoint connector.

**Comment by sgn2607** [comment]
@dadufour I'm facing a similar issue and using Strimzi. Do you know if there is any KIP on this issue from MM2 or did you handle it manually by checking the consumer group offsets from remote cluster and seek it manually?

**Comment by dadufour** [comment]
@sgn2607 : I didn't check recently. So far we don't use failback capability. I understood that technically, all the information to implement this feature in MM2 is already there but still, the reverse mapping of the offsets would be quite complex to implement.
