### ISSUE TITLE
Deprecate CPU + DISK capacity limit settings

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#6293]
**Is your feature request related to a problem? Please describe.**
Following [1] since Cruise Control `CPU` and `Disk` capacities are handle automatically by Kubernetes and Strimzi for the whole Kafka cluster we should remove the ability for users to be able to configure these values themselves. We can do this by deprecating the following fields in the Kafka resource:

- ```spec.cruiseControl.capacity.cpu```
- ```spec.cruiseControl.capacity.disk```

**Describe the solution you'd like**
Deprecate the ```spec.cruiseControl.capacity.cpu``` and ```spec.cruiseControl.capacity.disk``` in the Kafka resource and remove any related logic.

**Additional context**
[1] https://github.com/strimzi/strimzi-kafka-operator/pull/5918

**Comment by see-quick** [comment]
Should be this issue now closed, when PR related to this topic was merged?
