### ISSUE TITLE
Watch all namespaces by TopicOperator

### ISSUE THREAD

**Issue by anorm** [strimzi/strimzi-kafka-operator#6301]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to declare `KafkaTopic` in other namespaces than the one where the topic-operator is deployed. For security reasons, we might want to give specific ACLs on namespace and resources for different users.

**Describe the solution you'd like**
We want a way, either a config in Kafka CRD, or an env var, to tell the topic-operator to watch for KafkaTopic in all namespaces, as we can do for the kafka-operator itself via the var `STRIMZI_NAMESPACE=*`. It could even reuse this information and watch the same namespace as configured in the kafka-operator

**Describe alternatives you've considered**
A workaround consists of copying secrets from one namespace to another, or putting all topics in the same namespace, but we go back to the security issue mentionned above

**Additional context**
Copy of #5895 but for KafkaTopic

**Comment by scholzj** [comment]
I think this is covered in #1206

**Comment by anorm** [comment]
Oh, yes. I didn't see that one.

The only thing I don't see if is covered or not is is a `KafkaUser` in another namespace than the one that owns the `KafkaTopic` will be able to have access to the namespaced topic.

In my situation, I have two services, each running in their own kubernetes namespace. Service A should own the kafka topic and a user who can produce messages to the topic. Service B (in another namespace) should be able to subscribe to the same topic. Service A should own/deploy the CRDs for the topic and the producing user but Service B should deploy the CRD for the subscribing user.

In my mind, the solution would not involve "namespaced topics" but rather global topics which are defined by resources in different namespaces. So, for me, it would be enough to change the TopicOperator and the UserOperator to watch all namespaces. If, however, #1206 covers the above example, this issue is redundant.

---

A possible solution to the obvious problem of multiple `KafkaTopic`s having the same topic name but in different namespaces, could be that the TopicOperator decorates the `KafkaTopic` instance with the name of the first namespace who "claims" the topic name. The topic would then be "locked" to this namespace, and the operator would mark all other `KafkaTopic` resources with the same name with an error status.

**Comment by scholzj** [comment]
Well, I think the _locked_ part is much easier on paper than in reality. Plus the fact that many topics are created in Kafka first makes all of this a complete hell because you do not know where to lock it into. Realistically, I'm not sure there will be any solution unless Kafka starts support some form of namespacing / multitenancy to base this on.

**Comment by anorm** [comment]
OK. Thanks for your feedback :-)
