### ISSUE TITLE
Make the size of the `StrimziPodSetController` work queue configurable

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#6305]
The `StrimziPodSetController` class is using a work queue which has currently fixed size of `1024`. For operators handling many pods, it might make sense to have this configurable. A new configuration option should be added (as environment variable) to `ClusterOperatorConfig` and passed to the controller as parameter.

**Comment by aravindgijandren-ag** [comment]
Hi @scholzj , I would like to work on this issue. Kindly assign it to me.

**Comment by scholzj** [comment]
Done. Let me know if you need any help or have any questions.

**Comment by aravindgijandren-ag** [comment]
sure, thank you so much!
