### ISSUE TITLE
Strimzi Quickstart Configured service account doesn't have access. Service account may have been revoked.

### ISSUE THREAD

**Issue by sgreszcz** [strimzi/strimzi-kafka-operator#6307]
**Describe the bug**
Installing Strimzi operator as per: https://strimzi.io/docs/operators/latest/quickstart.html into fresh Rancher Desktop k3s.  (Also tried the same demo in kubespray/kubeadm production k8s cluster.

I've followed the steps by both changing the namespace using the suggested:
```
sed -i '' 's/namespace: .*/namespace: kafka/' install/cluster-operator/*RoleBinding*.yaml
```
as well as leaving it default using the "myproject" namespace.

operator pod doesn't deploy properly and gives "CrashLoopBackOff", the problem seems to be service account access:
```
ERROR Main:154 - Cluster Operator verticle in namespace my-kafka-project failed to start
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.43.0.1/apis/kafka.strimzi.io/v1beta2/namespaces/my-kafka-project/kafkas. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. kafkas.kafka.strimzi.io is forbidden: User "system:serviceaccount:kafka:strimzi-cluster-operator" cannot list resource "kafkas" in API group "kafka.strimzi.io" in the namespace "my-kafka-project".
```

**To Reproduce**
1. Go to https://strimzi.io/docs/operators/latest/quickstart.html
2. Follow instructions on quickstart
3. Run command "kubectl get pods --all-namespaces" then kubectl -n kafka logs strimzi-cluster-<pod_id>
4. See error in logs

**Expected behavior**
a stable operator installed, and the ability to deploy kafka objects.

**Environment (please complete the following information):**
 - Strimzi version: strimzi-0.27.1
 - Installation method: github files as per https://strimzi.io/docs/operators/latest/quickstart.html
 - Kubernetes cluster: Rancher Desktop v1.21.7+k3s1 (also tried on kubeadm/kubespray v1.21.4, same problem)
 - Infrastructure: Rancher Desktop, kubespray.

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.
[strimzi.txt](https://github.com/strimzi/strimzi-kafka-operator/files/7995442/strimzi.txt)

**Comment by ShubhamRwt** [comment]
Did you give permission to the Cluster Operator to watch the my-kafka-project namespace? I guess you might have missed the 7th step:- 

Give permission to the Cluster Operator to watch the my-kafka-project namespace.
1. kubectl create -f install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n my-kafka-project
2. kubectl create -f install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml -n my-kafka-project

**Comment by sgreszcz** [comment]
> Hi, Did you followed the next step? I guess you might have missed the 7th step:-
> 
> Give permission to the Cluster Operator to watch the my-kafka-project namespace.
> 
> 1. kubectl create -f install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml -n my-kafka-project
> 2. kubectl create -f install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml -n my-kafka-project

Yep, I did those steps everytime.  I think it has to do with the way the sed script interacts with the RoleBiinding operators or something.  I'll do it another time tomorrow, manually and see what happens.  Thanks for the reply.

**Comment by scholzj** [comment]
I re-run the quickstart guide myself and all seems to work fine. So I think there must be something you are missing. I guess you should doublecheck your steps and make sure they do what they should. (I’m on a Mac, so I didn’t tried the Linux sed command).

**Comment by scholzj** [comment]
The `sed` command changes the namespace of the Service account. After you run it, it should look like this in the role bindings:
```yaml
# ...
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: kafka # <------------------ THIS IS THE PART IT CHANGES
#...
```

**Comment by sgreszcz** [comment]
I rebuilt using the same commands as yesterday both in the laptop version and in our prod testbed and all it working.  I have no idea what went wrong, maybe it was the cut/paste into the mac terminal.  This time I went through all the yaml to make sure the sed scripts had run - maybe it was that.  Apologies for this.

```
kubectl get pods -n kafka
NAME                                        READY   STATUS    RESTARTS   AGE
strimzi-cluster-operator-5cc7bbcd6c-bz7k5   1/1     Running   2          4m4s
```

```
kubectl get pods -n my-kafka-project
NAME                                          READY   STATUS    RESTARTS   AGE
my-cluster-entity-operator-76cb666d46-khbks   3/3     Running   0          55s
my-cluster-kafka-0                            1/1     Running   0          78s
my-cluster-zookeeper-0                        1/1     Running   0          2m11s
my-cluster-zookeeper-1                        1/1     Running   0          2m11s
my-cluster-zookeeper-2                        1/1     Running   0          2m11s
```

**Comment by iagotomas** [comment]
I'm facing the same issue but with Helm deployment, I [configured the deployment to watch any namespace](https://github.com/strimzi/strimzi-kafka-operator/tree/main/helm-charts/helm3/strimzi-kafka-operator#configuration) and the pod throws the same error. Can you help please?

**Comment by all4innov** [comment]
same as @iagotomas . Any tips ?

**Comment by jtqfaire** [comment]
+1

**Comment by jtqfaire** [comment]
@all4innov I had install cluster operator with this command and it's works now => kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka

**Comment by cslovell** [comment]
I noticed that `https://strimzi.io/install/latest?namespace=kafka` works but `https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.35.1/strimzi-cluster-operator-0.35.1.yaml` has the error above (still). Would be nice if there were a way to pin the version in the command that works.

**Comment by scholzj** [comment]
@cslovell Did you updated the namespace in the ClzsteRoleBindings when using the YAML file from the release files?
