### ISSUE TITLE
Add support for Kubernetes 1.22 and OpenShift 4.9

### ISSUE THREAD

**Issue by knutejoh** [strimzi/strimzi-kafka-operator#6311]
Kubernetes 1,22 (and as such, Openshift 4.9) remove several APIs which have been deprecated or marked as beta. In Openshift there is an upgrade check before upgrading from 4.8 to 4.9, and it reports that Strimzi is using one of the API's that are being removed, and as such blocks an upgrade. The report states that there are requests from username: system:serviceaccount:openshift-operators:strimzi-cluster-operator towards clusterrolebindings.v1beta1.rbac.authorization.k8s.io which is being removed (see https://access.redhat.com/articles/6329921 for details about other API's).

Please update the code to allow users to upgrade to these new versions.

**Comment by im-konge** [comment]
Hi @knutejoh ,
as is written for each release, you should use API conversion tool before upgrading to newer version (https://strimzi.io/docs/operators/0.24.0/deploying.html#assembly-upgrade-resources-str). This will ensure that APIs, which are removed in newer version of OpenShift or K8s, will be upgraded and you will not have any further conflicts.

**Comment by knutejoh** [comment]
Hi @im-konge . I'm not sure I follow. The report states this:

apiVersion: apiserver.openshift.io/v1
kind: APIRequestCount
metadata:
  name: clusterrolebindings.v1beta1.rbac.authorization.k8s.io
status:
  currentHour:
    byNode:
    - byUser:
      - byVerb:
        - requestCount: 11
          verb: get
        requestCount: 11
        userAgent: okhttp/3.12.6
        username: system:serviceaccount:openshift-operators:strimzi-cluster-operator
      requestCount: 11

So bascially it states that the strimzie clusteroperator user is doing gets towards the old rbac API. Does updating the version of the Strimzi CRDs change this behaviour?

**Comment by knutejoh** [comment]
![image](https://user-images.githubusercontent.com/5584917/152612983-2135d93b-5271-4f3a-b0f6-2eb2a00755a9.png)

And it looks like all my CRDs are a the correct version?

**Comment by knutejoh** [comment]
Actually, looking at the report more closely, it looks like he requests originate from the master servers, and not the worker nodes where the Strimzi operator is running. Could this somehow be connect to the packaging in OLM, since that's the method I've used to install and upgrade Strimzi?

**Comment by im-konge** [comment]
Sorry, if my answer wasn't clear at first.

The conversion tool upgrades both CRDs (https://strimzi.io/docs/operators/0.24.0/deploying.html#proc-upgrade-cli-tool-crds-str) and CRs (https://strimzi.io/docs/operators/0.24.0/deploying.html#proc-upgrade-cli-tool-direct-str).

CRDs looks good, it looks like `system:serviceaccount:openshift-operators:strimzi-cluster-operator` doesn't have upgraded version of API. Can you take a look which version it has?

**Comment by scholzj** [comment]
@knutejoh Strimzi supports Kube 1.22 / OCP 4.9 from version 0.23 on. If you use 0.22 or older version, you will have to upgrade (in which case you should pay attention to the links from @im-konge). If you use 0.23 or newer, you should be fine. Keep in mind that operators and Kubernetes clients might use different API versions on different Kubernetes versions. So while the report about usage of the old APIs is good to raise attention, it doesn't really give a proper about the actual support.

**Comment by knutejoh** [comment]
@scholzj I startet at 0.23 and am now running 0.27.1 through OLM. So the fabric8 client will use the old version "because it can", and when I upgrade stop because it can't? So I should be able to upgrade without any worries?

@im-konge the service account is at version 1:
kind: ServiceAccount
apiVersion: v1
metadata:
  name: strimzi-cluster-operator
  namespace: openshift-operators

**Comment by scholzj** [comment]
> @scholzj I startet at 0.23 and am now running 0.27.1 through OLM. So the fabric8 client will use the old version "because it can", and when I upgrade stop because it can't? So I should be able to upgrade without any worries?

Yeah, basically, we detect version of Kubernetes (or even directly check the versions of the supported APIs to detect OpenShift for example) and based on that do a different calls. The reason to keep using the older APIs while the new once are already available is for example because the implementation using them is proven from previous versions and there is less risk of breaking something by keeping using them. And the new APIs are then used only for the newer Kube versions.

If you are on 0.27.1 you are fine, you can upgrade your cluster.

**Comment by knutejoh** [comment]
Just updated our test-cluster, and Strimzi looks like it's working perfect. No errors in the logs at least :) Will close this :)
