### ISSUE TITLE
upgrading CRs and CRDs with operator init container instead of non-devops JRE sh Tool

### ISSUE THREAD

**Issue by shalberd** [strimzi/strimzi-kafka-operator#6330]
**Is your feature request related to a problem? Please describe.**
I was frankly very dismayed by the fact then when upgrading CRs and CRDs under openshift, having tried to upgrade the operator to >v0.22, I am supposed to run a shell script, requiring a JRE on a e.g. jumphost

https://strimzi.io/docs/operators/0.24.0/deploying.html#proc-upgrade-cli-tool-files-str

**Describe the solution you'd like**
Other operators like ELK Operator manage to update the CRDs, unsure about CRs, themselves. 

**Describe alternatives you've considered**
None

**Additional context**
In a devops environment, your suggested solution with the shell script and java class behind it, is very cumbersome.
You should dockerize that somehow and integrate it into the operator.

**Comment by scholzj** [comment]
Thanks for the feedback. It is a valid point. But it is not as easy as you make it sound. When we do that, other users will complain about the need for too many RBAC rights etc. There is no one way which will suite everyone and we cannot really spend all our time on preparing different variants how to do things to make everyone happy.

In any case, next time such conversion is needed, we will see what options are available (I think today for example the OperatorHub can do some things automatically which were not supported in the past) and take this kind of feedback and the overall experience with the `v1beta2` conversion into account. I would say that if we were doing it again today, I would certainly try to integrate it directly into the operator in some way.

But I do not think we will in any way rework the conversion to `v1beta2` which was done a year ago. So I'm not sure it makes any sense to keep this issue open TBH.

**Comment by shalberd** [comment]
Sounds reasonable, thanks. Closing ticket.
