### ISSUE TITLE
Document exposing brokers to clients outside the Kubernetes cluster

### ISSUE THREAD

**Issue by msample** [strimzi/strimzi-kafka-operator#646]
What is the recommended practice for allowing Kafka producers and consumers outside of the Kubernetes cluster (that don't use Zk for offsets etc) to see the bootstrap brokers in a relatively stable, configuration-friendly way?

**Comment by scholzj** [comment]
This is currently not possible. But we have it in our backlog (#128 ).

**Comment by msample** [comment]
Thanks. Pardon the duplicate.   Search term boost: broker external IP external-ip address addresses port ports ingress

**Comment by scholzj** [comment]
No need to apologise ... there is a lot of issues and its not always easy to find the right one. Lets add the keywords to the description of the original issue. Is it ok to close this issue now?

**Comment by msample** [comment]
yes, please close this one.
