### ISSUE TITLE
Cold-backup script does not work on MacOS

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#6470]
The cold-backup tool does not work on MacOS. It fails with following error:

```
tar: Option --no-check-device is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
```

This is probably because of code like this:

```
    kubectl -n "$NAMESPACE" exec -i "$RSYNC_POD_NAME" -- bash -c "tar $flags -C /data -c ." \
      | bash -c "tar $flags -C $target -xv -f - && if [[ $? == 1 ]]; then exit 0; fi"
```

I suppose that the aliases set at the start of the script are no used when a new bash is started.

**Comment by scholzj** [comment]
CC @fvaleri

**Comment by fvaleri** [comment]
OK, I don't have a MacOS machine to test it anymore. I added that subshell commands to make shellcheck happy. Without `bash -c "..."` should work, but let's try to add the export command just before that row:

```    
    export flags target
    kubectl -n "$NAMESPACE" exec -i "$RSYNC_POD_NAME" -- bash -c "tar $flags -C /data -c ." \
      | bash -c "tar $flags -C $target -xv -f - && if [[ $? == 1 ]]; then exit 0; fi"
```

**Comment by scholzj** [comment]
The `flags` and `target` are fine I think because in the error the `--no-check-device` got passes to the `tar` executable`. But the aliases mapping `tar` to `gtar` IMHO don't work because it is calling the original `tar` and not `gtar`.

**Comment by fvaleri** [comment]
I think you are right. Aliases are not inherited in sub processes.
