### ISSUE TITLE
Cold-backup script does nto work when StrimziPodSets are used

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#6471]
The Cold backup tool does not support the StrimziPodSets. When the StatefulSets don't exist,it tries to do the backup without scaling down the pods. But this does not work because it does not et a clear access to the storage while the brokers / ZooKeepers are running. It will either never mount the volume (with RWO volumes) or it will mount it (with RWM volumes), but usually fail during backup when any of the files change.

**Comment by scholzj** [comment]
CC @fvaleri

**Comment by scholzj** [comment]
The PR #6472 disabled running the Cold backup STs with StrimziPodSets. It should be re-enabled when this is fixed.

**Comment by fvaleri** [comment]
Thanks for raising this @scholzj. I'll look into it.
