### ISSUE TITLE
report.sh in main stream does not work in a MacOS

### ISSUE THREAD

**Issue by xiwu** [strimzi/strimzi-kafka-operator#6491]
**Describe the bug**
cannot run the report.sh in MacOS 

**To Reproduce**
`./report.sh --namespace myproject --cluster kafka-base`

`./report.sh: line 17: gecho: command not found`

`./report.sh: line 22: gecho: command not found`

**Expected behavior**
/report.sh can run on all the platforms

**Environment (please complete the following information):**
 - Strimzi version: [main]

**Comment by scholzj** [comment]
Can you provide some actual logs, ZIP file with the output or proper description of the issue and not just the issue template?

**Comment by xiwu** [comment]
Updated the description.

**Comment by scholzj** [comment]
The tool is using GNU versions of different command line tools (whcih in many cases differ from the BSD versions used by MacOS). So to use the tool, you have to install the GNU versions of these tools and have them in our path with the `g` prefix. E.g. `gtar`, `gsed`, `gecho` etc. It looks like maybe this is missing in your case?

**Comment by fvaleri** [comment]
Hi, if you are using brew package manager, the you can run:

```shell
brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep
```
