### ISSUE TITLE
Strimzi user operator as a subordinate CA

### ISSUE THREAD

**Issue by mrubanov** [strimzi/strimzi-kafka-operator#6520]
**Is your feature request related to a problem? Please describe.**
Hi Strimzi team,

Normally we use the cluster operator to manage/operate our Kafka cluster, however recently we have stumbled upon a use-case of externally managed Kafka. In this case we decided to use the topic and user operators in the standalone mode in order to be able to manage the users and topics in the "usual" way. However we have now a problem with k8s secrets that the user operator generates out of KafkaUser objects, in particular with certificates.

The externally managed Kafka cluster trusts some certificate, however I can't make the user operator use it to sign the certificates for the actual users, since the corresponding private key is not exposed due to security reasons. It is however possible to request a intermediary/subordinate certificate (with my generated private key), which then can be used to set up the user operator and sign the certificates for the actual KafkaUsers. So then whole scheme consists then out of 3 elements:

Root certificate (associated with the Kafka cluster) -> Subordinate certificate (used by user operator) -> End user certificates (generated by the user operator for the applications)

The problem now is that the secrets for the KafkaUsers (namely the 'user.crt' and 'user.p12' fields) contain only the last certificate, which breaks the chain of trust in our case, since the applications use the content of 'user.p12' keystore to authenticate against Kafka cluster and it can't verify them, as the subordinate certificate is missing. (although it is technically present in 'ca.crt', if I recall right)

**Describe the solution you'd like**
Considering this, I'd like to ask if it is possible to implement some kind of a parameter in the user operator (like IS_SUBORDINATE_CA), setting which to 'true' would add the user operator's certificate to 'user.crt' and 'user.p12' fields of the generated secrets. This would then fix the chain of trust, as both subordinate and end-user certificates are present in the application's keystore and the Kafka cluster should be able to verify them.

Regards,
Maksim

**Comment by scholzj** [comment]
The user secret contains the `ca.crt`, `user.crt` and the `user.key`. So I guess you can use that to have a full chain of the certificate in your application, or?

**Comment by mrubanov** [comment]
Hi Jakub,

Thanks for a quick answer. Yes, technically all the data is present, however this would require adaptation of all the applications that we have in-house. Besides, it is highly desirable that the applications are environment-oblivious, which is then also not the case, since they need to be configured differently depending on the kind of Kafka cluster.

**Comment by scholzj** [comment]
I'm not sure I follow the argument. Your applications will need to get the certificates from the user secret anyway. If you want it to be _environment-oblivious_, the best way how to do it to pass to it some basic pieces such as the 3 files I mentioned above. That is the universal way which works for all applications -> they can decide how to handle the certificates based on their needs.

**Comment by mrubanov** [comment]
Yes, the apps need the secrets anyway. My concern is essentially about your point: "they can decide how to handle the certificates based on their needs". This decision has to be then made based on the "kind" of the Kafka cluster: Strimzi-managed or 3rd-party-managed, which has to be configured before deployment, as the applications do not know who/what manages the Kafka cluster. Therefore I thought it might be worthwhile to have this "switch" in the user operator instead of all the Kafka consumers.

**Comment by scholzj** [comment]
Well, TBH, the switch does not make any sense to me. That just throws the maintenance effort to Strimzi instead of your own applications. Also, your applications do not need to know to which cluster they are connecting - the User secret looks the same all the time. So they can use the X509 files all the time.

The thing which for me is for discussion is whether the full CA should be included in the PKCS12 file out of the box (i.e. without any switch). But TBH I think this would need to be tested to double check what impact does this have if it changes.

**Comment by mrubanov** [comment]
Regarding the inclusion of the CA - I guess this is also an acceptable solution, however I am not so sure about the impact either, therefore my original suggestion was to have a switch.

**Comment by scholzj** [comment]
Triaged on 21st June: We should doublecheck if the User Operator works with the Intermediate CAs => the current expectation is that it should. If we confirm it, it is not really clear what more is needed.

**Comment by scholzj** [comment]
@mrubanov I was trying this today and I'm not really sure what is the problem:
* You pass the certificate chain as the Clients CA (in my case Root CA - Int CA - Clients CA)
* When you create the user, the user certificate is signed by the Clients CA. The certificate is provided in the user secret as `user.crt`. If needed, the CA which was used to sign-it (the public keys only of course) are in the user secret as `ca.crt`.

I used this tooling for testing it: https://github.com/scholzj/strimzi-custom-ca-test ... it all seems to work fine and without any issues. So I'm not sure I understand the issue. You might need to explain what are you doing differently or what you expect to be different.
