### ISSUE TITLE
Strimzi Operator metrics strimzi_reconciliations_failed_total does not show KafkaConnector failure counts

### ISSUE THREAD

**Issue by yingyingtang-brex** [strimzi/strimzi-kafka-operator#6557]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
We have been using Strimzi Operator metrics for monitoring. The metrics work great, except that the KafkaConnector failures are not tracked by `strimzi_reconciliations_failed_total`. 

This metrics works for KafkaConnect kind, as when KafkaConnect fails to reconcile, the metrics increment the count. However, whenever we have KafkaConnector failed to reconcile, we can find the logs e.g. "Error reconciling connector XXX", but the metrics does not indicate this error for the KafkaConnector.  

**To Reproduce**
1. Create a KafkaConnector with wrong database secrets
2. Wait and find the logs in Strimzi Operator: "Error reconciling connector"
3. Check the Strimzi metrics by going to :8080/metrics
4. Could not see strimzi_reconciliations_failed_total indicating KafkaConnector failure (waited for ~ 30 min and still no)

**Expected behavior**
Would expect to find metrics:
strimzi_reconciliations_failed_total{kind="KafkaConnector",namespace="cdc",selector="",} 1.0

**Environment (please complete the following information):**
 - Strimzi version:0.27
 - Installation method: YAML
 - Kubernetes cluster: Kubernetes
 - Infrastructure:Amazon EKS

**YAML files and logs**
```
2022-03-23 22:07:27 INFO  AbstractConnectOperator:395 - Reconciliation #6920(timer) KafkaConnect(cdc/cdc-kafka-connect): creating/updating connector: test-debezium-connector
2022-03-23 22:07:27 INFO  AbstractConnectOperator:395 - Reconciliation #6920(timer) KafkaConnect(cdc/cdc-kafka-connect): creating/updating connector: transmission-service-debezium-connector
2022-03-23 22:07:27 WARN  AbstractConnectOperator:668 - Reconciliation #6920(timer) KafkaConnect(cdc/cdc-kafka-connect): Error reconciling connector test-debezium-connector
io.strimzi.operator.cluster.operator.assembly.ConnectRestException: PUT /connectors/test-debezium-connector/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
Error while validating connector config: FATAL: password authentication failed for user "cdc_user"
```

**Additional context**

**Comment by scholzj** [comment]
Can you please provide the full log from the cluster operator and the custom resources you are using to see if it can be reproduced.

**Comment by scholzj** [comment]
FYI: I think I reproduced it, so you do not need to provide more details.
