### ISSUE TITLE
Remove methods with signature that does not specifies namespace.

### ISSUE THREAD

**Issue by see-quick** [strimzi/strimzi-kafka-operator#6597]
### Description 

Currently in our STs we have numerous methods with signature:

```java
(1) public static void method(final String namespaceName, final String clusterName...) {
	// code
}
```

```java
(2) public static void method(final String clusterName...) {
	// code
}
```

This could potentially insert an unintentional bug, which is at first glance hidden. In sequence mode, everything is working fine, but in class-wide parallelisation, the context of the Kubernetes client could be different from what we need. For instance, two parallel suites (i.e., @ParallelSuites) are executed in parallel, and one test case is correctly using the signature (1) method. And the second one is using the signature (2) method, which results in an error (if the namespaces of (1) and (2) differ). 

We should eliminate such signatures from our STs to reduce this error.

**Comment by jankalinic** [comment]
Should be finally resolved by https://github.com/strimzi/strimzi-kafka-operator/pull/7555
