### ISSUE TITLE
[system test] - we should call of KafkaConnect API from scraper Pod instead of KafkaClients Pod.

### ISSUE THREAD

**Issue by see-quick** [strimzi/strimzi-kafka-operator#6608]
### Description

We should call KafkaConnect API from scraper Pod because that's the only one Pod, which has permission to do so. In the past, we use to call KafkaConnect API from KafkaClients Pod but currently, this case will not work. We should scan the whole `systemtest` module if there is some occurrence of this problem.

**Comment by Frawless** [comment]
@see-quick guess we can close this as it was solved by https://github.com/strimzi/strimzi-kafka-operator/pull/6604 ?

**Comment by see-quick** [comment]
Well, I think yes. Closing )
