### ISSUE TITLE
Making Cruise Control related topic names configurable

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#6613]
Today, the topics used by Cruise Control as metric samples store and used by the reporter have hard-coded names.

https://github.com/strimzi/strimzi-kafka-operator/blob/main/docker-images/kafka-based/kafka/cruise-control-scripts/cruise_control_config_generator.sh#L25

It would be useful having the current values as default but allowing to configure them.

**Comment by katheris** [comment]
I can take a look at this

**Comment by katheris** [comment]
@ppatierno what are your thoughts on the behaviour if a user wants to change the topic name once cruise control has already been deployed? In my current version the old topics are left lying around. Should Strimzi clean up the old topics, or should the user not be able to change the topic names once cruise control is already deployed, or is it ok for users to manually delete the old topics?

**Comment by ppatierno** [comment]
Right now, when you deploy Kafka together with CC but then you remove CC, the related topics are still there (Strimzi doesn't any clean up). 

> or should the user not be able to change the topic names once cruise control is already deployed

I think we should allow the user to change the names for any reasons he could have.
My opinion is to leave the user the deletion (as actually is today). Maybe we should document it, to make him aware of this manual action to take.

**Comment by katheris** [comment]
Ok sounds good to me. I'll make sure the documentation calls out the need for manual deletion if you rename topics in an existing cruise control deployment

**Comment by scholzj** [comment]
What is the use-case for making them configurable?

**Comment by ppatierno** [comment]
In general, I think that a company/organisation would be interested to have some "internal" topics named in a specific way (i.e. using a "prefix" for example) to distinguish from other topics and maybe making even filtering on UI or things like that.

**Comment by katheris** [comment]
PR opened: https://github.com/strimzi/strimzi-kafka-operator/pull/6637
