### ISSUE TITLE
Multiple isolated kafka, sharing the same zookeeper?

### ISSUE THREAD

**Issue by fzyzcjy** [strimzi/strimzi-kafka-operator#6638]
Hi thanks for the wonderful framework! I have multiple kafka clusters isolated by namespaces. Currently each cluster has one zookeeper cluster. But I hope the two kafka clusters can share the *same* zookeeper cluster. Is this possible? How can I implement it? Thanks!

**Comment by scholzj** [comment]
This is not supported and I do not think we have any plans to add support for it (especially given the focus these days is rather on removing ZooKeeper completely).

**Comment by fzyzcjy** [comment]
Thanks for the reply! But seems that kafka without zookeeper is still not stable?

**Comment by scholzj** [comment]
It is not, but one day it will be ... hopefully :-o

**Comment by fzyzcjy** [comment]
Thanks for the reply

**Comment by scholzj** [comment]
Just to add more info for clarity ... adding support for something like this would be significant redesign and will add significant maintenance costs. So although it will still take a long time to have ZooKeeper-less Kafka production ready, it is not something what would be "worth" the investment and the complications.

**Comment by fzyzcjy** [comment]
I agree.

**Comment by fzyzcjy** [comment]
I agree.
