### ISSUE TITLE
Strimzi 0.5.0 Zookeeper bin shell scripts not working

### ISSUE THREAD

**Issue by franjo-piskur** [strimzi/strimzi-kafka-operator#673]
Hello,

when we want to execute script on zookeeper pods we get errors.

Example:
`bin/kafka-topics.sh --list --zookeeper localhost:2181`

> WARN Session 0x0 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
> java.io.IOException: Connection reset by peer
>         at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
>         at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
>         at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
>         at sun.nio.ch.IOUtil.read(IOUtil.java:192)
>         at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
>         at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
>         at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
>         at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
> WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
> java.net.ConnectException: Connection refused
>         at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
>         at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
>         at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
>         at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

How can we solve this, is it because of tls internal communication?

Best regards, 

Franjo

**Comment by ppatierno** [comment]
Starting from 0.5.0, the communication with Zookeeper is encrypted via TLS. The simple way for running a command like this is executing it directly on a Zookeeper pod in the following way:

`bin/kafka-topics.sh --list --zookeeper localhost:2181X`

where X is the index number of the Zookeeper pod you are using, so for example if using the pod `my-cluster-zookeeper-0` you have to run the above command on that pod with port 21810.

**Comment by stanlyDoge** [comment]
I have a theoretical question. What if we have 10+ zookeeper nodes? Should not be better to say it is `21810 + $number_of_node`?

**Comment by ppatierno** [comment]
@stanlyDoge yes the real formula is `2181 * 10 + $number_of_node` ... but I think that I'll have cluster with maximum 5/7 zookeeper nodes or at least I have never heard about more than that.

**Comment by stanlyDoge** [comment]
Thank you @ppatierno.
