### ISSUE TITLE
File connector will not be loaded anymore in Kafka 3.1.1 / 3.2.0

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#6731]
The file connector will not be loaded anymore in Kafka 3.2.0, see [KAFKA-13748](https://issues.apache.org/jira/browse/KAFKA-13748). We will need a fix to explicitly add it to `plugin.path` to avoid breaking some Connect system tests.

**Comment by scholzj** [comment]
There is no plan to do anything with the plugin path. The removal of the connector in examples is handled through Kafka Connect Build - see #6709

**Comment by scholzj** [comment]
Well, your issue title doesn't cover system tests either. The PR outlines the direction Strimzi is going to take on this. There will be no changing of plugin paths. You just add it as any other connector.

**Comment by fvaleri** [comment]
Agree, that's the right approach to fix STs.
