### ISSUE TITLE
Prevent Kafka broker scale down if it still contains replicas

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#6736]
When the number of Kafka replicas is decreased in the Kafka CR the StatefulSet will shutdown the highest numbered brokers.

Currently, there is no check to see if these brokers contain any topic-partition replicas. [The documentation](https://strimzi.io/docs/operators/latest/using.html#scaling-clusters-str) recommends that all topic-partition replicas are reassigned before doing this scaling action. We should introduce a check, such that the Operator will refuse to scale down if the brokers that are to be removed still contain replicas.

Displaying appropriate warnings in the logs will prompt users to do the reassignment and hopefully reduce the chance of data loss.

**Comment by scholzj** [comment]
The first part has been done in https://github.com/strimzi/strimzi-kafka-operator/pull/9042 => it blocks the scale-down of non-empty brokers by ailing the reconciliation. User is expected to revert the scale-down or clean the broker (or skip the check using annotation).

The issue https://github.com/strimzi/strimzi-kafka-operator/issues/9232 tracks further improvement to not fail the reconciliation but to revert the scale-down instead. This would allow us to proceed with reconciliation as if nothing happened and not fail it.
