### ISSUE TITLE
Add support for `In` Label selector to Fabric8 mock Kubernetes server

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#6740]
In PR #6669, the code fixing the counting of the Connect metrics uses a Label selector with the `In` requirement which is currently not supported in the in-parallel developed move to Fabric8 Kubernetes Mock server (PR #6727). #6727 for the time being disables the related tests. But this feature should be added to the Fabric8 Kubernetes Mock and the tests should be re-enabled. The disabled tests are marked with this issue.

**Comment by ortex** [comment]
kubernetes-server-mock doesn't support label selector with `In` requirement. Related issue: https://github.com/fabric8io/kubernetes-client/issues/4113
