### ISSUE TITLE
[Question/Bug/Enhancement] Deletion of Cluster-resources exede lifetime of Kafka-CR

### ISSUE THREAD

**Issue by telperinion** [strimzi/strimzi-kafka-operator#6775]
We face the issue, that the Operator Leaves the Kafka Resources lying around long (10-30 Minitues) after the Kafka CR got deleted. 

This leads to problems if you want to restart the cluster under the same name, expecting to get an fresh cluster, cause there was not a Kafka-CR present at the namespace.

First of all i'm not quiet sure what takes Strimzi (0.28) so long to delete the resources (in 0.24 we didn't had this issues), secondly is there a way to get finalizers on the CR so the Kafka-CR would only be deleted if every associated resource is deleted when the CR is removed?

**Comment by scholzj** [comment]
Complete log might be more clear. But the resources are really deleted by Kubernetes Garbage Collection. not by the Cluster operator. So it looks like it was not deleting the CR immediatelly. This could be for example because of some finalizer set on the Kafka CR by you or some other tooling. but I guess it could be also some glitch in your Kubernetes cluster etc.

**Comment by telperinion** [comment]
I have one extra question on this issue:

Has there been a change in resource deletetion on strimzi-operator side between the versions 0.23 to 0.28, cause we see this issue only after the update

**Comment by scholzj** [comment]
No, I don't think there were any changes around this. Did you checked if something doesn't set some finalizers on the resources?

**Comment by telperinion** [comment]
No there aren't, as we are able to delete the resources by hand (just a kubectl delete deployment/statefulset/etc kafka-...) and directly get a result it must be some issue with the GC of the Cluster.

Its furstrating cause we can't see any issue there, it just dont starts for serveral minutes/days. :(

**Comment by scholzj** [comment]
> No there aren't, as we are able to delete the resources by hand (just a kubectl delete deployment/statefulset/etc kafka-...) and directly get a result it must be some issue with the GC of the Cluster.

eah, but the GC will delete them only after the Kafka CR is deleted. So does that have any finalizers?

**Comment by telperinion** [comment]
The Kafka-CR is long gone. 

You can apply finalizers with kubectl  --cascade=foreground which is working on other clusters (for example a local k3d with strimzi 0.28 installed). If you use this with our central cluster it don't get deleted at all.

**Comment by scholzj** [comment]
That is weird.

**Comment by scholzj** [comment]
Triaged on 25.8.2022: The resource deletion is done by Kubernetes Garbage Collection. So this does not seem to be a Strimzi issue but rather a Kubernetes issue. Normally, for me (Jakub Sch.) the GC works fine on my clusters. This should be closed.
