### ISSUE TITLE
Testing `KafkaRebalance` wrong annotation runs the entire rebalacing state machine

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#6799]
The `KafkaRebalanceAssemblyOperatorTest` class has different tests related to put a wrong annotation in specific states:

* `testNewToProposalReadyToProposalReadyWithWrongAnnotation`
* `testNewToProposalReadyToRebalancingToReadyRebalancewithWithWrongAnnotation`
* `testNewToPendingProposalToStoppedStatewithWrongAnnotation`

The problem with these tests is that each of them run the entire state machine (doing multiple reconcile) to reach a specific state and then applying the wrong annotation. This sounds to be useless to me.
We should build the `KafkaRebalance` instance by setting the `status` (so the rebalancing state machine state) in which we want to test wrong annotation directly. After that, just a single reconcile will be needed to do the test.

**Comment by ShubhamRwt** [comment]
Done in PR #6817
