### ISSUE TITLE
[Docker images] add OCI label org.opencontainers.image.source

### ISSUE THREAD

**Issue by OuesFa** [strimzi/strimzi-kafka-operator#6828]
**Is your feature request related to a problem? Please describe.**
I'm using [Renovate](https://github.com/renovatebot/renovate) to update dependencies. Renovate [supports docker label `org.opencontainers.image.source`](https://github.com/renovatebot/renovate/pull/2907) to point to source and add the release notes in the created PR. It doesn't find the source url in the Strimzi images.

**Describe the solution you'd like**
 I would like to leverage that for all strimzi images. 
 Is it possible to add the following OCI label `org.opencontainers.image.source` in the docker image to indicate the source repo URL. 

**Describe alternatives you've considered**
[Hardcode the sourceUrl in Renovate](https://github.com/renovatebot/renovate/discussions/15300#discussioncomment-2629772)

**Comment by scholzj** [comment]
TBH, I did not really understand the use-case (no idea what Renovate is). But I think this makes sense regardless. I thought we already had an issue for it, but it doesn't seem like it.  I guess we should also add `org.opencontainers.image.description` and `org.opencontainers.image.licenses`.

**Comment by OuesFa** [comment]
Thanks! 
Yes I should've given more details about the use case, we use Renovate to get automated Pull Requests to update our dependencies. 
In this case, it allows to fetch new versions of docker strimzi images in quay.io and update our dockerfiles automatically. 
For now, the PR does not contain the release notes because Renovate can't know in which Github repo to look for the release.

**Comment by scholzj** [comment]
Triaged on 7.6.2022: This would be useful. The labels mentioned in this issue would be a good start.
