### ISSUE TITLE
System Test failure on k8 cluster for bindingnamespaces

### ISSUE THREAD

**Issue by mcullenEST** [strimzi/strimzi-kafka-operator#6838]
**Describe the bug**
When running `HttpBridgeTlsST` system test on our k8 cluster using images from a private registry, it would not add our image pull secret into the `http-bridge-tls-namespace` namespace. The credential was passed through the env variable `SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET` and was visable in the `infra-namespace` also.

**To Reproduce**
1. Run the `HttpBridgeTlsST` system test on k8 cluster using a private registry

**Expected behavior**
For the system test to pass on a k8 cluster & the credential to be visable in the `http-bridge-tls-namespace` namespace

**Environment (please complete the following information):**
 - Strimzi version: 0.27.1
 - Installation method: YAML files - through the system test
 - Kubernetes cluster: Kubernetes

**Additional context**
To resolve this issue (and for multiple other tests that do not use the `namespace-XX` namespace). We had to manually add it through kubectl or even better, we added the following line to add the credential to the binding namespaces of the cluster:

```bindingsNamespaces.stream().forEach((c) -> StUtils.copyImagePullSecret(c));``` 
(all tests that used the binding namespaces also failed for us, so all them were assigned the credential)

just above:
https://github.com/strimzi/strimzi-kafka-operator/blob/f7162b01ac2b99c8fba544e3c1df74b2f405c7d7/systemtest/src/main/java/io/strimzi/systemtest/resources/operator/SetupClusterOperator.java#L228

**Comment by scholzj** [comment]
@Frawless @im-konge Can you have a look please?

**Comment by im-konge** [comment]
Hey @mcullenEST ,
this issue is already resolved in #6468 and especially on these lines [R137-R139| https://github.com/strimzi/strimzi-kafka-operator/pull/6468/files#diff-885fe3fd1158ac2dc6f2d1f828f5a2eb4d8d70380e4a2cce244e3e75950c7553R137-R139].
When you'll execute the tests from the main branch (or `release-0.29.x`), it should work without a problem.

**Comment by mcullenEST** [comment]
Perfect, Thanks for your responce!
