### ISSUE TITLE
Host a Helm Repository to manage Strimzi chart releases

### ISSUE THREAD

**Issue by seglo** [strimzi/strimzi-kafka-operator#686]
Create a helm repo on the strimzi website.  You can generate a Helm Repository with the helm CLI tool and host it using github pages.  This will let you release the chart in a more formal way.  The way the chart is bundled now, users will have to download the release artifact to install it, or install it as a standalone artifact via a URL.
  
```
helm install https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.6.0/strimzi-kafka-operator-0.6.0.tgz
```
  
If we create the repo then the user could add it and install the latest version via repo/package coordinates.
  
```
helm repo add strimzi http://strimzi.io/helm/
helm install strimzi/strimzi-kafka-operator
```

**Comment by scholzj** [comment]
@seglo How do we get the repo there? Do we just copy the `helm-charts/strimzi-kafka-operator` directory to `http://strimzi.io/helm/`? How would we handle master versus different releases?

**Comment by seglo** [comment]
@scholzj Good questions.  The way I think it works is that each release we would copy the chart release tarball generated by the `make release` process (i.e. `strimzi-kafka-operator-0.6.0.tgz`) into a directory on the website.  It would be cumulative.  Each release you generate a new `index.yaml` that encodes metadata about the charts and its versions into a file to be read by the helm CLI tool.  I haven't done this before, so maybe there's a better way that doesn't involve having duplicate release artifacts around, or maybe we don't put the chart tarball on the GH release site like I originally suggested.

I'll think about this some more and follow up.

[There are more details here about creating repositories here](https://github.com/helm/helm/blob/master/docs/chart_repository.md)

**Comment by seglo** [comment]
I'm working on this.
