### ISSUE TITLE
Create a Helm Chart for standalone deployment of the Topic and User operators

### ISSUE THREAD

**Issue by seglo** [strimzi/strimzi-kafka-operator#687]
Create a standalone `strimzi-topic-operator` chart.  This allows users to install the topic operator standalone without having to use the examples resource files directly.  It will also bring consistency with how the resource files are templated and managed as part of the release workflow.

**Comment by seglo** [comment]
@ppatierno You can assign this one to me if you like.

**Comment by seglo** [comment]
I was discussing with @scholzj in Slack if this effort was worth it.  I don't have a need for these standalone charts and the only reason I suggested it was if you had many users that preferred this standalone operator model.  

If the rest of you agree that it's not a priority (@tombentley , @ppatierno , or anyone else with an opinion), then I suggest we close this issue.

**Comment by tombentley** [comment]
I've unassigned you @seglo. I agree it's not a priority. I don't think we should close the issue though. Afterall, if someone did a PR we would most likely merge it.

**Comment by dkirrane** [comment]
Yes would like to see Topic Operator as a separate Helm Chart. Add to `requirements.yaml` of overall Chart.
Same for User Operator if possible?

**Comment by scholzj** [comment]
Triaged on 22.02.2022: The standalone UO and TO are really a sideproduct of Strimzi. We do not have the bandwith to develop and maintain the helm charts. If anyone wants to contribute this, we are open to discussion.
