### ISSUE TITLE
Submit Helm Charts to kubeapps incubator repository

### ISSUE THREAD

**Issue by seglo** [strimzi/strimzi-kafka-operator#688]
Submit the Helm Charts to the central kubeapps `incubator` repository.

The current implementation simply bundles the chart into the release process by calling `helm package` to create a tarball that's available as its own artifact as part of a release.  The chart is also available in its unarchived form in the `./charts/` dir of the release artifact.  We could also publish this to the central kubeapps chart repository.  

I've already started implementing the requirements listed in the [Review Guidelines](https://github.com/kubernetes/charts/blob/master/REVIEW_GUIDELINES.md) and [Contribution Guidelines](https://github.com/kubernetes/charts/blob/master/CONTRIBUTING.md) in the initial Helm Chart PR.  

Once the chart is accepted to the repo after an initial review, it will be possible to automate the creation of an update PR during the Strimzi release and then a committer can either manually or automatically approve it into the incubator repo.

**Comment by ppatierno** [comment]
@seglo As far as I understood you are already working on it right? Can I assign this issue to you?

**Comment by seglo** [comment]
@ppatierno I haven't started on this yet.  @tombentley mentioned in another thread he was looking into the review guidelines.  I was thinking about getting #687 done first and then someone could submit both at the same time.

It may also make sense to wait until the next release in case any issues arise with the chart.  My original thinking was that the chart could be submitted to kubeapps per Strimzi release, but we don't have to wait.

**Comment by scholzj** [comment]
Triaged on 22.02.2022: The kubernetes/charts is now deprecated in favour of ArtifactHub where Strimzi is listed.
