### ISSUE TITLE
TopicOperator allows user to set forbidden settings

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#6884]
**Describe the bug**

During our testing, we found strange behavior of TopicOperator, when we want to set "forbidden settings" - like decreasing number of partitions or setting `min.insync.replicas` to an invalid value (such as `asd`).

**To Reproduce**
1. deploy CO
2. deploy Kafka
3. create KafkaTopic - f.e. with 3 replicas and 3 partitions
4. either try to decrease the number of partitions/replicas or add to `.spec.config` some invalid key + value

**Expected behavior**
KafkaTopic will be in `NotReady` state and some error or something will be printed into the TO log

**Environment (please complete the following information):**
 - Strimzi version: main
 - Installation method: YAML files
 - Kubernetes cluster: K8s 1.16.0, Openshift 4.10, K8s 1.24.x
 - Infrastructure: Minikube, AWS

**YAML files and logs**

[to-log.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8814501/to-log.txt)

**Comment by im-konge** [comment]
Also, some of STs are being disabled in #6889 - after fixing this issue, they should be enabled again.

**Comment by LiamClarkeNZ** [comment]
Hi @im-konge, 

I'm not able to reproduce this manually. Do you have an example YAML config that would allow me to do so? 

My versions I'm using for this are:

* Kubernetes Version: v1.24.0-alpha.3.3621+bb9c2f1329958f-dirty
* Cluster operator 0.29.0

I've used both `kubectl patch` and `kubectl apply` to make the changes:
```
 oc -n kafka patch kafkatopics/test-topic --type=merge -p '{"spec": {"partitions": 5, "replicas": 1}}'
```

and am seeing the behaviour you expect:

```
> oc -n kafka describe kafkatopics/test-topic
...
Status:
  Conditions:
    Last Transition Time:  2022-06-07T02:49:50.273382Z
    Message:               Number of partitions cannot be decreased
    Reason:                PartitionDecreaseException
    Status:                True
    Type:                  NotReady
  Observed Generation:     4
  Topic Name:              test-topic
Events:
  Type     Reason  Age        From                                     Message
  ----     ------  ----       ----                                     -------
  Warning          <unknown>  io.strimzi.operator.topic.TopicOperator  Failure processing KafkaTopic watch event MODIFIED on resource test-topic with labels {strimzi.io/cluster=metrics-strimzi-cluster}: Number of partitions cannot be decreased
  Info             <unknown>  io.strimzi.operator.topic.TopicOperator  Number of partitions cannot be decreased
  Info             <unknown>  io.strimzi.operator.topic.TopicOperator  Number of partitions cannot be decreased
  Warning          <unknown>  io.strimzi.operator.topic.TopicOperator  Failure processing KafkaTopic watch event MODIFIED on resource test-topic with labels {strimzi.io/cluster=metrics-strimzi-cluster}: Number of partitions cannot be decreased
  Info             <unknown>  io.strimzi.operator.topic.TopicOperator  Number of partitions cannot be decreased
```

Thanks :)

**Comment by im-konge** [comment]
Hey @LiamClarkeNZ, as I mentioned in the bug description, it fails only on `main` branch -> it was functional on `0.29.0`.

I applied the `kafka-topic.yaml` from `packaging/examples/topic`, there I just changed the replicas and partitions to 3/3
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```

Topic then went to `Ready` state. After that I edited the `KafkaTopic` CR with forbidden option -> f.e. decrease the partitions. The KT was still in `Ready` state.

Can you please try this on the `main` branch?

**Comment by LiamClarkeNZ** [comment]
Ah sorry @im-konge I missed that, will do :)

**Comment by im-konge** [comment]
No problem :) thanks a lot

**Comment by scholzj** [comment]
Triaged on 18.8.2022: @scholzj tried this before the triage call and was not able to reproduce it by decreasing the partition count or setting some invalid values for some config options. @im-konge Can you still reproduce it? If not, can you please re-enable the system tests you mentioned as disabled?

**Comment by im-konge** [comment]
@scholzj will do

**Comment by im-konge** [comment]
@scholzj 
I tested this bug and it seems that it's mostly fixed.
I ran all the disabled test and there is just one failing -> `testCreateTopicAfterUnsupportedOperation`.
The TO will not decrease partitions and replicas, but it's still in `Ready` state and without any message logged (we are waiting for `NotReady` state and some message.

**Comment by scholzj** [comment]
You should then provide a clear scenatio for reproducing it I guess.

**Comment by im-konge** [comment]
I reproduced it this way:

1. Deploy Kafka with 3 Kafka replicas and 1 ZK replicas
2. Deploy KafkaTopic with replicas & partitions set to 3
3. After the KafkaTopic is `Ready`, set replicas & partitions to 1

This will not do anything, but there is no error message or exception anywhere (either in the KafkaTopic or TopicOperator)

**Comment by scholzj** [comment]
Still seems to work for me:
```yaml
  - lastTransitionTime: "2022-08-20T23:31:38.077726Z"
    message: Number of partitions cannot be decreased
    reason: PartitionDecreaseException
    status: "True"
    type: NotReady
```

MAybe it does nto happen everytime.

**Comment by im-konge** [comment]
Let me try it once more, if it fails again, I will share with you the logs.

**Comment by im-konge** [comment]
So, the steps are same as I mentioned above:
```
    1. Deploy Kafka with 3 Kafka replicas and 1 ZK replicas
    2. Deploy KafkaTopic with replicas & partitions set to 3
    3. After the KafkaTopic is Ready, set replicas & partitio

ns to 1
```
but now, TO allowed to change the replicas and partitions to 1. As an attachment I'm adding logs from Kafka pods, TO, CO and yamls of Kafka and KafkaTopic

[Archive.zip](https://github.com/strimzi/strimzi-kafka-operator/files/9402502/Archive.zip)

**Comment by scholzj** [comment]
The Bidirectional Topic Operator (BTO) has been replaced by the new Unidirectional Topic Operator from Strimzi 0.39. There are no plans to fix any outstanding issues in the old BTO and this issue can be closed.
