### ISSUE TITLE
Misleading imagePullSecrets value usage in operator helm chart

### ISSUE THREAD

**Issue by martonorova** [strimzi/strimzi-kafka-operator#6886]
**Describe the bug**
The strimzi-kafka-operator helm chart provides the `image.imagePullSecrets` value to set image pull secret used by the Operator Deployment config. However, it only accepts a single value which prevents using multiple image pull secrets and goes against common practices established in other popular helm charts.

**To Reproduce**
In the Deployment template of the operator [060-Deployment-strimzi-cluster-operator.yaml](https://github.com/strimzi/strimzi-kafka-operator/blob/main/helm-charts/helm3/strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml#L33), it only allows a single imagePullSecret:

```yaml
...
{{- if .Values.image.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.image.imagePullSecrets }}
{{- end }}
...
```

**Expected behavior**
In my opinion, the above mentioned part should look something like this:
```yaml
...
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}
...
```

With this, multiple `imagePullSecrets` could be provided in the `values.yaml` like the following:

```yaml
...
imagePullSecrets:
  - name: pullsecret-one
  - name: pullsecret-two
  - name: pullsecret-two
...
```

**Comment by scholzj** [comment]
So, what does your suggestion mean for b ackwards compatibility? Is it backwards compatible (in which case this seems like an easy change you can open a PR for)? Or is it not backwards compatible?

**Comment by scholzj** [comment]
Triaged on 18.8.2022: The general issue sound reasonable. The naming and the use of the variable are unfortunate. So if someone knows how to fix this in a backwards-compatible fashion, we would definitely welcome a PR.

**Comment by v-patel** [comment]
@scholzj I believe this can be closed.

**Comment by scholzj** [comment]
@v-patel Good catch. Thanks.
