### ISSUE TITLE
Multi datacenter support with MirrorMaker operator

### ISSUE THREAD

**Issue by seglo** [strimzi/strimzi-kafka-operator#689]
Provide an easy way to let users create Active/Active or Active/Passive synchronizations between Kafka clusters.  Apache Kafka bundles Mirror Maker which can be managed in a similar way as how topics are managed by the topic operator.  

To fully realize this feature some pre-requisites include

* External access to brokers outside K8s cluster.  Broker ingress.
* TLS and auth support for Mirror Maker client connections across untrusted networks.

A first iteration of this feature could begin in the meantime for multiple Kafka clusters running in the same Kubernetes cluster.  I would like to volunteer to work on this over August.

**Comment by ppatierno** [comment]
@seglo if you confirm that you would like to volunteer, I can assign this issue to you :-)

**Comment by seglo** [comment]
@ppatierno yes I can begin working on this after some other tasks I have on my plate.  I expect to have something to show in August.  If that changes I'll let you know.

**Comment by seglo** [comment]
Thanks! :)

**Comment by ppatierno** [comment]
Thanks to you! ;)

**Comment by seglo** [comment]
I was scanning PR's and noticed this work already got picked up, great! Feel free to re-assign this task to @stanlyDoge #862

**Comment by ppatierno** [comment]
@seglo yeah sorry for that, me and @stanlyDoge are already working on that.

**Comment by seglo** [comment]
Totally fine! 😁
