### ISSUE TITLE
Ability to define a nodePort port when using loadbalancer listener type

### ISSUE THREAD

**Issue by pupseba** [strimzi/strimzi-kafka-operator#6894]
Hi,

kafka.spec.kafka.listeners.configuration.bootstrap.nodePort is limited by design to be used only when the type of the listener is "nodeport". "Loadbalancer" kubernetes services also define a nodeport and it could be necessary to have the ability to be able to fix a specific port number in those cases too.

Would it be possible for having this parameter to be compatible with "nodeport" AND "loadbalancer" type of listeners?

**Comment by pupseba** [comment]
Closed as per the clarifications done in this slack thread: https://cloud-native.slack.com/archives/CMH3Q3SNP/p1654249105547249

Which explains how using such configuration would be "mixing services" and hence, not currently supported.

**Comment by scholzj** [comment]
I looked into this a bit more. If you or anyone else sees any value of configuring the exact node port for the load balancer services, tat would be easy to add. I'm personally not sure I see when it is useful. But if anyone does, let me know.

As for the other part -> in the past we considered allowing different type for bootstrap and broker services. The most common use-case was loadbalancer or Ingress for bootstrap and node ports for brokers. But at the end we decided not to do it. It would be a bit more complicated (also from the API perspective) and it is usually fairly easy to workaround by just creating the load balancer or ingress manually on top of `type: nodeport` listener.

**Comment by pupseba** [comment]
In our case, controlling which port is used in the loadbalancer service would be of much help. We use on-prem kubernetes and enable loadbalancer services via MetalLB. Having the capacity to control which nodePort is used for the LoadBalancer will help in 2 things:
- Ease of transition from current nodeport to loadbalancer while keeping the same NodePort port, without the need to define an extra listener for the specific purpose of the so called transition.
- More control over which port we allow in firewalls.
At the end, we will not use the NodePort port, in favour of using the port of the LoadBalancer service, noneyheless and as per the previous reasons, I can only see a nice value by having this possibility.

Thank you for your time with this!!!

**Comment by scholzj** [comment]
Ok, good. Thanks for the explanation. @ShubhamRwt is looking into it.
