### ISSUE TITLE
Tool for unbalancing partitions in a Strimzi managed Kafka cluster

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#6909]
**Is your feature request related to a problem? Please describe.**
For developing and testing cluster balancing features, it would be really nice to have some sort of tool for unbalancing partitions in a Kafka cluster that is managed by Strimzi. 

**Describe the solution you'd like**
Ideally some sort of cli tool or script that could load a Kafka cluster managed by Strimzi in an unbalanced manner. Maybe even accept arguments that could specify things like:

- How much data to send
- How fast to send the data
- How that data is distributed

**Comment by ppatierno** [comment]
@katheris did you use any third party or hand made tool for doing your tests around this?

**Comment by kyguy** [comment]
I forgot that @tomncooper created a tool for this [1], I am hoping we could copy this or develop something similar into the Strimzi repo. I think a simple Kafka client like this would be really useful!

[1] https://github.com/tomncooper/kafka-topic-loader

**Comment by tomncooper** [comment]
Yeah, that would do the job. I also remember @see-quick looking at porting this to java for the System Tests?

**Comment by scholzj** [comment]
Discussed on the community call on 18.4.: Nobody seems to have time for it and we survived without this tool for almost 2 years (since opening this issue). So this can be probably closed.
