### ISSUE TITLE
describing a failed KafkaConnector exposes password from env in clear text

### ISSUE THREAD

**Issue by omriarieli** [strimzi/strimzi-kafka-operator#6911]
**Describe the bug**
when using env config provider on kafka connect to get a db password for a KafkaConnector (MongoSourceConnector) i made some syntax mistakes, when trying to figure out why the connector isnt working i used kubectl describe kafkaconnector and noticed the db password is exposed in clear text in the Status.Conditions.Message.

**To Reproduce**
1. Create a kafka connect cluster with externalConfiguration.env with a config.providers: env
2. Create a KafkaConnector resources with a malformed connection.uri (in my case i had the port specified)
`connection.uri: mongodb+srv://kafka:${env:DB_PASS}@my-mongo.example.com`
3. Apply the manifest
4. Run command `kubectl -n kafka describe kafkaconnector mongodb-source-connector`
5. See Messsage with password in clear text
'Message:               PUT /connectors/mongodb-source-connector/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
Invalid value mongodb+srv://kafka:**<MY_CLEAR_PASSWORD>**@my-mongo.example.com:27017 for configuration connection.uri: Host for when using mongodb+srv protocol can not contain a port
You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`'

**Expected behavior**
the password will be omitted/consealed 

**Environment (please complete the following information):**
 - Strimzi version: 0.29.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.21
 - Infrastructure: GKE

**Comment by scholzj** [comment]
Can you please provide a sample custom resources and a full operator log?

**Comment by scholzj** [comment]
TBH, I suspect that this is the exception thrown by Kafka Connect / the connector you are using. So I don't think there is much we can do about this. This will need to be identified and raised either against Kafka or against the Connector authors depending on where it comes from. We have no chance to filter passwords in random exceptions provided by Connect.

**Comment by scholzj** [comment]
Triaged on 18.8.2022: Strimzi does not expand the configuration providers. So I do not think it was Strimzi who printed the password in some error message. And without the logs it is hard to say if this is related to the Connect cluster or to the Connector. This should be closed.
