### ISSUE TITLE
okhttp 4.9.0 critical vulnerability

### ISSUE THREAD

**Issue by cameronwaterman** [strimzi/strimzi-kafka-operator#6934]
**Describe the bug**
The latest docker image contains `okhttp` version 4.9.0 which contains a known critical [security vulnerability](https://github.com/square/okhttp/issues/6738).

**To Reproduce**
See link above.

**Expected behavior**
`okhttp` upgrade to >=4.9.2

**Environment (please complete the following information):**
 - Strimzi version: 0.27.1 (checked with 0.29.0 as well)
 - Installation method: Helm chart
 - Kubernetes cluster: Various
 - Infrastructure: Various

**YAML files and logs**
N/A

**Additional context**
None

**Comment by scholzj** [comment]
OkHttp is part of the Jaeger-client. Feel free to open a PR to update it to a new version if one exists. Thanks.

**Comment by cameronwaterman** [comment]
@scholzj - jaeger-client has been [updated](https://github.com/jaegertracing/jaeger-client-java/issues/832) with a fix for the vulnerability. Could we get a new image of the operator? Thanks.

**Comment by scholzj** [comment]
Thanks for the update. This is not question of just building a new base image or something. This needs to be updated in the code and go through the full release process. I will have a look at it when I find some time.

**Comment by cameronwaterman** [comment]
@scholzj - Thanks for getting that updated. Do you have an ETA on when a new release might be generated - or is this a process I could get the ball rolling on?

**Comment by scholzj** [comment]
I proposed a new release. If everyone is fine with it, it might be maybe some time next week or soemthing.
