### ISSUE TITLE
Update Documentation To Reflect Lack Of Support For TLS With Encrypted Private Keys

### ISSUE THREAD

**Issue by mr1716** [strimzi/strimzi-kafka-operator#6940]
**Suggestion / Problem**
I tried to use TLS using an encrypted private keys using the documentation below. It turns out the issue that I had was because I was using an encrypted private key. If the documentation below was updated to reflect this information, I would have known this. It is not reflected anywhere in documentation and it seems like the right place to do so

**Documentation Link**
https://strimzi.io/docs/operators/latest/full/configuring.html

**Comment by mr1716** [comment]
It probably makes sense to put it in section 9.7 "[9.7. Kafka listener certificates](https://strimzi.io/docs/operators/latest/full/configuring.html#kafka-listener-certificates-str)" to say, "Strimzi does not support the use of encrypted private keys for TLS use."

**Comment by scholzj** [comment]
Triaged on 18.8.2022: Since we do not have any password fields, it seems quite obvious that encrypted keys are nto supported. But we can enhance the documentation to make it more clear there.

**Comment by michealireland** [comment]
Hi, I'd like to take this one please.
