### ISSUE TITLE
Add Support For Encrypted Private Keys

### ISSUE THREAD

**Issue by mr1716** [strimzi/strimzi-kafka-operator#6941]
**Is your feature request related to a problem? Please describe.**
The tool should support the creation of TLS using encrypted private keys for Kafka listeners.

**Describe the solution you'd like**
Support the use for Kafka listeners to use TLS using an encrypted private key.

**Describe alternatives you've considered**
Yes, the alternative is to use a different tool or to add it myself. But by the time that I were to build the issue, I could implement another tool. This seems like it could be a great way for greater use of the Strimzi tool

**Comment by scholzj** [comment]
Please explain what will be the use-case and the value of this!

**Comment by mr1716** [comment]
@scholzj the use case is that in the event that I am using Strimzi and Kafka for a large deployment and I have been given an encrypted private key. The goal is to manage Kafka with the listeners with the externally signed CA and encrypted key. But if this isnt a possibility, I will just use another tool. I would love to help improve Strimzi, which is why I am submitting this ticket, rather than just not using Strimzi.

**Comment by mr1716** [comment]
It probably makes sense to put it in section 9.7 "[9.7. Kafka listener certificates](https://strimzi.io/docs/operators/latest/full/configuring.html#kafka-listener-certificates-str)" to say, "Strimzi does not support the use of encrypted private keys for TLS use."

**Comment by scholzj** [comment]
You can just decrypt the key and then create the secret with the decrypted key. You do not need any special tool for it.

**Comment by mr1716** [comment]
@scholzj True, that is 1 option. But another option that would be a longer term option is to add the support for this to provide complete coverage and cover the use cases so people would want to use, support, and contribute to the tool.

**Comment by scholzj** [comment]
Every feature requires some effort to develop and also some on-going effort to maintain it - test it, update it, keep it working etc. So it is not always just about adding a new feature because someone asked about it. It has to make some sense and add some additional value which justifies the effort.

**Comment by scholzj** [comment]
Triaged on 18.8.2022: Having the encrypted key with the password stored next to it would not help security. And the ask for this support seems to be very rare compared to the expected effort. This issue should be closed. In the future, for improving security, the issues for better integration with certificate providers such as Vault might provide more secure way forstoring the keys.
