### ISSUE TITLE
Include --registry-certificate as an allowed option in additionalKanikoOptions

### ISSUE THREAD

**Issue by stevetu21** [strimzi/strimzi-kafka-operator#6973]
**Is your feature request related to a problem? Please describe.**
We run [Harbor](https://goharbor.io/) for our internal container registry, and it's secured using an internal-only self-signed Root CA. In general that means for most of our tools, we are often providing our CA Bundle so that we don't get TLS errors.

**Describe the solution you'd like**
Include [--registry-certificate](https://github.com/GoogleContainerTools/kaniko#--registry-certificate) as an allowed option in [additionalKanikoOptions](https://strimzi.io/docs/operators/latest/full/configuring.html#type-DockerOutput-reference). I totally get that implementation of this would be nontrivial, since it's not just another behavioral option but rather involves passing a file. But it'd still be super useful!

**Describe alternatives you've considered**
Currently, we're using `'additionalKanikoOptions': ['--skip-tls-verify',   '--skip-tls-verify-pull']` as a stopgap. After all, Strimzi is still super-valuable to us!

**Comment by stevetu21** [comment]
You said it even better than I did! I completely agree, that's a better approach. Then I'd imagine that under the hood, `--registry-certificate /path/to/my-cluster-cluster-ca-cert/ca.crt` is being passed to kaniko.

**Comment by scholzj** [comment]
Triaged on 18.8.2022: The feature request makes sense. Bt we would need to clarify the APi changes needed for this since we will need to mount the certificates from some secrets and auto-configure Kaniko. So it is not completely trivial to implement and this should need a proposal to cover the changes to the API etc.

**Comment by scholzj** [comment]
`--registry-certificate` option is not enabled (from Strimzi 0.45). The certificates can be mounted using the additional volumes feature (in the `template` sections).
