### ISSUE TITLE
System tests failure due to helm chart with private images

### ISSUE THREAD

**Issue by mcullenEST** [strimzi/strimzi-kafka-operator#7010]
**Describe the bug**
Docker secret not being applied into namespace when System tests are run via helm chart with private images.

**To Reproduce**
1. Insert docker secret into the default namespace
2. run a system test that deploys the operator in a namespace (e.g infra-namespace) using a helm chart
3. operator cannot pull the image from the private registry as the secret is not injected to the namespace.

**Expected behavior**
Test to run sucessfully

**Environment (please complete the following information):**
 - Strimzi version: 0.29.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes & Minikube
 - Infrastructure: Minikube

**Additional context**
Command we run to test is:

`CLUSTER_OPERATOR_INSTALL_TYPE=HELM SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET=<<SECRET>> mvn -f pom.xml -Pall -B -V -Dit.test=KafkaST#testForTopicOperator -Djunit.jupiter.execution.parallel.enabled=false -Djunit.jupiter.execution.parallel.config.fixed.parallelism=1 verify`

To resolve this we had to add:
`StUtils.copyImagePullSecret(namespaceInstallTo);` after this line: 
[https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/src/main/java/io/strimzi/systemtest/resources/operator/SetupClusterOperator.java#L209](https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/src/main/java/io/strimzi/systemtest/resources/operator/SetupClusterOperator.java#L209)

**Comment by scholzj** [comment]
CC @im-konge @Frawless

**Comment by im-konge** [comment]
@mcullenEST sorry for the delay, I've just created PR to fix this.
