### ISSUE TITLE
Add support for OpenTelemetry

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#7021]
The OpenTracing project was archived by CNCF and the new tracing project in the landscape is now [OpenTelemetry](https://opentelemetry.io/).
We should add the support for OpenTelemetry on Kafka Connect, Mirror Maker 1 and 2 while maintaining the support for OpenTracing for backward compatibility but then removing it finally in one of the coming releases.

**Comment by rohithsai1904** [comment]
@ppatierno I would like to work on it. Please assign me

**Comment by ppatierno** [comment]
@rohithsai1904 hi! I have planned to work on it soon. It could be not so trivial. Did you have any other experience with the Strimzi codebase and OpenTelemetry for asking about this specific issue? Otherwise, if this is your first engagement with the community, you could find some issues with `good-start` label to start with. Just trying to figure out your background and how we can make together your contribution to Strimzi more effectively.

**Comment by rohithsai1904** [comment]
@ppatierno This is my first time here. Not much experienced. Kind of in the learning stage. But I have the juice to contribute :)

**Comment by ppatierno** [comment]
@rohithsai1904 and it is awesome!! New contributors are welcome! At this point, would you mind to take a look at `good-start` labeled issues through this filter?

https://github.com/strimzi/strimzi-kafka-operator/issues?q=is%3Aopen+is%3Aissue+label%3Agood-start

We have issues triage periodically and mark some issues as good start for people like you who want to engage with the community for the first time and learning the project codebase. I would pick one issue from that list to make the approach easier and leave this specific issue to me.
