### ISSUE TITLE
the current mechanism for downloading "latest" injects 5 namespaces into the yaml of the version available on downloads

### ISSUE THREAD

**Issue by davesargrad** [strimzi/strimzi-kafka-operator#7048]
We've been using strimzi for about a year. 

We are now refining our productization procedures. We've found an issue in the deployment of strimzi "latest" that seems like a relatively minor shortcoming in the support for installing "named versions".

the default strimzi process for deploying the latest is:
`kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka`

When you perform this command the specified namespace (kafka in the above) replaces the "myproject" that is currently seen in the "latest yaml" available on the [Downloads](https://strimzi.io/downloads/) page.

For example for [0.29.0](https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.29.0/strimzi-cluster-operator-0.29.0.yaml) "myproject" is found 5 times in the referenced yaml.

![image](https://user-images.githubusercontent.com/48793689/178759972-4d154e2f-7a71-43e0-a392-13bb2da95641.png)

Its fine that the installer (install/latest route) replaces myproject with namespace, however it also seems to "inject" 5 additional namespaces for the strimzi-cluster-operator Deployment,  2 RoleBindings (strimzi-cluster-operator, strimzi-cluster-operator-entity-operator-delegation ), 1 ConfigMap (strimzi-cluster-operator), and 1 ServiceAccount (strimzi-cluster-operator).

The following is found within strimzi-cluster-operator-0.29.0.yaml on the downloads page

![image](https://user-images.githubusercontent.com/48793689/178759518-96605e95-bf6d-42b2-840e-0d34808c43b0.png)

The following download of "[latest](https://strimzi.io/install/latest?namespace=i_am_a_namespace)" shows the "injected" namespace.

![image](https://user-images.githubusercontent.com/48793689/178759203-c0c43067-8d34-44b7-97ea-5fd6e4d47449.png)

![image](https://user-images.githubusercontent.com/48793689/178766480-d9f486dd-396c-4366-93d4-0d90ba9351b4.png)

If the 0.29.0 yaml had a "myproject" placeholder for these 5 injected namespaces, I'd have no problem.

Its then easy to download the version of interest and simply run sed to modify it. However the fact that 0.29.0 has 5 myprojects, and yet the "latest" has 5 replaced, and 5 injected, namespaces results in a mismatch that is difficult to deal with from the perspective of administering the operator.

this seems like an easy to fix "bug" in the installation procedures (and the installation yaml) provided by strimzi.

Please advise.

**Comment by scholzj** [comment]
Triaged on 25.8.2022: Should be closed. The benefits do not seem really clear and it is also not really clear what problems would the removal of the namespaces cause to other users since the namespaces are used there from the beginning.
