### ISSUE TITLE
TopicOperatorTest has strong potential for false positives due to usage of Vert.x JUnit5 checkpoints

### ISSUE THREAD

**Issue by LiamClarkeNZ** [strimzi/strimzi-kafka-operator#7072]
**Describe the bug**
There are assertions within the TopicOperatorTest that, even if failing, won't cause the test to fail, as the `VertxTestContext` has already been completed. This is most obvious within the `TopicOperatorTest#resourceAdded` method, which even includes a wait for the context to be completed. 

Subsequent assertions within a `VertxTestContext#verify` block are effectively noops, as even if they fail, the context has already been marked as completed and succeeded. 

I've run tests with a modified version of the VertxTestContext that I'm hoping to merge to vertx-junit-5 soon, and it flags the following as having this problem:

```
TopicOperatorTest.testOnKafkaTopicAdded_ClusterAuthorizationException
TopicOperatorTest.testOnKafkaTopicAdded_EntityExistsException
TopicOperatorTest.testOnKafkaTopicAdded_TopicExistsException
TopicOperatorTest.testReconcileMetrics
TopicOperatorTest.testReconcileMetricsDeletedTopic
TopicOperatorTest.testReconcileMetricsWithPausedTopic
TopicOperatorTest.testReconcile_withResource_noKafka_noPrivate
TopicOperatorTest.testReconcile_withResource_withKafka_noPrivate_matching
TopicOperatorTest.testReconcile_withResource_withKafka_noPrivate_overriddenName
```

**To Reproduce**
For an example: 
1. Edit `TopicOperatorTest#assertNotReadyStatus` to include an assertion that would fail, e.g.,:

```java
    void assertNotReadyStatus(VertxTestContext context, Exception createException) {
        List<KafkaTopicStatus> statuses = mockK8s.getStatuses();
        context.verify(() -> assertThat(statuses.size(), is(-100)));
```

2. Run `TopicOperatorTest#testOnKafkaTopicAdded_TopicExistsException` and watch it turn green, as the context was already marked as successful in `TopicOperatorTest#resourceAdded`.

**Expected behavior**
Checkpoints are used sparingly, if at all.

**Comment by scholzj** [comment]
Triaged on 25.8.2022: Should be fixed.
