### ISSUE TITLE
kafka-exporter-dashboard is unexpected on grafana 9

### ISSUE THREAD

**Issue by itzhoujun** [strimzi/strimzi-kafka-operator#7130]
**Describe the bug**
i import kafka exporter dashboard to grafana 9：
<img width="1855" alt="image" src="https://user-images.githubusercontent.com/6897671/181917285-2bf02609-4979-4a09-9318-51b6d14c72b7.png">
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/6897671/181917307-42b73723-4757-46a7-b9cf-3e8832c2d451.png">

**Comment by scholzj** [comment]
Works fine for me on Grafana 7.5. Are the metrics correct in your Prometheus? Or is Grafana is not backwards compatible (that would seem quite weird)?

**Comment by itzhoujun** [comment]
I modified the dashboard json modal manually

from:
```
"datasource": {
        "type": "datasource",
        "uid": "grafana"
      }
```
to:
```
"datasource": {
        "type": "prometheus",
        "uid": "P1809F7CD0C75ACF3" # my prometheus datasource uid
      },
```
