### ISSUE TITLE
Topic Operator fails to start while trying to clean /tmp

### ISSUE THREAD

**Issue by ramanenka** [strimzi/strimzi-kafka-operator#7143]
**Describe the bug**
We are testing the Strimzi upgrade from 0.28.0 to 0.30.0. The Topic Operator pod fails to start and enters a crach loop with the following logs being produced on each iteration:
```
rm: cannot remove '/tmp/hsperfdata_root/75': Permission denied
rm: cannot remove '/tmp/ks-script-31y0onvf': Operation not permitted
rm: cannot remove '/tmp/ks-script-_qd86jm0': Operation not permitted
```
This seems to be happening due to the image (`quay.io/strimzi/operator:0.30.0`) being built in the way that leaves some files in `/tmp` owned by `root`. When the pod starts [it fails to clean `/tmp`](https://github.com/strimzi/strimzi-kafka-operator/blob/fceaa81d723f4a7af4ca0738438b3fd9347f0922/topic-operator/scripts/topic_operator_run.sh#L5) as `strimzi` user doesn't have permissinos to delete those files:
```
$ docker run --rm -ti quay.io/strimzi/operator:0.30.0 bash -c 'id; ls -lha /tmp; rm -rvf /tmp/*'
uid=1001(strimzi) gid=0(root) groups=0(root)
total 20K
drwxrwxrwt 1 root root 4.0K Jul 15 19:08 .
drwxr-xr-x 1 root root 4.0K Aug  3 11:04 ..
drwxr-xr-x 2 root root 4.0K Jul 15 19:08 hsperfdata_root
-rwx------ 1 root root  701 Jun 17 04:13 ks-script-31y0onvf
-rwx------ 1 root root  291 Jun 17 04:13 ks-script-_qd86jm0
rm: cannot remove '/tmp/hsperfdata_root/75': Permission denied
rm: cannot remove '/tmp/ks-script-31y0onvf': Operation not permitted
rm: cannot remove '/tmp/ks-script-_qd86jm0': Operation not permitted
```

**To Reproduce**
1. Deploy Topic Operator from 0.30.0 release.
4. See it fails to start

**Expected behavior**
Topci Operator starts successfully.

**Environment:**
 - Strimzi version: 0.30.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.21

**Comment by scholzj** [comment]
How do you run the Topic Operator? The `/tmp` dir is normally overwritten by a empty-dir volume. so it does not matter what is inside the container image.

**Comment by scholzj** [comment]
I guess you are using the standalone Topic Operator deployment?

**Comment by scholzj** [comment]
I guess you are. The `/tmp` volume is missing int he standalone deployment. As a worksround, you can add it manually to the deployment. You can basically copy these two parts from the Cluster Operator deployment:
* https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L21-L24
* https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L36-L38

When deployed through the Cluster Operator, the Topic Operator normally uses 5Mi for the `/tmp` dir.

**Comment by ramanenka** [comment]
Yes, we are using the standalone Topic Operator deployment. Adding the `/tmp` volume fixes the problem. Thanks!

**Comment by scholzj** [comment]
Great, thanks for confirmation. I will get to it later and fix the YAML files in here as well.
