### ISSUE TITLE
Helm chart does not install the strimzipodsets CRD

### ISSUE THREAD

**Issue by benmathews** [strimzi/strimzi-kafka-operator#7147]
I updated my install of the strimzi-kafka-operator chart from 0.29.0 to 0.30.0 and the operator started crashing w/ 

```
2022-08-03 14:54:10 ERROR Main:165 - Cluster Operator verticle in namespace platformkafka failed to start
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.31.250.1/apis/core.strimzi.io/v1beta2/namespaces/platformkafka/strimzipodsets. Message: Not Found.
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555) ~[io.fabric8.kubernetes-client-5.12.2.jar:?]
```

After some digging, I noticed the request for strimzipodset, a new CRD. I checked out the 0.30.0 tag and manually installed strimzipodset. This resolved the crashing.

**Expected behavior**
The helm chart should install needed CRDs

**Environment (please complete the following information):**
 - Strimzi version: 0.30.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes v1.21.12
 - Infrastructure: Self hosted

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/main/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh --namespace <string> --cluster <string> [--bridge <string>] [--connect <string>] [--mm2 <string>]`*

**Additional context**

**Comment by scholzj** [comment]
Helm for whatever reason never updates any CRDs. You have to update them manually after the upgrade. This is both in our and in Helm docs.

**Comment by bmitchinson** [comment]
![image](https://user-images.githubusercontent.com/33632286/194436973-5478853a-4573-40b4-b375-5d4b1817f9db.png)

Section 10.4

After seeing this issue, I went to [the releases](https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.31.1), downloaded `[strimzi-crds-0.31.1.yaml]`, and did `kubectl apply -f strimzi-crds-0.31.1.yaml -n {namespace}`.

This fixed my operator startup error. 

I'm curious how I can automate this step though as part of the helm release, but that's a separate issue. No need to re-open, just leaving this info here for others.
