### ISSUE TITLE
Strimzi should identify itself via its User-Agent in calls to the Kubernetes API

### ISSUE THREAD

**Issue by adamzr** [strimzi/strimzi-kafka-operator#7163]
**Is your feature request related to a problem? Please describe.**
I am trying to determine which system is calling certain K8s APIs to see who is using a deprecated API before I do a K8s upgrade. The only data available about the caller is the User-Agent.

**Describe the solution you'd like**
Add the strimzi component name and version to the User-Agent string used by the Kubernetes client.

**Describe alternatives you've considered**
_None considered_

**Additional context**
_N/A_

**Comment by scholzj** [comment]
If you tell us how to do it, we can see if it can be done. But Kubernetes know what service account was making the calls which should be enough to identify the application.
