### ISSUE TITLE
Reconcile or Ignore topics found in the kafka cluster based on pattern

### ISSUE THREAD

**Issue by luisdavim** [strimzi/strimzi-kafka-operator#7183]
**Is your feature request related to a problem? Please describe.**
Some topics might be managed by some external system or we might just not want Strimzi to manage them or expose them as k8s resources.

**Describe the solution you'd like**
It would be great if there was a way of specifying a pattern to tell the topic operator to ignore matching topics, or the other way around, to tell it to only reconcile topics matching a given pattern.

**Describe alternatives you've considered**
I've checked the documentation and previous issues, both open and closed and couldn't find any alternative.

**Additional Context**
Using the topic operator in standalone mode with an AWS MSK Kafka cluster.

This could also be used as a workaround for https://github.com/strimzi/strimzi-kafka-operator/issues/1206, using multiple instances of the topic operator to manage different sets of topics in different namespaces.

**Comment by scholzj** [comment]
Triaged on 25.8.2022: This would be useful feature. But proposal detailing the implementation would be needed.

**Comment by luisdavim** [comment]
@scholzj do you have a template for the proposals?

**Comment by scholzj** [comment]
The proposals are here: https://github.com/strimzi/proposals ... it has a template file as well. You can check the other proposals. Just to be clear, a proposal like this would explain how it will be implemented as well, so it would require a knowledge of the Topic Operator code etc.

**Comment by scholzj** [comment]
(But you are of course welcomed to work on it!)

**Comment by coltmcnealy-lh** [comment]
Is this still relevant given the Uni-Directional Topic Operator?

**Comment by scholzj** [comment]
@tombentley @fvaleri I guess it makes no sense for Unidirectional TO, or?

**Comment by fvaleri** [comment]
That's correct @scholzj.

>  we might just not want Strimzi to manage them or expose them as k8s resources.

Using the new [UnidirectionalTopicOperator](https://strimzi.io/docs/operators/latest/deploying#ref-operator-unidirectional-topic-operator-feature-gate-str), which is fully backward compatible, you can un-manage a topic by setting the `strimzi.io/managed="false"` on the `KafkaTopic` resource with the same `topicName`. After you do that the UTO will completely ignore the resource when reconciling, also in case of deletion.

**Comment by scholzj** [comment]
Triaged in the community call on 21.9.2023: Does not make sense anymore with UTO and should be closed.
