### ISSUE TITLE
Add integration tests for SimpleAclOperator

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#721]
The `SImpleAclOperator` class has currently a good unit test coverage implemented using mocked `SimpleAclAuthorizer` class. It would be good to add some integration tests which would take it through paces also against an actual Kafka cluster. We have already IT tests using Kafka cluster in the topic operator. We can use the same mechanism to start the Kafka cluster for these tests here as well. Although I think we can test just the `SimpleAclOperator` alone and not test the whole setup including Kubertener.

**Comment by vdinovi** [comment]
https://github.com/strimzi/strimzi-kafka-operator/pull/2783 Appears to have introduced integration tests for the `SimpleAclOperator`. Can this be closed?

**Comment by ppatierno** [comment]
Yes thanks!
