### ISSUE TITLE
Add support for TransactionalID resource

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#722]
Currently the ACL support in User Oerator supports only following three resource types:
* Cluster
* Topic
* Group

It would be good to add support also for TransactionalID resources.

**Comment by ppatierno** [comment]
Taking a look at Kafka upstream source code it seems this option is available (there is `delegation-token` as well) but it's not documented upstream.

**Comment by scholzj** [comment]
This has been implemented in #1048
