### ISSUE TITLE
Improves KubernetesSecretConfigProvider with injecting files

### ISSUE THREAD

**Issue by lordofthejars** [strimzi/strimzi-kafka-operator#7240]
**Is your feature request related to a problem? Please describe.**

For some properties, you need to materialize the secret content as a file (ie truststores, ...) this makes you deal with two approaches, one injecting the files using Kubernetes volumes and the second one injecting using Kube API the passwords.
 

**Describe the solution you'd like**

kafka.ssl.truststore.location=${materializedsecret:debezium-example:my-cluster:ca.p12}
kafka.ssl.truststore.password=${secrets:debezium-example:my-cluster:ca.password}

 

Where materializedSecret takes the key, creates a file in the filesystem, and injects its location.

**Describe alternatives you've considered**

We can always use `externalConfiguration` with volumes, but then we are accessing secrets in two different ways. So there is a workaround.

**Comment by scholzj** [comment]
Triaged on the community call on 1.12.2022: This is not as simple as it sounds. The Config Provider is called multiple times during the lifecycle of the Connect pod. So creating files from the config providers is a bit messy. Using the `externalConfiguration` is the right model here.
