### ISSUE TITLE
kafka connect

### ISSUE THREAD

**Issue by thbeh** [strimzi/strimzi-kafka-operator#730]
I used the example in v0.5 doc to create kafka-connect like the following 
_apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
spec:
  nodes: 1
  image: strimzi/kafka-connect:0.5.0
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  config:
    bootstrap.servers: my-cluster-kafka-bootstrap:9092_

even 'nodes' is define as 1 but it still spin up 3 instances. Is that normal?

**Comment by ppatierno** [comment]
The example seems to be wrong, the correct field is `replicas` instead of `nodes`.

**Comment by thbeh** [comment]
Thanks, will change to replicas.

**Comment by ppatierno** [comment]
@thbeh can I close this issue? Did the suggestion work for you?
