### ISSUE TITLE
[Helm] Add option to set more than 1 replicas for the operator

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7302]
Based on https://github.com/orgs/strimzi/discussions/7301 ... the Helm Chart should have an option to configure the number of replicas in the cluster operator.

**Comment by joseacl** [comment]
Hi @scholzj ,
I've created a PR for that issue, https://github.com/strimzi/strimzi-kafka-operator/pull/7304

**Comment by sknot-rh** [comment]
Solved in https://github.com/strimzi/strimzi-kafka-operator/pull/7304
Thank you
