### ISSUE TITLE
Helm chart 0.31.1 is not yet available in the repository

### ISSUE THREAD

**Issue by uncycler** [strimzi/strimzi-kafka-operator#7369]
**Describe the bug**
Helm chart 0.31.1 is not yet available in the repository (https://strimzi.io/charts/index.yaml)

**Expected behavior**
The helm chart should be pushed to repo at the same time as the other assets.

**Environment (please complete the following information):**
 - Strimzi version: 0.31.1
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.24

**Comment by scholzj** [comment]
This should have been fixed in strimzi/strimzi.github.io#321. So please give it another try.

**Comment by uncycler** [comment]
It's all good, thanks!

**Comment by scholzj** [comment]
Great. Sorry for the complication :-/.
