### ISSUE TITLE
Combine different SASL mechanisms on a single listener

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7372]
This was one of the comments from the Strimzi Survey 2022. We currently don't support combination of multiple SASL mechanisms on a single listener (with the exception of OAuth which can do OAUTHBEARER and OAuth over PLAIN at the same time). The usecase is not completely clear, but this is something what can be evaluated. In particular the new API is not completely clear.

There is also similar issue #5331 about combining SASL and mTLS.

**Comment by tombentley** [comment]
Triaged on community call 1/12/2022. The decision was that it's difficult to justify the work for this when the use case is so unclear. It's not clear which SASL mechanisms which we support today would benefit from being used on the same listener. So we will close this.
