### ISSUE TITLE
Improve the Kafka brokers Grafana dashboard

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7374]
The "Log size" chart in our Kafka brokersGrafana dashboard is not that great. It shows each partition replica, so even in a very small cluster, you can very easily have few hundred items in it (just the default `__consumer_offsets` partition replicas make 150 items). This can be surely improved. SOme of the ideas were:
* Replacing it with table with paging?
* Using panels to be able to colapse it instead of rendering it all the time
* Spliting th dashboard into separate parts

This is one of the issues based on feedback from the Strimzi Survey 2022

**Comment by tombentley** [comment]
Triaged on community call 1/12/2022. This seems like a good improvement that we should try to implement.

**Comment by maciej-tatarski** [comment]
@scholzj let me know if this is still needed

**Comment by scholzj** [comment]
@maciej-tatarski I think this would be useful. Are you able to make it work across the different Grafana versions? Thanks.

**Comment by maciej-tatarski** [comment]
I tested it with grafana `7.3.7`, `7.5.7`:
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/135701313/1741d489-4608-4a77-8cd2-06a3a5e550db)

and `10.3.4`:
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/135701313/027c8c4c-8769-4849-95d7-148b50edafd8)

**Comment by scholzj** [comment]
Yeah, that looks good I think.

**Comment by maciej-tatarski** [comment]
Sure, I'll make a PR soon
