### ISSUE TITLE
Restrict cluster operator priviledges when in cluster wide mode

### ISSUE THREAD

**Issue by dadufour** [strimzi/strimzi-kafka-operator#7378]
When the cluster operator is installed in cluster wide mode (watching all namespaces), it has to be granted some cluster roles through cluster role bindings. In particular, the cluste role strimzi-cluster-operator-namespaced. The problem is that this cluster role contains quite sensitive k8s resources like secrets and rolebindings. As a consequence, the cluster operator service account is granted rights on secrets in ALL namespaces of the k8s cluster, which is a security concern.

We would like the service account to have rights at cluster scope only for necessary resources (principle of least priviledge). To do so, we propose to have strimzi-cluster-operator-namespaced split in 2 distinct cluster roles. One containing non sensitive resources that the cluster operator requires at cluster scope. Another one with sensitive resources that the cluster operator requires only for namespace hosting a strimzi resource.

The first cluster role would be bound with a cluster role binding once for all while the second with role bindings only in namespaces hosting strimzi resources

**Comment by scholzj** [comment]
I opened https://github.com/strimzi/strimzi-kafka-operator/pull/7390 for this.
