### ISSUE TITLE
Quickstart lists step that is not needed (and not possible)

### ISSUE THREAD

**Issue by v42net** [strimzi/strimzi-kafka-operator#7381]
**Suggestion / Problem**
The Quickstart section [`Installing Strimzi`](https://strimzi.io/docs/operators/latest/quickstart.html#proc-install-product-str) step 6 instructs to edit `install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml`. This entry now uses a `valueFrom`, so I suspect that it does not need to be modified anymore.

**Documentation Link**
https://strimzi.io/docs/operators/latest/quickstart.html#proc-install-product-str

**Comment by scholzj** [comment]
You mean the value for `STRIMZI_NAMESPACE`? That always used `vaueFrom` in the default installation files. But it defaults to the namespace where the operator runs while the example tells it to watch another namespace. So it needs to be modified.

**Comment by v42net** [comment]
Indeed the value of `STRIMZI_NAMESPACE`. From the quickstart instructions I understood that I had to replace `value: <old-value>` by `value: <new-value>`. So as a newbe, finding a `valueFrom` entry I suspected that this instruction was outdated. Thanks for the explanation.

**Comment by scholzj** [comment]
Ahh, ok. I opened https://github.com/strimzi/strimzi-kafka-operator/pull/7392 => do you think that would make it more clear for you?
