### ISSUE TITLE
Remove support for OpenTracing

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#7385]
When the #7201 (about adding OpenTelemetry support) will be closed, we should remove the OpenTracing support.
The OpenTracing project is now archived and not supported anymore with new releases, bug fixes or CVEs.
The Strimzi operator already deprecates its usage since 0.31.0 release.
By using the future OpenTelemetry addition, users can still continue to use their Jaeger UI to get tracing information, because the operator will use a `jaeger` exporter by default to maitain ba

**Comment by scholzj** [comment]
I think we should treat it a bit more nicely from backwards compatibility perspective as it is still working and not  remove it immediately.

**Comment by ppatierno** [comment]
Maybe we should define some "intermediate" Strimzi versions when it's still available and define which will be the next one where the OpenTracing support will be dropped. Of course, it depends on which version the OpenTelemetry support will be available.

**Comment by scholzj** [comment]
The deprecation of OpenTracing was done mainly because it was not clear how long it will work. At that point, it was not clear when will we have the OpenTelemetry support. So it was not possible do really discuss when it will be removed. If we manage to get OpenTelemetry in 0.32, maybe it could be something like `min(0.36, <when it stops working>)` or something like that. It would be good to discuss and decide on the exact version and clarify it in the docs when adding the Open Telemetry.

**Comment by ppatierno** [comment]
Other than "when it stops working" I am bother by CVEs and vulnerabilities as well. They won't be addressed anymore if a new OpenTracing isn't released. Does it count as "stop working" for you?

**Comment by scholzj** [comment]
I guess it would depend on how serious the CVE is 🤷

**Comment by ppatierno** [comment]
Yeah I meant for higher/critical ones.

**Comment by tombentley** [comment]
Triaged on community call 1/12/2022. Decision was that support should be removed by the first release after July 2023, announcing this in the changelog for the next release.

**Comment by ppatierno** [comment]
We have a corresponding issue on the bridge here https://github.com/strimzi/strimzi-kafka-bridge/issues/661
I guess it will be subjected to the same timeline because the `KafkaBridge` custom resource won't have support for OpenTracing anymore so the bridge won't need it.

**Comment by scholzj** [comment]
I opened #7743 for the docs and release notes.
