### ISSUE TITLE
Update JMX Exporter to 0.17.2 to patch snakeyaml CVEs

### ISSUE THREAD

**Issue by Boojapho** [strimzi/strimzi-kafka-operator#7398]
JMX Exporter 0.17.0 [shades SnakeYaml 1.30](https://github.com/prometheus/jmx_exporter/blob/main/jmx_prometheus_javaagent/pom.xml#L55).  Strimzi shadowed snakeyaml to 1.32, but because this one is shaded, it can't be overridden.  

JMX Exporter 0.17.2 has been rebuilt with SnakeYaml 1.32.   Update Strimzi to this version to patch the vulnerabilities in earlier versions of snakeyaml.

**Comment by scholzj** [comment]
Will you open a PR for it? Or should I do it?

**Comment by Boojapho** [comment]
I've got it
