### ISSUE TITLE
Intermittent test failure in KafkaConnectorIT

### ISSUE THREAD

**Issue by katheris** [strimzi/strimzi-kafka-operator#7420]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
The KafkaConnectorIT class has a problem where sometimes the tasks do not become ready during the reconcile loop. This means that the status that is checked by the test does not look as expected.

**To Reproduce**
As an example, this azure build failed: https://dev.azure.com/cncf/strimzi/_build/results?buildId=117901&view=logs&j=f79bfc33-8667-5620-e640-8f4582ec8a7d&t=7f904af8-831e-5ed4-4fba-83342469a022

**Expected behavior**
Instead we should have a more consistent way to make sure the connector is fully up before the test assertions are run so the test doesn't fail intermittently.

**Comment by scholzj** [comment]
I think we should try something like _adding_ a second reconciliation to stabilise the test. That should give Connect more time to start (and fail the task).
