### ISSUE TITLE
When kafka broker starts it is exiting due to Nullpointer exception

### ISSUE THREAD

**Issue by shahir-imemori** [strimzi/strimzi-kafka-operator#7443]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
When Kafka cluster starts on version 0.31.1 it crashes with the error "java.lang.NullPointerException"

**To Reproduce**
1. Deploy Kubernetes Cluster using the YAML file
2. Kafka cluster doesn't start. Getting below when list the PODS
imem-ns-dev-kafka-kafka-0                        0/1     CrashLoopBackOff   6 (3m16s ago)   9m29s
3. See error using kubectl logs  test-kafka-kafka-0 -n test

**Expected behavior**
Need to start kafka cluster

**Environment (please complete the following information):**
 - Strimzi version: 0.31.1
 - Installation method: YAML
 - Kubernetes cluster: 1.23.8
 - Infrastructure: Azure

**YAML files and logs**
        apiVersion: kafka.strimzi.io/v1beta2
        kind: Kafka
        metadata:
          name: "test-kafka"
          namespace: "test"
        spec:
          kafka:
            version: 3.2.3
            replicas: "1"
            listeners:
              - name: plain
                port: 9092
                type: internal
                tls: false
              - name: tls
                port: 9093
                type: internal
                tls: true
            config:
              offsets.topic.replication.factor: "1"
              transaction.state.log.replication.factor: "1"
              default.replication.factor: "1"
              transaction.state.log.min.isr: "1"
              min.insync.replicas: "1"
              inter.broker.protocol.version: "3.2"
            storage:
              type: jbod
              volumes:
              - id: 0
                type: persistent-claim
                size: 10Gi
                deleteClaim: false
            metricsConfig:
              type: jmxPrometheusExporter
              valueFrom:
                configMapKeyRef:
                  name: "test-q-metrics"
                  key: kafka-metrics-config.yml
          zookeeper:
            replicas: "1"
            storage:
              type: persistent-claim
              size: 10Gi
              deleteClaim: false
            metricsConfig:
              type: jmxPrometheusExporter
              valueFrom:
                configMapKeyRef:
                  name: "test-q-metrics"
                  key: zookeeper-metrics-config.yml              
          entityOperator:
            topicOperator: {}
            userOperator: {}

        kind: ConfigMap
        apiVersion: "v1"
        metadata:
          name: "test-q-metrics"
          namespace: "test"
          labels:
            app: "test-kafka"
        data:
          kafka-metrics-config.yml: |
            # See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus Exporter metrics
            lowercaseOutputName: true
            rules:
            # Special cases and very specific rules
            - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
              name: kafka_server_$1_$2
              type: GAUGE
              labels:
              clientId: "$3"
              topic: "$4"
              partition: "$5"
            - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
              name: kafka_server_$1_$2
              type: GAUGE
              labels:
              clientId: "$3"
              broker: "$4:$5"
            - pattern: kafka.server<type=(.+), cipher=(.+), protocol=(.+), listener=(.+), networkProcessor=(.+)><>connections
              name: kafka_server_$1_connections_tls_info
              type: GAUGE
              labels:
                cipher: "$2"
                protocol: "$3"
                listener: "$4"
                networkProcessor: "$5"
            - pattern: kafka.server<type=(.+), clientSoftwareName=(.+), clientSoftwareVersion=(.+), listener=(.+), networkProcessor=(.+)><>connections
              name: kafka_server_$1_connections_software
              type: GAUGE
              labels:
                clientSoftwareName: "$2"
                clientSoftwareVersion: "$3"
                listener: "$4"
                networkProcessor: "$5"
            - pattern: "kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+):"
              name: kafka_server_$1_$4
              type: GAUGE
              labels:
              listener: "$2"
              networkProcessor: "$3"
            - pattern: kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+)
              name: kafka_server_$1_$4
              type: GAUGE
              labels:
              listener: "$2"
              networkProcessor: "$3"
            # Some percent metrics use MeanRate attribute
            # Ex) kafka.server<type=(KafkaRequestHandlerPool), name=(RequestHandlerAvgIdlePercent)><>MeanRate
            - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate
              name: kafka_$1_$2_$3_percent
              type: GAUGE
            # Generic gauges for percents
            - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value
              name: kafka_$1_$2_$3_percent
              type: GAUGE
            - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value
              name: kafka_$1_$2_$3_percent
              type: GAUGE
              labels:
                "$4": "$5"
            # Generic per-second counters with 0-2 key/value pairs
            - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+), (.+)=(.+)><>Count
              name: kafka_$1_$2_$3_total
              type: COUNTER
              labels:
                "$4": "$5"
                "$6": "$7"
            - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count
              name: kafka_$1_$2_$3_total
              type: COUNTER
              labels:
                "$4": "$5"
            - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count
              name: kafka_$1_$2_$3_total
              type: COUNTER
            # Generic gauges with 0-2 key/value pairs
            - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value
              name: kafka_$1_$2_$3
              type: GAUGE
              labels:
                "$4": "$5"
                "$6": "$7"
            - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value
              name: kafka_$1_$2_$3
              type: GAUGE
              labels:
                "$4": "$5"
            - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
              name: kafka_$1_$2_$3
              type: GAUGE
            # Emulate Prometheus 'Summary' metrics for the exported 'Histogram's.
            # Note that these are missing the '_sum' metric!
            - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count
              name: kafka_$1_$2_$3_count
              type: COUNTER
              labels:
                "$4": "$5"
                "$6": "$7"
            - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*), (.+)=(.+)><>(\d+)thPercentile
              name: kafka_$1_$2_$3
              type: GAUGE
              labels:
                "$4": "$5"
                "$6": "$7"
                quantile: "0.$8"
            - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count
              name: kafka_$1_$2_$3_count
              type: COUNTER
              labels:
                "$4": "$5"
            - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile
              name: kafka_$1_$2_$3
              type: GAUGE
              labels:
                "$4": "$5"
                quantile: "0.$6"
            - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Count
              name: kafka_$1_$2_$3_count
              type: COUNTER
            - pattern: kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile
              name: kafka_$1_$2_$3
              type: GAUGE
              labels:
                quantile: "0.$4"
          zookeeper-metrics-config.yml: |
            # See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus Exporter metrics
            lowercaseOutputName: true
            rules:
            # replicated Zookeeper
            - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
              name: "zookeeper_$2"
              type: GAUGE
            - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
              name: "zookeeper_$3"
              type: GAUGE
              labels:
                replicaId: "$2"
            - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(Packets\\w+)"
              name: "zookeeper_$4"
              type: COUNTER
              labels:
                replicaId: "$2"
                memberType: "$3"
            - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(\\w+)"
              name: "zookeeper_$4"
              type: GAUGE
              labels:
                replicaId: "$2"
                memberType: "$3"
            - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)><>(\\w+)"
              name: "zookeeper_$4_$5"
              type: GAUGE
              labels:
                replicaId: "$2"
                memberType: "$3"

+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NullPointerException
	at java.base/java.util.TreeMap.putAll(TreeMap.java:312)
	at java.base/java.util.TreeMap.<init>(TreeMap.java:185)
	at io.prometheus.jmx.JmxCollector.loadConfig(JmxCollector.java:251)
	at io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:91)
	at io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422

**Comment by shahir-imemori** [comment]
Recreated the Kafka by deleting the operator worked

**Comment by shahir-imemori** [comment]
After enabling Prometheus the issue reappeared

**Comment by scholzj** [comment]
Probably some issue with your configuration for the JMX Exporter? Have you compared it with what we have in our examples?

**Comment by shahir-imemori** [comment]
I used the example from the below URL for configuration.
https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/kafka-metrics.yaml

Is there any additional configuration required

**Comment by scholzj** [comment]
Well, if you try to diff them, then your file is not the same. it has a bad allignment in several places:

```diff
       name: kafka_server_$1_$2
       type: GAUGE
       labels:
-       clientId: "$3"
-       topic: "$4"
-       partition: "$5"
+      clientId: "$3"
+      topic: "$4"
+      partition: "$5"
     - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
       name: kafka_server_$1_$2
       type: GAUGE
       labels:
-       clientId: "$3"
-       broker: "$4:$5"
+      clientId: "$3"
+      broker: "$4:$5"
     - pattern: kafka.server<type=(.+), cipher=(.+), protocol=(.+), listener=(.+), networkProcessor=(.+)><>connections
       name: kafka_server_$1_connections_tls_info
       type: GAUGE
@@ -111,14 +111,14 @@ data:
       name: kafka_server_$1_$4
       type: GAUGE
       labels:
-       listener: "$2"
-       networkProcessor: "$3"
+      listener: "$2"
+      networkProcessor: "$3"
     - pattern: kafka.server<type=(.+), listener=(.+), networkProcessor=(.+)><>(.+)
       name: kafka_server_$1_$4
       type: GAUGE
       labels:
-       listener: "$2"
-       networkProcessor: "$3"
+      listener: "$2"
+      networkProcessor: "$3"
     # Some percent metrics use MeanRate attribute
     # Ex) kafka.server<type=(KafkaRequestHandlerPool), name=(RequestHandlerAvgIdlePercent)><>MeanRate
     - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate
```

So probably as a first step you should make sure it is really the same. You should also doublecheck how you create it and make sure the `$` don't get replaced by bash for example etc.

**Comment by shahir-imemori** [comment]
Thanks for the guidance. It is working now.
