### ISSUE TITLE
Making probes configurable in Topic and User operators

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#745]
The new deployment of Topic and User operators through the Entity operator doesn't allow to customize liveness and readiness probes (which already happened with the "old" Topic operator deployment).
We should make it possible because today the HTTP probes is hardcoded on port 8080 for the Topic operator and port 8081 for the User operator.

**Comment by scholzj** [comment]
This should be fixed in #1619
