### ISSUE TITLE
Update Jacoco version to at least 0.8.3

### ISSUE THREAD

**Issue by mcullenEST** [strimzi/strimzi-kafka-operator#7458]
**Describe the bug**
The current version of Jacoco used in Strimzi is 0.7.9 (https://github.com/strimzi/strimzi-kafka-operator/blob/main/pom.xml#L92). However, this version doesn't support Java 11. Can we upgrade this to above 0.8.3 as this is when Java 11 support happens? 
See --> https://www.jacoco.org/jacoco/trunk/doc/changes.html

**Expected behavior**
Jacoco to run on Java 11

**Environment (please complete the following information):**
 - Strimzi version: 0.31.0

**Comment by scholzj** [comment]
TBH, I do not think the Jacoco is really used for anything. I always when I notice it want to look into it but then I forget about it. Do you have any use-case for it? If yes, feel free to open a PR to upgrade it. But in general I think we should investigate it and remove it if it is not used.
