### ISSUE TITLE
[ST] Kafka clients used in system tests should do TLS hostname verification

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7518]
It seems that today, the clients used by system tests disableTLS hostname verifications. At least the internal clients: https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/src/main/java/io/strimzi/systemtest/kafkaclients/internalClients/KafkaClients.java#L430

This does not make much sense => the hostname verification should work for all internal listeners. It should also work for all external listeners apart from node ports. So this should be also tested and not be disabled int he tests. This caused issues for example in #7365

**Comment by im-konge** [comment]
Fixed in #7526
