### ISSUE TITLE
Add support for OpenFeature

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7520]
Currently, Strimzi has its own mechanism for configuring feature gates. It uses environment variables. That brings in following limitations:
* Changes to the Feature Gates require restart of the operator
* The feature gates apply only centrally for all managed operands

One of the ways forward which should be considered would be using [OpenFeature](https://openfeature.dev/) to provide better and more granular support. We could keep the current model for _normal_ users which do not have any special requirements and do not want to run / use any special feature flagging software. But we could support some more advanced OpenFeature providers to:
* Allow changes per-cluster / namespace
* Allow dynamic changes

These would require the user to use some project / service with OpenFeature provider for it.

This needs a proposal first.

**Comment by scholzj** [comment]
As the proposal from @see-quick was closed as _rejected_ ... should we close this issue as well?

**Comment by ppatierno** [comment]
Triaged on 28/11/2024: agreed on closing it also because of the "rejected" proposal.
