### ISSUE TITLE
Error reported when ipFamiliy configured is confusing

### ISSUE THREAD

**Issue by acshekhara1** [strimzi/strimzi-kafka-operator#7524]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
 When ipFamily and ipFamilyPolicy is configured for internal listner, it throws an error saying
"Listener configuration is not valid: [listener plainauth cannot configure ipFamilyPolicy because it is not internal listener, listener plainauth cannot configure ipFamilies because it is not **internal** listener]"

**To Reproduce**
Create an internal listner with
      - name: plain
        port: 9093
        type: internal
        tls: false
        configuration:
          ipFamilyPolicy: PreferDualStack
          ipFamilies: [ IPv6, IPv4 ]

**Expected behavior**
 I think this is confusing. rather I would expect error to be "listner is internal" or "listener is not external".

**Environment (please complete the following information):**
 - Strimzi version: 0.31.1
 - Installation method: YAML files
 - Kubernetes cluster: v1.23.13
 - Infrastructure: baremetal

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/main/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh --namespace <string> --cluster <string> [--bridge <string>] [--connect <string>] [--mm2 <string>]`*

**Additional context**

**Comment by scholzj** [comment]
Can you please format the YAMl as code so that it is clear how your structure looks like?

**Comment by scholzj** [comment]
Yeah, you are right. The error is wrong (regardless if your YAML snippet is valid or not). I will fix it.

**Comment by acshekhara1** [comment]
Thank you.
