### ISSUE TITLE
Fix and re-enable `MetricsIsolatedST.testKafkaBridgeMetrics` test

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#7544]
The `MetricsIsolatedST.testKafkaBridgeMetrics` is disabled with https://github.com/strimzi/strimzi-kafka-operator/pull/7543.
After digging into it and fixing the issue we should re-enable the test again.

**Comment by scholzj** [comment]
CC @im-konge

**Comment by im-konge** [comment]
Thanks @ppatierno and @scholzj . It's a bit surprising that it's failing just now and it wasn't failing before.
Anyway, I will look at this.

**Comment by scholzj** [comment]
I wonder if something changed in OpenJDK or something and it is reporting overall numbers instead of what is available to the container? In any case, I think some better metric should be tested or you hould just test its presence instead of an exact number.

**Comment by im-konge** [comment]
Yes, maybe that's it
I think that checking the presence would be better instead of exact number (or maybe some more relevant metric to Bridge, as you mentioned)

**Comment by ppatierno** [comment]
Yeah I was also wondering why that check on the CPU count was added just to the bridge test and not the others.

**Comment by im-konge** [comment]
That's different question. Do you think it's important metric which shloud be tested for all components? I don't remember why exactly this metric was used just for the Bridge test.
