### ISSUE TITLE
Docs: Document how to use the broker public key and user certificates from User Operator

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#763]
Document how to use / mount the `cluster-ca-cert` with broker CA or the secret from User Operator.

**Comment by PaulRMellor** [comment]
_Using Strimzi_ now has the following procedures:

- [Configuring internal clients to trust the cluster CA](https://strimzi.io/docs/operators/in-development/using.html#configuring-internal-clients-to-trust-cluster-ca-str)
- [Configuring external clients to trust the cluster CA](https://strimzi.io/docs/operators/in-development/using.html#configuring-external-clients-to-trust-cluster-ca-str)
