### ISSUE TITLE
Logging for Kafka Mirror Maker Zookeeper and Co should be changeable without rolling update

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#765]
Logging for Kafka, Zookeeper and Co should be changeable without rolling update - because you often want to increse log levels on the fly - without restarting the brokers etc. This could be critical for users to help us debug issues.

**Comment by stanlyDoge** [comment]
There is `monitorInterval` attribute which should reload `log4j.properties` file automatically. I was trying this with `log4j2` and that didn't seem to work :( I will try this with `log4j`.

**Comment by scholzj** [comment]
I spawn some new issued to cover Kafka and Kafka Connect:
* #2806 
* #2807 

This issue should be kept for Zookeeper and Kafka Mirror Maker.

**Comment by scholzj** [comment]
Triaged on 22.02.2022: Once Kafka moves to Log4j2, we might be able to use the Log4j2 refresh intervals to handle Mirror Maker and ZooKeeper. We should get back to this again later.

**Comment by scholzj** [comment]
It looks like Kafka will move to Log4j2 only in Kafka 4.0. At that point, ZooKeeper and Mirror Maker 1 will be gone. So it will not help. Not other effort is expected until then to make the logging configurable. This should be closed.
