### ISSUE TITLE
TO and UO should have same defaults

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#766]
For things like reconciliation interval, zk session timeout etc.

**Comment by scholzj** [comment]
It looks like the main differences are:
* Reconciliation interval (UO=120s, TO=90s)
* Zookeeper timeout (UO=6s, TO=20s)

**Comment by scholzj** [comment]
Reconciliation Interval => Change to 120s
Zookeeper Timeout => 18s for both
