### ISSUE TITLE
Resources should validate correctness of new configuration

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#7683]
**Describe the bug**

During testing of #7421 , I have tried scenario with 3 Kafka pods and 3 Zookeeper pods, where user will specify some invalid configuration - f.e. setting request bigger than the limit. When the Zookeper is edited with this invalid configuration, first pod is deleted and after a while, another two pods are deleted, with 1 pod which is trying to be deployed - ending in `CrashLoopBackOff` state. But, this is not problem just for Zookeeper, but also for all other resources.

**To Reproduce**

1. Deploy CO
2. Deploy Kafka cluster with 3 Kafka pods and 3 ZK pods
3. Edit Zookeeper part of the Kafka CR, setting the invalid configuration
4. Check the rolling update of Zookeeper pods

**Expected behavior**

Instead of deleting/rolling the whole Zookeeper cluster, it would maybe throw `InvalidResourceException` and prevent the rolling update to happen

**Environment (please complete the following information):**
 - Strimzi version: main
 - Installation method: YAML
 - Kubernetes cluster: Kubernetes 1.19 and above
 - Infrastructure: Minikube

**YAML files and logs**

`kubectl get pods`
```
NAME                                                 READY   STATUS    RESTARTS   AGE
my-cluster-61d4c97e-entity-operator-c85cbdb6-6grc4   3/3     Running   0          16m
my-cluster-61d4c97e-kafka-0                          1/1     Running   0          16m
my-cluster-61d4c97e-kafka-1                          1/1     Running   0          11m
my-cluster-61d4c97e-kafka-2                          1/1     Running   0          11m
my-cluster-61d4c97e-zookeeper-0                      0/1     Running   1          17m
```

kafka.yaml
https://gist.github.com/im-konge/92cd4c9bf14fe63b2fde509e45ba16db

**Comment by scholzj** [comment]
Note: This issue is about validating the resources passed by the user to avoid these situations in the first place.
