### ISSUE TITLE
All Zookeeper pods are deleted when are rolled with invalid configuration

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#7685]
**Describe the bug**

As part of the [#7683](https://github.com/strimzi/strimzi-kafka-operator/issues/7683), there was also found one more thing about terminating the ZK pods. How it was done in #7421 , when the configuration cannot be fulfilled, it should just roll one ZK pod, to prevent loss of whole ZK cluster. But, instead of this behavior, each ZK pod is being deleted.

**To Reproduce**

Steps to reproduce the behavior are same as for #7683 :
1. Deploy CO
2. Deploy Kafka cluster with 3 Kafka pods and 3 ZK pods
3. Edit Zookeeper part of the Kafka CR, setting the invalid configuration
4. Check the rolling update of Zookeeper pods

**Expected behavior**

Expected behavior is, that only one ZK pod will be rolled and if the roll will not be successful, other ZK pods will not be rolled until the issue (invalid configuration) will be fixed.

**Environment (please complete the following information):**

- Strimzi version: main
- Installation method: YAML
- Kubernetes cluster: Kubernetes 1.19 and above
- Infrastructure: Minikube

**YAML files and logs**

`kubectl get pods`
```
NAME                                                 READY   STATUS    RESTARTS   AGE
my-cluster-61d4c97e-entity-operator-c85cbdb6-6grc4   3/3     Running   0          16m
my-cluster-61d4c97e-kafka-0                          1/1     Running   0          16m
my-cluster-61d4c97e-kafka-1                          1/1     Running   0          11m
my-cluster-61d4c97e-kafka-2                          1/1     Running   0          11m
my-cluster-61d4c97e-zookeeper-0                      0/1     Running   1          17m
```

kafka.yaml
 https://gist.github.com/im-konge/92cd4c9bf14fe63b2fde509e45ba16db

**Comment by scholzj** [comment]
To reproduce this, the invalid configuration needs to be in the Pod spec => e.g. memory limit smaller then memory request. Such invalid configuration will cause the Pod to be not created and not exist at all. That will make the ZooKeeperRoller to not take these _non-existent_ pods into account and roll the remaining running Pods into the same state as well until the whole ZooKeeper cluster is gone.

**Comment by scholzj** [comment]
Triaged on 12.1.2023: Should be tracked and fixed.

**Comment by fvaleri** [comment]
https://github.com/strimzi/strimzi-kafka-operator/pull/7826
