### ISSUE TITLE
Fix Javadocs in the `topic-operator` module

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7703]
By default we configure the Maven Javadoc plugin to raise any warnings as errors when validating the Javadocs in our code. That helps us to keep the comments valid and up-to-date. But Java 17 brings more strict checks for missing Javadocs. So as a result, we have lot of missing Javadoc errors. We decided to proceed with move to Java 17 and for now, we disabled the `failOnWarnings` flag for the `topic-operator` module. But we should get back to it, fix it and re-enable it again.

**Comment by ShubhamRwt** [comment]
Hi Jakub, Can I start work on this issue if its free to work upon?

**Comment by scholzj** [comment]
Well, in general, why not. But adding the Javadocs expects some kind of knowledge about what it is and what it does so that you can make sure the Javadoc makes at least little bit sense.

**Comment by ShubhamRwt** [comment]
Thanks @scholzj. I went through topic-operator code over the weekend. I will try to make the Javadoc clear and I will ask Tom B, if i get stuck somewhere

**Comment by scholzj** [comment]
Ok, great 👍
