### ISSUE TITLE
Use 'standalone' consistently in docs

### ISSUE THREAD

**Issue by ncbaratta** [strimzi/strimzi-kafka-operator#772]
Sergey Romanov [7:06 AM]
questions about word ordering... Why do we have in `Deploying the standalone User Operator` the word `standalone` before noun and in `Deploying the Topic Operator standalone` we have `standalone` after noun?

Nicole Baratta [7:19 AM]
@Sergey Romanov we should be consistent and I think it should be used as an adjective - and be standalone Topic Operator as well

**Comment by dmuntima** [comment]
I have raised a PR https://github.com/strimzi/strimzi-kafka-operator/pull/777  to ensure the consistent usage of 'standalone'.

**Comment by dmuntima** [comment]
PR https://github.com/strimzi/strimzi-kafka-operator/pull/777 addressed this issue.
