### ISSUE TITLE
Allow passing imagePullSecrets to operator as an env variable

### ISSUE THREAD

**Issue by amreshakim** [strimzi/strimzi-kafka-operator#773]
If one needs to deploy an operator with the custom Kafka and/or ZK images which for one or another reason have to be pulled from the private repo, there is no way to do it without changing the code I believe.

It would be nice to be able to specify imagePullSecrets (even if it is for both zk and kafka images) in the operator `Deployment` similar to how it allows to define a kafka image via `STRIMZI_DEFAULT_KAFKA_IMAGE` or zk image via `STRIMZI_DEFAULT_ZOOKEEPER_IMAGE`.

**Comment by sandyplace** [comment]
Just ran into this myself. Is there any workarounds?

**Comment by scholzj** [comment]
The Image pull secrets can be now specified for each pod in the `template` section of each CRD. This should address this issue. Feel free to reopen it / open a new one in case you encounter any issues.
