### ISSUE TITLE
KafkaRoller tcp probe uses incorrect host

### ISSUE THREAD

**Issue by robobario** [strimzi/strimzi-kafka-operator#7798]
In the KafkaRoller if we fail to connect an admin client connection to a broker pod (when determining if it is a controller) we try to make a TCP connection to the replication port. If that fails then we force restart the pod. I don't think the hostname we are connecting to is correct, we are connecting on `${podName}:${replicationPort}` [here](https://github.com/strimzi/strimzi-kafka-operator/blob/ef1bf282d97ecfa2ff3aa3a8ee759a11c52e9a49/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java#L803).

Debugging locally I can see that the admin client bootstraps using:
`my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc.cluster.local:9091`

But the tcp probe tries to connect using:
`my-cluster-kafka-0:9091` which doesn't resolve to anything (edit: on minikube, does this host work in other environments?)

**Comment by scholzj** [comment]
I'm not sure I follow the problem. `my-cluster-kafka-0` is valid address to be used within the healthcheck probe which runs inside the container it is checking. It is not a valid address in the KafkaRoller which runs in the Cluster Operator pod possibly in a different namespace. So this seems like a working code on both sides. While the Cluster Operator obviously requires more _work_ from DNS to route the longer address, the healthcheck probe inside the container is not tasked with probing if the DNS works or not but just with the Kafka container. So I do not think there is any reason to change it.

From your description, it is not really clear what does not work - if you use `my-cluster-kafka-0:9091` from the operator, that would be wrong and might not work in all situations. But that does not mean anything for the probe.

**Comment by robobario** [comment]
This is a connection from KafkaRoller. Maybe we are talking about different probes. I'm not talking about kubernetes probes, there is a method in KafkaRoller called `tcpProbe` making a connection from [the operator](https://github.com/strimzi/strimzi-kafka-operator/blob/ef1bf282d97ecfa2ff3aa3a8ee759a11c52e9a49/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/KafkaRoller.java#L820)

**Comment by scholzj** [comment]
Ok, that is quite confusing as _probe_ is the Kubernetes healthcheck name ;-).

That should definitely not use `my-cluster-kafka-0:9091`. The KafkaRoller should always use either `my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc.<Cluster-DNS-suffix>:9091` or just `my-cluster-kafka-0.my-cluster-kafka-brokers.myproject.svc:9091`. If it does not, feel free to open a PR as `my-cluster-kafka-0:9091` would be IMHO for sure a bug.

**Comment by robobario** [comment]
I'll get a PR together

**Comment by scholzj** [comment]
Triaged on 12.1.2023: We already have a PR for this.
