### ISSUE TITLE
System test failure due to imagePullSecret being not applied to ScraperTemplate with private image

### ISSUE THREAD

**Issue by arajguruEST** [strimzi/strimzi-kafka-operator#7822]
**Describe the bug**
Image pull secret not being applied into scraper pod when the system tests are run with private images. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Insert the docker secret into the default namespace.
2. Run a system test that deploys the scrapper in a namespace (e.g namespace-0).
3. Scrapper od can not able to pull the image from the private registry due to the secret not being injected in scraper deployment. 

**Expected behaviour**
Test to run successfully

**Environment (please complete the following information):**
 - Strimzi version: 0.32.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes & Minikube
 - Infrastructure: Minikube

**Additional context**
The command we run to test is:

`CLUSTER_OPERATOR_INSTALL_TYPE=HELM SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET=<<SECRET>> mvn -f pom.xml -Pall -B -V -Dit.test=KafkaST#testForTopicOperator -Djunit.jupiter.execution.parallel.enabled=false -Djunit.jupiter.execution.parallel.config.fixed.parallelism=1 verify`

To resolve this we had to add:
We have to add following lines in ScraperTemplate.java 
```
List<LocalObjectReference> imagePullSecrets  = new ArrayList<>();
if (Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET != null && !Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET.isEmpty()) {
            imagePullSecrets.add(new LocalObjectReference(Environment.SYSTEM_TEST_STRIMZI_IMAGE_PULL_SECRET));
        }

.withNewSpec()
       .withImagePullSecrets(imagePullSecrets)
```

**Comment by scholzj** [comment]
@im-konge @see-quick @Frawless Any ideas? ^^^

**Comment by im-konge** [comment]
Good catch, we were always using images which were public in Quay etc. so we didn't hit that.
I will add a fix for it.

Thanks for finding this @arajguruEST
