### ISSUE TITLE
[systemtest] Methods inside `KeycloakUtils` shouldn't use CO pod for API requests

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#7892]
In our `KeycloakUtils` class we are having methods for creating `GET`, `POST` or `PUT` requests to Keycloak API.
But currently we are using CO pod for doing those requests.

We should either deploy and use our `Scraper` pod (best solution) or use the Keycloak instance pod.

**Comment by im-konge** [comment]
@see-quick I guess you already fixed this, right?

**Comment by see-quick** [comment]
Yes, I have done this in some refactoring but I don't remember :) Closing this issue as done 👍
