### ISSUE TITLE
Add metrics for connector auto-restarts

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7900]
From Strimzi 0.33, we now have support for auto-restarting connectors. But right now, the information about the restarts is available only in the logs and in the status of the connector. But in the status, it might be available only for a limited time since the auto-restart status is reset if the connector is running again for some time. It would be useful to also have some metrics about the restarts. This would allow us to set up alerting or monitor it through dashboards. That would make it easier to notice if some connector is unstable for example.

Raised by https://github.com/strimzi/strimzi-kafka-operator/pull/7896#issuecomment-1380411407

**Comment by scholzj** [comment]
Triaged on 26th January 2023: This would be useful. A counter metric that would track the restarts on a per-connector basis would be useful.

**Comment by biswajit-9776** [comment]
Hello. I would like to work on this issue as a beginner. If it's okay for a beginner to start, could you please me this issue?

**Comment by scholzj** [comment]
@biswajit-9776 Yes, you can work on this. 

I guess a new counter would need to be added to `ConnectOperatorMetricsHolder` and used in the `AbstractConnectOperator` in the `autoRestartFailedConnectorAndTasks` method.

**Comment by haanhvu** [comment]
I'll work on this
