### ISSUE TITLE
Docs: Fix references to defaults picked for container images

### ISSUE THREAD

**Issue by ncbaratta** [strimzi/strimzi-kafka-operator#791]
In relation to ref-configuring-container-images.adoc

> Nicole Baratta [1:11 PM]
> In the docs in the container image section we say "When the image field is missing, the following images will be used (in the order of priority):" ... how is priority determined? Or did we mean in the order in which we list them? 
> 
> Jakub Scholz [1:12 PM]
> Yes ... that means they are listed as we take them ... if the first exists we use that, if not we move to the next

This means we should number these options as 1 and 2 and reword that statement, as it's not priority, it's in the order in which they appear below.

**Comment by dmuntima** [comment]
Fixed this issue: https://github.com/strimzi/strimzi-kafka-operator/pull/815
