### ISSUE TITLE
Use `additionalProperties` in the CRD OpenAPI spec for Maps of Strings instead of `x-kubernetes-preserve-unknown-fields`

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#7985]
As discussed in #7979, we should consider using the `additionalProperties` field instead of `x-kubernetes-preserve-unknown-fields` to improve the compatibility with other tools and be more in sync with Kubernetes spec. However, we need to keep in mind:
* That we need to stay backward compatible with existing resources
* We have places where Maps of Objects are used which should stick with ``x-kubernetes-preserve-unknown-fields`

**Comment by scholzj** [comment]
Should be triaged first to see other views!

**Comment by scholzj** [comment]
Triaged on 9.2.2023: This can be implemented, but:
* It seems like it should be used only for places where Map<String, String> is used and not where a deeper objects are (e.g. Connector status section)
* Backwards compatibility should be tested
* There is still some risk

**Comment by omjikush09** [comment]
Hi, Can I work on this?

**Comment by scholzj** [comment]
You can if you want. But I'm not sure how easy or straight forward it is TBH.

**Comment by omjikush09** [comment]
Then I don't think it's a great idea for me to work on this if I get stuck with whom I ask for help. :confused:
