### ISSUE TITLE
Kafka-zookeeper nodes temporarily unable to communicate with each other with warning message 

### ISSUE THREAD

**Issue by manishtakey** [strimzi/strimzi-kafka-operator#7989]
Kafka-zookeeper nodes temporarily unable to communicate with each other with warning message 
Do we have any fix for this issue...seems very common ? 
Zookeeper version: 3.4.13
OS: Linux 7.x on VMware 7.x
Warning message:
abc@kafkanode1::/apps/kafka/appdata/zookeeper/logs> cat server.log.2023-01-27-18 | grep GOODBYE [2023-01-27 18:31:39,071] WARN ******* GOODBYE /10.78.106.105:48920 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) [2023-01-27 18:36:48,424] WARN ******* GOODBYE /10.78.106.105:45678 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) [2023-01-27 18:41:41,568] WARN ******* GOODBYE /10.78.106.105:45810 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) [2023-01-27 18:42:30,085] WARN ******* GOODBYE /10.78.106.105:46010 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) [2023-01-27 18:46:28,760] WARN ******* GOODBYE /10.78.106.105:46040 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) [2023-01-27 18:47:05,872] WARN ******* GOODBYE /10.78.106.105:46136 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) [2023-01-27 18:47:29,403] WARN ******* GOODBYE /10.78.106.105:46164 ******** (org.apache.zookeeper.server.quorum.LearnerHandler) abc@kafkanode1::/apps/kafka/appdata/zookeeper/logs>

**Comment by scholzj** [comment]
What Strimzi and Kubernetes versions are you using? Your logs do not look like they have anything to do with Strimzi!
