### ISSUE TITLE
Running two versions of Strimzi in parallel

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#804]
Currently, it is quite hard to run two versions of Strimzi in parallel. This is mainly because the `ClusterRoles` and `ClusterRoleBindings` as global objects share the same names. So they cannot be easily deployed in parallel.

There are two possible solutions I can see right now - either name the global resources after the version to avoid these conflicts. But this adds complicates with renaming as versions change and with cleanup of these resources after the old version is not used anymore. Other option might be to simply document it and tell the users to rename it in the YAML files as we do it with namespace.

**Comment by iptrha** [comment]
Can you please add a note to the existing documentation with your suggested workarounds?
