### ISSUE TITLE
Adding STs for testing bridge authorization

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#8040]
We have `HttpBridgeScramShaST` and `HttpBridgeTlsST` bridge STs tests suites related to test the bridge authentication (with SCRAM-SHA and mTLS) against a Kafka cluster.
What we are missing are some tests related to the authorization as well, validating that bridge is able to produce and consume messages only if a corresponding `KafkaUser` is in place with the right rules.
We should add these tests.

**Comment by scholzj** [comment]
Why would you expect that to behave differently from regular Kafka clients? Or what are the Bridge specifics to test here? (E.g. some specific error codes returned by the bridge etc.)

**Comment by ppatierno** [comment]
No it would not be different compared to normal clients but I think that testing the feature when running on the bridge as a whole would make sense anyway.

**Comment by scholzj** [comment]
Well, I think we need to understand the benefits versus the cost. If it isn't really different from the existing tests what value does it add?

**Comment by ppatierno** [comment]
Yeah thinking more I see your point. In the end when we assure that the authentication is properly configured by the operator on the bridge, what comes later (the authorization) is not related to the bridge at all.
Going to close this.
