### ISSUE TITLE
Making Cruise Control configuration accessible via a ConfigMap

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#8043]
When Cruise Control is deployed by using the default configuration, this is what we have in a `Kafka` custom resource:

```yaml
cruiseControl: { }
```
The only way the user has to get which Cruise Control configuration is used is getting the corresponding `Deployment` and checking the `CRUISE_CONTROL_CONFIGURATION` env var, or accessing the pod and looking at the `/tmp/cruisecontrol.properties` file.
While it is possible, maybe it's not the best way.
For the Kafka brokers, for example, we have the configuration in a ConfigMap, I was wondering why not having a similar thing for Cruise Control.

For the record, getting the default configuration is useful when the user wants to change the hard goals for example. He would like to know the current ones in order to report them in the `cruiseControl` field but maybe stripping out some goals or adding new ones. Having the default one as a starting point is helpful instead of writing the list from scratch.

**Comment by kyguy** [comment]
Definitely worth investigating

**Comment by scholzj** [comment]
Triaged on 9.2.2023: Should be implemented. 

We should think if there is some way how to better handle the RackAware goal => e.g. disable it automatically in Cruise Control when rack awareness is not enabled in Kafka. But that should be part of a separate issue and discussion and does nto really influence if a Config Map is used to pass the configuration here.
