### ISSUE TITLE
strimzi operator crash when trying to autoRestart kafka connector

### ISSUE THREAD

**Issue by guyyakir** [strimzi/strimzi-kafka-operator#8046]
After i upgraded my environment from strimzi operator 0.25.0 to version 0.33.0, deleted all the existing CRDs and creating the new 0.33.0 CRDs, when trying to use autoRestart feature the operator crash.

it seems like the auto-restart status configuration is missing from the kafka connector configuration (only auto-restart in spec exists).

attached operator log, kafka connector and kafka connector configurations.

[strimzi-crash.log](https://github.com/strimzi/strimzi-kafka-operator/files/10611707/strimzi-crash.log)
[strimzi-crash-kc.txt](https://github.com/strimzi/strimzi-kafka-operator/files/10611708/strimzi-crash-kc.txt)
[strimzi-crash-kctr.txt](https://github.com/strimzi/strimzi-kafka-operator/files/10611710/strimzi-crash-kctr.txt)

**Comment by scholzj** [comment]
I tried to reproduce it with Debezium as well as with a specially crafted connector. But I did not manage to reproduce it. That makes it hard to fix. Can you provide some more details?
* Kafka Connect log with the failures
* Full Kafka Connector resource (including the `config` section)

**Comment by guyyakir** [comment]
Hey, in your reproduction, did the autoRestart status appear in the kafka connector after the upgrade? or is it starting to appear only after the first restart ?

**Comment by scholzj** [comment]
That would appear only after the first restart.

**Comment by guyyakir** [comment]
ill check if im able to upload the config and connect log, in the mean time i attached the crash with DEBUG log, maybe it would be helpful in some way

[strimzi-crash-debug.log](https://github.com/strimzi/strimzi-kafka-operator/files/10664848/strimzi-crash-debug.log)

**Comment by scholzj** [comment]
If I give you a custom build of Strimzi with some improved logging - can you test it somewhere?

**Comment by scholzj** [comment]
I cannot push it into the Strimzi org. But I pushed it here: `quay.io/scholzj/operator:connector-restart`. It has some improved logging.

**Comment by guyyakir** [comment]
attached the part of the crash, let me know if there is more data you need.

[strimzi-crash-debug-image.log](https://github.com/strimzi/strimzi-kafka-operator/files/10665426/strimzi-crash-debug-image.log)

**Comment by scholzj** [comment]
Thanks. That should help.

**Comment by guyyakir** [comment]
maybe it's related me upgrading from kafka 2.8.0 to kafka 3.3.2 ? 
the kafka connect image was based on quay.io/strimzi/kafka:0.25.0-kafka-2.8.0 image when i used operator version 0.25.0, while in operator version 0.33.0 the kafka connect image is based quay.io/strimzi/kafka:0.33.0-kafka-3.3.2 image.

it seems like  /restart?includeTasks=true&onlyFailed=true API wasn't supported in version 2.8.0

**Comment by guyyakir** [comment]
OK, i think i see an issue in my connect configuration, seems like i was running with kafka version 2.8.0 and not 3.3.2 . ill change and test it

**Comment by scholzj** [comment]
Right, that could be definitely related ... it would be great if you could test it.

**Comment by guyyakir** [comment]
yes this the issue. i ran with kafka 2.8.0 instead of 3.3.2, once i upgraded to kafka 3.3.2 the autoRestart works. I'm closing this ticket, maybe worth adding release note about kafka version >= 3.0.0 is needed for this feature .

thanks for the help!

**Comment by scholzj** [comment]
Oki, great. Thanks for investigating this! I will anyway have a look at improving the logging and better handling the outputs.

> yes this the issue. i ran with kafka 2.8.0 instead of 3.3.2, once i upgraded to kafka 3.3.2 the autoRestart works. I'm closing this ticket, maybe worth adding release note about kafka version >= 3.0.0 is needed for this feature .

Actually, the general expectation is that you always uses the the base image from the same Strimzi version and Kafka version. So in general, you should rebuild the image everytime it you upgrade Strimzi.
