### ISSUE TITLE
Improve the logging in `KafkaConnectApiImpl`

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8055]
It looks like the logging in `KafkaConnectApiImpl` differs significantly between different requests. For some of them, we log the communication with the Connect REST API at debug level. That seems to be useful in situations like #8046 (there it was actually missing). Should we add the same logging to all the calls to log:
* What calls are we making
* What was the outcome

**Comment by scholzj** [comment]
Triaged on 9.2.2023: Should be done for all calls at debug level as it is done currently for the GET call.

**Comment by omjikush09** [comment]
Hi, @scholzj  I would like to work on it.
Can you guide me a bit like where to find this file and any example of the outcome you expect?

**Comment by scholzj** [comment]
I think this was mentioned by someone as being worked on on Slack: https://cloud-native.slack.com/archives/CMH3Q3SNP/p1676574514792259 ... not sure about the progress. @kyguy might know.

**Comment by kyguy** [comment]
Hi @omjikush09, as Jakub mentioned someone expressed interest in working on this issue and asked for help getting started. I am happy to help as a guide if you are interested in working on contributing to Strimzi. Follow up with me on the thread Jakub mentioned above and we can get started on this issue or another.

**Comment by mimaison** [comment]
If someone is already working on this, can you assign the ticket to them?
