### ISSUE TITLE
Allow adding custom labels to kafka and zookeeper pod templates

### ISSUE THREAD

**Issue by amreshakim** [strimzi/strimzi-kafka-operator#810]
Currently, the only way to add custom labels to kafka and zookeeper pods is via kafka CRD. 

However, these labels would be inherited by all resources. In some cases (e.g., Istio, Cilium), it is desirable or even required to add specific custom labels to pods based on the service these pods belong to.

For example, something like this:

```apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: cluster-name
spec:
  kafka:
    replicas: 3
    template:
      metadata:
        labels:
         app: kafka
...
  zookeeper:
    replicas: 3
    template:
      metadata:
        labels:
         app: zookeeper```

**Comment by scholzj** [comment]
This should be implemented in PR #1039 and will be release in 0.9.0. I will close this issue now. If you have any issues or problems, feel free to re-open it or open a new issue.

**Comment by dekelmidlink** [comment]
@scholzj I can't find on the documentation how to setup custom labels for the zookeeper and kafka cluster

**Comment by AvihuHenya** [comment]
Open this question again. 
I'm currently use strimzi 0.25, what is the best way to add custom labels to the CR pods? (Kafka/Connect etc)

Trying this did not help me: 

kind: Kafka
metadata:
  name: cluster-name
spec:
  kafka:
    replicas: 3
    template:
      metadata:
        labels:
         app: kafka
...
  zookeeper:
    replicas: 3
    template:
      metadata:
        labels:
         app: zookeeper```
