### ISSUE TITLE
Update `KafkaRebalance` status if spec is changed

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#8104]
**Is your feature request related to a problem? Please describe.**
Once a `KafkaRebalance` resource is created and the status is set by the Cluster Operator, the status will never be updated again until the `KafkaRebalance` resource is "refreshed". This can lead to confusing UX when a user updates the `KafkaRebalance` spec and those changes are reflected in the `KafkaRebalance` spec but not in the `KafkaRebalance` status. The `KafkaRebalance` status will remain the same even if the `KafkaRebalance`  spec is changed, possibly leading users to think the status is related to the latest spec.

**Describe the solution you'd like**
We should have the Cluster Operator (or KafkaRebalanceOperator) automatically "refresh" the `KafkaRebalance` resource when the spec is changed.

**Describe alternatives you've considered**
I have considered two other options:

1.  Automatically update the `KafkaRebalance` status with an error when the spec changes and log an error in the Cluster Operator. However, this seems a lot more verbose than automatically "refreshing" the resource to pick up the changes.

2. Prevent the `KafkaRebalance` spec from being updated after creation, display an error that the resource must be recreated when a user attempts to update the spec. This also seems a lot more verbose than automatically "refreshing" the resource to pick up the changes.

**Comment by scholzj** [comment]
This sounds like it would deserve some more discussion during the triage on the community call.

**Comment by scholzj** [comment]
Triaged on 23.2.2023: This seems like a valid issue. But the proposed solution seems to cover only a small part of it. E.g.:
* How the spec change is detected?
* What if the spec is changed in earlier state then in `Ready`? E.g. in `ProposalReady` or `Rebalancing`?

We should try to come up with some better solution and triage it again. @kyguy and @ppatierno will think a bit more about the possible solution.

**Comment by kyguy** [comment]
> How the spec change is detected?

`KafkaRebalance` resource changes are already detected via a watch set up by the Kafka Rebalance Operator after every `KafkaRebalance` resource status change and state polling period. We would have the Kafka Rebalance Operator leverage the information in the spec for updating the Kafka rebalance request or status where appropriate.

> What if the spec is changed in earlier state then in Ready? E.g. in ProposalReady or Rebalancing?

Paolo and I brainstormed two potential solutions in more detail here:

###  (**OPTION 1**)  Auto "refresh" the KafkaRebalance resource

Kafka Rebalance Operator reads the `KafkaRebalance` resource after every status change and polling period (for states that are poll the CC API e.g. `PendingProposal` and `Rebalancing` states) This gives us an opportunity to read spec updates in every state and act on them when appropriate. This solution has the Kafka Rebalance Operator activate a `refresh`  whenever `KafkaRebalance` spec changes are detected. (with the exception of the `Rebalancing` state) Of course, we would need to slightly tweak how "refresh" are handled in every state.

Here is how the Kafka Rebalance Operator handles “refresh” requests in every state right now:

- **PendingProposal** -> ignores “refresh” request until proposal is returned, then logs a warning.
- **ProposalReady** -> requests new proposal.
- **Rebalancing** ->  ignores “refresh” request until rebalance is returned, then logs a warning. 
- **Stopped** -> requests new proposal
- **NotReady** -> requests new proposal.
- **Ready** ->   requests new proposal.

Here is how the Kafka Rebalance Operator could be updated to handle “refresh” requests in every state:

- **PendingProposal** -> stop current proposal generation, requests new proposal.
- **ProposalReady** -> request new proposal.
- **Rebalancing** -> This is a tricky one and needs more discussion,  we could:
  * Continue rebalancing but add a warning condition to the `KafkaRebalance` status and log a warning. 
  * Stop ongoing rebalance, then request a new proposal.
-  **Stopped** ->  request new proposal.
- **NotReady** ->  request new proposal.
- **Ready** ->  request new proposal.

This solution would mean that the status of the `KafkaRebalance` resource would always reflect the current spec (with the exception of the `Rebalancing` state). This saves the user from needing to manually refresh their `KafkaRebalance` resource after updating the spec.

### (**OPTION 2**)  Add a warning condition to `KafkaRebalance` status

This condition would say something like `"The spec has been updated and the KafkaRebalance resource needs to be refreshed"`. We could apply it to the status of the `KafkaRebalance` status in any of the states.  We leave it to the user to manually refresh the `KafkaRebalance` resource to pick up spec changes.

This solution requires the user to "refresh" their `KafkaRebalance` resource but it still solves the problem by notifying them that the spec has changed and the `KafkaRebalance` resource needs to be updated

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/0.33.2/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaRebalanceAssemblyOperator.java#L434

**Comment by scholzj** [comment]
Triaged on 23.3.2023: We should go with the option 1, with the variant that if the spec is changed during the `Rebalancing` state, the rebalance will be canceled and new proposal will be requested.

**Comment by ppatierno** [comment]
> with the variant that if the spec is changed during the Rebalancing state, the rebalance will be canceled and new proposal will be requested.

This will be not impossible but not trivial. Stopping a rebalance means anyway waiting for the current rebalancing operation batch to end first. Only when it ends, it will be possible to request a new proposal. I think it should be clarified at least with a warning in the operator log.
