### ISSUE TITLE
How to expose kafka to outside world

### ISSUE THREAD

**Issue by Mikedu1988** [strimzi/strimzi-kafka-operator#812]
Hi,
I recently deployed strimzi-0.5.0 in openshift-origin-3.10.
And I cant expose kafka to outside world.
I've tried LoadBalancer, and no luck 

Any help is appreciated.

**Comment by scholzj** [comment]
I'm afraid that this is not yet supported - see #128. I hope to have some time to work on this during September.

**Comment by Mikedu1988** [comment]
Ok, then I'm closing this. wait for your good news
