### ISSUE TITLE
outdated documentation about standalone user-operator mtls configuration

### ISSUE THREAD

**Issue by karolcienkosz** [strimzi/strimzi-kafka-operator#8125]
**Suggestion / Problem**
Update documentation about mlts configuration for user-operator

based on [1] standalone user-operator cannot be started. It tries to load empty key from k8s secret and base64 decode function fails with exception.

I've checked code[2] and when in secret under .crt and .key keys are stored cert and key in PEM format, operator start and is able to connect  to external kafka cluster.

**Documentation Link**
[1]https://strimzi.io/docs/operators/latest/deploying.html#deploying-the-user-operator-standalone-str
[2]https://github.com/strimzi/strimzi-kafka-operator/blob/d09f4eddeb62cacc66fc478d00c43216be0aedcf/operator-common/src/main/java/io/strimzi/operator/common/DefaultAdminClientProvider.java#L56

**Comment by scholzj** [comment]
Is this part what you mean by being wrong in the first link?

```
            - name: STRIMZI_CA_CERT_NAME (3)
              value: my-cluster-clients-ca-cert
            - name: STRIMZI_CA_KEY_NAME (4)
              value: my-cluster-clients-ca
```

**Comment by karolcienkosz** [comment]
> Is this part what you mean by being wrong in the first link?
> 
> ```
>             - name: STRIMZI_CA_CERT_NAME (3)
>               value: my-cluster-clients-ca-cert
>             - name: STRIMZI_CA_KEY_NAME (4)
>               value: my-cluster-clients-ca
> ```
I mean about:
```
env:
  - name: STRIMZI_CLUSTER_CA_CERT_SECRET_NAME (1)
    value: my-cluster-cluster-ca-cert
  - name: STRIMZI_EO_KEY_SECRET_NAME (2)
    value: my-cluster-entity-operator-certs
# ..."
```

and especially about:
`2. The Kubernetes Secret that contains the keystore (entity-operator.p12) with the private key and certificate for mTLS authentication against the Kafka cluster. The Secret must also contain the password (entity-operator.password) for accessing the keystore.`

Now, based on [2] and tests it should be .key a .cert in PEM format

**Comment by karolcienkosz** [comment]
And information about STRIMZI_KRAFT_ENABLED env should be added in my case (kraft, zookeeper-less) it has to be set.

**Comment by scholzj** [comment]
@karolcienkosz I opened #8149 to address both of the points. Feel free to have a look and comment here or on the PR. Thanks.
