### ISSUE TITLE
Generate network policies for Kafka Exporter and Entity Operator

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8177]
Today, Strimzi generates network policies only for components where it is connecting to itself such as Zoo, Kafka, or Cruise Control. In these policies, we allow everyone to access the metrics. However, for other components such as Kafka Exporter or Entity Operators, where the Cluster Operator doesn't connect we do not create any network policies.

So when users use deny-by-default network policies and deploy Kafka Exporter or Entity Operator, they are sometimes surprised that they cannot access the metrics on EO or KE without creating manually a corresponding network policy while they can do the same easily on Zoo, Kafka, or CC.

We should consider if we want to create some out-of-the-box network policies to allow access to the metrics also for KE and EO. This would make it less confusing for users.

The downside is that once we make the metrics port wide open, it is not easy to close it. The only option is to disable the operator from managing the network policies using an environment variable and then managing the policies manually for all components. But this might not be an issue, since if anyone has a problem with the KE and EO metrics being accessible, they probably anyway already do this for the other components.

This should be triaged before implementation. If it is implemented, do not forget that the network policy management should follow the flag for disabling them. We should also consider the backward compatibility implications of this.

**Comment by scholzj** [comment]
Triaged on 9.3.2023: We should add the network policies for KE and EO to open access to the metrics by default.

**Comment by omjikush09** [comment]
will work on this..
