### ISSUE TITLE
[systemtest] Delete few tests from `KafkaST`

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#8257]
We should delete few tests inside `KafkaST`, which are checked in UTs/ITs or are duplicates of other tests:

- `testCustomAndUpdatedValues` - liveness and readiness part can be tested on UT level
- `testEntityOperatorWithoutTopicOperator` - duplicate of `testRemoveTopicOperatorFromEntityOperator`
- `testEntityOperatorWithoutUserOperator` - duplicate of `testRemoveUserOperatorFromEntityOperator`
- `testEntityOperatorWithoutUserAndTopicOperators` - duplicate of `testRemoveUserAndTopicOperatorsFromEntityOperator`
- `testKafkaJBODDeleteClaimsTrue` - duplicate of `testKafkaJBODDeleteClaimsTrueFalse`
- `testKafkaJBODDeleteClaimsFalse` - duplicate of `testKafkaJBODDeleteClaimsTrueFalse`
- `testPersistentStorageSize` - covered in UTs/ITs
- `testConsumerOffsetFiles` - can be merged into another test or simply removed

**Comment by Frawless** [comment]
Test comment to verify CI changes

**Comment by Frawless** [comment]
Test comment to verify CI changes

**Comment by Frawless** [comment]
Test comment to verify CI changes

**Comment by Frawless** [comment]
Test comment to verify CI changes

**Comment by Frawless** [comment]
Test comment to verify CI changes

**Comment by Frawless** [comment]
Test comment to verify CI changes
