### ISSUE TITLE
Remove support for PodDisruptionBudget v1beta1

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8290]
**Note: This should be implemented only after the 0.35.0 release which drops support for Kubernetes 1.19 & 1.20!**

Today, Strimzi supports PodDisruptionBudgets v1beta1 and v1. PodDisruptionBudget v1 has been introduced in Kubernetes 1.21. So once we drop support for Kube 1.19 and 1.20, we can also remove support for PDB v1beta1.

**Comment by scholzj** [comment]
This can be now worked on if anyone is interested since 0.35 release is branched.

**Comment by MikeEdgar** [comment]
I can take a look at this.

**Comment by scholzj** [comment]
@ShazaAldawamneh is already working on this.
