### ISSUE TITLE
[Enhancement]: Allow TLS connections to Kafka exporter

### ISSUE THREAD

**Issue by Kartikey-Mishra1** [strimzi/strimzi-kafka-operator#8312]
### Related problem

Currently the metrics port in Kafka exporter does not support tls encypted connections ([these](https://github.com/strimzi/strimzi-kafka-operator/blob/171c13ecaaa290d84491d7a727919146340674aa/docker-images/kafka-based/kafka/exporter-scripts/kafka_exporter_run.sh#L43) are the current configs). Ability to communicate with Kafka exporter over tls would allow [spec.endpoints[].tlsConfig](https://docs.openshift.com/container-platform/4.10/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html#spec-endpoints-tlsconfig) and [.spec.podMetricsEndpoints[].tlsConfig ](https://docs.openshift.com/container-platform/4.10/rest_api/monitoring_apis/podmonitor-monitoring-coreos-com-v1.html#spec-podmetricsendpoints-tlsconfig) configs to be used in Service monitors and Pod monitors. 

### Suggested solution

Server certificates and keys can be configured in Kafka exporter by running the kafka exporter image with `server.tls.XXX` flags(more info can be found [here](https://github.com/danielqsj/kafka_exporter#flags)). If this feature request is accepted any suggestions on how the required certificates and keys can be generated are welcome(could be similar to how it's done for cruise control but this is not my area of expertise).

 A new config under `spec.kafkaExporter` section might have to be introduced to allow users to specify if they would like to enable TLS encrypted communication, something similar to below:

```
spec:
  kafkaExporter:
    enableTLS: true   
```

**Comment by scholzj** [comment]
You should probably explain the use-case => why would this be useful (also in the context of all other metrics endpoints being unencrypted).

**Comment by scholzj** [comment]
Triaged on 6.4.2023: This does not seem to make much sense in the context of all the other metrics endpoints which do not have any encryption. It is also not as straight forward as this issue makes it sounds -> one would need to generate the certificates and maintain them, probably provide ways to configure the SANs etc.
