### ISSUE TITLE
Cruise Control configuration should be passed in a ConfigMap instead of environment variable

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8337]
Currently, the Cruise Control configuration with the JSN describing the capacity configuration of the different nodes is passed to CC in an environment variable `CRUISE_CONTROL_CAPACITY_CONFIGURATION`. The same should apply to `CRUISE_CONTROL_CONFIGURATION` with the configuration. They are both already quite big, so using a Config Map would be much better.

**Comment by ppatierno** [comment]
Is this somehow related to this one https://github.com/strimzi/strimzi-kafka-operator/issues/8043
Maybe we could close that one and stay with this.

**Comment by scholzj** [comment]
Triaged on 6.4.2023: Should be done and this should be a good-start issue.

**Comment by Thealisyed** [comment]
Hey @scholzj and @ppatierno looking to take on this issue if that's ok?

**Comment by scholzj** [comment]
I think that should be fine, yes.

**Comment by ppatierno** [comment]
Fine with me!

**Comment by scholzj** [comment]
Done in #8977
