### ISSUE TITLE
[DOC] Clarify the use of `minAvailable` in `PodDisruptionBudget` resources

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8369]
When using StrimziPodSets, we cannot use `maxUnavailable` field in the Pod Disruption Budget settings as that is not allowed with custom controllers (which StrimziPodSets are). So we have to convert it to `minAvailable`. Since we know the number of pods the StrimziPodSets creates, we can simply calculate the `minAvailable` field. E.g.
* With 3 pods and `maxUnavailable` field configured to be set to 1, we set `minAvailable` to 2 (i.e. allowing one pod to be unavailable)
* With 0 pods and `maxUnavailable` field configured to be set to 0, we set `minAvailable` to 0 (i.e. allowing zero pod to be unavailable)

But the configuration option available to the users is still only `maxUnavailable`. This seems a bit confusing sometimes in the docs around the Drain Cleaner and in the docs around the `maxUnavailable` option in the PodDisruptionBudget template. We should try to clarify it there.

**Comment by PaulRMellor** [comment]
Discussed 2023/04/20

We need to change the docs as follows:
 * Update the [PodDisruptionBudgetTemplate schema reference](https://strimzi.io/docs/operators/latest/configuring.html#type-PodDisruptionBudgetTemplate-reference)  to explain that when configuring maxUnavailable the operator recalculates as  minAvailable, with examples and rationale.
 * Update the following sections to explain what happens with the maxUnavailable set at zero:
     * [Deploying the Strimzi Drain Cleaner using installation files](https://strimzi.io/docs/operators/latest/full/deploying.html#proc-drain-cleaner-deploying-str)
     * [Rolling pods using the Strimzi Drain Cleaner](https://strimzi.io/docs/operators/latest/full/deploying.html#rolling_pods_using_the_strimzi_drain_cleaner)
    * [Rolling pods manually while keeping topics available](https://strimzi.io/docs/operators/latest/full/deploying.html#rolling_pods_manually_while_keeping_topics_available)

NOTE: Look at the distribution of the drain cleaner doc. Maybe bring it all together now that the content is all in the deploying guide. At least, review the position of the install section.

**Comment by scholzj** [comment]
Triaged on 20.4.2023: @PaulRMellor is looking into this already.
