### ISSUE TITLE
[Enhancement]: [helm] grafana dashboards

### ISSUE THREAD

**Issue by jcpunk** [strimzi/strimzi-kafka-operator#8390]
### Related problem

It would be nice if the heml chart contained some optional grafana dashboards with "some useful information" that I could load via the grafana sidecar container.

### Suggested solution

Find some community dashboards folks like and add them to the chart

### Alternatives

Something home grown

### Additional context

the grafana side car is able to load config maps with a specified label and specified annotations into the container by default.

**Comment by scholzj** [comment]
How does Helm install Grafana dashboards?

**Comment by scholzj** [comment]
> Find some community dashboards folks like and add them to the chart

PS: We have Grafana dashboards in examples.

**Comment by jcpunk** [comment]
I was thinking about something similar to what is going on in kube-prometheus-stack : https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana

**Comment by scholzj** [comment]
Where are the JSONs with the Dashboards there? I do not see any there. Also, what exactly is loading the dashboards? I normally use some Grafana operator and load dashboards through custom resources. So I never used anything to do it from a ConfigMap - so it is not really clear to me how is it expected to work.

**Comment by jcpunk** [comment]
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/grafana-overview.yaml is probably the most direct example.  The dashboard json is passed as a value to a file in a config map.

https://ranchermanager.docs.rancher.com/v2.5/how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard https://johnharris.io/2019/03/dynamic-configuration-discovery-in-grafana/ have short descriptions of the process.

The official grafana container has a side car that looks for a specified label, (default is `grafana_dashboard=1`) and annotation (no default).  That sidecar mounts the configmaps it finds in a directory based on the annotation and then the container picks it up.

Since you've got example dashboards, I may try to whip up a patch in the next few days.  I didn't seem them when I was looking around.

**Comment by scholzj** [comment]
> https://ranchermanager.docs.rancher.com/v2.5/how-to-guides/advanced-user-guides/monitoring-alerting-guides/create-persistent-grafana-dashboard https://johnharris.io/2019/03/dynamic-configuration-discovery-in-grafana/ have short descriptions of the process.

So, it is a special feature of Rancher?

**Comment by jcpunk** [comment]
This is a feature builtin to the official grafana helm chart.

**Comment by jcpunk** [comment]
My initial thoughts were to do something like what I did for cilium : https://github.com/cilium/cilium/blob/master/install/kubernetes/cilium/templates/cilium-agent/dashboards-configmap.yaml

but I'm not sure how to get the dashboards into the helm area...

**Comment by scholzj** [comment]
I guess you would need to add it somewhere to the Make files. There are already targets such as `crd_install` which copy CRDs to the Helm chart. So I guess we could add something similar for the dashboards. Lets triage this first on the next community call and I can point you to the current Make steps and/or help you with the new ones.

**Comment by scholzj** [comment]
Triaged on 20.4.2023: Seems like a useful idea. It should be as optional so that the dashboards are not created for everyone by default but only when enabled.
