### ISSUE TITLE
[Bug]: Update Kafka User sample in OCP console to use the new operations field  

### ISSUE THREAD

**Issue by Kartikey-Mishra1** [strimzi/strimzi-kafka-operator#8413]
### Bug Description

The Kafka User sample that shows up in the OCP console seems to be using the `operation` field that has been deprecated in favour of the new `operations` field.   

### Steps to reproduce

1. Install the latest Strimzi Operator on an Openshift cluster.
2. After the operator is installed successfully click on Strimzi under Installed operators to enter the operands section and navigate to `Kafka User` heading.
3. Click on `createKafkaUser` and the below Kafka user sample file should appear.  

![](https://user-images.githubusercontent.com/36034999/233020344-2048c35b-1eb5-4d85-98bd-8dcb341734c3.png)

### Expected behavior

The above sample should use the new operations field.

 

### Strimzi version

0.34.0

### Kubernetes version

Openshift 4.11

### Installation method

OperatorHub.io

**Comment by scholzj** [comment]
Triaged on 20.4.2023: Should be fixed in the next Strimzi release (0.35.0 or 0.34.1 if there is a patch release).

**Comment by scholzj** [comment]
Should be addressed in https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/2660 as part of 0.35.0 release.
