### ISSUE TITLE
Forcing CA cert renewal from old Strimzi 0.6.0 Secret seems not necessary anymore

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#8420]
Currently in both `ClientsCa` and `ClusterCa` we are calling the super `Ca` constructor by forcing a renewal for the CA cert because of coming from old Strimzi 0.6.0 version.
You can see this happening [here](https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ClusterCa.java#L96) and [here](https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/main/java/io/strimzi/operator/cluster/model/ClientsCa.java#L39) through the [`forceRenewal`](https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/main/java/io/strimzi/operator/cluster/model/Ca.java#L193) method.
I would assume it's not needed anymore because of the pretty old 0.6.0 version it was for.

@scholzj wdyt? I you agree I would open a trivial PR to remove that.

**Comment by scholzj** [comment]
Yeah, I guess we do not need to be worried about upgrade from Strimzi 0.6.0.
