### ISSUE TITLE
[Enhancement]: upgrading ZooKeeper to a newer version

### ISSUE THREAD

**Issue by MantasMiksys** [strimzi/strimzi-kafka-operator#8435]
### Related problem

Currently, the latest version of Strimzi (0.34.0) uses rather old version of ZooKeeper (3.6.3). Some fixes (including some CVE fixes) were made to ZooKeeper 3.6.4 and also 3.6.* is EoL since 30th of December 2022 ([link](https://zookeeper.apache.org/releases.html)).

### Suggested solution

Could we upgrade to the latest stable release of ZooKeeper (3.7.1)?

**Comment by scholzj** [comment]
ZooKeeper is part of Apache Kafka distribution. So any upgrade to ZooKeeper version should be done as part of Apache Kafka itself (I believe some discussions are already happening in the Apache Kafka community).
