### ISSUE TITLE
[Bug]: Wrong digest of the Cluster Operator Helm Chart in the `index.yaml`

### ISSUE THREAD

**Issue by nashton** [strimzi/strimzi-kafka-operator#8437]
### Bug Description

The digests/hash for strimzi-kafka-operator charts specified in the helm repositories index.yaml file, does not match for any of the released strimzi-kafka-operator chart files.

### Steps to reproduce

1. Go to https://strimzi.io/charts/index.yaml and get the digest for strimzi-kafka-operator version 0.34.0
2. Download https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.34.0/strimzi-kafka-operator-helm-3-chart-0.34.0.tgz
3. Run the command `sha256sum strimzi-kafka-operator-helm-3-chart-0.34.0.tgz`

The digests does not match

### Expected behavior

Expected the digests to match

### Strimzi version

any

### Kubernetes version

any

### Installation method

Helm Chart

### Infrastructure

any

### Additional context

The hash is not the same, because the release procedure generates the helm chart twice, which will always have different hashes. Once by the Makefile, for creating the index.yaml file, and then again in a separate step in the Github CI, for publishing the charts to Github. The same tgz file must be used for generating the index.yaml file and for the actual publishing.

**Comment by scholzj** [comment]
Note: The PR related to this issue should make sure the digests are correct from the next release (0.35.0) -> it does not fix the previous releases.
