### ISSUE TITLE
Integrate with Service Catalog provisioning and binding

### ISSUE THREAD

**Issue by ron1** [strimzi/strimzi-kafka-operator#844]
Service Catalog should be able to provision/deprovision Strimzi Kafka Operator. Also, consider integrating User Operator-based user management with Service Catalog binding. Would it make sense to start with a helm2bundle-based Strimzi APB?

**Comment by scholzj** [comment]
TBH, I do not think this is currently high on our TODO list. I do not think the service broker really fits that well currently with the operator concept. What advantages would you expect from it?

There is already an existing version of  a Strimzi APB - [](https://github.com/matzew/strimzi-apb). But I'm not sure how up to date it is. I think it also doesn't support binding of users or topics to applications. But I'm sure you could contribute to that if you are interested.

PS: We also have some templates to provision the different resources - they can be installed into the Service Catalog. But in general the templates in OpenShift is fairly weak tool which offers only limited possibilities for configuration.

**Comment by ron1** [comment]
At a minimum, I'm looking for a standard way to provision the Strimzi Operator just like I provision other services. I prefer to use the Service Catalog for this purpose rather than Helm/Tiller or pre-processing templates with sed commands. The Service Catalog provides a nice UX to locate available services, provision those services, and capture service provisioning parameters. I think the instructions for "Deploying the Cluster Operator to watch multiple namespaces" in particular have enough complexity to justify use of an APB, especially for a first-time user. When an APB is used, the APB parameters map to Operator CRD properties for a simple, friendly day one user experience. As far as binding is concerned, Service Catalog binding with credentials remapping provides a standard, decoupled way for clients to use secrets to connect with various backing service types. Until the Operator framework provides a comparable user experience for managing bindings (which I consider a day two function), continued use of the Service Catalog for this purpose seems to make sense to me.

**Comment by scholzj** [comment]
Ok, thanks for your explanation. I appreciate it. Lets keep this open and see when we get to it.

**Comment by ron1** [comment]
Note that Service Catalog PodPresetBindings are under development here: https://github.com/jpeeler/podpresetbinding-crd. The goal for PodPresetBindings CRD ..."is to provide an easy method for synchronizing a given deployment with binding credentials that are eventually made ready by service-catalog." ..."The reconcile loop in this repository is responsible for handling creation and updates of pod preset resources based on the spec of a podpresetbinding. The podpreset CRD reconcile loop handles restarting deployments for which pod presets have mutated."

PodPresetBindings are currently defined in the context of the Service Catalog. Do you know if Operators/the Operator Framework aspire to offer comparable functionality? If so, I am not aware of it.

It seems reasonable to me that the Service Catalog would provision/bootstrap the strimzi-kafka-operator much like a Tiller-less Helm Chart install. After the initial provision, client apps would bind to the ServiceCatalog ServiceInstance which would in turn interact with the strimzi UserOperator to create the user and secret. Finally the user and secret would be associated with the ServiceBinding. In the future when an operator initiates a cert recycle, the ServiceCatalog PodPresetBinding would be updated resulting in client app deployment restarts. Again, I'm not sure if Operators have intentions to provide this functionality themselves or if they will delegate this functionality to the Service Catalog. Or maybe service meshes will evolve to solve this problem. Regardless, the Service Catalog seems to have the most mature solution today for solving some of these binding problems.

**Comment by ron1** [comment]
An alternative way to use the Service Catalog with Strimzi embraces your suggestion that "...I do not think the service broker really fits that well currently with the operator concept." Here, the Service Catalog "provision" action would simply deploy the strimzi-kafka-operator, duplicating the exact same functionality as provided by the existing helm-chart install. The ServiceInstance would be associated with the cluster-operator. This would provide a very OpenShift-friendly way to install/bootstrap the operator. It could also provide an easy way to "run two versions of Strimzi in parallel" by accepting a name discriminator as a parameter. The "deprovision" action would remove the strimzi-kafka-operator and all its resources. The "deprovision" would fail if one or more Kafka clusters exist.

In this scenario, the Strimzi operators themselves would be used as documented to manage clusters, topics, users, etc. The Service Catalog "bind" action would accept a cluster-name and user-name as parameters. The "bind" would create a ServiceBinding associated with the specified Kafka Cluster's Kafka User's Secret. The "bind" would fail if the cluster or user do not already exist.

This proposed usage of the Service Catalog is non-traditional. But it does separate Service Catalog concerns from Operator concerns in a reasonable manner and allows the Service Catalog to continue to be used for Operator installations as well as client application credentials mapping. WDYT?

**Comment by scholzj** [comment]
Triaged on 22.02.2022: The operator provisioning is done with OLM / Operator Hub if some automation other than Helm is needed. The service Binding is developed in the form of the [KafkaAccess operator](https://github.com/strimzi/kafka-access-operator). This issue should be closed.
