### ISSUE TITLE
[Bug]: s390x pipelines failing for ZkTopicStoreTest

### ISSUE THREAD

**Issue by yasiribmcon** [strimzi/strimzi-kafka-operator#8441]
### Bug Description

Since https://github.com/strimzi/strimzi-kafka-operator/pull/8330 has enabled a new test case, our s390x [pipelines](https://148.100.84.211/job/strimzi-kafka-operator/job/Strimzi_Kafka_Operator_ST/) are failing due to failing test case **_ZkTopicStoreTest.testCrud(VertxTestContext)_**.

Problem looks like **_CompletableFuture_** is not waiting for zookeeper topic store to be initialised, future.get() is **not** blocking until complete topic store initialisation and it returns instantly. Reason for this behaviour is most likely that ZK topic store creation(which itself is running on a vertx event loop asynchronous thread) is **_asynchronous_** as it leaves the topic store creation to ZkImpl's worker thread due to which `new ZkTopicStore(zkClient, "/strimzi/topics")` returns immediately without the store being actually ready.

So when **_testCrud_** test case goes to create a topic in this unready topic store, its gets `org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /strimzi/topics/my_topic_1549042347` exception.

This behaviour is same for intel and s390x, but when i tested on my intel machine, even without the use of completablefuture, topic store is still getting ready naturally, like it worked on committer's machine but CI/CD failed for them(Please refer [here](https://github.com/strimzi/strimzi-kafka-operator/pull/8330#issuecomment-1491968623) for details), hence this error may not be visible on some intel machines.Also I believe s390x is processing test suite much faster(takes half the time as compared to intel) w.r.t intel due to which this issue is surfacing more consistently in s390x machines.

Please note that this test case seems to be failing only during **_integration_** testing and **_not_** if we unit test it.

The only workaround I could come up with was replacing the completablefuture code with a sleep of atleast **_10ms_** in the test case setup phase, but i would prefer if there was a dynamic solution to this problem like waiting on the actual topic store initialisation. I believe committer also intended to use CompletableFuture for the same cause but he/she did not test his/her changes well enough as test case was not failing on their machine.

For more clarity, I am sharing logs for the failing test case where i have introduced debug messages to show code sequence with time(in ms) in different scenarios.
Intel : [SKO_Intel.txt](https://github.com/strimzi/strimzi-kafka-operator/files/11340730/SKO_Intel.txt)
S390X Failing : [SKO_Fail_s390x.txt](https://github.com/strimzi/strimzi-kafka-operator/files/11340770/SKO_Fail_s390x.txt)
S390X Passing : [SKO_Pass_s390x.txt](https://github.com/strimzi/strimzi-kafka-operator/files/11340773/SKO_Pass_s390x.txt)
Changes done to add debug messages : [SKO_Add_Debug_Msg.txt](https://github.com/strimzi/strimzi-kafka-operator/files/11341145/SKO_Add_Debug_Msg.txt)

Please advise.

### Steps to reproduce

Run integration test using `mvn -f topic-operator/pom.xml  -Dit.test=io.strimzi.operator.topic.ZkTopicStoreTest verify`

### Expected behavior

CompletableFuture waits for zookeeper topic store initialization before moving ahead with test case execution.

### Strimzi version

main

### Kubernetes version

Kubernetes 1.23.3

**Comment by scholzj** [comment]
@fvaleri Any ideas?

**Comment by yasiribmcon** [comment]
Thanks a lot @fvaleri !
Changes are working great on my local s390x machine.
Will update once s390x pipelines start passing.

**Comment by fvaleri** [comment]
Looks like it is also working on the s390x pipeline.

```sh
[INFO] Running io.strimzi.operator.topic.ZkTopicStoreTest
2023-05-03 11:12:43 [ZOOKEEPER] WARN  ServerCnxnFactory:309 - maxCnxns is not configured, using default value 0.
2023-05-03 11:12:43 INFO  ZkEventThread:65 - Starting ZkClient event thread.
2023-05-03 11:12:43 INFO  ZkClient:936 - Waiting for keeper state SyncConnected
2023-05-03 11:12:43 INFO  ZkClient:713 - zookeeper state changed (SyncConnected)
2023-05-03 11:12:43 INFO  ZkEventThread:83 - Terminate ZkClient event thread.
2023-05-03 11:12:43 [ZOOKEEPER] WARN  ClientCnxn:1294 - An exception was thrown while closing send thread for session 0x100778c281a0000.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: Unable to read additional data from server sessionid 0x100778c281a0000, likely server has closed socket
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:77) ~[zookeeper-3.6.3.jar:3.6.3]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:350) ~[zookeeper-3.6.3.jar:3.6.3]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1290) ~[zookeeper-3.6.3.jar:3.6.3]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.256 s - in 
```

**Comment by yasiribmcon** [comment]
Thanks @fvaleri !
Pipeline is passing now : https://148.100.84.211/job/strimzi-kafka-operator/job/Strimzi_Kafka_Operator_ST/448/
