### ISSUE TITLE
`KafkaTopic` without `.spec` section should not be silently ignored

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8465]
### Discussed in https://github.com/orgs/strimzi/discussions/8463

----

It looks like in the `KafkaTopic` CR, the `.spec` section is not required and users can create the resource without it. However, the operator seems to check it in the `K8sTopicWatcher` class and when it is missing, it silently ignores it. I think it is fine to not process such a resource, but we should at least throw a warning and not skip such a resource silently.

**Comment by scholzj** [comment]
Triaged on 4.5.2023: We should log a warning when the Topic Operator runs into such KafkTopic without the `.spec` section so that the user is aware of it.

**Comment by mabulgu** [comment]
I am gonna have a look at this one. @scholzj could you pls assign me to this issue?

**Comment by mabulgu** [comment]
Getting on it today. Sorry for the latency
