### ISSUE TITLE
[Bug]: Changing the cluster label on a KafkaUser changes the secret, but does not remove ACLs from the old cluster

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#8466]
### Bug Description

Admittedly this is a strange user flow, but recently a client of ours created a KafkaUser with `strimzi.io/cluster: old-cluster` they then wanted to use that KafkaUser for a new cluster in the same namespace, instead of deleting the KafkaUser and then recreating it with the new cluster label, they just patched it with `strimzi.io/cluster: new-cluster` as you might expect, it patched the secret with the new cluster, and was setup correctly, however the ACL's don't get removed from the old-cluster, since it never saw the KafkaUser get deleted.

### Steps to reproduce

1 - Install two `Kafka`'s in the same namespace
2 - Create any KafkaUser for cluster 1 with cluster label
3 - Patch KafkaUser to use cluster 2 in cluster label

### Expected behavior

The expected behaviour should be that changing the cluster label is semantically the same as a delete and so the ACLs are removed from the old-cluster, however this may be difficult to figure out at runtime.
Some suggested fixes:
- check the last modified and if label is different, do a delete for the old-cluster ACLs
- check if any other kafka clusters are in the namespace and if so, delete any ACLs not accounted for

### Strimzi version

0.32.0

### Kubernetes version

OpenShift 4.11

### Installation method

OperatorHub

### Infrastructure

Bare-Metal

### Configuration files and logs

Can be provided if needed but behaviour seems clear without

### Additional context

I know this flow seems strange, raising as a bug, but could be seen as a feature request.
Potential fixes may be difficult to implement so I understand if this is low priority.
If you think Strimzi just does not want to fully support patching of the cluster label (as the ACLs remain) I would be more than happy to close this issue as not a bug.

**Comment by scholzj** [comment]
The operator was basically completely rewritten in 0.33. So it would be worth checking this with 0.33 or 0.34.

I think the general expectation is that it:
* It should see the deletion (as by changing the label it is essentially deleted from the informer)
* And even if if does not see the deletion, the periodical reconciliation should delete it sooner or later

While any bugs might be different between the old and new designs, I think these expectations should be the same. So it suggests some bug in the code.

**Comment by samuel-hawker** [comment]
Thanks for the prompt response Jakub, we will check this now against 0.34 and see if it still persists.
Will close this if we confirm it is fixed.

**Comment by samuel-hawker** [comment]
I can confirm on 0.34.X this is fixed. Thanks for the assistance.

**Comment by scholzj** [comment]
Great, thanks for confirming @samuel-hawker
