### ISSUE TITLE
Pods failed to start. version 0.6.0

### ISSUE THREAD

**Issue by jihed** [strimzi/strimzi-kafka-operator#851]
Hello team,

I am trying to deploy the kafka operator on OCP over GCP using persistent template.
Pair of kafka/zk keep crashing and rebooting. It complains that the pv was not mount.

oc describe pod my-cluster-kafka-2
 3h            1m              100     kubelet, ocp-app-0                      Warning         FailedMount             Unable to mount volumes for pod "my-cluster-kafka-2_strimzi-060d(abd0442f-a7bc-11e8-b631-42010a2c5a03)": timeout expired waiting for volumes to attach/mount for pod "strimzi-060d"/"my-cluster-kafka-2". list of unattached/unmounted volumes=[data]

However, the pv/pvc are bound and attached to the node:
oc get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                                      STORAGECLASS   REASON    AGE
pvc-bf8672a7-a7b7-11e8-b631-42010a2c5a03   1Gi        RWO           Delete          Bound     strimzi-060d/data-my-cluster-kafka-2       ssd                

[root@ocp-app-0 abd0442f-a7bc-11e8-b631-42010a2c5a03]# df -h |grep pvc-bf8672a7-a7b7-11e8-b631-42010a2c5a03
/dev/sdg       1014M   33M  982M   4% /var/lib/origin/openshift.local.volumes/plugins/kubernetes.io/gce-pd/mounts/kubernetes-dynamic-pvc-bf8672a7-a7b7-11e8-b631-42010a2c5a03

[root@ocp-app-0 abd0442f-a7bc-11e8-b631-42010a2c5a03]# tree volumes/
volumes/
...
├── kubernetes.io~gce-pd
│   └── pvc-bf8672a7-a7b7-11e8-b631-42010a2c5a03
│       └── kafka-log2
│           ├── cleaner-offset-checkpoint
│           ├── log-start-offset-checkpoint
│           ├── meta.properties
│           ├── recovery-point-offset-checkpoint
│           └── replication-offset-checkpoint
...
Kindest Regards,
JM

**Comment by scholzj** [comment]
This sounds more like some OCP or GCP issue TBH. From the event it sounds like OpenShift doesn't start the pod because the volume is not mounted. The mounting of the volumes is fully up to OpenShift and GCP. We just use the OpenShift resources to tell them what we want.

Could you try to reboot the node?

**Comment by jihed** [comment]
It's the same behavior evern with rebooting the node.
GCP created the disk and attached to the node where the pod is runnig.
OCP bond the pvc/pv and I see the pv is available inside the pod.
