### ISSUE TITLE
[Enhancement]: Availability to configure nodeSelector at podLevel 

### ISSUE THREAD

**Issue by javiercri** [strimzi/strimzi-kafka-operator#8518]
### Related problem

Kubernetes allows to configure `scheduler.alpha.kubernetes.io/node-selector` at namespace level https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#configuration-annotation-format. Strimzi just allow `nodeAffinity` and `podAffinity` but pods are unable to schedule if you set up a node-selector at namespace level and try to overwrite using nodeAffinity. 
Right now, kubernetes API is overwriting strimzi pod if annotation is present in namespace and schedule this pod in this nodeGroup, so with namespace annotation it is impossible to use `nodeAffinity`. 

### Suggested solution

Create nodeSelector field in podTemplate https://strimzi.io/docs/operators/latest/configuring.html#type-PodTemplate-schema-reference
With this we are able to overwrite namespace annotation at pod level

**Comment by scholzj** [comment]
My understanding is that node selectors are inferior to affinity and affinity should be used instead as a newer and more advanced and rich feature. Is that not the case? 

Supporting everything like this means some effort to build it and ongoing maintenance effort. So we need to carefully consider if this really makes sense or not.

----

The Kubernetes docs also suggest that the admission controller enforces the node selector -> so why does it need to be configured? It sounds to me like if it is not set in the pod it is injected. If it is set to the same value as the namespace has, it is all ok. And if it is set to some other value it is rejected. So you anyway cannot customize it.

**Comment by scholzj** [comment]
Triaged on 1.6.2023: No feedback so far, let's wait another two weeks if we hear back.

**Comment by tombentley** [comment]
Triaged on 15/06/2023: No additional background/context/use case has been provided, so we going to close this. It can be reopened if if those use cases are provided.

**Comment by Seljuke** [comment]
i would like this issue to be reopened. For my use case, we are using karpenter with custom provisioners with 
```
- key: infraNode
  operator: Exists
``` 
requirement to create kinda on demand nodegroups. For this reason we need to always set `nodeSelector` in our pod templates.

**Comment by scholzj** [comment]
Sorry, but I'm not really sure I follow this - possibly because I do not know anything about Karpenter. So I think you might need to go into a more detail.
