### ISSUE TITLE
Helm chart parameter to custom the watched namespaces

### ISSUE THREAD

**Issue by sneko** [strimzi/strimzi-kafka-operator#852]
Hi!

I noticed in the new Helm Chart that there is no possibility to custom the STRIMZI_NAMESPACE environment variable:
https://github.com/strimzi/strimzi-kafka-operator/blob/master/helm-charts/strimzi-kafka-operator/templates/050-Deployment-strimzi-cluster-operator.yaml#L27

I think it could be really useful. For example, in my case I don't put my Kafka clusters in the same namespace than the operator.

What do you think :) ?

Thank you,

**Comment by scholzj** [comment]
This should be addressed by the PR #868. I will close this issue. If you think there is still some problem, feel free to reopen or open new issue.
