### ISSUE TITLE
[Bug]: Local build fails during java test phase on MacOS/aarch64

### ISSUE THREAD

**Issue by gracegrimwood** [strimzi/strimzi-kafka-operator#8526]
### Bug Description

On MacOS on Apple M2 (aarch64) with Strimzi versions newer than 0.33.x, builds fail during java_build stage due to multiple tests failing with timeout errors like the following:
```
java.lang.AssertionError: 
Expected: an instance of io.fabric8.kubernetes.client.KubernetesClientException
     but: <io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 10000ms while waiting for KafkaBridge resource my-test-resource-896958757 in namespace bridge-crd-it-namespace to be ready> is a io.strimzi.operator.common.operator.resource.TimeoutException
```
It seems that according to Minikube, these resources do eventually become ready, though not necessarily always within the timeout period.

Building Strimzi version 0.33.2 does not exhibit this behaviour, and the tests and build succeed every time.

Notably, increasing memory and/or CPU allocation for Minikube from default settings does not seem to have any effect on this issue (even quadrupling the default values does not have any noticeable effect), nor does allocating more nodes to the Minikube cluster.

### Steps to reproduce

1. Pull repository
2. Run `mvn clean install -DskipTests`
3. Run `make java_build` or `make all`
4. Build will fail at component operator-common with multiple test failures due to timeouts waiting for resources on Minikube.

### Expected behavior

Build should not fail on newer versions of Strimzi.

### Strimzi version

0.34.x, 0.35.x

### Kubernetes version

Kubernetes 1.26.3

### Installation method

_N/A_

### Infrastructure

Containerd 1.6.20, Minikube 1.30.1, Podman 4.5.0, MacOS Ventura 13.3.1 (a) on Apple M2

### Configuration files and logs

Console output from working build of Strimzi 0.33.2: [20230518T143139_strimzi_0.33.2_build.log](https://github.com/strimzi/strimzi-kafka-operator/files/11504785/20230518T143139_strimzi_0.33.2_build.log)
Console output from broken build of Strimzi 0.35.0: [20230518T174413_strimzi_0.35.0_build.log](https://github.com/strimzi/strimzi-kafka-operator/files/11504787/20230518T174413_strimzi_0.35.0_build.log)

### Additional context

Note that running Minikube with the default Docker container engine and Docker driver on aarch64 causes the image build stage to fail due to seperate issues with Docker on this architecture. Running Minikube with Podman driver and Containerd engine works for this purpose, however, so long as you also use socket_vmnet. (I was planning to submit a PR to update the Dev Guide with this info once I figured out what was going on with the java build stage...)

**Comment by scholzj** [comment]
Maybe it is just some flaky? I do not seem to have any issues with this test (also on MacOS with Arm).

**Comment by showuon** [comment]
@scholzj , could you share how you build the strimzi operator using macOS with ARM64 chip? In my experience, I encountered some issues during building and running the built images. And in @gracegrimwood 's case, I know she also encountered some issues during build like what the "additional context" said. So, it'd be great you (or any doc) shared the experience building/running strimzi under ARM64 processor. Thanks.

**Comment by scholzj** [comment]
Building the images depends what is the target platform. If I want to build for Linux/Aarch64, I use something like this (it is not exactly the same command as I have many of the variables defined on the environment level):
```
DOCKER_REGISTRY=quay.io DOCKER_ORG=scholzj MVN_ARGS="-DskipTests" make all
```

This builds the container images and pushes them to `quay.io/scholzj/...`. If I want to build it locally but for Linux/amd64, I add this as well `DOCKER_PLATFORM="--platform linux/amd64"`. This builds the container images for amd64. But no idea if this works with Podman or not - as I said, I use Docker.

As for the tests, I run them separately. Unit and integration tests usually just with `mvn`. System tests usually from IDE.

**Comment by gracegrimwood** [comment]
> Maybe it is just some flaky test?

Possibly. Re-running the same command on the same version of Strimzi reliably produces around the same number of failures (5-6), but not necessarily on the same specific tests. Running the tests separately with `mvn test` seems to intermittently produce errors (instead of failures), though the errors themselves are still TimeoutExceptions (although notably there are fewer of these). Occasionally I can get the tests to pass when run this way, but it's not consistent and fails more often than it succeeds.

> I'm using Docker and not Podman

Can I ask which version of Docker you're using, and whether it is Docker Desktop?

For context, the issue I had with running the image build stage on Docker was that some rpms (specifically shadow-utils) would not install due to an apparent issue setting file capabilities on aarch64 ([similar to this one](https://bugzilla.redhat.com/show_bug.cgi?id=1738233)).

**Comment by gracegrimwood** [comment]
Thanks for that @scholzj, I've tried replicating what you've described to little success. Running `mvn clean install -DskipTests` followed by `mvn test`, I've managed to get the tests to pass a total of 3 times (once using Podman 4.5.0, once using Docker Desktop 4.11.1, once using Docker Desktop 4.19.0), but none of those successes have been replicable and the tests continue to fail more often than they succeed.

I've noticed that on `mvn test` attempts that ultimately fail, I am seeing repeated `io.vertx.core.VertxException: Thread blocked` stack traces (hundreds of them). Is this known behaviour/could this perhaps be related?

**Comment by scholzj** [comment]
Triaged on 1.6.2023: The tests seem to be passing for some (e.g. me) on MacOS / AArch64. So they do not seem to be completely broken. But there are definitely some flaky tests that show up from time tot time even on the CI which is Linux based. This should be tracked as a bug and investigated deeper / fixed.
