### ISSUE TITLE
release artifacts

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#853]
The release artifacts contain `strimzi-0.6.0.tar.gz`, which includes _everything_, like install templates and or samples (e.g. for `kind: KafkaTopic` CR).

There is also a `strimzi-kafka-operator-0.6.0.tgz` which contains _only_ install files for the kafka-operator itself. 

I am wondering if there should be two more artifacts, in the release section on GH:
* `strimzi-topic-operator-0.6.0.tgz`
* `strimzi-user-operator-0.6.0.tgz`

**Comment by scholzj** [comment]
The naming is probably unfortunate. But `strimzi-kafka-operator-0.6.0.tgz` isn't the install for cluster operator from `strimzi-0.6.0.tar.gz`. It is the Helm Chart for installing Strimzi using Helm. We currently don't have Helm Charts for user or topic operators. We should probably name the artifact better for next release, such as `strimzi-helm-chart-0.7.0.tgz` or something like that.

**Comment by matzew** [comment]
were are you creating the release artifacts ? happy to send a PR for this, @scholzj :smile:

**Comment by scholzj** [comment]
I think the archive name actually comes from the Helm tool it self. We should probably rename it in the [Makefile in the `helm_pkg` task](https://github.com/strimzi/strimzi-kafka-operator/blob/4def3422fdbe586ab6c6ae1d53337e0120c5b31e/Makefile#L54). 

PR is of course always welcomed. :-) But I can also easily fix it when doing the next release.
