### ISSUE TITLE
[systemtest] `testConnectorTaskAutoRestart` - check for auto-restart count reset is not working

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#8560]
Currently inside the `ConnectIsolatedST#testConnectorTaskAutoRestart` there is an issue with the last check, where we are waiting for the auto-restart count to be reset to `0`.

It seems that the issue is with committing the offset inside the connector (we are using https://github.com/scholzj/echo-sink) - because the offset is not committed, after the connector restart, the messages are again pulled and the connector is restarted.

We should investigate this more, look for some configuration or somehow "fix it" in the connector.
After that, we should enable this check again.

**Comment by showuon** [comment]
@im-konge , I'm going to investigate it

**Comment by im-konge** [comment]
Hey @showuon , thanks a lot :) btw @jankalinic created a PR for that (https://github.com/strimzi/strimzi-kafka-operator/pull/8684), maybe you can sync with him about it?

**Comment by im-konge** [comment]
@jankalinic this seems to be done after your PR, right?
Can you please check it and close it? Thanks

**Comment by jankalinic** [comment]
@im-konge Thats absolutely correct, at first i wasn't sure but it seems to be fixed now! Closing this issue.
