### ISSUE TITLE
[NodePools] Validate Kafka cluster ID before Kafka reconciliation

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8605]
One of the things not delivered in the initial Kafka Node Pools PR #8551 is the validation of the Kafka cluster IDs. The idea is that as part of the node pool validation, we will validate that the Kafka cluster-ID in the `Kafka` CR and in the `KafkaNodePool` CRs is identical (unless it is a new cluster/pool and it is missing of course). This should help to prevent situations, where due to a change of the `strimzi.io/cluster` label, the node pool would be highjacked from one Kafka cluster to another.

**Comment by tombentley** [comment]
Triaged on 15/06/2003: This seems like a clear win for avoiding an unlikely, but potentially very damaging situation.

**Comment by tombentley** [comment]
@scholzj is this something you were planning to work on yourself? I've left it unassigned for now, but you can always mark it as help wanted if you weren't going to get to it soon.

**Comment by scholzj** [comment]
I will get it done, yes.
