### ISSUE TITLE
[Enhancement]: Adding Pod Disruption Budget (PDB) Configuration to Strimzi Kafka Operator's Helm Chart

### ISSUE THREAD

**Issue by OuesFa** [strimzi/strimzi-kafka-operator#8607]
### Related problem

The Strimzi Kafka Operator supports high availability based on the kube lease method from version 0.32 onwards. This is a valuable feature, particularly given the current reliance on SPS objects.

However, it seems there's currently no way to configure Pod Disruption Budgets (PDBs) within the operator's Helm chart. PDBs are important for maintaining a minimum number of operational pods during disruptions.

### Suggested solution

I suggest enhancing the Strimzi Kafka Operator's Helm chart by introducing an option to configure PDBs. This feature would improve the resilience of our deployments, especially in disruption scenarios by ensuring a minimum number of pods remain operational.

### Alternatives

As an alternative, users could manually set up PDBs outside of the Helm chart. However, this is not as seamless and would require extra work on the user's part, and potentially could lead to misconfigurations or errors. Incorporating this feature directly into the Helm chart would provide a more streamlined, user-friendly approach.

**Comment by tombentley** [comment]
Triaged on 15/06/2023: This seems a very reasonable request. PRs welcome.

**Comment by haijun2022** [comment]
Hi @tombentley, can I take this story if it is still available? Thank you!

**Comment by scholzj** [comment]
@haijun2022 Yes, you can look into it if you want.

**Comment by haijun2022** [comment]
Thanks @scholzj , I will start work on it!

**Comment by dttung2905** [comment]
Hello @haijun2022 , are you still working on the PR? If not, I would like to attempt to solve this 🙏

**Comment by haijun2022** [comment]
Hi @dttung2905  I already fixed the issue but current in our internal review process, will create PR once get approved(earlier next week). thank you for asking!
