### ISSUE TITLE
[STs] Tests that are using Cruise Control should be marked with the `@Tag(CRUISE_CONTROL)` tag

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8618]
All tests in the `LogSettingST` class are using Cruise Control because it is set up in the initial deployment of the shared Kafka cluster. However, they are not all marked with the `@Tag(CRUISE_CONTROL)` tag. Only one test which interacts with Cruise Control is marked with it. This is not sufficient, because when the Cruise Control doesn't work, all of these tests will fail during the setup phase even when tests with Cruise Control are excluded using the tag.

This should be addressed ...
* Either by enabling Cruise Control only int he test using it instead of the shared cluster in the setup phase
* Or by marking the whole test suite with the correct tag

The same seems to apply for `MultipleNamespaceIsolatedST` which seems to use setup from `AbstractNamespaceST` which seems to be also using Cruise Control. Also for `AllNamespacesIsolatedST`, `SecurityST`

**Comment by im-konge** [comment]
Yeah sure. I will take a look at that ASAP
