### ISSUE TITLE
[Bug]: Secret too long error when creating large cluster with inter-broker TLS enabled.

### ISSUE THREAD

**Issue by Wennn** [strimzi/strimzi-kafka-operator#8623]
### Bug Description

We notice that all the TLS key pairs of each broker are stored at one secret, which makes this secret exceed the Kubernetes length limit easily when creating a large cluster. In our test, we met this issue when we tried to create a cluster with more than 130 brokers.

Actually I am not sure if it is necessary for each broker to know other's keys. If not, shall we create different secret for each broker?

### Strimzi version

0.30.0

### Kubernetes version

Kubernetes 1.26

### Installation method

Helm chart

**Comment by scholzj** [comment]
Yes, it would make sense to split it into separate secrets. It was not easily possible while using StatefulSets, but it should be possible now.

There is already an issue tracking it => #7687.

**Comment by tombentley** [comment]
Triaged on 15/06/2023: Closing since this is tracked by #7687.
