### ISSUE TITLE
Split the classes from the `io.strimzi.api.kafka.model` package to multiple sub-packages

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#8628]
In the `api` module, the package `io.strimzi.api.kafka.model` currently contains log different classes for the different CRDs. They are often not shared between multiple CRDs - just share the package. This makes the package quite big and hard for people to find the right class in it. We should consider splitting this package into multiple sub-packages for the different CRDs and a `common` package for the classes which are really shared. A separate package was already used for example for the `KafkaNodePool` related classes.

Changing it for the existing classes might break compatibility, but might be useful - so maybe better to break it now than later. It is not really clear how many people are actually using the `api` module outside of Strimzi.

This was raised originally as part of the #8551 PR review.

**Comment by tombentley** [comment]
Triaged on 15/06/2023: There's a trade-off between java API compatibility for users of the api module and the benefits to the project (and now contributors) of having a tidier packaging. The [usage stats](https://mvnrepository.com/artifact/io.strimzi/api/0.18.0/usages) suggest there are very few users of the Java API, and it's still a 0.x version, so the trade-off seems to favour making this change.
