### ISSUE TITLE
Reconciliation after edit of StrimziPodSet causes another independent broker to be terminated

### ISSUE THREAD

**Issue by coperator** [strimzi/strimzi-kafka-operator#8712]
### Bug Description

 want to temporarily shut down a specific broker in order to do some manual maintenance.
Until now when StatefulSets were used to managed the pods I was able to do this with `kubectl annotate kafka my-cluster strimzi.io/pause-reconciliation="true" && kubectl delete statefulset my-cluster-kafka --cascade=false && kubectl delete pod my-cluster-kafka-0` 

Now with StrimziPodSets I am currently failing to accomplish the same thing.
`kubectl annotate kafka my-cluster strimzi.io/pause-reconciliation="true"` works as expected and I am able to edit the StrimziPodSet, e.g. with
```
kubectl patch StrimziPodSet my-cluster-kafka --type='json' -p='[{"op": "remove", "path": "/spec/pods/0"}]
```
The StrimziPodSets is reconciled and the pod is terminated.
So far, everything works well and as expected.

After the manual maintenance I want to start the temporarily shut down broker and go back to the initial state.
Until now when StatefulSets were used to managed the pods
```
kubectl annotate kafka my-cluster strimzi.io/pause-reconciliation-
```
worked well to automatically go back to initial deployment configuration.

However, now, with StrimziPodSets, I see the following behavior:
After calling `kubectl annotate kafka my-cluster strimzi.io/pause-reconciliation-` the StrimziPodSets is reconciled and another broker *the last broker in the array in the StrimziPodSet) is terminated right away and removed from the StrimziPodSet, which is definitely not what I want.
Then the temporarily shut down broker is started.
The unintentionally terminated broker is not started and the log contains the message
```
Failed to reconcile
io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod my-cluster-kafka-0 is currently not rollable
``` 
because of the unintendent shutdown of the other broker some topics are already under-replicated.

Before I start to investigate further and provide further logs I am wondering if there is another and better way to shut down a specific broker with StrimziPodSets.

### Strimzi version

0.31.0

### Kubernetes version

Openshift 4.10

### Installation method

YAML files

**Comment by scholzj** [comment]
I do not seem to be able to reproduce it with the latest version. So maybe an upgrade would help you. Also, I think you should try to do a non-cascading delete of the StrimziPodSet as you did with StatefulSet instead of editing it. They way you do it is essentially triggering scale-up of the cluster.

**Comment by coperator** [comment]
Thank you for the fast response and your help!
Deleting the StrimziPodSet non-cascading did the trick.
However, I thought, there would be a better/easier way to temporarily shut down a broker with StrimziPodSets, like propsed in https://github.com/strimzi/strimzi-kafka-operator/issues/3527.  With a non-cascading delete the situation is in principle the same as before with the StatefulSet. During maintenance the other broker pods are not watched and restarted if necessary for what ever other reason.

Currently, I am not able to quickly update my strimzi version. I plan to do this in the next weeks and could test again my approach.

**Comment by scholzj** [comment]
Triaged on 29.6.2023: This seems to be resolved and should be closed. If there is anything new, we can reopen it or have a new discussion/issue.
