### ISSUE TITLE
[Enhancement]: Add support for stopping connectors

### ISSUE THREAD

**Issue by mimaison** [strimzi/strimzi-kafka-operator#8713]
### Related problem

Kafka 3.5 introduced the `STOPPED` state for connectors via a new endpoint `PUT /connectors/<CONNECTOR>/stop`. Compared to `PAUSED` where the connector and tasks stay instantiated, in `STOPPED` only the configuration of the connector is kept but nothing is actually running.

A connector is `PAUSED` state still uses some resources but it's faster to resume. So using pause is great if you want to stop data flowing for a short duration. Otherwise it's interesting to fully stop the connector with the new API. Also the `STOPPED` state will be required to use the offset delete/reset endpoints that should come with Kafka 3.6.

### Suggested solution

Strimzi already supports pausing connectors using an annotation. A similar approach can probably be used to stop them. TO restart a stopped connector you use the `PUT /connectors/<CONNECTOR>/resume` endpoint like for paused.

### Additional context

See this [KIP-875](https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect) for details about this feature.

**Comment by scholzj** [comment]
Triaged on 29.6.2023: Makes sense to implement. But what should the API look like? We could deprecate the current `pause` field and replace it with a new field `state` which would have an Enum value of pause or stop (and possibly other values in the future). Should have a proposal detailing the API changes and the deprecation timeline.

**Comment by scholzj** [comment]
Done by @mimaison in #9095
