### ISSUE TITLE
[Enhancement]: Use PEM certificates when connecting to KafkaAgent's REST endpoint

### ISSUE THREAD

**Issue by tinaselenge** [strimzi/strimzi-kafka-operator#8721]
### Related problem

KafkaRoller currently uses PKCS12 certificates when connecting to KafkaAgent's REST endpoint to learn about broker state. 

### Suggested solution

We should implement using PEM certificates instead of PKCS12 because it is easier to use and more Kubernetes-friendly format. It may be easier for future work around certificate management.

**Comment by scholzj** [comment]
Triaged on 29.6.2023: This makes sense as we are in general moving towards PEM certificates rather then PKCS12 stores.
