### ISSUE TITLE
DCG: Python included in list of dependencies for contributing to Strimzi docs

### ISSUE THREAD

**Issue by laidan6000** [strimzi/strimzi-kafka-operator#874]
In the [Strimzi Documentation Contributor Guide](http://strimzi.io/contributing/guide/#dependencies), in the Dependencies section, Phython is incorrectly listed as a dependency for contributing to the Strimzi docs.

We should add Ruby as a dependency because it's required to install Asciidoctor. We could add a link to the Asciidoctor user manual for the supported versions - https://asciidoctor.org/docs/user-manual/#system-requirements

**Comment by PaulRMellor** [comment]
You don't need Ruby to install asciidoctor
Latest _contributor_ guide has a section that lists the tools to build docs:

- [Documentation tools](https://strimzi.io/contributing/guide/#documentation_tools)
