### ISSUE TITLE
[Bug]: Log-dump script doesn't work with KafkaNodePools

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#8769]
### Bug Description

The Log-dump script - `tools/log-dump/run.sh` - is not working with KafkaNodePools, as the script takes original names of the Pods and resources like `my-cluster-kafka-0`.
But, with KafkaNodePools, the names are different.
Names of the StrimziPodSets and Pods are (just for Kafka, not ZK) changed to following pattern: `CLUSTER_NAME-NODE_POOL_NAME`.

Also, the source of truth (information about replicas, storage...) should be used KafkaNodePools instead of Kafka resource. 

### Steps to reproduce

1. Deploy CO - `latest` - with `+KafkaNodePools` FG enabled
2. Deploy KafkaNodePool(s) for the Kafka cluster
3. Deploy Kafka
4. Execute the log-dump script: 
```
./tools/log-dump/run.sh partition --namespace NAMESPACE --cluster CLUSTER_NAME --topic TOPIC_NAME --partition PARTITION_NUMBER --out-path PATH
```

### Expected behavior

Everything will be correctly collected.

### Strimzi version

main

### Kubernetes version

all

### Installation method

YAML

**Comment by scholzj** [comment]
Solved in https://github.com/strimzi/strimzi-kafka-operator/pull/8816 by removing the `log-dump` utility which did not seem to get much use.
