### ISSUE TITLE
[Enhancement]: Generate PEM certificates by default

### ISSUE THREAD

**Issue by ruslangr** [strimzi/strimzi-kafka-operator#8814]
### Related problem

For now, operator generate by default certificates only in PKCS #12  format. But, some application which we use, support only PEM format. It would be grate if operator would generate certificates in PEM format too.

### Suggested solution

Make spec.clusterCa.type and spec.clientsCa.type option in Kafka CRD.

**Comment by scholzj** [comment]
All of the secrets Strimzi creates have PEM certificates. So I do not think it is clear what exactly you are suggesting. Where are you missing PEM secrets?

**Comment by scholzj** [comment]
Triaged on 13.7.2023: Should be triaged next time to see if we get some feedback from the user.

**Comment by ppatierno** [comment]
Triaged on 13.7.2023: @ruslangr we are going to close it, feel free to reopen if you have more feedback for us.
