### ISSUE TITLE
[Enhancement]: Allow @ in KafkaUser name

### ISSUE THREAD

**Issue by brunsgaard** [strimzi/strimzi-kafka-operator#8818]
### Related problem

When I use type oauth for listener authentication it would be great to be able to set `userNameClaim: email`, the problem is that the email address contains a "@" and thus for authorization I am not able to create a user with a matching name as kubernetes does not allow "@" in the `metadata.name` field. 

### Suggested solution

I would like to see a solution similar to the one for topic names, where it is possible to override the `metadata.name` with `topicName` in the `KafkaTopicSpec`.

**Comment by scholzj** [comment]
This was discussed many times before. There is currently no plan to support that. It introduces all kinds of problems and complications which eventually lead to bad software. You can disable the User Operator if needed and manage things directly using the Kafka Admin APIs.

**Comment by scholzj** [comment]
It will be triaged on the next community call. But I would expect the outcome to be the same as in the past.

**Comment by brunsgaard** [comment]
Hi again @scholzj 
Our team is evaluating if forking the user-operator and trying to resolve the issue in a fork would be viable. 
You wrote that it "introduces all kinds of problems", would you be able to elaborate a bit on your concerns?

**Comment by scholzj** [comment]
For example, you can have 10 different resources managing the same user which contain contradicting configurations. How do you decide which one is the _right one_? You also cannot easily search for the right user because the names are not clear anymore. Dealing with this and other issues significantly increases the complexity and maintenance efforts and ultimately leads to bugs and issues.

**Comment by scholzj** [comment]
Triaged on 13.7.2023: Already discussed in the past. We do not really want to increase the complexity level and maintenance effort by supporting usernames not compatible with Kubernetes.
