### ISSUE TITLE
Update to latest k8s/openshift client and k8s model

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#882]
Hi,

I noticed that currently some older versions of the following APIs are used:
https://github.com/strimzi/strimzi-kafka-operator/blob/master/pom.xml#L28-L30

While `k8s-client` and `openshift-clients` are on different `3.1.x` versions, the model is on an older `2.0.4` version.

The _latest_ for the clients is `4.0.4` and for the model is `3.0.3`.

I wonder if it is worth trying to update those? Or if there are some (specific) reasons for not doing that (yet).

thanks!

**Comment by scholzj** [comment]
I think this is too old and not valid anymore. I will close this issue.
