### ISSUE TITLE
[Enhancement]: Option to use jemalloc implementation

### ISSUE THREAD

**Issue by jakubmalek** [strimzi/strimzi-kafka-operator#8835]
### Related problem

Recently I was investigating high memory usage by Kafka Connect in my cluster. While looking at JVM memory usage statistics both for heap and non-heap (including threads x 1mb) there was relatively large portion of RSS memory used by the connect process growing over time. The problem was that this extra memory was not shown in JVM usage statistics, including `VM.native_memory summary` report. Interestingly, running the `System.trim_native_heap` operation seem to release portion of that memory. 
This lead me to believe that the problem is related C native-heap and  high memory fragmentation caused by glibc malloc. The number malloc arenas is by default configured to number CPU cores times 8 ( for 64 bit systems) which can lead to a lot of memory waste.
I found a nice blog post which describe this in more details
https://blog.malt.engineering/java-in-k8s-how-weve-reduced-memory-usage-without-changing-any-code-cbef5d740ad

To mitigate the problem I set fixed number of malloc arenas with `MALLOC_ARENA_MAX` env variable, but ultimately I wanted to switch to `jemalloc` implementation.
The problem is that currently there is no way to install the `jemalloc` into the container. For Kafka Connect I found a dirty workaround where you can package `jemalloc` lib and add it as connect plugin, then load it with `LD_PRELOAD` env variable from `/opt/kafka/plugins` dir.
This of course is a hack and I think it would be nice to have more proper way of installing it to the container.

### Suggested solution

The first idea I had was to extend template for `KafkaConnectBuild` with a configurable list of custom commands to be executed during the Docker image build. 

**Pros**:
- 👍 It can be relatively easy to implement, we only need to extend generated Dockerfile
- 👍 Can be used to install other tooling or/and OS security patches

**Cons**:
- 👎 It's limited only to KC workload
- 👎 Allowing execution of arbitrary commands can lead to failed builds or other side effects which can lead to application stability problems
- 👎 It's not a straightforward option to select different malloc version, and as such requires addition know-how how to do it

### Alternatives

Another potential option is to extend template for the `initContainer` with option to add the container definition that can be used to download the `jemalloc` lib and place it in shared volume.

**Pros**:
- 👍 It can be re-used for all workloads (not only KC)
- 👍 It can be used to install other tooling

**Cons**:
- 👎 It's not a straightforward option to select different malloc version, and as such requires addition know-how how to do it
- 👎 It complicates the deployment process

Yet another potential option would be to offer different variant of Kafka base image with `jemalloc` pre-installed and pre-configured.
**Pros**:
- 👍 Can be configured globally for all Strimzi workloads
- 👍 Easy to use, no need for manual download of the lib packages

**Cons**:
- 👎 Increase maintenance effort for another variant of Kafka image

### Additional context

Using different malloc version can have potential side-effects, including reduced performance. Nevertheless, as a informed user I should be able to do it and accept the risks. More-over, the `jemalloc` can also be temporary used, to conduct more detailed investigation to find memory leaks.

**Comment by scholzj** [comment]
Why don't you just build and use a custom container image where you add whatever you want? I think you can just edit the [_base image_](https://github.com/strimzi/strimzi-kafka-operator/tree/main/docker-images/base), build the project, and use your images.

**Comment by jakubmalek** [comment]
That's a fair point, I think I focused too much on connect-build process that I forgot about option to change the image 😅

**Comment by scholzj** [comment]
Triaged on 13.7.2023: We do not want to make this configurable because the effort would be too high. But we should leave it for next time to see if this would make some sense to use it out of the box? But it is not clear if this is generally applicable, how it works on different platforms etc.

**Comment by jakubmalek** [comment]
The solution with rebuilding the image is sufficient enough for me so I would be fine with closing this issue. 
For some reason I didn't consider it as an option, but now it makes perfect sense to me.

**Comment by ppatierno** [comment]
Triaged on 27.7.2023: @jakubmalek we are happy you are ok with rebuilding the image including the jemalloc. We think it's the best way to go. Closing the issue.
