### ISSUE TITLE
[Enhancement]: Liveness / readiness probe for Kraft mode 

### ISSUE THREAD

**Issue by tinaselenge** [strimzi/strimzi-kafka-operator#8850]
### Related problem

The current live and readiness probes are based on checking the ZooKeeper connection first and then checking the broker state. Currently, the Strimzi Cluster Operator already supports the KRaft mode (behind a feature gate) and zookeeper is being deprecated soon, therefore checking ZooKeeper is probably not the right approach anymore. 

### Suggested solution

Implement [proposal #046](https://github.com/strimzi/proposals/blob/main/046-kraft-liveness-readiness.md) for liveness and readiness probes in a KRaft Kafka cluster.

The expected outcome based on the proposal for this task is:
```
Controller only node:
Liveness: the Java process in the container is running
Readiness: controller is listening on the port 9090 which is configured in controller.listener.names

Broker only node:
Liveness: broker is listening on the port 9091 which is configured in inter.broker.listener.name
Readiness: the BrokerState metric >=3 && != 127

Combined node:
Liveness: the Java process in the container is running
Readiness: the BrokerState metric >=3 && != 127
```

The proposed liveness probe for broker only mode requires a change because of [KAFKA-14658](https://issues.apache.org/jira/browse/KAFKA-14658). Before this upstream change, Kafka broker port is opened early typically before the log recovery phase. Based on this logic, the proposed liveness probe for broker only mode to listen on the port 9091 which is configured in inter.broker.listener.name. However, after the upstream change in [KAFKA-14658](https://issues.apache.org/jira/browse/KAFKA-14658), the broker starts listening only when it's ready to serve client requests it would mean long log recovery might cause Kube to restart, because the pod wouldn't appear to be alive.

This upstream change does not have an impact on the existing liveness check for zookeeper mode because the check passes if there is a ZK session.

The proposed liveness probe for controller and combined mode to have running Java process in the container. The reason for this was because of very similar issue. For controller mode, the log recovery happens before socket bind, which happens before socket listen (the LISTEN state), so if recovery of the __cluster_metadata log takes a long time then using the port for a liveness check risks Kubernetes killing the controller.

Therefore I think it makes sense to change broker only mode to have the same liveness probe (running Java process in the container) as the controller and combined mode. The expected outcome becomes:
```
Controller only node:
Liveness: the Java process in the container is running
Readiness: controller is listening on the port 9090 which is configured in controller.listener.names

Broker only node:
Liveness: the Java process in the container is running
Readiness: the BrokerState metric >=3 && != 127

Combined node:
Liveness: the Java process in the container is running
Readiness: the BrokerState metric >=3 && != 127
```

The [proposal](https://github.com/strimzi/proposals/blob/main/046-kraft-liveness-readiness.md) for KRaft Liveness/Readiness probes involves 3 phases. Phase 1 has been completed [here](https://github.com/strimzi/strimzi-kafka-operator/pull/7878). 

Due to the upstream change mentioned above, phase 2 described in the proposal will look slightly different:
```
Phase 2 - Strimzi adds support for broker only and controller only modes
Controller only pod liveness and readiness checks are fully implemented to match this proposal.
Broker only pods are marked alive when there is a Java process running and ready if the BrokerState metric >=3 && != 127
Combined mode pods are marked as both alive and ready when there is a Java process running (no change from phase 1).
```

Phase 3 will fully implement both liveness and readiness probes for all three modes.

**Comment by ppatierno** [comment]
Triaged on 27.7.2023: community/maintainers will go and take a look at the changes and the corresponding PR that Tina opened to work on this. Leaving with needs-triage to discuss the outcome on the next community call if needed.

**Comment by katheris** [comment]
The link to the phase 1 PR currently points to the proposal PR, the phase 1 PR is here: https://github.com/strimzi/strimzi-kafka-operator/pull/7878

**Comment by scholzj** [comment]
Triaged on 12.8.2023: Work on this issue is in progress in #7878. We should proceed with it.
