### ISSUE TITLE
[systemtest] Use Admin client for checking topics in Kafka when UTO is used

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#8864]
In some STs, we check if spec of particular KafkaTopic has correct values -> in CR.
But in situations when the KafkaTopic is created just in Kafka (so there is no KafkaTopic CR), with usage of UTO, the KafkaTopic is not created (synced) from Kafka to KafkaTopic CR.
In these situations, we should check the spec of KafkaTopic directly in Kafka, for example using the test-clients' Admin client.

The test checks are currently disabled for UTO, but we should fix this issue and enable the checks back.
For enabling the checks, search for link of this issue.

**Comment by fvaleri** [comment]
This includes tests with `UTONotSupported` annotation and/or "TODO https://github.com/strimzi/strimzi-kafka-operator/issues/8864" comment.

**Comment by henryZrncik** [comment]
Closed as completed in https://github.com/strimzi/strimzi-kafka-operator/pull/9295 and https://github.com/strimzi/strimzi-kafka-operator/pull/9876
