### ISSUE TITLE
[Bug]: Operator not honorig PDB

### ISSUE THREAD

**Issue by leunamnauj** [strimzi/strimzi-kafka-operator#8866]
### Bug Description

Hello,
I'm just running a vanilla setup, pretty much copypaste the examples, but I've noticed that when I'm applying a change on a kafka server object suddenly stop all the pods together instead of running a normal rolling update.
I've checked the doc and PDB is in 1 by default (also tried setting this explicitly) and is still.
Am I missing something?
If needed can share the logs but is not more than a blank new cluster

### Expected behavior

normal rolling update for minimum downtime

### Strimzi version

0.35.1

### Kubernetes version

1.26

### Installation method

helm chart

### Infrastructure

baremetal (k3s)

**Comment by scholzj** [comment]
You should probably share some logs and exact steps to reproduce. The operator does not care about the PDB. That is for Kubernetes and its pod disruptions. The operator always rolls the pods one by one.
