### ISSUE TITLE
[Bug]: watchNamespaces automatically creates kafka-cluster in the NS being watched and creates 2 instances of Kafka-Cluster

### ISSUE THREAD

**Issue by vyom-soft** [strimzi/strimzi-kafka-operator#8905]
### Bug Description

Hello,

I am noticing a behavior with strimziOperator 
The NS which are bing watched, it automatically creates default Kafka cluster in that NS. Even though no Kafka cluster was previously created in that particular NS that is under watch. 

Example: In a NS called as kvib-dev, I did **not** create  kafka-cluster  (but, I kept it under watchNamespaces) the Strimzioperator created **2** instances of kafka-cluster ? 

On the other hand, for a given NS branch-dev, I did provide/create the Kafka cluster with overridden values, the Kafka cluster got created with the overridden values.  And again I see **2** instances of Kafka-Cluster in this NS. One is prefixed with the particular NS & one with the helm chart name.

I deployed strimzi-kafka-operator via ArgoCD.
Used this chart https://github.com/strimzi/strimzi-kafka-operator/tree/main/helm-charts/helm3/strimzi-kafka-operator

in values.yaml
watchNamespaces: ["kvib-dev", "kvibarch-288-2001df66", "dev-289-d1e8ff90"]
watchAnyNamespace: false

### Steps to reproduce

- Install Strimzi-Kafka-Operator helm chart in a NS.
- in it's values.yaml
   watchNamespaces: ["local-dev", "dev-288-2001df66", "dev-289-d1e8ff90"]
   watchAnyNamespace: false

Where "local-dev", "dev-288-2001df66", "dev-289-d1e8ff90" are valid NS.

### Expected behavior

Strimzi operator should not create 2 instances of Kafka-Cluster in all the watchNamespaces. ?
Extra cluster of Kafka-Cluster should not be created. And only when the Kafka-Cluster manifest is already being applied in that NS, then only the kafka-cluster should be created.

### Strimzi version

0.36.0

### Kubernetes version

1.26.3

### Installation method

HelmChart, ArgoCD

### Infrastructure

BareMetal

### Configuration files and logs

- In the first NS  kvib-dev 2 **default** kafka-cluster get created automatically by strimzi-operator, without explicitly deploying the kafka-cluster manifest.

```
$ kubectl get pods -n kvib-dev | grep kafka  
kafka-kvib-kafka-cluster-entity-operator-656cfc7985-hshdw    4/4     Running                       0                10h
kafka-kvib-kafka-cluster-kafka-0                             2/2     Running                       0                10h
kafka-kvib-kafka-cluster-zookeeper-0                         2/2     Running                       0                10h
kvib-be-kafka-entity-operator-66c6554d8c-5rmt5               4/4     Running                       0                10h
kvib-be-kafka-kafka-0                                        2/2     Running                       0                10h
kvib-be-kafka-kafka-1                                        2/2     Running                       0                10h
kvib-be-kafka-zookeeper-0                                    2/2     Running                       0                10h
```

- In the second NS  kvibarch-288-2001df66 **2**  kafka-cluster get created automatically by strimzi-operator, here I did create the cluster via  kafka-cluster manifest file over ArgoCD though.

```
$ kubectl get pods -n kvibarch-288-2001df66 | grep kafka
kvib-kafka-cluster-entity-operator-c47b5f597-frf27                3/3     Running                      0                 6h24m
kvib-kafka-cluster-kafka-0                                        1/1     Running                      0                 6h24m
kvib-kafka-cluster-zookeeper-0                                    1/1     Running                      0                 6h25m
kvibarch-288-2001df66-kvib-kafka-cluster-entity-operator-982c5v   3/3     Running                      0                 6h22m
kvibarch-288-2001df66-kvib-kafka-cluster-kafka-0                  1/1     Running                      0                 6h24m
kvibarch-288-2001df66-kvib-kafka-cluster-zookeeper-0              1/1     Running                      0                 6h25m
```

```

### Additional context

_No response_

**Comment by scholzj** [comment]
Strimzi Helm Chart does not create any Kafka clusters. It only installs the Strimzi Cluster Operator. So this sounds like some issue on your side in your tooling.

**Comment by vyom-soft** [comment]
> Strimzi Helm Chart does not create any Kafka clusters. It only installs the Strimzi Cluster Operator. So this sounds like some issue on your side in your tooling. And it would definitely not use on its own a name `kvibarch-288-2001df66` on its own. So this is likely a Kafka resource created by you or someone else using your cluster.

@scholzj Thank you for the reply. ArgoCD is used as tool to do the deployment.

**Comment by ppatierno** [comment]
Triaged on 27.7.2023: waiting for the user's feedback. We'll triage again on the next community call.

**Comment by ppatierno** [comment]
@vyom-soft thanks for your feedback!
