### ISSUE TITLE
[systemtest] Add new downgrade scenario 

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#8930]
Currently we have few test scenarios for downgrading Kafka version and also few for downgrading Strimzi version + Kafka version.
But, it seems that we are missing one more downgrade scenario, which is mentioned in #8869 :

1. deploy CO with the changes from main (latest)
2. deploy Kafka with latest supported version and `inter.broker.protocol.version` set to latest - 1 version of Kafka
3. when Kafka cluster is ready, downgrade CO version to latest released + change Kafka version to the latest - 1 version (supported by the latest released Strimzi)
4. check that Kafka cluster is correctly downgraded without issues.

**Comment by j4real2208** [comment]
For this case we could do the downgrade from 0.37 -> 0.36 right ? 
@im-konge

**Comment by im-konge** [comment]
We are typically doing downgrade from HEAD - `main` branch with latest changes - to latest released -> so `0.37.0`
The information about this is kept here https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/src/test/resources/upgrade/BundleDowngrade.yaml .

In code, we are getting this info from https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/src/main/java/io/strimzi/systemtest/upgrade/UpgradeKafkaVersion.java , so you can use that :)

**Comment by im-konge** [comment]
@j4real2208 I created this issue because of the bug #8869 , which is now closed after the latest comment. So I guess this is not needed, as it is not intended to actually work (so the test would fail all the time).

I'm gonna close this issue as well because of it - did you want to work on this issue?

**Comment by j4real2208** [comment]
No , I am good .
