### ISSUE TITLE
[Docs]: Release schedule for UnidirectionalTopicOperator feature gate

### ISSUE THREAD

**Issue by Kartikey-Mishra1** [strimzi/strimzi-kafka-operator#8935]
### Suggestion / Problem

We have started testing UTO in some of our dev/test environments by following the guidance [here](https://strimzi.io/docs/operators/latest/deploying.html#ref-operator-unidirectional-topic-operator-feature-gate-str). But I had some trouble finding the tentative release schedule of the feature gate. The table [here](https://strimzi.io/docs/operators/latest/deploying.html#ref-operator-unidirectional-topic-operator-feature-gate-str:~:text=longer%20be%20disabled.-,Table%2029,-.%20Feature%20gates%20and) doesn't seem to have an entry for the UTO feature gate. The proposal does seem to mention a [graduation timeline](https://github.com/strimzi/proposals/blob/main/051-unidirectional-topic-operator.md#co-managed-case-1) but I am not sure if it's up to date as the feature gate was suppose to be in alpha phase in 0.35 according to it. 
It would be great if the docs could be updated with the release schedule of the UTO feature gate following the recent developments. It will help us to prepare ourselves better for any future changes in regards to Topic operator.      

### Documentation Link

https://strimzi.io/docs/operators/latest/deploying.html#ref-operator-unidirectional-topic-operator-feature-gate-str:~:text=longer%20be%20disabled.-,Table%2029,-.%20Feature%20gates%20and

**Comment by Kartikey-Mishra1** [comment]
@scholzj thanks for responding to this and confirming that the schedule remains the same. I am also happy to contribute the doc changes needed here if you and others feel it would be appropriate to(wasn't sure about the schedule so I did not directly raise a PR).

**Comment by scholzj** [comment]
Oh, of course, you can absolutely open a PR for this if you want. That would be amazing. Thanks.

**Comment by PaulRMellor** [comment]
Thanks for updating the docs @Kartikey-Mishra1. I was going to update myself (not having seen this issue), but you beat me to it!
