### ISSUE TITLE
[Enhancement]: Kafka CRD should support `priorityClassName`

### ISSUE THREAD

**Issue by RobinSchwaller** [strimzi/strimzi-kafka-operator#8943]
### Suggested solution

The Kafka CRD should allow setting a priorityClassName for the deployments (kafka, zookeeper, entityOperator & kafkaExporter).

This aligns with other CRD & operators and enables the correct usage of priority classes within k8s.

**Comment by scholzj** [comment]
Triaged on 10.8.2023: This feature makes sense.

**Comment by ShazaAldawamneh** [comment]
I'll work on this if no one is working on it

**Comment by scholzj** [comment]
Looks like this has been already implemented a long time ago in #1755. Did you just missed it or do you think it needs something more @RobinSchwaller? I think you can use it to configure every single pod deployed by Strimzi.

**Comment by RobinSchwaller** [comment]
@scholzj Oh I missed that, sorry. Thanks for pointing this out, specifying the priorityClassName does already work.
