### ISSUE TITLE
[Enhancement]: Add template for clientsCaCert in Kafka resource

### ISSUE THREAD

**Issue by husker-du** [strimzi/strimzi-kafka-operator#8968]
### Related problem

The same way annotations can be set to the cluster-ca-cert secret generated by the strimzi operator for a kafka cluster, I need the same behaviour for the clients-ca-cert secret.

At this moment, in the Kafka CRD there's a template for the cluster-ca-cert secret where annotations can be set to it: `spec.kafka.template.clusterCaCert.metadata.annotations`.
I need the same for the clients-ca-cert:
`spec.kafka.template.clientsCaCert.metadata.annotations`.

This is extremely important in my project because we want use the [Kubed](https://appscode.com/products/kubed/) operator for copying those files from the kafka cluster namespace to other namespaces where consumers, producers and other components are connected to the kafka cluster using mtls authentication.

At this moment we are using hooks when deploying these components to copy those secret files to the release namespace but using kubed along with strimzi will simplify a lot our helm chart and I think kubed leverages strimzi for these kind of situations.

### Suggested solution

Add the `spec.kafka.template.clientsCaCert.metadata.annotations` section to the Kafka CRD.

**Comment by scholzj** [comment]
I don't think it is a problem to have this supported. But why is it so important to copy the Clients CA to the clients?
* The clients CA is in the User secret with the user certificate which you need to copy for mTLS
* The clients CA is in general not needed by the client. It needs to trust the server certificate -> so it needs the ClusterCA public key. And it needs the user public and private for the client authentication. The Clients CA public key is usually not used by the client.

As I said - I don't think it is problem to add this. Just curios to understand it.

**Comment by scholzj** [comment]
Triaged 10.8.2023: Let's leave more time to @husker-du to reply to better understand the motivation. Should be revisited in next call if needed.

**Comment by scholzj** [comment]
Triaged on the community call on 24th August: Should be closed as we do not understand the use-case for this. This secret is not needed for mTLS. If there is some use-case where it is needed, we can reopen it.
