### ISSUE TITLE
[Bug]: JVM InitialRAMPercentage/MaxRAMPercentage options ignored

### ISSUE THREAD

**Issue by dadufour** [strimzi/strimzi-kafka-operator#8976]
### Bug Description

When we specify `InitialRAMPercentage/MaxRAMPercentage` JVM options and we don't specify any `Xms/Xmx` option, then strimzi will dynamically compute values for `Xms` and `Xmx` and will provide them to the JVM.
As the computation is using hardcoded parameters, the `Xms/Xmx` values are usually completelly different from the size that would have been computed with `InitialRAMPercentage/MaxRAMPercentage`.
In the end, what is considered by the JVM are the `Xms/Xmx` values computed by strimzi and what has been provided by the user is ignored.

We would need strimzi to support `InitialRAMPercentage/MaxRAMPercentage` JVM options.

### Steps to reproduce

Use a CR with the following JVM option (and WITHOUT Xms+Xmx)
```
    jvmOptions:
      '-XX':
        InitialRAMPercentage: 50
        MaxRAMPercentage: 80
```

### Expected behavior

It is expected that the provided options are given to the JVM and no Xms/Xmx option is injected.

### Strimzi version

0.34

### Kubernetes version

Openshift 4.10.46

### Installation method

ArgoCD

### Infrastructure

Azure

### Configuration files and logs

We can see this in the logs:
```
##########
# User provided configuration
##########
auto.create.topics.enable=false
default.replication.factor=3
...
**Configuring Java heap: -Xms2136746229 -Xmx2136746229**
+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
```
We can see injection of Xms/Xmx values computed by strimzi

**Comment by scholzj** [comment]
Triaged on the community call on 24th August: Sounds reasonable and could be done as an enhancement.
