### ISSUE TITLE
[Enhancement]: Parameterized Install URL

### ISSUE THREAD

**Issue by rob-straughan** [strimzi/strimzi-kafka-operator#9001]
### Related problem

Currently to install the operators locally we reference the URL: https://strimzi.io/install/latest?namespace=default

Example:

> apiVersion: kustomize.config.k8s.io/v1beta1
> kind: Kustomization
> namespace: default
> resources:
> - https://strimzi.io/install/latest?namespace=default`

This file has the image version used hard-coded to the very latest.

This creates a problem if you are having to use an older version of kafka that is no longer supported by this target version of the operator.  For example, our kafka supplier is Aiven and our cloud hosted environments are on kafka v3.3.1 which is no longer supported by the current operator v0.36.1.

### Suggested solution

Could we update this to support either of the following?

a) Support being able to reference previous versions of this manifest file (historical archive?).
b) Support passing the image version label as a parameter to this URL.

### Alternatives

I may have to copy/paste the entire manifest down and change the image version to the one we need locally.

### Additional context

If the historical archive files do actually exist, I couldn't find any reference to them in any of the documentation.  If that's the case, could the documentation be updated to make it clearer where to find such files.

**Comment by scholzj** [comment]
The option 2 does not make much sense. The operator is written to support selected Kafka versions. You cannot add another version just by changing the image. A hack like that might work in some situations, but certainly not for any random version.

The second option would be theoretically possible. But I'm not sure we want to maintain yet another mechanism to install the operator. There are already ways which allow what you are asking for:
* Helm Charts
* Operator Hub
* Release YAML files

Also, the URL installation is really intended only for the quickstart guides. So there is also no promise that this will never change how it works or the format of the URL.

----

I'm also not sure I understand why Aiven defines your Kafka version. Kafka consumers/producers have normally very good compatibility across different Kafka versions.

**Comment by rob-straughan** [comment]
In an ideal world our local development environment should behave the same as our deployment environments.  Aiven is on 3.3.1 and so our local instance of kafka should also be on that version.  Otherwise we run the risk that our local development could behave differently to our deployments, making replicating and fixing issues harder.

We've done some testing by upgrading our local kafka instance to the minimum supported by the latest operators (3.4.0) and checked the compatibility with our application's kafka client.  As far as we can tell this should be fine and does not appear to have any differences in behaviour.
