### ISSUE TITLE
[Enhancement]: Allow do download JDBC drivers just like plugins in kafka connect CRD

### ISSUE THREAD

**Issue by guitcastro** [strimzi/strimzi-kafka-operator#9009]
### Related problem

As today is possible to load and install plugins using when using KafkaConnect CRD. However a very common plugin is the JDBC Sinker which requires that you install the driver by downloading and put under the "jdbc_drivers" folders.

### Suggested solution

Allow to deploy specify a url or maven repository do download plugins jar, tar.gz, or zip just like the plugins itself. 

### Alternatives

None that I am aware

**Comment by scholzj** [comment]
I'm not sure I follow the issue. Many connectors use some kind of binaries with drivers for database connections and so far nobody reported an issue with that. You can just download them as any other artifact.

**Comment by guitcastro** [comment]
From JDBC connector [docs](https://docs.confluent.io/kafka-connectors/jdbc/current/jdbc-drivers.html):

> 
> The connector comes with JDBC drivers for a few database systems, but before you use the connector with other database systems, you must install the most recent JDBC 4.0 drivers for those database systems. Although the details vary for each JDBC driver, the basic steps are:
> 
>     Find the JDBC 4.0 driver JAR file for each database system that will be used.
>     Place the JAR files into the share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib directory in your Confluent Platform installation on each worker node.
> 

I don't thing creating another plugin enter with the JAR will work [because](https://docs.confluent.io/platform/current/connect/userguide.html#define-a-plugin):

> 
A Kafka Connect plugin is a set of JAR files containing the implementation of one or more connectors, transforms, or converters. Connect isolates each plugin from one another so libraries in one plugin are not affected by the libraries in any other plugins. This is very important when mixing and matching connectors from multiple providers.

**Comment by scholzj** [comment]
Strimzi is not based on the Confluent Platform. It is based on Apache Kafka. It uses its own path for the plugins. So no, you cannot place the plugins exactly in the paths used by Confluent. And I don't think need to follow their paths - most of their connectors that are open source as far as I know work fine with Apache Kafka.

To be honest, I'm still not sure what exactly is the problem you have apart from the Confluent path not existing in Strimzi. Maybe you should try to start by explaining what have you tried and what exactly you want Strimzi to do differently. Because from what you shared above, apart from the Confluent part I do not see anything that would strimzi not be able to do.

**Comment by guitcastro** [comment]
Sorry, English is not my first language. I might be confusing  you. 


What I want is to use the JDBC Sink Connector  plugin with a driver that is not include by default(clickhouse), which I assume is a common user case (but as you stated that no one ever complain, I might be wrong).

The JDBC plugin allow do load external drivers by putting in another directory using the `kafka-connect-jdbc` (which is not a confluent path):

> The share/java/kafka-connect-jdbc directory mentioned above is for Confluent Platform. If you are using a different installation, find the location where the Confluent JDBC Source or Sink connector JAR files are located, and place the JDBC driver JAR file(s) for the target databases into the same directory.`.

So, today. I think is not possible to add a jar in the folder, right? 

You mentioned that I can create two plugins, one for the JDBC and other one for the driver. However I don't thing it will worked because the classpath are isolated (By the kafka connect, not confluent platform).

**Comment by scholzj** [comment]
> You mentioned that I can create two plugins, one for the JDBC and other one for the driver. However I don't thing it will worked because the classpath are isolated (By the kafka connect, not confluent platform).

That is not what I mentioned. Every plugin consists of multiple artifacts. So you just add it as another artifact.

> Sorry, English is not my first language. I might be confusing you.

No worries. But if you share the actual `KafkaConnect` custom resource you use, it will be easier to tall about the exact YAML.

**Comment by guitcastro** [comment]
> That is not what I mentioned. Every plugin consists of multiple artifacts. So you just add it as another artifact.

Ohh, Awesome!! Now I get it, thanks for much for the help. I am closing the issue then ;)
