### ISSUE TITLE
Produce and Consume message externally using Openshift cluster with strimzi

### ISSUE THREAD

**Issue by archupsg03** [strimzi/strimzi-kafka-operator#9029]
### Discussed in https://github.com/orgs/strimzi/discussions/4099

<div type='discussions-op-text'>

<sup>Originally posted by **scholzj** December 14, 2020</sup>

I have openshift cluster installed with strimzi operator. I need to externally access strimzi. I tried creating routes / load balancers , I was not able to connect. Is there any proper documentation that I can follow ? or can you guide me doing that
</div>

**Comment by scholzj** [comment]
This is not an issue! The instructions when opening issues are quite clear about it! It also seems like something what you asked about on Slack. So why do you open it in another place in parallel?!
