### ISSUE TITLE
[Bug]: KafkaRoller fail to return the result

### ISSUE THREAD

**Issue by oudb** [strimzi/strimzi-kafka-operator#9046]
### Bug Description

in method rollingRestart，when order the nodes by calling podOperations.isReady, then isReady throw some exception，the code do not handle it well， it should shutdown the singleExecutor and fail the result. so the reconciliation will be nerver
 terminate.  the next reconciliation will fail to acquire lock.

### Strimzi version

0.36.1

### Kubernetes version

Kubernetes 1.22

**Comment by scholzj** [comment]
Thanks for raising this. Can you please share some operator logs of it happening? It would help to understand what exactly and where is happening. Thanks.

**Comment by oudb** [comment]
@scholzj 

the log is:
2023-08-29 19:23:29 DEBUG AbstractOperator:383 - Reconciliation #288(timer) Kafka(ns/test): Try to acquire lock lock::ali-strimzi-kafka::Kafka::alikafka-post-cn-gb
2023-08-29 19:23:29 DEBUG AbstractOperator:386 - Reconciliation #288(timer) Kafka(ns/test): Lock lock::ali-strimzi-kafka::Kafka::alikafka-post-cn-gb acquired
2023-08-29 19:23:29 INFO  AbstractOperator:257 - Reconciliation #288(timer) Kafka(ns/test): Kafka alikafka-post-cn-gb will be checked for creation or modification
2023-08-29 19:23:30 DEBUG KafkaRoller:252 - Reconciliation #288(timer) Kafka(ns/test): Verifying cluster pods are up-to-date.

log should ouput,but never:
Initial order for updating pods (rolling restart or dynamic update) is xxxxx

I guess the code can not handle well：
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/6326847/ac46f391-7ba5-45b3-990d-665eb7c33968)

**Comment by scholzj** [comment]
I think it would be useful to see the full log with the exception. The 4 lines you shared above do not suggest anything wrong. While it indeed seems this exception might not be handled, I do not think it is really clear what is happening in the code.

**Comment by oudb** [comment]
I add some code to catch the exception：
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/6326847/7fc5f2c7-f7a2-4cf4-ab85-151a67b649ed)

the log output：
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/6326847/550da490-daab-47ab-99c7-bc89a585bf52)

the excepction detail is：
[2023-08-30 13:44:25]
content: 2023-08-30 13:44:25 INFO  KafkaRoller:269 - Reconciliation #877(watch) Kafka(ali-strimzi-kafka/alikafka-post-cn-jxgffjofjfhelr1): sort nodes:[alikafka-post-cn-jxgffjofjfhelr1-32-2000-2000/2000, alikafka-post-cn-jxgffjofjfhelr1-32-2000-2001/2001] error

+1
[2023-08-30 13:44:25]
content: io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [alikafka-post-cn-jxgffjofjfhelr1-32-2000-2001]  in namespace: [ali-strimzi-kafka]  failed.

+2
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:159) ~[io.fabric8.kubernetes-client-api-6.7.2.jar:?]

+3
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:187) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+4
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:141) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+5
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:92) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+6
[2023-08-30 13:44:25]
content: 	at io.strimzi.operator.common.operator.resource.AbstractReadyNamespacedResourceOperator.isReady(AbstractReadyNamespacedResourceOperator.java:65) ~[io.strimzi.operator-common-0.36.1-0.0.1-DEV.jar:0.36.1-0.0.1-DEV]

+7
[2023-08-30 13:44:25]
content: 	at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$rollingRestart$4(KafkaRoller.java:264) ~[io.strimzi.cluster-operator-0.36.1-0.0.1-DEV.jar:0.36.1-0.0.1-DEV]

+8
[2023-08-30 13:44:25]
content: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]

+9
[2023-08-30 13:44:25]
content: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]

+10
[2023-08-30 13:44:25]
content: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]

+11
[2023-08-30 13:44:25]
content: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]

+12
[2023-08-30 13:44:25]
content: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]

+13
[2023-08-30 13:44:25]
content: 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

+14
[2023-08-30 13:44:25]
content: Caused by: java.io.IOException: /192.168.168.166:42996: GOAWAY received

+15
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:515) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+16
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+17
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:478) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+18
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:741) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+19
[2023-08-30 13:44:25]
content: 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:185) ~[io.fabric8.kubernetes-client-6.7.2.jar:?]

+20
[2023-08-30 13:44:25]
content: 	... 10 more

+21
[2023-08-30 13:44:25]
content: Caused by: java.io.IOException: /192.168.168.166:42996: GOAWAY received

+22
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection.handleGoAway(Http2Connection.java:1008) ~[java.net.http:?]

+23
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection.handleConnectionFrame(Http2Connection.java:873) ~[java.net.http:?]

+24
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection.processFrame(Http2Connection.java:748) ~[java.net.http:?]

+25
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.frame.FramesDecoder.decode(FramesDecoder.java:155) ~[java.net.http:?]

+26
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection$FramesController.processReceivedData(Http2Connection.java:232) ~[java.net.http:?]

+27
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection.asyncReceive(Http2Connection.java:674) ~[java.net.http:?]

+28
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.processQueue(Http2Connection.java:1310) ~[java.net.http:?]

+29
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]

+30
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]

+31
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]

+32
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303) ~[java.net.http:?]

+33
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256) ~[java.net.http:?]

+34
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.runOrSchedule(Http2Connection.java:1328) ~[java.net.http:?]

+35
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1354) ~[java.net.http:?]

+36
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.Http2Connection$Http2TubeSubscriber.onNext(Http2Connection.java:1288) ~[java.net.http:?]

+37
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SSLTube$DelegateWrapper.onNext(SSLTube.java:210) ~[java.net.http:?]

+38
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:492) ~[java.net.http:?]

+39
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNext(SSLTube.java:295) ~[java.net.http:?]

+40
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:316) ~[java.net.http:?]

+41
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:259) ~[java.net.http:?]

+42
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]

+43
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]

+44
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]

+45
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303) ~[java.net.http:?]

+46
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256) ~[java.net.http:?]

+47
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:232) ~[java.net.http:?]

+48
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:198) ~[java.net.http:?]

+49
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:444) ~[java.net.http:?]

+50
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:268) ~[java.net.http:?]

+51
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205) ~[java.net.http:?]

+52
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149) ~[java.net.http:?]

+53
[2023-08-30 13:44:25]
content: 	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]
