### ISSUE TITLE
Controllers creation can cause metadata lost on ZooKeeper based cluster using node pools

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#9108]
I ran the following scenario ...

Create a ZooKeeper based Kafka cluster. Operator running without node pools nor KRaft feature gates enabled. Create some topics. Going into the shell of any of the brokers I can see the topics (even not using localhost:9092 but the bootstrap service):

```shell
[kafka@my-cluster-kafka-0 kafka]$ bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
my-topic-1
my-topic-2
my-topic-3
```

Now, apply the migration to use the node pools (for running the brokers but still ZooKeeper based) as per the [documentation](https://strimzi.io/docs/operators/latest/deploying#proc-migrating-clusters-node-pools-str).
Everything is fine.

Enable KRaft on the operator. As we know the operator will log this warning which is fine.

```shell
io.strimzi.operator.common.model.InvalidResourceException: Tha Kafka cluster my-cluster is invalid: [At least one KafkaNodePool with the controller role and at least one replica is required when KRaft mode is enabled]
```

Now create a node pool with controllers.
The operator deploys the controllers and, in my test, it was able to roll one of the brokers (configuring it with the connection to the KRaft quorum) but not the other two due to following which would make sense (?).

```shell
2023-09-12 09:14:19 INFO  KafkaRoller:576 - Reconciliation #7(watch) Kafka(kafka/my-cluster): Rolling Pod my-cluster-kafka-0/0 due to [Pod has old revision]                                                                               
2023-09-12 09:14:19 INFO  KafkaAvailability:135 - Reconciliation #7(watch) Kafka(kafka/my-cluster): my-topic-2/0 will be under-replicated (ISR={0,2}, replicas=[0,2,1], min.insync.replicas=2) if broker 0 is restarted.                   
2023-09-12 09:14:19 WARN  KafkaRoller:440 - Reconciliation #7(watch) Kafka(kafka/my-cluster): Pod my-cluster-kafka-0/0 can't be safely force-rolled; original error:                                                                       
2023-09-12 09:14:19 INFO  KafkaRoller:328 - Reconciliation #7(watch) Kafka(kafka/my-cluster): Could not verify pod my-cluster-kafka-0/0 is up-to-date, giving up after 10 attempts. Total delay between attempts 127750ms                  
io.strimzi.operator.cluster.operator.resource.KafkaRoller$ForceableProblem: Pod my-cluster-kafka-0 is controller and there are other pods to verify. Non-controller pods will be verified first 
```

Result ... one broker (the rolled one) is now connected to the KRaft quorum and it has no metadata about previously created topics. Other two are still using ZooKeeper because not rolled. Depending on where your request about metadata lands, you can get that topics don't exist (you hit the rolled broker using KRaft quorum) or they exist (you hit the not-rolled brokers still using ZooKeeper).
For example on a not rolled broker using the bootstrap service ...

```shell
[kafka@my-cluster-kafka-0 kafka]$ bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
my-topic-1
my-topic-2
my-topic-3
[kafka@my-cluster-kafka-0 kafka]$ bin/kafka-topics.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --list
my-topic-1
my-topic-2
my-topic-3
[kafka@my-cluster-kafka-0 kafka]$ bin/kafka-topics.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --list
my-topic-1
my-topic-2
my-topic-3
[kafka@my-cluster-kafka-0 kafka]$ bin/kafka-topics.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --list

[kafka@my-cluster-kafka-0 kafka]
```

Notice last query. It ended to the rolled broker using KRaft with no metadata.
I confirmed it by running the same topics listing command on each broker (rolled and not) by using localhost:9092 as well.

**Comment by scholzj** [comment]
I don't understand why are you opening an issue for this. The current Kraft mode is designed to be used only for new clusters. So this is not a bug in any way. This is also clearly stated in the documentation.

**Comment by ppatierno** [comment]
While this situation should be avoided when the user would apply the migration annotation as proposed in the https://github.com/strimzi/proposals/pull/90, it seems to be a problem in the current operator (or even when the migration is in place but the user forget to apply the migration annotation before creating the controllers node pools).

**Comment by scholzj** [comment]
No, it is not a problem. It is a known and intentional limitation of the feature gate designed for development and testing only.

**Comment by ppatierno** [comment]
> I don't understand why are you opening an issue for this. The current Kraft mode is designed to be used only for new clusters. So this is not a bug in any way. This is also clearly stated in the documentation.

I opened an issue to avoid polluting the migration proposal because we wanted to discuss more.
Taking what you are saying, you are just considering this a UX/user problem and not an operator issue? Is it what you mean? If the user makes this mistake how is he supposed to recover.

**Comment by scholzj** [comment]
We specifically say that this is not supported and you should not do it. And there are several things you need to do to not run into it by coincidence. There is nothing to discuss here from my point of view.

**Comment by fvaleri** [comment]
I can confirm the issue, but with a slightly different behavior. In my test, all Kafka brokers were eventually rolled, so I completely lost cluster metadata. [cluster-operator.log.tar.gz](https://github.com/strimzi/strimzi-kafka-operator/files/12585273/cluster-operator.log.tar.gz)

```sh
$ kubectl get po
NAME                                          READY   STATUS    RESTARTS   AGE
my-cluster-controller-3                       1/1     Running   0          40m
my-cluster-controller-4                       1/1     Running   0          40m
my-cluster-controller-5                       1/1     Running   0          40m
my-cluster-entity-operator-68c45754b6-klt68   2/2     Running   0          25m
my-cluster-kafka-0                            1/1     Running   0          29m
my-cluster-kafka-1                            1/1     Running   0          27m
my-cluster-kafka-2                            1/1     Running   0          26m
my-cluster-zookeeper-0                        1/1     Running   0          52m
my-cluster-zookeeper-1                        1/1     Running   0          52m
my-cluster-zookeeper-2                        1/1     Running   0          52m
strimzi-cluster-operator-674c5cc4c-dsxkr      1/1     Running   0          44m

$ kubectl exec my-cluster-kafka-0 -- bin/kafka-topics.sh --bootstrap-server :9092 --list

$ kubectl exec my-cluster-kafka-1 -- bin/kafka-topics.sh --bootstrap-server :9092 --list

$ kubectl exec my-cluster-kafka-2 -- bin/kafka-topics.sh --bootstrap-server :9092 --list

```

This scenario is not supported right now, but I think we want to avoid our users to shoot themself in the foot as much as possible. This could be easily fixed by setting the controller's KRaft migration configurations when the pool is connected to a ZK-based cluster (which means the controller will run in dual-write mode). We can make this part of the migration proposal.

**Comment by fvaleri** [comment]
To clarify, when we are not in ZK to KRaft migration mode, we could check if the target Kafka cluster is ZK-based by inspecting the Kafka ConfigMap. In that case, the controller NodePool reconciliation would fail with an appropriate message.

Instead, when we are in migration mode, we could add the Kafka migration configurations and roll the pods (controllers first, then brokers) to enable dual-write mode.

**Comment by ppatierno** [comment]
Taking into account the state of the art of the KRaft feature gate, its current behaviour, expectations and how it's going to be improved with proposal [PR#93](https://github.com/strimzi/proposals/pull/93), I think we can close this one.

**Comment by ppatierno** [comment]
I would like to reopen this, because even if it wasn't the current behaviour and expectations, I would like to highlight that this will be handled differently with https://github.com/strimzi/proposals/pull/93

Testing scenario by using the code in https://github.com/strimzi/strimzi-kafka-operator/pull/9141, and following the above steps, when the user creates the controllers pool, the operator doesn't restart and configure broker to use KRaft but it logs:

```shell
io.strimzi.operator.common.model.InvalidResourceException: Tha Kafka cluster my-cluster is invalid: [KafkaNodePool controller contains invalid roles configuration. In a ZooKeeper-based Kafka cluster, the KafkaNodePool role has to be a │
│ lways set only to the 'broker' role.]
```

This is actually right. The user is trying to applying KRaft related stuff (controllers) on a ZooKeeper-based cluster which is detected by the logic described in https://github.com/strimzi/proposals/pull/93.

I will close this issue when the PR will be merged.

**Comment by scholzj** [comment]
I think there is no need for this issue. You are addressing this in your proposal and until that, this is works as designed. Also, how does it _lose metadata_ when the validation fails?

**Comment by ppatierno** [comment]
I removed the needs-triage after closing it! I don't think it should have been there anymore after closing an issue or?
I don't see this as a big deal having this opened, but if you like I will close again, important is that I tracked I this was "fixed" with the upcoming proposal.
