### ISSUE TITLE
[Bug]: The UnidirectionalTopicOperator does not support reconciliation pausing

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#9113]
### Bug Description

Adding the `strimzi.io/pause-reconciliation: "true"` does not pause the reconciliation when using the UnidirectionalTopicOperator (UTO). This feature is documented for all Strimzi custom resources, and it works on the BidirectionalTopicOperator.

### Steps to reproduce

1. Deploy a cluster with the `UnidirectionalTopicOperator` feature gate enabled
2. Create a new topic t1 and wait for reconciliation
3. Annotate t1 with `strimzi.io/pause-reconciliation: "true"`
4. Edit t1 and increase the partition number

### Expected behavior

No reconciliation should happen when a `KafkaTopic` has the `strimzi.io/pause-reconciliation: "true"` annotation.

### Strimzi version

main

### Kubernetes version

1.25

**Comment by im-konge** [comment]
@fvaleri I talked with @tombentley about this a while ago and IIRC it was decided to _not support_ `pause-reconciliation` and instead use `managed-by` https://github.com/strimzi/proposals/pull/76#discussion_r1138292072

Correct me if I'm wrong Tom please.

**Comment by fvaleri** [comment]
@im-konge thanks for linking to that relevant discussion.

I think you mean the `strimzi.io/managed` (true|false) annotation, which can be used to un-manage a KafkaTopic resource. IMO, we need two different annotations. The `strimzi.io/pause-reconciliation` should keep the same behavior we have in the BTO and CO.

Like Tom, I also think that un-manage and pause are two fundamentally different operations. If I the topic is paused and I delete it, then it will be also deleted in Kafka. If the topic is un-managed and I delete it, then only the Kube resource will be garbage collected, but the topic will still exists in Kafka.

**Comment by im-konge** [comment]
Ah yes, makes sense. I hit this issue when I was enabling STs to work with UTO, but yeah I thought that it is not supported in UTO. Thanks for raising this.

**Comment by tombentley** [comment]
Yeah, I guess it would make sense to keep this.
