### ISSUE TITLE
[Enhancement]: Support resetting offsets for KafkaConnect

### ISSUE THREAD

**Issue by davido912** [strimzi/strimzi-kafka-operator#9158]
### Related problem

Currently in order to reset offsets one has to use the CLI/ rename the connector. 

### Suggested solution

It seems this is already implemented in later [versions of KafkaConnect ](https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect). The Strimzi KafkaConnect version seems to be lagging if I'm not wrong. 

Are there plans to implement any feature for resetting connectors offsets? That'd be great

### Alternatives

- CLI resetting (not amazing)
- Custom tooling
- Renaming connector (results in a lot of trash in config topics and cluster)

**Comment by scholzj** [comment]
Kafka 3.6.0 where this seems to be implemented is not released yet. 

You should probably also clarify what do you expect Strimzi to do with it. I think nothing will prevent you from resetting the offset manually. But it would be good to understand the ideas you have for any tighter integration of this feature into Strimzi.

**Comment by scholzj** [comment]
Ok, no worries. We can keep the issue and see what ideas will other some up with.

**Comment by dadufour** [comment]
We are interested in this feature as well - but to be honest, I am not sure how this should be supported by strimzi.

The use case we have is the following (not yet experimented at this level):
existing MirrorMaker2 replication from A to B
We want to be able to stop this replication then put in place a new replication from A to C which starts at the offset where the previous stopped. The goal is that (B + C) contains all the messages from A, without loss and without doubles.

**Comment by katheris** [comment]
Now this is in Kafka we should talk about how it could be supported in Strimzi. I'm going to raise a proposal PR next week to start the discussion so assigning this issue to myself.

**Comment by vladislav-bakanov** [comment]
@katheris, hi! Is there any news about this feature?

**Comment by katheris** [comment]
@vladislav-bakanov the proposal is currently being discussed https://github.com/strimzi/proposals/pull/121
