### ISSUE TITLE
[Enhancement]: Enable Prometheus metrics on standalone topic operator

### ISSUE THREAD

**Issue by pdalpra** [strimzi/strimzi-kafka-operator#9193]
### Related problem

As I am currently setting up the standalone topic operator in (UTO mode) in production at my workplace, I'm trying to collect metrics through Prometheus from the operator.

I noticed that while the topic operator exposes [`/ready`,`/healthy`,`/metrics`) through `HealthCheckAndMetricsServer`](https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/main/java/io/strimzi/operator/common/http/HealthCheckAndMetricsServer.java), `/metrics` returns a [501 Not Implemented](https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/main/java/io/strimzi/operator/common/http/HealthCheckAndMetricsServer.java#L162-L168) as the [`metricsProvider` is set to `null` when the server constructor is called](https://github.com/strimzi/strimzi-kafka-operator/blob/main/topic-operator/src/main/java/io/strimzi/operator/topic/v2/TopicOperatorMain.java#L58).

### Suggested solution

If possible, setup the metrics provider for the topic operator like [it is done for the user operator](https://github.com/strimzi/strimzi-kafka-operator/blob/e54522b91c9284dd1f8e1d4b19eb3df403c6ba53/user-operator/src/main/java/io/strimzi/operator/user/Main.java#L177-L188).

**Comment by scholzj** [comment]
This is also tracked in #8650. Or did you have something more specific in mind?

**Comment by pdalpra** [comment]
Sorry, I missed those issues 🤦‍♂️ 
The initial idea was even less specific than dedicated metrics, merely the JVM metrics, but since you're adding dedicated metrics, it's even better.
I'm closing the issue then, no point in laying my duplicated request around 👍
