### ISSUE TITLE
External client connectivity with Kafka amq running on Openshift

### ISSUE THREAD

**Issue by himmatb** [strimzi/strimzi-kafka-operator#920]
Hi Team,

I am facing issue regarding connectivity with Redhat amq kafka connectivity from external client using Nodeport service type.

Strimzi Version : strimzi-0.7.0
openshift Version : 3.9

Below Configuration changes done for enabling NodePort in configuration: 
kafka_strimzi-0.7.0/strimzi-0.7.0/examples/kafka/kafka-ephemeral.yaml 

spec:
  kafka:
    replicas: 1
    listeners:
      plain: {}
      #tls: {}
      **external:
        type: nodeport**
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
.......... so on

created a route  

Route / Node Port |   | Service Port |   | Target Port | Hostname | TLS Termination
-- | -- | -- | -- | -- | -- | --
kafka-amq-external-bootstrap / 32562 |   | 9094/TCP (external) |   | 9094 | http://kafka-amq-external-bootstrap-xxxxx.com |  

I have used configuration of route to connect from external client:

kafka-amq-external-bootstrap-xxxxx.com:32562 

<source>
   @type tail
   #path /opt/app/fluentd_links/finbroker.log
   #path /opt/test-logs/finbroker.log
   path /etc/fluent/aaa
   #pos_file /var/fluentd/file2
   tag tibcologs-finbroker
   read_from_head true
   format none
</source>

<match tibcologs-finbroker>
   @type kafka
   brokers "kafka-amq-external-bootstrap-xxxx.com:32562"
   default_topic topic-finbroker-2
   output_data_type json
</match>

also i have provided host entry in hosts file.
Getting below Error to connect with openshift externally : 

2018-10-02 10:40:25 +0400 [warn]: #0 emit transaction failed: error_class=Kafka::ConnectionError error="Could not connect to any of the seed brokers:\n- kafka://kafka-amq-external-bootstrap-xxxx.com:32562: Connection error EOFError: EOFError" location="/usr/local/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.6.7/lib/kafka/cluster.rb:407:in `fetch_cluster_info'" tag="tibcologs-finbroker"

I am using other kafka with same configuration provided for but its connecting properly.

Please help me to find out root cause for this issue.

**Comment by scholzj** [comment]
Judging by the `EOFError` ... I wonder if you configured TLS in Fluentd. In 0.7.0, all the external connections are always encrypted with TLS. In master and upcomming 0.8.0 it will be possible to use nodeports or loadbalancers also without TLS (Routes will keep using TLS to mask the TCP traffic as HTTPS :-o).
