### ISSUE TITLE
[Enhancement]: kafka-exporter make offset lag for disconnected consumers configuratble

### ISSUE THREAD

**Issue by msillence** [strimzi/strimzi-kafka-operator#9231]
### Related problem

currently offset.show-all is hardcoded to true

This means we collect stats on consumers that are no longer connected

We would like it to be configurable to turn it off

### Suggested solution

Add a new flag to allow turning off the offset.show-all

### Additional context

We are not interested in consumers that are no longer connected and can use other mechanisms to detect dead consumers if they are still required.

The default for expiring dead consumer groups is 1 week which means these stats hang around with the lag continually growing disrupting our ability to see real issues.

**Comment by scholzj** [comment]
Discussed on the Community call on 19.10.2023: Seems reasonable. Should be implemented.

**Comment by mabulgu** [comment]
Hi @scholzj . My friend @ilkerkocatepe  wants to work on this issue. I will try to guide him as we have been on a mentorship program recently. Would it be ok with you if he takes this one as it seems a good start issue?

**Comment by scholzj** [comment]
@ilkerkocatepe this issue should be available, so feel free to work on it. I think the changes here would be very similar to #8682. So looking at that might be the best start. Feel free to let me know if you would have any questions.
