### ISSUE TITLE
We should clarify the installation of topic and user operator 

### ISSUE THREAD

**Issue by christian-posta** [strimzi/strimzi-kafka-operator#925]
It's not clear based on the getting started documentation whether to install the topic and user operator. Right now, it takes up quite a big chunk of the Table of Contents but in reality it sounds like those operators are really geared toward operating an existing and possibly external Kafka cluster. We should move that to a section specifically identified as "operating an external cluster".

**Comment by PaulRMellor** [comment]
_Overview_ guide describes the purpose of Strimzi operators.
- [Strimzi Operators](https://strimzi.io/docs/operators/in-development/overview.html#overview-components_str)

_Deploying_ guide has procedures that describe how to deploy the operators when creating a Kafka cluster, a well as standalone installs for use with a Kafka cluster that is not managed by Strimzi. 
- [Create the Kafka cluster](https://strimzi.io/docs/operators/in-development/deploying.html#deploy-create-cluster_str)
- [Deploy the standalone Topic Operator](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-the-topic-operator-standalone-str)
- [Deploy the standalone User Operator](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-the-user-operator-standalone-str)
