### ISSUE TITLE
Tiered storage support

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9259]
From 3.6.0, Apache Kafka supports tiered storage (as early access currently). We should add support for it to Strimzi. 

There are several aspects that would need to be clarified:
* Do we need a dedicated API for it in the Kafka CR? Or can it be controlled through `Kafka.spec.kafka.config`?
  * Requiring an API will mean lot less flexibility as the API will control some options
  * Having an API will make it easier to use for users and to document it in Strimzi docs
  * It looks like most plugins would use the `TopicBasedRemoteLogMetadataManager` that creates a Kafka topic and uses it as a client. Bootstraping such clients including security is super hard from `Kafka.spec.kafka.config`. So these plugins would need some API support to let Strimzi configure the bootstraping of the Kafka client to the replication listener including the security.
* Kafka will not include any plugins. All plugins will be third party only.
  * Some of the plugins might require additional security configuration (e.g. AWS key and secret). Should these be part of the API? Should we let the users use config providers for those?
  * Should some of the plugins be bundled in Strimzi?
    * If yes, which ones and what would be the testing strategy?
    * If not, what is the expected mechanism for adding plugins? I assume custom Dockerfile as we do not want to have here some automated mechanism as with Connect.

These (and possibly other points) should be clarified in a proposal.

----

It would be also to have some more clarify of the possible future directions ...
* Any chance to use multiple plugins in parallel? E.g. one for local HDFS storage for topic A and one for S3 storage in the cloud for topic B?
* How will the plugins evolve? E.g. AWS S3 bucket configuration per cluster versus per-topic etc.

**Comment by scholzj** [comment]
Discussed on the Community call on 19.10.2023: 
* We want the tired storage to be supported. Proposal should be written.
* @mimaison and @showuon think the security bootstrapping of the Kafka client should work without needing any new configuration. Jakub will try to reproduce the issue he had with it and share the logs.

**Comment by gaobosince1987** [comment]
what do you think about this?

Do we need a dedicated API for it in the Kafka CR? Or can it be controlled through Kafka.spec.kafka.config?

> Regular tier storage configuration can be passed through Kafka.spec.kafka.config, security related configuration can be generated by Strimzi then added into static config in kafka_run.sh.

Some of the plugins might require additional security configuration (e.g. AWS key and secret). Should these be part of the API? Should we let the users use config providers for those?

> No, tier storage plugin specific parameters can be passed in through Kafka.spec.kafka.config.  Aws key and secret can be handled in customer plugin code by reading kafka static config.

Should some of the plugins be bundled in Strimzi?

> No, tier storage specific plugin can be added into Strimzi by using strimzi provided kafka as base image then add Dockerfile layer to include plugins to specific folder and config the folder in static configuration for tier storage feature to load

**Comment by scholzj** [comment]
That is what the proposal has to clarify.

**Comment by gaobosince1987** [comment]
who is drafting the proposal? we have run tier storage feature with strimzi for some time, we can share how we did it and provide input to the proposal if interested.

**Comment by scholzj** [comment]
How have you run it when the tiered storage support was added only in Kafka 3.6 and even there is only a _preview_? Also, nothing changed in Strimzi to prevent whatever way you used to run it. But I think that if you want, you can definitely work on this and prepare the proposal and contribute the code if it is approved. I guess the main questions it needs to answer are in the issue description.

**Comment by scholzj** [comment]
Support for custom tiered storage plugins ("bring your own") has been added in #9727. In the future as the tiered storage support in Kafka evolves, we might add a dedicated support for custom plugins such as S3 or HDFS etc. These should be subject to separate proposals and issues.
