### ISSUE TITLE
[Bug]: Deleting and re-creating a topic with the same name, offset not reset

### ISSUE THREAD

**Issue by jbnjohnathan** [strimzi/strimzi-kafka-operator#9269]
### Bug Description

We have a topic `logs`
We delete the topic `logs`
We create a new topic with the same name, `logs`
The same consumer group is used
When checking the offset for the topic it has a negative value, so it was not reset to zero after the topic was deleted.

### Expected behavior

When deleting a topic, we expect the offset to be removed from the consumer group for that specific topic

### Strimzi version

0.35.1

### Kubernetes version

1.25

### Installation method

helm

### Infrastructure

OpenShift

### Additional context

This issue from kafka that has resolution: Won't fix
https://issues.apache.org/jira/browse/KAFKA-4095

This comment on stackoverflow which says that this was solved in Confluent in 2017
https://stackoverflow.com/a/42585781

**Comment by scholzj** [comment]
This is clearly not a Strimzi bug. At best it might be an enhancement. But to be honest, if Kafka decided to reject this, I do not think we would go and contradict it in any way.

**Comment by jbnjohnathan** [comment]
Yeah you are right. I was first thinking that strimzi would take care of this but since it does not support it is by design as it is now.
It would be a good feature however as replication factor is something a user could want to change on a topic and the current method is a bit on the complicated side and needs a lot of manual steps.

**Comment by scholzj** [comment]
> It would be a good feature however as replication factor is something a user could want to change on a topic and the current method is a bit on the complicated side and needs a lot of manual steps.

I getting a bit lost. Changing the replication factor of topics already has an open issue: https://github.com/strimzi/strimzi-kafka-operator/issues/191. But that has nothing to do with removing the committed offsets.

**Comment by ppatierno** [comment]
Discussed on the Community call on 19.10.2023: going to close because it's actually how it works in Kafka, so not related to Strimzi.
