### ISSUE TITLE
Include example fragments in doc for "CO deploys (TO|UO)"

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#928]
In the documentation [here](http://strimzi.io/docs/0.7.0/#deploying-the-topic-operator-using-the-cluster-operator-str) and similarly for the UO case, we should include an example fragment of the `Kafka` resource rather than just referring by the path `Kafka.spec.entityOperator.topicOperator` to what the `Kafka` resource needs to include for it to deploy the TO/UO.

**Comment by PaulRMellor** [comment]
The deployment instructions now include an example fragment of the `Kafka` resource, plus a link to the _EntityTopicOperatorSpec schema reference_.

- [Deploying the Topic Operator using the Cluster Operator](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-the-topic-operator-using-the-cluster-operator-str)
- [Deploying the User Operator using the Cluster Operator](https://strimzi.io/docs/operators/in-development/deploying.html#deploying-the-user-operator-using-the-cluster-operator-str)
