### ISSUE TITLE
[Bug]: cannot add an additional variable for JMX to the broker

### ISSUE THREAD

**Issue by bth8939** [strimzi/strimzi-kafka-operator#9280]
### Bug Description

Hello,

I would like to know how to expose the broker JMX outside the kubernetes cluster by deleting the jmxremote.ssl (exposure works but with ssl). 

the goal  is to be able to supervise metrics with zabbix 

In short, I would like to have these parameters at the broker boot: 

-Dcom.sun.management.jmxremote.port=9999 \
 -Dcom.sun.management.jmxremote.rmi.port=9999 \
 -Dcom.sun.management.jmxremote.local.only=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dcom.sun.management.jmxremote.ssl=false 

This is my configuration:

`template:
    kafkaContainer:
      env:
      - name: JMX_PORT
        value: '9999'
      - name: KAFKA_JMX_OPTS
        value: '-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false '

Thank for your help. 

`

### Strimzi version

strimzi-kafka-operator-0.1.0

### Kubernetes version

v1.24.16-eks-2d98532

### Installation method

helm

### Infrastructure

Amazon EKS

**Comment by scholzj** [comment]
I assume the Strimzi 0.1.0 is just some typo?

We support exposing of JMX using the `jmxOptions` field. We do not support any other way of exposing JMX or any advanced configurations. That said, we do not use SSL for JMX, so you should not need to change anything with regard to that.

**Comment by ppatierno** [comment]
Discussed on the Community call on 02.11.2023: @k-wall is going to take a look at this because something that he already faced in the past.

**Comment by scholzj** [comment]
What is there to look into? I do not think there is enough information here to work on this and more details need to be provided by the user.

**Comment by k-wall** [comment]
Sorry, the comment recorded yesterday during triage gave the wrong impression of my intent.

It was some of the words in the issue resonated with me.  I thought I might have had some additional information to share, over what @scholzj had said already.   It turns out, I don't have anything more to add beyond `jmxOptions` already suggested.

I agree there is nothing more that can be done unless further clarification from the user.

**Comment by scholzj** [comment]
Discussed on the community call on 30.11.2023: As discussed in the previous comments, to expose JMX, you should use the `jmxOptions` field and not configure the environment variables directly.
