### ISSUE TITLE
[Enhancement]: Strimzi support SASL for tier storage remote log metadata common client

### ISSUE THREAD

**Issue by gaobosince1987** [strimzi/strimzi-kafka-operator#9310]
### Related problem

One issue related to tier storage remote log metadata common client is how to specify SSL_TRUSTSTORE_PASSWORD_CONFIG/SSL_KEYSTORE_PASSWORD_CONFIG in config if kafka server turned on SASL. When we use strimzi to manage the secrets,  we can not use the RLMM static configuration because the password are dynamically loaded.

### Suggested solution

have a way to specify SSL secret through existing RLMM static configuration through Strimzi or integrate with Kafka to dynamically load SSL secret

### Alternatives

I think I can get it from STRIMZI_CERT_STORE_PASSWORD env variable, but that need code change in kafka tier storage client setup to read from the env variable.

**Comment by scholzj** [comment]
There is already an issue covering tiered storage support. So why do we need another one?

**Comment by gaobosince1987** [comment]
I am not sure if the proposal have the issue covered, do you have a pointer to such proposal?

**Comment by scholzj** [comment]
There is no proposal. There is an issue saying that a proposal will be needed to clarify all the details.

**Comment by ppatierno** [comment]
Discussed on the Community call on 02.11.2023: going to close this one, because as Jakub said we already have a related issue https://github.com/strimzi/strimzi-kafka-operator/issues/9259 which needs a proposal.
