### ISSUE TITLE
[Enhancement]: Update Grafana version in example to 7.5.17 and change graphs to time-series

### ISSUE THREAD

**Issue by katheris** [strimzi/strimzi-kafka-operator#9317]
### Related problem

The Grafana version listed in the example grafana.yaml file is 7.3.7. The latest Grafana version is now 10.2.0 so this is now a very old version.

### Suggested solution

We should update this to 7.5.17 as this is the latest Grafana version that is licensed with Apache 2.0. At the same time we should update all the dashboards to change the `graph` visualisations to `time-series` since `graph` has been deprecated and will be removed in a future version of Grafana.

### Alternatives

We could update the Grafana version to the latest, but since this requires a new license it's preferable to pick a version that lets us use the new `time-series` visualisations while also using a Grafana version with the Apache license.

**Comment by scholzj** [comment]
Latest Grafana releases are not OpenSource anymore. So I don't think we
want to use any of the versions with proprietary license.

**Comment by katheris** [comment]
I think they are still OpenSource, but not using the Apache 2.0 license, the latest one with an Apache license is 7.5.17, so potentially not worth updating if we don't want to use one that has the AGPLv3 license

**Comment by scholzj** [comment]
I thought it is proprietary and not AGPL. But even AGPL is an issue for
many users as far as I know. So I guess nothing technically prevents us
from upgrading it. But still not sure we want to do it.

**Comment by ppatierno** [comment]
Discussed on the Community call on 02.11.2023: let's leave this open for more discussion across maintainers and community. Question came from @k-wall if there is any implication of using something which is not Apache 2.0 license within a CNCF project. Some reference here: https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
Also @katheris raised the point about we are not including Grafana itself but just a dashboard with a specific version (which could be even for a newer version with a different license).

**Comment by scholzj** [comment]
> Also @katheris raised the point about we are not including Grafana itself but just a dashboard with a specific version (which could be even for a newer version with a different license).

Well, that is true. But keep in mind that many of our users will have the same license concerns and might not be able to use such dashabords.

**Comment by katheris** [comment]
It looks like the `time-series` visualisation was introduced in beta in version 7.4 of Grafana, so actually if we update to the last Apache licensed version of 7.5.17 then we could change the `graph` visualisations in our Grafana dashboards to `time-series` instead and then anyone using the latest version wouldn't see deprecation warnings. I did a quick test with the Connect dashboard and it looks like it's a fairly straight forward change

**Comment by scholzj** [comment]
That sounds reasonable to me.

BTW: I think this is the long-term replacement for Grafana: https://github.com/perses/perses => but it is not yet ready for primetime.

**Comment by katheris** [comment]
@ppatierno are you happy with my suggestion of moving to the last Apache licensed version of Grafana and updating our `graph` visualisations to `time-series`?

**Comment by ppatierno** [comment]
> @ppatierno are you happy with my suggestion of moving to the last Apache licensed version of Grafana and updating our graph visualisations to time-series?

@katheris yes, it sounds good to me.

**Comment by katheris** [comment]
I've updated the issue description

**Comment by katheris** [comment]
I have found a problem with moving to the time-series included in version 7.5.17, the support for stacking was only added in version 8. So if we do this change we can't have any of the graphs be stacked. I think we need to revisit whether we want this change or not.

**Comment by scholzj** [comment]
Discussed on the community call on 30.11.2023: We should try to wait for the next call where @katheris might be able to join to better understand the issue.

**Comment by scholzj** [comment]
Discussed in the community call on 14.12.: The missing support for stacked charts seems significant limitation and given the current charts still seem to work, we should close it.
