### ISSUE TITLE
Ability to mount secrets into Kafka Connect

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#933]
Kafka Connect needs the ability to mount secrets ( containing the proper certificates) in order to communicate with encrypted services.

**Comment by Tombar** [comment]
Hello, if the strimzi kafka connect cluster can support this https://docs.confluent.io/current/connect/security.html#externalizing-secrets 

what would be needed is to only support mounting config map as secrets into the created clusters
