### ISSUE TITLE
Strimzi release yaml file

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#935]
It would be handy if the `strimzi-x.y.z.tar.gz` file would contain a release yaml file. and also that we have a hosted version online.

Currently the cluster-operator, for instance, is installed by applying a bunch (17?) of yaml files:
https://github.com/strimzi/strimzi-kafka-operator/tree/master/examples/install/cluster-operator

While this is handy for development, keeping them separate, it might be handy to have a release yaml file, combining those?

The Knative project does that too. They have a number of yaml files in the SRC repo, for instance the `eventing` component:  https://github.com/knative/eventing/tree/master/config 

but also offer a _larger_ release file, instead of several smaller files. E.g. like here:
* https://storage.googleapis.com/knative-releases/eventing/latest/release.yaml

**Comment by scholzj** [comment]
I think having multiple files is handy also for most installations. It makes is much more transparent what do you actually install. And it also makes it easy to install only some part of it for example for watching multiple namespaces.

But there is probably nothing what would prevent us from offering both.

**Comment by scholzj** [comment]
@matzew I opened a PR for this. I do not think we need to add it to the release archive. But we should upload the files to the GitHub releases so that you can download them and link to them if needed. Feel free to review if you want.

**Comment by matzew** [comment]
Thanks! I will give it a look
