### ISSUE TITLE
[Bug]: KafkaRoller handles error from describeQuorum gracefully during migration

### ISSUE THREAD

**Issue by katheris** [strimzi/strimzi-kafka-operator#9391]
### Bug Description

Once PR #9146 is merged, in KRaft mode the KafkaRoller will use describeQuorum to look up the quorum leader and see the state of the voters. It will use this information to determine the order to roll the controllers and whether it is safe to do so.

During migration from ZooKeeper to KRaft mode the describeQuorum call is not going to work. We need to either:
 - update the KafkaRoller to be aware of the fact a migration is happening and provide a fallback mechanism
 - provide some other mechanism to roll the controllers during a migration

More details of this error are in the comments on the KRaft migration work, in this [review](https://github.com/strimzi/strimzi-kafka-operator/pull/9324#pullrequestreview-1746737595) and [response](https://github.com/strimzi/strimzi-kafka-operator/pull/9324#issuecomment-1825320023).

One option is to use metrics, for example LastAppliedRecordLagMs metric to check the quorum health (leader it is always zero), and ActiveControllerCount to determine who is the leader.

### Strimzi version

main

### Kubernetes version

N/A

**Comment by scholzj** [comment]
Discussed on the community call on 30.11.2023: @ppatierno will check with @katheris to see if this is really needed.
