### ISSUE TITLE
Add documentation for resources short names

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#940]
There are short names defined for resources (i.e. `k` for `Kafka`, `kc` for `KafkaConnect`, `kt` for `KafkaTopic` and so on).
We should add documentation for that, maybe as an appendix.

**Comment by laidan6000** [comment]
This issue was resolved by @PaulRMellor. The Using Strimzi guide now has a table showing the long and short names of custom resources:

https://strimzi.io/docs/operators/master/using.html#con-custom-resources-info-str

**Comment by laidan6000** [comment]
This issue was addressed in PR #3463
