### ISSUE TITLE
Decide how to deal with the old methods in the `api` module `*Resources` classes

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9406]
In the `api` module, we have various `*Resources` classes (e.g. `KafkaResources`). These contain the definitions of the names used by various Strimzi Kubernetes resources. But over the time, some of them have diverged from how the re named and what they are used for.

For example, `KafkaResources.kafkaStatefulSetName(...)` ...
* It was originally used for the StatefulSet with the Kafka brokers
* It is still used in its original context when upgrading from old Strimzi versions stil using StatefulSets
* In some configurations not using node pools, it might be the name of the StrimziPodSet with Kafka brokers
* In configurations using KafkaNodePool resources it will be the `strimzi.io/name` label set on all Kafka pods.

We should think about what to do with the methods like this.

**Comment by Anefu** [comment]
Hey @scholzj I'm happy to work on this. Could you provide some more guidance (this is my first time contributing to Strimzi)?

**Comment by scholzj** [comment]
I guess you can rename the `*statefulSetName` methods to a better name. But I guess we would need to think about what the _better name_ would be :-/.

**Comment by Anefu** [comment]
Is this something that's currently being discussed?

**Comment by scholzj** [comment]
I guess you could call it `*ComponentName`. E.g. `KafkaResources.kafkaStatefulSetName(...)` would be `KafkaResources.kafkaComponentName(...)` etc. There is one more methods following this pattern for ZooKeeper and so on. And you can also do the same for the `deploymentName(...)` methods in the other `*Resource` classes (e.g. `KafkaCOnnectResources.deploymentName(...)` and `KafkaMirrorMaker2Resources.deploymentName(...)`).

WDYT @ppatierno?

**Comment by Anefu** [comment]
Should the `deploymentName` methods also be changed to `componentName`?

**Comment by scholzj** [comment]
Yeah, it should be the same I think.

**Comment by ppatierno** [comment]
+1 I am fine with the Jakub's suggestion.
