### ISSUE TITLE
[Bug]: Operator fails to start after Helm upgrade from 0.38.0 to 0.39.0

### ISSUE THREAD

**Issue by eric-dynamicops** [strimzi/strimzi-kafka-operator#9498]
### Bug Description

As per our normal procedure we use helm to upgrade the Strimzi Operator. 
When upgrading from 0.38.0 to 0.39.0 the Operator crashes with the below error in the logs:
`2024-01-03 02:23:50 ERROR Main:104 - Unable to start operator for 1 or more namespace
io.fabric8.kubernetes.client.KubernetesClientException: Received 404 on websocket. Failure executing: GET at: https://10.213.96.1:443/apis/kafka.strimzi.io/v1beta2/kafkanodepools?allowWatchBookmarks=true&watch=true. Message: Not Found.
`

### Steps to reproduce

Have a working installation of Strimzi Kafka Operator version 0.39.0.
Upgrade to 0.39.0 using Helm

### Expected behavior

Strimzi Operator to be functioning after this minor version upgrade

### Strimzi version

0.39.0

### Kubernetes version

v1.27.5-gke.200

### Installation method

Helm

### Infrastructure

GKE on GCP

### Configuration files and logs

Default Strimzi Operator configuration

**Comment by eric-dynamicops** [comment]
Found the issue, I was missing one CRD.

**Comment by nammehra** [comment]
@eric-dynamicops , how did you add the missing CRD?
