### ISSUE TITLE
Link to example Grafana dashboard is broken

### ISSUE THREAD

**Issue by gunnarmorling** [strimzi/strimzi-kafka-operator#951]
In http://strimzi.io/docs/0.7.0/#grafana_dashboard, there's a link to https://github.com/strimzi/strimzi-kafka-operator/blob/master/metrics/examples/grafana/kafka-dashboard.json. But this file doesn't exist. Which one should it be instead?

I tried https://github.com/strimzi/strimzi-kafka-operator/blob/master/metrics/examples/grafana/strimzi-kafka.json, but this gives me an empty dashboard (OpenShift 3.9.0).

**Comment by scholzj** [comment]
Unfortunately it seems that the dashboard links are currently not versioned. You can find the old dashboard here: [https://github.com/strimzi/strimzi-kafka-operator/blob/0.7.0/metrics/examples/grafana/kafka-dashboard.json](https://github.com/strimzi/strimzi-kafka-operator/blob/0.7.0/metrics/examples/grafana/kafka-dashboard.json).

The new dashboard is IMHO much nicer - it should be paired with the metrics configuration from the example resources here: [https://github.com/strimzi/strimzi-kafka-operator/tree/master/metrics/examples/kafka](https://github.com/strimzi/strimzi-kafka-operator/tree/master/metrics/examples/kafka) (You can just copy the metrics field and its content and use it with 0.7.0 without any problems).

I think the new dashboard requires Grafana 5.0 or higher (did I got that right @seglo?).

**Comment by seglo** [comment]
@scholzj Correct!

**Comment by gunnarmorling** [comment]
> (You can just copy the metrics field and its content and use it with 0.7.0 without any problems).

Copy where exactly? Is this to say that the instructions from master (http://strimzi.io/docs/master/#grafana_dashboard) work with 0.7.0, too? And yes, the new dashboard looks very nice indeed!

**Comment by gunnarmorling** [comment]
Btw. in http://strimzi.io/docs/master/#grafana_dashboard (i.e. master) there's also a broken link to https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/latest/metrics/examples/kafka/kafka-metrics.yaml (section D1).

**Comment by gunnarmorling** [comment]
Hum hum, so I've imported the 0.7.0 dashboard into Grafana, but all I'm getting is "No data points" for all the metrics. Any idea what could be going on? That said, I'd love to try out the new dashboard, so if you have instructions handy for explaining how this can be used with 0.7.0, that'd be great. Thanks for all your help!

**Comment by seglo** [comment]
@gunnarmorling Have you set the variables at the top?  You need to define at least a namespace and strimzi cluster name.

**Comment by gunnarmorling** [comment]
Hey, sorry, I'm lacking some context here :( "At the top" where? Within Grafana? I've been following the steps from the 0.7.0 docs.

> You need to define at least a namespace and strimzi cluster name.

Sounds reasonable; where do I need to do this, though?

**Comment by seglo** [comment]
Once you load the dashboard in Grafana you'll see 5 dropdowns at the top.  The first two are for Namespace and Cluster Name respectively.

http://strimzi.io/docs/master/#kafka_dashboard

**Comment by gunnarmorling** [comment]
Is this with the new dashboard by any chance? Note I'm trying to import the existing one from 0.7.0. Here's what I'm seeing, no dropdowns there:

<img width="1375" alt="screen shot 2018-10-09 at 16 58 29" src="https://user-images.githubusercontent.com/28612/46678308-a79f0a00-cbe4-11e8-8d47-526af0115486.png">

**Comment by seglo** [comment]
No, those are the old dashboards.  The new dashboards have not been released yet and are only available in master.  If you follow the instructions using the Strimzi master documentation then it _should_ work.

http://strimzi.io/docs/master/#metrics-str

**Comment by gunnarmorling** [comment]
Sorry, we might be cross-talking. For now I'd be fine using the old dashboard, so to not rely on unused features. Hence I'm following the instructions from http://strimzi.io/docs/0.7.0/#grafana_dashboard, but I don't see any data points in there. Looking at the master docs I see now that you're talking about the new dashboard. I _could_ try out that, too, but it's not clear to me whether/how that works with 0.7, hence I'd prefer to get the old dashboard going for now.

**Comment by seglo** [comment]
Ah I see.  The new dashboards will have no problem working with Strimzi 0.7.0.

But in any case, the usual reason for not seeing data points in Grafana is that the metrics aren't available to Prometheus, or your Grafana to Prometheus datasource isn't setup correctly.  Another issue could be that Prometheus JVM Exporter rules haven't been defined and metrics aren't being served to Grafana.  Can you confirm you've defined rules?  Can you share your `Kafka` resource config?

**Comment by gunnarmorling** [comment]
> Can you confirm you've defined rules?

Good question :) How would I do that? If it's not part of the description of http://strimzi.io/docs/0.7.0/#metrics-str, I likely haven't done it :)

> Can you share your Kafka resource config?

Sure:

```
oc describe kafka my-cluster
Name:         my-cluster
Namespace:    voxxed
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"kafka.strimzi.io/v1alpha1","kind":"Kafka","metadata":{"annotations":{},"name":"my-cluster","namespace":"voxxed"},"spec":{"entityOperator...
API Version:  kafka.strimzi.io/v1alpha1
Kind:         Kafka
Metadata:
  Cluster Name:
  Creation Timestamp:  2018-10-09T14:46:14Z
  Resource Version:    1574
  Self Link:           /apis/kafka.strimzi.io/v1alpha1/namespaces/voxxed/kafkas/my-cluster
  UID:                 12450129-cbd2-11e8-b135-96000011cbea
Spec:
  Entity Operator:
    Topic Operator:
    User Operator:
  Kafka:
    Config:
      Offsets . Topic . Replication . Factor:            3
      Transaction . State . Log . Min . Isr:             2
      Transaction . State . Log . Replication . Factor:  3
    Listeners:
      Plain:
      Tls:
    Liveness Probe:
      Initial Delay Seconds:  15
      Timeout Seconds:        5
    Metrics:
      Lowercase Output Name:  true
      Rules:
        Name:     kafka_server_$1_$2_total
        Pattern:  kafka.server<type=(.+), name=(.+)PerSec\w*><>Count
        Labels:
          Topic:  $3
        Name:     kafka_server_$1_$2_total
        Pattern:  kafka.server<type=(.+), name=(.+)PerSec\w*, topic=(.+)><>Count
    Readiness Probe:
      Initial Delay Seconds:  15
      Timeout Seconds:        5
    Replicas:                 3
    Storage:
      Type:  ephemeral
  Zookeeper:
    Liveness Probe:
      Initial Delay Seconds:  15
      Timeout Seconds:        5
    Metrics:
      Lowercase Output Name:  true
    Readiness Probe:
      Initial Delay Seconds:  15
      Timeout Seconds:        5
    Replicas:                 3
    Storage:
      Type:  ephemeral
Events:      <none>
```

It's the result of `oc apply -f examples/kafka/kafka-ephemeral.yaml`.

**Comment by seglo** [comment]
It looks like you have rules defined (`spec.metrics.rules`).  AFAIK those are compatible with the old Grafana dashboard.

As a next step I would confirm that prometheus is picking up Kafka metrics.  Create a `port-forward` to the Prometheus pod, goto the `/graph` endpoint.  If you start typing `kafka_server_` you should start seeing metrics in the drop down.  If you don't, then for some reason Prometheus can't scrape the metrics from Kafka pods.

**Comment by scholzj** [comment]
I think this can be closed due to the age. The documentation is not pointing to master branch anymore so at least that part should be solved as well.
