### ISSUE TITLE
[Bug]: With ArgoCD, created PVCs are reported as out of sync.

### ISSUE THREAD

**Issue by b-thiswatch** [strimzi/strimzi-kafka-operator#9554]
### Bug Description

We are using ArgoCD to provision our cluster. We have installed the Operator as a Helm chart and the kafka CRs as an Argo Application. When the cluster gets deployed by the operator the PVCs are considered as out of sync (Argo would remove them when using "purge")

### Steps to reproduce

1. Deploy Operator with ArgoCD
2. Deploy Kafka Example CR with ArgoCD

### Expected behavior

PVCs should not be out of sync as they aren't with other operators (Keycloak, CNPG, ..)

### Strimzi version

0.39

### Kubernetes version

1.29 RKE2

### Installation method

Helm Chart

### Infrastructure

Bare Metal, Ubuntu 22 LTS, RKE2

**Comment by scholzj** [comment]
There is not much Strimzi can do about how Argo behaves. Also, this has been discussed in the past. So please search the previous issues and discussions.

**Comment by scholzj** [comment]
I don't. But there are plenty of issues and discussions returned by search:
* https://github.com/orgs/strimzi/discussions?discussions_q=argo
* https://github.com/strimzi/strimzi-kafka-operator/issues?q=is%3Aissue+argo+is%3Aclosed
