### ISSUE TITLE
[Bug]: Foreground pod deletion prevents clean shutdowns on Cilium with enabled encryption

### ISSUE THREAD

**Issue by khartld** [strimzi/strimzi-kafka-operator#9592]
### Bug Description

The Strimzi operator mostly uses foreground cascading deletion to manage its kubernetes resources (in some cases orphaned, but never background). It always uses foreground deletion for managing its pods.
This leads to problems when running Strimzi in a cluster with Cilium and [enabled traffic encryption](https://docs.cilium.io/en/latest/security/network/encryption-wireguard/).

If a (Strimzi) pod is deleted with foreground deletion, the CiliumEndpoint owned by that pod is immediately garbage collected. Without the CiliumEndpoint which is required for traffic encryption, the pod is basically isolated from the network. This makes the broker unable to communicate with the other brokers/zookeeper/clients and inform them about the pending shutdown.

If pods would be deleted with background cascading deletion, their CiliumEndpoints are kept available until after they have finished terminating.

I'm honestly not really sure if this is rather a Cilium than Strimzi bug, but is there a specific reason Strimzi only uses foreground deletion?

### Steps to reproduce

1. Create some local k8s cluster
2. [Install Cilium](https://docs.cilium.io/en/stable/installation/kind/) with values `l7Proxy=false, encryption.enabled=true, encryption.type=wireguard`
3. Install Strimzi cluster with at least 2 brokers
4. Annotate current controller with `strimzi.io/manual-rolling-update=true`
5. Observe connection timeout exceptions occurring in the terminating broker
  - `WARN Client session timed out, have not heard from server in 12001ms for session id 0x2000012f3ba0000 (org.apache.zookeeper.ClientCnxn) [main-SendThread(my-cluster-zookeeper-client:2181)]`
  - `java.net.UnknownHostException: my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc: Name or service not known`
  - `WARN [KafkaServer id=1] Error during controlled shutdown, possibly because leader movement took longer than the configured controller.socket.timeout.ms and/or request.timeout.ms: Connection to my-cluster-kafka-1.my-cluster-kafka-brokers.kafka.svc:9091 (id: 1 rack: null) failed. (kafka.server.KafkaServer) [kafka-shutdown-hook]`

### Expected behavior

Pod restarts triggered by Strimzi should be clean by informing other brokers/zookeeper, even when using Cilium with encryption enabled

### Strimzi version

0.39.0

### Kubernetes version

Kubernetes v1.26.10 & v1.27.3

### Installation method

Helm chart

### Infrastructure

Kubernetes, Kind

### Configuration files and logs

[report-24-01-2024_18-26-49.zip](https://github.com/strimzi/strimzi-kafka-operator/files/14041716/report-24-01-2024_18-26-49.zip)

Kind config:
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true   # do not install kindnet
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker

```

Cilium Helm values
```
image:
  pullPolicy: IfNotPresent
ipam:
  mode: kubernetes

l7Proxy: false # does not cause problem, but is required for wireguard
encryption:
  enabled: true
  type: wireguard
```

**Comment by scholzj** [comment]
The main issue with problems like this is that we cannot go and change things just because of a single project in one configuration. That might break it for someone else who uses another project that needs the exact opposite. 

As a side note - the internal connections in the cluster are all encrypted by Strimzi. So you are probably doing double encryption. Not sure what your motivation is and maybe you want it because of other applications, but just wanted to mention it.

**Comment by khartld** [comment]
Yeah, we want to encrypt all traffic, because we don't have it for all applications individually yet.
I can understand the hesitation to change the behavior in Strimzi, we will then just use a patched operator until we can get rid of the Cilium encryption. Thanks!

**Comment by khartld** [comment]
eah, we want to encrypt all traffic, because we don't have it for all applications individually yet.
I can understand the hesitation to change the behavior in Strimzi, we will then just use a patched operator until we can get rid of the Cilium encryption. Thanks!
