### ISSUE TITLE
[Enhancement]: Add topicId to KafkaTopicStatus

### ISSUE THREAD

**Issue by MikeEdgar** [strimzi/strimzi-kafka-operator#9651]
### Related problem

I am working with a component that uses the Kafka `topicId` to identify a topic. Locating a `KafkaTopic` CR for a given `topicId` requires an additional describe operation to obtain the name to then find the CR.

### Suggested solution

Publish the `topicId` in the status section of the KafkaTopic custom resource.

### Additional context

Depending on the timeline for deprecating the bidirectional topic operator, this may be useful for both version of the TO.

**Comment by scholzj** [comment]
I don't think it would be a problem to have this. But when the Topic ID is published in the status, it would not make it easier to find it as you cannot easily query a topic by part of its status. You would need to get all KafkaTopic resources and basically go through them one by one to find the right resource (or to find out the resource does not exist).

**Comment by MikeEdgar** [comment]
Thanks. Given that `UnidirectionalTopicOperator` just became beta in 0.39, I'm guessing this would need to be implemented in both versions of the topic operator.

> You would need to get all KafkaTopic resources and basically go through them one by one to find the right resource (or to find out the resource does not exist).

Right, we have a cross-reference map updated by a watch/informer to keep things current.

**Comment by scholzj** [comment]
I guess @tombentley would know how hard would it be to add it to the Bidirectional Topic Operator - if it is simple I guess it can be added there as well. But at this point, I think adding it only to the Unidirectional Topic Operator would be preferred. (Keep in mind that Bidirection Topic Operator is scheduled for removal in Strimzi 0.41 -> so if we add it now, it will be just for one release).
