### ISSUE TITLE
Should manual rolling update failure fail the whole reconciliation?

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9654]
Currently, when a pod is annotated for manual rolling update and the manual rolling update fails (for example because topics or the other controllers are not in-sync), it also fails the whole reconciliation. But in some (rare) situations, this can cause issues. Imagine following scenario:

1) Due to a storage issues, one of the KRaft controller nodes is deleted including its PVC and PV
2) At the same time, another KRaft controller pod is annotated for manual rolling update (either by the user but possibly also by Drain Cleaner)
3) The StrimziPodSet controller will restart the failed pod, but without the PVC/PV, it will be in a Pending state
4) Next periodical reconciliation starts and tries to roll the annotated controller pod => this fails because with another controller in Pending state it would break quorum and as a result the whole reconciliation fails as well.
5) However, the PVC creation step is only after the manual rolling update. So the PVC is never recreated and the Pendign controller pod remains pending.
6) When the next reconciliation happens ... the same repeats again because these two events block each other.

We should try to avoid this and when the manual rolling update fails, we should try to suppress the error - just log a warning but proceed with the reconciliation. That should give the operator the chance to fix issues (e.g. recreate PVCs). I do not think this should cause any problems. The manual rolling update annotation should either survive till the next reconciliation or the pod will be rolled in regular rolling update -> I do not have any scenario where this would be an issue. But this should be triaged so that we can see if anyone sees any problems.

**Comment by scholzj** [comment]
Triaged on community call 8.2.2024: @tombentley asked for more time to think through this. Should be revisited next time.

**Comment by tombentley** [comment]
Why do we think it's correct that the order in `KafkaReconciler` is:

```java
                .compose(i -> manualRollingUpdate())
                .compose(i -> pvcs(kafkaStatus))
```

? I.e. what's the use case for needing to restart pods in a circumstance where the PVC might not exist (and so the pod can't possibly leave `Pending`)?

**Comment by scholzj** [comment]
The intention is to restart the old pod as it existed. If you move it later, you might not be able to roll it safely because of inconsistent state - e.g. different PVC from the desired configuration while rolling the old pod that is based on the current state.

**Comment by scholzj** [comment]
I do not think there is any contract we break. The only thing we promise in the docs is that it maintains the availability. That does not change with the suggestion from this issue.

A separate question is if we break some usecases. But I guess it would be good to have at least an example of what kind of workflow this would break. I do not have any.

The issue I described cannot be fixed in the roller - if you have a broker with missing PVCs as a scenario we have seen, it will not help to restart it as it doesn't run in the first place. The only other options are:
* To leave it to the users and their manual handling (this is the current state: i.e. detect the issue, recognize it for what it actually is which is non-trivial, remove the manual rolling update annotation, let the operator recreate the missing resources and finally add back the manual RU annotation).
* Give up on doing the manual rolling update with old pods and move it for example to the regular rolling updates as part of its checks. While I remember that we wanted to have the manual rolling update done as soon as possible and without any inconsistencies, I'm not sure anymore what the actual motivation for that was and why it wasn't built into the regular rolling update. I assume it might be because there is a higher risk it will not get there when something is wrong? (e.g. load balancer not provisioned etc.) Or was there any particular concern we saw?

**Comment by scholzj** [comment]
> To leave it to the users and their manual handling (this is the current state: i.e. detect the issue, recognize it for what it actually is which is non-trivial, remove the manual rolling update annotation, let the operator recreate the missing resources and finally add back the manual RU annotation).

After a follow-up discussion -> the manual handling described here might also include stopping a cluster upgrade or node draining or scaling down Drain Cleaner because otherwise the annotation is added by Drain Cleaner again and again when evictions are in progress.

**Comment by Frawless** [comment]
> After a follow-up discussion -> the manual handling described here might also include stopping a cluster upgrade or node draining or scaling down Drain Cleaner because otherwise the annotation is added by Drain Cleaner again and again when evictions are in progress.

That's exactly what we were hitting and the situation was quite user unfriendly. Eviction request is send every 5s with DC 1.0, every 10s with DC with https://github.com/strimzi/drain-cleaner/pull/113 (according the logs) so the user has to have a lucky hand to remove the annotation at exact time that will allow CO to start the reconciliation that will recover the pod.

Possible workaround is scaling down the DC for a while, but it adds another unwanted step that could be a little bit complicated in some cases like managing DC via ArgoCD ApplicationSets.

Our situation is a corner case I would say, but the solution proposed by @scholzj would make the whole UX from stuff like that much better. So +1 from me.

**Comment by scholzj** [comment]
@tombentley Any more thoughts on this?

**Comment by tombentley** [comment]
@scholzj: OK, OK, you've convinced me we should do this! WDYT about this bit though:

> But I wonder if we should have some config parameter to restore the old behaviour, just in case it breaks someone's workflow. If no one complains we could eventually remove it.

It would be a _bit_ more work (mostly in having tests for it), but at least it would allow people who experienced unforeseen problems with it to get the old behaviour.

**Comment by scholzj** [comment]
> > But I wonder if we should have some config parameter to restore the old behaviour, just in case it breaks someone's workflow. If no one complains we could eventually remove it.
> 
> It would be a _bit_ more work (mostly in having tests for it), but at least it would allow people who experienced unforeseen problems with it to get the old behaviour.

What kind of parameter would you expect? A feature gate?

**Comment by tombentley** [comment]
Yeah, that would allow us to get rid of it relatively quickly.

**Comment by scholzj** [comment]
Ok, a proposal is needed i that case. Thanks.

**Comment by scholzj** [comment]
Proposal opened in https://github.com/strimzi/proposals/pull/114

**Comment by scholzj** [comment]
Proposal approved. @Staniel will work on the implementation.

**Comment by scholzj** [comment]
Done in #10005
