### ISSUE TITLE
[Bug]: numbering inconsistent when deploying kraft KafkaNodePools

### ISSUE THREAD

**Issue by msillence** [strimzi/strimzi-kafka-operator#9705]
### Bug Description

When I deploy node pools sometimes the brokers start at 0 and then the controllers continue from the number of brokers and sometimes it happens the other way round

one deployment:

poa-broker-0                                2/2     Running   0          23d
poa-broker-1                                2/2     Running   0          15d
poa-broker-2                                2/2     Running   0          23d
poa-broker-3                                2/2     Running   0          16d
poa-controller-4                            2/2     Running   0          23d
poa-controller-5                            2/2     Running   0          23d
poa-controller-6                            2/2     Running   0          23d

second deployment

poa-broker-5                                2/2     Running   0                 2d17h
poa-broker-6                                2/2     Running   0                 2d17h
poa-broker-7                                2/2     Running   0                 2d17h
poa-broker-8                                2/2     Running   0                 2d4h
poa-controller-0                            2/2     Running   0                 2d17h
poa-controller-1                            2/2     Running   0                 2d17h
poa-controller-2                            2/2     Running   0                 2d17h
poa-controller-3                            2/2     Running   0                 2d17h
poa-controller-4                            2/2     Running   0                 2d17h

### Steps to reproduce

Difficult to reproduce it's tends to do one or the other and occassionally switches if I delete both the cluster (Kafkas) and the strimzipodset and redeploy

If this happens new storage is created and the new brokers no longer have any data

Possibly dependent on the order the KafkaNodePool are created?

### Expected behavior

The documentation says that the nodes will start with the number 0

I guess there is the option to deploy a single pool and have nodes performing both actions but it would be great if the numbering system could be consistent

### Strimzi version

0.39

### Kubernetes version

1.26.10-gke.1101000

### Installation method

terraform crd manifest using kubectl

### Infrastructure

google cloud platform

### Configuration files and logs

resource "kubernetes_manifest" "kafka_zookeeper_pool" {
  manifest = {
    "apiVersion" = "kafka.strimzi.io/v1beta2"
    "kind"       = "KafkaNodePool"
    "metadata" = {
      "labels" = {
        "strimzi.io/cluster" = var.strimzi_cluster_name
      }
      "name"      = "controller"
      "namespace" = var.namespace
    }
    "spec" = {
      "replicas" = var.zookeeper_replicas
      "roles" = [
        "controller",
      ]
      "storage" = {
        "type" = "jbod"
        "volumes" = [
          {
            "deleteClaim" = false
            "id"          = 0
            "size"        = var.zookeeper_disk_size
            "type"        = "persistent-claim"
            "class"       = "kafka-storage"
          },
        ]
      }

      template = {
        pod = {
          priorityClassName = var.high_priority_class
          affinity = {
            nodeAffinity = {
              requiredDuringSchedulingIgnoredDuringExecution = {
                nodeSelectorTerms = [
                  {
                    matchExpressions = [
                      {
                        key      = "topology.kubernetes.io/zone"
                        operator = "In"
                        values   = ["europe-west2-a", "europe-west2-b", "europe-west2-c"]
                      }
                    ]
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}
resource "kubernetes_manifest" "kafka_broker_pool" {
  manifest = {
    "apiVersion" = "kafka.strimzi.io/v1beta2"
    "kind"       = "KafkaNodePool"
    "metadata" = {
      "labels" = {
        "strimzi.io/cluster" = var.strimzi_cluster_name
      }
      "name"      = "broker"
      "namespace" = var.namespace
    }
    "spec" = {
      "replicas" = var.broker_replicas
      "roles" = [
        "broker",
      ]
      "storage" = {
        "type" = "jbod"
        "volumes" = [
          {
            "deleteClaim" = false
            "id"          = 0
            "size"        = var.kafka_disk_size
            "type"        = "persistent-claim"
            "class"       = "kafka-storage"
          },
        ]
      }
      template = {
        pod = {
          affinity = {
            nodeAffinity = {
              requiredDuringSchedulingIgnoredDuringExecution = {
                nodeSelectorTerms = [
                  {
                    matchExpressions = [
                      {
                        key      = "topology.kubernetes.io/zone"
                        operator = "In"
                        values   = ["europe-west2-a", "europe-west2-b", "europe-west2-c"]
                      }
                    ]
                  }
                ]
              }
            }
          }
        }
      }
    }
  }
}

**Comment by scholzj** [comment]
This is not a bug. There is no promise that the free ID assignment will always happen in the same way. It will depend on many factors including the order in which the things are created etc. Also, in both situations you shared it maintains the promise from the documentation that the node IDs start from 0. If you want the IDs to be more stable, you can assign different node ID ranges to different node pools: https://strimzi.io/docs/operators/latest/full/deploying.html#proc-managing-node-pools-ids-str

**Comment by msillence** [comment]
OK thanks for the quick reply, I was expecting it to behave more like when configured with zookeeper where both start at zero:

poa-kafka-0                                 2/2     Running   0             26d
poa-kafka-1                                 2/2     Running   0             26d
poa-kafka-2                                 2/2     Running   0             26d
poa-kafka-3                                 2/2     Running   0             26d

poa-zookeeper-0                             2/2     Running   0             26d
poa-zookeeper-1                             2/2     Running   0             26d
poa-zookeeper-2                             2/2     Running   0             26d
poa-zookeeper-3                             2/2     Running   0             26d
poa-zookeeper-4                             2/2     Running   0             26d

I guess setting the range would solve my issue, I don't like unpredictable results but having to do it this way could catch others out.

I'm happy to close it if you don't think this is an issue.

**Comment by scholzj** [comment]
> OK thanks for the quick reply, I was expecting it to behave more like when configured with zookeeper where both start at zero:

Oh no, that is not possible. The node pools are part of the same Kafka cluster so they share the same range of IDs and the ID has to be unique. So you cannot have node ID 0 in multiple node pools.

If you think there is some part of the documentation that confused you (or where we should perhaps add an explanation for this), we can definitely try to look into it and make it more clear. But I don't think there is much more we can do.

**Comment by scholzj** [comment]
Triaged on the community call on 22.2.2024: Seems to be clarified and can be closed.
