### ISSUE TITLE
[Docs]: Explain how to set ssl settings for KafkaConnect

### ISSUE THREAD

**Issue by GitarPlayer** [strimzi/strimzi-kafka-operator#9730]
### Suggestion / Problem

I need to configure the ssl directive to change the truststore that KafkaConnect uses and the password associated with it. From the doc I can only see this: 

> You can specify and configure the options listed in the [Apache Kafka documentation](https://kafka.apache.org/documentation/#connectconfigs) with the exception of those options that are managed directly by Strimzi. Specifically, configuration options with keys equal to or starting with one of the following strings are forbidden:

> ssl.

> sasl.

> security.

> listeners

> plugin.path

> rest.

> bootstrap.servers

> When a forbidden option is present in the config property, it is ignored and a warning message is printed to the Cluster Operator log file. All other options are passed to Kafka Connect.

But it is not explained at all where the settings then can be changed. I read across the entire KafkaConnect CRD section but there is no clue. Do I have to use externalConfiguration? But how?

### Documentation Link

https://strimzi.io/docs/operators/0.30.0/full/configuring#property-kafka-connect-config-reference

**Comment by scholzj** [comment]
This is covered in the documentation. For example https://strimzi.io/docs/operators/latest/full/deploying.html#con-kafka-connect-config-str, or in the reference. There are also examples on GitHub in the examples folder. So please check them out and if you have some more questions, you can start a discussion.
