### ISSUE TITLE
Use proper `toString()` implementation in the API classes

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9734]
The classes in our API module currently seem to mix several ways how to handle the `toString` methods:
* Some use Jackson libraries to render a YAML string
* Some do not do anything
* Some use the Lombok `@ToString` annotation to generate the `toString()` method

We should pick one way (Lombok annotation?) and use it properly in all resources and their subclasses. This would help when debugging issues, with log readability etc.

**Comment by scholzj** [comment]
Triaged on the community call on 7.3.2024: We should use the `@ToString` annotation on all the API classes.

**Comment by kockas** [comment]
I'd  do it. I see quite a lot of inconsistencies also in `@EqualsAndHashCode` when `callSuper = true`  is not used consistently. I would align it, and use `@ToString` inline with `@EqualsAndHashCode`, so both annotation use same `callSuper = true` (or false).
Is that approach ok for you?

**Comment by scholzj** [comment]
I think that makes sense, yes.
