### ISSUE TITLE
[Enhancement]: Use Util.decodeFromBase64 from operator-common module

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#9745]
### Suggested solution

In #9483 the method `decodeFromBase64` was introduced in `operator-common/src/main/java/io/strimzi/operator/common/Util.java`. The same logic is used in multiple places and across different modules. It would be good to use the new method instead, similar to what we have for the companion method `encodeToBase64`.

**Comment by ppatierno** [comment]
Triaged on 21.3.2024: it makes sent to implement it.

**Comment by steffen-karlsson** [comment]
If you like @fvaleri, I can work on this 😄

**Comment by fvaleri** [comment]
Sure, go for it. Thanks.

**Comment by scholzj** [comment]
@steffen-karlsson I think someone just opened a PR for this in #9906.
