### ISSUE TITLE
[Enhancement]: Switch to UTF-8 encoding

### ISSUE THREAD

**Issue by fvaleri** [strimzi/strimzi-kafka-operator#9746]
### Suggested solution

We use the `US_ASCII` encoding almost everywhere in Strimzi. For example in `operator-common/src/main/java/io/strimzi/operator/common/Util.java`. Unless it is required by some API/specification, we should switch to `UTF-8`, which is the platform/OS default these days.

**Comment by scholzj** [comment]
Triaged on the community call on 7.3.2024: It does not seem like we have clarity about the possible consequences and know for sure we can switch to UTF-8 everywhere. At the same time, we do not have any actuall issues where something doesn't work with ASCII as it is today. So we should close this.
