### ISSUE TITLE
[Bug]: strimzi kafka custom resource reverting to defaults

### ISSUE THREAD

**Issue by mrocheleau** [strimzi/strimzi-kafka-operator#9832]
### Bug Description

We are running `3.4.0` in EKS 1.28 and are finding edits to the `kafka` custom resource are reverting to defaults some hours or days after making changes.  No actions are taken otherwise by us, no code deploys or change are occurring and there are no automated processes we manage that might redeploy or otherwise interact with the kafka resource or it's pods, or the kafka/strimzi operator.

We made two changes to the `kafka` custom resource:
1) Upping the jbod persistent storage size from 100Gi to 125Gi, this upgraded the pvc's and the pods restarted, all was well
2) Adding `log.retention.hours: "96"' to reduce the retention from the 168 hours default, this restarted the kafka pods and triggered pruning of older log files correctly.

Some hours or days later, I check the `kafka` custom resource and see that it's reverted to 100Gi and the log retention config is missing. One of the pods restarted this morning for whatever reason and now the kafka resource shows an warning about the storage configuration for kafka being invalid and any further changes will be ignored.  The error is referencing the now lower 100Gi size which cannot be accomodated as K8s cannot scale down disks from the actual 125Gi size.  Changing that again and saving it removes the warning.  Re-adding the log retention config rolls the pods correctly.

This has happened twice that we're aware of, no one has touched it, 100% sure.  The operator pod has not restarted or been recreated since prior to the original change.  The only pod logs I see are kafka startup logs which show the default settings, not the custom ones we entered.  The operator shows some interesting logs though:

Around the time of the single kafka pod restart the operator shows:
```
2024-03-13 09:53:20 ERROR AbstractOperator:439 - Reconciliation #1234(timer) Kafka(monitoring/jaeger-streaming): Reconciliation completion handler failed
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Kafka]  with name: [jaeger-streaming]  in namespace: [monitoring]  failed.
...
Caused by: java.io.IOException: /172.25.1.202:36404: GOAWAY received
... (lots of reconciliation logs that don't see like errors just "checking this and that" repeatedly)
...
2024-03-13 10:03:19 WARN  AbstractModel:368 - Reconciliation #1239(timer) Kafka(monitoring/jaeger-streaming): Only the following changes to Kafka storage are allowed: changing the deleteClaim flag, adding volumes to Jbod storage or removing volumes from Jbod storage, changing overrides to nodes which do not exist yet and increasing size of persistent claim volumes (depending on the volume type and used storage class).
2024-03-13 10:03:19 WARN  AbstractModel:373 - Reconciliation #1239(timer) Kafka(monitoring/jaeger-streaming): The desired Kafka storage configuration in the custom resource monitoring/jaeger-streaming contains changes which are not allowed. As a result, all storage changes will be ignored. Use DEBUG level logging for more information about the detected changes.
2024-03-13 10:04:18 INFO  AbstractOperator:380 - Reconciliation #1239(timer) Kafka(monitoring/jaeger-streaming): Reconciliation is in progress
```

So somewhere in the middle of the night for the cluster, something reverted the kafka resource to a defaults and now it's failing to reconcile after that until I fix it manually.  Which it'll probably revert again.

### Steps to reproduce

1.  Modify the kafka resource to change disk size and add log.retention.hours: "96" to the kafka config
2. Wait some hours or days after all changes were set correctly in the kafka pods
3. Operator will show failures to reconcile after it reverts the kafka custom resource

### Expected behavior

Changes made to the kafka resource should stick and not be reverted to defaults. 

### Strimzi version

3.4.0

### Kubernetes version

Kubernetes 1.28

### Installation method

YAML manifests

### Infrastructure

EKS

### Configuration files and logs

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  creationTimestamp: "2023-04-21T01:11:57Z"
  generation: 12
  labels:
    app: jaeger
    app.kubernetes.io/component: kafka
    app.kubernetes.io/instance: jaeger-streaming
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-streaming
    app.kubernetes.io/part-of: jaeger
  name: jaeger-streaming
  namespace: monitoring
  ownerReferences:
  - apiVersion: jaegertracing.io/v1
    controller: true
    kind: Jaeger
    name: jaeger-streaming
    uid: 3915a3a6-1bbf-49d1-9bd2-f9789d72f375
  resourceVersion: "220846468"
  uid: 7926c70b-cbaa-4cb3-a5bd-492f7aa4cdd6
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: "2.3"
      log.retention.hours: "96"
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    replicas: 3
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 125Gi
        type: persistent-claim
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
```

### Additional context

Original discussion thread: https://github.com/orgs/strimzi/discussions/9812

**Comment by scholzj** [comment]
Strimzi never updates the Kafka custom resource metadata or specification. Only the `status` subresource. So if the changes are reverted, you have to look at your infrastructure and tooling to find out what is causing the issue. Maybe the resource is managed through some GitOps tooling or something and you have to apply the change there at the source? I think this should be closed and we should continue with the discussion you already started.

**Comment by mrocheleau** [comment]
It's not managed by anything, no.  It is a directly applied manifest which is not tied to our deploy system at all, nor have we done any deploys or even commits to the repository where the manifests live.  There's nothing that touches this outside of human fingers, we have two people that have access including myself and neither touched it.

The reconciliation steps that the strimzi operator is mentioning are certainly interacting with the kafka custom resource.

Is there any way in the operator or kafka custom resource that we can update the defaults to reflect our changes?  The 100Gb disk size for instance, that must be set somewhere, I presume it to be the default.  

Namespace events would be the only potential tracking of this that I'm aware of and unless I happen to catch it those rotate out after an hour.

**Comment by scholzj** [comment]
There is no place in the code that updates the Kafka resource spec or metadata. Feel free to look for it in the source code if you want. I do not know what your environment looks like, what tools you use or don't use, or who has access to it. But it is not Strimzi reverting your changes. The steps you describe are not reproducible in other environments.

**Comment by mrocheleau** [comment]
Can you tell me how the operator knows what defaults to use when creating the kafka custom resource in the first place?  Where does it get this from, for disk size on the `jdb` type and for what custom configs exist in `.spec.kafka.config`?

It'd be a bandage for us but if we couple update the source of this to have our own custom defaults then this would at least cause these instances to work correctly while we try to figure out what is changing things.

Again last night, when nothing was running, zero deployments, zero commits at all, zero manipulative services within K8s or outside of it, the kafka resource is now one generation higher at `13` and we've again lost our custom log retention setting from the kafka boxes.

**Comment by scholzj** [comment]
There is no default storage size. There is no default value for `.spec.kafka.config`. The storage size is mandatory. The config is optional and if you don't specify it, you don't specify it. Once again, Strimzi does not overwrite your resource with any defaults.

**Comment by mrocheleau** [comment]
So in a new setup, if I apply the operator and do whatever needs to be done, I would have to specify a disk size when it creates the initial kafka custom resource?  The Strimzi operator I assume does that initial creation, no?  

Or is it just a yaml manifest that is applied by the creating user and strimzi is only aware of it by the `strimzi.io/cluster` label?

**Comment by scholzj** [comment]
Yes. You have to specify the disk size in the Kafka CR. Strimzi will use that to create the PVCs, so you do not need to create those. But the size will be the one you specified in the Kafka CR.

**Comment by mrocheleau** [comment]
Ok, that original manifest is nowhere to be found so mystery remains.  I'll close this off then and keep investigating.
