### ISSUE TITLE
[Enhancement]: Replace x-kubernetes-preserve-unknown-fields in CRD for Kubernetes Resources object.

### ISSUE THREAD

**Issue by alexandrst88** [strimzi/strimzi-kafka-operator#9851]
### Related problem

There is still an issue when provision "Kafka" resource with Terraform Kubernetes Provider.  There is not possible change resources without re-creation of the resource which leads Operator to delete and create cluster. Could you please to add it, or point me the desired design for CRD generator code and i will implement it by myself.

### Suggested solution

https://github.com/strimzi/strimzi-kafka-operator/pull/9508 but for kubernetes resources as well in 0.40.0, it was partially implemented in https://github.com/strimzi/strimzi-kafka-operator/pull/9292 but it was closed.

**Comment by scholzj** [comment]
I think you have to be more specific about what is missing. As far as I know, we did all we could, and even that caused a lot of users some problems. So not sure what more are you asking for.

> Could you please to add it, or point me the desired design for CRD generator code and i will implement it by myself.

The source codes are in this repository. Unsurprisingly, the CRD generator is in the `crd-generator` directory.

**Comment by msillence** [comment]
I've not tested the new CRDs with terraform yet but we are using the kubectl provider https://github.com/gavinbunney/terraform-provider-kubectl with `resource kubectl_manifest` in our terraform to avoid this problem.
Of note the CRDs aren't upgraded by helm when you upgrade the operator you need to do that by hand. Thought I'd mention it in case you still had the old CRDs.

**Comment by alexandrst88** [comment]
Should be fixed in https://github.com/strimzi/strimzi-kafka-operator/pull/9857

**Comment by alexandrst88** [comment]
> I've not tested the new CRDs with terraform yet but we are using the kubectl provider https://github.com/gavinbunney/terraform-provider-kubectl with `resource kubectl_manifest` in our terraform to avoid this problem. You also need to include the provider in the module folder if you are using modules. Of note the CRDs aren't upgraded by helm when you upgrade the operator you need to do that by hand. Thought I'd mention it in case you still had the old CRDs.

I'm using official terraform kubernetes provider - https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest. I checked CRD's from 0.40.0 and their still have `x-kubernetes-preserve-unknown-field` for resourcers fields.

**Comment by scholzj** [comment]
I think doing it for the quantities is fine. But it is important to keep in mind that `x-kubernetes-preserve-unknown-field` is valid and does not require any deletion of a custom resource. So ultimately, this is a Terraform issue and one day you might not be able to work your way around it.

**Comment by alexandrst88** [comment]
> I think doing it for the quantities is fine. But it is important to keep in mind that `x-kubernetes-preserve-unknown-field` is valid and does not require any deletion of a custom resource. So ultimately, this is a Terraform issue and one day you might not be able to work your way around it.

Yes, but resources and limits are changing very often, https://github.com/strimzi/strimzi-kafka-operator/pull/9857 also adding validation for values. The fabric8 lib that is using is in this project for crds, reflects correct type of the resources, but crd-generator make it as `x-kubernetes-preserve-unknown-field`.  From my experience this field should defined type. like here https://github.com/fabric8io/kubernetes-client/blob/464e32eb7c8c05acd3ecd2fa90c0a295d6e80a59/java-generator/core/src/test/resources/spark-crd.yml#L901.

**Comment by scholzj** [comment]
Yeah, as I said, I think this change is fine.

**Comment by ppatierno** [comment]
Going to remove the "needs-triage" label because of the agreement and the PR already under review.

**Comment by scholzj** [comment]
@ppatierno Maybe you should review the PR instead and maybe we can close this :-)

**Comment by ppatierno** [comment]
@scholzj I haven't closed the issue. Of course it will be closed when PR is merged. I just removed the needs-triage label because I don't think it needs triage anymore taking into account there is a PR for it and we were in agreement here that it would have been good to have.
