### ISSUE TITLE
[Enhancement] Integrate the Quotas 0.3.0 plugin into the Kafka CR

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9859]
We should integrate the new version of the Quotas plugin (0.3.0) into Strimzi Cluster Operator and the Kafka CR in-sync with the [StrimziProposal#68](https://github.com/strimzi/proposals/blob/main/068-quotas-management.md)

**Comment by ppatierno** [comment]
Triaged on 21.3.2024: of course it has to be implemented taking into account the accepted proposal. @im-konge volunteered to work on this one.
