### ISSUE TITLE
Add unit tests for the Helm Chart

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9862]
We should try to add some unit tests for our Helm chart - for example using the https://github.com/helm-unittest/helm-unittest project.

**Comment by maciej-tatarski** [comment]
Hi @scholzj, I'm thinking about picking it up. I'm just wondering what should be granularity of the test, do we only want to test more complex scenarios when we use some helm functions and such or do we want to test all the functionalities?

Do we want to have it run on PR as well?

I've create this PR, as a conversation starter. If it is ok for you to do it in this way, I can add the rest of the test to it: https://github.com/strimzi/strimzi-kafka-operator/pull/10192

Example pipeline/workflow:
https://github.com/strimzi/strimzi-kafka-operator/actions/runs/9366458701/job/25783959894?pr=10192
