### ISSUE TITLE
[Bug]: Ensure that Kafka.KafkaStatus.ListenerStatus.type is NOT removed from CRD

### ISSUE THREAD

**Issue by pgodowski** [strimzi/strimzi-kafka-operator#9872]
### Bug Description

The [changelog of 0.38](https://github.com/strimzi/strimzi-kafka-operator/blob/main/CHANGELOG.md#0380) says:

The `Kafka.KafkaStatus.ListenerStatus.type` property has been deprecated for a long time, and now we do not use it anymore. **The current plan is to completely remove this property in the next schema version**. If needed, you can use the `Kafka.KafkaStatus.ListenerStatus.name` property, which has the same value.

In bold, marked the problematic statement that the filed will be **REMOVED** from the CRD - which is going to be a problem, in the scenario where on the same K8s cluster, there will be deployed the new & old version of the operator at the same time, in different namespaces.

The specific sequence which will be broken is that in `namespace-1` I would have Strimzi Operator in version which still has CRD with `Kafka.KafkaStatus.ListenerStatus.type` field and then one would install into `namespace-2` the newer version of the operator which CRD does not have this field anymore, leading to the field pruning - breaking the old operator instance.

This could be solved by at least adding `x-kubernetes-preserve-unknown-field: true` attribute into CRD, to prevent the field pruning.

The purpose of this issue (which is not really a bug _yet_) is to ensure that the community is aware about the real life scenarios of running multiple versions of Strimzi operator in different namespaces.

### Steps to reproduce

See a specific sequence above.

### Expected behavior

A customer is able to run both old and new version of the Strimzi operator in separate namespace, not interfering with each other.

### Strimzi version

main, 0.40

### Kubernetes version

OpenShift 4.12+

### Installation method

OLM

### Infrastructure

any

**Comment by scholzj** [comment]
I don't see how this is a bug:
* Running different Strimzi versions in the same Kubernetes cluster is always something what might work or might not work, depending on the exact versions and the exact changes between them. We do not recommend it in general.
* I guess you are misunderstanding what `The current plan is to completely remove this property in the next schema version.` means. It means it will be removed in the `v1beta3` (or `v1` or whatever is next) API. Not in the next Strimzi version. So removing it should not affect your old operator versions the way you describe (but given how the CRD versioning works, other things related to the CRD version change likely will).

**Comment by pgodowski** [comment]
OK - so as long as the removal means the new api version, then I think it shall be fine.
