### ISSUE TITLE
Creating KafkaTopic with replication factor more than available brokers

### ISSUE THREAD

**Issue by Ihjaz** [strimzi/strimzi-kafka-operator#990]
Hi,

If I create a kafkatopic with replicas as 3 while I have only one kafka broker then the topic-operator pod keeps restarting with the below error:

```
[2018-10-15 14:23:02,732] DEBUG <aseKafkaImpl:96> [oop-thread-6] Future KafkaFuture{value=null,exception=org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.,done=true} threw java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
[2018-10-15 14:23:02,733] ERROR <TopicWatcher:49> [oop-thread-6] Failure processing KafkaTopic watch event ADDED on resource topic12 with labels {strimzi.io/kind=topic}: Replication factor: 3 larger than available brokers: 1.
org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.
```
I was expecting the kafkatopic creation command to fail saying "replica is more than the number of brokers" but the command is going through and the pod is failing.

**Comment by scholzj** [comment]
Well, the Topic Operator shouldn't be restarting. 

However, the `kubectl create ...` command you use is actually talking only with Kubernetes. Not with the Topic Operator. So we cannot fail it. We would need to use aggregated API server for that which would be more complicated to setup etc.

**Comment by scholzj** [comment]
@stanlyDoge Is this fixed with your PR #1020?

**Comment by stanlyDoge** [comment]
@scholzj Yes. The TO is not restarted however, this message is printed every reconciliation. 
```
ERROR <opicOperator:368> [oop-thread-0] Error reconciling KafkaTopic myproject/my-topic
--
  | org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 4 larger than available brokers: 3.
```

**Comment by Lyndon-prequel** [comment]
I ran into this issue recently. To make it easier for others to figure out if they're affected, I created a common reliability enumeration (CRE). You can preview the rule [here](https://play.prequel.dev/?data=NoJgDCCsC0YxACCAuFBmALAGhATgGwC6CAogEpkDyZCA9gE4DmAdAIYAOrAxgBYCmzANasAZsOZdaAWym0Adsz716DAM7MAknIBurADYBLACZk%2B7Q11YAXA-IBi3KwxIAPLmZvzkCAKpzWAEZ6fAhOCPRmFtYhVvwInPQ2nnIIaKEGUnwAFKoAlN4AKnFWrEx8VuGRBpbJCCKODHQiqQiWcnK0FQEhEdz8RgjdlgCuqiHyegCeCACMgyqCSjm5CKU9fIwGqlZKfEbMAFAIWQwsHH0CwmKszE60euoFtOzVAMLSUqxyRrlAA&rule=E4VwNgpgzgXAUAAgQWgQY2BeScIJYAmMCAwgEoCiyATAAzUCsyt9DiuCUEAbhMHgBcAnsWrtcAwZGIBpAIYAzANZyEAI2AB7JXwSYADmDxo5kzQDsEAWzxQrptAAtxOEwIgBzTcBHXoUOQ8IZABHEAhw5H0tNUgrFyQ5EAFHb2IABUwwiDAEhAJoDDx9M3NiAB88pAB1RwhLFIh0CwU8DxBMAj0IQ2NTPAsEBTk0AW8h8dV5ZVUx-WN8KAQPTFNdFLkGuoQRgRA5MARzECs1XU0FdS0dYCW8Laa0MBAod2AAGgRplW79CDWCGAhEM5HgwEsxjsoFA2pZ9HJgJJSktNl0wJoPEsDEY3ANzMhMGAAQg%2BFpbgA6BAAFUctm6UHAAjucL4MNe9QECAA7gjzPdMQhJpYAAYASXM3AOhDIPRx-QsADFdt4KAAPNA9UrC7l1B5XbTrfjQBCQjD-dz4cxvcwHQXABAvPjIAqtcwQLpzYxQcl5EyOipVal1TA7EPmTSc%2BqaEAeRz6m4QzRDcCtMCHRqcP5oPCtd2-OWlEGjbyfaI8Dn8hCSoxdeGIwR4qEwjzmKwc715PBWeGjAMcHBqjXuysZuSSsFyWJNDQG27cwRx1S02O6bF9QvDYv2kyWSByD1J4ZgvOetDoVbIz5oCySY7Rpbojwk4BkqCfVEIfSaaF4KecPjcMYTQELYoAlI2Obng2JiHPc1q2qeSwABRGDozTmAybb2hcChcEydomsAmwBKMjavGsACU6CbOGnJnPm67uj6-Zdj2AgAMrXpgxAAGx5AIgSwIGqAqDMwkIEo4Zcvi0SaFO8T9jYkgePKZQIJU-ZIKgACyDhxuM6Jcus2xrrigybmM9qQqOoz7IcM43M0IBWp84xQDBTQgPoJrbN8qhPC8bwmkmIzXlYViaAQaw%2BU0y7BgxZmWBZ3jMRwSltKpnHeFgCBsP2mAKHw9QakJmkoAgjgCAI%2BiwAA9LVrz8FYABeeDkgMtUEJoaBQLVmh-ERlm9US7ivJ1sqaEI-IAMSyWgyBOJsHj8sgp4ErKfRQMgjXiZV1V1bVy0pCAajkmFDUCE1rW1bJX4BOCtWxHJtX2PctW0DxPGrf1xjrb0iXIMlwALY4S0QOSVgELtVU1TA9VHY4J1nZoVgXVdeBo12rXIKJKjIP1fCmN4tW2Ay0C1QAnBTtB5HI%2Bj-appWaagNptrIigqIGSC8LceLEAAzOSqriazOV%2BVzVasnzCAACxCy4bYCVFAnYBwSj3EQn5ZOEuQsZrAAyeBKOk3AACLpFSAAaDBKBQMh4GQ-MUJoABCFDaQA7HkoNQI4AvpBQ-MAFpWAAqmgFAKC7SjaR4-NKBT7ECKbABSVghOkACCeAABwKuxVLpKqISZ3IPEAIwAJohAAVvoaAAOJcnkQRqeXLigNIeR4ar-bllaveaVA0bABqxBmuSj7krjcjkmtBODd4gb2AITiD-2qDVuExAAETitW0obYlSpboOmp4jvQA) or run it against your logs [here](https://github.com/prequel-dev/preq).
