### ISSUE TITLE
[ST] System tests should collect init-container logs for failed tests

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9927]
Some of the System Tests using things such as node ports or rack awareness rely on the use of init-containers. But when the system test fails, the logs from the init containers are not collected. This would be a useful enhancement to collect them if the init container was used.

**Comment by see-quick** [comment]
Yeah, this seems reasonable 👍 .

**Comment by scholzj** [comment]
Discussed on the community call on 18.4.: Makes sense and should be done.
