### ISSUE TITLE
cluster-entity-operator does not inherit KUBERNETES_TRUST_CERTIFICATES env var

### ISSUE THREAD

**Issue by davecaplinger** [strimzi/strimzi-kafka-operator#993]
Per the recommendation in #544 I added `KUBERNETES_TRUST_CERTIFICATES` to the cluster operator yaml (`install/cluster-operator/050-Deployment-strimzi-cluster-operator.yaml`) and was able to successfully start `examples/kafka/kafka-ephemeral.yaml`, but the cluster-entity-operator pod that results appears to be in CrashLoopBackOff because its containers do not have the `KUBERNETES_TRUST_CERTIFICATES` environment variable. I can't see where I can change this; do you have any hints?

**Comment by stanlyDoge** [comment]
I think we can close this issue as the #1024 was closed.

**Comment by scholzj** [comment]
No, #1024 was resolved by using the proper certificate and thus not needing the option anymore. This issue still remains - for example for those who cannot change the certificate.

**Comment by scholzj** [comment]
Thanks to the PR #1920 the environment variables can be now set for all containers. That should allow to address this issue even in TO and UO. This issue can be closed now.
