### ISSUE TITLE
FAQ: Explain the permissions required for installation and runtime

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#995]
A number of people have wanted to know more detail about why the cluster operator appears to need cluster admin rights. We should write a FAQ entry for this.

**Comment by PaulRMellor** [comment]
We have an FAQ on this:
[Why do I need cluster administrator privileges to install Strimzi?](https://strimzi.io/docs/operators/in-development/using.html#co-faq-admin-privileges_str)
We also have a procedure on [Designating Strimzi administrators](https://strimzi.io/docs/operators/in-development/deploying.html#adding-users-the-strimzi-admin-role-str)

Closing the issue, as I think we're covered.
But maybe the details in the FAQ should sit with the procedure instead. Will investigate.
