### ISSUE TITLE
[Enhancement]: Improve tools/report.sh to make only the namespace required (make the cluster name optional)

### ISSUE THREAD

**Issue by tyamashi-oss** [strimzi/strimzi-kafka-operator#9969]
### Related problem

- Currently, the cluster name is required for tools/report.sh. Also, for Bridge, Connect, and MM2, if they are not specified, there is no information about them, and it is not possible to specify multiple them at the same time.
- Many other reporting tools, such as OpenShift, only specify the namespace. However, the current tools/report.sh requires the exact names of the cluster, Bridge, Connect, and MM2 to get those information. So mistakes are common.

### Suggested solution

It would be useful for usability and customer satisfaction if cluster names were not required and only namespace should be specified.

**Comment by scholzj** [comment]
Discussed on the community call on 18.4.: Scraping any data by default would not be secure as it might lead to users collecting and publicly sharing more data than they intended when raising issues or asking for help. So removing the cluster option does not seem like a secure idea. One option would be to have a dedicated option required to be specified when scraping all data. But the report tool seems to have very little use in Strimzi and does not seem to justify the effort into this. This should be rejected.
