### ISSUE TITLE
[Docs]: Add compatibility matrix table to docs

### ISSUE THREAD

**Issue by smyja** [strimzi/strimzi-kafka-operator#9973]
### Suggestion / Problem

People have to go through each releases in the repo to see the note on the kubernetes version when it could be a table showing each strimzi version and their kubernetes support range the way other cncf projects do it.

**Comment by scholzj** [comment]
There is no compatibility matrix. There is the minimal supported / tested version that is listed in the docs. And if needed, any further limitations are listed on the website, where it is easier to maintain as new Kubernetes versions come up with possible API changes etc.

**Comment by smyja** [comment]
Okay

**Comment by scholzj** [comment]
FYI: It is in the Downloads page in case you were looking for it: https://strimzi.io/downloads/

**Comment by smyja** [comment]
Awesome, thanks!
